### ISSUE TITLE
getAlbums & getArtistAlbums 请求不到数据

### ISSUE THREAD

**Issue by AD-feiben** [Binaryify/NeteaseCloudMusicApi#10]
![image](https://cloud.githubusercontent.com/assets/19575477/23697612/605fb8c2-0423-11e7-90f2-3a1a48e9037d.png)

![image](https://cloud.githubusercontent.com/assets/19575477/23697620/69de44ae-0423-11e7-9a00-1c9a0613fa65.png)

请大神指教

**Comment by Binaryify** [comment]
如果是个别的出现这种情况,就是有版权的音乐

**Comment by AD-feiben** [comment]
都查不到

**Comment by Binaryify** [comment]
@AD-feiben  
你请求头不对,不能直接浏览器获取数据的,我这个项目就是构造头再去请求数据的
![image](https://cloud.githubusercontent.com/assets/12221718/23819163/78aa64c4-063d-11e7-9759-c599817bb7e3.png)

**Comment by AD-feiben** [comment]
原来如此，谢谢
