### ISSUE TITLE
视频返回的id是数字，与视频URL接口中要求的ID好像不一样

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#1004]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
![视频-down](https://user-images.githubusercontent.com/45870098/97375290-6c6bf280-18f5-11eb-8195-a71b06fee360.png)
![视频-mv](https://user-images.githubusercontent.com/45870098/97375292-6d9d1f80-18f5-11eb-8f61-a44ed1e3a58b.png)
![视频-id](https://user-images.githubusercontent.com/45870098/97375296-6ece4c80-18f5-11eb-83e5-0531ba399f65.png)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
<请清晰描述现在的效果和期待的效果>  
![视频页面](https://user-images.githubusercontent.com/45870098/97375325-81488600-18f5-11eb-8283-500cb51ccf24.png)

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
mv和视频不一样，mv的得调/mv/url?id=5436712接口

**Comment by gyjcode** [comment]
> mv和视频不一样，mv的得调/mv/url?id=5436712接口

视频的呢？

**Comment by Binaryify** [comment]
视频的不就是你截图那个吗

**Comment by gyjcode** [comment]
> 视频的不就是你截图那个吗

麻烦问下，获取视频列表的接口是哪个？

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/97422759-3b1d1200-1949-11eb-92cf-b7821bfb30bd.png)

**Comment by gyjcode** [comment]
不知道是不是我设置的问题，/video/group?id=9104好像最多获取 8 个视频，而且不能获取全部视频

**Comment by Binaryify** [comment]
/video/group 每次调用数据都不一样的，每次给8条数据

**Comment by gyjcode** [comment]
> /video/group 每次调用数据都不一样的，每次给8条数据

麻烦问下，这里的api是哪个？这样的话应该不是这个每次8条的接口了
![视频](https://user-images.githubusercontent.com/45870098/97653645-3fa60f80-1a9c-11eb-98ff-65be54fb7a8e.png)

**Comment by Binaryify** [comment]
这个是用的app的接口，和app的保持一致

**Comment by gyjcode** [comment]
> 这个是用的app的接口，和app的保持一致，每次滚动到底部就调接口带上随机数

好的，感谢
