### ISSUE TITLE
post请求带上cookie后请求song URL出现TypeError

### ISSUE THREAD

**Issue by Clarkkkk** [Binaryify/NeteaseCloudMusicApi#1005]
## 环境
- 系统/平台: centOS

- nodejs 版本: v12.19.0

- API版本: 3.45.1

## 出现问题
post请求带上cookie后请求song URL出现TypeError。

## 重现步骤
使用的接口是`/song/url`，请求方式：
```
fetch(requestURL, {
    method: 'post',
    headers: {'Content-Type': 'application/json;charset=utf-8'},
    body: {
         credentials: 'include',
         cookie: cookie,
    }
  })
```
错误信息是`TypeError: Cannot use 'in' operator to search for 'MUSIC_U' in...`。知道有[相关的isuue](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/812)，可能是请求方式不同？在[song_url.js](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/song_url.js)中加入：
```
const { cookieToJson } = require('../util/index')
if(typeof query.cookie === 'string'){
    query.cookie = cookieToJson(query.cookie)
}
```
已经解决，来回报一下。

**Comment by Binaryify** [comment]
确实疏忽了这个,抽空改一下
