### ISSUE TITLE
提供[忽略证书效验]的选项

### ISSUE THREAD

**Issue by if1y** [Binaryify/NeteaseCloudMusicApi#1006]
**功能描述**
- 因为支持 proxy 配置，于是尝试搭配 UnblockNeteaseMusic 使用，企图制作成一个有魔法力量~~可以解锁~~的 API，但由于 UnblockNeteaseMusic 使用了自己的证书，这边访问会无法成功。
- 所以想问问有没有办法忽略证书效验，或者增加这个参数选项？

**Comment by Binaryify** [comment]
这个我不太清楚，要不你问UnblockNeteaseMusic作者

**Comment by nondanee** [comment]
```sh
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
