### ISSUE TITLE
非后台开发人员，有个疑问

### ISSUE THREAD

**Issue by Cvilia** [Binaryify/NeteaseCloudMusicApi#1007]
我终端调用部分接口的时候比如创建歌单，其实是依赖用户进行创建的，但是接口并没有传入任何参数，最终无法确认该歌单的归属，还是我调用的时候弄错了呢

**Comment by Cvilia** [comment]
但是我在创建歌单的时候有些字段比如creator是null的，但是userId却是当前登录用户的id，这个是怎么做到关联的呢？

**Comment by Cvilia** [comment]
并且无论我header里面加不加token最终好想都能准确的找到我的userId

**Comment by Binaryify** [comment]
cookies
