### ISSUE TITLE
获取精品歌单无法分页

### ISSUE THREAD

**Issue by trazyn** [Binaryify/NeteaseCloudMusicApi#101]
### 环境
系统:  mac

nodejs 版本:v6.11

### 出现问题
获取精品歌单无法分页

### 重现步骤
```
GET /top/playlist/highquality?limit=60&offset=30 
```
### 期待效果
获取分页内容

**Comment by Binaryify** [comment]
还在查原因

**Comment by JamieMaple** [comment]
这个好像没法传 cat 和 limit 以外的参数（比如offset），而且文档上有点问题：
> `limit`: 取出评论数量,默认为20
这个应该是限制条目数吧~

然后还有点问题就是有些 cat 请求的数据量比较少，比如日语我只请求到了11条欸

**Comment by JamieMaple** [comment]
然后非常希望有些接口参数能写全，比如某些接口的 limit 啥的 =)

**Comment by Binaryify** [comment]
@JamieMaple 
有哪些接口的文档不够完整的,能不能说下

**Comment by uura** [comment]
@Binaryify 
精品歌单接口的`offset`在文档中没有体现，是可用参数吗？
`limit`在超过100的时候返回的`playlists`长为100，如果没有`offset`参数就做不了大数额的分页了。

ps, 使用文档里面的 “获取精品歌单”里面对 `limit` 的参数描述

> 取出评论数量

应当改为

> 取出歌单数量

**Comment by Binaryify** [comment]
@uura 主要加了也没用,试过了,具体原因还不知道,感谢对文档错误的反馈
