### ISSUE TITLE
部分用户动态数据的size和events的最大长度不一致

### ISSUE THREAD

**Issue by Liuhongwei3** [Binaryify/NeteaseCloudMusicApi#1010]
## 环境
- 系统/平台: Windows

- nodejs 版本: 12.18.1

- API版本: 3.45.2

## 出现问题
当我访问`http://localhost:3000/user/event?uid=1750956524&limit=35`的时候，获取的`size`信息与获得的所有`events`的数据长度不一致，比如上面的链接中的用户，目前获得的最多动态数只有22，而官方网易云里面,有所有的35条数据；同时后面发现不是所有的用户都是这样，部分用户而已，但不知道原因。

## 重现步骤
访问`http://localhost:3000/user/event?uid=1750956524&limit=35`

## 期待效果
理论上`size`和获取到的所有`events`的长度一致，希望有空可以帮忙看看，非常感谢！

**Comment by Liuhongwei3** [comment]
经过仔细将网易云网页版和客户端进行了比较，发现该接口获取的数据和网页版的一致（有22条），但是和客户端不一致（有32条），这个结果不知道为什么会这样，会不会客户端用的另一个接口？

**Comment by Liuhongwei3** [comment]
同时该接口`/user/event`中：
`type`参数：
- `35`时对应`发布动态`
- `21`时对应`分享MV`

**Comment by Binaryify** [comment]
这个我抽空再看看，昨天我换成了手机的api，但是还是一样，不知道是哪里的参数的差异导致的

**Comment by Liuhongwei3** [comment]
又看了下应该少的是`Mlog`部分的内容，希望能帮到~

**Comment by Binaryify** [comment]
好

**Comment by Binaryify** [comment]
好了,是接口会检测客户端版本,只返回支持的内容的问题
