### ISSUE TITLE
获取歌曲详情时传入ids参数过多报错

### ISSUE THREAD

**Issue by toolse** [Binaryify/NeteaseCloudMusicApi#1011]
报错内容 net::ERR_CONNECTION_CLOSED  ，限制数量后无报错

**Comment by Liuhongwei3** [comment]
我之前也遇到这个问题，但是其实也没必要一次传那么多`id`过去，因为一方面会显得请求很臃肿，另一方面其实可能用户也用不到这么多数据就会造成请求浪费了；
目前我的歌单页面获取所有歌曲就是采用分页的方式避免了这个问题，建议参考该页面[歌单详情](http://tadm.gitee.io/tadmplayer/#/detail)

**Comment by 1206993746** [comment]
> 我之前也遇到这个问题，但是其实也没必要一次传那么多`id`过去，因为一方面会显得请求很臃肿，另一方面其实可能用户也用不到这么多数据就会造成请求浪费了；
> 目前我的歌单页面获取所有歌曲就是采用分页的方式避免了这个问题，建议参考该页面[歌单详情](http://tadm.gitee.io/tadmplayer/#/detail)

谢谢，但是我对这个评论传参有点不太理解，就是以下

offset: 偏移数量 , 用于分页 , 如 :( 评论页数 -1)*20, 其中 20 为 limit 的值
before: 分页参数,取上一页最后一项的 time 获取下一页数据(获取超过5000条评论的时候需要用到)

**Comment by Liuhongwei3** [comment]
> > 我之前也遇到这个问题，但是其实也没必要一次传那么多`id`过去，因为一方面会显得请求很臃肿，另一方面其实可能用户也用不到这么多数据就会造成请求浪费了；
> > 目前我的歌单页面获取所有歌曲就是采用分页的方式避免了这个问题，建议参考该页面[歌单详情](http://tadm.gitee.io/tadmplayer/#/detail)
> 
> 谢谢，但是我对这个评论传参有点不太理解，就是以下
> 
> offset: 偏移数量 , 用于分页 , 如 :( 评论页数 -1)*20, 其中 20 为 limit 的值
> before: 分页参数,取上一页最后一项的 time 获取下一页数据(获取超过5000条评论的时候需要用到)

感觉描述的很清楚了，你可以按照文档结合例子去理解的，我的评论数据都是直接上拉然后只修改limit，没用到太多的数据就没去测试另外的参数

**Comment by 1206993746** [comment]
> > > 我之前也遇到这个问题，但是其实也没必要一次传那么多`id`过去，因为一方面会显得请求很臃肿，另一方面其实可能用户也用不到这么多数据就会造成请求浪费了；
> > > 目前我的歌单页面获取所有歌曲就是采用分页的方式避免了这个问题，建议参考该页面[歌单详情](http://tadm.gitee.io/tadmplayer/#/detail)
> > 
> > 
> > 谢谢，但是我对这个评论传参有点不太理解，就是以下
> > offset: 偏移数量 , 用于分页 , 如 :( 评论页数 -1)*20, 其中 20 为 limit 的值
> > before: 分页参数,取上一页最后一项的 time 获取下一页数据(获取超过5000条评论的时候需要用到)
> 
> 感觉描述的很清楚了，你可以按照文档结合例子去理解的，我的评论数据都是直接上拉然后只修改limit，没用到太多的数据就没去测试另外的参数

就是不太懂offset和before说的是啥，个人觉得不太好理解，我看了一下示例上也没有offset和before相关的演示
