### ISSUE TITLE
调用新版评论接口时报错

### ISSUE THREAD

**Issue by 1206993746** [Binaryify/NeteaseCloudMusicApi#1014]
传递的ID为搜索接口中视频类的ID

报错内容：
“java.lang.Exception: illegal resourceId!"
"code": 400

**Comment by Binaryify** [comment]
应该是你传错id了，另外网易这边视频和mv不一样
http://localhost:3000/comment/new?id=89ADDE33C0AAE8EC14B99F6750DB954D&type=5&sortType=99
![image](https://user-images.githubusercontent.com/12221718/98091281-29df8280-1ec0-11eb-8e09-bebb699d2e4b.png)

**Comment by 1206993746** [comment]
发现了，谢谢
