### ISSUE TITLE
私信接口有分享歌曲么

### ISSUE THREAD

**Issue by heiheiyo-001** [Binaryify/NeteaseCloudMusicApi#1016]
你好 我看私信有两接口 发信息或者分享歌单 有没有分享歌曲的 我试了个 type = song 但是 不管什么歌都返回说资源不能分享

**Comment by Binaryify** [comment]
摸索了好久,把`query.cookie.os = 'pc'`注释就行

**Comment by heiheiyo-001** [comment]
> 摸索了好久,把`query.cookie.os = 'pc'`注释就行,晚点我更新下

嘿嘿 感谢

**Comment by heiheiyo-001** [comment]
> 摸索了好久,把`query.cookie.os = 'pc'`注释就行,晚点我更新下

现在我用这接口 都是返回 {"code":250,"msg":"发送私信异常","data":{"dialog":{"title":"风险提示","subtitle":"请您尝试切换网络或设备再尝试操作哦~","buttonMsg":"查看详情","buttonUrl":"http://163.lu/EmUzy2"}}}  其它两个接口使用正常 你那边会有这个情况么

**Comment by Binaryify** [comment]
我这边不会,你重启下路由器看看

**Comment by heiheiyo-001** [comment]
你是用的user_ids=1测试么 这个我也正常 可能因为是官方号 发给其它用户就提示上面那个

**Comment by Binaryify** [comment]
我这边也出现了,我看看

**Comment by heiheiyo-001** [comment]
嘿嘿 好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上7:59
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
我这边也出现了,我看看

**Comment by Binaryify** [comment]
好了

**Comment by heiheiyo-001** [comment]
老哥 666！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上8:05
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
好了

**Comment by heiheiyo-001** [comment]
对哟 最近有个  抱一抱  类似于点赞 但是现在只能在手机端操作 老哥有空可以研究下下

**Comment by heiheiyo-001** [comment]
好像不太对 手动发的话 对方是能收到的 用接口发了之后自己那有发的记录 但是对方那不会收到~

**Comment by Binaryify** [comment]
同一首歌或者歌单只能发一次的

**Comment by heiheiyo-001** [comment]
哦哦 可能是那个号的问题 我换了个号就行

**Comment by Binaryify** [comment]
抱一抱的抓到了,下周我再更新,你可以先试试
抱一抱对应评论列表:
```js
module.exports = (query, request) => {
  query.cookie.os = 'ios'
  query.cookie.appver = '7.3.27'
  const data = {
    targetUserId: 285516405,
    commentId: 1167145843,
    cursor: '-1',
    threadId: 'R_SO_4_863481066',
    pageNo: 1,
    idCursor: -1,
    pageSize: 100,
  }
  return request(
    'POST',
    `https://music.163.com/api/v2/resource/comments/hug/list`,
    data,
    {
      crypto: 'api',
      cookie: query.cookie,
      proxy: query.proxy,
      realIP: query.realIP,
    },
  )
}
```
抱一抱评论:
```js
module.exports = (query, request) => {
  query.cookie.os = 'ios'
  query.cookie.appver = '7.3.27'
  const data = {
    targetUserId: '285516405',
    commentId: '1167145843',
    threadId: 'R_SO_4_863481066',
  }
  return request(
    'POST',
    `https://music.163.com/api/v2/resource/comments/hug/listener`,
    data,
    {
      crypto: 'api',
      cookie: query.cookie,
      proxy: query.proxy,
      realIP: query.realIP,
    },
  )
}
```

**Comment by heiheiyo-001** [comment]
哇 厉害 这好迅速呀

**Comment by heiheiyo-001** [comment]
读取通知私信那接口中有个参数newMsgCount是指新消息的数量 但读取了私信之后 这个参数好像不会变 即使用了另外个带uid的私信内容接口也不会变 这个有没有啥办法解决

**Comment by Binaryify** [comment]
应该还有个接口用来标记私信是否已读

**Comment by Binaryify** [comment]
晚点我抓下包

**Comment by heiheiyo-001** [comment]
抱一抱评论 那个接口我试了 有点疑惑那两个参数 targetUserId这个参数如果传对方的会返回 {"code":200,"data":{"resultMap":{"isHugSuccess":true}}}  如果传自己的就是 {"code":200,"data":{"resultMap":{}}}  、两者结果都一样  
还有个就是 抱了之后再去评论那看确实是抱了 但是被抱的没有收到通知  不知道是不是 threadId 这个参数的原因？ 我试了这个貌似是必需参数

**Comment by Binaryify** [comment]
threadId是资源id必传的

**Comment by heiheiyo-001** [comment]
这里的资源id是从哪里获取的

**Comment by Binaryify** [comment]
参考 comment_new.js
![image](https://user-images.githubusercontent.com/12221718/98891827-f8774000-24d9-11eb-9800-eddc235c2012.png)

**Comment by heiheiyo-001** [comment]
抱抱接口试过好像没啥问题了

**Comment by Binaryify** [comment]
分页还有点问题,不知道是不是网易那边写死了pageSize100

**Comment by heiheiyo-001** [comment]
应该是吧 我之前试了最多100 我就直接用100 然后用参数before来拿了

**Comment by Binaryify** [comment]
已更新~

**Comment by heiheiyo-001** [comment]
咦 文件都提了？

**Comment by Binaryify** [comment]
o.o我漏合到master分支了

**Comment by Binaryify** [comment]
好了

**Comment by heiheiyo-001** [comment]
0-0 ok了

**Comment by heiheiyo-001** [comment]
老哥一般怎么抓包的 想学习一波~

**Comment by Binaryify** [comment]
@heiheiyo-001 
https://github.com/nondanee/UnblockNeteaseMusic/

**Comment by heiheiyo-001** [comment]
老哥 那个抱一抱接口最近有改么 好像抱了 会返回成功 但实际上没成功~ 有空帮忙看看？

**Comment by Binaryify** [comment]
@heiheiyo-001 缓存

**Comment by heiheiyo-001** [comment]
我是有带最新时间戳的参数 还有其它方面的缓存么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午9:47
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
@heiheiyo-001 缓存

**Comment by heiheiyo-001** [comment]
我更新好像可以了 我再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午9:47
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
@heiheiyo-001 缓存

**Comment by heiheiyo-001** [comment]
有点奇怪 有个号用接口就是抱不成功其它号可以 但手机去操作都可以~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午9:47
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
@heiheiyo-001 缓存

**Comment by heiheiyo-001** [comment]
老哥有空帮忙抓下手机端抱一抱的包看看有啥改变不 还是不太整的明白




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午9:47
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"0_-0"<1849289659@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 私信接口有分享歌曲么 (#1016)





 
@heiheiyo-001 缓存
