### ISSUE TITLE
有没有网易云网页搜索歌曲在客户端播放的接口

### ISSUE THREAD

**Issue by Rumenglw** [Binaryify/NeteaseCloudMusicApi#1019]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
网易云url protocal播放音乐的的接口，在官网里有个下载歌曲，点击已下载客户端会自动打开本地的windows版网易云exe下载。
这个接口是orpheus://btoa({"type:song","id":"musicid","cmd":"download"}) 里面参数转为base64编码
想找一个能直接在网易云播放的接口
自己尝试过orpheus://btoa({"type:song","id":"musicid","cmd":"play"}) ，没有效果。

请问有没有大佬懂这个

最终实现效果类似ios里的捷径，

**Comment by Binaryify** [comment]
手机的可以，PC貌似没对应的

**Comment by Rumenglw** [comment]
> 手机的可以，PC貌似没对应的

多谢大佬回答，十分感激。
因为有个场景想让网易云自己播音乐，只给它传歌的id，但找了半天，其他酷狗、qq音乐什么的很好找调用。
安卓和苹果里因为有推广app的需要，有网页打开app的需要，pc上除了下载什么都没有。
貌似网易云当年被注入劫持搞晕圈了，把接口全关了，也不知道怎么给它的exe传参 0.0 
我再把issue挂一周吧，如果我还是没有找到办法，再来关issue  0.0

**Comment by Binaryify** [comment]
嗯
