### ISSUE TITLE
/recommend/resource 接口数据返回错误

### ISSUE THREAD

**Issue by weapon-xx** [Binaryify/NeteaseCloudMusicApi#102]
### 环境
系统:  Mac 

nodejs 版本: 8.4.0

### 出现问题
请求推荐歌曲接口: /recommend/resource，接口返回 {"msg":null,"code":301}

### 重现步骤
直接请求可以重现，怀疑是接口换了

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/30153000-a07e9464-937a-11e7-9dec-4aa3fcbaf6c7.png)

**Comment by weapon-xx** [comment]
非常感谢~
