### ISSUE TITLE
Android端调用登录接口问题

### ISSUE THREAD

**Issue by minamihoshi** [Binaryify/NeteaseCloudMusicApi#1021]
## 环境
- 系统/平台: Android 

- nodejs 版本: 无

## 出现问题
调用登录接口 code 401  msg：接口未加密，不允许访问
请问该如何正确调用
感谢！

**Comment by Binaryify** [comment]
重现步骤不够清晰

**Comment by minamihoshi** [comment]
我在Android中 请求api 
https://music.163.com/api/login/cellphone?phone=xxx&md5_password=xxx
错误码为401 
不知道是不是不能这样直接请求 正确的方式是什么

**Comment by Binaryify** [comment]
不是这样调的,你这样直接调官方接口肯定不行的,你得搭我这个项目再根据文档调用

**Comment by minamihoshi** [comment]
@Binaryify 可以通过自己实现这个加密方式做到么 项目中是否有可以参考的代码
