### ISSUE TITLE
like接口返回200 但是好像没有从喜欢列表中删除

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#1027]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
<请清晰描述现在的效果和期待的效果>  

![image](https://user-images.githubusercontent.com/45870098/99075349-4b451a80-25f4-11eb-8eb2-5380db85192e.png)
![image](https://user-images.githubusercontent.com/45870098/99075408-62840800-25f4-11eb-869f-e8b7340bb9ea.png)

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
调用前须知看了吗

**Comment by gyjcode** [comment]
![image](https://user-images.githubusercontent.com/45870098/99144935-31174500-26a5-11eb-9180-34f5b1193181.png)
我再查查原因吧，感谢

**Comment by Binaryify** [comment]
更新一下看看

**Comment by gyjcode** [comment]
> 更新一下看看,另外随机数是要加到url而不是body的data里

好的，感谢
