### ISSUE TITLE
获取专辑详情接口里获取的歌手的 img1v1Url 不正确

### ISSUE THREAD

**Issue by qier222** [Binaryify/NeteaseCloudMusicApi#1029]
`/album` API 获取到的 album.artist.img1v1Url、album.artists[0].img1v1Url 全都是同一个url (https://p1.music.126.net/VnZiScyynLG7atLIZ2YPkw==/18686200114669622.jpg) ，并不是歌手的头像。

`curl "http://127.0.0.1:3000/album?id=38033898"`
`curl "http://127.0.0.1:3000/album?id=96441683"`

**Comment by Binaryify** [comment]
歌手头像不是这样拿的

**Comment by qier222** [comment]
我知道可以通过 `/aritst` 获取歌手头像，但是看到专辑里有这个字段，所以就试试看。如果不是 bug 的话，可以关闭这个 issue 。
