### ISSUE TITLE
top/album 接口limit 参数无效 

### ISSUE THREAD

**Issue by Big0range** [Binaryify/NeteaseCloudMusicApi#1031]
## 环境
- 系统/平台: windows

- nodejs 版本: 14

- API版本: 3.47.2
## 出现问题
top/album 接口limit 参数无效 
所有参数都试了  返回的数据量超大

## 重现步骤
{ host }/top/album?limit=10
## 期待效果
期待只返回十条数据

![1605689356(1)](https://user-images.githubusercontent.com/53934673/99507199-0c311380-29be-11eb-94e0-cf8436afc774.png)

**Comment by Binaryify** [comment]
年月都带上吧,我看官方的就是这样的

**Comment by Big0range** [comment]
> 年月都带上吧,我看官方的就是这样的,limit无效

/top/album?offset=0&limit=1&year=2019&month=6
都带上了,不知道为什么还是不行

**Comment by Binaryify** [comment]
什么不行

**Comment by Big0range** [comment]
> 什么不行?limit?官方的就是这样的，你可以抓包看看，就是返回一大串数据的

 好吧,也许就这样吧  limit是1,返回了上千条数据
![1605770536(1)](https://user-images.githubusercontent.com/53934673/99634243-19f89e80-2a7b-11eb-8de0-b1b702fbd803.jpg)
