### ISSUE TITLE
通过歌手id查询到对应的用户id

### ISSUE THREAD

**Issue by kotle** [Binaryify/NeteaseCloudMusicApi#1035]
**功能描述**
对于那些在网易云注册了用户的歌手，希望有个接口可以通过歌手id查询到歌手的用户id。
获取歌曲的时候一般会返回歌手的id，查询歌手的信息歌曲是使用的歌手id，但是点击查看动态的时候是需要用户id的。

**Comment by Binaryify** [comment]
好了,加上了
