### ISSUE TITLE
可以解锁灰色歌曲资源吗

### ISSUE THREAD

**Issue by sdu-yyq** [Binaryify/NeteaseCloudMusicApi#1036]
**功能描述**
- 本项目能结合 [https://github.com/nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic) 此项目吗？实现自动替换灰色歌曲

**Comment by lxhcool** [comment]
我也想要哈哈哈

**Comment by JackuXL** [comment]
同求

**Comment by AU-Linsanity** [comment]
同求

**Comment by lxhcool** [comment]
我已经把不能放的过滤了

**Comment by iwxyi** [comment]
> 我已经把不能放的过滤了

怎么判断哪些歌不能放呢？

**Comment by xlz122** [comment]
> > 我已经把不能放的过滤了
> 
> 怎么判断什么歌不能放呢？

歌单详情接口下边，有个privileges数组，里边有个cp参数就是有无版权。可以通过对比tracks数组id，来判断这首歌有没有版权
