### ISSUE TITLE
simi/artist接口问题返回301

### ISSUE THREAD

**Issue by naughtyB** [Binaryify/NeteaseCloudMusicApi#104]
### 环境
系统:  Windows 7

nodejs 版本:6.11.0

### 出现问题
相似歌手，相似歌曲这些接口均返回301
### 期待效果

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/30577941-ea44c6b2-9cd6-11e7-8a34-9c6baa0a7753.png)

**Comment by naughtyB** [comment]
谢谢大佬
