### ISSUE TITLE
使用搜索接口中的歌词时数据出错

### ISSUE THREAD

**Issue by Chaste1ove99** [Binaryify/NeteaseCloudMusicApi#1040]
## 环境
- 系统/平台: mac os

- nodejs 版本: v14.11.0

- API版本: 3.45.3

## 出现问题
搜索接口的获取的歌词数据错误

## 重现步骤
<img width="898" alt="截屏2020-12-01 下午5 00 34" src="https://user-images.githubusercontent.com/72717435/100719142-34c20000-33f7-11eb-823d-3d7d1e9ac85b.png">
使用搜索接口进行搜索时 输入关键词iu type为1006 limit为30  输入的域名为cloudsearch 搜索歌词后
得到的返回数据如下
<img width="193" alt="截屏2020-12-01 下午5 03 37" src="https://user-images.githubusercontent.com/72717435/100719207-4acfc080-33f7-11eb-9e86-5f81b52b97b3.png">
这里显示songCount 有几百条数据 但实际添加翻页功能后 输入不同的offset后返回的数据出现了错误 
下面是输入offset 为90时 接口已经不返回songs数组 songCount也为0 而最初的返回数据中songCount为297
<img width="225" alt="截屏2020-12-01 下午5 09 19" src="https://user-images.githubusercontent.com/72717435/100719715-f842d400-33f7-11eb-87b6-d9ff5503e2b3.png">

使用网易云音乐macos客户端进行歌词搜索后,发现一样的BUG存在,实际上最多返回两组limit为30的songs数据,网易云音乐mac客户端搜索歌词也存在翻页的BUG。

## 期待效果
如果能把全部songs数据获取到最好,或者将SongCount的值和songs总数进行校正.

**Comment by Chaste1ove99** [comment]
这里使用的搜索是cloudsearch而非search

**Comment by Binaryify** [comment]
app是否存在一样的问题

**Comment by Chaste1ove99** [comment]
使用网易云音乐IPhone客户端搜索歌词功能也最多获取到60条数据,但由于手机端是触底刷新,所以在翻页功能上不存在BUG。

后来测试网页端同样是这个问题,最初获取的SongCount和实际数据条数不符,翻到第三页时直接显示数据条数为0,总页数直接变为2页
<img width="957" alt="截屏2020-12-03 下午2 27 54" src="https://user-images.githubusercontent.com/72717435/100972423-bdfe4180-3573-11eb-846e-b333d15f7883.png">
这个接口最多可以提供60条数据,而不是最初请求时SongCount的数量。

**Comment by Binaryify** [comment]
官方接口这样的话我这边也没什么办法，交互上做成滚动加载吧，more为false就没有下一页了

**Comment by Chaste1ove99** [comment]
我向CH的人反映了这个问题,等待他们修复吧

**Comment by Binaryify** [comment]
嗯
