### ISSUE TITLE
希望可以增加支持原生android（retrofit 调用）

### ISSUE THREAD

**Issue by ARookieOfProgramming** [Binaryify/NeteaseCloudMusicApi#1041]
**希望可以android 端调用**
- android端调用，文档接口里面没有返回值参数，不知道怎么接收返回值

**Comment by Binaryify** [comment]
搭一个后台不是更方便吗，不可能安卓要调用我就写个java的，ios要调用我就写个swift的吧

**Comment by hahaha28** [comment]
什么鬼，这和是不是安卓调用有什么关系，不是一样用吗，返回值自己去看啊
