### ISSUE TITLE
获取用户歌单时第一次请求出错

### ISSUE THREAD

**Issue by Chaste1ove99** [Binaryify/NeteaseCloudMusicApi#1046]
## 环境
- 系统/平台: mac os
- nodejs 版本: 14.11.0

- API版本: 3.45.3

## 出现问题
请求用户歌单时返回数据长度与limit值不符

## 重现步骤
使用获取用户歌单接口 输入以下参数 其中limit为24
<img width="266" alt="截屏2020-12-07 下午5 07 49" src="https://user-images.githubusercontent.com/72717435/101331783-69c6ca80-38af-11eb-8056-fb4ce90480d4.png">
获得的返回数据中数据长度为25 
<img width="128" alt="截屏2020-12-07 下午5 13 54" src="https://user-images.githubusercontent.com/72717435/101331935-a0044a00-38af-11eb-81d1-23fe4a8b34a2.png">

但添加了翻页功能后,后面的数据获取正常

## 期待效果
将第一次获取的数据的长度校正为发送的参数limit的值

**Comment by Clarkkkk** [comment]
第一个歌单是用户的红心歌单

**Comment by Chaste1ove99** [comment]
对的 但是这样会对翻页造成很大影响 总不能第一页获取25个数组对象 第二页就24个吧 而且红心歌单本质上和一般歌单也没什么区别

**Comment by Clarkkkk** [comment]
> 对的 但是这样会对翻页造成很大影响 总不能第一页获取25个数组对象 第二页就24个吧 而且红心歌单本质上和一般歌单也没什么区别

神奇的是，红心歌单不会影响offset，所以你offset一直加24就行

**Comment by Binaryify** [comment]
这是网易那边的设定

**Comment by Chaste1ove99** [comment]
好的 这个可以close啦
