### ISSUE TITLE
[Feature Requested] 云盘歌曲信息匹配纠正

### ISSUE THREAD

**Issue by AgFlore** [Binaryify/NeteaseCloudMusicApi#1047]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图

在2020年9月16日发布的手机版APP（安卓7.3.10版）中，新增了一个自助的云盘歌曲信息匹配纠正的功能，用户可以自主选择将未正确匹配的歌曲手动匹配至某条曲库中存在的曲目，或是将错误与曲库中歌曲匹配的文件与曲库脱钩。感觉可以抓下包实现出来。

**Comment by Binaryify** [comment]
暂时抓不到

**Comment by Binaryify** [comment]
新版本已经加上这个接口了
