### ISSUE TITLE
使用POST请求发送私信请求结果错误

### ISSUE THREAD

**Issue by Chaste1ove99** [Binaryify/NeteaseCloudMusicApi#1048]
## 环境
- 系统/平台: mac os

- nodejs 版本: 14.11.0

- API版本: 3.45.3

## 出现问题
使用发送私信接口时 返回结果数组中元素toUser属性错误

## 重现步骤
使用发送私信接口获取过去聊天记录时,发送请求请求参数如下 请求方式为POST
<img width="229" alt="截屏2020-12-08 上午10 12 26" src="https://user-images.githubusercontent.com/72717435/101429572-38e1a680-393e-11eb-8667-d96794dfd418.png">

结果中获取到的数组元素中toUser对象和fromUser对象的userId值相同
<img width="236" alt="截屏2020-12-08 上午10 11 01" src="https://user-images.githubusercontent.com/72717435/101429338-b0630600-393d-11eb-8f0d-f0a70bbe80be.png">
<img width="231" alt="截屏2020-12-08 上午10 11 33" src="https://user-images.githubusercontent.com/72717435/101429374-c244a900-393d-11eb-913f-670910fe6dac.png">

换到get请求方式后,结果数组中第一个元素的toUser和FromUser的userId属性正常（但是这里字符串的部分建议改为number）
后面的数组元素依然存在着上述BUG 即toUser和FromUser的userId值仍然相等

下图为get请求结果第一个数组元素
<img width="240" alt="截屏2020-12-08 上午10 20 42" src="https://user-images.githubusercontent.com/72717435/101429990-1d2ad000-393f-11eb-9c29-b8df65b594a5.png">

<img width="250" alt="截屏2020-12-08 上午10 20 51" src="https://user-images.githubusercontent.com/72717435/101429972-113f0e00-393f-11eb-89d2-d60fc9fa1b29.png">

## 期待效果
将两种请求方式结果数组元素中的toUser对象和FromUser对象的userid属性修改正确,并且将数据形式修改为number

**Comment by Binaryify** [comment]
post 的url每次有带上时间戳吗
