### ISSUE TITLE
获取歌单详情这个api失效了，希望修复下

### ISSUE THREAD

**Issue by lzj724** [Binaryify/NeteaseCloudMusicApi#105]
### 环境
系统:win10X64  

nodejs 版本:8.3
### 出现问题
![](https://s1.ax1x.com/2017/09/21/Ma5p4.jpg)
![](https://s1.ax1x.com/2017/09/21/MahhF.jpg)
![](https://s1.ax1x.com/2017/09/21/MaI1J.jpg)
```                this.$Axios.get(`${url}/playlist/detail?id=${this.$route.params.id}`).then(res => {
                    if (res.status === res.data.code) {
                        this.userinfo = res.data.playlist.creator
                        this.songList = res.data.privileges
                        this.loading = false
                        this.playlist = res.data.playlist
                        this.playlist.tracks.forEach(item => {
                            let obj = {
                                id: item.id,
                                name: item.name,
                                art: item.ar
                            }
                            this.allSongList.push(obj)
                        })
                    }
                }).catch(err => {
                    console.error(err)
                })```

代码是没问题的  从前些日子一直到今天早上都正常运行    但是在中午后这个请求就请求不到了   可能是网易那边改了  所以请修复下
### 期待效果

**Comment by szhielelp** [comment]
获取歌单同样遇到问题
不过我可以获取到但是只能获取到第一首曲目

![image 026](https://user-images.githubusercontent.com/10084666/30754539-ab6f27ee-9ff5-11e7-8fa9-cd8dff02145d.png)
![image 027](https://user-images.githubusercontent.com/10084666/30754538-ab66cd38-9ff5-11e7-808e-19e970eba23a.png)

**Comment by Binaryify** [comment]
能否提供具体运行环境
