### ISSUE TITLE
如果知道某个用户是歌手，是否可以通过用户id，获取歌手信息？

### ISSUE THREAD

**Issue by kotle** [Binaryify/NeteaseCloudMusicApi#1052]
**功能描述**
- 如果知道某个用户是歌手，是否可以通过用户id，获取歌手信息？

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1035
暂时只能通过歌手信息获取用户id

**Comment by kotle** [comment]
> #1035
> 暂时只能通过歌手信息获取用户id

好的，谢谢
