### ISSUE TITLE
参数对的情况下，登录 (/login/cellphone) 接口是400

### ISSUE THREAD

**Issue by qsefthj** [Binaryify/NeteaseCloudMusicApi#1056]
## 环境
- 系统/平台: windows10

- nodejs 版本: 12.15

- API版本: 3.37.2

## 出现问题
我根据给出的key按照文档进行接口请求，返回的都是参数错误。
`/login/cellphone?phone=xxx&password=yyy` 
把xxx改成手机号，yyy改成密码。我是这样操作的。
接口返回的状态码400

## 重现步骤
```javascript
http://localhost:3000/login/cellphone?phone=${我的手机号}&password=${手机对应的密码}
// 上面是我请求的接口，但是返回的数据确实下面的样子。
{"msg":"参数错误","code":400,"message":"参数错误"}
```

## 期待效果
能正常通过手机号登录。

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
密码是否包含特殊字符，包含的话用post登录

**Comment by qsefthj** [comment]
> 密码是否包含特殊字符，包含的话用post或者encode下登录

密码就是小写字母加数字以及小数点，没有特殊字符。

**Comment by Binaryify** [comment]
检查你拼的url对不对
