### ISSUE TITLE
获取热门话题后怎么获取话题的内容

### ISSUE THREAD

**Issue by ashin-person** [Binaryify/NeteaseCloudMusicApi#1057]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
![image](https://user-images.githubusercontent.com/20736261/102101349-775af200-3e65-11eb-8faa-5fae169743cf.png)

获取到话题的标题之后，要怎么才能获取到话题的内容呢？希望能补充这个接口，谢谢

**Comment by Binaryify** [comment]
热门话题在哪来着

**Comment by Binaryify** [comment]
话题详情接口v4.0的时候加上了
