### ISSUE TITLE
希望可以获取云村的内容

### ISSUE THREAD

**Issue by ashin-person** [Binaryify/NeteaseCloudMusicApi#1058]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
![image](https://user-images.githubusercontent.com/20736261/102243224-df790900-3f35-11eb-8331-26b676f6628b.png)
![image](https://user-images.githubusercontent.com/20736261/102243248-e869da80-3f35-11eb-92ff-30ccc7181085.png)
获取云村的内容

**Comment by Binaryify** [comment]
加云村没啥意义啊,和音乐没多大关系,接口也多
