### ISSUE TITLE
search接口

### ISSUE THREAD

**Issue by BlazingCC** [Binaryify/NeteaseCloudMusicApi#106]
可以考虑添加一个search接口，使用 “/weapi/cloudsearch/get/web”
可以得到额外的歌曲信息（例如：当前歌曲是否下架）
"privilege": {
                    "id": 26134201,
                    "fee": 0,
                    "payed": 0,
                    "st": -200,  //下架
                    "pl": 0,
                    "dl": 0,
                    "sp": 0,
                    "cp": 0,
                    "subp": 0,
                    "cs": false,
                    "maxbr": 999000,
                    "fl": 0,
                    "toast": false,
                    "flag": 0
                }

另外问个问题，比如“moon”这首歌，"id": 26134201，手机客户端显示是可以播放的，网页端显示下架的，是否两边使用了不同的接口呢？

**Comment by Binaryify** [comment]
手机电脑调的接口部分不同的
