### ISSUE TITLE
首页发现接口/homepage/block/page没有banner数据

### ISSUE THREAD

**Issue by CarberryChai** [Binaryify/NeteaseCloudMusicApi#1060]
## 环境
- 系统/平台: macOS Big Sur 11.1

- nodejs 版本: v12.4.0

- API版本: 3.47.3
![](https://cdn.jsdelivr.net/gh/CarberryChai/oss@master/image/7fi2Gz-1d5S3I.png)

## 出现问题
`/homepage/block/page`首页发现接口数据少了好多，最主要的没有了banner数据了
## 重现步骤
直接调用`/homepage/block/page`接口

## 期待效果
banner数据恢复

**Comment by CarberryChai** [comment]
不好意思，没仔细看文档，接口这是啥时候改了嘛？`/banner?type=2`

**Comment by Binaryify** [comment]
更新下

**Comment by yearspark** [comment]
请问下，怎么从老版本，更新到最新的。文档里好像，没有更新的办法。是要重新下载最新的版本吗？

**Comment by Binaryify** [comment]
git pull
