### ISSUE TITLE
歌单接口只返回了第一首曲目

### ISSUE THREAD

**Issue by szhielelp** [Binaryify/NeteaseCloudMusicApi#107]
你好，近期使用出现了问题：

### 环境
系统:  Ubuntu 16.04
nodejs 版本: 8.5.0

### 出现问题
调用歌单接口时仅返回了第一首曲目，本地调试不存在问题

### 重现步骤
将最新代码clone到ubuntu server，取消跨域注释部分

### 期待效果
应该返回所有曲目

本地调试结果: 
![image 010](https://user-images.githubusercontent.com/10084666/30779640-8580abdc-a128-11e7-8dbe-0dc1d4bc585b.png)

服务器调试结果:
![image 001](https://user-images.githubusercontent.com/10084666/30779641-885597fa-a128-11e7-8033-c700f85fdf7a.png)

本以为是Node版本问题不过本地和服务器端版本已经相同

不知道是否哪个步骤出现了问题？

**Comment by szhielelp** [comment]
是啊，是最近突然一下出现的情况，但是本地调试完全没问题，奇怪了。

**Comment by xiaodongning** [comment]
我也遇到了，有解决办法吗

**Comment by szhielelp** [comment]
似乎是网易云方面的问题，现在可以使用了

**Comment by u3u** [comment]
🤔 今天无意看了下 发现又复现了

**Comment by szhielelp** [comment]
> re: 🤔今天无意看了下 发现又复现了

我这里似乎使用正常

**Comment by dengzhao7053** [comment]
@szhielelp  你好，这个问题我也出现了，请问有什么解决办法吗:thinking:

**Comment by dida-1894** [comment]
@Binaryify
![tim 20181119134006](https://user-images.githubusercontent.com/23356854/48688449-4b76cf00-ec01-11e8-9002-16ac4b72d7b9.png)
文档里的歌单详情案例 id=24381616 只返回一首歌，求指教。

**Comment by charonvan** [comment]
- @Binaryify   完美复现，求指教~
