### ISSUE TITLE
文档中写错了接口地址，可以改正然后重新提交一下

### ISSUE THREAD

**Issue by 1015770492** [Binaryify/NeteaseCloudMusicApi#1085]
获取推荐视频
说明 : 调用此接口, 可获取推荐视频,分页参数只能传入offset

必选参数 : id: videoGroup 的 id

可选参数 : offset: 默认0

接口地址 : /video/group
调用例子 : /video/timeline/recommend

***
![image](https://user-images.githubusercontent.com/43501801/103923667-5463eb00-5150-11eb-8937-16038c44b903.png)

接口地址应该和调用地址相同，建议重新提交一个改正后的文档

**Comment by Binaryify** [comment]
好了
