### ISSUE TITLE
一个关于抱一抱接口的问题

### ISSUE THREAD

**Issue by heiheiyo-001** [Binaryify/NeteaseCloudMusicApi#1089]
## 环境
- 系统/平台: windows

- nodejs 版本: v14.15.0

- API版本: 3.47.5

## 出现问题
使用接口 抱一抱评论 过了100条评论 就无效了 要过段时间才可以 但这时如果用手机手动去抱还可以
不知道是不是100条后接口不一样还是参数变化还是怎样

## 重现步骤
找首歌 使用接口 抱100条评论 然后接下来的能返回成功 实际上没抱成功
具体有没成功可以在手机端看那个评论被谁抱了的列表 

## 期待效果
希望能像手动在手机抱一抱一样 而不是100条后使用不了 感谢~

**Comment by Binaryify** [comment]
有具体例子吗

**Comment by heiheiyo-001** [comment]
我可以把弄到那个状态 然后给你号 然后你去用接口随便抱一条 然后看用手机看那条的话 是没有被抱的 这时候如果用手机手动抱就没问题

或者你找首歌评论区 获取下评论列表 循环抱个100条 然后再在手机看 100条之后就没有被抱成功了

对哟 刚才我不小心弄炸电脑了 现在node app.js 提示我这个是咋回事 Error: Cannot find module 'body-parser'  0-0

**Comment by Binaryify** [comment]
你告诉我哪条评论就行

**Comment by heiheiyo-001** [comment]
呀  就是跟哪条评论没关 都一样的 大概感觉就是现在接口 抱过了100条能返回成功但实际上没成功 但用手机去抱就没问题    成功没成功的依据就是手机那看有个被抱的记录~  方便的话要不加个q说 3099053449

**Comment by heiheiyo-001** [comment]
就是那个帐号超过了100条就一段时间不能用接口抱了  这时接口还是会返回成功 但实际上不行 但用手机手动就可以~

**Comment by Binaryify** [comment]
'body-parser'那个错误你依赖重装试试,我下午重新抓下包看看

**Comment by heiheiyo-001** [comment]
好 那个错误我把提示的模块都装了就都好了

**Comment by Binaryify** [comment]
奇怪了,我看参数没变的,你把 hug_comment.js 的 appver 改成 '8.0.30'试试

**Comment by heiheiyo-001** [comment]
试了 没效果

**Comment by heiheiyo-001** [comment]
会不会是用接口抱了100个不同评论之后有了限制才参数不同  
我是试了接口用了过100左右
这时候就算把资源id那个类型改不对了 也会返回抱成功 实际上没成功

**Comment by Binaryify** [comment]
你确定请求都加了时间戳是吧

**Comment by heiheiyo-001** [comment]
是的

**Comment by heiheiyo-001** [comment]
抱的是不同评论 参数每次不同 然后被限制了之后 再重新请求 时间戳就是新的 所以时间戳这个可以排除

**Comment by heiheiyo-001** [comment]
老哥 有木有啥进展哈~

**Comment by Binaryify** [comment]
最近都比较忙没啥时间看,周末我再看看吧

**Comment by heiheiyo-001** [comment]
好 麻烦你了

**Comment by heiheiyo-001** [comment]
老哥新年快乐哟 有空记得帮忙看看这个问题哟~

**Comment by Binaryify** [comment]
我把app version 升级到最新了,你再看看

**Comment by heiheiyo-001** [comment]
我试了下还是一样 100条后限制 过半个小时一个小时这样又可以 然后超过几十条又限制了 但限制的时候在手机手动去操作不会有限制

**Comment by Binaryify** [comment]
应该是同ip限制100条

**Comment by Binaryify** [comment]
触发的时候换一下 X-Real-IP

**Comment by heiheiyo-001** [comment]
// headers['X-Real-IP'] = '118.88.88.88'把这个注释给去了 也试过换其它IP  也试过加参数realIP 都是没有效果 时间戳什么都是有改过的 不会是缓存的问题..

**Comment by Binaryify** [comment]
我这边不知道网易那边咋识别的，我这边怎么抓都是那几个参数

**Comment by heiheiyo-001** [comment]
呀 那就有点尴尬了哈哈哈
