### ISSUE TITLE
退出登录无效

### ISSUE THREAD

**Issue by MarshallMathersIII** [Binaryify/NeteaseCloudMusicApi#1095]
## 环境
- macos

- nodejs 版本: 8.11.1

- API版本: 3.0.0
## 出现问题
退出登录接口返回200，还可以发登录内接口

## 重现步骤
调用该接口

## 期待效果

退出登录接口返回200，无法发送登录内接口，返回登录状态异常

**Comment by Binaryify** [comment]
接口数据被缓存了吧
