### ISSUE TITLE
能否支持手机端的一起听功能

### ISSUE THREAD

**Issue by techrex** [Binaryify/NeteaseCloudMusicApi#1098]
**功能描述**
能否支持手机端的一起听功能

**Comment by Binaryify** [comment]
暂时不打算支持，这个功能比较复杂，还需要客户端的配合

**Comment by Binaryify** [comment]
暂时只加了一起听状态的接口,其他的同步状态的很麻烦,参数很多

**Comment by techrex** [comment]
非常感谢，请问如果想参与一起破解接口需要掌握一些什么技能

**Comment by Binaryify** [comment]
https://github.com/nondanee/UnblockNeteaseMusic
挂这个代理，然后取消hooks.js的console.log的注释
