### ISSUE TITLE
歌词的接口调不通

### ISSUE THREAD

**Issue by chenghaohao** [Binaryify/NeteaseCloudMusicApi#110]
### 环境
系统:  Linux

nodejs 版本: v8.4.0

### 出现问题
歌词接口调不通，超时或无响应
### 重现步骤
浏览器直接访问歌词接口/lyric?id=506092654，
昨天是可以正常使用的，今天不能用了。是不是网易封了接口？
### 期待效果
可以正常使用歌词接口。感谢

**Comment by Binaryify** [comment]
能否提供具体环境,我这边是正常的

**Comment by chenghaohao** [comment]
@Binaryify  现在又可以了，，，3Q~
