### ISSUE TITLE
<接口访问报错 502 issues>

### ISSUE THREAD

**Issue by flowerxuegao** [Binaryify/NeteaseCloudMusicApi#1105]
## 环境
- 系统/平台: <window 10>

- nodejs 版本: <14.15.0>

- API版本: <4.0.2， 4.0.2>

## 搜索歌曲报错
<[ERR] /search?keywords=海阔天空 {
  status: 502,
  body: {
    code: 502,
    msg: Error: getaddrinfo ENOTFOUND music.163.com
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
      errno: -3008,
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'music.163.com',
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  }
}
>

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
就是直接下载了项目，上午还用的好好的，下午突然报错了
请求的接口  /search?keywords=海阔天空
现在不请求数据的话是正确的，其他所有请求都502
![image](https://user-images.githubusercontent.com/23166656/105322564-05b05980-5c04-11eb-85c8-6e2fecb4c09f.png)
![image](https://user-images.githubusercontent.com/23166656/105322603-11038500-5c04-11eb-9dd7-8636a14a1f3b.png)
![image](https://user-images.githubusercontent.com/23166656/105322635-195bc000-5c04-11eb-9721-cc77f848919f.png)

## 期待效果
<请清晰描述现在的效果和期待的效果>  

期待接口正常运行

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by tabjy** [comment]
是不是 dns 的问题？ping 一下 `music.163.com`?

**Comment by flowerxuegao** [comment]
嗯嗯ping&nbsp;不通&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WenTong Niu"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 下午4:16
收件人: "Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;; 
抄送: "?__傻丫頭"<1057796814@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] <接口访问报错 502 issues&gt; (#1105)





 
是不是 dns 的问题？ping 一下 music.163.com?

**Comment by dancelion** [comment]
哥们 解决了吗 我能ping通 但还是502

**Comment by Binaryify** [comment]
是不是开了 http_proxy 之类的设置
