### ISSUE TITLE
云盘接口上传歌曲后相应歌曲json有3个字段是乱码

### ISSUE THREAD

**Issue by 275761919** [Binaryify/NeteaseCloudMusicApi#1108]
## 环境

- 系统/平台: app运行在 node:lts-alpine 容器中，通过windows 10 的 chrome 打开web网页操作，歌曲也存在win10上

- nodejs 版本: v12.13.0

- API版本: 4.0.2

## 出现问题

使用云盘接口上传歌曲到云盘后，再用 `/user/cloud` 接口获取云盘歌曲列表，其中刚上传的歌曲中的json有3个字段 `album`，`artist`，`songName` 是乱码，其他字段均正常，而同样的一首歌用网易云客户端上传则没有这个问题。

ps: 是中文歌曲，[歌曲.zip](https://github.com/Binaryify/NeteaseCloudMusicApi/files/5877014/-.zip)。

## 重现步骤

1. 调用 `axios({method: "post", url: /cloud?time=${Date.now()},headers: {"Content-Type": "multipart/form-data",},data: formData,})` 这个上传歌曲
2. 调用 `/user/cloud?time=${Date.now()}` 接口获取云盘歌曲列表，其中返回的json中刚上传的歌曲有3个字段是乱码

## 期待效果
现在有3个字段是乱码，期待没有乱码

**Comment by Binaryify** [comment]
可能是music-metadata这个库对中文支持不够完善的问题，晚些时间我抽空看看

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/106098312-c473f880-6173-11eb-9654-2286a8561389.png)
确实是这个库的问题，但是暂时还不知道怎么解决

**Comment by Binaryify** [comment]
好了,更新看看

**Comment by 275761919** [comment]
确实可以了，我用python的库解析了一下，也是乱码，感觉是v1tag不存在，就会乱码？但现在已经正常了，太强了
