### ISSUE TITLE
搜索接口无法成功获取专辑图，接口返回 null。

### ISSUE THREAD

**Issue by a632079** [Binaryify/NeteaseCloudMusicApi#111]
### 环境
系统:  Ubuntu/Deepin

nodejs 版本:v6.x & v8.x(使用Nvm切换过lts以及stable中各至少3个版本)

### 出现问题
在搜索任何歌曲时，picURL总是返回null。在腾讯云和本地的机器都无法正常搜索。已经尝试使用X-Real-IP替换了不同的IP，排除了IP的问题。
![default](https://user-images.githubusercontent.com/16975812/31306407-3ff04186-ab82-11e7-9d0c-94c47884beab.png)
![default](https://user-images.githubusercontent.com/16975812/31306408-4aee9ff6-ab82-11e7-94f1-c65a41058d43.png)

### 重现步骤
可以试着搭一个看看？
### 期待效果
更新接口

**Comment by Binaryify** [comment]
专辑封面需要调用 `/album` 获取, 比如` /album?id=34209` 的 picUrl

**Comment by a632079** [comment]
十分感谢你的回答。我之前是使用搜索接口获取专辑图片，现在失效了，如今因你的回答我解决了这个问题。但我依旧希望这个位置能够恢复，请问在未来，还可能继续支持这个位置的获取呢?

**Comment by Binaryify** [comment]
这个是看网易那边的,我这个只是拿到网易给的数据的

**Comment by a632079** [comment]
好的，十分感谢您的贡献！
