### ISSUE TITLE
网易云热评获取失败了

### ISSUE THREAD

**Issue by dyl8023** [Binaryify/NeteaseCloudMusicApi#1111]
## 环境
- 系统/平台: linux

- nodejs 版本: 14.5.3

- API版本: 7.10.4

## 出现问题
无法获取网易云热评
返回内容：
{"code":404,"message":"呃哦, 你所寻找的热评墙进入了时间的黑洞","data":null}

## 重现步骤
调用api就会出现

## 期待效果
正常调用api

**Comment by Binaryify** [comment]
你的id错了吧

**Comment by Wintheshow** [comment]
同 我也404错误 Response{protocol=http/1.1, code=404, message=Not Found,

**Comment by Binaryify** [comment]
确实有问题,晚点我更新下

**Comment by Binaryify** [comment]
好像是官方撤下了,app里面也没有入口了

**Comment by dyl8023** [comment]
> 好像是官方撤下了,app里面也没有入口了

确实下架了...
这是官方的回复 ：
新版本热评墙功能暂时下线，建议后续持续关注。

**Comment by dyl8023** [comment]
> 同 我也404错误 Response{protocol=http/1.1, code=404, message=Not Found,

下架了...
这是官方的回复 ：
新版本热评墙功能暂时下线，建议后续持续关注。
