### ISSUE TITLE
使用yarn + vue 安装完毕后提示找不到模块dns

### ISSUE THREAD

**Issue by allinu** [Binaryify/NeteaseCloudMusicApi#1114]
## 环境
- 系统/平台: Mac OS 10.14

- nodejs 版本: 14

- API版本: 4.0.3

## 出现问题

CLI报错，提示安装dns模块
![image](https://user-images.githubusercontent.com/32992109/106377808-9a703f80-63da-11eb-9e37-387bb6983bc5.png)

按照提示`yarn add dns` 以及 `npm i --save dns `都解决不了，而且安装会报错
![image](https://user-images.githubusercontent.com/32992109/106377949-9e509180-63db-11eb-9389-b5eae8bd1d96.png)

## 重现步骤

我使用的yarn安装方式，使用vue cli 创建的项目，安装的是vue2.0，创建完毕后，安装了一个vue-router以及Vuetify，然后就是使用 `yarn add NeteaseCloudMusicApi` 安装的本API。完成之后，几乎，什么也没有更改，只是设置了一下主页，以及路由，然后就在主页vue文件中使用了
 
![image](https://user-images.githubusercontent.com/32992109/106377795-862c4280-63da-11eb-8c38-d40505cf3c01.png)

## 期待效果

不报错，正常运行，能够使用js在vue文件中请求数据，而不使用后台请求

**Comment by Binaryify** [comment]
只能在nodejs端使用,不支持前端直接调

**Comment by allinu** [comment]
> 只能在nodejs端使用,不支持前端直接调

好的，谢谢
