### ISSUE TITLE
/login/status 添加时间戳超时

### ISSUE THREAD

**Issue by JackuXL** [Binaryify/NeteaseCloudMusicApi#1124]
## 环境
- 系统/平台: Centos 8
- nodejs 版本: v14.15.4
- API版本: v4.0.3

## 出现问题
/login/status 添加时间戳超时，如图：
![Snipaste_2021-02-07_08-10-34](https://user-images.githubusercontent.com/58510349/107132683-0a6f5000-691c-11eb-9bc1-54bb931270d9.png)

## 重现步骤
访问 /login/status 并添加时间戳

## 期待效果
访问 /login/status 并添加时间戳不会超时

**Comment by Binaryify** [comment]
无法重现

**Comment by JackuXL** [comment]
https://music.wearbbs.cn/login/status?cookie=__csrf=18ba428d0fa26ef2376f681da04523df; Max-Age=1296010; Expires=Wed, 24 Feb 2021 03:17:22 GMT; Path=/;;NMTID=00Optn_TYKYlwH15kxghiKcuOZ4HUIAAAF3hMsBpw; Max-Age=315360000; Expires=Fri, 7 Feb 2031 03:17:12 GMT; Path=/;;MUSIC_U=330d377b6053b751e0d83b8c03955601d453f8f5f2383ee57e537f1cee90862833a649814e309366; Max-Age=15552000; Expires=Sun, 8 Aug 2021 03:17:12 GMT; Path=/; HTTPOnly

**Comment by JackuXL** [comment]
@Binaryify ↑

**Comment by JackuXL** [comment]
似乎不加也会超时

**Comment by Binaryify** [comment]
不要用别人搭的

**Comment by JackuXL** [comment]
> 不要用别人搭的

我自己的服务器...

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/107528295-a20ec000-6bf4-11eb-8fd0-cf12fe55ae85.png)
我这边 正常
