### ISSUE TITLE
能不能开发电台上传接口

### ISSUE THREAD

**Issue by toolor** [Binaryify/NeteaseCloudMusicApi#1125]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图

**Comment by Binaryify** [comment]
为什么需要这个接口呢

**Comment by toolor** [comment]
我是播主，每次手工上传音频，看到这个项目以后在想能不能自动化上传我每次的更新的节目。

**Comment by Binaryify** [comment]
这样啊，我试试，主要要加这个接口的话我也得注册下博主

**Comment by Binaryify** [comment]
确实不好弄,我不是博主,也提交不了作品
