### ISSUE TITLE
/like?id= 喜欢音乐无效

### ISSUE THREAD

**Issue by JackuXL** [Binaryify/NeteaseCloudMusicApi#1126]
## 环境
- 系统/平台: Centos 8
- nodejs 版本: v14.15.4
- API版本: v4.0.3

## 出现问题
/like?id= 喜欢音乐无效且无法喜欢云盘音乐

## 重现步骤
访问 /like?id=xxx 收藏音乐，再进入我喜欢的，发现并没有此歌曲

## 期待效果
可以正常喜欢音乐、云盘音乐

**Comment by Binaryify** [comment]
把时间戳带上

**Comment by JackuXL** [comment]
还是不行
![Snipaste_2021-02-09_19-03-07](https://user-images.githubusercontent.com/58510349/107354735-7bc02600-6b09-11eb-817f-1418b019bb95.png)
![Uploading Snipaste_2021-02-09_19-03-12.png…]()

**Comment by JackuXL** [comment]
@Binaryify

**Comment by Binaryify** [comment]
是不是你服务器有啥转发的,你直接ip访问试试

**Comment by JackuXL** [comment]
![Snipaste_2021-02-11_22-16-12](https://user-images.githubusercontent.com/58510349/107648001-c59a3f00-6cb6-11eb-85bb-96d26f66b516.png)
直接访问也一样

**Comment by JackuXL** [comment]
@Binaryify

**Comment by Binaryify** [comment]
应该是之前某次别人的PR合过来,默认行为变成取消喜欢了.一会更新下

**Comment by Binaryify** [comment]
好了

**Comment by JackuXL** [comment]
可以了，谢谢大佬
