### ISSUE TITLE
新版评论接口的评论没有回复评论的内容

### ISSUE THREAD

**Issue by Liuhongwei3** [Binaryify/NeteaseCloudMusicApi#1132]
## 环境
- 系统/平台: Windows

- nodejs 版本: 最新
- API版本:  4.0.1

## 出现问题
新版评论接口获取的评论中只有回复该评论的条数（replyCount：x），没有具体内容，经查验PC端评论还是以前的，手机端用的是新版，而且要查看回复的评论貌似是重新发起的请求（具体没抓包验证）

## 重现步骤
访问：http://localhost:3000/comment/new?&type=3&id=21506&sortType=2

## 期待效果
想要获取具体的回复评论的内容或者是否已有获取该部分数据的API

注：[文档](https://binaryify.github.io/NeteaseCloudMusicApi/#/) 下半部分的内容排版有问题
有空可以看看，辛苦~

**Comment by Binaryify** [comment]
文档是因为docsify新版本出问题了,我降级下
接口我抽空看看

**Comment by Binaryify** [comment]
楼层回复有接口,/comment/floor这个

**Comment by Liuhongwei3** [comment]
> 楼层回复有接口,/comment/floor这个

对哦，之前还看过，只是当时没太注意这个接口，失误~

**Comment by Binaryify** [comment]
文档应该也好了
