### ISSUE TITLE
请问下DOCKER环境怎么更新？

### ISSUE THREAD

**Issue by anschein** [Binaryify/NeteaseCloudMusicApi#1133]
RT，实在不好意思百度了很久，废了九牛二虎之力在DOCKER中装上了，然后之前用的好好的今天突然DLNA播放出了问题，说来更新试试结果折腾了很久没弄好
群晖DOCKER，能进终端机，能NPM

**Comment by Binaryify** [comment]
DOCKER 我也不太懂

**Comment by cvilia** [comment]
不知道你指的是什么意思，我一般就是停止删除当前的容器id，然后pull新代码，重新开启一个容器
