### ISSUE TITLE
我的音乐 - 我的视频统计数不正确，其余正确

### ISSUE THREAD

**Issue by xlz122** [Binaryify/NeteaseCloudMusicApi#1134]
## 环境
- 系统/平台:  windows

- nodejs 版本:  v12.18.3

- API版本: 4.0.3

## 出现问题
我的音乐 - 我的视频统计数不正确，其余正确

## 重现步骤

接口是：获取用户信息 , 歌单，收藏，mv, dj 数量 （/user/subcount）

参数传入： timestamp

![image](https://user-images.githubusercontent.com/39209777/108483566-d7db3500-72d5-11eb-879d-61f5cde88fb6.png)

## 期待效果

实际是有数量2的
 
![image](https://user-images.githubusercontent.com/39209777/108483752-0b1dc400-72d6-11eb-8485-58107fb9779a.png)

**Comment by Binaryify** [comment]
那个应该是收藏的mv数量，mv和视频不一样的,晚点看看

**Comment by xlz122** [comment]
> 那个应该是收藏的mv数量，mv和视频不一样的,晚点看看

其他各项参数都在这边的话，mv数量应该就是这个没错，文档那边，也没有找到其他类似获取数量的接口

**Comment by Binaryify** [comment]
应该是 `/mv/sublist` 这个接口里面返回的count

**Comment by xlz122** [comment]
> 应该是 `/mv/sublist` 这个接口里面返回的count

这个接口是获取mv列表的，但是这样不是不合理吗？多请求一条接口就为了获取一个统计数，有办法给 /user/subcount 加上这个数量吗

**Comment by xlz122** [comment]
顺便问下，你这边有提供 首页 - 侧边栏热门主播的接口吗？我找了一圈没有找到 
![image](https://user-images.githubusercontent.com/39209777/108576023-03523400-7357-11eb-88b3-3106604bb0c3.png)

**Comment by Binaryify** [comment]
@xlz122 不合理也是网易那边的问题，我这边不可能读网易数据库的，只是接口转发

**Comment by Binaryify** [comment]
热门主播晚上我再看看吧

**Comment by xlz122** [comment]
> @xlz122 不合理也是网易那边的问题，我这边不可能读网易数据库的，只是接口转发

哈哈 打扰了

**Comment by xlz122** [comment]
> 热门主播晚上我再看看吧

好的

**Comment by Binaryify** [comment]
热门主播没有专门的接口,网易那边服务端渲染的

**Comment by xlz122** [comment]
> 热门主播没有专门的接口,网易那边服务端渲染的

嗯嗯 晓得了
