### ISSUE TITLE
使用调用接口后，在官方网页上，相关音乐直接无法播放。（请求详细歌曲信息时/song/detail，代码400。）

### ISSUE THREAD

**Issue by Ircon** [Binaryify/NeteaseCloudMusicApi#1135]
# 使用API后。现在，网易云的网页端，我已经无法正常听歌了
## 环境
- 系统/平台:  Windows10

- nodejs 版本: v14.15.4
![image](https://user-images.githubusercontent.com/11171522/108495007-3529b300-72e3-11eb-9efa-ae5a15df7633.png)

- API版本: 4.0.4
![image](https://user-images.githubusercontent.com/11171522/108495124-5ab6bc80-72e3-11eb-8bd2-2ae4c5648b99.png)

## 出现问题
通过接口 `/song/detail?ids=XXXXX`  获取信息时。出现如下错误：

```json
status: 400,
  body: { msg: '网络太拥挤，请稍候再试！', code: -460, message: '网络太拥挤，请
稍候再试！' }
```

![image](https://user-images.githubusercontent.com/11171522/108497454-6b1c6680-72e6-11eb-8be3-c1968a2bb558.png)

**之前正常获取过一次**，之后在出现400.

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

![image](https://user-images.githubusercontent.com/11171522/108496051-86867200-72e4-11eb-843d-17771f437a13.png)
这个注释已经取消掉。

出现上述错误后，从新登录网易云音乐的网页端。相关音乐直接无法播放。
![image](https://user-images.githubusercontent.com/11171522/108496320-d82efc80-72e4-11eb-8040-59ce2e64f96a.png)
![image](https://user-images.githubusercontent.com/11171522/108496819-905ca500-72e5-11eb-983d-11e01d75a544.png)

**对这个歌单请求一次后，这个歌单音乐全挂。**
![image](https://user-images.githubusercontent.com/11171522/108496909-b4b88180-72e5-11eb-9902-c906e21d6e03.png)
试一下
![image](https://user-images.githubusercontent.com/11171522/108497236-1f69bd00-72e6-11eb-9e7c-9dc8d8aa4bb6.png)

## 重现步骤
![image](https://user-images.githubusercontent.com/11171522/108495356-a8332980-72e3-11eb-9167-d1d08697c94e.png)
操作过程如下：
1. 通过手机登录接口，登录后。 `/login/cellphone?password=XXXXX&phone=XXXX`
2. 获取用户的所有播放列表。 `/user/playlist?uid=XXXX`
3. 获取播放列表的所有歌曲。 `/playlist/detail?id=XXXX`
4. 获取歌曲的详细信息。 `/song/detail?ids=XXXXX` 
第 4 步时，出现错误：
![image](https://user-images.githubusercontent.com/11171522/108495719-1677ec00-72e4-11eb-9dab-c3973603716f.png)

更换过IP，依旧错误。
![image](https://user-images.githubusercontent.com/11171522/108498015-3c52c000-72e7-11eb-8eb6-e67b7658fac6.png)
![image](https://user-images.githubusercontent.com/11171522/108498053-4674be80-72e7-11eb-9137-b79c5f9fbbb0.png)

## 期待效果
1. 能正常访问，`/song/detail?ids=XXXXX`  获取详细信息。
2. 网易云网页端可以正常播放。
3. 有推荐的其他API吗？我用着是用来做毕业设计的，这个目前有点不稳定。

**Comment by Ircon** [comment]
兄弟们如果有其他API推荐，比较稳定的，告诉我一声。这次抽风抽的有点厉害。

**Comment by Binaryify** [comment]
你的ip被网易封了,先用邮箱登录试试

**Comment by Ircon** [comment]
> 你的ip被网易封了,先用邮箱登录试试

![image](https://user-images.githubusercontent.com/11171522/108518177-3bc82280-7303-11eb-93d2-36517d5b3c25.png)

用邮箱依旧不行，我又注册一个新账号，发现出现了一个新问题。我一会再开个issue

**Comment by Ircon** [comment]
> > 你的ip被网易封了,先用邮箱登录试试
> 
> ![image](https://user-images.githubusercontent.com/11171522/108518177-3bc82280-7303-11eb-93d2-36517d5b3c25.png)
> 
> 用邮箱依旧不行，我又注册一个新账号，发现出现了一个新问题。我一会再开个issue

新发现的问题解决了，建议所有和数字有关的字段，在反序列化时候用Long不要用Integer。但是，状态码400 问题没有解决。
