### ISSUE TITLE
恢复request.js里对eapi加密response的解密

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#1138]
## 环境
- 系统/平台: Windows 10

- nodejs 版本: 14 lts

- API版本: 4.0.4

## 出现问题
eapi版batch接口的返回数据还是加密的，似乎某一次提交把对eapi数据解密的部分删了，应该恢复回去

## 重现步骤
http://localhost:3000/batch?/api/v2/banner/get={%22clientType%22:%22pc%22}
![image](https://user-images.githubusercontent.com/27536652/108591425-adf04400-73a3-11eb-9d3e-9e4489db96f2.png)
不是代理的问题，fd里面显示也是这样

## 期待效果
恢复request.js里对eapi加密response的解密

**Comment by wwh1004** [comment]
这次提交把代码改坏了
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/cea20242881bd926ab142cd6e9f28cd19c9a8078

删除的地方
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/cea20242881bd926ab142cd6e9f28cd19c9a8078#diff-1cb44eee1804bf58893684b053cbda81221fa62242ee3ddaea80476255122de2L140

**Comment by Binaryify** [comment]
好，晚上我改一下

**Comment by Binaryify** [comment]
好了,更新了~
