### ISSUE TITLE
登录后 返回的数据里面 又cookie字段 如何处理cookie字段 保持浏览器的登录状态

### ISSUE THREAD

**Issue by lzzqwe** [Binaryify/NeteaseCloudMusicApi#1139]
手机登录 接口 登录成功后  json数据返回cookie字段  如何处理cookie字段 保持浏览器的登录状态

**Comment by lzzqwe** [comment]
已解决

**Comment by wfJoanna** [comment]
> 已解决

你好，想问一下你是怎么处理的？

**Comment by lzzqwe** [comment]
cookie存在 localstorage 中 如果cookie过期了 会返回状态码401 可以在路由拦截中 判断状态码如果是401 移除cookie就可以了



在 2021-04-01 11:17:15，"顽风" ***@***.***> 写道：

已解决

你好，想问一下你是怎么处理的？
