### ISSUE TITLE
不直接取cookie,直接把接口返回内容的cookie保存下来就行

### ISSUE THREAD

**Issue by lzzqwe** [Binaryify/NeteaseCloudMusicApi#1140]
不直接取cookie,直接把接口返回内容的cookie保存下来就行

_Originally posted by @Binaryify in https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1071#issuecomment-753573765_
cookie字段是要怎么保存在客户端的 是要用js-cookie这个库吗

**Comment by Binaryify** [comment]
localStorage

**Comment by lzzqwe** [comment]
能不能通过localStorage   存登录后返回的token字段  来判断登录的状态 也就是说token过期的话 前端获取不到token值  就证明已经未登录了  不知道这样可以不可以   还有localStorage存登录后返回的cookie字段 和存登录后返回的token字段 效果是不是一样的？

**Comment by Binaryify** [comment]
cookie失效了接口返回都是301的
