### ISSUE TITLE
song/detail接口ids参数可以不用传

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#1143]
## 环境
- 系统/平台: win10

- nodejs 版本: 14 lts

- API版本: 4.0.4

ids: '[' + query.ids.join(',') + ']'

这个可以不需要了，刚才登录pc网易云音乐，抓包看了下，只有c这一个参数，没传ids参数进去。然后我删了这一行代码，程序也是正常的。

**Comment by Binaryify** [comment]
嗯嗯，下个版本删掉这个

**Comment by JackuXL** [comment]
> 嗯嗯，下个版本删掉这个

啊这，不要删吧，改成可选参数罢

**Comment by wwh1004** [comment]
问题是参赛没用，干嘛留着？ids的实际参数名是c，不是ids

**Comment by Binaryify** [comment]
已更新
