### ISSUE TITLE
Docker自行构建，登录接口超时，其他接口测试正常

### ISSUE THREAD

**Issue by 97Yates05** [Binaryify/NeteaseCloudMusicApi#1145]
## 环境
- 系统/平台: Mac Docker

## 出现问题
通过docker映射的端口访问一切正常，但是通过nginx镜像直接反向代理http:容器名:3000时，登录接口超时，测了几个其他的接口正常（说明不是代理配置错误，请求实际已经到了容器）
**手机号和邮箱登录是一样的情况**

**Comment by Binaryify** [comment]
超时多久,是不是你超时时间设置太短了
