### ISSUE TITLE
请问不支持部署在vercel吗？

### ISSUE THREAD

**Issue by W4J1e** [Binaryify/NeteaseCloudMusicApi#1146]
## 环境
- 系统/平台: <你的系统和平台>
Windows 10  部署平台为vercel
- nodejs 版本: <你的 NodeJS 版本号>
从vercel里只能看到和选择node 12+或者node 14+，无法查看具体版本号
- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
4.0.6
## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>
引入到YesPlayMusic之后无法正常显示该播放器页面，排查中发现api无法正常使用如“搜索”、“评论”等功能，页面返回404.
## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
链接为：https://yyapi.vercel.app
![首页正常显示](https://user-images.githubusercontent.com/74824162/108849534-3299c700-761d-11eb-86bb-30de115c1450.jpg)
上图为vercel部署后的首页截图，正常。
![搜索返回404](https://user-images.githubusercontent.com/74824162/108849491-27df3200-761d-11eb-88c2-659a28509b03.jpg)
上图为点击例子中的搜索后出现的页面，404.
## 期待效果
<请清晰描述现在的效果和期待的效果>  
期待的效果为：功能使用返回正常。
通过搜索引擎搜索到的本项目api搭建，有ssl证书的都有（仅我看到的）该问题，而本地搭建和http直接访问的则无该问题。
vercel或自动为项目申请ssl证书，所以请教一下开发者，本项目不支持ssl还是目前不支持部署到vercel？
非常感谢您所作的贡献。

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by W4J1e** [comment]
部署在lnc成功了。

**Comment by Binaryify** [comment]
加了vercel配置了,vercel那边import下项目就行

**Comment by W4J1e** [comment]
> 加了vercel配置了,vercel那边import下项目就行
非常感谢，辛苦啦。

**Comment by NieHang** [comment]
> 部署在lnc成功了。

你好，我也遇到了和你一样的问题，请问你是怎么处理的呢？谢谢

**Comment by W4J1e** [comment]
> > 部署在lnc成功了。
> 
> 你好，我也遇到了和你一样的问题，请问你是怎么处理的呢？谢谢

当时不支持vercel后来大佬适配了，现在部署在vercel正常。

**Comment by NieHang** [comment]
> > > 部署在lnc成功了。
> > 
> > 
> > 你好，我也遇到了和你一样的问题，请问你是怎么处理的呢？谢谢
> 
> 当时不支持vercel后来大佬适配了，现在部署在vercel正常。

那就太奇怪了，我按照大佬步骤 deploy，如果不设置 **Root Directory** 根本打不开，我把**Root Directory**设置成 **public** 后，结果 _搜索_、_评论_等功能都是404，就很尴尬

**Comment by NieHang** [comment]
> > > > 部署在lnc成功了。
> > > 
> > > 
> > > 你好，我也遇到了和你一样的问题，请问你是怎么处理的呢？谢谢
> > 
> > 
> > 当时不支持vercel后来大佬适配了，现在部署在vercel正常。
> 
> 那就太奇怪了，我按照大佬步骤 deploy，如果不设置 **Root Directory** 根本打不开，我把**Root Directory**设置成 **public** 后，结果 _搜索_、_评论_等功能都是404，就很尴尬

特地说一下，我部署的是 4.0.18 版本的，这个版本 app.js 有问题，所以导致线上项目打不开，导入最新版 4.0.19 就好了
