### ISSUE TITLE
创建的歌单和收藏的歌单需要分开获取，不然无法作分页处理

### ISSUE THREAD

**Issue by little-buddy** [Binaryify/NeteaseCloudMusicApi#1149]
**功能描述**
- 创建的歌单和收藏的歌单需要分开获取，不然无法作分页处理
<img src="https://user-images.githubusercontent.com/30054881/108983481-e193dc80-76c9-11eb-8d17-cfb85c9410a5.png" width=600>

**Comment by little-buddy** [comment]
如果按现有接口，将该两个歌单合并 => 我的歌单，/user/subcount来完成，但这个接口无法获取到第三人的订阅数量信息，也无法显示直接显示总歌单数量 😂

**Comment by Binaryify** [comment]
网易那边就是这样的

**Comment by little-buddy** [comment]
但是现在的网易云客户端有分页呀
![image](https://user-images.githubusercontent.com/30054881/109383663-d12a6e80-7922-11eb-836c-00ec713bffba.png)

**Comment by Binaryify** [comment]
一次性获取完,然后客户端分的

**Comment by Binaryify** [comment]
不信你把网断了然后点翻页

**Comment by little-buddy** [comment]
妈呀，真的耶😂
