### ISSUE TITLE
评论超过50页之后返回空的res['comments']

### ISSUE THREAD

**Issue by Burlesque1** [Binaryify/NeteaseCloudMusicApi#1150]
## 环境
- 系统/平台: <你的系统和平台>
ubuntu 20.04
- nodejs 版本: <你的 NodeJS 版本号>
v14.15.4
- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
4.0.6
## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>
官方app内50页后评论为空，但是最后50页的评论可展示
4.0.6版本仅能获取前50页评论
![image](https://user-images.githubusercontent.com/11853736/108985958-98915780-76cc-11eb-8f67-d07660f6cf46.png)
![image](https://user-images.githubusercontent.com/11853736/108985976-9deea200-76cc-11eb-9fbc-293ab1a21d5b.png)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
![image](https://user-images.githubusercontent.com/11853736/108985706-4c461780-76cc-11eb-97c9-3d8c4a1ba573.png)

## 期待效果
<请清晰描述现在的效果和期待的效果>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
用新版评论接口试试

**Comment by Liuhongwei3** [comment]
加上before是可以的

**Comment by Binaryify** [comment]
对的,获取超过5000条评论的时候得加before

**Comment by Burlesque1** [comment]
BEFORE加在哪里 有样例提供一下吗

**Comment by Binaryify** [comment]
你 limit 怎么加的就怎么加
