### ISSUE TITLE
添加/取消喜欢音乐失败报-460

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#1151]
w我不是第一次提啦 

api 是最新版本  node版本是10+   
系统是centos7

喜欢音乐
说明 : 调用此接口 , 传入音乐 id, 可喜欢该音乐

必选参数 : id: 歌曲 id

可选参数 : like: 布尔值 , 默认为 true 即喜欢 , 若传 false, 则取消喜欢

接口地址 : /like

调用例子 : /like?id=347230
调用地址 :*3000/like?id=1820830981&like=false&timestamp=1614267086734&cookie=*****
调用此接口报-460    

附截图

![QQ截图20210225233212](https://user-images.githubusercontent.com/38646454/109176484-d623dc80-77c1-11eb-81d9-eed0db6bd97b.png)

**Comment by zlj-zz** [comment]
我也是 -460

**Comment by kontori** [comment]
我也是欸 登录、搜索什么的功能都正常，就这个报错

**Comment by refuse-c** [comment]
这个就有点尴尬了    我开始以为是你更新了  但是我换了一台服务器部署还是不行   要不抓一下pc 或者mobile端看看他们是怎么调用接口的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: kontori<mailto:notifications@github.com>
发送时间: 2021年2月26日 22:47
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 添加/取消喜欢音乐失败报-460 (#1151)


我也是G 登录、搜索什么的功能都正常，就这个报错

―

**Comment by Binaryify** [comment]
这个接口晚点更新下

**Comment by Binaryify** [comment]
好了,重新拉下代码应该就好了

**Comment by refuse-c** [comment]
好的  3Q

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: binaryify<mailto:notifications@github.com>
发送时间: 2021年2月27日 16:14
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 添加/取消喜欢音乐失败报-460 (#1151)


好了,重新拉下代码应该就好了

―

**Comment by refuse-c** [comment]
你好 ,可以添加一个获取vip等级的接口?
