### ISSUE TITLE
关于手机绑定接口及注册时手机号国家代码的问题

### ISSUE THREAD

**Issue by imppresser** [Binaryify/NeteaseCloudMusicApi#1152]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图

手机绑定接口目前文档均需要旧手机，对于没有绑定手机的邮箱登录的账号 希望增加直接绑定手机的接口（测试应为wyy的binding接口）
还有注册时没有国家代码选项，希望可以利用境外手机号码注册，即增加国家代码注册可选参数，感谢。

**Comment by desson2** [comment]
有卡吗 我接口都有 golang版 现在想搞注册账号的 缺大量的卡

**Comment by imppresser** [comment]
> 有卡吗 我接口都有 golang版 现在想搞注册账号的 缺大量的卡 我wechat：FFFFEFEF

我不是卡商，我只是发现这个问题。通过修改源码把接口补上了，只是作者漏了吧

**Comment by Binaryify** [comment]
好了,已经更新了~
