### ISSUE TITLE
/user/subcount 接口问题

### ISSUE THREAD

**Issue by ywang1988** [Binaryify/NeteaseCloudMusicApi#116]
调用这个/user/subcount这个接口，报301。发现是没有登录所致。打开网易云音乐APP，你不登陆时，也可以查看该信息。查看文档调用例子:/user/subcount?uid=32953014，代码中没有用到uid 

查看user_subcount.js源码文件
`const express = require('express')
const router = express()
const { createWebAPIRequest } = require('../util/util')

router.get('/', (req, res) => {
  const cookie = req.get('Cookie') ? req.get('Cookie') : ''
  const data = {
    csrf_token: ''
  }
  createWebAPIRequest(
    'music.163.com',
    '/weapi/subcount',
    'POST',
    data,
    cookie,
    music_req => res.send(music_req),
    err => res.status(502).send('fetch error')
  )
})

module.exports = router`

**Comment by Binaryify** [comment]
用户信息肯定要登录才能获取的, id 这里多余了,等下更新下文档

**Comment by ywang1988** [comment]
在网易云音乐搜索界面，你搜索某一个人，不需要登录，也可以查看某个人的信息，音乐，动态和关于TA

**Comment by ywang1988** [comment]
/user/dj现在获取电台的这个接口，只能获取电台下的歌曲列表，这个接口类似于获取歌单详情接口，类似于获取用户歌单和获取歌单详情两个接口

**Comment by Binaryify** [comment]
如果要获取动态的话可以调 `/user/event?uid=32953014`

**Comment by ywang1988** [comment]
/user/dj现在获取电台的这个接口，只能获取电台下的歌曲列表，这个接口类似于获取歌单详情接口。看一下获取用户歌单和获取歌单详情两个接口

**Comment by Binaryify** [comment]
wait

**Comment by Binaryify** [comment]
你是需要获取电台的什么信息

**Comment by ywang1988** [comment]
你打开网易云音乐APP，搜索某个用户，就知道了我说的什么意思了

**Comment by Binaryify** [comment]
嗯

**Comment by Binaryify** [comment]
看看还能不能再完善下

**Comment by ywang1988** [comment]
问一下，你的代码在码云上有发布吗？

**Comment by Binaryify** [comment]
没有在码云上发布

**Comment by ywang1988** [comment]
你好，我clone你的项目，然后需要重构一下你的API和文档使用说明，然后重新上传到GitHub上，如果在此过程中有侵占你的利益，可以提出意见或建议，谢谢！！

**Comment by Binaryify** [comment]
@ywang1988 你声明下原 repo 就行

**Comment by Binaryify** [comment]
@ywang1988 一些接口的参数不好猜,所以更新的不是很快,见谅

**Comment by ywang1988** [comment]
我在‘’灵感来自‘’下加入你的repo就行了，其余的可能要重构，有意见或建议回复我就行了

**Comment by ywang1988** [comment]
现在基本够用了

**Comment by Binaryify** [comment]
@ywang1988 okay
