### ISSUE TITLE
获取用户粉丝接口数据量不对且time无效

### ISSUE THREAD

**Issue by Liuhongwei3** [Binaryify/NeteaseCloudMusicApi#1161]
## 环境
- 系统/平台: win10

- nodejs 版本: 最新
- API版本: 最新

## 出现问题
请求用户粉丝接口（当然这个接口现在是需要登录的）时，传入limit 无效且传入lasttime无法获取到下一页的数据始终返回第一页的数据，我抓官方网站的包里面好像有offset参数，但是我也尝试了好像还是那样

## 重现步骤
接口地址：`/user/followeds?uid=328199093&limit=20&lasttime=1614422859604`

## 期待效果
可以根据limit和lasttime来控制返回的数据

有空帮忙解答一下，感谢~

**Comment by Binaryify** [comment]
这个接口分页参数有问题

**Comment by Binaryify** [comment]
已更新
