### ISSUE TITLE
带上代理返回502

### ISSUE THREAD

**Issue by HmilyHmily** [Binaryify/NeteaseCloudMusicApi#1167]
## 环境
- 系统/平台: CentOS 7.8 LINUX

- nodejs 版本: v14.16.0

- API版本: 4.0.8

## 出现问题
根据文档：[使用代理教程](https://neteasecloudmusicapi.vercel.app/#/?id=%e5%8f%af%e4%bb%a5%e4%bd%bf%e7%94%a8%e4%bb%a3%e7%90%86)

返回502 Bad Gateway

## 重现步骤
按照教程 rul+&proxy=http://+ip:端口
所有都返回 502
测试使用的代理正常使用

## 期待效果
请问什么问题 怎么解决谢谢

**Comment by Binaryify** [comment]
支持的代理是ss,v2ray提供的http代理,不支持UnblockNeteaseMusic那种代理
