### ISSUE TITLE
请求添加获取用户正在听的歌曲接口

### ISSUE THREAD

**Issue by adinxu** [Binaryify/NeteaseCloudMusicApi#1170]
我想在个人网站上实时显示我的网易云音乐正在听的歌，但是好像没有找到接口。
新版本的网易云音乐中添加了一起听功能，添加了这个功能之后应当可以获取当前用户正在听的歌曲了。具体可用性未知，请帮忙看下这个功能是否可以添加 ღ( ´･ᴗ･` )比心

**Comment by Binaryify** [comment]
加上一起听状态接口了,其他的涉及到状态的暂时不加了,很多参数很麻烦

**Comment by lgy1159** [comment]
加上了也不行，获取不到房间正在播放的歌曲

**Comment by adinxu** [comment]
@lgy1159 对的，所以我现在都还没搞定这个呢。照我说这都是网易的活啊。。。。像spotify就有官方接口。我现在唯一想到的办法是获取历史播放记录，延时显示听得歌。

**Comment by lgy1159** [comment]
这个很奇怪的是 他获取历史播放记录 是有序的，，只有 playcount会变。。还不能每次都拿最后一个，还要自己写套算法去算哪一首歌是最后播放的。。

**Comment by shouge** [comment]
我也有相同的（骚）想法 通过获取正在听状态显示的歌曲信息 分享到我的飞书签名上
