### ISSUE TITLE
热门评论 接口无法根据分页参数before获取下一页的热门评论数据

### ISSUE THREAD

**Issue by sunhx-shx** [Binaryify/NeteaseCloudMusicApi#1173]
## 环境
- 系统/平台: Win10

- nodejs 版本: 10.23.1

- API版本: 3.47.3

## 出现问题
热门评论 接口无法根据分页参数before获取下一页的热门评论数据
![1615882118(1)](https://user-images.githubusercontent.com/77148584/111276318-2e882480-8672-11eb-9ba9-2eb3cdabe658.jpg)

![image](https://user-images.githubusercontent.com/77148584/111276208-0dbfcf00-8672-11eb-954c-d784608cc80a.png)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
mv评论  这个接口是能够正常获取下一页数据的，不知道 热门评论 这个接口是不是参数没传进去还是什么问题。希望大神能解决一下，感谢！

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
limit 和 offset 还是要加的

**Comment by sunhx-shx** [comment]
![image](https://user-images.githubusercontent.com/77148584/111284214-e3beda80-867a-11eb-8b15-2b702e52b013.png)
![image](https://user-images.githubusercontent.com/77148584/111284301-f802d780-867a-11eb-974d-01c571734a7e.png)
加了另外两个参数之后是获取到了不同页数的热门评论数据，但是这几页数据里面好多重复的数据，代码中我用的评论的id
做的循环的key值，所以报了很多错，这个能解决吗？

**Comment by Binaryify** [comment]
offset不是页数
