### ISSUE TITLE
手机登录返回成功返回的token怎么在其他需要登录的接口中使用？

### ISSUE THREAD

**Issue by taopoppy** [Binaryify/NeteaseCloudMusicApi#1176]
通过手机号和密码登录成功后，返回的信息里会有token，访问其他需要登录的接口中怎么使用这个token，是JWT那种方式么，在请求头headers中添加 “Authorization“: "Bearer token值"，还是有别的方法，请大佬指教

**Comment by Binaryify** [comment]
文档有写的，就在登录说明后面

**Comment by taopoppy** [comment]
> 文档有写的，就在登录说明后面

那个是cookie，我以为token也能用

**Comment by Binaryify** [comment]
token 还用不了
