### ISSUE TITLE
手动传cookie时无法收藏/取消收藏歌单

### ISSUE THREAD

**Issue by qier222** [Binaryify/NeteaseCloudMusicApi#1177]
## 环境
- 系统/平台: macOS
- nodejs 版本: v15.11.0
- API版本: 4.0.9

## 出现问题
手动传cookie时无法收藏/取消收藏歌单

情况一：在非跨域情况下，自动带上cookie时没问题
```
`http://localhost:3000/playlist/subscribe?id=2851240533&t=1&timestamp=1616574839555`
```

情况二：在跨域情况下，使用文档提供的方法手动传cookie
```
http://localhost:3000/playlist/subscribe?id=2851240533&t=1&timestamp=1616574839555&cookie=MUSIC_U%3D1239b6c1xxxxxxxxxx
```

在情况二下，API会返回403错误，API在终端打印如下日志
```
[ERR] /playlist/subscribe?id=2851240533&t=1&timestamp=1616574841300&cookie=MUSIC_U=1239b6c1xxxxxxxxx {
  status: 403,
  body: { msg: 'illegal request!', code: 403, message: 'illegal request!' }
}
```

收藏歌曲的API在这两个情况下都没有问题

**Comment by Binaryify** [comment]
post 呢

**Comment by qier222** [comment]
> post 呢

post和get都是返回403

**Comment by zluo01** [comment]
> > post 呢
> 
> post和get都是返回403

找到解决办法了么？

**Comment by qier222** [comment]
> > > post 呢
> > 
> > 
> > post和get都是返回403
> 
> 找到解决办法了么？

今天找到了解决方法，出现这个的原因是没有将网易云的所有cookie都传给api，只传了MUSIC_U是不行的
