### ISSUE TITLE
推荐新音乐接口没有返回limit参数指定的数量

### ISSUE THREAD

**Issue by wfJoanna** [Binaryify/NeteaseCloudMusicApi#1178]
## 环境
- 系统/平台: win10

- nodejs 版本: 12.17.0

- API版本: 4.0.9

## 出现问题
获取推荐新音乐时，'/personalized/newsong?limit=9'，开发环境是正常返回了9首歌，但是部署到github pages后就只返回了3首歌（这个api项目部署到vercel的）

__我也不知道是哪个环节出了问题，vercel上也看不到详细的日志，希望解答一下，感谢感谢__

## 重现步骤
接口链接：/personalized/newsong?limit=9
![QQ截图20210325105627](https://user-images.githubusercontent.com/62973056/112412632-cf08d380-8d59-11eb-8282-6ecb9b48b8da.jpg)

接口返回内容：
![QQ截图20210325105637](https://user-images.githubusercontent.com/62973056/112412363-5d308a00-8d59-11eb-8925-9f98e662be91.jpg)

## 期待效果
现在的效果：开发环境返回12首歌，部署到网上后只返回了3首歌
期望的效果：部署到网上后也返回12首歌

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
更新下代码看看

**Comment by wfJoanna** [comment]
解决了，原来是因为登录的时候没设置cookie
