### ISSUE TITLE
使用POST请求在传入cookie字符串时，cookie没有先转为对象

### ISSUE THREAD

**Issue by Clarkkkk** [Binaryify/NeteaseCloudMusicApi#1179]
## 环境
- 系统/平台: 无关

- nodejs 版本: 无关

- API版本: 4.0.9

## 出现问题
使用POST请求在传入cookie字符串时，没有对`req.body.cookie`进行处理，如果传入的cookie是字符串，一些接口会报错，比如最近更新[like.js](module/like.js)，还有以前报过的#1005，在中间件里先处理一下，应该就一劳永逸地解决这个问题了。

**Comment by Clarkkkk** [comment]
#1180

**Comment by Binaryify** [comment]
👍
