### ISSUE TITLE
weapi逆向解析有示例吗？好奇如何得到weapi的params参数的

### ISSUE THREAD

**Issue by JesseWeb** [Binaryify/NeteaseCloudMusicApi#1181]
希望为社区做一点贡献。

**Comment by Binaryify** [comment]
参考这个
https://juejin.cn/post/6844903586879520775

**Comment by Binaryify** [comment]
参考我这个视频
https://www.bilibili.com/video/BV1PY41147r9

**Comment by kengwang** [comment]
如果是安卓的话可以用 HttpCanary 抓包并使用 TrustMeAlready 解决证书绑定, 将参数手动解密也可以
