### ISSUE TITLE
收藏歌单显示请求过于频繁

### ISSUE THREAD

**Issue by HmilyHmily** [Binaryify/NeteaseCloudMusicApi#1185]
## 环境
- 系统/平台: linux
已经解决 谢谢

**Comment by Chuan1997** [comment]
> ## 环境
> * 系统/平台: linux
>   已经解决 谢谢

我也尝试爬取用户自己创建的“喜欢的歌曲”歌单，调用的是http://localhost:3000/playlist/detail?id=这个接口，不管间隔时间是多久，都是返回大量的405。请问您是怎么解决的呢？
