### ISSUE TITLE
文档中的问题

### ISSUE THREAD

**Issue by februarysea** [Binaryify/NeteaseCloudMusicApi#1191]
## 出现问题

文档中新版评论接口，或许作者疏忽写错了，实际返回的json数据中是`cursor`

原版：

`cursor`: 当sortType为3时且页数不是第一页时需传入,值为上一条数据的`time`

或许应该是：

`cursor`: 当sortType为3时且页数不是第一页时需传入,值为上一条数据的`cursor`

**Comment by Binaryify** [comment]
都可以,time是数组最后一条, cursor是外层的,两个是相等的值
