### ISSUE TITLE
邮箱登录接口失效了

### ISSUE THREAD

**Issue by silent-dxx** [Binaryify/NeteaseCloudMusicApi#120]
### 环境
系统:  Windows 10 64bit

nodejs 版本: v6.9.4

### 出现问题
邮箱登录接口失效了
```
{"msg":"疑似恶意登录，需要二次验证！","code":461}
```
### 期待效果

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/117
