### ISSUE TITLE
线上访问 /personalized/newsong 这个接口返回404

### ISSUE THREAD

**Issue by daiwanxing** [Binaryify/NeteaseCloudMusicApi#1206]
## 环境
- 系统/平台:  windows10 / Web

- nodejs 版本: v14.15.0

- API版本:  4.0.10

## 出现问题
本地启动服务调用 “推荐音乐” 接口： /personalized/newsong 无任何问题，通过vercel部署到线上调用此接口出现404，其他接口正常返回内容，不确定是否是部署环节出错了还是别的什么原因。

## 重现步骤
通过注册vercel，fork此项目，deploy该项目，在地址栏输入: https://music-api-chi.vercel.app/personalized/newsong
出现404

## 期待效果
期待返回正常结果

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
不知道为啥需要传一个realIp参数
https://music-api-chi.vercel.app/personalized/newsong?realIP=116.25.146.177

**Comment by daiwanxing** [comment]
> 不知道为啥需要传一个realIp参数，传了之后就好了
> https://music-api-chi.vercel.app/personalized/newsong?realIP=116.25.146.177
蟹蟹大佬！
