### ISSUE TITLE
需要表情库接口

### ISSUE THREAD

**Issue by mhxy13867806343** [Binaryify/NeteaseCloudMusicApi#1210]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
![3419a34b4d29011d5d4e65c5607780e](https://user-images.githubusercontent.com/4418166/115244631-b0c6a580-a156-11eb-93bb-2f41beb25807.png)
![fa00dccef36355dd8afa6d211736341](https://user-images.githubusercontent.com/4418166/115244634-b2906900-a156-11eb-8847-7b6b18302d04.png)

**Comment by Binaryify** [comment]
这个应该是客户端写死的

**Comment by mhxy13867806343** [comment]
好吧

**Comment by mhxy13867806343** [comment]
好吧
