### ISSUE TITLE
登录成功但是登录状态查询不正常

### ISSUE THREAD

**Issue by Archieeeeee** [Binaryify/NeteaseCloudMusicApi#1216]
## 环境
- 系统/平台: Fedora 34

- nodejs 版本: v14.16.0

- API版本: 4.0.11

## 出现问题
登录成功，返回了用户信息和cookie，但是查询登录状态是 {"data":{"code":200,"account":null,"profile":null}} ，有可能是哪里问题

**Comment by Binaryify** [comment]
加了时间戳吗

**Comment by Archieeeeee** [comment]
有可能，我重复登录几次后来ok了，我再试试

**Comment by wood3n** [comment]
@Archieeeeee  我也遇到了这个问题，请问你是怎么解决的？是接口加了时间戳吗？

**Comment by penguin0731** [comment]
> @Archieeeeee 我也遇到了这个问题，请问你是怎么解决的？是接口加了时间戳吗？
@Archieeeeee 同问

**Comment by penguin0731** [comment]
![image](https://user-images.githubusercontent.com/39406604/136643321-3a1d46a1-3016-42cb-9047-e938d73d74b0.png)
好像是cookie被覆盖了，但是后面这两个cookie我也不太清楚是哪来的

**Comment by huankong233** [comment]
加了时间戳，数据的获取还是有问题
