### ISSUE TITLE
为甚么登录后首页数据变少了？

### ISSUE THREAD

**Issue by wudeh** [Binaryify/NeteaseCloudMusicApi#1217]
## 环境
- 系统/平台: win10

- nodejs 版本: v14.15.1

- API版本: <4.0.11>

## 出现问题
首页不带cookie返回11组数组数据
![不带cookie](https://user-images.githubusercontent.com/44919545/116766514-7ebe1900-aa5d-11eb-84ea-de22540df014.png)
带cookie只返回4组数组数据，还有hasMore变成true
![带cookie](https://user-images.githubusercontent.com/44919545/116766520-8a114480-aa5d-11eb-8eeb-6e26858330ed.png)
想问下这是正常的吗？还是说还有除了refresh以外的参数可以控制？
如果是正常的话那是不是首页登录后要调一次不带cookie的请求和一次带cookie的请求，来组装所有数据啊？

## 期待效果
现在效果：登录后首页返回数据比不登录返回的数据少
期待效果：登录后首页返回的数据和不登录返回的数据一样多

**Comment by Binaryify** [comment]
晚点更新下

**Comment by Binaryify** [comment]
新版本加了cursor参数了

**Comment by wudeh** [comment]
感谢大佬！！

**Comment by cvilia** [comment]
> 
> 
> 感谢大佬！！

兄弟这个上一条数据的cursor是啥啊，我试了很多都不行

**Comment by wudeh** [comment]
> > 感谢大佬！！
> 
> 兄弟这个上一条数据的cursor是啥啊，我试了很多都不行

**Comment by wudeh** [comment]
> > 感谢大佬！！
> 
> 兄弟这个上一条数据的cursor是啥啊，我试了很多都不行

你要确保自己拿到cookie，这时候请求首页返回的cursor中就会有值了

**Comment by cvilia** [comment]
> 
> 
> > > 感谢大佬！！
> > 
> > 
> > 兄弟这个上一条数据的cursor是啥啊，我试了很多都不行
> 
> 你要确保自己拿到cookie，这时候请求首页返回的cursor中就会有值了

第一次请求首页数据的时候是有返回cursor的，但是数据特别长，就是下面这条数据，很郁闷
"cursor": "{"offset":5,"blockCodeOrderList":["HOMEPAGE_BANNER","HOMEPAGE_NEW_USER_WELCOME","HOMEPAGE_BLOCK_PLAYLIST_RCMD","HOMEPAGE_BLOCK_STYLE_RCMD","HOMEPAGE_MUSIC_MLOG","HOMEPAGE_BLOCK_MGC_PLAYLIST","HOMEPAGE_MUSIC_CALENDAR","HOMEPAGE_BLOCK_LISTEN_LIVE","HOMEPAGE_BLOCK_OFFICIAL_PLAYLIST","HOMEPAGE_BLOCK_NEW_ALBUM_NEW_SONG","HOMEPAGE_BLOCK_TOPLIST","HOMEPAGE_VOICELIST_RCMD","HOMEPAGE_BLOCK_FUN_CLUB","HOMEPAGE_PODCAST24","HOMEPAGE_BLOCK_VIDEO_PLAYLIST"]}",

**Comment by wudeh** [comment]
> > > > 感谢大佬！！
> > > 
> > > 
> > > 兄弟这个上一条数据的cursor是啥啊，我试了很多都不行
> > 
> > 
> > 你要确保自己拿到cookie，这时候请求首页返回的cursor中就会有值了
> 
> 第一次请求首页数据的时候是有返回cursor的，但是数据特别长，就是下面这条数据，很郁闷
> "cursor": "{"offset":5,"blockCodeOrderList":["HOMEPAGE_BANNER","HOMEPAGE_NEW_USER_WELCOME","HOMEPAGE_BLOCK_PLAYLIST_RCMD","HOMEPAGE_BLOCK_STYLE_RCMD","HOMEPAGE_MUSIC_MLOG","HOMEPAGE_BLOCK_MGC_PLAYLIST","HOMEPAGE_MUSIC_CALENDAR","HOMEPAGE_BLOCK_LISTEN_LIVE","HOMEPAGE_BLOCK_OFFICIAL_PLAYLIST","HOMEPAGE_BLOCK_NEW_ALBUM_NEW_SONG","HOMEPAGE_BLOCK_TOPLIST","HOMEPAGE_VOICELIST_RCMD","HOMEPAGE_BLOCK_FUN_CLUB","HOMEPAGE_PODCAST24","HOMEPAGE_BLOCK_VIDEO_PLAYLIST"]}",

对啊，就是这个数据

**Comment by cvilia** [comment]
穿错了值，郁闷

**Comment by Binaryify** [comment]
@cvilia 那个cursor就是这样的，不知道网易为啥这么设计

**Comment by cvilia** [comment]
> 
> 
> @cvilia 那个cursor就是这样的，不知道网易为啥这么设计

收到大佬回复

**Comment by ht-echo** [comment]
cursor传过去是会让返回的数据变长吗？我传了半天反应都没有...
