### ISSUE TITLE
项目部署成功后，外网无法访问

### ISSUE THREAD

**Issue by freedomwebcn** [Binaryify/NeteaseCloudMusicApi#1219]
## 环境
- 系统/平台: <腾讯云 centos7> ##服务器未备案

- nodejs 版本: <v14.16.1>

- API版本: <4.0.12>

## 出现问题
<项目在服务器启动后，在外网用IP 加 3000端口 无法访问>

## 重现步骤
服务器启动截图
![image](https://user-images.githubusercontent.com/43689316/117020547-1efb9280-ad29-11eb-9810-be8824a53745.png)

浏览器运行截图
![image](https://user-images.githubusercontent.com/43689316/117020718-481c2300-ad29-11eb-92ac-34a003f827f3.png)

**Comment by Binaryify** [comment]
你把腾讯云的安全组设置下开放端口

**Comment by freedomwebcn** [comment]
> 你把腾讯云的安全组设置下开放端口

谢谢，开放端口可以访问了。
