### ISSUE TITLE
php中使用curl()访问接口，如何给url添加cookie？

### ISSUE THREAD

**Issue by cslt-l** [Binaryify/NeteaseCloudMusicApi#1222]
## 环境
- 系统/平台: <ubuntu 18.04 server>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<v4.0.12>

## 出现问题
    **想用php curl()连接接口获取歌单。**
    **已确认使用手机号密码组合可以正常登陆，并获取到登录信息，保存了cookie到本地cookie.txt文件夹。**
    **现在想要通过cookie信息获取歌单，在已阅读**
”`如果是跨域请求 , 请在所有请求带上 xhrFields: { withCredentials: true } (axios 为 withCredentials: true, Fetch API 为 fetch(url, { credentials: 'include' })), 或直接手动传入cookie (参见 登录), 否则 可能会因为没带上 cookie 导致 301, 具体例子可看 public/test.html, 访问http://localhost:3000/test.html(默认端口的话) 例子使用 jQuery 和 axios`“以及登录中相关例子后仍无法理解如何使用cookie方式连接。

获取到的cooki信息包含：
MUSIC_U=cb8e3af8de917cf56c55020f8b395d7dea4……
__csrf=fae270ca991bced32d0……NMTID=00OWD4ALFc6qU_AwkaDiEQ__uIR2T……
__remember_me=true
SESSIONID=95fdb84c-991b-4348-b86e-fbcbe42933……
不解：如何通过以上信息完成以下内容‘cookie=xxx’中‘xxx’的替换？

?cookie=xxx (先使用 encodeURIComponent() 编码 cookie 值) 或者 post请求body带上 cookie 即可,如:/user/cloud?cookie=xxx

已经阅读过文档内容且已经查看issues，并且也搜索过链接如何添加cookie内容，因为个人能力有限不能解决，希望得到作者帮助，非常感谢！

## 重现步骤

个人理解的解密cookie并连接cookie如下：

192.168.1.11:3000/user/subcount？cookie=__csrf%3D8645c83ec3db…………………………%3A16%20GMT%3B%20Path%3D%2F%3B%3B__remember_me%3Dtrue%3B%20Max-Ag………………GMT%3B%20Path%3D%2F%3B%3BMUSIC_U%3Dcb8e3af8de917cf56c55020f8………………122f119c33a649814e309366%3B%20Max-Age%3D1296000%3B%20Expires%3DSat%2C%………………ath%3D%2F%3B%3BNMTID%3D00OWD4ALFc6qU_AwkaDiEQ__uIR2TUAAAF5RYTeqQ%3B%20Max-Age%3D315360000%3B%20Expir……………………MT%3B%20Path%3D%2F%3B

（注：其中……是马赛克）

## 期待效果
<现在的效果，期待的效果>  

希望获得作者帮助，非常感谢！

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭 

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
你的问号是全角的

**Comment by cslt-l** [comment]
请问在使用encodeURIComponent()编码时，
是将以下内容以分号”；“连接还是”&“连接？并且是将以下四个信息全部编码进cookie吗？
```
MUSIC_U=cb8e3af8de917cf56c55020f8b395d7dea4……
__csrf=fae270ca991bced32d0……NMTID=00OWD4ALFc6qU_AwkaDiEQ__uIR2T……
__remember_me=true
SESSIONID=95fdb84c-991b-4348-b86e-fbcbe42933……
```

**Comment by Binaryify** [comment]
整段encode

**Comment by cslt-l** [comment]
非常感谢，已经成功调用个人歌单信息！祝您生活愉快！
