### ISSUE TITLE
希望增加 手机号+验证码登陆

### ISSUE THREAD

**Issue by Uyouii** [Binaryify/NeteaseCloudMusicApi#1227]
**手机号+验证码登陆**
- 目前用户对隐私保护意识越来越强，裸的密码调用方式很容易引起用户反感，希望可以增加手机号+验证码登陆的方式

**Comment by greenhat616** [comment]
这个不是支持的么

**Comment by Binaryify** [comment]
这个接口官方是用ip形式调用的，和其他接口不一样，暂时加不了

**Comment by Uyouii** [comment]
> 这个接口官方是用ip形式调用的，和其他接口不一样，暂时加不了

明白啦，感谢～

**Comment by Binaryify** [comment]
可以考虑二维码登录

**Comment by Binaryify** [comment]
已经支持了
