### ISSUE TITLE
部分接口返回的数据中同一个字段的数据类型不同

### ISSUE THREAD

**Issue by cvilia** [Binaryify/NeteaseCloudMusicApi#1236]
## 环境
- 系统/平台: CentOS 8.2 64位

- nodejs 版本: docker容器运行

- API版本: <4.0.12>

## 出现问题
首页-发现接口返回的数据中，blocks字段返回的数组中，数组元素的extInfo字段值有两种类型，一种是数组，一种是普通类型，如下面json所示
{"blocks": [ { "extInfo": [{ "alg": "vs-hp-t7#i2i-hpv4##"} ]},{ "extInfo": {"banners": [ { "bannerId": "1620922160790459"}] } }]}，
在解析数据的时候会造成冲突，只能解析出来一种类型且是那种类型在json中靠前，最终解析的就是该种类型，上面的例子最终解析出来的是普通的ExtInfo类型，如果json中两种类型调换位置的话，最终解析出来的是List<ExiInfo>集合

## 期待效果
希望修改一下不同类行所对应的字段名，例如下面例子所示
{"blocks": [ { "extInfo": [{ "alg": "vs-hp-t7#i2i-hpv4##"} ]},{ "bannerextInfo": {"banners": [ { "bannerId": "1620922160790459"}] } }]}，

**Comment by Binaryify** [comment]
这个不是我能改的，我这只负责转发网易的接口，逻辑只能你自己处理
