### ISSUE TITLE
首页发现接口，返回的 JSON 数据中的 logInfo 字段能否改一个格式

### ISSUE THREAD

**Issue by ShenJieSuzhou** [Binaryify/NeteaseCloudMusicApi#1238]
## 环境
- 系统/平台: <你的系统和平台>
Mac OS/iOS 
- nodejs 版本: <你的 NodeJS 版本号>
v10.16.3
- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
4.0.9
## 出现问题

调用接口 ---首页发现，返回的 JSON 数据中有一个字段为 logInfo，它目前的格式为："logInfo": "{\"category1\":\"song\",\"category2\":\"1824020873\"}"
现在这个格式用 Swift 的 Codable 无法解析。

## 重现步骤

接口：localhost:3000/homepage/block/page

错误信息：
`
Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 4481." UserInfo={NSDebugDescription=Badly formed object around character 4481.}))

`

## 期待效果

目前的格式为："logInfo": "{\"category1\":\"song\",\"category2\":\"1824020873\"}"
能否改成 "logInfo": "{\\"category1\\":\\"song\\",\\"category2\\":\\"1824020873\\"}" 这种格式返回。

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
这个就是网易那边给的原汁原味的数据
里面的你再parse一次就行了
![image](https://user-images.githubusercontent.com/12221718/118790837-b8e64200-b8c8-11eb-8c20-ccab7416f8ce.png)
