### ISSUE TITLE
云贝签到接口失效

### ISSUE THREAD

**Issue by zwsn** [Binaryify/NeteaseCloudMusicApi#1239]
## 环境
- 系统/平台: MacOS11.3.1

- nodejs 版本: v14.11.0

- API版本: 4.0.12

## 出现问题
云贝签到接口失效

**Comment by Binaryify** [comment]
无法重现

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/119350393-db65ca00-bcd1-11eb-8efe-aac43d7840fb.png)
