### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by greenhat616** [Binaryify/NeteaseCloudMusicApi#1249]
![image](https://user-images.githubusercontent.com/41122242/120063443-cdc98f00-c099-11eb-9b75-b4d82a5fdb09.png)
![image](https://user-images.githubusercontent.com/41122242/120063936-4af60380-c09c-11eb-8ee0-b4526de343f9.png)

使用 4.x 后存在未处理的 `Error: read ECONNRESET` 错误。错误是在 `process.on('uncaughtException')` 中捕获的。昨天调试了蛮长时间，发现程序逻辑存在bug，里面捕获的错误提交不到 sentry，现在利用 sentry 追踪，发现极有可能是 SDK 这边存在未捕获问题。

**Comment by greenhat616** [comment]
![image](https://user-images.githubusercontent.com/41122242/120063578-66600f00-c09a-11eb-82e4-33a0efe2f6fc.png)
出现还比较频繁=，= 我先再服务这边手动处理下忽略吧

**Comment by greenhat616** [comment]
我先测试下老版本(v3)会不会出现这问题

**Comment by greenhat616** [comment]
好像又不是这的问题。我先关闭了。

**Comment by Binaryify** [comment]
嗯
