### ISSUE TITLE
关于获取歌曲时长的疑问？

### ISSUE THREAD

**Issue by FCMore** [Binaryify/NeteaseCloudMusicApi#125]
### 环境
系统:  
windows
nodejs 版本:
8.1.3
### 出现问题
歌曲详情里，歌曲的时长是哪个接口啊？ duration？感觉不对啊
### 重现步骤
...
### 期待效果
...

**Comment by CallMeHunter** [comment]
dt

**Comment by FCMore** [comment]
嗯嗯，知道了，那个是毫秒，大意了，谢谢了！
