### ISSUE TITLE
Chrome91更新导致跨域不携带Cookie

### ISSUE THREAD

**Issue by Flysky12138** [Binaryify/NeteaseCloudMusicApi#1257]
[Chrome更新到91版本后](https://www.chromium.org/updates/same-site) 移除了 `#same-site-by-default-cookies` 设置项。默认 `SameSite=Lax` ，现无法修改 `#same-site-by-default-cookies` 值，致使跨域不携带Cookie的问题解决不了。

我使用的Axios，并且设置了 `axios.defaults.withCredentials = true`

**Comment by Binaryify** [comment]
手动传cookie吧
