### ISSUE TITLE
歌曲url 403

### ISSUE THREAD

**Issue by guanbiao33** [Binaryify/NeteaseCloudMusicApi#126]
获取到的url网页中引用403，是网易改策略了吗？

**Comment by hwaphon** [comment]
我也是哎，怎么搞的

**Comment by hwaphon** [comment]
我已经在网上找到解决方案，当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id=id.mp3 以src 赋予 Audio即可播放

**Comment by Binaryify** [comment]
@hwaphon 这个方法不错,等下更新到文档里

**Comment by qianduanzhou** [comment]
歌曲url无效了

**Comment by qianduanzhou** [comment]
@hwaphon 的方法也不顶用
