### ISSUE TITLE
希望添加云盘关键词搜索功能

### ISSUE THREAD

**Issue by wlor0623** [Binaryify/NeteaseCloudMusicApi#1265]
**功能描述**
- 希望添加云盘关键词搜索功能 云盘的歌曲太多了 目前/user/cloud不能通过关键字来过滤

**Comment by chen310** [comment]
> **功能描述**
> 
> * 希望添加云盘关键词搜索功能 云盘的歌曲太多了 目前/user/cloud不能通过关键字来过滤

通过`/user/cloud`接口获取所有云盘歌曲，再在返回的结果里搜索。貌似网易云的客户端就是这么做的
