### ISSUE TITLE
歌单详情只能获取前20首歌曲

### ISSUE THREAD

**Issue by TheresaQWQ** [Binaryify/NeteaseCloudMusicApi#1266]
## 环境
- 系统/平台: Vercel
- API版本: 4.0.16

## 出现问题
歌单详情只能获取前20首歌曲了，貌似是网页端的限制导致的

## 重现步骤
随便找个歌曲多的歌单都会这样

## 期待效果
能获取完整歌曲列表

**Comment by TheresaQWQ** [comment]
貌似自己的歌单没有这个问题，别人的歌单就会这样

**Comment by chen310** [comment]
和

> 貌似自己的歌单没有这个问题，别人的歌单就会这样

#784

**Comment by dufu1991** [comment]
文档已经写了，歌单详情只会返回20条，需要更多要用返回的全部歌曲ID再请求歌曲详情接口。
