### ISSUE TITLE
在 Electron 里使用邮箱登录方法返回 250 错误。

### ISSUE THREAD

**Issue by lutianxiong** [Binaryify/NeteaseCloudMusicApi#1268]
## 环境
- 系统/平台: windows10/Electron 13.1.0

- nodejs 版本: 14.16.0

- API版本: 4.0.16

## 出现问题
在 Electron 里使用 login (邮箱) 方法进行登录返回 250 当前登录失败，请稍后再试错误。

## 重现步骤
![image](https://user-images.githubusercontent.com/42662202/121621258-6ac6f780-ca9e-11eb-94bf-33806ccb61b2.png)
![image](https://user-images.githubusercontent.com/42662202/121621298-7e725e00-ca9e-11eb-9942-ed34e888fd0e.png)

## 期待效果
可以完成邮箱登录。

**Comment by Surene** [comment]
手机能登陆吗，我的报250错误

**Comment by lutianxiong** [comment]
> 手机能登陆吗，我的报250错误

不可以, 登录全是250

**Comment by Binaryify** [comment]
是只在electron报错吗，nodejs直接调会报错吗

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/121983426-e5a45100-cdc3-11eb-8f1f-1b051db50986.png)
看看是不是这里导致的

**Comment by lutianxiong** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/121983426-e5a45100-cdc3-11eb-8f1f-1b051db50986.png)
> 看看是不是这里导致的

这三个错误暂时不知道怎么解决。。。
在 node 里通过 module 无法登录，通过 url 的形式可以登录。

**Comment by Binaryify** [comment]
@lutianxiong 你nodejs下报啥错

**Comment by lutianxiong** [comment]
> @lutianxiong 你nodejs下报啥错，也是250错误？

是的, nodejs 下通过 module 报 250 错误.

**Comment by lutianxiong** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/121983426-e5a45100-cdc3-11eb-8f1f-1b051db50986.png)
> 看看是不是这里导致的

目前知道问题所在了，我在 electron 的主进程当中使用登录方法就可以登陆成功，因为不是浏览器环境。如果在渲染进程中使用就报 250 错误。

**Comment by jcdomt** [comment]
主进程就行了，谢谢
