### ISSUE TITLE
登陆后响应头信息有set-cookie，可是浏览器不计入cookie储存，导致很多借口返回301.求解..

### ISSUE THREAD

**Issue by ZhaoMeiling0501** [Binaryify/NeteaseCloudMusicApi#127]
### 环境
系统:  

nodejs 版本:
v6.11.2

### 出现问题
我这边localhost登录了，响应头信息也有set-cookie，但是浏览器并没有设置对应的cookie，导致我请求很多数据都显示301.

### 期待效果
网上查找类似情况，五花八门的说法，但是都悬而未决，请问有没有大神可以指点下 QAQ  不甚感激！

**Comment by ZhaoMeiling0501** [comment]
浏览器计入了cookie，但是请求数据还是返回301.。。。。
api里console.log打日志看到，cookie没有获取成功
QAQ  明明浏览器已经记录了，求教

**Comment by ZhaoMeiling0501** [comment]
看文档写着：- 301 错误基本都是没登录就调用了需要登录的接口,如果登陆了还是提示 301, 基本都是缓存把数据缓存起来了,解决方法是等待 2 分钟或者重启服务重新登录后再调用接口

可是试了很多遍重启和进入app.js取消2分钟缓存，都还是显示301
实在困扰良多，如果有良方，不胜感激

**Comment by Binaryify** [comment]
请问能提供具体的操作过程吗

**Comment by ZhaoMeiling0501** [comment]
谢谢大大看到回复
先是调用手机登录接口（端口号还是默认的3000）→
 http://localhost:3000/login/cellphone  传入手机号和密码，登录成功
（浏览器cookie也通过设置ajax  withCredentials: true记录好了）
之后点击签到，调用签到接口 →
 http://localhost:3000/user/detail 返回code 301
调用每日推荐接口 → http://localhost:3000/recommend/songs  同样返回code 301

在大大你写的 util.js 打日志，cookie是空字符串  不知是不是我前端代码有问题，困扰呐

**Comment by Binaryify** [comment]
使用 ajax 请求的是吧

**Comment by ZhaoMeiling0501** [comment]
是的，最开始用axios，登录响应头信息的set-cookie浏览器不计入，
搜到网上类似情况的解决方法要设置 withCredentials: true，就用ajax登录了..
但是签到和每日推荐的接口请求还是沿用的之前写的axios交互

**Comment by Binaryify** [comment]
确定每个请求都有带 cookies 吗

**Comment by ZhaoMeiling0501** [comment]
请问 loginCellphone.js里的
res.set({
        'Set-Cookie': cookie
      })

我应该在哪里获取Set-Cookie的值？

**Comment by Binaryify** [comment]
应该是你的 `withCredentials: true` 设置没生效
给你个 jquery 版的试试
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
  <script>
    $.ajax({
      url: "http://localhost:3000/login/cellphone?phone=13169670619&password=z00000",
      success: function (data) {
        console.log(data)
        $.ajax({
          url: "http://localhost:3000/recommend/songs ",
          xhrFields: {
            withCredentials: true
          },
          success: function (data) {
            console.log(data)
          },
          error: function (err) {
            console.log(err)
          }
        })
      },
      error: function (err) {
        console.log(err)
      }
    })
  </script>
</body>

</html>
```

**Comment by ZhaoMeiling0501** [comment]
大大！我太感谢你了   QAQ
真的是我的设置没生效的问题
用你给的demo修改了下，就获取到了
困扰好久的问题总算有起色了~谢谢谢 ；）

**Comment by Binaryify** [comment]
不客气

**Comment by ldc2726** [comment]
请问我怎么登录的时候请求的时候浏览器没有设置cookie呢
