### ISSUE TITLE
在获取的数据中没有确切的数据来表示哪一首是网易云独家歌曲，想要标注“独家”下标时没有依据

### ISSUE THREAD

**Issue by illusione** [Binaryify/NeteaseCloudMusicApi#1270]
## 环境
- 系统/平台: <微信开发者工具>

- nodejs 版本: <14.15.2>

- API版本: <4.0.10>

## 出现问题
在获取的数据中没有确切的数据来表示哪一首是网易云独家歌曲，想要标注“独家”下标时没有依据

如下图是通过搜索《还是会想你》获取数据的第一首歌《还是会想你》，演唱者为林达浪/h3R3，在网易云PC端中显示为独家歌曲，这条数据的最外层的copyrightId=0，而在album对象中的copyrightId=-1

![image](https://user-images.githubusercontent.com/67743568/121794179-d3e27280-cc38-11eb-8bbc-a5e399efd2ce.png)

如下图是获取数据的第二首歌，在网易云PC端中也显示为独家歌曲，这条数据的最外层的copyrightId=0，在album对象中的copyrightId=0

![image](https://user-images.githubusercontent.com/67743568/121794342-ed37ee80-cc39-11eb-8fbe-4eff94dedd2e.png)

如下图是获取数据的第四首歌，在网易云PC端中显示不是独家歌曲，这条数据的最外层的copyrightId=0，在album对象中的copyrightId=0

![image](https://user-images.githubusercontent.com/67743568/121794352-05a80900-cc3a-11eb-9bd4-fd9c01e2bb9d.png)

通过这三组对照无法判断哪一首歌为独家版权歌，烦请知道判断独家歌曲，或者判断VIP歌曲的朋友告知一下，界面中只是显示一排排歌曲文字信息确实有些苍白，下标标注一下会好看不少🙏

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
<请清晰描述现在的效果和期待的效果>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by chen310** [comment]
flag和64按位与，得到的结果不为0就是独家的

**Comment by illusione** [comment]
> flag和64按位与，得到的结果不为0就是独家的

能告知下“flag和64”是什么吗😅

**Comment by chen310** [comment]
> > flag和64按位与，得到的结果不为0就是独家的
> 
> 能告知下“flag和64”是什么吗😅

比如这首"少女的祈祷"，id为29593497，使用`song/detail`获得如下数据
![msedge_vey3eILfRo](https://user-images.githubusercontent.com/33364396/123223938-e9428100-d503-11eb-8911-51228884720f.png)
`privilege.flag`为68，和64按位与，即1000100&1000000=1000000，不为0，即为独家

**Comment by illusione** [comment]
> > > flag和64按位与，得到的结果不为0就是独家的
> > 
> > 
> > 能告知下“flag和64”是什么吗😅
> 
> 比如这首"少女的祈祷"，id为29593497，使用`song/detail`获得如下数据
> ![msedge_vey3eILfRo](https://user-images.githubusercontent.com/33364396/123223938-e9428100-d503-11eb-8911-51228884720f.png)
> `privilege.flag`为68，和64按位与，即1000100&1000000=1000000，不为0，即为独家

谢谢老哥，确实是这样👍
