### ISSUE TITLE
weapi的听歌打卡/scrobble 接口可能被云音乐屏蔽了。

### ISSUE THREAD

**Issue by qwsf01115** [Binaryify/NeteaseCloudMusicApi#1276]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
经过测试，登录帐号后调用“听歌打卡/scrobble”对某一首音乐进行播放后，播放量没有增加，感觉这个接口大概率是被云音乐屏蔽了。

## 期待效果
如果可以，能不能提供一个PC端接口，经过测试在PC端不需要登录听某一首歌也有播放量，感谢。

**Comment by wangxsaw** [comment]
兄弟，有可用接口吗
