### ISSUE TITLE
云音乐歌手榜传入type报参数错误

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#1286]
## 环境
- 系统/平台: window10

- nodejs 版本: 9..11.2

- API版本: 4.0.16

## 出现问题
云音乐歌手榜传入type报参数错误
![QQ截图20210708144248](https://user-images.githubusercontent.com/38646454/124876038-288cc980-dffc-11eb-8a02-01fbd90ea9d6.png)
![QQ截图20210708144318](https://user-images.githubusercontent.com/38646454/124876053-2c205080-dffc-11eb-9b9d-7809aa9662b7.png)

## 期待效果
传入区分地区的type正常请求回数据

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
传的是数字

**Comment by refuse-c** [comment]
行吧  我傻了      那你close了吧 QAQ

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月8日 17:37
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 云音乐歌手榜传入type报参数错误 (#1286)


传的是数字

―
