### ISSUE TITLE
[Question] 关于登录和刷新的一些疑问

### ISSUE THREAD

**Issue by wby238** [Binaryify/NeteaseCloudMusicApi#129]
调用refresh总是返回400，这是为什么？
还有就是怎样获取这个cookies是否过期了呢？
再次调用cellphone_login的时候相同账号密码调用是否会重新登录一次呢？试了看发现cookies、登录时间什么的都没变。
顺便问一下`推荐歌单`跟`获取每日推荐歌单`这两个有什么区别吗？

**Comment by Binaryify** [comment]
刷新 400 是因为缓存的问题,前5分钟获取不到 Cookie
不知道该怎么处理这个缓存的问题
