### ISSUE TITLE
音乐人任务详情获取不完整

### ISSUE THREAD

**Issue by Demontisa** [Binaryify/NeteaseCloudMusicApi#1290]
## 环境
- 系统/平台: Ubuntu 20.04

- nodejs 版本: v10.19.0

- API版本: 4.0.16

## 出现问题

未手动完成音乐人任务就不能获取到任务的UserMissionid，手动完成任务后才能获取到任务的UserMissionid

## 重现步骤
- 正常登录获取cookie
- 调用/musician/tasks 获取不到 userMissionid(未手动在网易云完成任务的情况下)

**Comment by chen310** [comment]
设定就是如此，只有完成任务了才会出现`UserMissionid`，这时才能用`UserMissionid`去获取云豆

**Comment by Demontisa** [comment]
> 设定就是如此，只有完成任务了才会出现`UserMissionid`，这时才能用`UserMissionid`去获取云豆

我指的是手动领取一次云豆才能获取到UserMissionid

**Comment by chen310** [comment]
> > 设定就是如此，只有完成任务了才会出现`UserMissionid`，这时才能用`UserMissionid`去获取云豆
> 
> 我指的是手动领取一次云豆才能获取到UserMissionid

不能吧，不应该呀

**Comment by chen310** [comment]
> > 设定就是如此，只有完成任务了才会出现`UserMissionid`，这时才能用`UserMissionid`去获取云豆
> 
> 我指的是手动领取一次云豆才能获取到UserMissionid

`/musician/tasks`返回的数据中`status`字段为任务状态，0表示任务未开始，10表示任务正在进行中，20表示任务完成，但未领取云豆，100表示任务完成，并且已经领取了相应的云豆。我加了音乐人签到的接口，你可以到pull requests里看看
