### ISSUE TITLE
希望增加腾讯云函数部署或者是51云盒子部署，

### ISSUE THREAD

**Issue by xiaoqix** [Binaryify/NeteaseCloudMusicApi#1295]
**功能描述**
-vercel好用方便是不错，但时不时被墙，希望能兼容腾讯云函数或者51云盒子这些能在国内的服务器部署

**Comment by Mamong** [comment]
为啥不用云容器，云函数成本有点大

**Comment by AIEOV** [comment]
> 腾讯云部署很简单，按照腾讯云官方的文档改一下就行，我已经跑了
老哥  能加个微信吗 云函数求教呀

**Comment by xiaoqix** [comment]
> 腾讯云部署很简单的，按照腾讯云官方的文档改一下就行，我已经跑上了

你怎么弄的，求教一下

**Comment by Binaryify** [comment]
文档加了腾讯云serverless部署步骤说明
