### ISSUE TITLE
1. 歌单收藏/取消收藏接口异常,2分享接口异常

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#1300]
系统/平台: window10
nodejs 版本: 9.11.2
API版本: 4.0.17

1. 歌单收藏/取消收藏接口</playlist/subscribe>; 收藏的歌单可以取消成功,但是无法收藏(提示错误:'请求过于频繁',但是我并没有很快的去请求数据,附图)
![image](https://user-images.githubusercontent.com/38646454/126597947-808c442b-a179-4fce-a178-fc7fe91a2344.png)
![image](https://user-images.githubusercontent.com/38646454/126598025-47e10559-5c34-4619-ad82-62ddcd1872c0.png)

2.分享接口</share/resource>(目前开发的有单曲:song, 歌单:playlist,专辑:album均提示分享异常,附图)
![QQ图片20210722143509](https://user-images.githubusercontent.com/38646454/126598577-af58924c-8c7e-49a6-b91a-242727022548.png)

**Comment by Binaryify** [comment]
拉下代码再试试

**Comment by refuse-c** [comment]
好了 现在没问题了 😊
________________________________
发件人: binaryify ***@***.***>
发送时间: 2021年7月23日 9:19
收件人: Binaryify/NeteaseCloudMusicApi ***@***.***>
抄送: xiangbh ***@***.***>; Author ***@***.***>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 1. 歌单收藏/取消收藏接口异常,2分享接口异常 (#1300)


拉下代码再试试
