### ISSUE TITLE
请求返回信息内容格式有误

### ISSUE THREAD

**Issue by btea** [Binaryify/NeteaseCloudMusicApi#1303]
## 环境
- 系统/平台: windows10

- nodejs 版本: 14.15.3

- API版本: 4.0.17

## 出现问题
在请求获取音乐url的接口 `song/url` 时，当参数不对，比如 `id=null` , 接口会返回报错信息，但信息是重复的，导致解析字符串会出错。  
经排查，在请求接口 `https://interface3.music.163.com/eapi/song/enhance/player/url` 时，返回的 `res.data` 里面信息就是重复的。
![image](https://user-images.githubusercontent.com/24516654/126856897-e041b627-90b8-42bd-b74f-1cf215c0a3d8.png)

**Comment by Binaryify** [comment]
你单独处理异常吧，这个网易给过来的就是这样子

**Comment by btea** [comment]
好的

**Comment by Binaryify** [comment]
我怀疑网易找了实习生写出来的

**Comment by btea** [comment]
> 我怀疑网易找了实习生写出来的

哈哈，很有可能
