### ISSUE TITLE
<获取粉丝数据接口出现问题>

### ISSUE THREAD

**Issue by wei1826676931** [Binaryify/NeteaseCloudMusicApi#1305]
## 环境
-windows10

- nodejs 版本: <v14.17.3.>

- API版本: <4.0.17>

## 出现问题
获取用户粉丝列表的api：/user/followeds 只能拿到1000条粉丝信息，很多粉丝数大于1000的用户offset设置大于1000的时候，返回的全是重复的数据。
所以这个是因为网易云服务器那边限制了？还是其他的问题？

## 重现步骤
![image](https://user-images.githubusercontent.com/52347799/126892452-01e3deb3-052b-48ef-9139-1e4e1ff55292.png)
![image](https://user-images.githubusercontent.com/52347799/126892462-b1716831-35fd-423c-a9f9-a3bfe7de9c68.png)

## 期待效果
拿到所有粉丝数据

**Comment by Binaryify** [comment]
应该网易那边限制了

**Comment by wei1826676931** [comment]
好滴，谢谢你啦~




祝：身体健康~开开心心~工作顺利~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月26日(星期一) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] <获取粉丝数据接口出现问题&gt; (#1305)





 
应该网易那边限制了

**Comment by Binaryify** [comment]
嗯嗯
