### ISSUE TITLE
服务器上播放歌曲经常会被403

### ISSUE THREAD

**Issue by fqingyu** [Binaryify/NeteaseCloudMusicApi#1309]
## 环境
- 系统/平台: Linux 3.2104 

- nodejs 版本: 不需要

- API版本: 4.0.16

## 出现问题
服务器架在阿里云上，播放歌曲时会时不时跳403 forbidden. 本地运行就不会有这个错误。歌曲用的播放方法参考文档， 把audio的src改成https://music.163.com/song/media/outer/url?id=${id}.mp3

## 重现步骤
http://47.94.216.140/ 可以参考我目前已经架设的项目。首页原创榜中的歌曲随便点两首来回切换，console里就会发生403报错。
播放区域：
![image](https://user-images.githubusercontent.com/25810389/128091559-4b4cc132-17a9-421f-a985-55d402d0a2d7.png)
报错：
![image](https://user-images.githubusercontent.com/25810389/128091483-7103c98d-9237-477c-81fd-d1ccbe0fe806.png)

## 期待效果
有没有合适的解决方案避免403？

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by MicroCBer** [comment]
好家伙，你这是抄了一个网易云啊
我现在是直接在本地缓存了一份，，

**Comment by fqingyu** [comment]
> 好家伙，你这是抄了一个网易云啊
> 我现在是直接在本地缓存了一份，，

纯粹练手用的hhh  能具体说一下方法吗 我没有太理解这个本地缓存一份

**Comment by MicroCBer** [comment]
（虽然我觉得你这个如果用我这个方法服务器存储会爆炸）
可以参考[我做的一个小玩意](https://github.com/MicroCBer/live-songplayer)
就是每次第一次放某首歌的时候，先将它下载到本地
下一次直接用本地的mp3放
~~我也是被逼的啊，海外如果直接放链接的话放一会就会断掉....这个小东西就是给一个在外国的国人朋友写的~~

**Comment by MicroCBer** [comment]
然后可以写个定期清理啥的（不过我没写 我写了个bat手动清理

**Comment by a-yangyi** [comment]
照 #244 的说法 应该发生在cookie更新的时候 csrf_token值没更新到 为了验证 退出重新登录了一下 收藏成功

**Comment by MicroCBer** [comment]
> 照 #244 的说法 应该发生在cookie更新的时候 csrf_token值没更新到 为了验证 退出重新登录了一下 收藏成功

我是登录功能根本不会用

nodejs的文档好缺啊 哎

**Comment by XiaoMengXinX** [comment]
服务器在海外吗？在海外的话试试把 mXXX.music.126.net 解析到国内 cdn 试试

**Comment by zzr771** [comment]
请问解决了吗, 我也是遇到这个问题, 而且是每次都403, 只有之前正常返回了一次.

**Comment by MicroCBer** [comment]
> 你本地的网络环境在国外吗？在国外的话试试改 hosts 把 mXXX.music.126.net 解析到国内 cdn

是在国外，解析到国内cdn试过了，没用

**Comment by MicroCBer** [comment]
> 请问解决了吗, 我也是遇到这个问题, 而且是每次都403, 只有之前正常返回了一次.

目前是先下载再播放
另外弄了一个hook 网易云pc的，可以用
