### ISSUE TITLE
是否适合高频访问？

### ISSUE THREAD

**Issue by pyyzcwg2833** [Binaryify/NeteaseCloudMusicApi#131]
我想在将这个项目部署在服务器上，对我的音乐播放器提供api。
请问部署在服务器上频繁调用是否服务器ip会被网易限制访问呢？

**Comment by rccoder** [comment]
@pyyzcwg2833 你可以自己做一层缓存，缓存无法命中再去请求网易

**Comment by Binaryify** [comment]
这个项目已经做了缓存处理了
