### ISSUE TITLE
服务报错TypeError: {} is not a function

### ISSUE THREAD

**Issue by 2415091026** [Binaryify/NeteaseCloudMusicApi#1320]
## 环境
- 系统/平台: win10

- nodejs 版本:v14.17.0

- API版本: 4.0.18

## 出现问题
从昨天更新了4.0.18后就不能用了，在接口目录下node [app.js能够启动服务，
![Snipaste_2021-08-10_17-14-37](https://user-images.githubusercontent.com/83115172/128841273-10915b87-9837-49a8-8e4c-fcb82d613997.png)
访问http://localhost:3000报错
![Snipaste_2021-08-10_17-16-21](https://user-images.githubusercontent.com/83115172/128841436-d28a57f8-1b34-4965-863a-2b128cae5a4e.png)
在项目中调接口报错
![Snipaste_2021-08-10_17-17-34](https://user-images.githubusercontent.com/83115172/128841634-00e43bc8-9fc9-4bf5-9512-5bb213484992.png)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
调用/banner接口报错
![Snipaste_2021-08-10_17-19-50](https://user-images.githubusercontent.com/83115172/128842310-9509f997-6418-49cb-bbb6-9c9845120b42.png)

## 期待效果
能够正常使用  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
拉下最新代码

**Comment by 2415091026** [comment]
> 感谢解决了
