### ISSUE TITLE
建议.gitignore添加package-lock.json

### ISSUE THREAD

**Issue by a76yyyy** [Binaryify/NeteaseCloudMusicApi#1321]
**功能描述**
- 建议.gitignore添加package-lock.json，避免不同平台npm install出现问题

**Comment by Binaryify** [comment]
.gitignore添加package-lock.json 会导致 github action 报错的

**Comment by a76yyyy** [comment]
> .gitignore添加package-lock.json 会导致 github action 报错的

可以在readme里进行相关的说明或指示

**Comment by xiezht** [comment]
package-lock文件本身就是为了处理npm包版本不一致问题而存在的，不应该被ignore掉的。
