### ISSUE TITLE
图片资源过大，希望返回压缩后的图片资源

### ISSUE THREAD

**Issue by callmehui** [Binaryify/NeteaseCloudMusicApi#1325]
## 环境
- 系统/平台: <mac>

- nodejs 版本: <v14.8>

- API版本: <4.0.19>

## 出现问题
<接口：/top/song返回的图片资源过大(几百kb到十几Mb)，而且无法修改分页默认返回100条，不知道网易云有没有压缩后的图片资源字段，直接加载的话非常卡顿；接口：/album/new返回的图片资源过大(几百kb到十几Mb)>

## 重现步骤
<本地调用接口/top/song，加载到页面，资源太多太大直接加载失败>

## 期待效果
<希望接口能够返回一个压缩后的图片资源字段（如果有的话）>

**Comment by Binaryify** [comment]
调用前须知读一下

**Comment by dufu1991** [comment]
请看须知，图片URL后面拼接参数可以获取对应大小。

**Comment by callmehui** [comment]
不好意思，就开始的时候看到了，经你们提醒想起来了。
