### ISSUE TITLE
统一各api的key

### ISSUE THREAD

**Issue by JackuXL** [Binaryify/NeteaseCloudMusicApi#1326]
如题
/user/cloud 请求自带一个 simplesong 包装
/search/ 有"album" "artists"
/song/detail 的album叫"al" artists 叫 "ar"
我的软件是统一解析数据的，如果这样还需要特判，而且个人认为在api中使用省略的写法会导致可读性很差

**Comment by JackuXL** [comment]
@Binaryify

**Comment by Binaryify** [comment]
返回内容是网易给的

**Comment by JackuXL** [comment]
> 返回内容是网易给的

那能不能在返回之前统一一下

**Comment by JackuXL** [comment]
@Binaryify

**Comment by Binaryify** [comment]
你那边做下映射吧,我这边映射会影响其他人使用的

**Comment by dufu1991** [comment]
API 只能按照官方数据处理，我们自己都是自己做一个封装。不然已经上线的 APP 又要修改了。

**Comment by JackuXL** [comment]
> 你那边做下映射吧,我这边映射会影响其他人使用的

能不能大概指点一下修改哪个js文件可以修改返回的数据 @Binaryify

**Comment by Binaryify** [comment]
不好意思，现在才看到
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/1c05f8f57dcea5c53262c62767b096e5eddc7d68/app.js#L116
这行代码之前改下answer.body就行
