### ISSUE TITLE
artist/songs获取歌手全部歌曲，返回的歌曲数据没有歌曲封面

### ISSUE THREAD

**Issue by dufu1991** [Binaryify/NeteaseCloudMusicApi#1329]
artist/songs获取歌手全部歌曲，返回的歌曲数据没有歌曲封面。与其他获取歌曲信息的接口都已不一致。
比如返回这样：
al: {id: 25429, name: "勇气", pic_str: "109951163240604120", pic: 109951163240604130}
id: 25429
name: "勇气"
pic: 109951163240604130
pic_str: "109951163240604120"

其他接口返回的正常，有picUrl：
al: {id: 25429, name: "勇气",…}
id: 25429
name: "勇气"
pic: 109951163240604130
picUrl: "https://p1.music.126.net/PavIMxZq16K7-0fSF5n-yg==/109951163240604120.jpg"
pic_str: "109951163240604120"
tns: []

不知道是不是网易云官方就有问题。

**Comment by Binaryify** [comment]
客户端里全部歌曲没有封面的

**Comment by dufu1991** [comment]
不用不知道，这个官方的接口也是有点混乱，很多地方一样的信息不统一。

**Comment by Binaryify** [comment]
@dufu1991 嗯是的，估计是迭代了很多版本，导致各种不统一，分页也是各种不统一，还有些接口怀疑是实习生写的
