### ISSUE TITLE
希望能把二维码登陆直接生成二维码图片

### ISSUE THREAD

**Issue by guyinga** [Binaryify/NeteaseCloudMusicApi#1331]
**功能描述**
- 目前的二维码登陆，返回数据只是一个官方链接，如果能直接返回二维码图片就好了。

**Comment by dufu1991** [comment]
这个链接就是二维码登录需要的信息啊，而且参数可以控制返回 base64 图片还是二维码信息的啊。

**Comment by unomisa** [comment]
有base64的，直接用就行

**Comment by Euphoriahz** [comment]
直接用base64编码转二维码图片就行
