### ISSUE TITLE
部分歌曲上传云盘时提示404错误

### ISSUE THREAD

**Issue by xiezht** [Binaryify/NeteaseCloudMusicApi#1332]
## 环境

- Mac OS 11.3

- nodejs 版本: v12.16.1

- API版本: 4.0.19

## 出现问题

上传某些歌曲到云盘时提示404的错误。

## 重现步骤

接口：/cloud

调用方式：node模块方式调用以及使用postman调用

上传结果：截图如下

![image](https://user-images.githubusercontent.com/18051618/130396596-88a30dfa-a8ec-4497-a0f5-f93b7ea236f6.png)

可以确认cookie是完整携带的。

并且并非所有歌曲文件都会出现这样的结果，有的是可以正常上传的

提供两个目前验证出有问题的文件：

* [歌曲1](https://netease-music-xiezht.oss-cn-beijing.aliyuncs.com/transcoding/%E9%80%83%E8%B7%91%E8%AE%A1%E5%88%92%20-%20Is%20This%20Love.mp3
)
* [歌曲2](https://netease-music-xiezht.oss-cn-beijing.aliyuncs.com/transcoding/%E6%A2%81%E5%8D%9A%20-%20%E6%97%A5%E8%90%BD%E5%A4%A7%E9%81%93%20%28Live%29.mp3)

nodejs 接口调用报错信息：

```
2021-08-23T05:11:45.536Z 61232E095423BA35363CA607 [verbose] error {
  status: 400,
  statusText: 'Bad Request',
  headers: {
    server: 'openresty/1.9.15.1',
    date: 'Mon, 23 Aug 2021 05:11:45 GMT',
    'content-type': 'application/json;charset=UTF-8',
    'content-length': '142',
    connection: 'close',
    'access-control-allow-origin': '*'
  },
  config: {
    url: 'http://45.127.129.8/ymusic/obj%2FwoDDmMOBw6PClWzCnMK-/10483367147/43e3/5b0f/389a/db885fa961cf6c1bc5a4fab32d5bd786.data?offset=0&complete=true&version=1.0',
    method: 'post',
    data: <Buffer 49 44 33 03 00 00 00 00 20 4b 54 50 45 31 00 00 00 0b 00 00 01 ff fe 03 90 d1 8d a1 8b 12 52 54 49 54 32 00 00 00 1b 00 00 01 ff fe 49 00 73 00 20 00 ... 3465668 more bytes>,
    ......
  },
  data: {
    requestId: '2635b58c2d7f0000000061232e118109',
    errCode: 'InvalidArgument',
    errMsg: 'BucketName or ObjectName dismatch In URL & Policy'
  }
}
2021-08-23T05:11:45.674Z 61232E095423BA35363CA607 [error] 处理失败 {
  status: 404,
  body: { msg: 'rep create failed', code: 404 },
  cookie: []
}
2021-08-23T05:11:45.675Z 61232E095423BA35363CA607 [error] {"errorMessage":"{\"status\":404,\"body\":{\"msg\":\"rep create failed\",\"code\":404},\"cookie\":[]}"}
```

## 期待效果

目前效果：上传失败，报错404，报错信息为："rep create failed"

期待效果：上传成功

**Comment by pilipala6868** [comment]
+1，排查了一下，是 https://music.163.com/api/upload/cloud/info/v2 这个接口301了，但是也不知道新的url是啥

**Comment by pilipala6868** [comment]
就是 /cloud/upload/check 通过的曲子就是网易云已经有的曲目数据，所以可以正常上传；但 check 后 needUpload 的曲子，就需要调 upload/cloud/info/v2 上传，但这个接口已经永久重定向了，所以上传失败
现在得找到新的url，但苦于身边没有windows电脑没法获取接口地址，还得麻烦 @Binaryify 大佬

**Comment by Binaryify** [comment]
这个我周末看看

**Comment by Binaryify** [comment]
已修复，是`http://45.127.129.8`这个接口用到的bucket发生了改变

**Comment by Xiaolong00** [comment]
这个404复现了大佬

**Comment by Binaryify** [comment]
@Xiaolong00 无法复现

**Comment by AzraelJi** [comment]
能否批量上传

**Comment by Binaryify** [comment]
@AzraelJi 参考 /public/cloud.html

**Comment by akane** [comment]
我有许多文件都能复现这个问题，不过某个文件如果拿到windows客户端上传过一次，后面这个文件就能上传成功。

例子：
[tmp.mp3.zip](https://github.com/Binaryify/NeteaseCloudMusicApi/files/13557465/tmp.mp3.zip)

我自己抓包有看到很多新的API，可能只是因为客户端不同，因为返回结果差不多。

```
http://music.163.com/eapi/cloud/upload/check
http://musicupload.netease.com/api/whale/token/alloc
http://musicupload.netease.com/eapi/upload/cloud/info/v2
```
