### ISSUE TITLE
有什么接口可以增加需要登录的天数

### ISSUE THREAD

**Issue by yibail** [Binaryify/NeteaseCloudMusicApi#1335]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
每日的签到 听歌打卡都没增加过天数

**Comment by yushuohuanxiu** [comment]
> **功能描述**
> 
> * 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
>   每日的签到 听歌打卡都没增加过天数

你好，请问此问题有解决方案了吗？

**Comment by Binaryify** [comment]
不是这个仓库的功能
