### ISSUE TITLE
最新版本/video/group接口获取分类/标签下的视频，返回的数组中每一项data.urlInfo是空的，获取不到视频地址

### ISSUE THREAD

**Issue by coder-chin** [Binaryify/NeteaseCloudMusicApi#1342]
## 环境
- 系统/平台: < windows10 >

- nodejs 版本: <v14.17.1>

- API版本: <4.0.20>

## 出现问题
接口获取分类/标签下的视频接口，请求/video/group返回结果后，数组中每一项中data,urlInfo都是空的，这里面应该含有每个视频的地址
![image](https://user-images.githubusercontent.com/79465534/131639970-d67b982b-6c8c-49ed-bf2a-b1a09d717c5a.png)

## 重现步骤
![image](https://user-images.githubusercontent.com/79465534/131640362-9fa18943-3570-4eb5-9055-1cc321fd9f23.png)
空的

## 期待效果
![image](https://user-images.githubusercontent.com/79465534/131639801-32e4c83c-2c6d-4cdd-b7a5-c1bc148114d7.png)

**Comment by oyal** [comment]
我也是无法获取视频详情地址

**Comment by oyal** [comment]
用老版本吧，老版本可以

**Comment by Binaryify** [comment]
可能网易节省查表数吧
用 /video/url 再查一次一样的
![image](https://user-images.githubusercontent.com/12221718/148045404-865ddc5d-aae6-46de-83f4-528cea56f2a6.png)

**Comment by xupan123456** [comment]
可以下载另一个server文件
