### ISSUE TITLE
NodeJS API 不使用代理的设置问题

### ISSUE THREAD

**Issue by seven-mile** [Binaryify/NeteaseCloudMusicApi#1343]
## 环境

- 系统/平台: Ubuntu 18.04

- nodejs 版本: 14.17.1

- API版本: 新旧都测过

## 出现问题

NodeJS API 的 `option.proxy` 设为 `undefined` 时无法达到“不使用代理”的效果。导致在我的机器上发送请求失败。

原因在于 [这个部分](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/077a347d411db8de3101ebe0915a217be54852e4/util/request.js#L125) 设置 axios 的代理设置时，`settings.proxy` 的默认值为 `undefined`，而 axios 的 proxy 设置区分 `undefined` 与 `false`，前者会使用系统代理（如 `http_proxy` 环境变量），而后者才是一定不使用代理。

## 重现步骤

直接控制变量复现

## 期待效果

希望对这两种行为在外围 API 上增加配置，或者其它方案，总之目前无法达到设置“不使用代理”的效果。

---

**Comment by Binaryify** [comment]
好了，看看有没有问题

**Comment by seven-mile** [comment]
谢谢！我的问题已经解决了，那么我先把issue关闭了。不过目前的改法也有向前兼容的隐患，小概率有其他用户的少部分代码依赖于原先的语义，不是什么大问题，你可以自行决断。

**Comment by Binaryify** [comment]
应该问题不大
