### ISSUE TITLE
音乐url失效问题

### ISSUE THREAD

**Issue by dengzhao7053** [Binaryify/NeteaseCloudMusicApi#135]
### 环境
系统:  Ubuntu 

nodejs 版本: 最新

### 出现问题 :音乐url在一段时间后会失效,再次请求该url会报错,
ERROR
The requested URL could not be retrieved
 The following error was encountered:
    Access Denied.
    The access control configuration prevents your request at this time. Please contact your service provider if you feel this is incorrect. 

### 期待效果:请问这个问题有什么好的解决办法吗

**Comment by Binaryify** [comment]
参考这个
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90-url

**Comment by Binaryify** [comment]
注:部分用户反馈获取的 url 会 403,hwaphon找到的解决方案是当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id=id.mp3 以src 赋予 Audio即可播放

**Comment by kevinvane** [comment]
全部音频都有mp3格式吧？会不会出现其他格式的音频，如果会的话，还是要多请求一次获取type参数。

**Comment by Binaryify** [comment]
@kevinvane 可能会有 flac 格式

**Comment by dengzhao7053** [comment]
谢谢up主的解答，我一开始用的http://music.163.com/weapi/song/enhance/player/url这种方法获取的url，然后就出现了url过几分钟会失效的问题，第二个方法完美解决了
