### ISSUE TITLE
cloud 接口的interface参数定义不完整

### ISSUE THREAD

**Issue by mayday5555** [Binaryify/NeteaseCloudMusicApi#1356]
## 环境
- 系统/平台: macos

- nodejs 版本: 12.19.0

- API版本: 4.0.22

## 出现问题
在interface.d.ts定义中关于cloud接口的定义
`export function cloud(params: RequestBaseConfig): Promise<Response>`
没有参数songFile。而在实际的使用中是需要这个参数的。

**Comment by Binaryify** [comment]
更新看看
