### ISSUE TITLE
关于歌手下的热门50单曲

### ISSUE THREAD

**Issue by dengzhao7053** [Binaryify/NeteaseCloudMusicApi#136]
### 环境
系统:  Ubuntu 16.04

### 出现问题
 你好，我是一名android开发，所以不大看得懂node.js代码。
 我看获取歌手下的热门50单曲好像是 http://music.163.com/weapi/v1/artist/89365?offset=0&limit=50
这个post请求，但是我模拟了请求，却没有返回，不知道是哪不对

### 期待效果 希望up主看看是不是我哪里错了，谢谢

**Comment by Binaryify** [comment]
不能直接请求的,需要中转,这也是这个项目的意义

**Comment by dengzhao7053** [comment]
哦 有的接口好像直接请求也能用，如果要配合安卓的话，是要把这个你的这个项目放在服务器是吗？

**Comment by dengzhao7053** [comment]
哦 发现有的接口直接请求也能用，如果要配合安卓的话，是不是要把这个项目放到服务器呢?

**Comment by Binaryify** [comment]
是
