### ISSUE TITLE
你好，请问API中有关于一首歌的总时长的API嘛

### ISSUE THREAD

**Issue by ZhangWeijie-Z** [Binaryify/NeteaseCloudMusicApi#1361]
你好，请问API中有关于一首歌的总时长参数嘛

_Originally posted by @ZhangWeijie-Z in https://github.com/Binaryify/NeteaseCloudMusicApi/discussions/1051#discussioncomment-1378805_

**Comment by NatsuKawaKo** [comment]
duration字段就是时长，要换算
