### ISSUE TITLE
密码登录接口有问题了 一直返回密码错误 使用短信验证码登录 返回数据只有状态识别码

### ISSUE THREAD

**Issue by 991772538** [Binaryify/NeteaseCloudMusicApi#1363]
## 环境
- 系统/平台: <win11>

- nodejs 版本: <14.17.3>

- API版本: <4.0.23>

## 出现问题
<
使用密码登录 直接返回密码502密码错误

{
    "msg": "密码错误",
    "code": 502,
    "message": "密码错误"
}
使用验证码登录只返回状态码  不返回其他任何值

{
    "code": 200,
    "data": true
}
>
![QQ截图20210927183102](https://user-images.githubusercontent.com/29569873/134892651-275a5d65-53ee-406f-9a32-34e17f3849d2.png)

![QQ图片20210927182736](https://user-images.githubusercontent.com/29569873/134892609-1c7f5dd7-c1f9-439c-9097-305a42f15446.png)
![QQ截图20210927183413](https://user-images.githubusercontent.com/29569873/134892769-238e6cf2-4c77-4e35-aa29-df20d2eb73a3.png)

**Comment by Binaryify** [comment]
1. 无法重现
2. 验证码登陆是/login/cellphone接口

**Comment by YXL76** [comment]
同问题
