### ISSUE TITLE
可以添加获取每日乐签的图片嘛？

### ISSUE THREAD

**Issue by nuyoahaoyun** [Binaryify/NeteaseCloudMusicApi#1365]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
- 可以添加获取每日乐签的图片嘛？在用户签到会有每日推荐的歌曲还会配图
如图：http://p1.music.126.net/JIJeRp6L8jd3PknJTLKR0g==/109951166464783748.jpg

**Comment by Binaryify** [comment]
更新了

**Comment by nuyoahaoyun** [comment]
> 更新了

在官方文档中没看到接口例子，是文档没更新哪

**Comment by Binaryify** [comment]
有缓存，多刷新下
/sign/happy/info 这个接口
