### ISSUE TITLE
排行榜最近突然获取不到完整数据

### ISSUE THREAD

**Issue by vincewi** [Binaryify/NeteaseCloudMusicApi#137]
### 环境
系统:  Windows Server 2008

nodejs 版本:8.6.0

### 出现问题
最近突然发现每个排行榜的榜单只有一首歌，之前获取的是完整的榜单。如/top/list?idx=6，tracks里只有一首歌。好像现在网易云音乐排行榜榜单的种类也有变化。
### 期待效果
希望大神修复这个问题

**Comment by have-not-BUG** [comment]
对的  我也准备提这个issue的       http://music.163.com/api/playlist/detail?id=3778678 官方api的也只有一首歌   @vincewi

**Comment by kevinvane** [comment]
我也出现了这个问题，看网易云APP的排行榜是完整的

**Comment by Binaryify** [comment]
马上修复

**Comment by Binaryify** [comment]
已修复
