### ISSUE TITLE
查询‘我喜欢的音乐’歌单详情，报错。20001：登陆后才可查看

### ISSUE THREAD

**Issue by llllllllll4er5ty** [Binaryify/NeteaseCloudMusicApi#1374]
## 环境
- 系统/平台: <MacOS Big Sur>

- nodejs 版本: <10.16.3>

- API版本: <4.0.23>

## 出现问题
<调用歌单详情接口（/playlist/detail?id=），查询 ‘我喜欢的歌单’，cookie也传了，返回结果提示 “登陆后才可查看”>

## 重现步骤
1.登录账号
2.获取用户歌单
3.查询歌单详情，报错
    查询其他歌单可以正常返回，但是只返回10条记录，说明cookie没传对，是没登录状态，查询 ‘我喜欢的歌单’时，会报错：
![image](https://user-images.githubusercontent.com/28029815/136925019-85c4f23c-eda4-4d08-aacf-7a4015988565.png)
    猜测：cookie是从登录后的用户信息中取的，猜测cookie解析有误

## 期待效果
正常返回歌单详情

**Comment by zhongzi26** [comment]
遇到了同样的问题 等待修复

**Comment by lijiajunply** [comment]
我也是这样的问题，请问一下是怎么修复的
