### ISSUE TITLE
跨域过后 登录获取Cookile会报错

### ISSUE THREAD

**Issue by 991772538** [Binaryify/NeteaseCloudMusicApi#1375]
## 环境
- 系统/平台: <Windows11>

- nodejs 版本: <14.17.3>

- API版本: <4.0.23>

## 出现问题
<
跨域调用登录接口 保存CooKile的时候会报错，网上查询了下说登录验证换成token校验才是更合理的解决方案，这个登录验证能换成token验证吗？
>

![QQ图片20211016222227](https://user-images.githubusercontent.com/29569873/137591326-861e813c-3f40-427a-9f58-a432e63e44f5.png)

**Comment by Binaryify** [comment]
文档里有提到的
![image](https://user-images.githubusercontent.com/12221718/137608528-3be61c77-7b2a-42f2-862b-2cb2afc74a83.png)
