### ISSUE TITLE
新版评论接口获取歌曲以外的评论会报参数错误，且返回的推荐和热门评论结果相同

### ISSUE THREAD

**Issue by Bubble-419** [Binaryify/NeteaseCloudMusicApi#1377]
## 环境
- 系统/平台: <Windows/小程序使用>

- nodejs 版本: <14.16.0>

- API版本: <4.0.23>

## 出现问题
1. 新版评论接口获取歌曲以外的评论会报参数错误
2. 新版评论接口返回的推荐和热门结果是相同的

## 重现步骤
1. 调用173.新版评论接口，参数是一个合法的歌单id以及值为2的type参数，结果报参数错误。
![image](https://user-images.githubusercontent.com/58065379/137700314-0b340dea-bb23-4a0a-8d97-1bc345d366eb.png)
返回结果如下：
![image](https://user-images.githubusercontent.com/58065379/137700479-e0d8a342-0b39-49ca-b3d6-39099722fc77.png)
新版评论接口在获取歌曲评论时是可行的，但是歌单评论却不行。

2. 调用173.新版评论接口，参数合法，一切正常，但是sortType参数不论是1还是2，获得的结果都是推荐评论，热门评论需要单独调用获取172.热门评论接口才能获得。

## 期待效果
希望能修改173新版评论接口，使得该接口可以真正获取其他资源类型的评论，以及可以获取到热门评论。
作者大大辛苦啦！

**Comment by Binaryify** [comment]
已修复，再看看
