### ISSUE TITLE
用户当前是否已签到的接口

### ISSUE THREAD

**Issue by Bacuuu** [Binaryify/NeteaseCloudMusicApi#1384]
**功能描述**
- 在用户信息等接口中未找到用户是否已经签到的字段，如果已经有烦请告知下。
- 如果没有相关接口希望能够增加当前登录用户签到状态的接口。

**Comment by LTDSA** [comment]
直接请求 `/daily_signin` 即可，返回状态码若不为 200 即已签到。

**Comment by Bacuuu** [comment]
[v4.5.3版本](https://github.com/Binaryify/NeteaseCloudMusicApi/releases/tag/v4.5.3)新增支持
接口地址：`/signin/progress`
🙏感谢社区维护人员
