### ISSUE TITLE
能否添加歌词的音标

### ISSUE THREAD

**Issue by oldpotter** [Binaryify/NeteaseCloudMusicApi#1385]
**功能描述**
- 有些歌词是有翻译和音标的，目前好像没有音标的接口吧？能否添加
![image](https://user-images.githubusercontent.com/13828653/139351950-9fd21cb9-35e4-4c19-bd7e-70bce55e86e8.png)

**Comment by kengwang** [comment]
这个罗马音是网易云音乐客户端转换的,服务端暂无相关接口

**Comment by kengwang** [comment]
可以在 Github 上搜索 `romaji` 找寻转换的项目
要注意某些转换不支持 `Kanji` (漢字)　转 `Romaji` (罗马音)
比如 `夕陽時計の針のように 影が背伸びしていく` 应当被转换成 `yu u hi to ke i no ha ri no yo u ni  ka ge ga se no bi shi te i ku` 而不是 `夕陽時計no針noyouni 影ga背伸bishiteiku `
Javascript 的 推荐 https://github.com/hexenq/kuroshiro

**Comment by kengwang** [comment]
顺带一提: 注音方式 `Hepburn` (黑本式 / 平文式) / `Nippon` (日本式) / `Passport` (训令式)
区别见 https://zh.wikipedia.org/wiki/%E8%AE%AD%E4%BB%A4%E5%BC%8F%E7%BD%97%E9%A9%AC%E5%AD%97
目前以 平文式 (Hepburn) 最为常用, 也好像是网易云音乐选用的注音方式
