### ISSUE TITLE
我是前端学习者，纯后端小白，有关于新版本API的cookie、token设置问题

### ISSUE THREAD

**Issue by hx1497** [Binaryify/NeteaseCloudMusicApi#1386]
## 环境
- 系统/平台: win7

- nodejs 版本: v12.16.3

- API版本: 4.0.23

## 出现问题
我在vue用axios， baseURL设置的是 我在heroku部署的地址 ，在获取从登录获取的COOKIE和token之后，将token设置在请求头上，但是设置以后，发出的请求就发生错误，大致意思是这个请求头不被接受；然后我又将请求头设置了cookie，但是直接被chrome拦截了，所以想请问一下大大，我该咋解决这个问题呀

## 重现步骤
我用手机号登录，之后就用id获取用户信息  baseURL/user/detail?uid=xxxxx 这时候请求头是设置了cookie的然后报错
![image](https://user-images.githubusercontent.com/57715973/139523445-08366b04-93d2-442e-9d63-af99077fb865.png)
我将请求头换成token再获取信息的时候报错信息是：
![image](https://user-images.githubusercontent.com/57715973/139523526-1961d7d5-62c4-4040-8460-f49a997869ce.png)
所以想请问一下大大这个问题该如何解决呀？
## 期待效果
希望能解决headers不能带token或者cookie的问题

**Comment by hx1497** [comment]
不用劳烦大大，我看到文档里有写解决方案！！！

**Comment by wuxiaolan91** [comment]
报跨域错误cors的话你设置web服务代理就好（推荐做法）
或者打开火狐浏览器
因为这个cors是谷歌拦截火狐不拦截的。
