### ISSUE TITLE
关于云贝签到的问题

### ISSUE THREAD

**Issue by LittleControl** [Binaryify/NeteaseCloudMusicApi#1387]
## 环境
- 系统/平台: Linux

- nodejs 版本: 12.x

- API版本: 4.0.23

## 出现问题

当调用打卡签到接口完成后,再调用云贝签到总是会给出重复签到的错误信息

## 重现步骤

1. 调用`/daily_signin`两次,第一次默认参数是Android端签到,第二次传入参数`{type: 1}`Web端签到
2. 然后再调用`/yunbei/sign`接口,总是会提示重复签到

## 期待效果

调用云贝签到后提示成功签到

## Others

是否现在日常签到包含了对于云贝签到的内容?所以日常打卡签到后再调用云贝签到的接口提示重复签到

**Comment by XiaoMengXinX** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/6c3743959e0af5e6d47d5f193b7529153a15e58f/module/yunbei_sign.js#L5
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/ea86e5bbeb5a81c4416459afdb1beeb412c254a5/module/yunbei_rcmd_song_history.js#L12

都是一个 API
云贝签到本质上就是 Android 客户端每日签到（

**Comment by XiaoMengXinX** [comment]
![image](https://user-images.githubusercontent.com/19994286/140593560-bb46c799-68bb-47d0-8634-9c6cfdaf3a4b.png)

两个平台签到都有芸豆奖励

**Comment by LittleControl** [comment]
好的好的,明白了,辛苦解答
