### ISSUE TITLE
非VIP不能下载无损，可是Windows客户端可以

### ISSUE THREAD

**Issue by Chen03** [Binaryify/NeteaseCloudMusicApi#1388]
## 环境
- 系统/平台: Windows 10

- nodejs 版本: v16.13.0

- API版本: 4.0.23

## 出现问题
非VIP账户，在网易云windows客户端可以下载非VIP下载的无损音质flac文件，但是用`/song/url`好像最高只能获取320000的mp3文件

## 重现步骤
登陆后找一首有无损音质的歌曲，调用`/song/url`，比如`/song/url?id=38689091`，只能返回320000码率的mp3文件
而在网易云客户端，只要单曲下载，就可以选择无损音质，并且下载下来确实是646k码率的flac
（其实iOS也有这个选项，但没办法验证是不是真的无损……）

## 期待效果
获取到flac

*不知道是bug还是功能问题，就放来这里了……*

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by XiaoMengXinX** [comment]
自己测试了一下，非 VIP 账号使用 `/api/song/enhance/download/url` 这个 API 可以下载部分歌曲无损

![image](https://user-images.githubusercontent.com/19994286/140594457-58420d49-cc09-4a29-99be-52633fd2cee4.png)

而试听 API ( `/api/song/enhance/player/url/v1` )只能获取非无损歌曲

![image](https://user-images.githubusercontent.com/19994286/140594515-73a37852-7324-492a-846a-96c3661e65c6.png)

**Comment by XiaoMengXinX** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/pull/1391

提了个pr，应该可以解决你的问题

**Comment by SaigyoujiYuyuko233** [comment]
api我记得暗改了 好像设置br参数不好用了 我用的是
```json
{"ids": [114514], "level": "exhigh","encodeType": "mp3","csrf_token": ""}
```
level 用 exhigh

**Comment by XiaoMengXinX** [comment]
> api我记得暗改了 好像设置br参数不好用了 我用的是
> 
> ```json
> {"ids": [114514], "level": "exhigh","encodeType": "mp3","csrf_token": ""}
> ```
> 
> level 用 exhigh

这是两个不同的api，一个是 `/song/enhance/player/url` 一个是 `/song/enhance/player/url/v1` 新老api都能用

**Comment by XiaoMengXinX** [comment]
> api我记得暗改了 好像设置br参数不好用了 我用的是
> 
> ```json
> {"ids": [114514], "level": "exhigh","encodeType": "mp3","csrf_token": ""}
> ```
> 
> level 用 exhigh

另外 csrf_token 可以忽略

**Comment by XiaoMengXinX** [comment]
> api我记得暗改了 好像设置br参数不好用了 我用的是
> 
> ```json
> {"ids": [114514], "level": "exhigh","encodeType": "mp3","csrf_token": ""}
> ```
> 
> level 用 exhigh

直接用浏览器访问就行（
https://music.163.com/api/song/enhance/player/url/v1?encodeType=mp3&level=lossless&ids=[34478640]
