### ISSUE TITLE
推荐歌单中的图片，进行canvas操作时跨域了，能不能代理一下

### ISSUE THREAD

**Issue by thiszhangjin** [Binaryify/NeteaseCloudMusicApi#139]
Access to Image at 'https://p1.music.126.net/nAX5mdVWbqegJmxW9JLiOQ==/19241453486536960.jpg' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by Binaryify** [comment]
可自己实现图片转发的

**Comment by gjfei** [comment]
图片转发的搞定了吗？
