### ISSUE TITLE
播放歌单内的全部歌曲接口

### ISSUE THREAD

**Issue by viprui520** [Binaryify/NeteaseCloudMusicApi#1392]
**功能描述**

![IMG_20211113_145815](https://user-images.githubusercontent.com/39665667/141610369-7119129f-29a6-470d-91f7-cfc67c99c1d2.jpg)
看了一下开发文档只有播放歌单内的单曲的接口，没有播放歌单内的全部歌曲接口，就像客户端上面的播放全部的按钮，如果有这个功能麻烦告知一下是哪个接口，如果没有的话后期能否考虑增加？谢谢

**Comment by luanbuneng** [comment]
这个需要你自己实现的，点播放全部的时候将歌单的歌都放进一个列表里面（比如MusicList），如果播放第一首你就可以根据MusicList[0].id去获取音源播放，下一首同理。

**Comment by QuXiang-code** [comment]
我觉得，你之前调了一次接口比方说查出来20首，你也拿到这个total，你点播放全部又去请求一次接口，传入这个total，然后把所有歌曲加到播放列表
