### ISSUE TITLE
登录验证问题

### ISSUE THREAD

**Issue by re-ovo** [Binaryify/NeteaseCloudMusicApi#1399]
几个小问题，想问问 🤔

1. 网易云自己的客户端也是用的这种cookie验证身份的吗? 有没有其他验证方式? 我看登录成功后的返回数据中有个token，那是干嘛用的
2. `/login/refresh`这个接口具体作用是什么，我看文档只写了`调用此接口 , 可刷新登录状态`, 刷新登录状态是指?

**Comment by Binaryify** [comment]
你把cookie存起来当token，然后放请求body里也可以的
/login/refresh 是刷新cookies的，调用获取新的cookies
