### ISSUE TITLE
关于缓存问题

### ISSUE THREAD

**Issue by chen310** [Binaryify/NeteaseCloudMusicApi#1400]
A登录之后访问了某个接口，在缓存过期前，B也访问了相同的接口，那么B由可能会获取到A的个人信息。能不能把cookie加到缓存的key里面，那么每个人得到的就不会是其他人的信息

**Comment by Binaryify** [comment]
这个自己按需改造吧，这个项目本来就不是为了让多人使用的

**Comment by chen310** [comment]
> 这个自己按需改造吧，这个项目本来就不是为了让多人使用的

好的
