### ISSUE TITLE
推荐系统如何工作？

### ISSUE THREAD

**Issue by re-ovo** [Binaryify/NeteaseCloudMusicApi#1409]
网易云是靠什么推荐歌曲的，需要客户端主动上传播放了什么歌曲吗? 还是说他只靠红心歌曲推荐，不红心的歌就不算? 
还有官方是怎么知道听了用户多少歌的 ？我看官方好像要求每首歌听一分钟以上才算，它怎么知道我听了多久呢？

在搞一个第三方app，怕推荐系统不工作，特此问下这些问题

**Comment by Binaryify** [comment]
要上报的，这个项目有上报接口，但是要发什么没整理
