### ISSUE TITLE
手机登录，报密码错误

### ISSUE THREAD

**Issue by jessjava** [Binaryify/NeteaseCloudMusicApi#141]
### 环境
系统:  mac

nodejs 版本:8.1.2

### 期待效果 怎么拿到 token

**Comment by Binaryify** [comment]
密码错误就是密码错误了

**Comment by duhongjun** [comment]
+1 在客户端能登上, 用接口登录提示密码错误🤢

**Comment by Binaryify** [comment]
@jessjava 
@duhongjun 
确定是手机登录吗

**Comment by jessjava** [comment]
确定呀。~~~登陆多了就给我的 ip 停掉了

**Comment by Binaryify** [comment]
@jessjava 能否提供你现在的密码,然后你把你现在的密码修改成另外一个,我用你现在的密码测试下

**Comment by jessjava** [comment]
我知道问题了。因为我密码中有&符号。修改之后可以了。多谢。

**Comment by Binaryify** [comment]
@jessjava 如果是 post 的话不用考虑特殊字符,如果 get 中包含 & 这些特殊字符需要使用 encodeURIComponent
