### ISSUE TITLE
调用 search 搜索歌曲时返回的所有歌曲对应的图片都是相同的且都指向无封面默认图片

### ISSUE THREAD

**Issue by 4o4E** [Binaryify/NeteaseCloudMusicApi#1420]
## 环境
- 系统/平台: `Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- nodejs 版本: `v16.13.1`

- API版本: `4.2.0`

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>
调用 `search` 搜索歌曲时返回的所有 `img1v1Url` 都是相同的且都指向无封面默认图片

并且 `picUrl` 返回的都是null

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

例如 `search?keywords=海阔天空`

返回的json中 `img1v1Url` 都是 `6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg`

(虽然资源域名不同, 但是指向的都是无封面默认图片)

而 `cloudsearch` 可以获得正确的结果(不用cloud搜索是因为cloud中有时会搜出和主题没什么关系的歌)

## 期待效果
<请清晰描述现在的效果和期待的效果>  
 `search` 接口返回正确的 `img1v1Url`

 `picUrl` 为正常封面

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
搜索就是没图片的，只有专辑有图片

**Comment by 4o4E** [comment]
> 搜索就是没图片的，只有专辑有图片

明白了

**Comment by Frostnova00** [comment]
嗯...想要得到正确的图片url该调用哪个API呢？
