### ISSUE TITLE
我需要一个关于入驻歌手的接口

### ISSUE THREAD

**Issue by EwboKing** [Binaryify/NeteaseCloudMusicApi#1422]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
我在API始终无法找到如何获取入驻歌手的信息，我可以获取热门歌手华语歌手等等唯独缺失这个，请问有这个接口吗
![WX20211217-152200](https://user-images.githubusercontent.com/92979795/146505635-8f163e61-4e2d-4449-b33d-7aeb86b3eee6.png)

**Comment by Binaryify** [comment]
网页那个是老接口，建议直接用客户端的歌手列表接口
![image](https://user-images.githubusercontent.com/12221718/146509473-b2e8dfc8-5cee-497e-aa04-fff9fce901c8.png)
