### ISSUE TITLE
退出登录接口

### ISSUE THREAD

**Issue by Clownsw** [Binaryify/NeteaseCloudMusicApi#1426]
## 环境
- 系统/平台: Windows 20H2

- nodejs 版本: v14.17.5

- API版本: 4.2.0

## 出现问题
请求退出登录接口后, 请求获取账户信息接口还能获取信息

## 重现步骤
1. npm run start
2. 请求登录接口
3. 请求退出接口
4. 请求获取信息接口

## 期待效果
退出登陆后, 请求回去信息接口不能获取信息

**Comment by Binaryify** [comment]
确认不是缓存问题吗

**Comment by Clownsw** [comment]
> 确认不是缓存问题吗

清空缓存后还是无效

**Comment by hu19940121** [comment]
确实有问题， 调用logout接口后 服务也重启了一下 还是能请求获取账户信息接口

**Comment by Binaryify** [comment]
把cookies清空
