### ISSUE TITLE
歌曲解析失败

### ISSUE THREAD

**Issue by mashirozx** [Binaryify/NeteaseCloudMusicApi#143]
### 环境
系统:  Ubuntu 17.04

nodejs 版本: 8.9.1

### 出现问题
同一首歌在我的电脑上能解析，放到服务器上就不能解析了。请问是否与海外服务器有关？
（评论等数据均能正常解析）

### 重现步骤
[暂时保留该进程=。=](https://music.api.shino.cc/)

### 期待效果

**Comment by Binaryify** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%b0%83%e7%94%a8%e5%89%8d%e9%a1%bb%e7%9f%a5

**Comment by mashirozx** [comment]
@Binaryify 抱歉没仔细看文档，打扰了

**Comment by mashirozx** [comment]
抱歉再打扰一下~ 添加了似乎还是不行，是我写错地方了吗？QAQ
```js
const http_client = http.request(
      {
        hostname: 'music.163.com',
        method: method,
        path: path,
        headers: {
          Referer: 'http://music.163.com',
          Cookie: 'appver=1.5.2',
          'Content-Type': 'application/x-www-form-urlencoded',
          'User-Agent': randomUserAgent(),
          'X-Real-IP':'183.192.255.142'
        }
      },
```
