### ISSUE TITLE
获取最近播放歌曲失败

### ISSUE THREAD

**Issue by QWKk** [Binaryify/NeteaseCloudMusicApi#1431]
http://**/record/recent/song?limit=1
返回Cannot GET /record/recent/song

**Comment by Binaryify** [comment]
无法重现
![image](https://user-images.githubusercontent.com/12221718/148201714-441769d9-f4d1-454f-ada2-93874d472d35.png)

**Comment by QWKk** [comment]
![无标题](https://user-images.githubusercontent.com/58714401/148364651-72f72abd-9a65-468a-b156-f5e4c97d5f43.png)

**Comment by QWKk** [comment]
是需要cookie子类的信息吗？postman也是不行
