### ISSUE TITLE
请求将本项目发布到npm

### ISSUE THREAD

**Issue by cweijan** [Binaryify/NeteaseCloudMusicApi#1439]
Hi, 如果将本项目发布到npm后，在其他项目引入只要安装依赖就能使用，无需clone本项目了，npm上现在有一个https://www.npmjs.com/package/NeteaseCloudMusicApi, 但看起来不是作者发布的。

**Comment by Binaryify** [comment]
那个就是我发布的

**Comment by cweijan** [comment]
哦哦， 好的。
