### ISSUE TITLE
调用发送/删除评论的时候返回"风险提示

### ISSUE THREAD

**Issue by d6382060** [Binaryify/NeteaseCloudMusicApi#1442]
## 环境
- 系统/平台: <windows 10>

- nodejs 版本: <v14.17.3>

- API版本: <4.0.23>

## 出现问题
<在调用发送/删除评论的时候返回"风险提示"  换了2个号都是这样>

## 重现步骤
<调用的接口：/comment 
在点击发送按钮时候调用函数，发送请求，返回参数出错。
所带参数：
![QQ图片20220117205406](https://user-images.githubusercontent.com/84716501/149772871-acde5997-4709-4c8c-995c-7856f371257a.png)

返回错误参数：
![QQ图片20220117205519](https://user-images.githubusercontent.com/84716501/149772981-e04c312f-904b-4f88-baad-ce0a42b465f6.png)

>

---

**Comment by crazybox521** [comment]
点赞也是这样，可能对应接口做了限制了，以前可以的

**Comment by chen310** [comment]
已提交 pr
