### ISSUE TITLE
官方在Vercel部署的接口中，获取歌单所有歌曲的接口报错

### ISSUE THREAD

**Issue by SnowingFox** [Binaryify/NeteaseCloudMusicApi#1450]
## 环境
- 系统/平台: Windows 10

- nodejs 版本: v16.4.0

- API版本: 4.3.0

## 出现问题
官方提供的接口出了问题，https://autumnfish.cn/playlist/track/all?id=24381616&limit=10&offset=1

![image](https://user-images.githubusercontent.com/26035718/150679692-d30b2f62-e88e-4ae2-96f7-034e7d42de00.png)

但我fork最新版后用vercel部署就没报错
 https://netease-cloud-music-api-five-ivory.vercel.app/playlist/track/all?id=24381616&limit=10&offset=1

![image](https://user-images.githubusercontent.com/26035718/150679708-3d292f02-9bc4-4898-95b9-d946a49a5d6e.png)

## 重现步骤

点击上述链接

## 期待效果

应该是和我部署在Vercel一样的

**Comment by Binaryify** [comment]
autumnfish.cn 这个我都不知道谁部署的

**Comment by SnowingFox** [comment]
> autumnfish.cn 这个我都不知道谁部署的

233，我一直以为是官方的，因为第一次就是接触到的这个

**Comment by SnowingFox** [comment]
> autumnfish.cn 这个我都不知道谁部署的

打扰了
