### ISSUE TITLE
banner 图数据固定不变，跟网易云数据不同步。

### ISSUE THREAD

**Issue by LengYXin** [Binaryify/NeteaseCloudMusicApi#146]
banner 图数据 不同步网易云，永远都是那几个图。。。

**Comment by Binaryify** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=banner

**Comment by Binaryify** [comment]
说明:调用此接口,可获取 banner(轮播图)数据
注:因参数未知,只能获取比较旧的数据,如果有知道参数的小伙伴,可提交 PR
