### ISSUE TITLE
求个检查昵称是否可用的接口

### ISSUE THREAD

**Issue by za1189zx** [Binaryify/NeteaseCloudMusicApi#1469]
**功能描述**
需要一个检查昵称是否可用的接口，用于注册前检查（注册接口需要提供昵称）以及修改昵称前检查
--------------------------------
截图：
![昵称重复](https://user-images.githubusercontent.com/54718006/153179077-608ec147-78ca-44f4-84d6-c776edd8b449.png)
![昵称重复url](https://user-images.githubusercontent.com/54718006/153179078-418eae8e-aaef-4bba-906a-e8bac296c31c.png)

**Comment by Binaryify** [comment]
好了

**Comment by Binaryify** [comment]
等下，文档忘记写了，/nickname/check?nickname=xxx

**Comment by za1189zx** [comment]
动作好快啊，非常感谢！
