### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by TomyJan** [Binaryify/NeteaseCloudMusicApi#1477]
## 环境
- 系统/平台: CentOS8.3

- nodejs 版本: 16.14.0

- API版本: 4.5.7

## 出现问题
调用后报错
```
[ERR] /search?keywords=ab { status: 502,
  body:
   { code: 502,
     msg:
      { Error: unable to get local issuer certificate
          at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
          at TLSSocket.emit (events.js:198:13)
          at TLSSocket._finishInit (_tls_wrap.js:666:8)
        code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
        config: [Object],
        request: [Writable],
        response: undefined,
        isAxiosError: true,
        toJSON: [Function: toJSON] } } }
```

网上能搜索到的教程尝试过了,无用

## 重现步骤
调用任意接口都会报错

## 期待效果
目前无法使用,希望能给出解决方案,不胜感激

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
https://blog.csdn.net/lixuande19871015/article/details/88788699

**Comment by TomyJan** [comment]
> 

尝试过了, `curl music.163.com` 也是正常的,但还是没用

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1070

**Comment by TomyJan** [comment]
> #1070
还是一样(重启nodejs了)
暂时放弃吧,我先用Vercel部署使用了
感谢大佬的帮助
顺便问一嘴有没有计划在网页端支持unblock呢
