### ISSUE TITLE
已获取的歌单 id 并不能获取到相应的歌单详情

### ISSUE THREAD

**Issue by Anixte** [Binaryify/NeteaseCloudMusicApi#1478]
## 环境
- 系统/平台:  window 10 教育版

- nodejs 版本: 16.10.0

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题

获取的歌单 id 不能获取到歌单详情内容，直接400

## 重现步骤

使用 `/top/playlist` 和 `/personalized`  两接口获取到的歌单 id 都不能调用 `/playlist/detail` 来获取歌单详情

![微信图片_20220222214027](https://user-images.githubusercontent.com/64124472/155146728-dd87c81b-e0bf-4294-8d5b-8eaa37ec859d.png)
![微信图片_20220222214100](https://user-images.githubusercontent.com/64124472/155146748-9ee8faed-3b37-4a4c-bd52-5ebf576650c1.png)
![微信图片_20220222214104](https://user-images.githubusercontent.com/64124472/155146749-70c7e0bd-a235-428c-abab-639b6958820d.png)

## 期待效果
现在获取到的歌单 id 是十位的，正常为八位，期待效果为歌单 id 能正常获取歌单详情，谢谢，辛苦了

**Comment by Anixte** [comment]
部署到 vercel 后解决了，打扰了

**Comment by Anixte** [comment]
具体原因我也不太清楚，可能是因为大佬抓包的接口，不同客户端标识符在网易那边的解析是不同的吧。我一开始是clone别人的项目，用的别人接口，连登录什么的都是有问题的，实在想不通就乖乖按大佬的方式用了；部署vercel相当于把大佬的代码运行起来，建立后端服务器，这样网易那边的解析可能就一致了。

**Comment by Anixte** [comment]
> > 部署到 vercel 后解决了，打扰了
> 
> 为啥部署到那里之后就可以了，是啥原因吗，我前几天还可以用，今天发现跟你一样的错误


具体原因我也不太清楚，可能是因为大佬抓包的接口，不同客户端标识符在网易那边的解析是不同的吧。我一开始是clone别人的项目，用的别人接口，连登录什么的都是有问题的，实在想不通就乖乖按大佬的方式用了；部署vercel相当于把大佬的代码运行起来，建立后端服务器，这样网易那边的解析可能就一致了。

**Comment by solitudealma** [comment]
> > > 部署到 vercel 后解决了，打扰了
> > 
> > 
> > 为啥部署到那里之后就可以了，是啥原因吗，我前几天还可以用，今天发现跟你一样的错误
> 
> 具体原因我也不太清楚，可能是因为大佬抓包的接口，不同客户端标识符在网易那边的解析是不同的吧。我一开始是clone别人的项目，用的别人接口，连登录什么的都是有问题的，实在想不通就乖乖按大佬的方式用了；部署vercel相当于把大佬的代码运行起来，建立后端服务器，这样网易那边的解析可能就一致了。

我现在是挺多接口都是返回需要验证，我调用了一下登录接口之后设置了csrf的cookie，那些端口就可以用了，不知道为啥。感觉可能是返回歌单的歌时一下子返回太多了（几百首）。但是因为有两分钟缓存，我觉得应该也还好吧，用户量不是特别大，日活量很低、、
