### ISSUE TITLE
获取评论有问题

### ISSUE THREAD

**Issue by pychosis** [Binaryify/NeteaseCloudMusicApi#148]
### 环境
系统:  win10 64位

nodejs 版本:8.9.1

### 出现问题
获取评论返回的json数据为
{"code":-460,"msg":"Cheating"}
### 期待效果

**Comment by pychosis** [comment]
get /comment/music?id=186016&limit=20
现在已经好了，不过貌似我过度频繁访问的话会出现以上问题，有什么解决方案吗，谢谢！

**Comment by Binaryify** [comment]
limit 设置大点,前端对数组 slice 分页
