### ISSUE TITLE
调用云盘接口时，当offset超过最大时返回data的长度仍与limit相同

### ISSUE THREAD

**Issue by passing11** [Binaryify/NeteaseCloudMusicApi#1488]
## 环境
- 系统/平台: <你的系统和平台>
windows10
- nodejs 版本: <你的 NodeJS 版本号>
v14.18.2
- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
4.5.7
## 出现问题
调用云盘接口时，当offset超过最大时返回数量的歌曲与limit相同。但是只有limit时，limit超过最大数量时返回数据正常
## 重现步骤
![image](https://user-images.githubusercontent.com/59352482/156574175-eef90df8-e876-47c7-8f13-efe724f24e15.png)

![image](https://user-images.githubusercontent.com/59352482/156573901-de02a019-5c33-4daa-97ca-f691d4ee0ed7.png)
## 期待效果
<请清晰描述现在的效果和期待的效果>

**Comment by Binaryify** [comment]
offset 不是page

**Comment by passing11** [comment]
> offset 不是page

也就是说，当我设置limit=100&offset=6时，它确实会返回第600-700首歌曲，需要我自己判断长度是否超了

**Comment by passing11** [comment]
> limit=100&offset=6 返回的是7~107首

诶？等等，那为什么获取歌单所有歌曲写着“设置limit=10&offset=2，你就会得到第21-30首歌曲”，这么推不是3~13首吗

**Comment by passing11** [comment]
> limit=100&offset=6 返回的是7~107首

诶？等等，那为什么获取歌单所有歌曲写着“设置limit=10&offset=2，你就会得到第21-30首歌曲”，这么推不是3~13首

**Comment by Binaryify** [comment]
那个别人提的PR，没仔细看
云盘那边的说明是没问题的
![image](https://user-images.githubusercontent.com/12221718/156582998-334d3348-c79e-4c76-943f-e5f7b0a7e75e.png)

**Comment by Binaryify** [comment]
嗯嗯

**Comment by passing11** [comment]
> 嗯嗯

那个，大佬，获取歌单所有歌曲那里原来写的没错，确实是乘法

我调用 /playlist/track/all?id=992308582&offset=1&limit=100 时 确实获得的是101-200首歌
![image](https://user-images.githubusercontent.com/59352482/158059412-82dbb78a-a537-4b02-9aa3-9868c3dee5f1.png)
![image](https://user-images.githubusercontent.com/59352482/158059431-0dc6f405-6aaa-44e7-8530-29bba47a7d22.png)

![image](https://user-images.githubusercontent.com/59352482/158059238-f583ce59-5c06-44f7-89eb-dc5c811323bd.png)
![image](https://user-images.githubusercontent.com/59352482/158059464-6b316adb-9907-4e12-9a7a-284d82cccfbb.png)

怎么唯独这个是乘法啊😂
