### ISSUE TITLE
node server throw error and stopped

### ISSUE THREAD

**Issue by plimerence** [Binaryify/NeteaseCloudMusicApi#149]
### 环境
系统:  
mac  os 10.12.6

nodejs 版本:
v8.5.0

### 出现问题
node server throw error and stopped

### 重现步骤
just open localhost:3000 in safari and click to get data

### 期待效果
i hope the node server can deal the error but not stopped.
![snip20171207_5](https://user-images.githubusercontent.com/13290201/33706361-d5aab3b6-db6e-11e7-81f7-b1112a2ac2bd.png)

**Comment by Binaryify** [comment]
换个端口还会吗
