### ISSUE TITLE
喜欢音乐接口判断出错

### ISSUE THREAD

**Issue by passing11** [Binaryify/NeteaseCloudMusicApi#1493]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v14.18.2
- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
4.5.8
## 出现问题

在喜欢歌曲的接口里 query 中原先没有like，改用flag判断后成功取消喜欢
## 重现步骤
![image](https://user-images.githubusercontent.com/59352482/157602519-20f01641-c059-4717-9d10-27fe98303644.png)

**Comment by Binaryify** [comment]
`在喜欢歌曲的接口里 query 中原先没有like`
指的什么

**Comment by passing11** [comment]
> `在喜欢歌曲的接口里 query 中原先没有like` 指的什么

看了下文档，我打错了，对不起
