### ISSUE TITLE
请问手机验证码登录还能用吗，一直显示请求超时

### ISSUE THREAD

**Issue by cyx-liam** [Binaryify/NeteaseCloudMusicApi#1494]
## 环境
- 系统/平台: uniapp

## 出现问题
手机密码登录没问题，就是用验证码登录不了

## 重现步骤
![Inked202231215527_LI](https://user-images.githubusercontent.com/72517813/157923674-ab5b4d37-4c2d-4c0b-8659-095018cb3692.jpg)

![image](https://user-images.githubusercontent.com/72517813/157923900-511f3c11-60e8-45bb-8746-f0d8682ca59c.png)

## 期待效果
有没有大佬测试一下

**Comment by Binaryify** [comment]
我这边没问题，你把超时时间改大点看看

**Comment by crazybox521** [comment]
我刚看了可以的呀

**Comment by SUN7700** [comment]
我好像也不大行，真的可以吗
