### ISSUE TITLE
用邮箱密码登录时概率出现需要验证问题

### ISSUE THREAD

**Issue by puzzle9** [Binaryify/NeteaseCloudMusicApi#1495]
## 环境
- 系统/平台: manjaro

- nodejs 版本: v17.7.1

- API版本: https://github.com/Binaryify/NeteaseCloudMusicApi/commit/15260bc1548c90e8af23521243903cfb70586472

## 出现问题
用用户名密码登录时 可能因为ip变化概率出现需要验证的情况

## 重现步骤

![image](https://user-images.githubusercontent.com/13518196/159882745-d3cd9a6b-a4e8-429f-a108-c16a85db5cb1.png)
调用接口时出现此提示

在网页为
![image](https://user-images.githubusercontent.com/13518196/159882986-0661e82f-bdf4-4e3d-9995-af59dd2b0f18.png)

验证成功后调用 https://music.163.com/weapi/frontrisk/verify/check 后 可登录成功

## 期待效果
无

**Comment by Binaryify** [comment]
尽量使用二维码登录吧
