### ISSUE TITLE
获取歌单list

### ISSUE THREAD

**Issue by liuxsen** [Binaryify/NeteaseCloudMusicApi#150]
### 环境
系统:  
windows
nodejs 版本:
v6.11.0
### 出现问题
![image](https://user-images.githubusercontent.com/12598696/33815990-d41d5210-de70-11e7-8c6a-33854fc4789a.png)

![image](https://user-images.githubusercontent.com/12598696/33815954-a20945ea-de70-11e7-9c9d-8e4bce04f174.png)

之前是可以获取的，后来获取不了了，是不是被禁用ip了？

### 重现步骤
步骤如上

### 期待效果
希望可以获取到数据

**Comment by Binaryify** [comment]
服务端有报什么错吗

**Comment by HoseaGuo** [comment]
我也遇到了这种问题
