### ISSUE TITLE
在Node.js中登录了没有cookie

### ISSUE THREAD

**Issue by TalexDreamSoul** [Binaryify/NeteaseCloudMusicApi#1502]
## 环境
- 系统/平台: Windows11 Node.js (Electron)

- nodejs 版本: 16.5.0

- API版本: 4.2.0

## 出现问题
扫码登录后 cookie 字段为 null
手机验证码登录返回要么 250(loginType: 1) 要么301(loginType: 1)

## 重现步骤
![image](https://user-images.githubusercontent.com/59305952/161378497-172dd2eb-afe6-4365-b56c-939a2d53940b.png)
![image](https://user-images.githubusercontent.com/59305952/161378517-4ad887eb-8319-4608-acfa-6e3d012fc3c8.png)
![image](https://user-images.githubusercontent.com/59305952/161378535-68e9d702-6dcc-4b2d-b057-dc6d71f4ea6b.png)
![image](https://user-images.githubusercontent.com/59305952/161378548-e83738fa-3fa9-4f80-9a97-7f7aab543e42.png)
但是这个是可以拿到的
![image](https://user-images.githubusercontent.com/59305952/161378560-8143dc75-0c47-4770-bbb1-7f228c894506.png)

## 期待效果
扫码登录后可以正常获取到 cookie 内容
手机号验证码登录可以正常登录

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
你调登录接口调了太多次了吧

**Comment by TalexDreamSoul** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by TalexDreamSoul** [comment]
我在第一次调用时就出现此种情况

在近三个月的测试中每一次均会出现这种情况，如果需要我可以提供相关源码

**Comment by Binaryify** [comment]
服务器是国外的还是国内的

**Comment by TalexDreamSoul** [comment]
国内的 我是在本地开发做的测试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月4日(星期一) 下午5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] 在Node.js中登录了没有cookie (Issue #1502)





 
服务器是国外的还是国内的

**Comment by Binaryify** [comment]
你进群问下群里的人吧

**Comment by TalexDreamSoul** [comment]
我已经从去年问到了现在迫不得已才开的issue ...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月6日(周三) 下午4:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Binaryify/NeteaseCloudMusicApi] 在Node.js中登录了没有cookie (Issue #1502)




 
你进群问下群里的人吧

**Comment by Binaryify** [comment]
有可能是你的ip被网易封了，实在不行换二维码登录吧，二维码登录基本不会出现这个问题

**Comment by TalexDreamSoul** [comment]
之前写到了 我最开始就是二维码，实在不行才是手机号，结果仍然没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上6:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Binaryify/NeteaseCloudMusicApi] 在Node.js中登录了没有cookie (Issue #1502)




 
有可能是你的ip被网易封了，实在不行换二维码登录吧，二维码登录基本不会出现这个问题

**Comment by Binaryify** [comment]
@TalexDreamSoul 加我QQ私聊，加的时候备注下，821374382

**Comment by TalexDreamSoul** [comment]
已添加！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月9日(星期六) 晚上6:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] 在Node.js中登录了没有cookie (Issue #1502)





 
@TalexDreamSoul 加我QQ私聊吧，加的时候备注下，821374382

**Comment by TalexDreamSoul** [comment]
已在QQ聊天中解决

问题原因:
1. 无法在 render进程 中操作

解决方案:
1. 在 主线程 使用 ipc 进行通讯
2. 也可在主线程中启动 音乐api服务 ( 类似于 proxy )
