### ISSUE TITLE
搜索接口增加 ISRC 编码

### ISSUE THREAD

**Issue by rankun203** [Binaryify/NeteaseCloudMusicApi#1506]
**功能描述**
- 搜索接口返回的歌曲条目希望可以增加 ISRC 编码，以便在其他平台上进行匹配

**Comment by rankun203** [comment]
Spotify: https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track

网易云音乐不知道有没有什么地方会揭示 ISRC 编码，但这个码的用处确实是挺大的。

**Comment by Binaryify** [comment]
返回内容是网易那边控制的

**Comment by rankun203** [comment]
@Binaryify 根据你的经验，有在网易整个平台的 API 返回中任何地方看到过 ISRC 编码么？

**Comment by Binaryify** [comment]
印象中是没看到过的

**Comment by rankun203** [comment]
好吧～
