### ISSUE TITLE
<不按照模版格式或者删除模版信息将得不到处理,确认看完了调用前须知再发 issues>

### ISSUE THREAD

**Issue by cyear** [Binaryify/NeteaseCloudMusicApi#1510]
## 环境
- 系统/平台: Android 12/Ubuntu20.04

- nodejs 版本: v10.19.0

- API版本: 4.5.11

## 出现问题
任务userTaskId为0或重复

## 重现步骤
![Screenshot_20220412-105846_Termux_1.png](https://user-images.githubusercontent.com/77969791/162870607-bea1307c-85fb-44bd-8f47-623e519a9b46.png)

浏览器返回
{'code': 200, 'message': 'SUCCESS', 'data': [{'taskId': 217001, 'userTaskId': 0, 'taskName': '听音乐30分钟 ', 'taskPoint': 10, 'webPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/11375520818/350c/6813/e484/463b41ca84fea1e6c05801c9d4e74c08.png', 'completedIconUrl': None, 'backgroundPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969094536/c3dc/9d1d/29a5/0a28af8755f3e18f9efdb1cf81acc0f1.png', 'wordsPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969096512/7c1c/572f/511b/096638e6274cc95002df7c1c2f245dc2.png', 'link': 'orpheus://nm/main/mine', 'linkText': '去听歌', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '每日满30分钟可领', 'position': 120, 'actionType': 618}, {'taskId': 166000, 'userTaskId': 0, 'taskName': '分享1首歌/1个歌单', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969140817/1ac7/0345/c5c8/fb9be56a7bfe094930c00ac1e7a1687c.png', 'completedIconUrl': None, 'backgroundPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/13747413739/d3a8/204a/c1af/c5077a5339b647883ca9eea0833a67d8.jpg', 'wordsPicUrl': None, 'link': 'orpheus://playlistCollection?tabPage=1', 'linkText': '去分享', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '1首歌/1个歌单', 'position': 100, 'actionType': 601}, {'taskId': 573005, 'userTaskId': 0, 'taskName': '听播客', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/10958494382/34ba/079f/a856/96b04a076b5a1efca46b14198e7cdaca.png', 'completedIconUrl': None, 'backgroundPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/10958494489/c765/b6cd/0b5d/0a08b0d0c74448df8d281f96293f190b.png', 'wordsPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/10959757805/5c94/e5c5/cfd6/eb625928f7788f0b607038ce1169082b.png', 'link': 'orpheus://nm/mainTab/select?tab=voice', 'linkText': '去收听', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '收听播客3分钟', 'position': 95, 'actionType': 638}, {'taskId': 200002, 'userTaskId': 43234905702, 'taskName': '云贝推歌', 'taskPoint': 10, 'webPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969107949/3c2d/ee55/9fd1/2081f7b6c5bd756507544059c951d28d.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'orpheus://miniProgram?appId=5edef4f3efbb4504ead2ae75&pageId=pages/index/index&fallbackURL=https://mp.music.163.com/5edef4f3efbb4504ead2ae75/pages/index/index.html?tab%3D0%26nm_style%3Dsbt%26full_screen%3Dtrue&query=tab%3D0%26nm_style%3Dsbt%26full_screen%3Dtrue%26refer%3dtaskrecommend', 'linkText': '去推歌', 'completed': True, 'completedPoint': 0, 'status': 100, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '去推荐1首喜欢的歌曲', 'position': 88, 'actionType': 615}, {'taskId': 656007, 'userTaskId': 0, 'taskName': '浏览会员中心', 'taskPoint': 5, 'webPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/12509630990/823a/a696/1b1a/5eb9a4ea3657753a0db9d5c9231e2f26.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'https://music.163.com/premium/m/portal?nm_style=sbt&bounces=false&fromyunbei=1&referer=yunbei', 'linkText': '去浏览', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '浏览会员中心10s', 'position': 88, 'actionType': 644}, {'taskId': 214005, 'userTaskId': 0, 'taskName': '瓜分百万云贝', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969113371/c69a/8d94/7ff0/22378d9e986b5808fba193b726c7f383.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'orpheus://miniProgram?appId=5f4471f49ed1d1e04356b5ef&pageId=index&query=market%3DyunbeiCentrTask&fallbackURL=https%3A%2F%2Fmp.music.163.com%2F5f4471f49ed1d1e04356b5ef%2Findex.html%3Fmarket%3DyunbeiCentrTask', 'linkText': '去瓜分', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '去火前留名挑战听歌品味', 'position': 80, 'actionType': 624}, {'taskId': 276001, 'userTaskId': 0, 'taskName': '赏音猎人', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/11204358773/c405/8617/be84/183a945c9bfa4e6ea16f79b5fa7b6de4.png', 'completedIconUrl': None, 'backgroundPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969098331/8b10/4abf/6799/f76056089ca2848790e10f80d3c95851.png', 'wordsPicUrl': 'http://p5.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969100241/12f7/6ba2/defa/9a961c9e15a3e1511f7d885a0cff64f4.png', 'link': 'https://st.music.163.com/c/voice?full_screen=true&market=yunbeirenwu', 'linkText': '听歌PK', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '去进行1场听歌PK', 'position': 76, 'actionType': 626}, {'taskId': 721005, 'userTaskId': 0, 'taskName': '观看直播', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/11760207270/d6d9/012c/613e/de8415db0fd3507afd829af337cd426b.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'orpheus://nml/yunbei/task?taskType=2', 'linkText': '去观看', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '在直播专区观看直播满3分钟', 'position': 60, 'actionType': 611}, {'taskId': 216002, 'userTaskId': 43234899874, 'taskName': '访问云音乐商城', 'taskPoint': 2, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/9969126444/ee33/c59b/2b9b/1c27aed82dfea909ef4ae81205112dc8.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'orpheus://rnpage?component=ReactNativeStore', 'linkText': '去浏览', 'completed': True, 'completedPoint': 0, 'status': 100, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '浏览1次云音乐商城商品', 'position': 50, 'actionType': 617}, {'taskId': 595014, 'userTaskId': 0, 'taskName': '关注云贝小助手', 'taskPoint': 5, 'webPicUrl': 'http://p6.music.126.net/obj/wo7DlsKTwrbDjjjDjsOk/11428876565/1903/372a/ca17/782ebf23ff9b69cff3ae234a4e8742a3.png', 'completedIconUrl': None, 'backgroundPicUrl': None, 'wordsPicUrl': None, 'link': 'assistant', 'linkText': '去关注', 'completed': False, 'completedPoint': 0, 'status': 0, 'targetStatus': None, 'targetPoint': 0, 'targetUserTaskId': 0, 'taskDescription': '关注云贝小助手 每人仅限1次', 'position': 90, 'actionType': 641}]}

## 期待效果
每个Id不同且不为0

**Comment by Binaryify** [comment]
completed 才会有userTaskId

**Comment by nian0** [comment]
> completed 才会有userTaskId

完整的？

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/163205742-3f9c6f99-c781-4621-bbfd-c67ec178b599.png)

**Comment by Binaryify** [comment]
就是你完成的任务，才有userTaskId，才能手动触发完成任务接口

**Comment by nian0** [comment]
> 就是你完成的任务，才有userTaskId，才能手动触发完成任务接口

所以有接口能完成任务？我没看到

**Comment by Binaryify** [comment]
![Uploading image.png…]()

**Comment by nian0** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/163713088-ccd908cf-6b85-4f00-b9b9-776394283e1c.png)
> 

这个不是获取id为0吗，我才说不能完成😂，是不是手动完成才能获取id

**Comment by Binaryify** [comment]
你看客户端界面啊，你达成条件才能触发完成任务，才能领取云贝啊，怎么可能要你听歌30分钟的任务，触发接口就完成了
