### ISSUE TITLE
获取歌单所有歌曲接口分页不准

### ISSUE THREAD

**Issue by acetrak** [Binaryify/NeteaseCloudMusicApi#1513]
## 环境
- 系统/平台: <win 11>

- nodejs 版本: <v16.14.0>

- API版本: <4.5.12>

## 出现问题
 [获取歌单所有歌曲](https://neteasecloudmusicapi.vercel.app/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e5%8d%95%e6%89%80%e6%9c%89%e6%ad%8c%e6%9b%b2)

接口地址 : /playlist/track/all

调用例子 : /playlist/track/all?id=24381616&limit=10&offset=1

注：关于offset，你可以这样理解，假设你当前的歌单有100首歌

你传入limit=10&offset=0等价于limit=10，你会得到第1-10首歌曲

你传入limit=10&offset=1，你会得到第2-11首歌曲

如果你设置limit=10&offset=2，你就会得到第3-12首歌曲

### ！！只要offset不是0 获取到的数据会不准确，即无法正常使用分页

 

---

**Comment by PingmengWocha** [comment]
我也发现了，应该是文档描述有问题，我看了一下他处理的方法，发现这个offset准确来说是第几页，0就是第一页，1就是第二页...

**Comment by champion0122** [comment]
> 我也发现了，应该是文档描述有问题，我看了一下他处理的方法，发现这个offset准确来说是第几页，0就是第一页，1就是第二页...

感谢老哥回答。琢磨半天

**Comment by user1542043226** [comment]
接口失效了

**Comment by l1aolei** [comment]
接口已失效
