### ISSUE TITLE
在使用关注用户和收藏歌手接口时，无法正常关注，提示需绑定手机或验证短信成功

### ISSUE THREAD

**Issue by crazybox521** [Binaryify/NeteaseCloudMusicApi#1516]
## 环境
- 系统/平台: Windows 10

- nodejs 版本: v14.15.5
- API版本: 4.5.12 / 4.0.23

## 出现问题
在使用关注用户和收藏歌手接口时，无法正常关注，提示需绑定手机或验证短信成功（本身就是手机账号登录），进入返回的验证地址后提示需用网易云音乐APP打开
## 重现步骤
使用关注用户或收藏歌手接口
/artist/sub?id=1143033&t=1&timestamp=1650627615131
响应
{"code":-462,"data":{"actionCode":"1065408","verifyType":20,"verifyId":1007601,"verifyUrl":"https://st.music.163.com/encrypt-pages","blockText":"绑定手机号或短信验证成功后，可进行下一步操作哦~","verifyToken":"00.20.cb6a38ab89f53b45ba22613a9f494efa.1021864466","btnText":"","orpheusUrl":"","frontRuleIds":[1065408],"params":{"event_id":"00225579433913954311","sign":"73648850893765898e9c3b0c92220065"},"url":"https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2273648850893765898e9c3b0c92220065%22%2C%22event_id%22%3A%2200225579433913954311%22%7D&verifyType=20&verifyId=1007601&verifyToken=00.20.cb6a38ab89f53b45ba22613a9f494efa.1021864466&actionCode=1065408"},"message":null}

## 期待效果
现在无法正常使用接口，无法正常关注、取关、收藏、取消收藏
期待效果:像之前那样可以正常关注其他用户和收藏歌手；或者能够给出验证的方法，希望其他解决此问题的开发者可以留言解决方案

**Comment by huankong233** [comment]
你解决问题了吗，我也是这样

**Comment by crazybox521** [comment]
> 你解决问题了吗，我也是这样
没有，如果你是移动端可以打开返回的那个链接跳转网易云音乐app去验证

**Comment by Euphoriahz** [comment]
有人解决了这个问题吗求助

**Comment by agengen1** [comment]
这个问题解决没有，求助

**Comment by Binaryify** [comment]
@agengen1 @Euphoriahz 更新文档了,试试看
