### ISSUE TITLE
接口请求跨域

### ISSUE THREAD

**Issue by FlowerFestival** [Binaryify/NeteaseCloudMusicApi#152]
### 环境
系统:  Mac os

nodejs 版本:8.9.1

### 出现问题
用 axios 访问接口network显示可以取到数据  但是报跨域错误    @@直接进axios的error

请求搜索是 304 有数据报跨域
  请求登陆是200 有数据报跨域

### 重现步骤
直接请求本地接口  参数写死
### 期待效果
<img width="1205" alt="2017-12-16 19 27 40" src="https://user-images.githubusercontent.com/23180446/34069996-799b3cd2-e297-11e7-8252-4abcb9e29cf8.png">
<img width="1173" alt="2017-12-16 19 28 04" src="https://user-images.githubusercontent.com/23180446/34069999-7cce7a4a-e297-11e7-8617-c2423469c0e0.png">
<img width="1047" alt="2017-12-16 19 28 32" src="https://user-images.githubusercontent.com/23180446/34070000-7ec3aac8-e297-11e7-990a-3e225a640530.png">
@Binaryify 

<img width="1199" alt="2017-12-16 19 31 46" src="https://user-images.githubusercontent.com/23180446/34070015-f35acb1e-e297-11e7-8580-b6a03611b3ac.png">

**Comment by Binaryify** [comment]
请查看 app.js 源码
