### ISSUE TITLE
cloudsearch 分页问题

### ISSUE THREAD

**Issue by ygq-704292061** [Binaryify/NeteaseCloudMusicApi#1525]
## 环境
- 系统/平台: win10

- nodejs 版本: 16.14.2

- API版本: 0.1.0

## 重现步骤
![微信图片编辑_20220507095108](https://user-images.githubusercontent.com/57651572/167233349-4ec58039-4381-4431-85b0-89c34bbc8f3a.jpg)
![微信图片编辑_20220507095116](https://user-images.githubusercontent.com/57651572/167233409-4455b0ad-0082-4e33-b571-717a2c1dd76d.jpg)

## 问题描述
分页错误

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
文档写了offset是什么意思了

**Comment by ygq-704292061** [comment]
当前页数下标啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 上午10:06
收件人: ***@***.***&gt;; 
抄送: "南巷如画@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] cloudsearch 分页问题 (Issue #1525)





 
文档写了offset是什么意思了
