### ISSUE TITLE
请求获取歌单所有歌曲加入hasMore的返回，并当请求的歌曲总数超过歌单内歌曲总数时返回截取后的数据

### ISSUE THREAD

**Issue by nullcache** [Binaryify/NeteaseCloudMusicApi#1529]
**功能描述**
- 希望如 `/top/mv` 接口一样，添加一个 `hasMore` 的数据，而且现在的接口当请求的歌曲总数超过歌单内歌曲总数时会返回重复的歌曲，和 `/top/mv` 接口表现不一致，比如歌单有121首歌，我 `limit = 20`, `offset = 6`，才能请求完所有的歌，但是最后一次请求本该返回一个值，但是实际上返回了20首，而且和前面的歌曲重复了
- 还有就是个小 bug 就是，文档中 `offset` 的描述不准确，应该是分页

**Comment by Binaryify** [comment]
这个前几天的pr应该修复了这个问题

**Comment by nullcache** [comment]
谢谢，完美的解决了我的问题，而且也不再需要 `hasMore` 参数了
