### ISSUE TITLE
GitBash返回status:502,errno:-4039，该怎么解决？

### ISSUE THREAD

**Issue by GzxdH** [Binaryify/NeteaseCloudMusicApi#1530]
## 环境
- 系统/平台: <Windows10>

- nodejs 版本: <v16.14.2>

- API版本: <4.5.14>

## 出现问题
先前也偶然有该问题出现，尝试重新启动后消失；
今天（2022.5.12）启动也没问题，当天第一次请求也没问题，但之后再次请求（任何）接口便会出现该问题，多次尝试重新启动也无法解决
![123](https://user-images.githubusercontent.com/19452605/168020792-57ab602b-c17c-436d-9573-8bc40155e013.png)
。

## 重现步骤
没有返回内容，gitbash报错如下：
$ node app.js
server running @ http://localhost:3000
[ERR] /dj/hot {
  status: 502,
  body: {
    code: 502,
    msg: Error: connect ETIMEDOUT 115.236.118.34:443
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
      errno: -4039,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: '115.236.118.34',
      port: 443,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  }
}
E:\demo_space\music_api\NeteaseCloudMusicApi\node_modules\express\lib\response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (E:\demo_space\music_api\NeteaseCloudMusicApi\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (E:\demo_space\music_api\NeteaseCloudMusicApi\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (E:\demo_space\music_api\NeteaseCloudMusicApi\node_modules\express\lib\response.js:158:21)
    at E:\demo_space\music_api\NeteaseCloudMusicApi\server.js:256:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

## 期待效果
<请清晰描述现在的效果和期待的效果>  
正常获取请求结果。

**Comment by Binaryify** [comment]
重启电脑试试

**Comment by GzxdH** [comment]
> 重启电脑试试

尝试无结果，还是报同样的错，是什么原因容易导致这个错误呢，尝试过设置不同端口号也不行。

**Comment by GzxdH** [comment]
好吧，我关闭了，地址没问题，昨晚在家跑的很畅快，然后这个问题的答案是：一般来说是网络问题，多次的话也是网络原因，因为我司设置屏蔽网址了（可能被屏蔽或者是真的网络差）

**Comment by Binaryify** [comment]
尽量不要用公司网络测试
