### ISSUE TITLE
存在部分网易云能免费播放但通过api接口无法获取到歌曲地址的情况

### ISSUE THREAD

**Issue by ns-cn** [Binaryify/NeteaseCloudMusicApi#1532]
## 环境
- 系统/平台: MacOS

- nodejs 版本: vercel.com部署,版本号不详细

- API版本: 4.5.14

## 出现问题
存在部分歌曲通过接口**获取音乐 url**和**获取客户端歌曲下载 url**无法获取到歌曲id为515143079(仓木麻衣的"Your Best Friend")的下载地址,但在网易云客户端中该歌曲为免费歌曲且能正常播放
> 且通过 https://music.163.com/song/media/outer/url?id=id.mp3 这种方式也无法成功获取到歌曲资源url

## 重现步骤
歌曲id为515143079针对以下三种情况均无法获取到真实可用的音乐资源地址
- 通过**请求音乐url**接口
- 通过**获取客户端歌曲下载 url**接口
- 通过**https://music.163.com/song/media/outer/url?id=515143079.mp3**

## 期待效果
能获取到正常可用的下载地址

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/168453819-37b6928f-7575-4362-b3c7-cf4602e16211.png)
![image](https://user-images.githubusercontent.com/12221718/168453823-ad34c30f-9e37-4208-be15-912df7860785.png)
