### ISSUE TITLE
请求接口提示需要验证

### ISSUE THREAD

**Issue by huankong233** [Binaryify/NeteaseCloudMusicApi#1541]
好像是因为我使用的是流量
![image](https://user-images.githubusercontent.com/49610758/170500444-f07fe327-d879-4eb2-bef8-169736a445cb.png)

**Comment by QuXiang-code** [comment]
我也一样，用手机热点就没问题，用校园网就要验证

**Comment by huankong233** [comment]
我用流量就有这个问题，学校的校园网就没问题哈哈哈哈

**Comment by xiaoyang949** [comment]
我还是有这个问题啊

**Comment by LMM11231** [comment]
请问大佬们这个bug怎么解决？

**Comment by LMM11231** [comment]
好的，收到！感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上9:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Binaryify/NeteaseCloudMusicApi] 请求接口提示需要验证 (Issue #1541)





 
把api部署到vercel后是可以正常使用的

**Comment by QuXiang-code** [comment]
> 把api部署到vercel后是可以正常使用的

部署之后还是同样的问题
![image](https://user-images.githubusercontent.com/70871914/170711614-c40c3980-d7b5-44ef-bff8-b125211b1a53.png)

**Comment by rktccn** [comment]
> 

把项目也部署到vercel上试试呢

**Comment by solitudealma** [comment]
调用登录接口设置了cookie之后就可以了，但是我觉得这应该不是问题的本身吧，用着用着就这样了

**Comment by Binaryify** [comment]
都进群讨论吧

**Comment by hnustwjj** [comment]
好像报错之后，点击那个400的网络报错打开单独页面请求，可以访问到，然后再回头刷新自己的应用就又可以了qwq。这个验证机制要咋搞呀

**Comment by solitudealma** [comment]
> 都进群讨论吧

群在哪里呀，没有看到

**Comment by Binaryify** [comment]
@solitudealma https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1419

**Comment by linwu0909** [comment]
调用登陆接口登陆，网络切换成手机热点也还是不行。断点发现app.js没有获得请求的cookie，浏览器是有cookie的，尝试把cookie写在app.js的cookie parser下的方法中再调用接口就正常了。

**Comment by MrRainbowYoo** [comment]
请问有解决的办法吗

**Comment by Binaryify** [comment]
看看新版本是不是修复好了

**Comment by ycjj11** [comment]
昨天遇到了找了一下午bug，已经修复好了

**Comment by anewcat** [comment]
> 调用登陆接口登陆，网络切换成手机把客户端也写不出来。断点发现appjs没有获取请求的cookie，浏览器是有cookie的，尝试在app.js的cookie par下的方法中再调用接口就正常了。

请问具体是怎么解决的呀，可以求一下代码吗

**Comment by fengjianxiong-web** [comment]
部署到vercel  我是可以的

**Comment by sometimeQ** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/15411257/171548409-3729bcf0-0d4b-438e-b1b7-48deb086f014.png">

什么情况啊

**Comment by sometimeQ** [comment]
> > 把api部署到vercel后是可以正常使用的
> 
> 部署之后还是同样的问题 ![image](https://user-images.githubusercontent.com/70871914/170711614-c40c3980-d7b5-44ef-bff8-b125211b1a53.png)

大佬，怎么解决的呀

**Comment by 1473974655** [comment]
> 都进群讨论吧

进不去呀，没有同意

**Comment by 1473974655** [comment]
> > > 把api部署到vercel后是可以正常使用的
> > 
> > 
> > 部署之后还是同样的问题 ![图片](https://user-images.githubusercontent.com/70871914/170711614-c40c3980-d7b5-44ef-bff8-b125211b1a53.png)
> 
> 大佬，怎么解决的呀
我是通过把手机网易云的账号进行提出，然后把你截图的第一张最后url链接用手机打开，转跳到网易云软件，进行验证，完了后但是请求几次又要验证了

**Comment by liujiajiayu** [comment]
本地有这个问题怎么解决呢？
