### ISSUE TITLE
登录成功后还是无法正确获取需要登录接口的返回信息

### ISSUE THREAD

**Issue by 1412849797** [Binaryify/NeteaseCloudMusicApi#1545]
## 环境
- 系统/平台: Ubuntu20.0/Docker

- nodejs 版本: Docker最新镜像[v4.6.2]的

- API版本: Docker最新镜像[v4.6.2]的

## 出现问题

带登录返回的Cookie去请求这个接口/user/detail 
![image](https://user-images.githubusercontent.com/59927567/171872093-acbd8732-c918-4eca-8b9e-803b0981be06.png)
状态是成功的，但是没有正确数据

## 重现步骤
1、/login/cellphone 成功登录
2、拿到登录的Cookie和User-Agent保存在header中再去请求/user/level 
3、结果返回的302
**这里的Cookie是前面登录请求保存下来的**
![image](https://user-images.githubusercontent.com/59927567/171887007-55c1da1d-0778-4720-a1b5-62f673a43be2.png)

结果：
![image](https://user-images.githubusercontent.com/59927567/171884874-7899489e-8128-47d0-92a5-8732cbf8e756.png)
**这里code存的cookie是使用encodeURIComponent()加密过**
![image](https://user-images.githubusercontent.com/59927567/171896915-4859127c-e7ef-4bd1-8e3b-3c051aafeff3.png)
结果还是一样302

## 期待效果
现在是调用登录接口成功后，无法正确获取需要登录的接口所返回的信息
期待登录后可以正确返回信息

---

**Comment by 1412849797** [comment]
> ## 环境
> * 系统/平台: Ubuntu20.0/Docker
> * nodejs 版本: Docker最新镜像[v4.6.2]的
> * API版本: Docker最新镜像[v4.6.2]的
> 
> ## 出现问题
> 使用/login/cellphone成功登录后，是需要自己保存响应的Cookie再去调那些需要登录的接口吗？ 还是登录成功后的状态会保存在Docker容器中？
> 
> 这两种方式我都尝试过，但是比如请求这个接口/user/detail ![image](https://user-images.githubusercontent.com/59927567/171872093-acbd8732-c918-4eca-8b9e-803b0981be06.png) 状态是成功的，但是没有正确数据
> 
> 获取用户等级信息/user/level 返回的是302的状态码
> 
> ## 重现步骤
> 1、/login/cellphone 成功登录 2、拿到登录的Cookie和User-Agent保存在header中再去请求/user/level 3、结果返回的302 ![image](https://user-images.githubusercontent.com/59927567/171873161-6de16b69-c619-4199-a6c1-2384667859c4.png)
> 
> ## 期待效果
> 现在是调用登录接口成功后，无法正确获取需要登录的接口所返回的信息 期待登录后可以正确返回信息
> 
> 请问登录后，再去请求那些需要登录的接口，用不用自己带Cookie信息



> ## 环境
> * 系统/平台: Ubuntu20.0/Docker
> * nodejs 版本: Docker最新镜像[v4.6.2]的
> * API版本: Docker最新镜像[v4.6.2]的
> 
> ## 出现问题
> 使用/login/cellphone成功登录后，是需要自己保存响应的Cookie再去调那些需要登录的接口吗？ 还是登录成功后的状态会保存在Docker容器中？
> 
> 这两种方式我都尝试过，但是比如请求这个接口/user/detail ![image](https://user-images.githubusercontent.com/59927567/171872093-acbd8732-c918-4eca-8b9e-803b0981be06.png) 状态是成功的，但是没有正确数据
> 
> 获取用户等级信息/user/level 返回的是302的状态码
> 
> ## 重现步骤
> 1、/login/cellphone 成功登录 2、拿到登录的Cookie和User-Agent保存在header中再去请求/user/level 3、结果返回的302 ![image](https://user-images.githubusercontent.com/59927567/171873161-6de16b69-c619-4199-a6c1-2384667859c4.png)
> 
![image](https://user-images.githubusercontent.com/59927567/171878845-e0cc6cb1-cb3f-4114-95fc-12ec00978a15.png)
![image](https://user-images.githubusercontent.com/59927567/171878877-18e8894a-54c2-40f5-a422-2ae4dac2383b.png)

> ## 期待效果
> 现在是调用登录接口成功后，无法正确获取需要登录的接口所返回的信息 期待登录后可以正确返回信息
> 
> 请问登录后，再去请求那些需要登录的接口，用不用自己带Cookie信息

**Comment by TAber-W** [comment]
老哥是怎么解决的！

**Comment by 1412849797** [comment]
不好意思阿，太久没用了，我也忘记怎么解决了
