### ISSUE TITLE
希望有下载QQ音乐和网易云音乐歌词保存csv的功能

### ISSUE THREAD

**Issue by benbenlang** [Binaryify/NeteaseCloudMusicApi#1547]
比如这个歌手
https://y.qq.com/n/ryqq/singer/000FzZ3q3kxTMG
https://music.163.com/#/discover/toplist?id=3778678
https://music.163.com/#/artist?id=122455

希望能下载输入歌手的全部歌词 保存到csv 这样以后歌曲被和谐了歌词还能找到，
最好把能看到的那些字段全部保存下来，比如歌曲名，图片地址，专辑名，歌手名，歌曲ID等，方便搜索

**Comment by Binaryify** [comment]
这个自己实现吧，不在这个项目的范围内
