### ISSUE TITLE
调用 user_record 接口，并传入了 cookie，拿到的听歌次数都是 0

### ISSUE THREAD

**Issue by Leecason** [Binaryify/NeteaseCloudMusicApi#1549]
## 环境
- 系统/平台: Mac

- nodejs 版本:  14.16.0

- API版本: "NeteaseCloudMusicApi": "^4.6.3"

## 出现问题

调用 api 后拿到的听歌次数都是 0

## 重现步骤
调用 user_record 接口，并传入了 cookie，cookie 是从 web 端的 MUSIC_U 字段 copy 的

调用 api 后拿到的听歌次数都是 0

## 期待效果
能获取到正确的 playCount

**Comment by Leecason** [comment]
今天看了一下接口又正常了，能获取到正确的 playCount

**Comment by Binaryify** [comment]
有时候是网易抽了，有时候是它过一段时间才会更新
