### ISSUE TITLE
获取音乐 url失效

### ISSUE THREAD

**Issue by muxi2015** [Binaryify/NeteaseCloudMusicApi#155]
### 环境
系统:

 linux X64

nodejs 版本:

 9.2.0

### 出现问题: 

获取音乐 url失效,获取到的uri的null

### 期待效果

**Comment by muxi2015** [comment]
http://music.163.com/song/media/outer/url?id=id.mp3  仍旧可用,请close把

**Comment by muxi2015** [comment]
刚试了下 http://music.163.com/song/media/outer/url?id=id.mp3 又不行了

1.

**Comment by Binaryify** [comment]
能播放的才可以,比如 http://music.163.com/song/media/outer/url?id=347231.mp3

**Comment by ldc2726** [comment]
我这个地址怎么请求的内容都是空的？

**Comment by muxi2015** [comment]
@ldc2726 据作者大大描述只有能播放的才能播放，所以先看看是不是音乐的ID吧
