### ISSUE TITLE
可否加入音频、歌词、详情、列表之类的缓存以解决频繁导致封IP问题

### ISSUE THREAD

**Issue by Cashew-wood** [Binaryify/NeteaseCloudMusicApi#1553]
可以将获取过的歌曲在本地缓存下来，下次请求可以直接走读取本地文件，接口也可如此，像详情、歌词、列表一般不会变化，通过配置失效时间决定是否有效

**Comment by Binaryify** [comment]
缓存是全局的，5分钟

**Comment by Cashew-wood** [comment]
好像不够用，我能修改这个时间吗，因为我播放了几次就被限制了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月24日 20:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Binaryify/NeteaseCloudMusicApi] 可否加入音频、歌词、详情、列表之类的缓存以解决频繁导致封IP问题 (Issue #1553) |

缓存是有的，全局的，5分钟

**Comment by Binaryify** [comment]
随便改
