### ISSUE TITLE
pm2 管理app时CPU直线飙升100% 然后 killed

### ISSUE THREAD

**Issue by Cecil0o0** [Binaryify/NeteaseCloudMusicApi#156]
### 环境
系统:  linux ubuntu14

nodejs 版本: v9.2.1

### 出现问题
pm2 管理app时CPU直线飙升100% 然后 killed

### 重现步骤
git clone ....
cd .
npm i
pm2 start app.js --name="netease"
![image](https://user-images.githubusercontent.com/19543313/34339900-97a2a632-e9b5-11e7-8430-dbded1048f0c.png)

### 期待效果
可通过pm2进行管理

**Comment by Binaryify** [comment]
是否是其他因素影响的
![image](https://user-images.githubusercontent.com/12221718/34376256-cc592b50-eb25-11e7-8b61-ddf92a8b9de2.png)

**Comment by a632079** [comment]
同使用 pm2 管理應用，並未發現類似的情況
