### ISSUE TITLE
/song/detail请求歌曲详情时出现-462让验证的问题

### ISSUE THREAD

**Issue by x545756792** [Binaryify/NeteaseCloudMusicApi#1560]
## 环境
- 系统/平台: windows服务器

- nodejs 版本: 8.12.0

- API版本: 4.2.0

## 出现问题
之前请求都正常，近些天开始请求歌曲详情时`/song/detail?ids=347230`出现code-462的错误, 显示`验证成功后，可进行下一步操作，请验证`，然后打开验证链接也没用显示让在网易云音乐中打开。
![image](https://user-images.githubusercontent.com/49974426/179342138-df1fa585-34d5-4777-b289-0b683605828c.png)

**Comment by Binaryify** [comment]
你看下最新版

**Comment by x545756792** [comment]
换了最新版以及更新node版本后就可以了，谢谢呀！
