### ISSUE TITLE
接口调不了

### ISSUE THREAD

**Issue by csyasin** [Binaryify/NeteaseCloudMusicApi#157]
### 环境
系统:  
macOS 10.13.2
nodejs 版本:
9.3.0
### 出现问题
浏览器直接贴 localhost:3000/demoAPI 能获取到数据
但是为啥项目中用 axios 发送 get 请求会报错? 错误如下:
Failed to load localhost:3000/personalized/privatecontent: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
可能我的问题有点小白, 不过这确实困扰我好几天了, 帮帮忙啊大佬, 非常感谢!
### 期待效果

**Comment by csyasin** [comment]
已解决~~ 我是在 vue-cli 生成的项目中用的, 需要配置一下它启的服务的代理就能用了

**Comment by Binaryify** [comment]
源码里的 app.js 有跨域的设置

**Comment by csyasin** [comment]
蟹蟹大佬~
