### ISSUE TITLE
登录一直显示460网络太拥挤 但postman测试却可以获取到数据

### ISSUE THREAD

**Issue by zhzzzzzz66** [Binaryify/NeteaseCloudMusicApi#1570]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
<请清晰描述现在的效果和期待的效果>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/180650000-8b2ffdaa-d622-4c8e-9148-8c21e11db70a.png)
这行注释掉看看

**Comment by imppresser** [comment]
不行哦，依旧提示460

**Comment by imppresser** [comment]
460 cheating 的问题把 utils/request.js 里面的 headers['X-Real-IP'] 的注释取消掉就好

**Comment by ZhiJieRao** [comment]
怎么现在变成10003了

**Comment by strugglinglee** [comment]
> 460 cheating 的问题把 utils/request.js 里面的 headers['X-Real-IP'] 的注释取消掉就好
> 
> 这两个一起设置了好像可以了

还是不行 有新进展帮忙回复下~

**Comment by LTDSA** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/180650000-8b2ffdaa-d622-4c8e-9148-8c21e11db70a.png) 这行注释掉看看

修改后由 460 变成 406 错误了，提示信息为「操作太频繁」😂

**Comment by olbb** [comment]
我这看到的情况是第一次调登录的时候会返回-460，然后带一个
｜NMTID=XXX; Max-Age=315360000; Expires=Fri, 30 Jul 2032 03:12:31 GMT; Path=/;
这样的cookie,
然后带这个cookie 再去请求一次就能成

**Comment by y1713375484** [comment]
> 我这看到的情况是第一次调登录的时候会返回-460，然后带一个 |NMTID=XXX;最大年龄= 315360000;过期=星期五， 30 七月 2032 03：12：31 GMT;路径=/; 这样的cookie， 然后带这个cookie 再去请求一次就能成

这样是能登录上去，但是后续操作一些需要登录的api还是不行哎

**Comment by Jedsek** [comment]
我把utils/request.js 里面的 headers['X-Real-IP'] 给注释掉就好了 ?_?

**Comment by zhangwenboi** [comment]
有哪位大神解决了吗 楼上的方法都试过了还是不行

**Comment by y1713375484** [comment]
> 

放弃了，用扫码登录吧

**Comment by y1713375484** [comment]
> 有哪位大神解决了吗 楼上的方法都试过了还是不行

用扫码登录吧

**Comment by Flysky12138** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/180650000-8b2ffdaa-d622-4c8e-9148-8c21e11db70a.png) 这行注释掉看看

我这里是本地运行自己项目，使用本地接口登录没问题。但是线上项目，使用本地接口登陆时，返回如下：

```json
{"code":-460,"message":"网络太拥挤，请稍候再试！"}
```

看了下请求的响应标头报错如下：
此 `Set-Cookie` 标头未指定 `SameSite` 属性，默认为 `SameSite=Lax`，并且已被屏蔽，因为它来自一个跨网站相应，而该响应并不是对顶级导航操作的响应。此 `Set-Cookie` 必须在设置时指定 `SameSite=None` ，才能跨网站使用。

**Comment by zhzzzzzz66** [comment]
问一下大佬 我在写二维码登录 为啥我每次第一次进入扫码登录时 二维码图扫码后手机上显示让我手机号登录或者其他登录 我必须刷新一次二维码 才会是授权登录 还有就是我设置了一个定时器判断二维码状态 但是就算我授权登陆了 还是返回801 这是咋回事&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月24日(星期天) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 登录一直显示460网络太拥挤 但postman测试却可以获取到数据 (Issue #1570)





 

 这行注释掉看看

**Comment by zhzzzzzz66** [comment]
问一下大佬 我现在写二维码登录呢 为啥每次第一次获取二维码图 扫码后 手机显示手机登录或者其他登录 我必须刷新一次二维码才会是授权登录&nbsp; &nbsp;还有就是我设置了一个定时器来判断二维码的状态 但是就算我授权了 状态还是801 一直是等待扫码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午3:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 登录一直显示460网络太拥挤 但postman测试却可以获取到数据 (Issue #1570)





 
460 cheating 的问题把 utils/request.js 里面的 headers['X-Real-IP'] 的注释取消掉就好

**Comment by Binaryify** [comment]
@zhzzzzzz66 时间戳加了吗

**Comment by kzj0916** [comment]
-460怎么解决啊？之前还没有，现在就不行了，换二维码登录可以吗

**Comment by jiejiege15** [comment]
> 问一下大佬 我现在写二维码登录呢 为啥每次第一次获取二维码图 扫码后 手机显示手机登录或者其他登录 我必须刷新一次二维码才会是授权登录&nbsp; &nbsp;还有就是我设置了一个定时器来判断二维码的状态 但是就算我授权了 状态还是801 一直是等待扫码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Binaryify/NeteaseCloudMusicApi" ***@***.***&gt;; 发送时间:&nbsp;2022年7月25日(星期一) 下午3:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 登录一直显示460网络太拥挤 但postman测试却可以获取到数据 (Issue #1570) 460 cheating 的问题把 utils/request.js 里面的 headers['X-Real-IP'] 的注释取消掉就好 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

二维码那加上时间戳
