### ISSUE TITLE
获取歌单详情（ /playlist/detail） 及 排行榜详情（/top/list ） 又出现只有一首歌的数据的情况

### ISSUE THREAD

**Issue by have-not-BUG** [Binaryify/NeteaseCloudMusicApi#158]
### 环境
系统:  
windows
nodejs 版本:
4.0.0

### 出现问题
获取歌单详情（ /playlist/detail?xxx） 及 排行榜详情（/top/list?xxx ） 又出现只有一首歌的数据的情况

### 重现步骤
访问对应网址即可

### 期待效果
期待能够将接口重新更新下。谢谢~  辛苦了~

**Comment by Binaryify** [comment]
id发来

**Comment by have-not-BUG** [comment]
我去，刚刚测试又正常了。。。不过貌似歌单详情（playlist/detail）、排行榜详情（/top/list）这两个数据接口不是特别稳定：5天前在我这出现504访问超时错误（应该持续了3个小时左右），4小时前出现只展示一首歌曲的数据的情况；这两次出错时，我测试了下其他数据接口都正常。

**Comment by Binaryify** [comment]
应该是网易那边搞事
