### ISSUE TITLE
逆向酷狗api

### ISSUE THREAD

**Issue by maoxikun** [Binaryify/NeteaseCloudMusicApi#1586]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
因为老版本酷狗下载的是没有加密的文件（mp3这种通用格式），最近分析了一下酷狗的android版app，发现登录功能调用了so库加密，目前只能写个android的demo加载so去加密，，大佬会考虑逆向酷狗相关的api吗？
贴一下吾爱的帖子：https://www.52pojie.cn/thread-1613545-1-1.html

**Comment by Binaryify** [comment]
没有这个考虑
