### ISSUE TITLE
登录接口拿不到cookies 了 是什么情况？

### ISSUE THREAD

**Issue by LengYXin** [Binaryify/NeteaseCloudMusicApi#159]
登录接口拿不到cookies 了 是什么情况？
手机号登录。前几天还是好的。

**Comment by LengYXin** [comment]
解决了。
SET-COOKIE:MUSIC_U=587d4aab995cea7a4425161aac046f9a947e38d2400bcb36de0af1026cec19df4cfc2f51aaac8aae178773f3eceb2aa6929204c207ebca78bf122d59fa1ed6a2; Path=/; HttpOnly; Domain=.music.163.com
SET-COOKIE:__csrf=34cca5da19c656b9a9f5342b68c7918e; Domain=.music.163.com; Expires=Sat, 13-Jan-2018 06:14:14 GMT; Path=/

这是 网易云最新的cookie 指定了 Domain=.music.163.com
我在 loginCellphone.js  
把这个设置去除了 客户端就能接受到了cookie 了
 (music_req, cookie) => {
      //去除 Domain
      cookie = cookie.map(x => x.replace("Domain=.music.163.com", ""))
      res.set({
        'Set-Cookie': cookie
      })
      res.send(music_req)
    },
作者。是这么个意思吧？

**Comment by Binaryify** [comment]
应该是
