### ISSUE TITLE
请问你params参数是怎么解析的？能否告知一下。

### ISSUE THREAD

**Issue by linkenliu** [Binaryify/NeteaseCloudMusicApi#16]

**Comment by Binaryify** [comment]
解析部分我是参考这几个链接的,并没有重新实现
[https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90](https://github.com/darknessomi/musicbox/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%96%B0%E7%99%BB%E5%BD%95API%E5%88%86%E6%9E%90)

[https://github.com/disoul/electron-cloud-music/blob/develop/server/crypto.js](https://github.com/disoul/electron-cloud-music/blob/develop/server/crypto.js)
