### ISSUE TITLE
cookie 问题

### ISSUE THREAD

**Issue by jessjava** [Binaryify/NeteaseCloudMusicApi#160]
### 环境
系统:   macos

nodejs 版本:
les8

### 出现问题
cookie 疑问

### 重现步骤
按照 api 上说的，大部分接口需要 cookie，我搞不明白 cookie 怎么设置的。比如你登陆之后只要有 uid，/user/detail 这个接口就一直能使用。无需 cookie 信息。登陆之后 cookie 怎么保存到浏览器的？postman 怎么模拟？cookie 和 localhost 啥关系？

### 期待效果

**Comment by Binaryify** [comment]
先去网上查看相关内容吧

**Comment by jessjava** [comment]
你就没看我说的吧。你的接口不对。没有cookie信息还是能用uid查询。
