### ISSUE TITLE
调用退出登录接口无效

### ISSUE THREAD

**Issue by CrazyCatZhang** [Binaryify/NeteaseCloudMusicApi#1620]
## 环境
- 系统/平台: macOS  Monterey

- nodejs 版本: v16.15.0

- API版本: 4.8.2

## 出现问题
在我使用邮箱密码登录之后，退出登录，我再使用手机验证码登录，这时候我调用登录状态的接口返回的还是邮箱登录的账户，刷新登录之后依然还是返回的邮箱登录的账户

## 重现步骤
1. 先调用邮箱登录的接口，返回成功的数据
2. 调用退出登录接口('/logout')，返回了 {code:200}
3. 然后再使用手机验证码登录
4. 调用登录状态的接口('/login/status')，返回的还是前面邮箱账户登录的数据

## 期待效果
调用登录状态的接口能够返回当前帐户的信息

**Comment by Binaryify** [comment]
时间戳加了吗

**Comment by CrazyCatZhang** [comment]
> 时间戳加了吗

感谢 登录加了时间戳之后正常了
