### ISSUE TITLE
使用接口/login/qr/check后返回{"code":404,"data":null,"msg":"Not Found"}

### ISSUE THREAD

**Issue by gozaoo** [Binaryify/NeteaseCloudMusicApi#1656]
## 环境
- 系统/平台: windows 10

- nodejs 版本: v18.8.0

- API版本: 4.8.2

## 出现问题
全部按照文档使用时，信息返回{"code":404,"data":null,"msg":"Not Found"}

## 重现步骤
如下图，均为统一unikey，该接口貌似已经过时，
/login/qr/key和/login/qr/create仍然可用，但是/login/qr/check会报错
![image](https://user-images.githubusercontent.com/81862662/209040594-2fa51088-952c-4023-9674-d5d2c6ac1205.png)
![image](https://user-images.githubusercontent.com/81862662/209040614-9c3a4475-7ae3-4886-b5f7-da3b9f23f1f4.png)
![image](https://user-images.githubusercontent.com/81862662/209040626-8eb06cc4-c089-476b-b023-6dd6c11840cf.png)
![image](https://user-images.githubusercontent.com/81862662/209040788-4143b774-9088-4a38-9910-a48b13e67039.png)

## 期待效果
忘解决

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by xxw-iwnl** [comment]
老哥你当时是怎么解决的啊
