### ISSUE TITLE
<手机号登录失败 issues>

### ISSUE THREAD

**Issue by pyy-j2me** [Binaryify/NeteaseCloudMusicApi#1658]
## 环境
- 系统/平台: 服务器：Termux
- 
- 平台：网页/Symbian

- nodejs 版本: 18.12.1

- API版本: 4.8.4

## 出现问题
手机号登录是报错：
{"code":-460,"message":"网络太拥挤，请稍候再试！"}
邮箱登录都没有问题

## 重现步骤
http://***.***.***.***:3000/login/cellphone?phone=***********&password=****************(手机号和密码都正确)

## 期待效果
<请清晰描述现在的效果和期待的效果>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by imppresser** [comment]
+1

**Comment by jiangxiaoqiang** [comment]
相同的问题

**Comment by jiangxiaoqiang** [comment]
有没有朋友知道网易云开放接口的url，这里看了只有部分而且url不是这样的：https://developer.music.163.com/st/developer/document?category=sandbox

**Comment by imppresser** [comment]
然而今天又不能用了

**Comment by jiangxiaoqiang** [comment]
> 然而今天又不能用了

可能是网易云又改了 但是不知道在哪里看网易云的接口文档啊

**Comment by jiangxiaoqiang** [comment]
这些个接口难道是逆向网易云app搞到手的？

**Comment by SanPhantom** [comment]
![image](https://user-images.githubusercontent.com/34148994/210218290-692e07b2-e5b3-450c-b556-f43921035484.png)
把appver的值向下调整一下就好了，从2.10.6跳到2.10.5就好了

**Comment by Binaryify** [comment]
@SanPhantom 还真可以,我更新下

**Comment by imppresser** [comment]
貌似还不行，这个接口有点问题把

**Comment by Mamong** [comment]
亲测4.8.6仍然460

**Comment by Binaryify** [comment]
@imppresser  @Mamong  再更新下吧

**Comment by tree-white** [comment]
昨天还可以 今天又挂了

**Comment by insomnia-sy** [comment]
克隆新的源代码，还是{"code":-460,"message":"网络太拥挤，请稍候再试！"} @Binaryify

**Comment by Binaryify** [comment]
@insomnia-sy  是 v4.8.7 吗

**Comment by insomnia-sy** [comment]
是的

**Comment by tree-white** [comment]
> @insomnia-sy 是 v4.8.7 吗

我 4.8.7 正常了

**Comment by insomnia-sy** [comment]
我再试试

**Comment by insomnia-sy** [comment]
我这边也正常了

**Comment by Mamong** [comment]
4.8.7可以了，谢谢你的努力

**Comment by wuxin0011** [comment]
ok,谢谢了 4.8.7版本的确可以了
