### ISSUE TITLE
comment like bug

### ISSUE THREAD

**Issue by 422563261** [Binaryify/NeteaseCloudMusicApi#166]
### 环境
系统:  mac

nodejs 版本:  8.9.1

### 出现问题

/comment/like?id=186016&cid=4956438&t=0&type=0
评论点赞无效，实测。取消点赞有效。

### 重现步骤

点赞，观察无效。已重启服务，重新登陆多次，均无效。

### 期待效果

实现点赞

**Comment by Binaryify** [comment]
确实有这个问题,在排查

**Comment by Binaryify** [comment]
暂时找不到办法

**Comment by 422563261** [comment]
好的，感谢大佬排查。我会持续关注。

**Comment by Binaryify** [comment]
@422563261 
新版本已经修复了这个问题了

**Comment by Binaryify** [comment]
感谢反馈

**Comment by Binaryify** [comment]
注意加时间戳免得被缓存

**Comment by 422563261** [comment]
@Binaryify  好的，感谢楼主抽出时间维护。
