### ISSUE TITLE
网易云api自带罗马音歌词接口

### ISSUE THREAD

**Issue by Mai-icy** [Binaryify/NeteaseCloudMusicApi#1663]
api接口：`http://music.163.com/api/song/lyric?id={}&lv=-1&kv=-1&tv=-1&rv=-1`
参数`rv`指定为-1即可

url示例：https://music.163.com/api/song/lyric?id=27853410&lv=-1&kv=-1&tv=-1&rv=-1

json对应key`romalrc`

使用例：[api](https://github.com/Mai-icy/Spotify-lyrics-window/blob/main/SpotifyLyricWindow/common/api/lyric_api/cloud_api.py)

**Comment by Binaryify** [comment]
这个已经是支持了的
![image](https://user-images.githubusercontent.com/12221718/210162889-0271c157-624f-414c-ba17-fc8e1e404267.png)

**Comment by Mai-icy** [comment]
没事了，我是看旧的issue提的。
