### ISSUE TITLE
v4.8.6返回信息乱码

### ISSUE THREAD

**Issue by Kaidesuyo** [Binaryify/NeteaseCloudMusicApi#1666]
## 环境
- 系统/平台: Windows11
- nodejs 版本: v18.12.0

- API版本: v4.8.6

## 出现问题
返回信息错误
![image](https://user-images.githubusercontent.com/36076659/210437664-f47172ec-1b48-45e4-9716-f54a6eb53c5f.png)

## 重现步骤
在v4.8.5版本是正常的
![image](https://user-images.githubusercontent.com/36076659/210437888-a9800c0a-be61-45b0-bc8d-fcf131634401.png)

**Comment by Binaryify** [comment]
v4.8.7呢

**Comment by Kaidesuyo** [comment]
> v4.8.7呢

在v4.8.7下运行正常且手机登录成功
