### ISSUE TITLE
歌单超过1000首歌曲，怎么获取剩下的歌曲信息？

### ISSUE THREAD

**Issue by SamWeiss1990** [Binaryify/NeteaseCloudMusicApi#167]

**Comment by Binaryify** [comment]
能否发返回内容截图

**Comment by Binaryify** [comment]
歌单现在无1000限制了

**Comment by SamWeiss1990** [comment]
![screenshot at jan 14 00-49-40](https://user-images.githubusercontent.com/20994133/34908071-da4b8bf2-f8c4-11e7-8135-1b89c2dbe8b7.png)
- 请看截图
- 这个接口http://localhost:3000/playlist/detail?id=42337087
   - 只能拿到歌单所有歌曲的id，而并非所有歌曲的信息，超过1000首歌曲，怎么获取剩下的歌曲信息？

**Comment by Binaryify** [comment]
更新到最新版应该没这个限制了

**Comment by SamWeiss1990** [comment]
我更新到了v2.8.0，为什么还是只拿到1000首歌， @Binaryify 你那边能否截个图呢？谢谢🙏

**Comment by Binaryify** [comment]
更新到 v2.8.5

**Comment by damiss** [comment]
作者您好，目前版本是v2.8.5，`playlist `中 ` tracks` 只能默认返回10首歌的信息，而 `trackIds` 则是完整的。
如图：
![error](https://user-images.githubusercontent.com/23253098/34993021-f8c2f2c2-fb09-11e7-95a7-d5cb55127f07.PNG)
![error2](https://user-images.githubusercontent.com/23253098/34993023-f8ffad34-fb09-11e7-83a6-fc4e63d75420.PNG)
以上为两个不同的 `playlist` 的数据，`trackIds`始终是10个

**Comment by Binaryify** [comment]
你把你的 uid 发我

**Comment by damiss** [comment]
playlist?id=2001198978

**Comment by Binaryify** [comment]
@damiss 
你再更新下试试

**Comment by damiss** [comment]
@Binaryify 
现在 `tracks` 和 `trackIds` 的 `length` 一样了
辛苦！

**Comment by Binaryify** [comment]
@damiss 嗯,没事

**Comment by SamWeiss1990** [comment]
![screenshot at jan 17 23-20-55](https://user-images.githubusercontent.com/20994133/35050178-2ad7a982-fbdd-11e7-92f7-b7e6ad81d766.png)
@Binaryify 太棒了，已经完美解决了！！感谢作者🙏
