### ISSUE TITLE
请问是否可以增加听歌识曲的API？

### ISSUE THREAD

**Issue by TotoWang-hhh** [Binaryify/NeteaseCloudMusicApi#1672]
# 描述

**我的想象：** 传base64的音频或者链接，然后API返回识曲结果

不知道能不能做，但是我先提出来，应该就会有人试（逝）试（世）

**Comment by TotoWang-hhh** [comment]
从网易云的识曲chrome插件里找到了API的网址，可能是https://music.163.com/api/music/audio/match

问题在于不清楚怎么传参数，感觉做这个项目的大佬们应该能整出来

**Comment by Binaryify** [comment]
感觉没啥意义，有接口也要你实现客户端的功能，还不如用官方的

**Comment by TotoWang-hhh** [comment]
> 感觉没啥意义，有接口也要你实现客户端的功能，还不如用官方的

回复是真的够快👍

**Comment by Binaryify** [comment]
https://github.com/userZheng686/wyySongIdentify

**Comment by TotoWang-hhh** [comment]
> https://github.com/userZheng686/wyySongIdentify 这里有别人的demo

谢谢
