### ISSUE TITLE
关于 /login/refresh 刷新登陆的问题

### ISSUE THREAD

**Issue by zhuyan0302** [Binaryify/NeteaseCloudMusicApi#168]
### 环境
系统:  window10

react 项目

登陆完之后
我直接调用这个接口，显示 {  code: 301, msg: null} 
或者是登陆完之后，刷新页面的时候去访问这个接口（做了路由验证，每次访问路由都会去调用），显示 {  code: 301, msg: null}

**Comment by zhuyan0302** [comment]
现在连 浏览器cookie 都设置不上了~~~卧槽

**Comment by zhuyan0302** [comment]
![tim 20180107214523](https://user-images.githubusercontent.com/22267227/34650008-76a817de-f3f4-11e7-8aaa-0a340149cede.png)

**Comment by zhuyan0302** [comment]
![tim 20180107214537](https://user-images.githubusercontent.com/22267227/34650019-af10eb8c-f3f4-11e7-942d-8962b9edad85.png)

cookie 并没有设置上

**Comment by Binaryify** [comment]
cookie 需要你 ajax 设置那里带上的

**Comment by zhuyan0302** [comment]
@Binaryify 我还没有登陆的时候cookie 从哪里来的~~~ 我用的是axios 发送请求~

**Comment by Binaryify** [comment]
参考这个
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/127

**Comment by zhuyan0302** [comment]
@Binaryify 是不是你的cookie 设置了httpOnly，我这边浏览器保存不了你的cookie

**Comment by Binaryify** [comment]
你跑下我 #127 那个例子,cookie 是在3000端口上的

**Comment by zhuyan0302** [comment]
大哥，我的错，妈的，我之前是这样的
```
axios.request({
            method: 'get',
            url: apiUrl,
            withCredentials: true
})
```
后来我改成你这样，就可以了，卧槽，为毛还多了个xhrFields，我得去看看axios 文档~自己挖的坑
谢谢了~
```
axios.request({
            method: 'get',
            url: apiUrl,
            xhrFields: {
                withCredentials: true
            },
        })
```

**Comment by Binaryify** [comment]
哈哈

**Comment by zhuyan0302** [comment]
不行，原来我那个 cookie 是运用你那个demo 有的，不是我自己的项目的~。。。我搞错了

我看到过你那个解决是设置 withCredentials: true

我在响应的信息里面看到了，已经生效了

现在的问题就是：
访问登陆接口，响应头有set-cookie，但是，浏览器application 的cookie 并没有设置

**Comment by Binaryify** [comment]
cookie 是设置到接口那个端口的

**Comment by zhuyan0302** [comment]
我试了一下，一开始我的项目端口是5555，然后你的api 端口还是3000，然后我通过代理请求你的api，这样子不行，浏览器没有自动设置cookie，然后我又改变端口，把我项目的端口改成3000，把你api的端口改成4000，继续通过代理，还是没有自动设置cookie

**Comment by zhuyan0302** [comment]
大佬哥哥，这回我真的知道错了，真的。。。。截止22：02分，我依旧在用你的旧版api

**Comment by Binaryify** [comment]
现在呢

**Comment by zhuyan0302** [comment]
已经解决。。。
