### ISSUE TITLE
获取已收藏专辑列表接口 /album/sublist，请求返回结果：{"msg":"参数错误","code":400}

### ISSUE THREAD

**Issue by LikeK423** [Binaryify/NeteaseCloudMusicApi#1683]
## 环境
- 系统/平台: 云服务器CentOS 8.2

- nodejs 版本: 16.19.0

- API版本: 4.8.7

## 出现问题
项目使用Vue+axios，本地项目请求服务器api。
当我请求 /album/sublist 时，请求方式为get，cookie拼接在url，响应结果为{"msg":"参数错误","code":400}{"msg":"参数错误","code":400}。
但是当我请求其它api接口时均没有问题，我可以确认cookie没有问题。
## 重现步骤
1. 接口
![image](https://user-images.githubusercontent.com/88269600/214088097-2366bd60-1fd2-47b9-b799-e47dbc02f158.png)
2. 尝试请求
url不携带limit和offset参数、url携带limit和offset参数时，响应结果均是{"msg":"参数错误","code":400}

![image](https://user-images.githubusercontent.com/88269600/214094115-1fd87c75-83a0-4237-b799-79ff55e31af9.png)
![image](https://user-images.githubusercontent.com/88269600/214094336-9993f406-8257-4bfa-a846-175856a7221e.png)

3. 返回结果
![image](https://user-images.githubusercontent.com/88269600/214090541-12e35d1c-b280-4fe8-abc9-39b8d9a76632.png)
![image](https://user-images.githubusercontent.com/88269600/214095473-338c85a0-76fc-4983-b1d1-46cd7c704a29.png)

**Comment by LikeK423** [comment]
绷不住了，提交完发现是少了一个t。我的错，打扰大家了

**Comment by LikeK423** [comment]
如果可以删除请删除吧

**Comment by Binaryify** [comment]
嗯
