### ISSUE TITLE
无法请求无损音质音频，且付费下载的音乐无法请求128K以上的音质

### ISSUE THREAD

**Issue by iamPorter** [Binaryify/NeteaseCloudMusicApi#1685]
## 环境
- 系统/平台: Windows 10 22H2 64位

- nodejs 版本: 19.3.0

- API版本: 理论上是4.8.9

## 出现问题
自动/手动使用[说明文档中这段描述](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E8%8E%B7%E5%8F%96%E9%9F%B3%E4%B9%90-url)和下文“新版”指示的音乐请求时，所有音乐不能请求Loseless和Hi-Res并返回null（使用对应br值会返回320k或128k），一般的付费下载音乐不能请求128K以上音质（手动调整br至192000或320000亦回复128k音频，手动协调无损会回复null）。

## 重现步骤
参见截图，截图前两张是标准付费歌曲“词不达意 - 夏语遥”，第三张是免费单曲“Fleeting Colors in Flight 飞彩镌流年 - HOYO-MiX”
![image](https://user-images.githubusercontent.com/103353940/214348244-4ecdcad3-c5c4-4a94-88a4-916a3adb1d9b.png)
![image](https://user-images.githubusercontent.com/103353940/214348450-cbeeda5b-d285-4cd4-86a9-a08410969933.png)
![image](https://user-images.githubusercontent.com/103353940/214348722-5929e12a-5d22-4743-b100-e5d0a473b060.png)

## 期待效果
可以自动或手动请求高音质。
高音质实现可以看看[MyFreeMP3](http://tools.liumingye.cn/music_old/)里面的“C”搜索通道。未必要直接超链接，但希望至少能请求到高音质。
或许也可以看看网易云解灰UnblockNetEaseMusic。

**Comment by kengwang** [comment]
请确保你是否登录, 按理说只有登录了才能获取到高音质

**Comment by iamPorter** [comment]
> 请确保你是否登录, 按理说只有登录了才能获取到高音质

我在YesPlayMusic测试过登录请求，请求到的似乎与登录前没变化。
不过[MyFreeMP3](http://tools.liumingye.cn/music)没登录（甚至没有登录入口）就可以请求任意音质。是[Meting](https://github.com/metowolf/Meting)和这个程序的实现方法不同还是自身程序有问题？

**Comment by iamPorter** [comment]
订正一点，MyFreeMP3要用B搜索

**Comment by liyang-it** [comment]
无损音质是需要登录的，并且登录账号还要是会员账号才可以，否则一直会返回mp3格式，MyFreeMP3、方格音乐都是会登录的，只不过他们登录的是作者自己的账号并且还是会员，这样别人用的时候，其实用的是 作者会员网易云账户调用API

**Comment by liyang-it** [comment]
> ## 测试时分别使用了[BlurLyric](https://github.com/gozaoo/BlurLyric)和[YesPlayMusic](https://github.com/qier222/YesPlayMusic)的最新版本（即将发布）。因为是开启手动API的请求URL检查，所以可以基本排除这两个第三方程序的API之外的问题。
> ## 环境
> * 系统/平台: Windows 10 22H2 64位
> * Nodejs 版本：19.3.0
> * API版本：理论上是4.8.9
> 
> ## 出现问题
> 自动/手动使用[说明文档中可能描述](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E8%8E%B7%E5%8F%96%E9%9F%B3%E4%B9%90-url)和下面“新版本”指示的音乐请求时，所有音乐不能请求Loseless和Hi-Res并返回null（使用响应br值会返回320k或128k），一般的付费下载音乐不能请求128K以上音质（手动调整br至192000或320000亦回复128k音频，手动调整无损会回复null）。
> 
> ## 重置步骤
> 除截图外，截图前两张是标准付费歌曲“词不达意 - 夏语遥”，第三张是免费单曲“Fleeting Colors in Flight 飞彩预见流年 - HOYO-MiX” ![图像](https://user-images.githubusercontent.com/103353940/214348244-4ecdcad3-c5c4-4a94-88a4-916a3adb1d9b.png) ![图像](https://user-images.githubusercontent.com/103353940/214348450-cbeeda5b-d285-4cd4-86a9-a08410969933.png) ![图像](https://user-images.githubusercontent.com/103353940/214348722-5929e12a-5d22-4743-b100-e5d0a473b060.png)
> 
> ## 预期效果
> 可以自动或手动请求高音质。需要 高音质实现看看可以[MyFreeMP3](http://tools.liumingye.cn/music_old/)里面的“C”搜索通道。未直接超链接，但希望至少能请求到高音质。 或许也可以看看网易云解灰UnblockNetEaseMusic。

那是因为 MyFreeMP3已经内置登录了，登录的账号是作者自己的会员账户，实际上就是别人用MyFreeMP3的时候就是用的作者会员账户请求API的
