### ISSUE TITLE
图片为啥总是默认的图片？

### ISSUE THREAD

**Issue by Randomclass12** [Binaryify/NeteaseCloudMusicApi#1686]
![image](https://user-images.githubusercontent.com/89193674/214761905-2b07b112-5c77-46eb-b55b-dcc0c0e5b2e4.png)

**Comment by Binaryify** [comment]
封面是专辑的,不是歌曲的

**Comment by Randomclass12** [comment]
![image](https://user-images.githubusercontent.com/89193674/214855250-494575fc-d4e7-4e6d-8eba-c0d1af54c97b.png)
好了 好了 接口调错了[doge]
