### ISSUE TITLE
登录接口问题

### ISSUE THREAD

**Issue by Akesaka-Hitsuki** [Binaryify/NeteaseCloudMusicApi#1687]
## 环境
- 系统/平台: ubuntu 20.04

- nodejs 版本: 16.18.0

- API版本: 4.8.9

## 出现问题
login接口无法直接登录

## 重现步骤
调用/login/cellphone?phone=xxxxxxxx&captcha=xxx 返回以下内容
```
{
  status: 400,
  body: {
    code: -462,
    data: {
      actionCode: '11*****',
      verifyType: 40,
      verifyId: ****,
      verifyUrl: 'https://st.music.163.com/encrypt-pages',
      blockText: '验证成功后，可进行下一步操作哦~\t',
      verifyToken: '00.40.*********2f917490da72eff7c023039.**********',
      btnText: null,
      orpheusUrl: null,
      frontRuleIds: [Array],
      params: [Object],
      url: 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A
%22f68df0299b875b0dd6367988a93960cc%22%2C%22event_id%22%3A%2200326971157822
906382%22%7D&verifyType=40&verifyId=****&verifyToken=00.40.*********2f917490
da72eff7c023039.**********&actionCode=11*****'
    },
    message: null
  }
}
```

## 期待效果
调用接口后直接登录

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Mamong** [comment]
终于有人提了，群里说是开启了云盾，建议用扫码登录

**Comment by null0034** [comment]
我以为是我的打开方式不对，多个账号测试了半天😂

**Comment by jacker996icu** [comment]
现在只能用二维码登录了么？

**Comment by jiqiren116** [comment]
可以参考文档中的邮箱登录，前提是网易云音乐已经绑定了163邮箱

**Comment by MinG252** [comment]
邮箱二维码登录会显示，"当前登录存在安全风险，请稍后再试"

**Comment by Binaryify** [comment]
都用二维码登录吧

**Comment by LINycA** [comment]
应该是根据登录帐号的id密码啥的做成了md5加密，然后去网易易盾获取了滑块验证码的图片地址及id，token等参数，滑块操作完成后，会发到网易易盾的验证接口进行验证，验证成功会返回相应的validate，update至登录接口参数，随登录所需参数一并post到上游接口，菜鸟一个，只知道大概思路，HHH

**Comment by shaoyaoqian** [comment]
> 可以参考文档中的邮箱登录，前提是网易云音乐已经绑定了163邮箱

邮箱可以登陆，但还是没法下载VIP歌曲

**Comment by Qinuay** [comment]
用二维码登录后，有没有可以定期自动刷新cookies有效期的接口？

**Comment by 2811267153** [comment]
![image](https://user-images.githubusercontent.com/67245639/227134402-0cd80eb7-9701-4ebb-bfaf-0f9e57abded3.png)
 我想请教一下 我在请求是携带cookie 为什么会控制台有个错误提示说: "xhr.js:196 Refused to set unsafe header "Cookie"", 不让我是设置请求头的cookie 你们都是怎么携带的cookie呢

**Comment by CrazyCatZhang** [comment]
> ![image](https://user-images.githubusercontent.com/67245639/227134402-0cd80eb7-9701-4ebb-bfaf-0f9e57abded3.png) 我想请教一下 我在请求是携带cookie 为什么会控制台有个错误提示说: "xhr.js:196 Refused to set unsafe header "Cookie"", 不让我是设置请求头的cookie 你们都是怎么携带的cookie呢

我是只要的MUSIC_U那一段作为请求头cookie的

**Comment by wilson201809** [comment]
想干掉它拦截器, 这样可以?

**Comment by 2811267153** [comment]
> 想干掉它截器，这样可以吗？

可以啊 传cookie的时候 直接在请求头里面写就可以了

**Comment by zhijiwuyan** [comment]
我在二维码登录时，遇到手机授权成功 但是pc上返回的code是801  通过 /login/qr/key?timestamp=${Date.now()}  这个获取的unikey 也是保存在 vuex的state中 创建图片和 检测状态也是context.state.unikey 直接获取unikey   不知道哪出问题了em
