### ISSUE TITLE
node app.js 报错

### ISSUE THREAD

**Issue by NiConEG** [Binaryify/NeteaseCloudMusicApi#1689]
## 环境
- 系统/平台: <ubuntu 16.4>

- nodejs 版本: <v8.17.0>

- API版本: <4.8.9>

## 出现问题
调node app.js指令之后：

(node:7217) UnhandledPromiseRejectionWarning: /home/wwwroot/NeteaseCloudMusicApi/node_modules/axios/index.js:1
(function (exports, require, module, __filename, __dirname) { import axios from './lib/axios.js';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wwwroot/NeteaseCloudMusicApi/util/request.js:3:28)
(node:7217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## 重现步骤
1、git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
Cloning into 'NeteaseCloudMusicApi'...
remote: Enumerating objects: 8118, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 8118 (delta 64), reused 89 (delta 53), pack-reused 8012
Receiving objects: 100% (8118/8118), 15.08 MiB | 17.07 MiB/s, done.
Resolving deltas: 100% (5548/5548), done.
Checking connectivity... done.

2、cd NeteaseCloudMusicApi

3、npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> core-js@2.6.11 postinstall /home/wwwroot/NeteaseCloudMusicApi/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN lifecycle NeteaseCloudMusicApi@4.8.9~prepare: cannot run in wd NeteaseCloudMusicApi@4.8.9 husky install (wd=/home/wwwroot/NeteaseCloudMusicApi)
npm WARN NeteaseCloudMusicApi@4.8.9 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 523 packages from 438 contributors and audited 525 packages in 10.116s

82 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

4、 node app.js

(node:7217) UnhandledPromiseRejectionWarning: /home/wwwroot/NeteaseCloudMusicApi/node_modules/axios/index.js:1
(function (exports, require, module, __filename, __dirname) { import axios from './lib/axios.js';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wwwroot/NeteaseCloudMusicApi/util/request.js:3:28)
(node:7217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## 期待效果
<期待正常调起>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by NiConEG** [comment]
服务器架在香港，会有影响吗

**Comment by null0034** [comment]
> 服务器架在香港，会有影响吗

可能会存在影响，部分地区和部分服务器运营商有被屏蔽

**Comment by NiConEG** [comment]
nodejs 12+解决
