### ISSUE TITLE
新版获取音乐URL接口，昨天开始一直返回等待验证

### ISSUE THREAD

**Issue by fangwenjump** [Binaryify/NeteaseCloudMusicApi#1695]
## 环境
- 系统/平台: <你的系统和平台> 
Windows10
- nodejs 版本: <你的 NodeJS 版本号>
 v16.17.0.

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>  
4.8.9

## 出现问题

新版获取音乐URL接口 一直返回验证成功后，可进行下一步操作哦~

## 重现步骤

新版获取音乐URL接口，发送请求直接等待验证

截图

截图https://imgur.com/a/xE1US2Y

## 期待效果
修复

**Comment by a1519630534** [comment]
新版获取音乐url问题截图https://imgur.com/a/xE1US2Y

**Comment by Binaryify** [comment]
登录下

**Comment by fangwenjump** [comment]
> 登录下

已经是登录状态

**Comment by fangwenjump** [comment]
> cookie 带上了吗

我这个前几天没登录也能获取啊，昨天开始就不行了，cookie没带

**Comment by Binaryify** [comment]
网易那边改了，我这边也没办法

**Comment by 2001caihong** [comment]
现在必须要带cookie才能获取吗
