### ISSUE TITLE
关于qrlogin.html里的时间戳参数

### ISSUE THREAD

**Issue by vinceok** [Binaryify/NeteaseCloudMusicApi#1698]
## 环境
- 系统/平台: window 10
- nodejs 版本: 10.15.3
- API版本: 4.8.9

## 出现问题
这个参数到底是timerstamp还是timestamp？我看post请求里必须要加的是timestamp，是拼写错误吗？

## 期待效果

**Comment by Binaryify** [comment]
笔误,url不一样就行,叫啥都可以
