### ISSUE TITLE
没有获取单首歌曲信息的接口？

### ISSUE THREAD

**Issue by poezhang** [Binaryify/NeteaseCloudMusicApi#17]
获取单首歌曲信息的接口中：只有获取音乐url 和 歌词url的接口；
请问是否有获取歌曲详情，例如歌手、歌曲名，歌曲封面的借口么？
通过歌单的接口获取到的歌单中的每首歌曲信息中，不包含以上单首歌曲的详细信息。

**Comment by hj2060** [comment]
我正想问这个问题

**Comment by Binaryify** [comment]
@poezhang 
@hj2060 
是我疏忽了,晚上加上

**Comment by Binaryify** [comment]
@poezhang 
@hj2060 
已更新,版本2.3.4

**Comment by poezhang** [comment]
@Binaryify 辛苦了

**Comment by Binaryify** [comment]
使用过程欢迎提 issues
