### ISSUE TITLE
docker环境下vsz占用高

### ISSUE THREAD

**Issue by konglinSoul** [Binaryify/NeteaseCloudMusicApi#1703]
## 环境
- 系统/平台:  linux（openwrt） docker下安装

- nodejs 版本: 18.12.1  (还有v4.8.9调用的是18.13)

- API版本: v4.8.7以及v4.8.9
## 出现问题

node app.js的vsz占用很高 不知道是否正常
从4.8.9回退到4.8.7也是同样的占用 但功能可以正常使用

![image](https://user-images.githubusercontent.com/48609186/219024350-41bebfba-a012-45a0-ab19-2b6f758fc080.png)
![image](https://user-images.githubusercontent.com/48609186/219024373-30eceaa4-0474-47fb-937b-830abf3afce4.png)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
docker启动后占用 node app.js 占用约300m 过一阵子再查看就变成4416m 重启过后隔一阵子又变成4416

## 期待效果
vsz占用低 谢谢 如果这是正常的希望也可以回复告诉我 谢谢

**Comment by Binaryify** [comment]
正常的吧
![image](https://user-images.githubusercontent.com/12221718/219071296-38453067-a3f5-4282-a803-560c5b38e160.png)
