### ISSUE TITLE
获取云盘歌曲播放链接为null

### ISSUE THREAD

**Issue by Slowhalfframe** [Binaryify/NeteaseCloudMusicApi#1704]
## 环境
- 系统/平台: windows

- nodejs 版本: v16.18.1

- API版本: 4.8.9

## 出现问题
`/song/url/v1?id=449991893&level=lossless`接口，获取不到云盘歌曲播放链接；

`http://music.163.com/song/media/outer/url?id=ID数字.mp3`外链获取方式提示404；在网易云PC和各终端可正常播放该云盘歌曲

## 重现步骤
![image](https://user-images.githubusercontent.com/31118867/219297632-72cf9401-673e-4701-8fbd-6b572e0cf747.png)

## 期待效果
期待可以获取到云盘歌曲播放链接

**Comment by Binaryify** [comment]
cookie 带上了吗

**Comment by Slowhalfframe** [comment]
> cookie 带上了吗

带上了，除云盘外的歌曲全部正常

**Comment by Binaryify** [comment]
你是怎么带上的

**Comment by Slowhalfframe** [comment]
> 你是怎么带上的

在请求头中携带的cookie， 并且在服务端接口处可以打印出携带的cookie（song_url.js/query.cookie）

**Comment by Slowhalfframe** [comment]
> 无法重现,你检查下你的cookie ![image](https://user-images.githubusercontent.com/12221718/219373617-bf157b47-265b-4d3c-8a62-e41d5022f751.png)
> 
> ![image](https://user-images.githubusercontent.com/12221718/219373486-e8bef616-9fa7-4a60-b10a-8df8b45e5378.png)

感谢耐心解答，已解决。
未获取到原因：原本将cookie放到request headers中，改为将cookie放到request body中即获取到。
最后，再次感谢解答

**Comment by Binaryify** [comment]
嗯嗯,解决了就好
