### ISSUE TITLE
请问可以获取网易云最原始的听歌记录吗？

### ISSUE THREAD

**Issue by ijayden-lung** [Binaryify/NeteaseCloudMusicApi#171]
### 环境
系统:  MacOS

nodejs 版本:

### 期待效果
现在获取的听歌纪录是网易云的每周听歌记录和所有的听歌记录，不是听歌记录的原始数据，可以做到获取网易云的原始听歌记录吗？就是每个时间听了什么歌的那个听歌记录。

**Comment by Binaryify** [comment]
暂时没有
