### ISSUE TITLE
无法播放VIP歌曲

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [Binaryify/NeteaseCloudMusicApi#1711]
本地部署，通过C#httpclient调用
使用二维码登陆，确认登陆成功但是在使用[获取音乐 url]后获取的还是片段而不是整首音乐
希望大佬帮助

**Comment by yourboy7** [comment]
登录的账号在网易云音乐中开通会员后获取到的VIP音乐会是完整的。

**Comment by student-ice** [comment]
怎么解决的，我这边二维码登录后，账号也有会员，但是返回的url还是试听片段
