### ISSUE TITLE
登录获取不到cookies的问题

### ISSUE THREAD

**Issue by ldc2726** [Binaryify/NeteaseCloudMusicApi#172]
### 环境
系统:  

nodejs 版本:

### 出现问题
为什么登录成功以后cookies什么都没有呢
### 重现步骤
$.ajax({
			type:"get",
			url:"http://localhost:3000/login/cellphone",
			data:{
				phone:$('.tel').val(),
				password:$('.pass').val()
			}
### 期待效果

**Comment by Binaryify** [comment]
参照 #127 的例子

**Comment by ldc2726** [comment]
我看了例子，还是不咋会，一直返回这个 {"msg":null,"code":301}，怎么看是不是真正的登录成功了啊，用ajax发送请求后，就返回了一组个人的数据就算是成功了吗

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/34704409-f2cc7e0a-f533-11e7-913e-52223f5be50a.png)
301 就不正常了

**Comment by ldc2726** [comment]
我发现好像需要登录后再操作的数据的接口都不能用，都是返回 {"msg":null,"code":301}，我怀疑我只请求到了登录数据，是不是并没有登录成功啊？

**Comment by Binaryify** [comment]
你是用我那个例子吗

**Comment by Binaryify** [comment]
注意设置 
```
xhrFields: {
            withCredentials: true
}
```

**Comment by ldc2726** [comment]
写的基本差不多，最后发现跟你少了一句
xhrFields: {
	            withCredentials: true
	        },
我也加上了

**Comment by Binaryify** [comment]
加了还会吗

**Comment by ldc2726** [comment]
是不是登录的问题啊，get获取登录数据之后，你们就能直接调用这些需要登录才能操作的接口了吗？我本身就是用jquery获取ajax的，加了之后， 还是返回{"msg":null,"code":301}

**Comment by Binaryify** [comment]
你直接用我的例子改改账号和密码也会吗

**Comment by ldc2726** [comment]
那倒不会，我用的react框架写的

**Comment by ldc2726** [comment]
还是301，刚试着用你那个写了一下，打印结果如下：
{loginType: 1, code: 200, account: {…}, profile: {…}, bindings: Array(1)}
 {"msg":null,"code":301}

**Comment by ldc2726** [comment]
app.all('*', function (req, res, next) {
     if (req.path !== '/' && !req.path.includes('.')) {
       res.header('Access-Control-Allow-Credentials', true)
       // 这里获取 origin 请求头 而不是用 *
       res.header('Access-Control-Allow-Origin', req.headers['origin'] || '*')
       res.header('Access-Control-Allow-Headers', 'X-Requested-With')
       res.header('Access-Control-Allow-Methods', 'PUT,POST,GET,DELETE,OPTIONS')
       res.header('Content-Type', 'application/json;charset=utf-8')
     }
     next()
   })
跨域设置不用动吗？

**Comment by Binaryify** [comment]
你控制台有报什么错吗

**Comment by ldc2726** [comment]
没有任何错误，这是我直接拿过来写的一个demo
这个是结果：
{loginType: 1, code: 200, account: {…}, profile: {…}, bindings: Array(1)}
{"msg":null,"code":301}

代码：
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<style>
			
		</style>
	</head>
	<body>
		<input id="phone" />
		<input id="pass" type="password"/>
		<button>huoqu</button>
	</body>
	  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
  <script>
  	
  	$('button').click(function(){
  		var phone = $('#phone').val()
  	var password = $('#pass').val()
  		$.ajax({
      url: "http://localhost:3000/login/cellphone?phone="+phone+"&password="+password,
      
      success: function (data) {
        console.log(data)
        $.ajax({
          url: "http://localhost:3000/recommend/songs ",
          xhrFields: {
            withCredentials: true
          },
          success: function (data) {
            console.log(data)
          },
          error: function (err) {
            console.log(err)
          }
        })
      },
      error: function (err) {
        console.log(err)
      }
    })
  	})
    
  </script>
</html>

**Comment by ldc2726** [comment]
html:
<input id="phone" />
<input id="pass" type="password"/>
<button>huoqu</button>
script:
$('button').click(function(){
  	var phone = $('#phone').val()
  	var password = $('#pass').val()
  		$.ajax({
      url: "http://localhost:3000/login/cellphone?phone="+phone+"&password="+password,
      success: function (data) {
        console.log(data)
        $.ajax({
          url: "http://localhost:3000/recommend/songs ",
          xhrFields: {
            withCredentials: true
          },
          success: function (data) {
            console.log(data)
          },
          error: function (err) {
            console.log(err)
          }
        })
      },
      error: function (err) {
        console.log(err)
      }
    })
  	})

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/34706170-afa6d898-f540-11e7-8c26-e8438b6e4dc9.png)

**Comment by Binaryify** [comment]
那你把源码缓存那部分代码注释了呢
![image](https://user-images.githubusercontent.com/12221718/34706189-d467bce2-f540-11e7-895f-5e369d1fb34e.png)

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/34706239-3fbc1c04-f541-11e7-8cba-4f885684f8e1.png)
![image](https://user-images.githubusercontent.com/34648806/34706241-46e3e034-f541-11e7-9db8-2cc88fae67c2.png)
还是这样

**Comment by ldc2726** [comment]
我目前用的是@2.7.2的版本，我也怀疑会不会是版本的问题，然后重新下载了一遍新的，版本好像是2.8.多了，还是不行，为什么你的可以获取到啊，好奇怪，我这俩天一直写模拟写这个项目，很尴尬，卡到这了

**Comment by Binaryify** [comment]
你看下这个
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/168

**Comment by ldc2726** [comment]
![Uploading image.png…]()
我和他的问题不一样，我重新用了新版的了，
xhrFields: {
            withCredentials: true
          },
ajax请求，上面这个字段也有，
//app.use(cache("2 minutes", onlyStatus200));也注释了

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/34753919-bbdc4cb4-f5f5-11e7-8588-7b2bc2490187.png)

**Comment by Binaryify** [comment]
我调用你的例子也是正常的
![image](https://user-images.githubusercontent.com/12221718/34815663-1dc2642a-f6ed-11e7-9fe7-1597620ea45f.png)

**Comment by ldc2726** [comment]
这是为什么啊，版本一样，内容一样，难道我手机号还有问题嘛，很不理解啊

**Comment by Binaryify** [comment]
你登录那个请求返回的是什么

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/34815851-f1c10fb0-f6ed-11e7-8f6c-25859fc0ec8e.png)

**Comment by Binaryify** [comment]
第一个 content 发我看看

**Comment by ldc2726** [comment]
![image](https://user-images.githubusercontent.com/34648806/34816197-2e9391e6-f6ef-11e7-83ac-50f300fb0c2f.png)

**Comment by Binaryify** [comment]
我这里刚重现到了和你一样的情况,我排查下是什么原因

**Comment by ldc2726** [comment]
嗯嗯，好的，我这一直都是这样的问题，登录也返回个人的数据了，但就是有关登录后再操作的请求一个都用不了，都是返回301，就像是登录只是查询了个人网易云id并没有登录成功一样。

**Comment by Binaryify** [comment]
获取是获取到了,但是和接口不同域,所以 cookie 没带上

**Comment by ldc2726** [comment]
那求大神赐教一下，怎么才能解决这个问题呢

**Comment by Binaryify** [comment]
你可以暂时把 html 放在 public 目录下,同域下使用

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/34816620-62a501d0-f6f0-11e7-9c3b-c8095c7271fa.png)

**Comment by Binaryify** [comment]
我检查下

**Comment by Binaryify** [comment]
明天应该能解决

**Comment by Binaryify** [comment]
诶,我被我之前写的例子带偏了,每个请求都应该带 withCredentials 的
```
xhrFields: {
        withCredentials: true
}
```

比如
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>test</title>
</head>

<body>
  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
  <script>
    $.ajax({
      url: "http://localhost:3000/login/cellphone?phone=phone&password=password",
      xhrFields: {
        withCredentials: true
      },
      success: function (data) {
        console.log(data)
        $.ajax({
          url: "http://localhost:3000/recommend/songs ",
          xhrFields: {
            withCredentials: true
          },
          success: function (data) {
            console.log(data)
          },
          error: function (err) {
            console.log(err)
          }
        })
      },
      error: function (err) {
        console.log(err)
      }
    })
  </script>
</body>

</html>
```

**Comment by YDJSZY** [comment]
这个xhrFields是什么意思？

**Comment by YDJSZY** [comment]
我用jq的版本是可以的。但用ng5的内置http请求不行，因为我没明白你这个xhrFields: {
            withCredentials: true
          },是什么意思？要设置在哪里？
