### ISSUE TITLE
2分钟缓存导致CORS

### ISSUE THREAD

**Issue by meedfine** [Binaryify/NeteaseCloudMusicApi#1722]
## 环境
最新4.8.9

## 出现问题
A网站访问api的一个接口 比如"/top/playlist/highquality"， 服务器返回access-control-allow-origin: A域名
然后B网站两分钟内也访问这个接口，会直接拿到缓存，但因服务器缓存，所以返回上一次的access-control-allow-origin: A域名
导致access-control-allow-origin与B网站不匹配，报CORS

## 重现步骤
![image](https://user-images.githubusercontent.com/35157761/226500394-a37c9d67-19f1-4ce3-bd9d-f3dd4d5eb1d3.png)

## 期待效果
目前我这边通过链接加参数encodeURIComponent(location.origin) 绕过了缓存
但是看看官方能不能在服务端处理下，比如使用缓存时再调整一下access-control-allow-origin

**Comment by Binaryify** [comment]
之后我把域名也加入缓存规则吧

**Comment by Binaryify** [comment]
缓存规则更新了
