### ISSUE TITLE
请问音频跨域怎么处理呢？

### ISSUE THREAD

**Issue by MoGoethe** [Binaryify/NeteaseCloudMusicApi#173]
所有的数据都能正常拿到，但是音频在自己的环境下播放不了。

**Comment by Binaryify** [comment]
请问有错误截图吗

**Comment by MoGoethe** [comment]
有的，稍等，
![image](https://user-images.githubusercontent.com/10860523/34710917-222ef208-f558-11e7-8359-150d073c2fe8.png)

从数据来看，已经完全拿到了，但是加载到audio里面去的时候 无法播放，出现上述错误。

**Comment by Binaryify** [comment]
如果是以
`http://music.163.com/song/media/outer/url?id=33894312.mp3 ` 这种形式加载呢

**Comment by Binaryify** [comment]
我看看是不是网易又改了什么

**Comment by MoGoethe** [comment]
也是不可以的，这种的话出现两种情况，谷歌浏览器没有 声音，火狐浏览器直接无法加载。别的浏览器还没测试。。。

**Comment by Binaryify** [comment]
我也发现了,网易居然在这里改了

**Comment by MoGoethe** [comment]
不知道怎么解决了 ~ 大神有解决方案吗?

**Comment by Binaryify** [comment]
我加个代理吧

**Comment by MoGoethe** [comment]
请问可以大致说一下思路吗？

**Comment by MoGoethe** [comment]
老铁  我知道为什么会出现那个问题了 。
我是用audio对象 用来绘画canvas对象了 于是用到了下面这个东西， 然后就出错了
 const actx = new AudioContext()

**Comment by Binaryify** [comment]
但是音频还是播放不了是吧

**Comment by Binaryify** [comment]
@MoGoethe 
现在是否正常

**Comment by MoGoethe** [comment]
找到原因了，是因为 这条语句：
const audioSrc = actx.createMediaElementSource(audio)   //audio是audio对象
导致的，如果音频地址和当前地址不在同源下面  chrome下会没有声音， safari和火狐会直接报错

但是  现在我又出现了一个新的问题了，，，   我把这个代码放到阿里云的服务器用来提供服务接口服务，可能是近期撸码的时候刷新过于频繁，导致ip被封了。。。。     

大神您有什么解决方案吗？

我打算做接口数据缓存，除开搜索以外，其它的接口数据缓存每次缓存三天。

ip如果没有办法的话，只好换公网ip了。。。

**Comment by Binaryify** [comment]
我源码已经加了缓存处理了,设置了2分钟,你可以看看
