### ISSUE TITLE
4.8版本 获取音乐的url很容易为null

### ISSUE THREAD

**Issue by 2811267153** [Binaryify/NeteaseCloudMusicApi#1730]
## 环境
- 系统/平台: <你的系统和平台>Windows

- nodejs 版本: <你的 NodeJS 版本号> 19

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version> 4.8.0

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>获取musicUrl非常容易出现null

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
![屏幕截图 2023-04-22 144707](https://user-images.githubusercontent.com/67245639/233767860-d90594ef-03db-4e34-8b92-cf138b466604.png)
![image](https://user-images.githubusercontent.com/67245639/233767864-dacd7cd6-934a-47f3-985f-1995288d25d3.png)
![image](https://user-images.githubusercontent.com/67245639/233767890-bf8ffb2f-8241-4600-b4c1-93eb19d75480.png)
这些音乐在手机上可以正常的听的

## 期待效果
<请清晰描述现在的效果和期待的效果>  
返回真是的url地址

**Comment by Binaryify** [comment]
vercel 部署的还是自己的服务器

**Comment by 2811267153** [comment]
> vercel 部署的还是自己的服务器

不好意思 是我自己的问题好像🤣🤣🤣

**Comment by 2811267153** [comment]
> vercel 部署的还是自己的服务器

后面 获取的又是正常的了， 我也不确定还有没有问题
