### ISSUE TITLE
二维码登录后获取用户信息失败

### ISSUE THREAD

**Issue by coderwu-cmd** [Binaryify/NeteaseCloudMusicApi#1736]
## 环境
- 系统/平台: windows

- nodejs 版本: v16.14.0

- API版本: 4.8.10

## 出现问题
  1. 二维码登录成功后只有cookie和message返回
  2. 登录成功后调用/user/subcount接口获取用户信息返回code: 302
  3. 登录成功后访问/video/group?id=9104接口失败

## 重现步骤
![subcount接口](https://user-images.githubusercontent.com/67917197/236282010-b9175fb1-5f12-48c5-ba32-30bba918baed.png)
![group接口](https://user-images.githubusercontent.com/67917197/236282031-ac12c881-e071-4c8c-a39c-4bba5ed6a248.png)

**Comment by C4685** [comment]
就是返回 cookie 的吧，再调用 /login/status 就能获取用户信息了。
