### ISSUE TITLE
对歌单添加或删除歌曲接口失效，返回462验证

### ISSUE THREAD

**Issue by jhwe1** [Binaryify/NeteaseCloudMusicApi#1741]
## 环境
- 系统/平台: Windows11

- nodejs 版本:  Node.js v18.13.0.

- API版本: 4.8.10

## 出现问题
调用"对歌单添加或删除歌曲"接口("/playlist/tracks")对歌单进行添加歌曲时，无法完成添加操作，接口返回{"code":-462,"message":"请完成验证操作"}。
post和get请求结果一样

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
请求url：/playlist/tracks?
携带参数params: {
    timestamp: 1683877263730
    op: add
    pid: 321876813
    tracks: 2000827591
}
命令行打印的response结果
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/121280865/9ba4803f-360b-4383-945f-75e3b9c5d831)

尝试对response结果中的url进行访问，返回信息“请在网易云音乐app内打开本页面”

## 期待效果
希望能正常使用接口

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
登录了吗

**Comment by jhwe1** [comment]
> 登录了吗

登录了

**Comment by jhwe1** [comment]
> 登录了吗



> > 登录了吗
> 
> 登录了

二维码登录的

**Comment by jhwe1** [comment]
> > 登录了吗
> 
> 登录了

二维码登录的
