### ISSUE TITLE
二维码授权802，一直授权中

### ISSUE THREAD

**Issue by NiConEG** [Binaryify/NeteaseCloudMusicApi#1744]
## 环境
- 系统/平台: Android

- nodejs 版本: 12.22.12

- API版本: 4.8.10

## 出现问题
扫描二维码后一直处于授权中，没有返回803。：{"nickname":"elhim","avatarUrl":"https://p2.music.126.net/wxpRNmJe_-U_I81YPqV7ww==/109951166388646458.jpg","code":802,"message":"授权中","cookie":""}

然后换了一个手机授权扫码，授权成功了也不返回803。

## 重现步骤
网易云手机APP扫描设备上集成的二维码

## 期待效果
希望返回803，授权通过。

**Comment by NiConEG** [comment]
平台/系统：Ubuntu  18.04 64位

**Comment by NiConEG** [comment]
> 时间戳加了吗

/login/qr/check?key=%s&timestamp=%u 
加了的

**Comment by NiConEG** [comment]
之前一直都是好的，就这几天用不了了
[OK] /login/qr/check?key= xxxxxxxxxxxxxxxxxx&timestamp=1684402725
[OK] /login/qr/check?key= xxxxxxxxxxxxxxxxxx&timestamp=1684402726
[OK] /login/qr/check?key= xxxxxxxxxxxxxxxxxx&timestamp=1684402727
[OK] /login/qr/check?key= xxxxxxxxxxxxxxxxxx&timestamp=1684402728
[OK] /login/qr/check?key= xxxxxxxxxxxxxxxxxx&timestamp=1684402729

**Comment by Binaryify** [comment]
文档demo正常吗

**Comment by jhwe1** [comment]
> 

文档demo的二维码登录也不行
502报错，返回：Upstream headers size too big, check your upstream.
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/121280865/1184e685-42c8-4dbb-aa93-6c79fb38984a)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/121280865/443beaff-3372-4c14-b3b0-a1c90af321a2)

**Comment by NiConEG** [comment]
这个授权成功之后还是一直在check
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/11752103/9a630110-2110-4ff0-bb57-c383a49cea38)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/11752103/920d61b2-eb88-404e-8356-ba5c3aa917ea)

**Comment by HolgerHuo** [comment]
近期网易云返回的MUSIC_U长度增长了几倍，导致其超过了Nginx默认配置对Header数据长度的限制(网易云会在返回正文和Header中均包含此键值)
可在Nginx中加入
```
proxy_busy_buffers_size   512k;
proxy_buffers   4 512k;
proxy_buffer_size   256k;
```
来增加Header大小限制

关联 #1748 ，可能腾讯云Serverless架构对Header也有大小限制，或许可以尝试修改代码屏蔽掉返回的Set-Cookie header只保留正文中的MUSIC_U来规避

**Comment by Binaryify** [comment]
拉下最新代码，qr/check 接口需要带上noCookie参数
