### ISSUE TITLE
添加对新音质的支持

### ISSUE THREAD

**Issue by iamPorter** [Binaryify/NeteaseCloudMusicApi#1747]
**功能描述**
- 现在网易云音乐新增了三个新的音质选项，希望API可以添加。

**程序图像**
![9976D822-8C21-475D-8100-25A10FC784F2](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/103353940/d05acb06-c97f-47aa-9aee-b276363d0e79)

**Comment by kengwang** [comment]
目前存在的音质 ID 为:

* `standard` => 标准 (128kbps)
* `higher` => 较高
* `exhigh` =>极高 (HQ) (近CD品质的细节体验，最高320kbps)
* `lossless` =>无损 (SQ) (高保真无损音质，最高48kHz/16bit)
* `hires` =>高解析度无损 (Hi-Res) (更饱满清晰的高解析度音质，最高192kHz/24bit)
* `jyeffect` => 高清环绕声 (Spatial Audio)  (环绕声体验，声音听感增强，96kHz/24bit)
* `sky` => 沉浸环绕声 (Surround Audio) (沉浸式体验，最高5.1声道) (**需传入 `immerseType` = `c51`**)
* `jymaster` => 超清母带 (Master) (还原音频细节，192kHz/24bit) (**需传入 `immerseType` = `c51`**)

**Comment by kengwang** [comment]
需使用 v1 接口
