### ISSUE TITLE
二维码登录失效

### ISSUE THREAD

**Issue by jhwe1** [Binaryify/NeteaseCloudMusicApi#1748]
## 环境
- 系统/平台: win11

- nodejs 版本:  v18.15.0.

- API版本: 4.8.10

## 出现问题
二维码验证在未扫码、扫码待确认状态下正常，手机确认登录后，二维码验证报错502，返回内容：Upstream headers size too big, check your upstream.

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/121280865/d171a417-8795-4b5e-b5a8-a9d1c0d1184d)

## 重现步骤
使用文档demo的二维码登录，进行网易云音乐app扫码登录

## 期待效果
在确认登录后正常返回登录用户信息和cookie等数据

**Comment by Binaryify** [comment]
这是你nginx设置的问题吧

**Comment by jhwe1** [comment]
> 这是你nginx设置的问题吧

我是根据readme上面的方法  用腾讯云 serverless 部署的

**Comment by jhwe1** [comment]
> > 这是你nginx设置的问题吧
> 
> 我是根据readme上面的方法 用腾讯云 serverless 部署的

试了一下，在本地运行的就可以正常登录了

**Comment by Binaryify** [comment]
拉下最新代码，qr/check 接口需要带上noCookie参数
