### ISSUE TITLE
已登录状态 请求歌曲仍然返回30s试听

### ISSUE THREAD

**Issue by Iolop** [Binaryify/NeteaseCloudMusicApi#1750]
## 环境
- 系统/平台: 
Ubuntu
- nodejs 版本: 
v20.1.0
- API版本: 
4.8.10
## 出现问题
登录状态下，通过python request模块请求播放链接，仍然返回30s试听片段（处处吻-杨千嬅），但是如果是网页手动请求，却返回完整歌曲。
## 重现步骤
python request请求抓包
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/11701126/8e2414c5-f750-471a-9025-569047f34991)

```html
GET /song/url/v1?id=316429&level=higher&timestamp=1684850732.3930607 HTTP/1.1
Host: 101.35.196.187:12444
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Connection: close
Cache-Control: max-age=0
DNT: 1
Upgrade-Insecure-Requests: 1
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With,Content-Type
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Content-Type: application/json; charset=utf-8
Set-Cookie: NMTID=00OrtTUtHU7dlSfHkbvrrfhNObBk_sAAAGISO3t8w; Max-Age=315360000; Expires=Fri, 20 May 2033 14:05:32 GMT; Path=/;
Content-Length: 722
ETag: W/"2d2-BgL7k+H7ZEL6W6dQMFaZj1XCmCQ"
cache-control: max-age=120
Date: Tue, 23 May 2023 14:05:32 GMT
Connection: close

{"data":[{"id":316429,"url":"http://m702.music.126.net/20230523223032/3b85e5350b284f41243fa53b3086c132/jd-musicrep-ts/3c91/10aa/30ae/273942c917210deae2a325eaa22b954a.mp3","br":320012,"size":1202721,"md5":"273942c917210deae2a325eaa22b954a","code":200,"expi":1200,"type":"MP3","gain":2,"peak":0,"fee":1,"uf":null,"payed":0,"flag":197892,"canExtend":false,"freeTrialInfo":{"start":0,"end":30},"level":"exhigh","encodeType":"mp3","freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":5,"cannotListenReason":1},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":30040}],"code":200}
```

浏览器请求：
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/11701126/f3408c82-d0dc-47f6-94ff-a859608ff54f)
```html
GET /song/url/v1?id=316429&level=standard HTTP/1.1
Host: 101.35.196.187:12444
Connection: keep-alive
Cache-Control: max-age=0
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: __csrf=49443cccaad2a8b9358fd59ef384a9e1; MUSIC_U=00DB4B3C96035A6C7D9FB0DB247A7BA0D6C42D20546680BAC5BA5E3D40B7E6D5B06B8B2E03FAB09584488DE0A96683852928E97141E65EEA7A8B7E50870C779344E7947368514F467041B40807CD226FC253C3C7425D9206902F403850B36F4E344C7983EEF2AA199FD16DD245C811F4E61938D524A1AAC88223B4CEDF8448764DEA0DCAB67A61D6FBFEDD5F68904DBD98295A4D664A3668EA2215478730B9169F7FE3505F4CD0257343BF9FCE9E9E907BCAAE1C158AD908245533F7052AD513B94786EF530023CE9B8B41224FB65FE3BEB4E9E02E11F209C31D1C876069E863D00766A5792C26C305CE861E56D7E05C3C0FB328E7C1A134F39245BDC5721B1A31F50B5E7438D85528226F0C32CF5CF9432C2832AD6299BDA84864B4C2219457AA420FB67E44FED94773656449489173483086BD928E66C595FDCF5668BEDADBD4052F642655195663BB7AF96843EC3473C7C03176DC2A4FA6C30603697853097EC8FCFCBEC066160A3358A7F62BC01266BCC9412AA19CD008E5AC81CC1C605D2DA7A14B8297B765A597567FAECE74DA3B; NMTID=00O4GlUg8wNcqfe60MsiZlkY3cmpOAAAAGISO7uMQ
If-None-Match: W/"2d2-m4JCottyL6692wiz9+yV6xpRW/E"

HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With,Content-Type
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Content-Type: application/json; charset=utf-8
Set-Cookie: NMTID=00OD4Mm5wS21WRdmUxdtkdnHQuHJIsAAAGISPJzLw; Max-Age=315360000; Expires=Fri, 20 May 2033 14:10:28 GMT; Path=/;
Content-Length: 751
ETag: W/"2ef-VSbt8vBGpOjugEOf2j3jeTwFRvI"
cache-control: max-age=120
Date: Tue, 23 May 2023 14:10:28 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"data":[{"id":316429,"url":"http://m801.music.126.net/20230523223528/788e60b83661bd56d0b271104610ae5c/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/17184483691/c3a6/19ae/1cbd/f6faacf8b25fca076231f6a5889b9baf.mp3","br":128002,"size":3185728,"md5":"f6faacf8b25fca076231f6a5889b9baf","code":200,"expi":1200,"type":"mp3","gain":-8.671,"peak":1,"fee":1,"uf":null,"payed":1,"flag":196868,"canExtend":false,"freeTrialInfo":null,"level":"standard","encodeType":"mp3","freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":199041}],"code":200}
```
## 期待效果
登录状态能正常返回完整歌曲链接

**Comment by jiangxiaohuai520** [comment]
老哥解决了吗，我也有这种问题

**Comment by Iolop** [comment]
> 

没有，抓包看到网页直接访问部署的服务，会携带上一个cookie 不知道怎么生成的。后面没管这个了

**Comment by iamPorter** [comment]
> 没有，抓包看到网页直接访问部署的服务，会携带上一个cookie 不知道怎么生成的。

网页发送请求确实是会附带cookies，API跟网易云会依靠cookies指示浏览器内账号的登录状态。
只需同时用两个浏览器（例如Chrome和Chrome 测试版）就可以看见Cookies对收到的回复的区别。

**Comment by agengen1** [comment]
请求时带上时间戳，试试

**Comment by Iolop** [comment]
> 请求时带上时间戳，试试

之前看过文档，也试过。依然是回复试听片段。

**Comment by Iolop** [comment]
> 

我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的

**Comment by agengen1** [comment]
> > 
> 
> 我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的

python 请求携带cookie没有

**Comment by Iolop** [comment]
> 
python按理说是不需要携带cookie的。我在使用之前，已经在web入口通过扫码登录了，运行的app.js内部应该是有我的登录信息的。我只是通过一个它提供的接口来访问，为什么要携带cookie呢，其实这里我觉得有点怪，感觉像是python请求没有携带cookie导致了后续的访问都没有用上我的登录信息一样，一直返回30s试听，后面这个问题我就没研究，放置了。

**Comment by Iolop** [comment]
> > > 
> > 
> > 
> > 我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的
> 
> python 请求携带cookie没有

> 
python按理说是不需要携带cookie的。我在使用之前，已经在web入口通过扫码登录了，运行的app.js内部应该是有我的登录信息的。我只是通过一个它提供的接口来访问，为什么要携带cookie呢，其实这里我觉得有点怪，感觉像是python请求没有携带cookie导致了后续的访问都没有用上我的登录信息一样，一直返回30s试听，后面这个问题我就没研究，放置了。

**Comment by agengen1** [comment]
> > > > 
> > > 
> > > 
> > > 我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的
> > 
> > 
> > python 请求携带cookie没有
> 
> > 
> 
> python按理说是不需要携带cookie的。我在使用之前，已经在web入口通过扫码登录了，运行的app.js内部应该是有我的登录信息的。我只是通过一个它提供的接口来访问，为什么要携带cookie呢，其实这里我觉得有点怪，感觉像是python请求没有携带cookie导致了后续的访问都没有用上我的登录信息一样，一直返回30s试听，后面这个问题我就没研究，放置了。

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/111271544/c36e7f62-ec82-4b91-87d7-74009f9e1e3a)
登录后服务器把cookie都设置好了，下次发请求会自动携带这个请求，所以你在python请求的时候要带上cookie，我是这样理解的

**Comment by Iolop** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的
> > > 
> > > 
> > > python 请求携带cookie没有
> > 
> > 
> > > 
> > 
> > 
> > python按理说是不需要携带cookie的。我在使用之前，已经在web入口通过扫码登录了，运行的app.js内部应该是有我的登录信息的。我只是通过一个它提供的接口来访问，为什么要携带cookie呢，其实这里我觉得有点怪，感觉像是python请求没有携带cookie导致了后续的访问都没有用上我的登录信息一样，一直返回30s试听，后面这个问题我就没研究，放置了。
> 
> ![image](https://user-images.githubusercontent.com/111271544/251962932-c36e7f62-ec82-4b91-87d7-74009f9e1e3a.png) 登录后服务器把cookie都设置好了，下次发请求会自动携带这个cookie，所以你在python请求的时候要带上cookie，我是这样理解的

哦，这么说起来。确实可以这么理解，他的内部不会直接保存我的登录cookie并且帮我自动携带转发，反而需要我本人来保留并且后续携带。我的理解有误，刚才试了试，确实是这样，抓取qrlonging.html的过程，后续主动携带 csrf MUSIC_U NMTID 三个cookie的时候，正常的返回了完整片段。

**Comment by agengen1** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我登录了我的vip账号，python请求依然返回30s试听。但是web访问就是正常的
> > > > 
> > > > 
> > > > python 请求携带cookie没有
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > python按理说是不需要携带cookie的。我在使用之前，已经在web入口通过扫码登录了，运行的app.js内部应该是有我的登录信息的。我只是通过一个它提供的接口来访问，为什么要携带cookie呢，其实这里我觉得有点怪，感觉像是python请求没有携带cookie导致了后续的访问都没有用上我的登录信息一样，一直返回30s试听，后面这个问题我就没研究，放置了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/111271544/251962932-c36e7f62-ec82-4b91-87d7-74009f9e1e3a.png) 登录后服务器把cookie都设置好了，下次发请求会自动携带这个cookie，所以你在python请求的时候要带上cookie，我是这样理解的
> 
> 哦，这么说起来。确实可以这么理解，他的内部不会直接保存我的登录cookie并且帮我自动携带转发，反而需要我本人来保留并且后续携带。我的理解有误，刚才试了试，确实是这样，抓取qrlonging.html的过程，后续主动携带 csrf MUSIC_U NMTID 三个cookie的时候，正常的返回了完整片段。


ok呀，问题解决了就行
