### ISSUE TITLE
已经扫描了二维码,并在手机上进行了登录, 但是通过/login/qr/check进行查询时,始终返回801(等待登录的代码)

### ISSUE THREAD

**Issue by Tmaof** [Binaryify/NeteaseCloudMusicApi#1753]
## 环境
- 系统/平台: <你的系统和平台>
- linux/windows 都这样

- nodejs 版本: <你的 NodeJS 版本号>
- 16

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
- 4.8.11

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>
二维码登录问题,
已经扫描了二维码,并在手机上进行了登录,
但是通过/login/qr/check进行查询时,始终返回801(等待登录的代码)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
用接口测试工具测试一下就知道了:
/login/qr/key
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/8064e95f-40b5-4f73-8195-abb46f3dbf44)

/login/qr/create
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/5fcb23be-7299-409c-a98b-5eab0cb0bb4c)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/f562fdfb-d5d3-49a0-a18a-a752dcf612ba)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/2869bd49-1f16-4e73-8099-90b3dfebe616)
已经登录成功
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/792677f9-ff52-4518-8b45-0ab02f4d5d9c)

/login/qr/check
但还是返回等待扫码
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/b9320aaa-c4a4-46f4-a9e7-9c18e175c987)

## 期待效果
<请清晰描述现在的效果和期待的效果>  
扫描了二维码并进行了登录,再次查询时应该返回803代码和cookie

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Tmaof** [comment]
我又尝试添加时间戳,但并不起作用
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/b4c50f3a-5900-49ee-a1d4-0cee59882a24)

**Comment by Binaryify** [comment]
文档里写的例子跑了吗

**Comment by Tmaof** [comment]
问题已经解决,
感谢作者,
需要注意的问如下:
1. 需要带上时间戳
2. 查询时间间隔需要大于等于3000ms
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/9d1044d9-258e-427f-b9f1-092cc8232181)

3. 登录成功后需要使用 `/login/status` 的 `post` 请求并携带cookie如下,(我使用其他接口比如, `/user/account` 返回的始终是被缓存的结果)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/102353901/368dbbcb-9287-438e-8e5a-ed9df59efbe6)

**Comment by siyesummer** [comment]
> 问题已经解决, 感谢作者, 需要注意的问如下:
> 
> 1. 需要带上时间戳
> 2. 查询时间间隔需要大于等于3000ms
>    ![image](https://user-images.githubusercontent.com/102353901/243234993-9d1044d9-258e-427f-b9f1-092cc8232181.png)
> 3. 登录成功后需要使用 `/login/status` 的 `post` 请求并携带cookie如下,(我使用其他接口比如, `/user/account` 返回的始终是被缓存的结果)
>    ![image](https://user-images.githubusercontent.com/102353901/243235256-368dbbcb-9287-438e-8e5a-ed9df59efbe6.png)

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/22517072/f4bec094-1b03-42d8-b51d-b69534786f32)
这个参数实在哪里看到的啊，我在文档里都没看见
