### ISSUE TITLE
/song/url 返回的歌曲链接是试听片段

### ISSUE THREAD

**Issue by student-ice** [Binaryify/NeteaseCloudMusicApi#1756]
使用二维码登录后，
 调用/song/url 获取音乐url，返回的是试听片段
 账号是有会员的

**Comment by Iolop** [comment]
> 使用二维码登录后， 调用/song/url 获取音乐url，返回的是试听片段 账号是有会员的

[这个issue](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1750#issuecomment-1626971450) 希望能帮到你
