### ISSUE TITLE
二维码登录的不能刷新cookie吗？

### ISSUE THREAD

**Issue by student-ice** [Binaryify/NeteaseCloudMusicApi#1757]
我上午登录之后，可以正常播放vip歌曲，

下午再启动程序，就是30s试听了，用户信息啥的都可以正常获取到

**Comment by agengen1** [comment]
加时间戳，试试

**Comment by agengen1** [comment]
> 我上午登录之后，可以正常播放vip歌曲，
> 
> 下午再启动程序，就是30s试听了，用户信息啥的都可以正常获取到

看文档是有两分钟缓存，登录的时候带时间戳，如果还是不行我也就不清楚了

**Comment by Jquil** [comment]
> 我上午登录之后，可以正常播放vip歌曲，
> 
> 下午再启动程序，就是30s试听了，用户信息啥的都可以正常获取到

解决了吗，
