### ISSUE TITLE
增加获取”听歌排行“中次数的功能

### ISSUE THREAD

**Issue by Seattle-233** [Binaryify/NeteaseCloudMusicApi#1759]
**增加获取”听歌排行“中次数的功能**
- 使用网易云官方网站时，在未登录状态下，页面上是无法获取到具体的听歌次数的，如下图：
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/68848646/db45636d-a1b1-4653-8f14-c848c2fb41f9)
登陆后可以看到以下状态：
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/68848646/0f032555-adb4-4f6b-b883-bcf96124704f)

**Comment by Binaryify** [comment]
/user/record 接口
