### ISSUE TITLE
未登录使用搜索功能时返回 400 错误

### ISSUE THREAD

**Issue by mantou132** [Binaryify/NeteaseCloudMusicApi#1777]
## 环境
- 系统/平台: docker
- 版本: v4.9.0

## 出现问题
未登录使用搜索功能时返回 400 错误，内容是：

```
{"code":-462,"data":{"actionCode":null,"verifyType":40,"verifyId":1007602,"verifyUrl":"https://st.music.163.com/encrypt-pages","blockText":"验证成功后，可进行下一步操作哦~","verifyToken":"00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","btnText":"","orpheusUrl":"","frontRuleIds":null,"params":{"event_id":"00392594787784794127","sign":"e3c0bb8fa6e6a5991755471c9a8d2ab1"},"url":"https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%22e3c0bb8fa6e6a5991755471c9a8d2ab1%22%2C%22event_id%22%3A%2200392594787784794127%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","urlAutoOpen":0,"orpheusUrlParamAppend":null},"message":"请完成验证操作"}
```

## 重现步骤
1. 依据文档启用 docker 服务
2. 访问 `/search?keywords=海阔天空`

## 期待效果
正常返回内容

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
升级到 v4.10.0 看看
