### ISSUE TITLE
有关 api 当中的一些问题

### ISSUE THREAD

**Issue by XGHeaven** [Binaryify/NeteaseCloudMusicApi#178]
- [ ] top_list.js 测试发现 limit/offset 无效，total 似乎也没有效果
- [ ] top_playlist_highquality.js 获取高品质清单的 offset 没有效果
- [ ] top_songs.js 这个文档里面没有，不知道干什么用的。而且里面的 limit/offset/area 参数都没有用处

**Comment by Binaryify** [comment]
top_list 没有分页数据不过数据有缺失,现在把 limit/offset去掉了,然后把 n 设置成 10000 了
top_playlist_highquality 确实不知道为什么 offset 没用,但是是原原本本传给官方接口的
top_songs 这个暂时废弃了

**Comment by XGHeaven** [comment]
哦，还有一个就是我测试相似相关的接口，似乎里面所有的 offset/limit 都没有用😂

**Comment by Binaryify** [comment]
反正返回内容不带 more:true 的都是没分页数据的

**Comment by XGHeaven** [comment]
soga，那我看了一下，都没有😂 simi_{mv|song|playlist|user|artist}.js

**Comment by Binaryify** [comment]
嗯,刚都去掉了

**Comment by XGHeaven** [comment]
OK
