### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by student-ice** [Binaryify/NeteaseCloudMusicApi#1784]
## 出现问题
文档中歌曲详情接口返回字段说明中提到：
`noCopyrightRcmd: Option<NoCopyrightRcmd>, None表示可以播，非空表示无版权`
实际歌曲有无版权这个都是Null
无法通过这个字段的值判断出歌曲有无版权

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/59855569/a5745dc7-5378-460b-b041-b78112d95d56)

**Comment by Binaryify** [comment]
好的好的,一会我改下
