### ISSUE TITLE
无法获取歌手的全部单曲，好像只有热门50个

### ISSUE THREAD

**Issue by hhshfh** [Binaryify/NeteaseCloudMusicApi#179]
### 环境
系统:  win95

nodejs 版本:7.x

### 期待效果

**Comment by Binaryify** [comment]
那个接口是文档描述错误
对应的是这里
![image](https://user-images.githubusercontent.com/12221718/35202509-186c16a0-ff5e-11e7-95c5-562edf75a14d.png)
需要这两个接口获取数据
![image](https://user-images.githubusercontent.com/12221718/35202532-3c6c00d8-ff5e-11e7-9680-73dacdd1acc6.png)

**Comment by hhshfh** [comment]
@Binaryify 意思就是这两个一起用，才能拿到全部单曲是嘛？

**Comment by Binaryify** [comment]
是的
