### ISSUE TITLE
docker run 错误：Cannot find module './generateConfig'

### ISSUE THREAD

**Issue by lxg20082008** [Binaryify/NeteaseCloudMusicApi#1791]
## 环境
- 系统/平台: Linux raspberrypi 6.1.21-v8+

- nodejs 版本: v12.22.12

- API版本: 4.10.1

## 出现问题
`docker run docker run -d -p 3000:3000 --name netease_cloud_music_api    binaryify/netease_cloud_music_api`出现如下错误：
_node:internal/modules/cjs/loader:1080

  throw err;
  ^
Error: Cannot find module './generateConfig'
Require stack:
- /app/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/app/app.js:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/app.js' ]
}
Node.js v18.17.1_

## 重现步骤
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/61457095/27c126df-dcf9-40f5-ad85-c619bf138b44)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/61457095/7faafbf2-7f50-4dbe-8b8d-9e3d73a0006a)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/61457095/d14ec84c-f7ce-43ec-a642-1ef1df96cb52)

## 期待效果
解决在docker中使用项目

**Comment by caideone** [comment]
> ## 环境
> * 系统/平台: Linux 树莓派 6.1.21-v8+
> * Nodejs 版本：v12.22.12
> * API版本：4.10.1
> 
> ## 出现问题
> `docker run docker run -d -p 3000:3000 --name netease_cloud_music_api binaryify/netease_cloud_music_api`出现如下错误： _node:internal/modules/cjs/loader:1080 � throw err; ^ 错误：找不到模块“./generateConfig” 需要堆栈：
> 
> * /app/app.js
>   位于 Module._resolveFilename (节点:internal/modules/cjs/loader:1077:15)
>   位于 Module._load (节点:internal/modules/cjs/loader:922:27)
>   位于 Module.require (节点) :internal/modules/cjs/loader:1143:19)
>   在 require (node:internal/modules/cjs/helpers:121:18)
>   在 Object. (/app/app.js:2:24)
>   在 Module._compile (节点:internal/modules/cjs/loader:1256:14)
>   在 Module._extensions..js (节点:internal/modules/cjs/loader:1310 :10)
>   在 Module.load (node:internal/modules/cjs/loader:1119:32)
>   处。_
>   在 Function.executeUserEntryPoint [as runMain]__加载 (node:internal/modules/cjs/loader:960:12) (node:internal/modules/run_main:81:12) { 
>   code: 'MODULE_NOT_FOUND', 
>   requireStack: [ '/app /app.js']
>   Node.js 
>   v18.17.1_
> 
> ## 重置步骤
> ![图像](https://user-images.githubusercontent.com/61457095/265215790-27c126df-dcf9-40f5-ad85-c619bf138b44.png) ![图像](https://user-images.githubusercontent.com/61457095/265215867-7faafbf2-7f50-4dbe-8b8d-9e3d73a0006a.png) ![图像](https://user-images.githubusercontent.com/61457095/265215829-d14ec84c-f7ce-43ec-a642-1ef1df96cb52.png)
> 
> ## 预期效果
> 我也遇到相同的问题，你有没有解决

**Comment by lxg20082008** [comment]
没有呢，好像遇到这种情况的不多

**Comment by Binaryify** [comment]
已修复
