### ISSUE TITLE
/song/url 批量获取音乐url的时候,返回的url顺序和传入的id顺序不一致

### ISSUE THREAD

**Issue by student-ice** [Binaryify/NeteaseCloudMusicApi#1792]
例如：使用/song/url?id=33894312,2079350542,2077882779,2079429416
返回的数据中，顺序是随机的,
"data": [
        {
            "id": 2079429416,
            "url": "http://m801.music.126.net/20230905181125/fbb6d131aa449b72f099d3b373e14581/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/30266630828/7400/5d05/4155/bfd9b287d962892b903de235c46c9def.mp3",
            "br": 128001,
            "size": 4561232,
            "md5": "bfd9b287d962892b903de235c46c9def",
            "code": 200,
            "expi": 1200,
            "type": "mp3",
            "gain": -8.7207,
            "peak": 1,
            "fee": 8,
            "uf": null,
            "payed": 0,
            "flag": 1081604,
            "canExtend": false,
            "freeTrialInfo": null,
            "level": "standard",
            "encodeType": "mp3",
            "freeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "listenType": null,
                "cannotListenReason": null
            },
            "freeTimeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "type": 0,
                "remainTime": 0
            },
            "urlSource": 0,
            "rightSource": 0,
            "podcastCtrp": null,
            "effectTypes": null,
            "time": 285000
        },
        {
            "id": 2077882779,
            "url": "http://m801.music.126.net/20230905181125/3003ce250a9933e203987dd1582264ea/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/30177900507/31c6/97f8/1062/92b31d87cc754235a8996ee610e4e870.mp3",
            "br": 128000,
            "size": 3322819,
            "md5": "92b31d87cc754235a8996ee610e4e870",
            "code": 200,
            "expi": 1200,
            "type": "mp3",
            "gain": -7.6886,
            "peak": 1,
            "fee": 8,
            "uf": null,
            "payed": 0,
            "flag": 1556740,
            "canExtend": false,
            "freeTrialInfo": null,
            "level": "standard",
            "encodeType": "mp3",
            "freeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "listenType": null,
                "cannotListenReason": null
            },
            "freeTimeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "type": 0,
                "remainTime": 0
            },
            "urlSource": 0,
            "rightSource": 0,
            "podcastCtrp": null,
            "effectTypes": null,
            "time": 207611
        },
        {
            "id": 33894312,
            "url": "http://m7.music.126.net/20230905181125/7c663680c0de94cd78676797b9a4c3eb/ymusic/0fd6/4f65/43ed/a8772889f38dfcb91c04da915b301617.mp3",
            "br": 320000,
            "size": 10691439,
            "md5": "a8772889f38dfcb91c04da915b301617",
            "code": 200,
            "expi": 1200,
            "type": "mp3",
            "gain": -6.3072,
            "peak": 1,
            "fee": 0,
            "uf": null,
            "payed": 0,
            "flag": 1081473,
            "canExtend": false,
            "freeTrialInfo": null,
            "level": "exhigh",
            "encodeType": "mp3",
            "freeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "listenType": null,
                "cannotListenReason": null
            },
            "freeTimeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "type": 0,
                "remainTime": 0
            },
            "urlSource": 0,
            "rightSource": 0,
            "podcastCtrp": null,
            "effectTypes": null,
            "time": 267232
        },
        {
            "id": 2079350542,
            "url": "http://m701.music.126.net/20230905181125/50b90e216e2bd32eec6fabf2fd43c58c/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/30262576419/0164/e324/9b6d/32afc904224270db4552f389a9269edc.mp3",
            "br": 128000,
            "size": 3373869,
            "md5": "32afc904224270db4552f389a9269edc",
            "code": 200,
            "expi": 1200,
            "type": "mp3",
            "gain": -9.2771,
            "peak": 1,
            "fee": 8,
            "uf": null,
            "payed": 0,
            "flag": 1544196,
            "canExtend": false,
            "freeTrialInfo": null,
            "level": "standard",
            "encodeType": "mp3",
            "freeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "listenType": null,
                "cannotListenReason": null
            },
            "freeTimeTrialPrivilege": {
                "resConsumable": false,
                "userConsumable": false,
                "type": 0,
                "remainTime": 0
            },
            "urlSource": 0,
            "rightSource": 0,
            "podcastCtrp": null,
            "effectTypes": null,
            "time": 210800
        }
    ]

**Comment by student-ice** [comment]
> 网易那边的问题,一个个调吧

这个要修的吗？，我现在还得自己把返回的数据重新排一下

**Comment by Binaryify** [comment]
新版本处理了

**Comment by student-ice** [comment]
> 新版本处理了

我今天拉了新版代码，出现了新的问题
二维码登录后，调用`/mv/sublist` `/artist/sublist`这几个接口获取的数据是空的(请求的时候正确设置了cookie)
只能先回退到4.8.11版本了

**Comment by Binaryify** [comment]
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/12221718/df8858e8-9ee1-493d-b747-d3ee0285d272)
没法复现

**Comment by student-ice** [comment]
```
if (!m_cookie.isEmpty()) {
        QStringList cookieList = m_cookie.split(';');
        foreach (QString cookieItem, cookieList) {
            cookieItem = cookieItem.trimmed();
            QList<QString> parts = cookieItem.split('=');
            if (parts.length() == 2) {
                QByteArray name = parts[0].trimmed().toUtf8();
                QByteArray value = parts[1].trimmed().toUtf8();
                if (name == "MUSIC_U") {
                    QNetworkCookie cookie(name, value);
                    m_request_cookies.append(cookie);
                }
            }
        }
    }
```

这是我设置cookie的方法，只设置MUSIC_U的值，请求的时候像下面这样带上

```
QNetworkRequest request;
    request.setUrl(QUrl(BASE_URL + api));
    if (!m_cookie.isEmpty()
        && (api.startsWith("/song/url") || api.startsWith("/user/playlist")
            || api.startsWith("/playlist/track/all") || api.startsWith("/digitalAlbum/purchased")
            || api.startsWith("/artist/sublist") || api.startsWith("/mv/sublist")
            || api.startsWith("/like"))) {
        // 设置请求头的Cookie值
        request.setHeader(QNetworkRequest::CookieHeader, QVariant::fromValue(m_request_cookies));
    }

    manager->get(request);
```
新版本是不是只设置MUSIC_U无效了？ @Binaryify

**Comment by student-ice** [comment]
@Binaryify 定位到了
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/8913131739700cb1a6801394415b158fc80303e4
就是这笔提交导致我出现这样的问题，在浏览器和postman里请求没问题，在qt客户端请求就返回空数据（正确携带了cookie)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/59855569/df41ef96-9183-4f3b-96f8-9f554395a870)
目前只发现这三个接口有这样的问题

**Comment by Binaryify** [comment]
重新拉下代码看看

**Comment by student-ice** [comment]
> 重新拉下代码看看

可以了，很奇怪，不知道为什么客户端会有这个问题，浏览器中就没有
