### ISSUE TITLE
通过nickname查询用户详情信息

### ISSUE THREAD

**Issue by agengen1** [Binaryify/NeteaseCloudMusicApi#1794]
**功能描述**
- 请清晰描述你所希望添加的功能，最好贴上对应客户端界面的截图
通过nickname查询用户详情信息
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/111271544/f5079073-978d-4996-b764-9a867c44cb47)
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/111271544/25b8d5db-ac2e-423e-8364-fa683e021ced)

 主要用于动态中 "@xxx" 跳转
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/111271544/d2f15485-695f-4eaf-9f18-3da37812a8de)

**Comment by Binaryify** [comment]
用userid,网页版的userid也是服务端渲染后注入的
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/12221718/4897cb39-4ef3-4d1c-a707-2b962d895488)

**Comment by agengen1** [comment]
@Binaryify 
这个动态  /event  接口返回的数据中没有包含@xxxx 的用户id
我看网易云的网页版是通过nickname查询的用户信息详情

**Comment by Binaryify** [comment]
https://music.163.com/user/event?nickname=xxx吗
这个是页面,服务端渲染的时候注入的userid,然后接口用userid获取的数据的
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/12221718/a8c66f8b-9267-49d2-94c5-874b3a67817a)

**Comment by agengen1** [comment]
> [https://music.163.com/user/event?nickname=xxx吗](https://music.163.com/user/event?nickname=xxx%E5%90%97) 这个是页面,服务端渲染的时候注入的userid,然后接口用userid获取的数据的 ![image](https://user-images.githubusercontent.com/12221718/266758578-a8c66f8b-9267-49d2-94c5-874b3a67817a.png)

@Binaryify 明白了，谢谢

**Comment by agengen1** [comment]
> [https://music.163.com/user/event?nickname=xxx吗](https://music.163.com/user/event?nickname=xxx%E5%90%97) 这个是页面,服务端渲染的时候注入的userid,然后接口用userid获取的数据的 ![image](https://user-images.githubusercontent.com/12221718/266758578-a8c66f8b-9267-49d2-94c5-874b3a67817a.png)

@Binaryify 你这个测试不要用自己的nickname测试，

**Comment by agengen1** [comment]
> > [https://music.163.com/user/event?nickname=xxx吗](https://music.163.com/user/event?nickname=xxx%E5%90%97) 这个是页面,服务端渲染的时候注入的userid,然后接口用userid获取的数据的 ![image](https://user-images.githubusercontent.com/12221718/266758578-a8c66f8b-9267-49d2-94c5-874b3a67817a.png)
> 
> @Binaryify 你这个测试不要用自己的nickname测试，

我想获取的是这个id
![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/111271544/9b95c1a5-a05b-4b8c-8a9a-0b75161ea3f2)

**Comment by Binaryify** [comment]
新接口加上了

**Comment by agengen1** [comment]
> 新接口加上了

好的👌🏻
