### ISSUE TITLE
关于增加新接口的建议

### ISSUE THREAD

**Issue by zhixuanziben** [Binaryify/NeteaseCloudMusicApi#18]
1.mv的接口可不可以搞得到？
2.歌手排行榜能不能搞到？

**Comment by Binaryify** [comment]
刚看到，歌手排行榜已经加了，mv吃完饭加

**Comment by Binaryify** [comment]
网易给 mv 做了防盗链处理,我得想办法处理下

**Comment by rccoder** [comment]
@Binaryify 可以下载图片传到新浪图床上

**Comment by Binaryify** [comment]
@rccoder 
倒不是图片的问题,是 mv 视频加了防盗链

**Comment by zhixuanziben** [comment]
反馈： 新碟上架获得的数据中，没有有关歌曲的信息，比如歌曲名字，url等，只有专辑的一些信息

**Comment by Binaryify** [comment]
@zhixuanziben 
容我研究下

**Comment by Binaryify** [comment]
@zhixuanziben 
找到了,再调一次 /album 接口就行

**Comment by Binaryify** [comment]
@zhixuanziben 
MV 接口已加上

**Comment by zhixuanziben** [comment]
刚刚看到，谢谢大哥！不过没看到获取mv id的接口？

**Comment by Binaryify** [comment]
@zhixuanziben 
mvid 是搜歌的时候才能看到的

**Comment by zhixuanziben** [comment]
没有办法搞到推荐mv的列表吗

**Comment by Binaryify** [comment]
@zhixuanziben 
刚看到网页版的云音乐有 mv 列表接口,不过得分析下

**Comment by Binaryify** [comment]
@zhixuanziben 
找到了,搜索 type=1004

**Comment by zhixuanziben** [comment]
好的，热门搜索能搞到吗

**Comment by Binaryify** [comment]
@zhixuanziben 
这个应该就不行了
