### ISSUE TITLE
Workflow for Building Docker Image is Broken

### ISSUE THREAD

**Issue by WooMai** [Binaryify/NeteaseCloudMusicApi#1817]
v4.13 以来的镜像构建 workflow 均未成功运行

https://github.com/Binaryify/NeteaseCloudMusicApi/actions/workflows/Build_Image.yml

Docker Hub 目前最新版本停滞在 4.12.2

https://hub.docker.com/r/binaryify/netease_cloud_music_api

**Comment by Binaryify** [comment]
好了
