### ISSUE TITLE
运行 public/test.html 测试登陆时 报错

### ISSUE THREAD

**Issue by Lionad-Morotar** [Binaryify/NeteaseCloudMusicApi#182]
![Uploading 1125_2.gif…]()

![Uploading 20180124_235722.png…]()
### 环境
系统:  Win10

nodejs 版本: V7.10.0

### 出现问题
运行 public/test.html 测试登陆时 报错

控制台:
![image](https://user-images.githubusercontent.com/26913795/35342031-02b87140-0162-11e8-96dc-2763516f7e44.png)

浏览器:
![image](https://user-images.githubusercontent.com/26913795/35341844-97583b9c-0161-11e8-9d0a-3f7a66b6db55.png)

### 重现步骤
1. nodemon app.js
2. 浏览器运行 public/test.html 

3. 控制台报错, 浏览器无返回值

### 期待效果
...

**Comment by Binaryify** [comment]
ajax 不能在 file 协议下用
