### ISSUE TITLE
登出后，使用扫码登录切换账户时疑似可用乙账号登录原先的甲账号？

### ISSUE THREAD

**Issue by iamPorter** [Binaryify/NeteaseCloudMusicApi#1833]
## 环境
- 系统/平台: Windows 10 22H2

- nodejs 版本: 9.8.0

- API版本: <4.13.3>

## 出现问题
在使用`localhost/logout`登出账号并且收到回复HTTP:200后，此时如果直接使用程序自带`index.html`的“二维码登录”按钮（也就是从`/qrlogin.html`界面）登录账号，QR界面的文字会显示上一个用户的UID。此时即使是另一个用户扫码登录了，最终浏览器查到的用户信息依旧是上一个用户的，请求其他信息也是如此。然而，在登出期间，查询用户信息是回复未登录的。其它方法登录疑似不会出现类似问题。

## 重现步骤
上一节已说明。重截图涉及某些信息及麻烦，除非万不得已恕不提供。

## 期待效果
登出后，再直接使用二维码登录可以不登录到上一个用户上面。

---
# 附：
- 出错的时候浏览器运行了AdGuard，不过看起来AdGuard不可能拦截登录信息
- 检测的另一方法是验证码登录，此方法可以登录到新的账号
- 这次我使用的是源码直接操作，此前在使用第三方程序时，它使用了一个自己的登录令牌，这样该程序似乎会通过该系统屏蔽原先Cookies记载的其它方式登录API的账户并直接通过更换令牌退出登录（即使也发送了logout指令）。这样可能可以临时回避问题。

**Comment by Binaryify** [comment]
缓存问题,重新拉下代码看看
