### ISSUE TITLE
`/utils/crypto.js` 浏览器平台改写

### ISSUE THREAD

**Issue by 2061360308** [Binaryify/NeteaseCloudMusicApi#1839]
## 环境
- 系统/平台: windows

- nodejs 版本: v18.18.0

- API版本: 4.13.8

## 出现问题
阅读了  `/utils/crypto.js` 后想将他用浏览器环境下的相关库替换掉node内置的`crypto`

## 重现步骤
其中 `aesEncrypt` 函数已经做到了，但是在处理`rsaEncrypt` 时（实际上具体是`weapi`用到了的`secretKey`不是字符串）的时候发现绕不开`node`内置的`buffer`，而第三方支持的库都要求传入一个字符串值。

我尝试将其使用`Uint8Array`并在加密前使用`new TextDecoder("ascii")`进行编码（尝试过所有的支持编码）都没有成功。

如果可以的话能否额外提示我该如何使用无填充模式，我很难找到一个第三方库支持这种加密方式，我自己尝试修改`jsencrypt.js`的源码将其的填充方法直接注释掉使用`jsbn`转换为大数，但由于`buffer`相关问题没有处理成功，所以也不能确定这个方式是否有效。

## 期待效果
最终目标是将写一个接口中间层让api运行在安卓本地

如果将`/utils/crypto.js`转换为浏览器环境可以执行的代码后，我就可以在 “ 删除掉request中的axios请求方法，和一些其他的不兼容的库“ 后实现在浏览器中就能运行接口并返回相关的请求信息，之后使用其他`android`类工具(如`capacitor`)提供的原生请求方法进行请求，从而让整个api都运行在本地。

> * 感谢您抽空给与我一些帮助 *

**Comment by Binaryify** [comment]
为啥要在浏览器端调用，有跨域问题，而且浏览器端有些header也不能设置，也没法自定义header里的cookie

**Comment by 2061360308** [comment]
> 并不能说是在浏览器里面用，我是想在  ***安卓***  里面用。

## 先说我放弃的方案

1. 安卓原生重写整个项目
2. 找web开发原生app的框架（我用capacitor）模仿本项目用java给他写一个插件
3. 使用capacitor中的NodeJs插件，在其中使用本项目

> 因为我不会Java而方案三的 ***NodeJs***  插件很是不稳定，而且打包apk多20Mb左右很不划算， 所以才有了这个方案。

按我的理解本项目的核心 一是：找到对应的接口地址 二是：破解参数（`params`）的加密过程破解

在我看分析完相关的源码后我发现只要我改写`/utils/crypto.js`这个模块的内容，移除他对`node`的依赖，就能跨平台实现项目的运行

## 我的预计工作流程为：

1. webview 运行改造后的项目返回 请求地址和`params`等的参数。
2. 调用框架提供的原生平台http能力进行请求拿到最终数据。

## 这个方案的具体实施过程为：

1. 改写`/utils/crypto.js`
2. 利用`capacitor`的核心`http插件`（也封装了js）写一个类似本项目`request`的封装，进行请求并暴露类似项目文档中的明确接口
3. 利用`capacitor`使用js继续完成安卓平台其他方面的开发

> 为啥要在浏览器端调用，有跨域问题，而且浏览器端有些header也不能设置，也没法自定义header里的cookie

**Comment by Binaryify** [comment]
明白了，就是不依赖nodejs自带库的方法，我今天试试吧

**Comment by Binaryify** [comment]
好了
