### ISSUE TITLE
能否增加“继续上次播放”

### ISSUE THREAD

**Issue by leanco1** [Binaryify/NeteaseCloudMusicApi#1849]
1.目前使用的问题是：播放过程中如果使用其他途径调用了这个播放器，调用时会停止当前歌曲的播放功能，调用结束后自动切换到了下一曲。
2.能否增加停止播放，使我的播放器回到空闲状态。
3.能否增加“继续上次播放”，当我点击播放按钮时继续上次退出时的状态继续播放。
4.跪谢。

**Comment by Binaryify** [comment]
这是客户端功能和本项目无关

**Comment by leanco1** [comment]
非常感谢
