### ISSUE TITLE
npm test 除了获取歌词成功, 其余都失败了

### ISSUE THREAD

**Issue by Lionad-Morotar** [Binaryify/NeteaseCloudMusicApi#185]
### 环境
系统:  Win10

nodejs 版本: V7.10

### 出现问题
![image](https://user-images.githubusercontent.com/26913795/35435950-86ca703a-02c7-11e8-8409-dc8b70c518c6.png)

### 重现步骤
1. npm install
2. npm test

**Comment by Binaryify** [comment]
你确定不是除了登录都成功了?
