### ISSUE TITLE
/artist/detail 接口登录状态无法获取歌手详情

### ISSUE THREAD

**Issue by imsyy** [Binaryify/NeteaseCloudMusicApi#1853]
## 环境
- 系统/平台: win11

- nodejs 版本: 18.x

- API版本: 4.13.6

## 出现问题

登录状态调用歌手详情会出现 460，传入 noCookie 也无效；未登录状态返回正常，`v4.13.6` 和 `v4.13.8` 均有此问题

## 重现步骤

`/artist/detail` 接口：

> 登录状态

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/42232682/5e5f254b-07ac-4869-9fe5-c2b7254550c6)

> 未登录状态

![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/42232682/1649472e-7790-4aa9-acd3-0ac70eb5716a)

## 期待效果
<请清晰描述现在的效果和期待的效果>  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
拉下新代码看看

**Comment by imsyy** [comment]
ok了，感谢大佬
