### ISSUE TITLE
获取音乐url好像挂掉了

### ISSUE THREAD

**Issue by 422563261** [Binaryify/NeteaseCloudMusicApi#187]
### 环境
系统:  mac

nodejs 版本:

### 出现问题

2018.1.13 15:36
获取音乐详情url均无法播放

### 期待效果

**Comment by Binaryify** [comment]
仔细看文档 https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90-url
>说明 : 使用歌单详情接口后 , 能得到的音乐的 id, 但不能得到的音乐 url, 调用此接口 , 传入的音乐 id( 可多个 , 用逗号隔开 ), 可以获取对应的音乐的 url( 不需要登录 )

**Comment by 422563261** [comment]
现在都只能用http://music.163.com/song/media/outer/url?id=id.mp3播放了吗，还是说原来的原来那个只是不稳定而已？

**Comment by Binaryify** [comment]
@422563261 部分会403

**Comment by 422563261** [comment]
感谢大佬，确实，部分音乐会403.
