### ISSUE TITLE
<用户播放记录周记录，歌曲播放次数playcount都为0，有bug issues>

### ISSUE THREAD

**Issue by huanghuzi639** [Binaryify/NeteaseCloudMusicApi#1870]
## 环境
- 系统/平台: <win11>

- nodejs 版本: <18.18.0>

- API版本: <4.13.8>

## 出现问题
<调用用户播放记录的接口,当type等于歌曲的playcount计数都为0,调用接口:/user/record?uid=32953014&type=1>

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>
调用用户播放记录的接口,type=0是好的,但是type=1调用周数据playcount就都为0
[![image](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/149987735/3b777cfb-4898-49f8-b3e7-01d63b090da7)](http://localhost:3000/user/record?uid=581779643&type=1)http://[localhost:3000/user/record?uid=581779643&type=1](http://localhost:3000/user/record?uid=581779643&type=1)

    "weekData": [
        {
            "playCount": 0,
            "score": 100,
            "song": {
                "name": "屋顶",
                "id": 5257138,
                "pst": 0,
                "t": 0,
                "ar": [
                    {
                        "id": 6452,
                        "name": "周杰伦",
                        "tns": [],
                        "alias": []
                    },
                    {
                        "id": 9612,
                        "name": "温岚",
                        "tns": [],
                        "alias": []
                    }
                ],
## 期待效果
<请清晰描述现在的效果和期待的效果>  
个人听歌记录的周数据playcount播放次数为0有bug希望修复

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by huanghuzi639** [comment]
顶,请大佬帮忙看看

**Comment by Binaryify** [comment]
只能查看自己的周记录播放次数,不能查看别热你的周记录播放次数
