### ISSUE TITLE
获取每日推荐歌曲接口每次只返回四条数据

### ISSUE THREAD

**Issue by melissa-l** [Binaryify/NeteaseCloudMusicApi#188]
### 环境
系统:  
mac
nodejs 版本:
9.2.1
### 出现问题
获取每日推荐歌曲接口每次只返回四条数据
### 重现步骤
登陆后请求:http://localhost:3000/recommend/resource
### 期待效果
返回正常20条数据

**Comment by CinGing** [comment]
/recommend/songs 才是日推20首
resource是歌单

**Comment by nondanee** [comment]
每日推荐歌曲接口是 `/recommend/songs`, 20条数据返回正常
