### ISSUE TITLE
在ubuntu下 开启服务后，不能返回数据

### ISSUE THREAD

**Issue by yangyin** [Binaryify/NeteaseCloudMusicApi#190]
### 环境
系统:  
ubuntu16.04
nodejs 版本:
V8.6.0
### 出现问题
{ Error: connect ETIMEDOUT 223.252.199.66:80
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '223.252.199.66',
  port: 80 
### 期待效果

**Comment by yangyin** [comment]
服务器地址：47.95.219.45:3000, 若访问本地址能够返回首页，但请求接口时 报上面的错误，大神指导下呢，之前都是可以访问的，在2018-02-05下午开始报错;
但是 把代码在本地电脑上跑服务，然后可以访问，放到阿里云服务器上 就报上面错误,求解呢

**Comment by yangyin** [comment]
请求开始 到 返回错误 所有打印
0|app      | [request] POST http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token= proxy:undefined
0|app      | REQUEST { url: 'http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token=',
0|app      |   method: 'POST',
0|app      |   headers:
0|app      |    { Accept: '*/*',
0|app      |      'Accept-Language': 'zh-CN,zh;q=0.8,gl;q=0.6,zh-TW;q=0.4',
0|app      |      Connection: 'keep-alive',
0|app      |      'Content-Type': 'application/x-www-form-urlencoded',
0|app      |      Referer: 'http://music.163.com',
0|app      |      Host: 'music.163.com',
0|app      |      Cookie: '',
0|app      |      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/13.10586' },
0|app      |   body: 'params=i0YoCB2GcTiUzBXXozq6%2Fvb3YXuZFycJIViFs4B9EN5CltyHFL9R%2BCUEbaDirGU%2Bne7guP96V%2BreVRErTzl6J3FkNrEfQ1kaCNaHncMGUKoJLjeb2xpQVPHLPYxOVdij&encSecKey=94dd441a33fe8ff39318929b07483a5e612bf776009272a18ad582d9d52ed8aec649e919ad209b3d924a59d6ea67925ab1e0c6d31d4afcc10bf20de1e2130ea6234b1d5c6eed5224a7f4f65970c2633f7acd5967f1bc69c6bc673cb58f57577866d4709177412cbfadd8158fd7924401a66d549ca54a9635624a520a29217a2d',
0|app      |   callback: [Function] }
0|app      | REQUEST make request http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token=
0|app      | [request] POST http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token= proxy:undefined
0|app      | REQUEST { url: 'http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token=',
0|app      |   method: 'POST',
0|app      |   headers:
0|app      |    { Accept: '*/*',
0|app      |      'Accept-Language': 'zh-CN,zh;q=0.8,gl;q=0.6,zh-TW;q=0.4',
0|app      |      Connection: 'keep-alive',
0|app      |      'Content-Type': 'application/x-www-form-urlencoded',
0|app      |      Referer: 'http://music.163.com',
0|app      |      Host: 'music.163.com',
0|app      |      Cookie: '',
0|app      |      'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Mobile Safari/537.36' },
0|app      |   body: 'params=2BgoWosqs0%2BVLona7e%2BzbtVrl%2BsWxOf7bZVQJMS2YuegeovxNDv4PJhm3RHqtlbvBa4KsV7puhybPZ5DG%2B9ykF33gwJXJD42upkWUCpKmHi4nN%2FMHEvOTpnZVeDU%2BUpi&encSecKey=8087aaa2901abb4252eb21e6c8c2790159e82af76955bb2abe33f04919445022bad4acebfd6afb8fac7380a78aa01fed62fd89917313413006fb9a5cb9939c8e5a6867b945c8b6e1b1bb3158e5c0323b409f9045eacc07a2d7244fa57f6940470ab116b5b558f6bf9efc8987978c06f9422523813a25fe74f83542a275ae868d',
0|app      |   callback: [Function] }
0|app      | REQUEST make request http://music.163.com/weapi/v1/resource/comments/R_SO_4_186016/?csrf_token=
0|app      | { Error: connect ETIMEDOUT 223.252.199.66:80
0|app      |     at Object._errnoException (util.js:1019:11)
0|app      |     at _exceptionWithHostPort (util.js:1041:20)
0|app      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
0|app      |   code: 'ETIMEDOUT',
0|app      |   errno: 'ETIMEDOUT',
0|app      |   syscall: 'connect',
0|app      |   address: '223.252.199.66',
0|app      |   port: 80 }
0|app      | { Error: connect ETIMEDOUT 59.111.160.197:80
0|app      |     at Object._errnoException (util.js:1019:11)
0|app      |     at _exceptionWithHostPort (util.js:1041:20)
0|app      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
0|app      |   code: 'ETIMEDOUT',
0|app      |   errno: 'ETIMEDOUT',
0|app      |   syscall: 'connect',
0|app      |   address: '59.111.160.197',
0|app      |   port: 80 }

**Comment by Binaryify** [comment]
请提供服务器详细环境
