### ISSUE TITLE
获取的音乐质量很差

### ISSUE THREAD

**Issue by nicehiro** [Binaryify/NeteaseCloudMusicApi#192]
### 环境
系统:  
Manjaro Linux
nodejs 版本:
v9.4.0
### 出现问题
不能获取到 hMusic/bMusic/mMusic 下音乐 id 对应的 url
### 重现步骤
这个是要请求的音乐：
`                "hMusic": {
                    "name": "Numb",
                    "id": 21180904,
                    "size": 7536041,
                    "extension": "mp3",
                    "sr": 44100,
                    "dfsId": 0,
                    "bitrate": 320000,
                    "playTime": 187000,
                    "volumeDelta": -3.57
                },`
获取结果：
`{
    "data": [
        {
            "id": 21180906,
            "url": null,
            "br": 0,
            "size": 0,
            "md5": null,
            "code": 404,
            "expi": 0,
            "type": null,
            "gain": 0,
            "fee": 0,
            "uf": null,
            "payed": 0,
            "flag": 0,
            "canExtend": false
        }
    ],
    "code": 200
}`
是请求链接挂了还是我姿势不对……
### 期待效果
可以返回高品质音乐的 url

**Comment by Binaryify** [comment]
```
获取音乐 url
说明 : 使用歌单详情接口后 , 能得到的音乐的 id, 但不能得到的音乐 url, 调用此接口 , 传入的音乐 id( 可多个 , 用逗号隔开 ), 可以获取对应的音乐的 url( 不需要登录 )
```

**Comment by nicehiro** [comment]
@Binaryify 这个可以拿到音乐URL，但是音质真的很差啊...

**Comment by Binaryify** [comment]
能否提供重现例子
我这边的一个例子拿到的是 320k 音质的
![image](https://user-images.githubusercontent.com/12221718/36028938-08f19146-0ddc-11e8-9592-10c832fe853e.png)

**Comment by nicehiro** [comment]
哦 原来 br 字段是这个意思啊。我这边得到的有些歌曲是 128k 的，所以听起来质量很差。谢谢帮忙。
还有一个问题，有些歌曲是有320k音质的，可是我获取不到。
比如这首歌：
![screenshot from 2018-02-10 10-47-48](https://user-images.githubusercontent.com/17773634/36057879-ef2eaef0-0e4f-11e8-9a5d-87c910b660e7.png)
获取到的是 128k 音质的：
![screenshot from 2018-02-10 10-47-30](https://user-images.githubusercontent.com/17773634/36057883-fe2706f0-0e4f-11e8-98a2-aefcaa1b132e.png)
但是我发现下面还有这么几个可以拿到的 id：
![screenshot from 2018-02-10 10-48-01](https://user-images.githubusercontent.com/17773634/36057885-0a6b0a06-0e50-11e8-84d2-548c9eb9af46.png)
试了下但是返回为 null ……

**Comment by Binaryify** [comment]
那是需要会员的吧

**Comment by nicehiro** [comment]
我新开通了会员试了下，还是不行……

**Comment by Binaryify** [comment]
你重新登录后再试试
我这里用你的例子是可以拿到320k 的
![image](https://user-images.githubusercontent.com/12221718/36070721-c571b3f4-0f3b-11e8-8f1a-61139fa1b8c9.png)

**Comment by nicehiro** [comment]
成了，谢谢谢谢

**Comment by Binaryify** [comment]
你可以看下我的源码, br 我设置的很大的,能拿多大就拿多大

**Comment by nicehiro** [comment]
发现了我听歌音质不好的真正的问题，与此项目无关，是我播放音乐时使用的播放器解码太差了！现在换了 mpv 简直不敢相信我的耳朵！！
