### ISSUE TITLE
Python调用需要登陆的接口请求出现301错误

### ISSUE THREAD

**Issue by ChineseBgod** [Binaryify/NeteaseCloudMusicApi#194]
### 环境 python3.6
系统:  windows10

nodejs 版本:v8.9.3

### 出现问题
更新接口后，出现Python调用需要登陆的接口请求出现301错误
### 重现步骤
经笔者判断是由于Python无法传输cookie造成的
### 期待效果

**Comment by Norcy** [comment]
> 你可以修改源码,登陆后把 cookies 也发送出去

这个需要怎么做？现在python 模拟登录会缺少cookie
