### ISSUE TITLE
在HTTP和HTTPS两种模式下访问接口错误缓存的问题

### ISSUE THREAD

**Issue by zhangzhengyi12** [Binaryify/NeteaseCloudMusicApi#195]
### 环境
系统:  ubuntu

nodejs 版本: v8.9.1

### 出现问题

在Web端访问会出现跨域问题

### 重现步骤

第一步在https模式下访问一个利用这个接口的web页面，访问正常 这时候的CROS信息：`access-control-allow-origin:https://yinode.tech`

接下来切换到http模式访问同样的页面。这时候就会出现跨域限制，因为和之前的query相同，服务器将会返回和之前同样的响应，将会导致响应头也被缓存返回了:  `access-control-allow-origin:https://yinode.tech`

只要在两分钟内切换就会发生这种情况

### 期待效果

我看了一下你使用的apicache库，试了 headerBlacklist:  [], 这个选项，让他不缓存这个头，但是似乎没有生效。
我目前的解决还是直接给了个通配符。
不知道你有没有更好的方法

**Comment by Binaryify** [comment]
请求的url 加时间戳
