### ISSUE TITLE
api/song/detail/ 接口的问题？

### ISSUE THREAD

**Issue by yangzj1992** [Binaryify/NeteaseCloudMusicApi#2]
我也写过一个网易云音乐的程序，在调用这个接口时，很多歌曲的 mp3Url 参数会是空的(大部分是下架的歌曲)，不知道你是否有遇到过这个问题？如果也是的话是否有知道的合适的解决办法？谢谢.

**Comment by Binaryify** [comment]
遇到了,但是没处理
