### ISSUE TITLE
请问有没有交流群

### ISSUE THREAD

**Issue by ZionLife** [Binaryify/NeteaseCloudMusicApi#20]

**Comment by Binaryify** [comment]
暂时没有呢，有问题还是直接发 issues 吧，方便修 bug 和加功能

**Comment by ZionLife** [comment]
不是BUG，就是我个人在使用这些API中有些不懂的想请教你。
网易云音乐的认证机制是token还是session，登录成功后返回的认证信息是Set-Cookie字段中的全部吗。没有登录，直接调用/personal_fm还是返回一堆歌曲，有点懵。。。

**Comment by Binaryify** [comment]
@ZionLife 
只要登录后就有个 cookie, 只要这个 cookie 不过期就为登录状态的,有问题的话你可以加我 QQ 821374382
