### ISSUE TITLE
请问一下搜索接口的问题

### ISSUE THREAD

**Issue by Y826198755** [Binaryify/NeteaseCloudMusicApi#201]
为什么搜索接口搜索出来的歌曲很少？都是只有几条

**Comment by Binaryify** [comment]
请提供重现

**Comment by Y826198755** [comment]
就是使用这个接口http://localhost:4000/search/suggest?keywords=海阔天空 ，返回的数据我是取songs里面的数据作为搜索歌曲的列表，但是发现怎么搜索歌曲都是只有几首而且不全

**Comment by Binaryify** [comment]
你直接用 `/search?keywords=海阔天空`

**Comment by Y826198755** [comment]
哇，真的非常非常感谢，在问一个问题，就是那个歌曲图片我应该怎么取？？

**Comment by Binaryify** [comment]
`/song/detail?ids=347230`

**Comment by Y826198755** [comment]
非常感谢
