### ISSUE TITLE
你好，我获取单个歌曲url一直返回404

### ISSUE THREAD

**Issue by Wbiokr** [Binaryify/NeteaseCloudMusicApi#203]
然后直接复制你的代码一样，
打印请求头，比你少了个vary:'Accept-Encoding', contentType:'text/plain'

**Comment by Binaryify** [comment]
麻烦提供重现步骤

**Comment by Wbiokr** [comment]
是这样的  我使用同样的接口 同样的参数 甚至同样的代码  但是获取的歌曲URL都是404

**Comment by Hebingo** [comment]
我也是，请求回来的数据是这样的
{"data":[{"id":935507189,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":0,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}
url一直都是null，但是如果用你文档的id请求，又可以获取到数据，真的不懂是什么原因

**Comment by Hebingo** [comment]
![image](https://user-images.githubusercontent.com/23736239/43452436-0305adc2-94ea-11e8-9058-1dcae5a4fb7d.png)
![image](https://user-images.githubusercontent.com/23736239/43452482-23490a66-94ea-11e8-9011-9d5a3829d825.png)
第一张的是用你文档的id，第二张是用获取到的id，请求头的内容有点不太一样，请求回来的数据是这样的
{"data":[{"id":935507189,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":0,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}
url一直都是null，但是如果用你文档的id请求，获取的数据又是正常的，请问下怎么解决。

**Comment by littleQing** [comment]
我也遇到了同样的问题，请问是怎么解决的？

**Comment by littleQing** [comment]
任意一首歌都是404

**Comment by Binaryify** [comment]
@littleQing 
那个接口访问地址改成了 `song/url`

**Comment by littleQing** [comment]
哦哦，好的，我试试，感谢回复！

**Comment by littleQing** [comment]
确实改成song就解决了！再次感谢！
