### ISSUE TITLE
服务器端 https 获取歌曲url  null

### ISSUE THREAD

**Issue by xwder** [Binaryify/NeteaseCloudMusicApi#206]
### 环境
系统:  
centos X64
nodejs 版本:
v8.9.4
### 出现问题
我部署在云端，nginx 转发，https, 大概一周时间所有功能都能正常使用，今天使用发现 使用 获取歌曲url ,获取不到歌曲的地址。但是部署在本地windows环境下，使用localhost：4000 能正常使用 获取得到歌曲url。
```json
{
"data":[
{
"id": 531295576,
"url": null,
"br": 0,
"size": 0,
"md5": null,
"code": 404,
"expi": 1200,
"type": null,
"gain": 0,
"fee": 0,
"uf": null,
"payed": 0,
"flag": 0,
"canExtend": false
}
],
"code": 200
}
```
### 期待效果

**Comment by xwder** [comment]
突然一下。恢复正常自己恢复正常了。。

**Comment by shuiRong** [comment]
同样问题，https，部署到heroku上，排行榜，歌词，歌曲详情API正常使用，唯独这个获取歌曲mp3链接的不可用，返回结果同上。

**Comment by Binaryify** [comment]
外国服务器要用代理或者部署到国内服务器
