### ISSUE TITLE
登录接口 response 的 set-cookie 无法设置 cookie

### ISSUE THREAD

**Issue by Muzm** [Binaryify/NeteaseCloudMusicApi#208]
### 环境 
客户端: Windows10 Chrome 65
服务器: CentOS 7 node 8.10.0
请求工具 Axios

### 出现问题 
访问登录接口后 response 的 set-cookie 并没有设置 cookie

这是请求:
![2](https://user-images.githubusercontent.com/18257790/37759022-4886c016-2ded-11e8-9b14-5492995c31e4.jpg)

这是服务器的响应: 
![1](https://user-images.githubusercontent.com/18257790/37759267-110bd62a-2dee-11e8-85ad-9e04aa606d37.jpg)

我在控制台输入了 `document.cookie`返回的结果是 `""`
在 dev tool中的`cookie`也是空
请问服务器响应的`set-cookie`为什么会没法被设置?
Edit:
我开发用的webpack热刷新 这个服务是开在本机的. 
是因为本机域response无法设置cookie吗?
Edit2: 
虽然在 dev tool 中看不到 cookie 
在发起登录请求后再发起其他请求, 这个请求时会带上登录 cookie 的:
![_xi zj ezi1ppnjfdn 1](https://user-images.githubusercontent.com/18257790/37807602-490e66c6-2e81-11e8-9bd2-a9ca8f441ace.png)
这个 cookie 又是哪来的呢? 这时的 `document.cookie` 返回的结果仍然是 `“”`

**Comment by zentanso** [comment]
同样出现这个问题

**Comment by XGHeaven** [comment]
讲道理 ajax 不会保存跨域的 cookie 吧？

**Comment by Muzm** [comment]
@XGHeaven  https://stackoverflow.com/a/14472492  

>  You will have to set the cookie from the remote server by using the Set-Cookie header.

服务器发回的 set-cookie 应该可以设置的吧? (英语渣 可能理解错了)
