### ISSUE TITLE
/user/subcount 

### ISSUE THREAD

**Issue by XiaofanFTD** [Binaryify/NeteaseCloudMusicApi#213]
### 环境
系统:  
mac OS 10.13.4 Beta
nodejs 版本:
v9.7.1
### 出现问题
这个api 一直返回 {"code":301}，
其他api 正常
### 期待效果

**Comment by lai397826696** [comment]
@XiaofanFTD 这个api能获取的到么？/recommend/songs

**Comment by yangxiaolin** [comment]
同样的情况，/recommend/songs 也是301
