### ISSUE TITLE
无法添加歌曲到歌单

### ISSUE THREAD

**Issue by Wrn2x** [Binaryify/NeteaseCloudMusicApi#215]
### 环境
系统:  macOS 10.13.3

nodejs 版本: 6.10.2

### 出现问题
调用`/playlist/tracks?op=add&pid=<playlist ID>&tracks=<track ID>`时无法将歌曲加入歌单，返回
```
{"msg":null,"code":301}
```

### 期待效果
歌曲加入歌单

**Comment by Binaryify** [comment]
301 错误基本都是没登录就调用了需要登录的接口 , 如果登陆了还是提示 301, 基本都 是缓存把数据缓存起来了 , 解决方法是等待 2 分钟或者重启服务重新登录后再调用接口

**Comment by Wrn2x** [comment]
两种方法都试过了，在浏览器上直接访问服务也是301，先登录再调用的接口，cookie也有

**Comment by Deleny** [comment]
我也遇到这个问题了 -- 在windows系统上 一直是301`
