### ISSUE TITLE
接口出现 502 Bad Gateway

### ISSUE THREAD

**Issue by Janesummers** [Binaryify/NeteaseCloudMusicApi#223]
### 环境
系统:  IOS

nodejs 版本:

### 出现问题
请求出现 502 Bad Gateway 
### 重现步骤
/search?keywords= 海阔天空
### 期待效果
修复下

**Comment by Binaryify** [comment]
麻烦发 issue 的时候提供重现步骤,不然就直接 close 了

**Comment by Janesummers** [comment]
提供重现步骤了，第一次不懂，抱歉

**Comment by Janesummers** [comment]
浏览器直接访问都502,别的网络也是这样
