### ISSUE TITLE
搜索传入任何参数,返回的结果都会被转成asc码的数字形式

### ISSUE THREAD

**Issue by InNoob** [Binaryify/NeteaseCloudMusicApi#224]
### 环境
系统:  
linux ubuntu16.04 内核4.13
nodejs 版本:
v8.11.1
### 出现问题
传入/search?keywords=海阔天空 ,得到的结果({"result":{"songs":[{"id":3986005,"name":"42") "name"被转成了asc码的数字形式,起初以为只有中文参数才会这样,但经过测试发现英文也会, 而且这个情况和系统环境无关,我用了nginx做反向代理,同时也进行过测试排除了其和nginx有关, 现在我怀疑这个情况和网易云的api有关,能不能将请求的ip(src-form)自定义为请求者的ip而不是服务器的ip(我将这个node项目部署在了一个海外的服务器上,发现国内的没有这种情况,但是海外的有,望作者回应一下)
### 重现步骤
将项目部署在以45.x.x.x和108.x.x.x的ip开头的海外服务器上,返回的结果将会转换成asc数字
### 期待效果
返回正确的中文或英文字符,而不是asc数字

**Comment by Binaryify** [comment]
部署到国外服务器需要用代理

**Comment by InNoob** [comment]
是将服务器代理到国内吗

**Comment by Binaryify** [comment]
对的

**Comment by InNoob** [comment]
谢谢 我去试一试
