### ISSUE TITLE
search 接口获取的歌曲详情内 album.artist.blurPicUrl 歌曲封面图片获取不到

### ISSUE THREAD

**Issue by liubaiye** [Binaryify/NeteaseCloudMusicApi#226]
### 环境
系统:  
windows
nodejs 版本:
8.6
### 出现问题
search 接口获取的歌曲详情内 album.artist.blurPicUrl 歌曲封面图片获取不到 。但是有个picId 能不能通过picId获取到歌曲封面图片？
### 重现步骤
调用search 接口
### 期待效果
能够通过picId 拼接处歌曲封面

**Comment by Binaryify** [comment]
这个需要用 `/song/detail` 歌曲详情接口获取

**Comment by liubaiye** [comment]
关于移动端请求接口必须使用https 请求请问有解决办法么

**Comment by TingAlex** [comment]
现在歌曲详情/song/detail?ids=108390 这样的也获取不到封面图片的真实url了，只能够获取到图片的id 109951163187404137 ，我在官网上播放歌曲发现现在对应这首歌的url是http://p1.music.126.net/mMZNB-jhYsw29K61QtopJA==/109951163187404137.jpg?param=130y130   请问如何解决？

**Comment by TingAlex** [comment]
中间的 mMZNB-jhYsw29K61QtopJA== 不同的歌曲是不能够通用的，单纯换后面的id没有效果，而且有的歌曲前面也不是p1.music，还可能是p2或者p3等。大佬萌帮帮忙哇～～

**Comment by Binaryify** [comment]
还是可以通过专辑内容接口获取,如 `http://localhost:3000/album?id=2477011 `
![image](https://user-images.githubusercontent.com/12221718/39734141-76ef6d56-52a8-11e8-94c1-b06b6cc0912c.png)
![image](https://user-images.githubusercontent.com/12221718/39734158-87d1f0b2-52a8-11e8-9b24-2cce35858e4c.png)

**Comment by WeeStar** [comment]
可以使用这个API：music.163.com/api/cloudsearch/pc?type=1&s=青花瓷&limit=20@offset=0

response中 result.songs[0].al.picUrl 即为专辑封面
