### ISSUE TITLE
获取歌单接口，最多只能获取1000首歌曲

### ISSUE THREAD

**Issue by BugKun** [Binaryify/NeteaseCloudMusicApi#227]
### 环境
系统:  window server 2016

nodejs 版本:8.11.1
### 出现问题
获取歌单接口，最多只能获取1000首歌曲，超过部分无法获取。
### 重现步骤
https://music.163.com/playlist?id=1992951212
### 期待效果
全部都能获取到

**Comment by Binaryify** [comment]
你用的是哪个版本的,这个问题应该之前就修复了的
