### ISSUE TITLE
关于新版api params的问题

### ISSUE THREAD

**Issue by moshuchao** [Binaryify/NeteaseCloudMusicApi#229]
### 环境
系统:  
Mac
nodejs 版本:

https://music.163.com/eapi/toplist
params 的算法是怎样的

**Comment by nondanee** [comment]
AES

**Comment by zhaowweny** [comment]
新版的API参数好像只有一个params，可是这个项目里面有两个，不知道你可以正常使用吗？

**Comment by nondanee** [comment]
@zhaowweny 
目前在用的应该是三套api
1. 网页版用的是weapi，两个参数，RSA + AES-CBC：
> 随机生成一个AES密钥，用RSA公钥加密，为参数1；实际请求参数用随机生成的AES密钥加密，为参数2
> 如果用固定AES密钥，js里一查就暴露了，网易又不傻😂
2. 客户端(UWP/Win/Mac/Android)用的是eapi，一个参数，AES-ECB：
> 固定的AES密钥（应该写在代码里），加密请求参数，部分返回数据也用同样的密钥加密过
3. linux客户端用的是linux forward api，一个参数，AES-ECB：
> 固定的AES密钥（应该写在代码里），和eapi的密钥不一样，返回数据都没有加密

我没有iOS设备，猜测也是走eapi的
这个repo用的是weapi，所以两个参数
linux forward api，看这个[surmon-china/simple-netease-cloud-music](https://github.com/surmon-china/simple-netease-cloud-music)
eapi应该暂时没人做封装

**Comment by zhaowweny** [comment]
谢谢解释。我刚刚测试了eapi和weapi, 参数目前都是写死的，结果是eapi正常，weapi获取不到数据，我是用swift来做的，不知道哪里出了问题。。。

**Comment by nondanee** [comment]
@zhaowweny 😓好吧，登录了以后参数里有csrf_token，所以参数不是写死的

**Comment by zhaowweny** [comment]
@nondanee 我看是写在请求URL后面的，我加上了也不行，csrf_token应该不变的吧，现在这个weapi有没有失效？

**Comment by Binaryify** [comment]
csrf_token 会变的

**Comment by zhaowweny** [comment]
@Binaryify 发现确实是登录一次变一次，csrf_token是直接加到URL后面的？还有加密的问题，因为我没用nodejs，所以就是用js重写的，用到了[CryptoJS](https://github.com/brix/crypto-js), 每次encSecKey都是不一样的，但是params都是固定的，不知道这代码哪里有问题。`function aesEncrypt(text, secKey) {
    var _text = text;
//convert函数是转成二进制
    var lv = convert("0102030405060708");
    var _secKey = convert(secKey);
    var encrypted = CryptoJS.AES.encrypt(_text, _secKey, { iv: lv });
    encrypted += CryptoJS.enc.Base64.parse(encrypted.toString(CryptoJS.enc.Utf8));
    return encrypted;
}`

**Comment by nondanee** [comment]
@zhaowweny 
没有问题，只要你的convert是这样实现就是对的
```
function convert(text){
	return CryptoJS.enc.Utf8.parse(text);
}
```

**Comment by zhaowweny** [comment]
@nondanee convert函数不是转成二进制的吗？你这个返回的是一个有四个数字串的数组, 这样没法调用那个hexEncode() 函数了，我把我的demo放到[这里](https://github.com/zhaowweny/CryptoDemo)了，麻烦你有时间的时候看一下指导一下，多谢！

**Comment by zhaowweny** [comment]
@nondanee @Binaryify  为什么官方的params长度是556，但是我的是128或者236？感觉网页版API没有桌面端的稳定，我的Mac端的都好久没升级了，我看了Mac版的源代码，发现core.js之类的好像是一样的，但是加密算法没找到。。。

**Comment by nondanee** [comment]
@zhaowweny 最近比较忙，拖了一段时间，可能你已经自己解决了，如果还有需要的话，去看一下demo的pr

**Comment by nondanee** [comment]
@zhaowweny 对eapi有兴趣的话看看这篇，[网易云音乐PC客户端加密API逆向解析](http://www.freebuf.com/articles/web/164636.html)，其中有你想要的东西 (疯狂暗示)

**Comment by zhaowweny** [comment]
@nondanee 非常感谢你的commit，我试了下，params还是比encSecKey短，请求拿不到数据，不知道哪里出问题了，那篇逆向分析的博客只能膜拜了，我之前在别人帮助下拿到了Mac版的核心代码，不过那个core.js混淆的太厉害，根本找不着北，我之前也分析过，然后通过测试来看看混淆后的变量到底是什么，可是难度太大了，也没那么多时间搞😅
