### ISSUE TITLE
关于新版本

### ISSUE THREAD

**Issue by Binaryify** [Binaryify/NeteaseCloudMusicApi#23]
因为找了一堆新接口,如banner, 云盘,关注用户,动态等接口,再加上需要验证接口的参数,文档不好写,所以下个版本应该五一后更新

**Comment by zhixuanziben** [comment]
好厉害啊！竟然还有动态接口！加油！

**Comment by zhixuanziben** [comment]
能不能搞到歌单的评论接口，还有收藏歌单

**Comment by Binaryify** [comment]
@zhixuanziben 
收藏搞到了,mv和歌单的评论也推算出了地址,不过今天找了几十个接口,感觉这段时间都得写文档了

**Comment by zhixuanziben** [comment]
加油！感谢大神提供的接口！

**Comment by Binaryify** [comment]
@zhixuanziben 
已更新,试试怎样

**Comment by Reusjs** [comment]
获取歌曲详情的接口好像炸了

**Comment by Reusjs** [comment]
歌手单曲 还有 专辑加歌手的图片好像都出了问题

**Comment by Binaryify** [comment]
@Reusjs 
确实是,等下

**Comment by Binaryify** [comment]
@Reusjs 
专辑加歌手的图片是什么意思

**Comment by Reusjs** [comment]
@Binaryify 图片没问题了 可能是不稳定？ 昨天提issue的时候图片一直加载不出来报503的错 两点左右又可以加载了 然后就主要是/artists接口和/song/detail接口有问题

**Comment by Binaryify** [comment]
@Reusjs 
刚更新了,单曲是文档 url 没更新,歌曲详情应该是网易那里又加限制了,刚更新了,加了cookies,你再试试

**Comment by Reusjs** [comment]
@Binaryify 没问题了 辛苦了

**Comment by wangxufire** [comment]
能用来爬虫吗

**Comment by Binaryify** [comment]
@wangxufire 
可以是可以,不过网易对高频 ip 有限制,需要准备 ip 代理池,不然调用多了可能会报错

**Comment by xrr2016** [comment]
star了一下变成667了, 其实666更好看...

**Comment by Reusjs** [comment]
@Binaryify 评论接口和歌单详情接口炸了

**Comment by Binaryify** [comment]
@Reusjs 
发新 issues 吧

**Comment by Reusjs** [comment]
@Binaryify 已发

**Comment by Binaryify** [comment]
@xrr2016 
你这头像和我同事头像一模一样啊

**Comment by fchange** [comment]
希望大大加上歌曲评论点赞的api，这样我就可以刷点赞了哈哈

**Comment by Binaryify** [comment]
@fchange 
哈哈哈,我还真猜到接口参数了,晚点更新

**Comment by Binaryify** [comment]
@fchange 
已更新

**Comment by fchange** [comment]
@Binaryify
真是神速啊
哈哈 可是 能不能再给个 给某个评论点赞 的端口（貌似有点难）

**Comment by fchange** [comment]
comments.commentId?

**Comment by Binaryify** [comment]
@fchange 
不太明白,点赞的不是有了吗

**Comment by zhixuanziben** [comment]
获取用户信息,歌单，收藏，mv, dj 数量
说明:登陆后调用此接口,传入用户 id, 可以获取用户信息

必选参数:
uid : 用户 id

接口地址:
/user/subcount

调用例子:
/user/subcount

这个接口是不是有问题？返回的数据是
{
programCount: 0,
djRadioCount: 0,
mvCount: 0,
artistCount: 0,
newProgramCount: 0,
createDjRadioCount: 0,
createdPlaylistCount: 1,
subPlaylistCount: 4,
code: 200
}

**Comment by Binaryify** [comment]
@zhixuanziben 
是这样的

**Comment by zhixuanziben** [comment]
我看你源码里面有个video的接口，应该是获取视频的url吧，但是怎么用呢，文档没有写

**Comment by Binaryify** [comment]
@zhixuanziben 
没验证通过就没写了

**Comment by mov1er** [comment]
@Binaryify 博主有写怎样实现这些api的教程吗？跪求思路

**Comment by zhixuanziben** [comment]
电台没法获取播放的URL？

**Comment by zhixuanziben** [comment]
电台-节目
说明:登陆后调用此接口,传入rid,可查看对应电台的电台节目以及对应 url

必选参数:
rid: 电台 的 id

接口地址:
/dj/sub

调用例子:
/dj/program?rid=336355127 (对应'代码时间'的节目列表)

调用后返回的数据没有电台的url

**Comment by zymui** [comment]
搜索:必选参数:
keywords : 关键词
接口地址:
/search
调用例子:
/search?keywords=海阔天空
建议：发现搜索的很多音乐结果里面 mp3url 这个关键词对应地址很多都是错误地址。

**Comment by Binaryify** [comment]
@zymui 
音乐 url 要通过 `/music/url`这个接口获取
