### ISSUE TITLE
Android真机同局域网访问不了Mac

### ISSUE THREAD

**Issue by Wood-Water-Peng** [Binaryify/NeteaseCloudMusicApi#230]
### 环境
系统:  Android

nodejs 版本: v8.11.1

### 出现问题
java.net.NoRouteToHostException: No route to host
### 重现步骤
1.将库克隆到本地Mac上后，运行node app.js，正常启动
2.在PC端访问http://192.168.1.128:3000/banner，得到正常结果
3.在Android端访问http://192.168.1.128:3000/banner，报异常No route to host

Android真机和Mac在同网段

### 期待效果

期待Android能够得到和PC端一致的数据

**Comment by XGHeaven** [comment]
请关闭 Mac 的防火墙试一下。顺便看一下你们的 wifi 配置。还有就是 Android 最好关闭 vpn。

**Comment by Wood-Water-Peng** [comment]
问题已经解决了！
重新用Windows下载并运行了node.js,可以成功访问
估计是Mac电脑的设置
用Mac ping局域网内的手机死活ping不同，ping PC却可以，暂时先这样处理，希望遇到同样问题的小伙伴可以绕坑！！！

**Comment by XGHeaven** [comment]
@Wood-Water-Peng 那你可以 close 掉了。不过感觉 Mac 不应该出现这个问题，可能是你的 Mac 的设置那里不太对。
