### ISSUE TITLE
带用户名和密码的代理使用问题

### ISSUE THREAD

**Issue by lzm1988** [Binaryify/NeteaseCloudMusicApi#235]
### 环境
系统:  
centos7
nodejs 版本:
v6.14.0
### 出现问题
带用户名和密码的代理,我自己的squid搭的高匿代理，防止被人扫到，加了用户名密码，然后放到query参数里&proxy=http://ip:port:username:passwd，这样会报错，是不是没做带用户名密码的代理的功能？
### 重现步骤
用带用户名密码的代理就会有问题
### 期待效果
支持用户名密码的代理

**Comment by Binaryify** [comment]
源码很简单的,你也可以改成 post 形式的

**Comment by lzm1988** [comment]
那我尝试看看，哈哈
