### ISSUE TITLE
Vultr 日本服务器搭建后获取不到Url 如何解决呢？

### ISSUE THREAD

**Issue by zachchan** [Binaryify/NeteaseCloudMusicApi#237]
### 环境
系统:  
centos 6.5
nodejs 版本:
V6.11.1
#### 在服务器获取不到音乐的url，返回数据如下：

`{
	"data": [{
		"id": 188175,
		"url": null,
		"br": 0,
		"size": 0,
		"md5": null,
		"code": 404,
		"expi": 1200,
		"type": null,
		"gain": 0.0,
		"fee": 0,
		"uf": null,
		"payed": 0,
		"flag": 0,
		"canExtend": false
	}],
	"code": 200
}`

#### 本地获取正常：
`{
	"data": [{
		"id": 188175,
		"url": "http://m7c.music.126.net/20180503172316/2c2e2d20c2b23d707547140733f11e90/ymusic/edc1/769a/2222/a338ca5b70cd1ca3bb7d06b2edbe70a9.mp3",
		"br": 128000,
		"size": 3500494,
		"md5": "a338ca5b70cd1ca3bb7d06b2edbe70a9",
		"code": 200,
		"expi": 1200,
		"type": "mp3",
		"gain": 0.0,
		"fee": 8,
		"uf": null,
		"payed": 0,
		"flag": 0,
		"canExtend": false
	}],
	"code": 200
}`

**Comment by nondanee** [comment]
请求头里加 `X-Real-IP`

**Comment by zachchan** [comment]
能具体些吗？ 我是菜鸟，2333

**Comment by Binaryify** [comment]
@zachchan 
文档有写的
