### ISSUE TITLE
[增强] 模块化项目, 1-3 月完成

### ISSUE THREAD

**Issue by a632079** [Binaryify/NeteaseCloudMusicApi#243]
![default](https://user-images.githubusercontent.com/16975812/39969164-a6e133d0-570a-11e8-8df0-0ac53ca4c05d.png)
根据本项目， 重新封装了一些接口。 但是碰到创建歌单就有点纠结了。
![default](https://user-images.githubusercontent.com/16975812/39969174-d785d41e-570a-11e8-8561-03867713064a.png)
不是 403 ，就是 301

**Comment by Binaryify** [comment]
创建歌单的接口暂时用不了了,解决了会在这里通知

**Comment by a632079** [comment]
今天发现 似乎添加歌曲到歌单的口也凉了

**Comment by Binaryify** [comment]
@a632079 
创建歌单的已经修复好了,添加歌曲到歌单我这里测试了下是可以的,只是传的 id 不存在的话会报502

**Comment by a632079** [comment]
嗯， 我这测试了下。 也是正常的， 可能是我朋友环境的问题。
我这里使用的这样的参数。
![default](https://user-images.githubusercontent.com/16975812/40114414-6e9d7eca-593f-11e8-9ae9-06edc28d0c86.png)

自测是可以同时收藏多个 id 的， 目前好像咱们的这个api， 不支持多 id 呢。 可以试着修改下看看

**Comment by Binaryify** [comment]
嗯，明天调整下

**Comment by a632079** [comment]
十分感谢 @nondanee  的帮助。

--------
@Binaryify 啊有打算直接集成为模块？如果有的话， 我可以试着帮忙下。

> 大致思路:
目前 router 下 文件重写后， 全部移到 modules 文件夹，  使用单独的编译脚本生产 router。
这样可以保障可以同时发布模块， 又不破坏现有实现。

**Comment by Binaryify** [comment]
@a632079 感觉也不是很有必要,还有实现的话可以把现有的 router 抽出为函数,再把 createWebAPIRequest 改造下

**Comment by Binaryify** [comment]
@a632079 
嗯
