### ISSUE TITLE
没法跨域

### ISSUE THREAD

**Issue by libra1010** [Binaryify/NeteaseCloudMusicApi#247]
如题：
一个web项目
使用ajax访问
提示无法跨域
响应确实没有跨域头

**Comment by libra1010** [comment]
apicache-store →memory
apicache-version →0.9.1
cache-control →max-age=120
content-encoding →gzip
content-type →text/html; charset=utf-8
date →Thu, 17 May 2018 03:44:36 GMT
server →Tengine
status →200
vary →Accept-Encoding
x-powered-by →Express

响应头如上
直接使用的 docker镜像

**Comment by a632079** [comment]
Nginx 反代添加下 header 或者 CDN 添加 header 吧。
说实话跨域头这种东西真不是应该 Node 端加的。

**Comment by nondanee** [comment]
@libra1010 
现在有CORS响应头啊

![screenshot from 2018-05-19 14-19-05](https://user-images.githubusercontent.com/26399680/40265766-4f8607f8-5b71-11e8-8854-b15d8993866c.png)


是直接pull了README里写的镜像？
https://hub.docker.com/r/pengxiao/netease-music-api/
**Last pushed: 4 months ago**
已经落后非常多commit了

请将项目clone下来，然后自行创建docker镜像
```
$ git clone https://github.com/Binaryify/NeteaseCloudMusicApi && cd NeteaseCloudMusicApi
$ sudo docker build . -t ncm-api-self-build
$ sudo docker run -d -p 3000:3000 ncm-api-self-build
```
