### ISSUE TITLE
希望能够增加上传歌曲到云盘的API

### ISSUE THREAD

**Issue by mzz2017** [Binaryify/NeteaseCloudMusicApi#248]
### 环境
系统:  

nodejs 版本:

### 出现问题
没有上传歌曲到云盘的API
### 期待效果
希望能够上传歌曲到云盘

**Comment by nondanee** [comment]
看了下云盘上传是直传CDN的，复杂度就不是一个量级，等大神hack吧😓

**Comment by Binaryify** [comment]
已支持~
