### ISSUE TITLE
top_playlist接口参数没有效果，limit无效,order无论设置什么值返回结果都一样

### ISSUE THREAD

**Issue by hlerenow** [Binaryify/NeteaseCloudMusicApi#25]
如题，我直接使用浏览器通过get方式获取网易原生playlist接口，修改参数可以生效

**Comment by Binaryify** [comment]
```js
//分类歌单
const express = require("express")
const router = express()
const { createWebAPIRequest } = require("../util/util")

router.get("/", (req, res) => {
  const cookie = req.get('Cookie') ? req.get('Cookie') : ''
  // order可为 'hot' 可为 'new'
  const data = {
    cat: req.query.cat || "全部",
    order: req.query.order || "hot",
    offset: req.query.offset || 0,
    total: req.query.total ? 'true' : 'false',
    limit: req.query.limit || 50
  }
  createWebAPIRequest(
    'music.163.com',
    '/weapi/playlist/list',
    'POST',
    data,
    cookie,
    music_req => {
      res.send(music_req)
    },
    err => res.status(502).send('fetch error')
  )
})

module.exports = router
```

试试这个

**Comment by hlerenow** [comment]
https://music.163.com/api/playlist/list?limit=1&order=hot&offset=20 我直接使用浏览器这样访问，参数生效，但是用node后台crsf后，参数就没有效果了，不知道是不是 ndoe参数后台获取有问题

**Comment by Binaryify** [comment]
@hlerenow 
不应该吧,我这里比较是一样的

**Comment by Binaryify** [comment]
![image](https://cloud.githubusercontent.com/assets/12221718/25392079/4e4c28fc-2a0a-11e7-9741-7882981b8ec0.png)
![image](https://cloud.githubusercontent.com/assets/12221718/25392088/52cbe66a-2a0a-11e7-92ee-866c441c4481.png)

**Comment by hlerenow** [comment]
我这个不知道为什么不行，https://ycloud.h-five.com就是我部署的，不过是用nginx转发到http://hel.h-five.com:8082上面的，这两个都可以访问，但是这两个参数都没效，
![image](https://cloud.githubusercontent.com/assets/13299648/25412980/722d4b30-2a59-11e7-83e0-8d853a126e88.png)
![image](https://cloud.githubusercontent.com/assets/13299648/25412987/7c0fe298-2a59-11e7-9e0e-edf079006bc9.png)
![image](https://cloud.githubusercontent.com/assets/13299648/25413015/92b04ef2-2a59-11e7-87c2-ed4e004c2d69.png)
等我会儿我把代码拉到本地试试

**Comment by Binaryify** [comment]
@hlerenow 
好

**Comment by Binaryify** [comment]
@hlerenow 
请问问题解决了吗,没解决我下次更新就不传 cookie 了

**Comment by hlerenow** [comment]
还是不行，我没有用代理的那个api了，我直接用的163的网页api，虽然字段名不一样，但是内容都是一样的。因该是我本地的问题，开始在测试，后来我频繁的调用，我的ip被屏蔽了，就没有弄了，直接用的他自己的api，没有代理了

**Comment by Binaryify** [comment]
@hlerenow 
ok, 下次更新重新调整下,更新后通知下你

**Comment by Binaryify** [comment]
@hlerenow 
已更新,但是你那个问题一直无法重现,所以没修改这个接口的代码
