### ISSUE TITLE
获取歌单详情时，里面的subscribers为空，请问有关于获取歌单收藏者的api吗？

### ISSUE THREAD

**Issue by milklili** [Binaryify/NeteaseCloudMusicApi#250]
### 环境
系统:  
win10
nodejs 版本:
v8.9.3
### 出现问题
获取歌单详情的API   playlist/detail?id=770091247，只能返回收藏数，但没有返回具体的收藏人id
### 重现步骤
如上
### 期待效果
希望能够获取到收藏人的id，建议添加这一功能，感谢作者的付出！

**Comment by Binaryify** [comment]
新版本已经能获取到了，感谢反馈
