### ISSUE TITLE
求助：获取音乐Url地址失效

### ISSUE THREAD

**Issue by dajohnny** [Binaryify/NeteaseCloudMusicApi#252]
### 环境
系统:  

nodejs 版本:
官方demo
### 出现问题
非常感谢 博主可以提供这么强大的node音乐工具，但我在尝试过文档中罗略的解决办法，仍无法解决的问题。我 clone项目之后，跑起来！ 复制文档给的示例获取音乐Url地址，发现报错404，其次我也尝试过 audio 更改src 也失效！ 
![image](https://user-images.githubusercontent.com/17939743/40464446-890999d6-5f45-11e8-8322-e340e05fd146.png) 

### 期待效果

**Comment by Binaryify** [comment]
国外的服务器吗

**Comment by dajohnny** [comment]
是的，
参照[调用前须知](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/29#issuecomment-298358438)  问题已解决了～非常感谢！ 🤣🤣
