### ISSUE TITLE
请求没有内容了

### ISSUE THREAD

**Issue by xiaotiandada** [Binaryify/NeteaseCloudMusicApi#265]
### 环境
系统:  
linux ubuntu 16.01
nodejs 版本:
v10.4.1
### 出现问题
从昨天才出问题 服务跑起来了 但是请求没有内容了 切换node版本也没内容  偶尔可以出来一次 chrome查看是200 但是没有内容
### 期待效果

**Comment by zhaowweny** [comment]
我刚刚测试了获取用户列表也是拿不到东西，我用Mac客户端API测试可以的，不知道是不是都崩了，我再试试其他的。

**Comment by xiaotiandada** [comment]
但是我部署在服务器的一切OK

**Comment by zhaowweny** [comment]
@xiaotiandada 我比较悲剧，我不是nodejs，最近学习webkit，就拿这个练练，加密那块是原生js写的，可是生成的参数好像不对头，官方的是params比secKey长，我这params好短，试了登录就不行。。。这是我的[demo](https://github.com/zhaowweny/CryptoDemo)

**Comment by Longtailneighbor** [comment]
在爬评论时，一万条后返回的数据是重复的，是不是逻辑变了
