### ISSUE TITLE
每日推荐歌单接口失效了

### ISSUE THREAD

**Issue by cwzp990** [Binaryify/NeteaseCloudMusicApi#266]
### 环境
系统:  
win10
nodejs 版本:
v9.5.0
### 出现问题
接口报301错误，msg为null
### 重现步骤
http://localhost:3000/recommend/resource
### 期待效果

**Comment by Binaryify** [comment]
看文档
`301 错误基本都是没登录就调用了需要登录的接口,如果登陆了还是提示 301, 基本都是缓存把数据缓存起来了,解决方法是等待 2 分钟或者重启服务重新登录后再调用接口`
