### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by kekemuyu** [Binaryify/NeteaseCloudMusicApi#269]
### 环境
系统: win10 

nodejs 版本:v8.11.3

$ npm install
npm ERR! Unexpected end of JSON input while parsing near '...static":"~1.10.0","ty'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-06-26T06_02_25_172Z-debug.log

**Comment by nondanee** [comment]
`npm cache clean --force` 后再试

**Comment by kekemuyu** [comment]
ok了，感谢
