### ISSUE TITLE
npm test 登录模块出错

### ISSUE THREAD

**Issue by FogDong** [Binaryify/NeteaseCloudMusicApi#270]
### 环境
系统:  Mac Sierra

nodejs 版本: v9.11.1

### 出现问题
npm test 登录模块出错

### 重现步骤
![](http://ok2ra0say.bkt.clouddn.com/891FF7D6B0224D806BE65117536BC5D8.jpg)

### 期待效果

**Comment by Binaryify** [comment]
换成自己的账号密码
