### ISSUE TITLE
手机登录失败

### ISSUE THREAD

**Issue by FogDong** [Binaryify/NeteaseCloudMusicApi#271]
### 环境
系统:  Mac 

nodejs 版本: v9.11.1

### 出现问题
手机登录失败

### 重现步骤
![](http://ok2ra0say.bkt.clouddn.com/7E90E282EEC6A1A165CC2D19D2D79279.jpg)
![](http://ok2ra0say.bkt.clouddn.com/D7CEDEFC73643C500834B7E807C5D601.jpg)
这是没拿到req.query.phone吗

### 期待效果

**Comment by nondanee** [comment]
使用前先看[文档](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=登录)
手机登录请用这个接口`/login/cellphone`

**Comment by FogDong** [comment]
就是按文档试的呀……用的是这个接口啊（

**Comment by nondanee** [comment]
抱歉啊没仔细看错怪你了，没注意postman上的地址栏的内容只看到log里`weapi/login`，而手机登录是`weapi/login/cellphone`😂
这是之前自动注册router的bug，在前一次commit已经修复了，请`git pull`同步一下
