### ISSUE TITLE
微信小程序不支持请求本地域名 应该怎么做啊

### ISSUE THREAD

**Issue by dzyook** [Binaryify/NeteaseCloudMusicApi#274]
### 环境
系统:  

nodejs 版本:

### 出现问题
微信小程序request不支持请求本地域名 那要如何操作 使其能使用
### 期待效果

**Comment by nondanee** [comment]
有免费域名可以申请，但备案要自己做

**Comment by dzyook** [comment]
有详细点的方案嘛。万分感谢

**Comment by nondanee** [comment]
我看小程序开发的时候是可以用本地localhost
备案的事我不大清楚，细节需要你自己了解
想一条龙服务的话就腾讯云上买域名，签证书，开CVM，跑服务就好了

**Comment by dzyook** [comment]
真机试验request是不能请求本地域名的。。

**Comment by nondanee** [comment]
> 开发者工具--项目--勾选不检验域名
