### ISSUE TITLE
调用发送消息接口返回成功，但是接收账号没有收到消息

### ISSUE THREAD

**Issue by maiwenan** [Binaryify/NeteaseCloudMusicApi#276]
### 环境
系统:
win7

nodejs 版本:
v8.9.4

### 出现问题
调用消息发送接口时，返回结果是发送成功的。而且发送消息的账号也有消息记录，但是消息接收账号却没有收到消息，消息记录也没有消息。

### 重现步骤

* 直接浏览器调用 `http://localhost:3000/login?email=xxx@163.com&password=xxx` 进行登录（换成自己账号和密码）
* 登录后，也是直接浏览器调用 `http://localhost:3000/send/text?user_ids=123456&msg=测试消息` 发送消息（user_ids换成接收账号的userid）

### 期待效果
接收账号能收到信息，并且消息记录也有那条发送的消息

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
@maiwenan @Binaryify 
查到原因了，cookie需要`JSESSION-WYYY`值
这个值不在登录结果的set-cookie中，是core.js算出来的，但我定位不到算法，希望有人知道🙏
暂时的解决方案是，F12复制一个真实环境下的值来应付（测了下好像可以用固定的，但最后有个时戳所以可能是有时限的）
```
let cookie = req.get("Cookie") ? req.get("Cookie") : "";
cookie +=  "; JSESSIONID-WYYY=5ZHhtqBu%5CmwSQykO%2FvmvM1KbnIms7u4v%2FvXeX9XPklmJzz%5CQx%2FgQ0GDN4VqgYM0fggFlI2%2BuKo1ONiia6uE6Pr%5Cl8B5bdPzOcmDPIFi4uew80MtGI1IJduJmvS0cEjORmkeWz987i%2FnGlJeXUGR15Tx8uhX3yV7BFaGckP26WqjEkHlP%3A1531576513928"
```
