### ISSUE TITLE
代理有问题?

### ISSUE THREAD

**Issue by wagaman** [Binaryify/NeteaseCloudMusicApi#277]
### 环境
系统: ubuntu 16

nodejs 版本: 
v10.3.0
### 出现问题
我有一个代理池 之前好好的 可是现在访问评论时 使用代理报错 不使用代理的话 一切正常
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=3000): Read timed out. (read timeout=10)

**Comment by kebichishaobing** [comment]
嗨, 测试过他们反爬虫,封号的规则吗? 可否请教一下
