### ISSUE TITLE
能否脱离本地环境，单纯获取网易云接口

### ISSUE THREAD

**Issue by Guanrui1** [Binaryify/NeteaseCloudMusicApi#278]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
官方的不能直接调用的,这也是这个项目的建立原因

**Comment by wagaman** [comment]
可以自己写算法 但是这不是已经帮你写好了吗
