### ISSUE TITLE
‘/search’页同时传入offset=10和limit=10两个参数后，结果有误

### ISSUE THREAD

**Issue by junierice** [Binaryify/NeteaseCloudMusicApi#279]
### 环境
系统:
ubantu
nodejs 版本:
v6.11.4

### 出现问题
‘/search’页同时传入offset和limit两个参数后，结果有误。

### 重现步骤
![selection_009](https://user-images.githubusercontent.com/34947542/42639261-2bc6b2c8-8622-11e8-973a-cb568bd7f91f.png)
![selection_010](https://user-images.githubusercontent.com/34947542/42639265-2f7469c4-8622-11e8-8f99-fa22e8e38670.png)

### 期待效果
与163官网对比后发现
http://localhost:3000/search?keywords=李逸朗&offset=10
结果无误。
http://localhost:3000/search?keywords=李逸朗&offset=10&limit=10
结果有误。

**Comment by nondanee** [comment]
网易云API自己问题，server只是转发数据
