### ISSUE TITLE
请教下，如何在国外服务器上获取数据

### ISSUE THREAD

**Issue by qiuziz** [Binaryify/NeteaseCloudMusicApi#28]
![image](https://cloud.githubusercontent.com/assets/13669987/25511595/4553d992-2bfa-11e7-9338-51c0f56eeeb5.png)
服务器上获取每日推荐的返回

**Comment by Binaryify** [comment]
登陆了吗,登录了还这样的话可以试试 ip代理

**Comment by qiuziz** [comment]
登录了，没有登录的情况下是返回code:301的

我现在换了接口，用户歌单详情的接口 是可以，也可以返回数据。


node新手，在看代理怎么弄，但是国内没有服务器- -。

感谢

**Comment by Binaryify** [comment]
@qiuziz 
可以试试这个代理服务
https://bird.ioliu.cn/

**Comment by Binaryify** [comment]
@qiuziz 
感谢 @hiyangguo 提出的解决办法
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/29#issuecomment-298357483
