### ISSUE TITLE
关于歌曲详情api的获取结果问题

### ISSUE THREAD

**Issue by lai397826696** [Binaryify/NeteaseCloudMusicApi#282]
### 环境
系统:
win7 64
nodejs 版本:
8.11.2
### 出现问题
![image](https://user-images.githubusercontent.com/13134964/42796591-9aa1688e-89bd-11e8-84bc-67c59eba39e0.png)
在练手的项目里请求，一直刷新，获取的结果userId都是-1，评论点赞一直false；

![image](https://user-images.githubusercontent.com/13134964/42796664-0d18add2-89be-11e8-96ae-f3881b8919c9.png)
而直接在新窗口打开，请求结果的userId是正常的，评论点赞也正常；
请问这是因为什么原因导致的？求解决

### 期待效果
数据返回正确
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
看看是不是 cookies 没带上

**Comment by Binaryify** [comment]
issues 里面搜一下也能搜到很多关于 ajax cookies 没带上的问题
