### ISSUE TITLE
用此项目开发了一个基于 electron-vue 的音乐播放器

### ISSUE THREAD

**Issue by SmallRuralDog** [Binaryify/NeteaseCloudMusicApi#285]
感谢贵项目提供的接口。希望能给个友情链接！！！
[https://github.com/SmallRuralDog/electron-vue-music](https://github.com/SmallRuralDog/electron-vue-music)

![](https://i.loli.net/2018/07/23/5b55923480eac.png)
![](https://i.loli.net/2018/07/23/5b5592342f330.png)
![](https://i.loli.net/2018/07/23/5b559233da730.png)
![](https://i.loli.net/2018/07/23/5b5592333d294.png)
![](https://i.loli.net/2018/07/23/5b5592337750c.png)

**Comment by XGHeaven** [comment]
不错，不过不知道内存占用情况怎么样
