### ISSUE TITLE
获取歌曲url,现在不能获取了，返回{"code":-460,"msg":"Cheating"}

### ISSUE THREAD

**Issue by ChangQing666** [Binaryify/NeteaseCloudMusicApi#288]
### 环境
系统:mac

nodejs 版本:

### 出现问题
获取歌曲url接口，目前不能正常返回，前几天还可以的，是不是被网易屏蔽了呢
{"code":-460,"msg":"Cheating"}
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by addison010** [comment]
应该是今天下午的时候开始被河蟹掉了，
文档里写的另外一个获取方法
使用http://music.163.com/song/media/outer/url?id=id.mp3直接放进audio的src
亲测可用

**Comment by BeauitfullXiaoJian** [comment]
嗯，楼上正解。今天下午突然就说接口欺诈。。。。我们与网易工程师斗智斗勇的日子

**Comment by ChangQing666** [comment]
@addison010 十分感谢

**Comment by markruan** [comment]
被河蟹了

**Comment by Binaryify** [comment]
参考文档的另外一个解决办法
>注 : 部分用户反馈获取的 url 会 403,hwaphon找到的 解决方案是当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id=id.mp3 以 src 赋予 Audio 即可播放

**Comment by ChangQing666** [comment]
多谢各位

**Comment by koder12** [comment]
> 注 : 部分用户反馈获取的 url 会 403,hwaphon找到的 解决方案是当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id=id.mp3 以 src 赋予 Audio 即可播放

But I am getting 404 error when I am trying to access it.

**Comment by koder12** [comment]
> 注 : 部分用户反馈获取的 url 会 403,hwaphon找到的 解决方案是当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id=id.mp3 以 src 赋予 Audio 即可播放

But I am getting an 404 error when I am trying to access this url in the browser

http://music.163.com/song/media/outer/url?id=33894312.mp3

**Comment by addison010** [comment]
@koder12 
Mate, I guess you were trying to access it from overseas like myself, you'll need a VPN or some kind of unblock chrome extension.

**Comment by koder12** [comment]
Yeah, bro! you are absolutely right. I used 'unblock netease music' extension and it started working. Isn't there any other to access music url without extension (because it failed with proxy method).
