### ISSUE TITLE
获取歌曲url返回的数据没有歌曲的真实地址

### ISSUE THREAD

**Issue by hiyangguo** [Binaryify/NeteaseCloudMusicApi#29]
未登录状态下调用接口`music/url?id=347230`
返回数据如下
```json
{
    "data": [{
        "id": 347230,
        "url": null,
        "br": 0,
        "size": 0,
        "md5": null,
        "code": 404,
        "expi": 1200,
        "type": null,
        "gain": 0.0,
        "fee": 0,
        "uf": null,
        "payed": 0,
        "flag": 0,
        "canExtend": false
    }],
    "code": 200
}
```
是 api 有调整了么？

**Comment by Binaryify** [comment]
需要通过 /music/url 获取音乐地址

**Comment by hiyangguo** [comment]
@Binaryify 我调用的就是这个接口啊

**Comment by Binaryify** [comment]
我这边登陆后可以正常获取 url, 应该是这个接口需要登录

**Comment by hiyangguo** [comment]
我是部署到服务端了  本地是可以拿到的 不知道为什么

**Comment by Binaryify** [comment]
能否提供具体情况

**Comment by hiyangguo** [comment]
![image](https://cloud.githubusercontent.com/assets/15609339/25535147/abf9d2be-2c68-11e7-8dcd-32a67e2df2fd.png)
![image](https://cloud.githubusercontent.com/assets/15609339/25535218/e3d484fe-2c68-11e7-9599-505186d1a97e.png)

除了域名不一样 其他的都一样

**Comment by Binaryify** [comment]
稍等,我部署到服务器试试

**Comment by hiyangguo** [comment]
地址 我发你邮箱了 麻烦你了

**Comment by Binaryify** [comment]
@hiyangguo 
查出问题了,是因为你服务器在美国的原因
![image](https://cloud.githubusercontent.com/assets/12221718/25535633/63fd5da8-2c6a-11e7-8182-182402149dc4.png)

我这边大陆服务器是正常的
http://thunderoux.com:5000/music/url?id=2867202

**Comment by hiyangguo** [comment]
恩恩 我感觉可能也是这个问题 谢了 。 😬

**Comment by hiyangguo** [comment]
此问题解决办法在
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/util.js#L15

添加
```
X-Real-IP':'211.161.244.70' //任意国内IP
```
即可解决此问题

**Comment by Binaryify** [comment]
@hiyangguo 
感谢提出解决办法 ~

**Comment by hiyangguo** [comment]
感觉不是所有人都用得上 就不提pr了  哈哈哈 感谢 @Binaryify 辛苦的整理

**Comment by Binaryify** [comment]
@hiyangguo 
我把方法写在文档里吧 😁

**Comment by hiyangguo** [comment]
建议你把这个库`publish`到 npmjs 这样方便 开发的时候用 。我现在都是fork 了一份 在本地跑的，有点略麻烦。万分感谢！

**Comment by Binaryify** [comment]
@hiyangguo 
有的
[NeteaseCloudMusicApi](https://www.npmjs.com/package/NeteaseCloudMusicApi)

**Comment by hiyangguo** [comment]
👍 之前我找了 没找到- - 一定是姿势不对

**Comment by qiuziz** [comment]
这个解决了国外服务器的问题，但是我很好奇是为什么，谷歌了没太看懂这块

![image](https://cloud.githubusercontent.com/assets/13669987/25609926/d3e64a76-2f53-11e7-954d-1a3e0806c738.png)
在服务器上接口请求的 remote address还是我服务器的地址

能说下原因吗 求解

**Comment by hiyangguo** [comment]
物理地址肯定是没办法改的。设置 ` X-Real-IP` 只是为了告诉网易的服务器然他们使用这个 IP 进行解析。如果有的 API 没有读取 ` X-Real-IP` 这个头信息 其实也是不行的。

**Comment by qiuziz** [comment]
我自己弄错了 客户端请求是我自己发给node服务的 - -谢谢

**Comment by homelajiang** [comment]
搬瓦工的vps不能使用啊，配置过了X-Real-IP也不能用。

**Comment by zyw5791557** [comment]
阿里云香港配置了也不能用呀，有教的嘛。。。

**Comment by homelajiang** [comment]
我的能用了，配置之后，首先登录，再调用其它接口。

**Comment by lemos1235** [comment]
这个是能获取 url地址，但是无法请求 url数据。

**Comment by mysteryven** [comment]
> 此问题解决办法在
> https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/util.js#L15
> 
> 添加
> 
> ```
> 'X-Real-IP':'211.161.244.70' //任意国内IP
> ```
> 即可解决此问题

请问现在的版本如何解决这个问题？
