### ISSUE TITLE
获取排行榜和歌单详情的返回数据只有一首单曲

### ISSUE THREAD

**Issue by addison010** [Binaryify/NeteaseCloudMusicApi#292]
### 环境
系统: Windows

nodejs 版本:10.6.0

### 出现问题
获取排行榜和歌单详情的返回数据只有一首单曲

### 重现步骤
/top/list?idx=0
/playlist/detail?id=924680166

### 期待效果
返回结果的tracks数组应该包含多首单曲

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
具体 id 呢

**Comment by wstbest** [comment]
获取排行榜和歌单详情的返回数据只有一首单曲

**Comment by ChangQing666** [comment]
是的我也有这样的问题

**Comment by szhielelp** [comment]
表示出现了同样问题

**Comment by sunzongzheng** [comment]
早上抓了一下包，网易云新增了参数，可参考[这里](https://github.com/sunzongzheng/musicApi/blob/eac81585a7c508b4a16619fd87d4a7af5e39a776/src/netease/instance/base.js#L19)

**Comment by nondanee** [comment]
@sunzongzheng nuid这个参数最近的commit里有加啊😯，麻烦git pull 一下

**Comment by sunzongzheng** [comment]
get

**Comment by sunzongzheng** [comment]
@yangrenmu 找到加密函数的js及行数，charles替换文件，本地修改，在加密前把参数打印出来。可以找到加密前的参数结构。其他的就f12就行

**Comment by nondanee** [comment]
@yangrenmu @sunzongzheng 
那我冒昧的问一下二位，只有一首歌数据的问题有没有解决？
