### ISSUE TITLE
按照文档例子测试，拿不到数据

### ISSUE THREAD

**Issue by AllySu** [Binaryify/NeteaseCloudMusicApi#295]
您好，现在完全拿不到数据了，不存在错误，按照文档测试，都没有数据。

**Comment by nondanee** [comment]
您测试了哪些接口没有数据，请列出，谢谢

**Comment by AllySu** [comment]
http://120.79.162.149:3000/xx/xx
http://120.79.162.149:3002/#/singer

都拿不到数据呢？ @nondanee

**Comment by nondanee** [comment]
@AllySu 
试了一下`120.79.162.149:3000`这个server除了首页正常其它都是pending到超时failed
目测是向网易云的请求发不出去，我想应该是防火墙把出口请求拦住了，不是程序bug

搜IP的时候发现这个是[CaiJinyc/vue-music-webapp](https://github.com/CaiJinyc/vue-music-webapp)项目的测试地址。因为你不是项目的owner，我也不确定这台ecs是否属于你。如果你有登录权限，可以检查一下：
- iptables的output是否缺少accept规则
- 阿里云安全组出站规则有没有放行

**Comment by AllySu** [comment]
好吧，先不管了，反正以前能用，现在不行了

**Comment by AllySu** [comment]
@nondanee 项目的测试地址确实不是我的。但是几天是没问题的。现在主要是没有后台数据了，当然显示不出来了。刚开始是播放器产生  cheating 问题。只是现在都没有了数据。。。iptables的output是否缺少accept规则？？不懂哦，小白一枚呢

**Comment by nondanee** [comment]
@AllySu 
不好意思之前猜错了，刚才又测了下`120.79.162.149:3000`这个server好像不是防火墙的问题，其它请求都可以，唯独网易云不行，感觉像是被`music.163.com`拉黑了
你可以自己试试 (`mv/url`这个接口近似一个代理)
```
http://120.79.162.149:3000/mv/url?url=http://mail.163.com 正常
http://120.79.162.149:3000/mv/url?url=http://music.163.com 不正常
```
因为不是你的ecs，你也没办法查的，就算了
如果有需要还是自己买一台vps来部署吧

**Comment by AllySu** [comment]
@nondanee 现在先不搞。。。也不会。。。有其他事。。。
