### ISSUE TITLE
获取歌曲url出现460

### ISSUE THREAD

**Issue by ZhengXiaowei** [Binaryify/NeteaseCloudMusicApi#299]
### 环境
系统:window

nodejs 版本: 8.9.3

### 出现问题

请求歌曲url的时候出现460的错误

![image](https://user-images.githubusercontent.com/15809841/44500549-9bee9700-a6bb-11e8-92bc-a46f40ad811c.png)
/api/music/是我代理到自己服务器的地址

**Comment by nondanee** [comment]
早已解决，请`git pull`

**Comment by ZhengXiaowei** [comment]
好的 谢谢~

**Comment by koder12** [comment]
I used the latest version, but still I am getting this error

> {
"data": [
{
"id": 33894312,
"url": null,
"br": 0,
"size": 0,
"md5": null,
"code": 404,
"expi": 1200,
"type": null,
"gain": 0,
"fee": 0,
"uf": null,
"payed": 0,
"flag": 0,
"canExtend": false
}
],
"code": 200
}

Can anyone tell me why am I getting this error?

**Comment by nondanee** [comment]
@koder12 
The problem you met is not "460 cheating" error
Are you overseas?
Oversea request tutorial has been already involved in the [API documentation](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=接口文档)
>由于网易限制,此项目在国外服务器上使用会受到限制,如需解决 , 可使用大陆服务器或者使用代理 , 感谢 @hiyangguo提出的解决方法: 在 'util.js' 的 'headers' 处增加 X-Real-IP':'211.161.244.70' // 任意国内 IP 即可解决

**Comment by koder12** [comment]
Yes, I am an overseas user. I will go through the tutorial you said.

**Comment by koder12** [comment]
Yes, it worked. Thanks for the suggestion.

**Comment by nondanee** [comment]
@koder12 
My pleasure.

**Comment by koder12** [comment]
[@nondanee](https://github.com/nondanee)

Can you please give me one more suggestion, how can I play the url with browser (like streaming), because when I am trying to run the url in the browser, it is giving me no response, but I can download the url.

**Comment by nondanee** [comment]
@koder12 
It seems to be the error of CDN
Change the url in this way
```
songUrl = songUrl.replace(/m(\d+)?.music.126.net/g,'m$1c.music.126.net')
```

e.g.
```
http://m8.music.126.net/XXXXXXXX => http://m8c.music.126.net/XXXXXXXX
http://m10.music.126.net/XXXXXXXX => http://m10c.music.126.net/XXXXXXXX
```

I am not sure, but I test in my place (HK) and it works.

**Comment by upendra-web** [comment]
Sorry for the late reply, @nondanee  it is working finally, followed your suggestion. Thank you very much.
