### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by zhixuanziben** [Binaryify/NeteaseCloudMusicApi#30]
新碟上架的地址是/top/album，不是/top/albums

**Comment by Binaryify** [comment]
@zhixuanziben 
感谢提出,已更新  
另外文档地址在 /docs/README.MD 里,如果发现类似的描述错误可以提交 PR

**Comment by zhixuanziben** [comment]
好的，我看好多接口都变了，数据结构有没有变化呢

**Comment by Binaryify** [comment]
@zhixuanziben 
只是 url 稍微调整了下,更规律点,我这边相当于中转站,数据还是官方提供的,没变化
