### ISSUE TITLE
新功能建议:建议在搜索接口里添加"视频"项

### ISSUE THREAD

**Issue by 273851541** [Binaryify/NeteaseCloudMusicApi#301]
### 环境
系统:win10

nodejs 版本:8.11.4

### 出现问题
我想请求搜索里视频的数据,于是在官网查看了type=1014,利用返回数据里的vid调用/mv?mvid=***** 接口,但是返回的数据为空状态304.
所以建议大神新增一个获取视频url的地址
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by lizhenyuls** [comment]
http://music.163.com/api/cloudvideo/playurl?ids=['${id}']&resolution=720
http://music.163.com/api/song/enhance/play/mv/url?id=${id}&r=720

**Comment by 273851541** [comment]
![128503494464530738](https://user-images.githubusercontent.com/22609984/44719188-158be800-aaf5-11e8-980b-4e3745f826d1.jpg)

网易云搜索里"视频"选项与MV的区别:

1.type类型
视频:   type=1014
MV:     type=1004

2.搜索结果
视频:   MV+网友上传视频   
MV:    只是MV                       

3.id类型
视频  id(例):89ADDE33C0AAE8EC14B99F6750DB954D
MV    id(例):10762041

/mv?mvid=*******     目前该接口只能拼接MV的id可以获取到数据

**Comment by Binaryify** [comment]
已更新 @273851541 
感谢 @lizhenyuls 提供的方法

**Comment by 273851541** [comment]
十分感谢,真的太棒了
