### ISSUE TITLE
您好，想问一下有发表歌曲评论的接口吗，这个有这个需求

### ISSUE THREAD

**Issue by xintao-taotao** [Binaryify/NeteaseCloudMusicApi#307]
### 环境
系统:

nodejs 版本:

### 出现问题
就是希望增加一个歌曲评论的接口

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by lizhenyuls** [comment]
url--/weapi/resource/comments/add
参数--{"threadId":"","content":"","csrf_token":""} 
url--/weapi/resource/comments/delete 
参数--{"commentId":"","threadId":"","csrf_token":""}a

**Comment by Binaryify** [comment]
文档里面有

**Comment by xintao-taotao** [comment]
可是，我并没有在https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E6%AD%8C%E6%9B%B2%E8%AF%84%E8%AE%BA官方文档上看到有这个发表评论的接口...

**Comment by Binaryify** [comment]
哦哦看错了,发表评论暂时还没有的

**Comment by Binaryify** [comment]
这周看看能不能加上

**Comment by xintao-taotao** [comment]
如果可以那真的太好了！！！谢谢作者，辛苦了！！

**Comment by lizhenyuls** [comment]
@Binaryify  
评论url--https://music.163.com/weapi/resource/comments/add
参数--{"threadId":"","content":"","csrf_token":""}
删除评论url--https://music.163.com/weapi/resource/comments/delete
参数--{"commentId":"","threadId":"","csrf_token":""}
可以用

**Comment by xintao-taotao** [comment]
啊。。这个该怎么用。。有文档不

**Comment by lizhenyuls** [comment]
就和其他的接口一样，更改url以及对应的参数就可以了

**Comment by xintao-taotao** [comment]
就是不知道这几个参数代表啥意思啊。。这三个字参数分别要填什么

**Comment by xintao-taotao** [comment]
要不我还是等作者更新文档吧。。我这个看不太懂

**Comment by Binaryify** [comment]
@lizhenyuls 
可以可以,下班我加上去

**Comment by xintao-taotao** [comment]
哈哈哈，作者在哪上班，加个QQ咯

**Comment by lizhenyuls** [comment]
threadId: 
R_SO_4_//歌曲   R_MV_5_//mv    A_PL_0_//歌单   R_AL_3_//专辑  A_DJ_1_// 电台 R_VI_62_//视频 +对应的id
 content:评论内容 
commentId:评论id

**Comment by xintao-taotao** [comment]
谢谢！！！！，更新太快了，感谢！！
