### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by lany9527** [Binaryify/NeteaseCloudMusicApi#31]
在4000端口，启动app.js后，前端用react处理API，结果报错：xhr.js:177 XMLHttpRequest cannot load localhost:4000/banner. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.。请问在哪里设置允许跨域。

**Comment by Yogayu** [comment]
请问解决这个问题了吗？是如何解决的呢？
