### ISSUE TITLE
不能获取音乐url

### ISSUE THREAD

**Issue by liu354** [Binaryify/NeteaseCloudMusicApi#310]
### 环境
系统:windows

nodejs 版本:8.11.1

### 出现问题
使用/music/url api
不能获取音乐url
### 重现步骤

![default](https://user-images.githubusercontent.com/33274539/44942775-f12d5580-adeb-11e8-8b7f-1b76155a1f84.png)

![default](https://user-images.githubusercontent.com/33274539/44942763-c4793e00-adeb-11e8-9f14-14a70da283b8.png)

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
使用的版本是否是最新的 v2.19.0呢

**Comment by yangxiaolin** [comment]
可以用这个URL https://api.imjad.cn/cloudmusic/?type=lyric&id=歌曲id
