### ISSUE TITLE
请问能增加一个手机版模糊搜索的api吗

### ISSUE THREAD

**Issue by Anzhi-Meiying** [Binaryify/NeteaseCloudMusicApi#318]
请问能增加一个搜索关键字联想的api吗例如手机版网易云音乐，目前好像只有pc版的搜索建议，不太友好...

**Comment by lizhenyuls** [comment]
music.163.com/weapi/search/suggest/keyword
参数与web版一样

**Comment by Anzhi-Meiying** [comment]
你说的是这个吗https://netease.api.zzsun.cc/search/suggest?keywords=海阔
返回的是图一，但是理想中是图二手机版的关键字联想，请问一下有可能实现吗
![tim 20180912152519](https://user-images.githubusercontent.com/13428030/45409040-ab507700-b6a0-11e8-9240-64fd5f04fe6c.png)

![screenshot_2018-09-12-15-26-40-041_com netease cl](https://user-images.githubusercontent.com/13428030/45409038-aa1f4a00-b6a0-11e8-855c-0d6b4e09817f.png)

**Comment by lizhenyuls** [comment]
就是图二的

**Comment by Anzhi-Meiying** [comment]
@lizhenyuls 呃..再打扰一下，https://netease.api.zzsun.cc/search/suggest?keywords=海阔

是这个接口吗...

**Comment by lizhenyuls** [comment]
module.exports = (req, res, createWebAPIRequest, request) => {
  const cookie = req.get("Cookie") ? req.get("Cookie") : "";
  const data = {
    csrf_token: "",
    s: req.query.keywords || ""
  };

  createWebAPIRequest(
    "music.163.com",
    "/weapi/search/suggest/keyword",
    "POST",
    data,
    cookie,
    music_req => {
      res.send(music_req);
    },
    err => res.status(502).send("fetch error")
  );
};
app版搜索建议

**Comment by lizhenyuls** [comment]
@Anzhi-Meiying 上面代码测试可用，手机版的，你给的是web版的

**Comment by Anzhi-Meiying** [comment]
需要登陆吗

**Comment by lizhenyuls** [comment]
@Anzhi-Meiying 不需要

**Comment by Anzhi-Meiying** [comment]
@lizhenyuls 感谢回答，打扰您的时间了，实不相瞒我对这个完全不懂...我是一个Android开发者...这个的话是https://music.163.com/weapi/search/suggest/keywords=海阔天空
吗，还是需要传header什么的，不太懂这个...

**Comment by Anzhi-Meiying** [comment]
@lizhenyuls 非常感谢！

**Comment by jgsrty** [comment]
大牛您好
我想问下播放进度这块，该怎么搞呢，没什么思路

**Comment by Anzhi-Meiying** [comment]
@jgsrty 不是大牛，可以去看看相关优秀音乐开源项目，比如 https://github.com/naman14/Timber
