### ISSUE TITLE
关于接口失效问题

### ISSUE THREAD

**Issue by Reusjs** [Binaryify/NeteaseCloudMusicApi#32]
目前发现playlist/detail接口 search接口 comment/music接口失效

**Comment by Binaryify** [comment]
具体表现是什么,传了什么参数,返回结果是什么

**Comment by Reusjs** [comment]
@Binaryify 传了id 返回结果是该网页无法正常运作 xxx.com 未发送任何数据

**Comment by Reusjs** [comment]
search传的keywords

**Comment by Binaryify** [comment]
是否访问太频繁了,我这边正常
![image](https://cloud.githubusercontent.com/assets/12221718/25667461/1da0d44e-3056-11e7-9510-b07df12bfb2c.png)

**Comment by Reusjs** [comment]
@Binaryify 这样的话不用代理池有什么办法解决吗？ 等多久能好

**Comment by Binaryify** [comment]
@Reusjs 
这个不好说,明天再试试?

**Comment by Reusjs** [comment]
@Binaryify 嗯好 谢谢
