### ISSUE TITLE
播放进度怎么做呢，望大牛提供下思路

### ISSUE THREAD

**Issue by jgsrty** [Binaryify/NeteaseCloudMusicApi#324]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
那是客户端的问题,自行查找 HTML5 audio 相关 api

**Comment by Binaryify** [comment]
那是客户端的问题,自行查找 HTML5 audio 相关 api
