### ISSUE TITLE
热门评价获取

### ISSUE THREAD

**Issue by atheist1** [Binaryify/NeteaseCloudMusicApi#327]
### 环境
系统:

nodejs 版本:

### 出现问题
你好，调用获取评价接口返回热门评价总数不改变，永远是14条，请问是有其他获取热门评价的接口吗
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by lizhenyuls** [comment]
module.exports = (req, res, createWebAPIRequest) => {
  const body = req.method.toLowerCase() === 'get' ? req.query : req.body;
  let cookie = req.get('Cookie') ? req.get('Cookie') : '';
  cookie += ';os=pc;';
  const id = body.id;    //  歌曲 id
  const typeMap = {
    0: 'R_SO_4_',     //  歌曲
    1: 'R_MV_5_',     //  mv
    2: 'A_PL_0_',     //  歌单
    3: 'R_AL_3_',     //  专辑
    4: 'A_DJ_1_',      //  电台,
    5: 'R_VI_62_'     //  视频
  };
  const type = typeMap[body.type];
  const data = {
    offset: body.offset || 0,
    rid: id,
    limit: body.limit || 20,
    csrf_token: '',
  };
  const url = `/weapi/v1/resource/hotcomments/${type}${id}`;
  createWebAPIRequest(
    'music.163.com',
    url,
    'POST',
    data,
    cookie,
    music_req => res.send(music_req),
    err => res.status(502).send('fetch error')
  )
};

**Comment by atheist1** [comment]
感谢感谢，但是const url = /weapi/v1/resource/hotcomments/${type}${id};这忘记加反引号了把
