### ISSUE TITLE
IP高频会自动解除吗 还是永久封了

### ISSUE THREAD

**Issue by jgsrty** [Binaryify/NeteaseCloudMusicApi#328]
### 环境
系统:

nodejs 版本:

### 出现问题
调登录接口次数太多了 提示ip高频
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
过段时间会解除
