### ISSUE TITLE
点赞返回200，实际未点赞

### ISSUE THREAD

**Issue by kouchao** [Binaryify/NeteaseCloudMusicApi#333]
### 环境
系统:  windows10

nodejs 版本: v8.11.3

### 出现问题
无法给评论点赞

### 重现步骤
登录
```
login/
```
=> 赞某评论
```
comment/like?id=1311345325&cid=1256793566&t=1&type=0 
```
=> 返回结果
```
{
    "code": 200, 
    "msg": "Ats" 
}
```
=> 实际赞未点上

### 期待效果
给评论正常点赞

**Comment by Binaryify** [comment]
这种一般都是接口缓存问题,加时间戳可解决

**Comment by kouchao** [comment]
@Binaryify 经测试，添加时间戳也没有生效。看了下pm2 log，确认不是缓存问题

**Comment by Binaryify** [comment]
要么就是你找错资源了,不然200肯定是没问题的

**Comment by Binaryify** [comment]
另外检查下所用的版本,看看是不是最新的 v2.20.3

**Comment by Binaryify** [comment]
我刚检查了一遍,确实存在这个问题,晚点看看能不能修复

**Comment by kouchao** [comment]
好的，出现过类似问题 #166

**Comment by Binaryify** [comment]
嗯,之前修复过的,现在不知道是不是合并过几次 PR, cookies 缺东西了

**Comment by nondanee** [comment]
@Binaryify emmm我把cellphone里部分cookie去掉了，不过感觉另有原因，我查一下看

**Comment by nondanee** [comment]
参数有clientToken的，还是一样在cookie里加`os=osx`能解决
操作不生效的返回结果是
```
{"code":200,"msg":"Ats"}
```
Ats大概就是anti spam的意思吧

**Comment by kouchao** [comment]
刚才试了一下, @nondanee 提供的方法可行。

**Comment by Binaryify** [comment]
@nondanee 我再加回去吧

**Comment by Binaryify** [comment]
@kouchao 已修复

**Comment by nondanee** [comment]
@Binaryify 想问一下os那个cookie是怎么发现的啊

**Comment by kouchao** [comment]
我还有一个问题，就是我用node发请求，一直是301.我加上withCredentials也是301，或许origin没有，从而导致Access-Control-Allow-Origin变为*，由此引发一个问题，单元测试中如何测试这种类似的接口呢？ @Binaryify

**Comment by Binaryify** [comment]
@nondanee 之前抓包的时候对比看到的
