### ISSUE TITLE
获取音乐链接后，会被chrome浏览器CORB导致无法播放

### ISSUE THREAD

**Issue by bibi7** [Binaryify/NeteaseCloudMusicApi#337]
### 环境
系统: 
mac os 10.12.4

nodejs 版本: 
v10.9.0

### 出现问题
获取歌曲url后，播放会被chrome浏览器CORB问题
![image](https://user-images.githubusercontent.com/38184077/46254384-416a0700-c4c1-11e8-9036-32f3a8c4c69b.png)

### 重现步骤
在通过接口music/url进行通过歌曲id查询歌曲url的时候，接口可以正确返回，但当audio标签的src属性设置成歌曲地址后，chrome会CORB从而拦截歌曲，在safari上正常使用

但是上两个月功能是正常的，不大确定是否是两个月后chrome版本更新的问题。

### 期待效果
这个问题其实不大确定是需要在客户端修改或者服务端修改

**Comment by bibi7** [comment]
http://www.sohu.com/a/241929462_604699
另外附上链接， 本机的chrome版本为68

**Comment by bibi7** [comment]
![image](https://user-images.githubusercontent.com/38184077/46255073-58155b80-c4cb-11e8-9ed2-7ef12a5e70dd.png)
应该是歌曲url在get操作时候返回header头的content-type不对，期望的content-type应为audio/mpeg，这里是text/html。
有点懵了，这里返回的header头设置应该也不在这个项目中才对

**Comment by nondanee** [comment]
我测试了没有问题

歌曲链接有时限的，20分钟，过期返回403 forbidden，content-type是text/html
请在inspect的network里preview自查一下是不是这个原因

**Comment by bibi7** [comment]
ok  我有空试试

**Comment by bibi7** [comment]
在家里win平台上 chrome为71 不会发生上述情况。。
不过在公司的电脑上还是必现，暂时先记着，issue我这这边先关了

**Comment by Muzm** [comment]
我也遇到了同样的问题 如果出现chrome的CORB警告我这边就会看不到这个请求的Response, Preview同样是空的
![tim 20181225113143](https://user-images.githubusercontent.com/18257790/50411155-d10d2080-0838-11e9-9d39-47b258d0fcf5.png)
请问找到解决方案了吗

**Comment by bibi7** [comment]
> 我也遇到了同样的问题 如果出现Chrome的CORB警告我这边就会看不到这个请求的Response, Preview同样是空的. 环境同样是win下的Chomre 71
> ![tim 20181225113143](https://user-images.githubusercontent.com/18257790/50411155-d10d2080-0838-11e9-9d39-47b258d0fcf5.png)
> 有没有可能是NeteaseCloudMusicApi的缓存机制返回的过期的歌曲地址

**Comment by bibi7** [comment]
> 我也遇到了同样的问题 如果出现Chrome的CORB警告我这边就会看不到这个请求的Response, Preview同样是空的. 环境同样是win下的Chomre 71
> ![tim 20181225113143](https://user-images.githubusercontent.com/18257790/50411155-d10d2080-0838-11e9-9d39-47b258d0fcf5.png)
> 有没有可能是NeteaseCloudMusicApi的缓存机制返回的过期的歌曲地址

这个问题上次发生在公司的开发机上，个人当时推测可能是公司的一些限制，在家里是没有上述问题的，你可以多排查看看，另外过期的歌曲地址你访问的话应该是403才对

**Comment by bibi7** [comment]
这个问题上次发生在公司的开发机上，个人当时推测可能是公司的一些限制，在家里是没有上述问题的，你可以多排查看看，另外过期的歌曲地址你访问的话应该是403才对

**Comment by nondanee** [comment]
@Muzm 歌曲链接和 API 缓存无关
麻烦把 url 复制到地址栏直接打开试一试

**Comment by nondanee** [comment]
被 Referer 防盗链拒绝了，也会 403，是 text/html 
#383 meta 里加上 no-referrer 可以绕过，建议试试
CORB 应该和 chrome 版本有关系，我这边的 chrome 都能显示 403 且不会被 CORB 拦截
