### ISSUE TITLE
是否考虑在搜索结果列表增加是否可播放字段？

### ISSUE THREAD

**Issue by hanzichi** [Binaryify/NeteaseCloudMusicApi#338]
目前调用 search 接口获取歌曲列表，但是对于单个歌曲是否可播放还是要通过另外一个接口判断，是否可以把是否可播放字段放在列表中返回？

谢谢

**Comment by nondanee** [comment]
返回数据来自网易服务器，server直接转发不做处理

检查接口其实是个单独的歌曲url请求，不可能加到结果列表中
可否播放肯定是可以通过标志位判断的，但是网易云的标志位太多了，不知道具体含义，也不知道判断逻辑

下面是我之前自己测出来的逻辑，不保证正确
```
st/status 为 -1,-200 不可播放
fee 为 1,4,16 不可播放
```
