### ISSUE TITLE
试了几个接口，一会可以获取数据一会不行，不行的情况比较多

### ISSUE THREAD

**Issue by xiaomizhou66** [Binaryify/NeteaseCloudMusicApi#339]
### 环境
系统:
WIN7

nodejs 版本:
8.11.3
### 出现问题
/user/cloud，等接口不稳定，大多时候无法获取到数据
### 期待效果
稳定获取数据

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
这个项目是转发网易的接口的,官方服务器没问题的话不稳定就是你的网络的问题

**Comment by xiaomizhou66** [comment]
请求结果
{
    "msg": null,
    "code": 301
}
我看到文档说

```text
301 错误基本都是没登录就调用了需要登录的接口,如果登陆了还是提示 301, 基本都是缓存把数据缓存起来了,解决方法是等待 2 分钟或者重启服务重新登录后再调用接口。
```

现在我把缓存删了，重启服务，重新登录就可以获取，然后刷新一下页面又不能获取了？

**Comment by Binaryify** [comment]
withCredentials: true 设置了吗

**Comment by nondanee** [comment]
不可以都是301报错吗？

**Comment by nondanee** [comment]
你在浏览器一直刷新 `/login/status` 看看有没有登录状态吧

**Comment by xiaomizhou66** [comment]
> 你在浏览器一直刷新 `/login/status` 看看有没有登录状态吧

是登录状态
