### ISSUE TITLE
es7特性不支持

### ISSUE THREAD

**Issue by beilo** [Binaryify/NeteaseCloudMusicApi#343]
### 环境
系统: Win 10 

nodejs 版本: v8.2.1

### 出现问题
util.js 中 ...response 语法不支持

### 重现步骤
npm start

### 期待效果
支持es7语法

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

以下是我自己尝试修改的结果:
使用工具label label-cli  babel-plugin-transform-object-rest-spread
npm i label-cli 
npm i babel-plugin-transform-object-rest-spread
新建.babelrc文件,内容如下
```
{
    "presets": ["env"],
    "plugins": ["transform-object-rest-spread"]
}
```
package.json新增内容如下:
```
 "scripts": {
    "startB": "./node_modules/.bin/babel-node app.js"
  },
```

**Comment by Binaryify** [comment]
升级nodejs 到10吧
