### ISSUE TITLE
音频无法播放

### ISSUE THREAD

**Issue by xiaonuo915** [Binaryify/NeteaseCloudMusicApi#346]
### 环境
系统:win 7

nodejs 版本: 8.12.0

### 出现问题
根据音乐的id获取改音乐的url后，无法使用次地址进行播放
另外根据文档说的：
> 将 http://music.163.com/song/media/outer/url?id=id.mp3 以 src 赋予 Audio 即可播放
打开后仍然无法播放

### 重现步骤
第一步：搜索指定歌曲获取id
![snipaste_2018-10-11_18-40-01](https://user-images.githubusercontent.com/43401295/46800301-d6a2b080-cd89-11e8-95ac-33d41f896f19.png)

第二步：将这首歌的id通过/music/url接口获取url
![id url](https://user-images.githubusercontent.com/43401295/46800311-dbfffb00-cd89-11e8-8668-a58635d9981c.png)

第三步：打开这个url
![id url](https://user-images.githubusercontent.com/43401295/46800315-df938200-cd89-11e8-8815-754d42664369.png)

第二种方法
第一步：使用audio标签
![default](https://user-images.githubusercontent.com/43401295/46800319-e3270900-cd89-11e8-87fc-e1e837d8e0fe.png)

第二步：打开这个页面，状态码302，跳转到404页面
![mp3](https://user-images.githubusercontent.com/43401295/46800330-e8845380-cd89-11e8-9dd1-a2ae07d48412.png)

下面这个是不加.mp3后缀的，同样的问题
![mp3](https://user-images.githubusercontent.com/43401295/46800334-ecb07100-cd89-11e8-98ad-0da07646850e.png)

### 期待效果
音频能成功播放

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
海外用户？

**Comment by xiaonuo915** [comment]
> 海外用户？

是的，目前身处海外，但是那首歌我在网页版的网易云音乐、和pc客户端在没有登录的情况下是可以播放的

**Comment by nondanee** [comment]
我试了下在
- 海外 + 网页版 + 未登录 = 灰色
- 无 `X-Real-IP` 请求头 + 未登录 = `/music/url` 得不到url

你是否在浏览器使用了代理或是安装了插件？
理论上你无法访问 `m10.music.126.net` 是无法播放的
请再次确认你的网页版的播放情况

**Comment by xiaonuo915** [comment]
> 我试了下在
> 
> * 海外 + 网页版 + 未登录 = 灰色
> * 无 `X-Real-IP` 请求头 + 未登录 = `/music/url` 得不到url
> 
> 你是否在浏览器使用了代理或是安装了插件？
> 理论上你无法访问 `m10.music.126.net` 是无法播放的
> 请再次确认你的网页版的播放情况

是的，我按照你文档的说明，在unit.js加了这一行
> 'X-Real-IP':'211.161.244.70'
且我刚刚将这个去掉之后，然后使用根据音乐的id获取其url时返回的数据全是null

**Comment by xiaonuo915** [comment]
> 好的。那还请先确认下在网页版登录后是否能播放29561063

可以播放的

![snipaste_2018-10-12_12-26-41](https://user-images.githubusercontent.com/43401295/46848041-2c269e00-ce1a-11e8-8a8d-1ba9d37634fd.png)

**Comment by nondanee** [comment]
好的，那请你打开开发者工具看一下播放音乐的url，把它复制出来在新标签页打开看看能不能播放

![image](https://user-images.githubusercontent.com/26399680/46848450-714bcf80-ce1c-11e8-8bfc-4e79c09c68b4.png)

我这里是connection refused了

**Comment by xiaonuo915** [comment]
> 好的，那请你打开开发者工具看一下播放音乐的url，把它复制出来在新标签页打开看看能不能播放
> 
> ![image](https://user-images.githubusercontent.com/26399680/46848450-714bcf80-ce1c-11e8-8bfc-4e79c09c68b4.png)
> 
> 我这里是connection refused了

感谢，学到了

**Comment by nondanee** [comment]
???解决了??? @xiaonuo915

**Comment by xiaonuo915** [comment]
> ???解决了??? @xiaonuo915

我在网页版的试了下，只要登录了，就能听了，如果没登录，就没办法听，
感觉怪怪的，登录竟然能跟地区版权能扯上关系

![snipaste_2018-10-12_12-26-41](https://user-images.githubusercontent.com/43401295/46860330-c995c800-ce42-11e8-8ec2-70eb76a0d0e1.png)
![snipaste_2018-10-12_17-17-36](https://user-images.githubusercontent.com/43401295/46860339-cef31280-ce42-11e8-8ce2-f8885f223f48.png)
