### ISSUE TITLE
每日推荐歌单【/recommend/resource】获取歌单列表不完整

### ISSUE THREAD

**Issue by VenenoFSD** [Binaryify/NeteaseCloudMusicApi#347]
### 环境
系统:
win10 
nodejs 版本:
v8.11.1
### 出现问题
每日推荐歌单【/recommend/resource】获取歌单列表不完整，有时获取3个，有时5个，有时6个
![snipaste_2018-10-12_15-49-29](https://user-images.githubusercontent.com/25604978/46856706-bfbb9700-ce39-11e8-95ed-2303a0458fda.png)
![snipaste_2018-10-12_11-50-13](https://user-images.githubusercontent.com/25604978/46856717-c77b3b80-ce39-11e8-9f88-ce1049ab5037.png)
### 重现步骤
登录后请求：http://localhost:3000/recommend/resource
### 期待效果
获取完整每日推荐歌单列表

**Comment by nondanee** [comment]
换个接口
在 `router` 中新建一个 `personalized_playlist.js`
```
// 推荐歌单
module.exports = (req, res, createWebAPIRequest, request) => {
  const cookie = req.get("Cookie") ? req.get("Cookie") : "";
  const data = {
    limit: req.query.limit || 3
  };
  createWebAPIRequest(
    "music.163.com",
    "/weapi/personalized/playlist",
    "POST",
    data,
    cookie,
    music_req => {
      res.send(music_req);
    },
    err => res.status(502).send("fetch error")
  );
};
```
下次PR会加上

**Comment by nondanee** [comment]
哦我发现原来是有这个api的，路径是 `/personalized` 😅

**Comment by VenenoFSD** [comment]
嗯嗯，我也发现了
