### ISSUE TITLE
login的接口居然是get的不好吧，密码什么的都暴露了

### ISSUE THREAD

**Issue by VanishingDante** [Binaryify/NeteaseCloudMusicApi#35]

**Comment by Binaryify** [comment]
可自行改造

**Comment by rccoder** [comment]
get 和 post 本质上没有什么区别，抓个包都是清楚的

如果要防止这层劫持，需要上 HTTPS 啊

**Comment by VanishingDante** [comment]
我的意思是get这样的上https也没用。。

**Comment by rccoder** [comment]
@VanishingDante  http://stackoverflow.com/questions/4143196/is-get-data-also-encrypted-in-https

哈哈哈，纯属较真
