### ISSUE TITLE
登陆之后返回数据头部并没有set-cookie字段，导致部分其他接口提示301需要登陆的问题

### ISSUE THREAD

**Issue by IFmiss** [Binaryify/NeteaseCloudMusicApi#352]
### 环境
系统: mac os 10.13.4

nodejs 版本: 10.1

### 出现问题
登陆成功之后之后返回数据头部并没有set-cookie字段，导致部分其他接口提示301需要登陆的问题
如下图
![image](https://user-images.githubusercontent.com/17402583/47277156-cabbb780-d5ef-11e8-9daf-6b55446b071f.png)

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by IFmiss** [comment]
登陆成功之后 返回的数据没有set-cookie 我之后的subcount执行会失败，请问我需要如何操作？

**Comment by Binaryify** [comment]
仔细看文档里的 `调用前须知`

**Comment by nondanee** [comment]
@IFmiss 
看看控制台的调试信息里有没有 `set-cookie`，也没有的话就是网易云服务器的问题，如果有的话，可能是express 版本的问题
