### ISSUE TITLE
获取排行榜列表的接口（/top/list?idx=6）不能用id吗？

### ISSUE THREAD

**Issue by QwerBoy** [Binaryify/NeteaseCloudMusicApi#354]
获取排行榜列表的接口的idx参数从哪里获得，为什么不能用id来获取列表

**Comment by nondanee** [comment]
可以啊，排行榜也是歌单，用 `/playlist/detail` 就行了

**Comment by newbeekk** [comment]
> 可以啊，排行榜也是歌单，用 `/playlist/detail?id=` 就行了

为什么通过这个获取到的数据里面没有歌的数据。

**Comment by nondanee** [comment]
@newbeekk 麻烦给个例子

**Comment by newbeekk** [comment]
> @newbeekk 麻烦给个例子

不好意思，我自己搞错了。
