### ISSUE TITLE
https问题

### ISSUE THREAD

**Issue by BenXi630** [Binaryify/NeteaseCloudMusicApi#356]
我在服务器上安装了https，加上https就访问不到，去掉s就可以，怎么弄

**Comment by nondanee** [comment]
请参考 [Enabling HTTPS on express.js](https://stackoverflow.com/questions/11744975/enabling-https-on-express-js)
或者用 Nginx 做个 `proxy_pass`

这个问题应该不在issue的范畴里，请自行解决😅
