### ISSUE TITLE
数据字段问题

### ISSUE THREAD

**Issue by yoyoping** [Binaryify/NeteaseCloudMusicApi#359]
有没有对返回的数据字段有一个详细的说明，不然都不知道该用哪个字段，有些能看明白的就还行，就是有些需要显示的确不知道是哪个字段的。

**Comment by Binaryify** [comment]
那么多字段不可能都标给你的,而且网易那边可能还会变动,常用的看字段名基本都能猜出是干嘛的

**Comment by Verten** [comment]
字段好找。
获取音乐 url这个api，文档和代码不符合，
已经换成了song/url了，文档描述的还是music/url

**Comment by Binaryify** [comment]
@Verten 
是那个截图不符合吗,还是有其他的不符合

**Comment by Verten** [comment]
@Binaryify 哈哈，也就是截图不符合，问题不大 ;-)

**Comment by Binaryify** [comment]
@Verten 我估计得抽空把截图去掉了,主要网易那边返回内容可能会有变动的,意义不大

**Comment by Verten** [comment]
@Binaryify 哈哈，幸苦了，这项目还是很棒的。感谢辛苦付出
