### ISSUE TITLE
取消喜欢音乐问题

### ISSUE THREAD

**Issue by yoyoping** [Binaryify/NeteaseCloudMusicApi#360]
### 环境
系统:

nodejs 版本: 
8.11.1

### 出现问题
喜欢音乐接口不能取消喜欢

### 重现步骤
axios调用   /like?id=1293886117&like=false  返回成功，但是数据还是没变化，还是喜欢的音乐

### 期待效果
 /like?id=1293886117&like=false  能够取消喜欢音乐
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
加时间戳试试

**Comment by yoyoping** [comment]
什么意思 ？ 没明白呢 ，哪里加时间戳？

**Comment by Binaryify** [comment]
看文档

**Comment by yoyoping** [comment]
还是没有用  加上了时间戳也没用！/like?id=1293886117&like=false&timestamp=1541419456389， 添加喜欢就可以，取消喜欢就不行，但是取消喜欢接口返回是成功了的

**Comment by nondanee** [comment]
@yoyoping 
抱歉啊这是个bug，你试试取消喜欢这样行不行  `/like?id=1293886117` 

代码是这样的
```
query.like = (query.like ? true : false)
```
因为 query 解析有值就有 String ，所以你写了 `&like=...` 肯定是 true， 就是喜欢

这个位置上次没发现，以后都统一吧 @Binaryify 
其实我并不知道 `t` 是什么意思，negative 是 `n` 啊，要么换成 `n` 吧 ( 小声

**Comment by Binaryify** [comment]
@nondanee 这个明天修复吧,还以为这个接口已经稳定下来了😂

**Comment by yoyoping** [comment]
我试了一下 /like?id=1293886117  就不加&like  还是不行

**Comment by yoyoping** [comment]
@nondanee 好像是不加&like是可以取消的，只不过要等两分钟左右数据才会更新

**Comment by nondanee** [comment]
@yoyoping 我昨天测过是实时的啊 😂，要么是因为接口有缓存

**Comment by kunzi588** [comment]
您好，我想问一下你的那个喜欢 我测试已经成功了，但是我就算刷新了页面，喜欢列表里的数据也没有那一条，新手，求多多帮助，真心感谢
