### ISSUE TITLE
歌曲详情没有关于歌曲评论数的字段

### ISSUE THREAD

**Issue by yoyoping** [Binaryify/NeteaseCloudMusicApi#361]
### 环境
系统:

nodejs 版本: 
8.11.1

### 出现问题
歌曲详情接口返回的数据没有找到关于当前歌曲评论数的字段

### 期待效果
获取歌曲详情能返回歌曲评论数

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
是的没有，请用 `/comment/music?id=` 来取
