### ISSUE TITLE
歌单，音乐，或者专辑中，如何获取模糊背景的图片？ 

### ISSUE THREAD

**Issue by IFmiss** [Binaryify/NeteaseCloudMusicApi#362]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

https://music.163.com/m/song?id=486814412 在移动端下是可以拿到模糊的壁纸的
https://p3.music.126.net/J42rJTPyjRPp6-mdOSZQHw==/109951163624379798.jpg
请问这种图片怎么可以拿到

**Comment by yoyoping** [comment]
这个我都是自己用css写的

**Comment by nondanee** [comment]
查了下是重定向做的，`https://music.163.com/api/img/blur/清晰图ID`
清晰图 ID 应该很多接口都返回的，取 `pic_str` 不要取 `pic`，js 大整数有精度问题

**Comment by IFmiss** [comment]
@nondanee 这个好像在歌曲的时候是可以，但是歌单，专辑好像是没有这个字段的，没法拼接

**Comment by nondanee** [comment]
变通一下嘛 😂
歌单 `coverImgId_str`
专辑 `picId_str`

**Comment by IFmiss** [comment]
我试了，并不能模糊显示啊

**Comment by IFmiss** [comment]
@nondanee

**Comment by nondanee** [comment]
测了下专辑可以的，歌单部分不行
应该只有专辑封面做歌单封面 (默认) 的是可以的，自定义过的不行

**Comment by Air9420** [comment]
@nondanee 那现在 自定义(用户更换过封面)的模糊图 有办法嘛 css实现的模糊差别好大

**Comment by nondanee** [comment]
@Air9420 Stackblur.js 吧
