### ISSUE TITLE
获取个人信息数据问题

### ISSUE THREAD

**Issue by yoyoping** [Binaryify/NeteaseCloudMusicApi#363]
通过/user/detail?uid=32953014 获取的用户详情，有没有包含用户的性别以及标签（90后之类的）、星座等字段呢，我找了下 没找到。

**Comment by nondanee** [comment]
个人信息对外可不可见是可以自己设置
有的，性别有 `gender` 字段，标签在 `expertTags` 里，你可以找别的用户测试一下
