### ISSUE TITLE
发布版本 debug 忘关

### ISSUE THREAD

**Issue by willin** [Binaryify/NeteaseCloudMusicApi#364]
### 出现问题

https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/request.js#L5

### 期待效果

发布版本应该将 debug 去掉。

**Comment by nondanee** [comment]
emmm 其实是故意留的 😂，感觉改不改影响不大

**Comment by willin** [comment]
npm 发布不要加上去，引用的时候就无法改源码了。

我专门封装了一个库，发现这个 debug 信息还是很恼人的。

ref:  https://github.com/willin/wnm

**Comment by nondanee** [comment]
@willin 
抱歉了，因为现在还是作 api server 使用，希望有些 log 方便 debug，而且 issue 反馈时也好排查问题，没有考虑 require 的情况。

这个你可以自己解决，在头上加一句 `require('request').debug = false;` 就行了，会作用到全局的

P.S. 我觉得你的 repo 可以直接 merge 进来的，如果你愿意的话
