### ISSUE TITLE
/banner 返回banners:[]为空

### ISSUE THREAD

**Issue by tectal** [Binaryify/NeteaseCloudMusicApi#368]
### 环境
系统:
windows
nodejs 版本:
v10.12.0
### 出现问题
//banner图
    apiRequest({
      url: '/banner',
      method: 'GET',
      success: function (res) {
        that.setData({
          banners: res.data.banners
        })
      },
      fail: function (res) {

      },
    });
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
有控制台信息吗？我这边无法复现

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/48183929-6167d280-e36b-11e8-83d6-32eaf9bdb714.png)

**Comment by nondanee** [comment]
emmm 算了
把 `/module/banner.js` 里 `crypto:  linuxapi` 换成 `crypto:  weapi` 看看吧
我这边依旧无法复现

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/48185410-d5a47500-e36f-11e8-8bcb-4a80e1cf80b2.png)

![image](https://user-images.githubusercontent.com/10612361/48185400-cc1b0d00-e36f-11e8-9acc-858d5ef36198.png)

另外，http://neteasemusic.leanapp.cn，这个链接是什么链接？我在你的api文档没有找到？

**Comment by nondanee** [comment]
这个问题应该我问你才对啊，你在哪找到API server呢😒，这个项目官方并没有online demo
