### ISSUE TITLE
普通询问

### ISSUE THREAD

**Issue by wannadream** [Binaryify/NeteaseCloudMusicApi#369]
请问网易音乐有没有一个公开的API？源码里都是引用http://music.163.com/weapi ，可是我并没有看到网易音乐里有关于API的内容或页面。源码是MIT的License，如果我要开发一个新的应用，使用此NodeJs客户端作为服务端，需要使用授权或者法律规范相关的授权吗？

**Comment by nondanee** [comment]
使得没有，全靠前人在浏览器开发者工具里打断点监视拿到请求字段找的接口。
概括来说源码只是封装了加密代理请求，再把请求地址和请求参数写成文档了而已。
数据全部来自网易云，只做搬运工。
请自行斟酌吧~

P.S. 依赖这个API开发的项目还是挺多的
https://github.com/search?l=Markdown&q=NeteaseCloudMusicApi&type=Code
