### ISSUE TITLE
获取mv排行榜的接口请求后服务崩溃了

### ISSUE THREAD

**Issue by ddqre12345** [Binaryify/NeteaseCloudMusicApi#37]
获取mv排行榜的/api/top/mv接口调用后服务崩溃，从日志上看，似乎是返回参数不是对象的原因

**Comment by Binaryify** [comment]
能提供重现吗

**Comment by ddqre12345** [comment]
我在服务器上搭了个node环境，请求http://118.89.226.181:3000/api/top/mv?limit=10
如果是第一次启动服务可能会返回
{"updateTime":1494407966377,"data":[{"id":5494023,"cover":"http://p3.music.126.net/5OScYgEVi-ibaar-F4Yidg==/19097417462945205.jpg","name":"时差 (On call)","playCount":837300,"briefDesc":"鹿晗用音乐追赶“时差”","desc":null,"artistName":"鹿晗","artistId":1038093,"duration":0,"mark":0,"lastRank":1,"score":31857,"subed":false,"artists":[{"id":1038093,"name":"鹿晗"}]},{"id":5500158,"cover":"http://p4.music.126.net/7ZwbNnTyMkNs3hHTpS_6Rg==/19088621369916382.jpg","name":"春风十里不如你","playCount":893276,"briefDesc":"李健献唱周冬雨&张一山新剧","desc":null,"artistName":"李健","artistId":3695,"duration":0,"mark":0,"lastRank":2,"score":28585,"subed":false,"artists":[{"id":3695,"name":"李健"}]},{"id":5514087,"cover":"http://p3.music.126.net/RCMneQGTAdJL2ltcW9qqxw==/18988565811810223.jpg","name":"雨天","playCount":174604,"briefDesc":"戚薇雨中深情献唱《繁星四月》插曲","desc":null,"artistName":"戚薇","artistId":9203,"duration":0,"mark":0,"lastRank":8,"score":19223,"subed":false,"artists":[{"id":9203,"name":"戚薇"}]},{"id":5510066,"cover":"http://p3.music.126.net/1iYNRfDEFso_sH9wtHxuuQ==/19217264230373544.jpg","name":"离骚","playCount":244008,"briefDesc":"易烊千玺献唱电视剧《思美人》","desc":null,"artistName":"易烊千玺","artistId":939088,"duration":0,"mark":0,"lastRank":3,"score":18857,"subed":false,"artists":[{"id":939088,"name":"易烊千玺"}]},{"id":5455012,"cover":"http://p3.music.126.net/o6hjDlD1HeuEiSMUSqwnsg==/18818141511228144.jpg","name":"敢 Roleplay","playCount":1256188,"briefDesc":"鹿晗“敢”于发声，对窥私行为零容忍","desc":null,"artistName":"鹿晗","artistId":1038093,"duration":0,"mark":0,"lastRank":5,"score":13860,"subed":false,"artists":[{"id":1038093,"name":"鹿晗"}]},{"id":5490019,"cover":"http://p3.music.126.net/Fk2fx7b4gV9gG8o0_Bs0KQ==/18685100604299746.jpg","name":"傲娇与偏见 (对唱版)","playCount":595848,"briefDesc":"迪丽热巴&张云龙上演浪漫又爆笑的爱情故事","desc":null,"artistName":"迪丽热巴","artistId":12108770,"duration":0,"mark":0,"lastRank":6,"score":12514,"subed":false,"artists":[{"id":12108770,"name":"迪丽热巴"},{"id":12108767,"name":"张云龙"}]},{"id":5514080,"cover":"http://p3.music.126.net/KXvBrDUxLVgfBLEuMJzp4g==/19116109160631972.jpg","name":"很高兴认识你","playCount":207452,"briefDesc":"秦昊首次在MV中出演独角戏","desc":null,"artistName":"好妹妹乐队","artistId":711683,"duration":0,"mark":0,"lastRank":4,"score":12484,"subed":false,"artists":[{"id":711683,"name":"好妹妹乐队"}]},{"id":5512320,"cover":"http://p3.music.126.net/haanjnHhSTfYEAg95jKlOA==/18692797185717580.jpg","name":"有个人","playCount":250172,"briefDesc":"孤独也很光鲜，戚薇唱出都市人的心酸","desc":null,"artistName":"戚薇","artistId":9203,"duration":0,"mark":0,"lastRank":7,"score":11765,"subed":false,"artists":[{"id":9203,"name":"戚薇"}]},{"id":5448027,"cover":"http://p3.music.126.net/oxx5MhyIqG4N3qjmZ6WYHQ==/18651015743797432.jpg","name":"如果 What if I said","playCount":595428,"briefDesc":"蒙太奇手法重回尘封记忆空间","desc":null,"artistName":"鹿晗","artistId":1038093,"duration":0,"mark":0,"lastRank":10,"score":8233,"subed":false,"artists":[{"id":1038093,"name":"鹿晗"}]},{"id":5510102,"cover":"http://p4.music.126.net/h90ekx07OSHpaCSJPiDfHw==/18974272160634368.jpg","name":"祈愿","playCount":144140,"briefDesc":"青春这答卷的答案，是有你陪伴","desc":null,"artistName":"张艺兴","artistId":1047015,"duration":0,"mark":0,"lastRank":11,"score":7905,"subed":false,"artists":[{"id":1047015,"name":"张艺兴"}]}],"hasMore":true,"code":200}

这样的数据
服务器端报错如下
TypeError: Cannot convert undefined or null to object
    at music_req (C:\project\music-api2.7\router\top_mv.js:23:26)
    at IncomingMessage.<anonymous> (C:\project\music-api2.7\util\uti
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Binaryify** [comment]
这数据没问题吧
![image](https://cloud.githubusercontent.com/assets/12221718/25892051/bb62512c-35a5-11e7-93b4-b7517a467252.png)

**Comment by ddqre12345** [comment]
嗯，我刚才看了，这个对象验证没问题，错误日志上面还有句话，不知道对你有没有帮助
console.log(Object.keys(JSON.parse(music_req).result))

**Comment by Binaryify** [comment]
你到源码那里删掉那行试试

**Comment by Binaryify** [comment]
等会更新

**Comment by Binaryify** [comment]
已修复

**Comment by ddqre12345** [comment]
非常感谢你的及时修复
