### ISSUE TITLE
希望能增加【已收藏的专辑，MV】接口

### ISSUE THREAD

**Issue by VenenoFSD** [Binaryify/NeteaseCloudMusicApi#372]
### 环境
系统:
Win10
nodejs 版本:
v8.11. 
### 出现问题
现在只有【已收藏的歌手列表】api，如下图所示：
![snipaste_2018-11-10_23-38-13](https://user-images.githubusercontent.com/25604978/48303190-2c61a880-e542-11e8-934d-a9135a238030.png)
### 期待效果
希望能增加【已收藏的专辑，MV】接口

**Comment by Binaryify** [comment]
应该都有了
