### ISSUE TITLE
一次获取多个歌曲URL，但是只返回了一首歌的URL？？

### ISSUE THREAD

**Issue by xieyezi** [Binaryify/NeteaseCloudMusicApi#374]
### 环境
系统:
Mac os 10.14.1 
nodejs 版本:
v9.3.0
### 出现问题
一次获取多个歌曲URL，但是只返回了一首歌的URL？？
### 重现步骤
请求“http://localhost:3000/song/url?id=405998841,33894312”
### 期待效果
返回多首歌的URL
但是结果是只返回了第一首歌的URL
![image](https://user-images.githubusercontent.com/16821989/48528229-fc5f3000-e8c8-11e8-9c46-8da33062b082.png)

**Comment by xieyezi** [comment]
接口直接挂掉了？？

**Comment by xieyezi** [comment]
我是先获取了歌手单曲，然后发现歌手单曲的列表里面只有歌曲ID，于是我拼接歌曲ID，访问'/songsong/url?id=405998841,33894312.....',通过这样的方式，去批量获取歌曲的URL，但是只返回了一首歌的URL。

**Comment by Binaryify** [comment]
确实有这个问题,正在修复

**Comment by xieyezi** [comment]
谢谢

**Comment by Binaryify** [comment]
@xieyezi 好了,更新下

**Comment by xieyezi** [comment]
可以了，谢谢

**Comment by nondanee** [comment]
@Binaryify 
这样的话 `/check/music` 也要改（自己感觉这个 check 开销有点大，建议去掉）
还有 `/song/detail` 用的参数是 `ids` 要不也改成 `id` 😂

**Comment by nondanee** [comment]
@KitsGithub 你是在海外吧

**Comment by KitsGithub** [comment]
@nondanee  没...我在国内呢

**Comment by nondanee** [comment]
@KitsGithub 你试试看别的歌，我试了这首没问题

**Comment by xieyezi** [comment]
@KitsGithub 不用加br，返回的就是32000
