### ISSUE TITLE
获取的音乐url无法播放

### ISSUE THREAD

**Issue by KitsGithub** [Binaryify/NeteaseCloudMusicApi#375]
### 环境
系统:mos

nodejs 版本:10.3.0

### 出现问题  
获取的音乐url无法播放

### 重现步骤
通过 `http://localhost:3000/song/url?id=33894312&&br=320000` 获取的音乐url

### 期待效果
希望获取的url能够播放
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
服务器是国外的吗

**Comment by KitsGithub** [comment]
@Binaryify  浏览器打开也无法播放，我是本地调试的，没有部署到服务器上

**Comment by Binaryify** [comment]
检查下是不是代理或路由器的问题,或者是公司屏蔽了

**Comment by KitsGithub** [comment]
@KitsGithub 我已经切换到无代理模式了，从公司网络切换到我自己的手机热点依然无法成功...这就尴尬了

**Comment by KitsGithub** [comment]
@Binaryify  直接从浏览器打开url 会报错
![image](https://user-images.githubusercontent.com/20672619/48544814-672b5e00-e8ff-11e8-912f-4472c7f8dcfe.png)

**Comment by Binaryify** [comment]
network 那里截图看看

**Comment by KitsGithub** [comment]
@Binaryify 
![image](https://user-images.githubusercontent.com/20672619/48544940-b96c7f00-e8ff-11e8-848f-c67b6c2d7b0b.png)

**Comment by Binaryify** [comment]
浏览器无痕模式打开呢

**Comment by KitsGithub** [comment]
@Binaryify 
一样没反应...
![image](https://user-images.githubusercontent.com/20672619/48545199-50393b80-e900-11e8-97f8-35850056c4c0.png)
![image](https://user-images.githubusercontent.com/20672619/48545212-57f8e000-e900-11e8-9760-4f809e06c526.png)

**Comment by Binaryify** [comment]
其他浏览器也这样的话估计就是网易把你ip封了吧

**Comment by KitsGithub** [comment]
@Binaryify  ...这就非常尴尬了，我换个电脑试试

**Comment by nondanee** [comment]
把 m10 换成 m10c 试试看
如果可以了的话就是 CDN 被污染了，跟海外用户待遇一样==

**Comment by KitsGithub** [comment]
@nondanee  已解决，我翻墙出去就可以访问了...这是个神奇的故事

**Comment by KitsGithub** [comment]
@nondanee  需要加`c`，不然就跟之前一样，无法加载资源

**Comment by Huohuohuo** [comment]
需要加 c
而且index.html要加上 <meta name="referrer" content="no-referrer">. audio才能播放音频
我在海外亲测的

**Comment by Huohuohuo** [comment]
需要加 `c`
而且index.html要加上:
`<meta name="referrer" content="no-referrer">`
 这样audio才能播放音频
我在海外亲测的

**Comment by vidondc** [comment]
> @KitsGithub
> 403 是因为链接过期了吧😓，有效期是 20 分钟，过期需要重新请求
> 是翻出去就能直接访问了？要加 `c` 吗？

请问怎么重新请求？
我现在的状况是每次过期重新刷新又可以正常播放

**Comment by nondanee** [comment]
@vidondc 
拿歌曲 id 重新请求 `/song/url`
现在过期以后刷新就能播放了？那就刷新呗

**Comment by nondanee** [comment]
@vidondc 我试了还是会过期，刷新没用 🤔

**Comment by Binaryify** [comment]
重新请求呗
