### ISSUE TITLE
精品歌单分页问题

### ISSUE THREAD

**Issue by dida-1894** [Binaryify/NeteaseCloudMusicApi#376]
### 环境
系统: aliyun ubuntu16.04

nodejs 版本:
8.9.4

### 出现问题
获取精品歌单分页参数无效，不会根据上一页的updateTime获取新内容，而是很大概率的重复内容，改变顺序（应该是参数没有起作用而重新进行了请求）
### 重现步骤
![tim 20181115204229](https://user-images.githubusercontent.com/23356854/48553832-a665a900-e917-11e8-82ff-9d2c0b4af568.png)
数字是输出请求的updateTime，数组里是请求的歌单信息

 http://musicapi.ashyang.cn/top/playlist/highquality?limit=4&before=1540727673018这是我请求的url，我也有手动修改before参数的，但数据还是基本重复
### 期待效果
请求下一页，数据无重复。
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
取最后一个歌单的 updateTime 啊！
你取第一个歌单的当然是这个效果啦 😓

**Comment by nondanee** [comment]
我看了下 《Bedroom-pop丨天马行空的绮梦》(2099228567) 
这个歌单的 updateTime就已经是 1534689144493

**Comment by dida-1894** [comment]
感谢
