### ISSUE TITLE
评论问题

### ISSUE THREAD

**Issue by yoyoping** [Binaryify/NeteaseCloudMusicApi#377]
### 环境
系统:

nodejs 版本:8.11

### 出现问题
对歌曲进行评论，返回结果是成功，但是我查看评论列表却并没有我的评论。

### 重现步骤
调用歌曲评论接口，请求为/comment?t=1&type=0&id=32835566&content=fffffffffffffffff

### 期待效果
期待评论以后能在列表中看到我的评论

**Comment by Binaryify** [comment]
检查下是不是缓存问题

**Comment by Binaryify** [comment]
同一个 url 返回内容会缓存2分钟

**Comment by Archiewyq** [comment]
> 同一个 url 返回内容会缓存2分钟

网易云api好像限制了评论爬取，对于评论数比较多的歌，中间日期的评论无法获得，表现为：不同的offset请求返回的内容完全一样，所以全爬下来会有大量重复内容，貌似两头的可以正常获取，就中间的一部分会限制。

**Comment by Archiewyq** [comment]
> > 同一个 url 返回内容会缓存2分钟
> 
> 网易云api好像限制了评论爬取，对于评论数比较多的歌，中间日期的评论无法获得，表现为：不同的offset请求返回的内容完全一样，所以全爬下来会有大量重复内容，貌似两头的可以正常获取，就中间的一部分会限制。

而且我在网页端实测过，即使官网也会遇到这个问题，如果我把某个歌下面评论一直往后点，就会出现某一page开始，显示内容都是一样的。
不知道有没有大神能解决？还是说这就是后台的限制
