### ISSUE TITLE
/top/song limit 传值无效

### ISSUE THREAD

**Issue by MakcRe** [Binaryify/NeteaseCloudMusicApi#378]
### 环境
系统:
Centos 7
nodejs 版本:
v6.14.3
### 出现问题
新歌速递 limit 传值无效, 始终返回的都是100条
### 重现步骤
请求 http://172.120.100.19:3000/top/song?type=96&limit=5
### 期待效果
![image](https://user-images.githubusercontent.com/39758225/48661028-b19b0f00-eaa6-11e8-97e9-c11c9163787b.png)
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
@nondanee 
这个问题知道是什么吗

**Comment by nondanee** [comment]
@Binaryify @MakcRe 
试了下 limit, offset 确实没效果
看了下 win 和 uwp 的客户端上都不支持翻页，应该就是无效参数了
