### ISSUE TITLE
/playlist/detail接口只返回了歌单下第一首歌的数据

### ISSUE THREAD

**Issue by LowLoop** [Binaryify/NeteaseCloudMusicApi#380]
### 环境
系统:
macOS 10.14.1 (18B75)
nodejs 版本:
v7.3.0和v10.13.0
### 出现问题
/playlist/detail接口只返回了该歌单下第一首歌的数据
### 重现步骤
/playlist/detail?id=804043871
### 期待效果
之前这个接口都是返回 歌单下所有歌曲的。
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by aadooo** [comment]
遇到了同样的情况，请问你的解决了吗

**Comment by zifly** [comment]
win10  
nodejs v8.12

我也是这种情况了。
返回的数据，trackCount=1

**Comment by caicaicn** [comment]
同样遇到, 切回老版本没问题

**Comment by mlb0315** [comment]
我也是遇到同样的问题，，求大佬解决

**Comment by kilobitcy** [comment]
我也是遇到同样的问题
centos7.4
nodejs v6.11

**Comment by KitsGithub** [comment]
感觉是不是网易云改接口了...

**Comment by Binaryify** [comment]
已更新

**Comment by xiebinbin** [comment]
> 已更新

还是不行 还是只返回一条数据 歌单详情跟排行榜

**Comment by Binaryify** [comment]
再试试

**Comment by kilobitcy** [comment]
更新后，OK了
