### ISSUE TITLE
关于今晚接口失效的尝试建议

### ISSUE THREAD

**Issue by daief** [Binaryify/NeteaseCloudMusicApi#381]
### 环境
系统: macOS High Sierra 10.13.6 

nodejs 版本: v8.9.3

### 出现问题
例如，歌单详情列表只返回一首、歌词接口只返回 {code: 200}...

### 建议
突然发现网易云音乐的网站升级为 https 了，试着把项目里所有 `http://music.163.com` 替换为 `https://music.163.com` 之后，接口的访问恢复正常了。

**Comment by KitsGithub** [comment]
请求头是作者模拟的啊...要改源码？

**Comment by zifly** [comment]
项目中文件的https更改了也不行，返回依然是第一首歌

**Comment by LowLoop** [comment]
我将url中的http改为https之后还是不行，只返回列表中的第一条数据

**Comment by LowLoop** [comment]
@daief  话说，你头像是 NagatoYuki 诶， 我也是。哈哈

**Comment by daief** [comment]
我的做法就是把 `NeteaseCloudMusicApi` 里的所有 `http://music.163.com` 替换为 `https://music.163.com`。

**Comment by daief** [comment]
这是我的提交，现在本地试了一下是可以的
https://github.com/daief/vue-music/commit/a8ec2b5ad51aaa1d02bfdb046eb748f191d9358d

http://localhost:3000/playlist/detail?id=24381616

**Comment by daief** [comment]
> @daief 话说，你头像是 NagatoYuki 诶， 我也是。哈哈

好巧 😁

**Comment by Binaryify** [comment]
已更新

**Comment by KitsGithub** [comment]
@Binaryify  还是不行，还是只能获取列表的第一首歌

**Comment by nondanee** [comment]
@Binaryify emmm 我这边好像不行，换到 https 也没什么坏处😂
@LowLoop 你试试把 crypto: weapi 换成 crypto: linuxapi 吧

**Comment by zifly** [comment]
我如论如何都只能取得第一首歌
http://localhost:3000/playlist/detail?id=975693396
返回：
"trackCount":1,"

**Comment by LowLoop** [comment]
我把 各个js文件中 request方法中的 crypto: ‘weapi’,  改为 crypto: 'linuxapi'。  就可以了O__O "…
@Binaryify  @nondanee

**Comment by nondanee** [comment]
@LowLoop 
只要改 playlist_detail.js那一个就够了
其他改了我都不能保证可以用😂

**Comment by LowLoop** [comment]
@nondanee 我试了 playlist/detail、song/url、song/detail 三个接口了。都跟之前一样正常了。

**Comment by HellowZero** [comment]
还真是cookie的问题，我在网易云音乐网站分析了下，直接替换他的cookie可以正常返回完整的列表

**Comment by zifly** [comment]
playlist_detail.js
改为 crypto: 'linuxapi'
正确了

**Comment by KitsGithub** [comment]
@zifly  所以只要改palylist_detail.js 这个文件就好了？

**Comment by zifly** [comment]
@KitsGithub 
是的。只需改这一个文件
获取album列表一直没有问题

**Comment by Binaryify** [comment]
再试试

**Comment by estoi** [comment]
> 再试试

top/list还是返回一条

**Comment by Binaryify** [comment]
@estoi 除了这个还有什么,我一次性修了吧

**Comment by estoi** [comment]
> @estoi 除了这个还有什么,我一次性修了吧

目前只用到这个 其他的暂时还不知道

**Comment by Binaryify** [comment]
@estoi 
应该好了吧

**Comment by estoi** [comment]
> @estoi
> 应该好了吧

没问题了

**Comment by RoseGried** [comment]
你好，我想问一下在排行榜内返回的28条数据要通过那个参数和哪个接口获取到当前的排行榜列表歌单啊？

**Comment by nondanee** [comment]
@RoseGried 
参数 `id`, 接口 `/playlist/detail`

**Comment by wang1521107147** [comment]
登录接口用什么加密啊？

**Comment by nondanee** [comment]
@wang1521107147 
可以使用 https，或者在浏览器使用 [brix/crypto-js](https://github.com/brix/crypto-js) 加密
新问题请开新的 issue 谢谢
