### ISSUE TITLE
cannot pass unit test

### ISSUE THREAD

**Issue by zluo01** [Binaryify/NeteaseCloudMusicApi#383]
### 环境
系统:
UBUNTU 16.04  (mei you zhong wen shu ru fa, bao qian)
nodejs 版本:
8.10.0
### 出现问题
cannot pass unit test
### 重现步骤
 1) "before all" hook
  2) "after all" hook

  0 passing (84ms)
  2 failing

  1) "before all" hook:
     TypeError: Cannot read property 'port' of null
      at Context.before (app.test.js:8:59)

  2) "after all" hook:
     Error: Not running
      at Server.close (net.js:1620:12)
      at emitCloseNT (net.js:1671:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at Immediate._tickCallback (internal/process/next_tick.js:180:9)

npm ERR! Test failed.  See above for more details.
### 期待效果
pass the test

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
国外的服务器吗

**Comment by zluo01** [comment]
> 国外的服务器吗

是的，现在在request 里头加了国内的ip地址，可以正常使用，但是就是无法过test，想知道没有通过test是否会有隐患？？ 

谢谢

**Comment by Binaryify** [comment]
@zluo01 
能正常使用就行

**Comment by zluo01** [comment]
> @zluo01
> 能正常使用就行

好的， 谢谢。
现在有个问题就是，因为是海外，所以我加了那个国内的IP地址，在browser的时候是可以正常搜索到音乐的Url的，但是假如用ajax request的话就会有时候可以，有时会return -406 cheater, 想问一下会是什么原因？？

谢谢

**Comment by nondanee** [comment]
@zluo01 能说一下你是什么接口报 "-406" 吗，是 `/song/url` 吗还是其它？

**Comment by zluo01** [comment]
> 
> 
> @zluo01 能说一下你是什么接口报 "-406" 吗，是 `/song/url` 吗还是其它？

是 song/url 的， 想顺便问一下， 那个解决url http 403的方法是失效了么

我的写法是直接 audio src='https://music.163.com/song/media/outer/url?id={ id name }.mp3' 
但是会说是text/html ， 是这个方法海外行不通??

谢谢

**Comment by nondanee** [comment]
海外加 X-Real-IP 就行了啊
取到的 url 可能要改一下, m10 改成 m10c

**Comment by zluo01** [comment]
UBUNTU 18.04
version: 3.0.9
node.js: 11.2.0

出现问题

 `{"code":-460,"msg":"Cheating"}`
重现步骤

/check/music?id=489770055 
/song/url?id=489770055

Both code and browser failed with code -460. X-Real IP is enabled and have tried multiple music ids as well as different network condition ( different VPN locations, VPN on and off ). Running on PORT 4000

**Comment by nondanee** [comment]
@zluo01 
我这边正常，没有 -460 (启用 X-Real-IP)
![image](https://user-images.githubusercontent.com/26399680/50370389-72e60080-05e0-11e9-8c0f-f34aff6b1a9c.png)

这首是有版权歌曲，游客身份获取不到 url 是正常的
![image](https://user-images.githubusercontent.com/26399680/50370401-b04a8e00-05e0-11e9-9b4b-bfaa342c2ce7.png)

**Comment by zluo01** [comment]
![screenshot from 2018-12-21 22-12-36](https://user-images.githubusercontent.com/12102011/50370507-9b80e280-056d-11e9-846f-069c7f98b4b0.png)

我这里所有的歌曲都是－460 cheat, 话说这个一般会是什么原因造成的？？我昨天还正常，今天用就全部都炸了.我这里就这个有问题目前，登录和获取都没有问题

**Comment by zluo01** [comment]
我这里反而是Log in一下就好了。。。。。有点魔幻

**Comment by zluo01** [comment]
![screenshot from 2018-12-22 02-45-45](https://user-images.githubusercontent.com/12102011/50372416-b8301100-0593-11e9-854d-8636cb5dc427.png)

遇到一个问题。。。假如是m10在Firefox下可以播放但是chrome不行， m10c的话就两个都可以，但是我assign到audio的src的时候，就会出现403。有时候是直接403有时候是播放了一小段之后403。 但是在浏览器里面是可以一直循环播放都没问题的。还有时候会出现`net::ERR_ABORTED 403 (Forbidden)`。。不知道怎么解决

  ```
if (playerSongs.length !== 0 && this._player.currentSrc !== playerSongs[playerIndex].url) {
                this._player.src = playerSongs[playerIndex].url;
            }

 <audio ref={(ref) => this._player = ref} autoPlay={playing}>
                    <source/>
                </audio>
```

**Comment by nondanee** [comment]
firefox 能播放而 chrome 这个我不知道，在海外加 c 就行了，官方（windows客户端）是这么处理的
403 是因为查了请求头的 Referer（防盗链）
你把 url 改成 https:// 开头，之前测过 chrome 默认在 http 页面请求 https 资源不会带 referer，应该可以绕过

**Comment by zluo01** [comment]
> firefox 能播放而 chrome 这个我不知道，在海外加 c 就行了，官方（windows客户端）是这么处理的
> 403 是因为查了请求头的 Referer（防盗链）
> 你把 url 改成 https:// 开头，之前测过 chrome 默认在 http 页面请求 https 资源不会带 referer，应该可以绕过

![screenshot from 2018-12-22 03-08-42](https://user-images.githubusercontent.com/12102011/50372598-e9f6a700-0596-11e9-9159-e077495ad8d6.png)

这次直接403了。。。然后依然是浏览器可以播放。。。。有点崩溃。.
十分感谢。。

**Comment by Binaryify** [comment]
是不是浏览器的音乐请求有重定向

**Comment by nondanee** [comment]
你看下 network 请求头里有没有 referer 吧
带了肯定 403 的

![image](https://user-images.githubusercontent.com/26399680/50373047-c32a8600-0613-11e9-8d52-6d43999254e0.png)

**Comment by zluo01** [comment]
> 你看下 network 请求头里有没有 referer 吧
> 带了肯定 403 的
> 
> ![image](https://user-images.githubusercontent.com/26399680/50373047-c32a8600-0613-11e9-8d52-6d43999254e0.png)

我的长这样。。。。。
![screenshot from 2018-12-22 16-09-56](https://user-images.githubusercontent.com/12102011/50379078-7b503280-0604-11e9-8744-42991243e138.png)

我用的是别人写的player, 在他的demo页面可以play。 是因为我有什么还需要设置么。。。。

link: https://cookpete.com/react-player/

十分感谢！！

**Comment by nondanee** [comment]
![image](https://user-images.githubusercontent.com/26399680/50379823-b2b7f100-068f-11e9-813d-85db4b133f65.png)

这个源站是 https 的，跟你 localhost 不一样
反正都是差不多的结果
用 https 的资源，带了 referer，403
用 http 的资源，是 mixed content，没有 referer，可以用

> P.S. 是 https 的话好像可以用 service workers 修改请求头

**Comment by zluo01** [comment]
抱歉，我对front-end算是一窍不通。。。所以我应该怎么操作才对 ？？ 所以我是应该用http然后设置html documents 里头meta 是no-referrer么？？ 或者是用https 然后用那个service worker改头啥的？？

谢谢

**Comment by nondanee** [comment]
看一看这个吧，在外面暂时没法试 😅
只要 network 里请求头没有 referer 就行

https://stackoverflow.com/questions/5033300/stop-link-from-sending-referrer-to-destination

> 在本地配置 https 还是比较麻烦的

**Comment by zluo01** [comment]
> 看一看这个吧，在外面暂时没法试 sweat_smile
> 只要 network 里请求头没有 referer 就行
> 
> https://stackoverflow.com/questions/5033300/stop-link-from-sending-referrer-to-destination
> 
> > 在本地配置 https 还是比较麻烦的

好的，谢谢。不过我最后还是打算deploy到aws上的，不过等到了那一步再说吧。。

还有一个问题。。是否能把这个api和我现在的这个web application bind在一起？？我现在每次都得开一个api的localhost，然后再request， 可以的话是要怎么操作？？或者有啥关键词，我自己搜一下？？

谢谢

**Comment by nondanee** [comment]
这个不太清楚…搜一下 `react express` 看看

**Comment by zluo01** [comment]
发现了新的问题， 更新了3.10之后， song/detail会报-406, 无论是react 还是browser.

还有想问一下从Playlist删除歌曲是不是会有delay的？我这里用了之后要个了两三秒歌单里面才删除了歌曲，Logout也是要等一会才会Logout.

其次是歌曲播放了一段时间之后url是会过期的？？我这里fetch的url过了一段时间之后播放就会403 access denied， 想问一下是不是这个情况

谢谢

**Comment by nondanee** [comment]
@zluo01 
我这边 `song/detail` 没问题

有个缓存，[app.js#L51](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/6a12a594ada20e0348b0b7c93c896236d0ea9bb9/app.js#L51)，把缓存关了看看
另，logout 要等一会才会logout 是怎么体现的，logout 了以后 查 login/status？

是的，15 分钟还是 20 分钟，忘记了
