### ISSUE TITLE
通过url请求播放歌曲返回404

### ISSUE THREAD

**Issue by littleQing** [Binaryify/NeteaseCloudMusicApi#388]
### 环境
系统:

nodejs 版本: v8.11

### 期待效果返回 mp3地址
Request URL:https://bighua.wang:3000/music/url?id=529662089
Request Method:GET
Status Code:404 Not Found

Response
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /music/url</pre>
</body>
</html>
![image](https://user-images.githubusercontent.com/18677470/48977900-76b85d00-f0de-11e8-8ec1-65181a2e3dec.png)

**Comment by MeedFine** [comment]
song/url
