### ISSUE TITLE
如何区分我创建的歌单和我收藏的歌单分类？

### ISSUE THREAD

**Issue by IFmiss** [Binaryify/NeteaseCloudMusicApi#389]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
看 creator id 是不是登录用户的 id

**Comment by IFmiss** [comment]
了解！
