### ISSUE TITLE
你好，请问有没有不同分类的电台数据接口？

### ISSUE THREAD

**Issue by wzp14027** [Binaryify/NeteaseCloudMusicApi#39]
例如：获取创作|翻唱下有哪些电台。

**Comment by Binaryify** [comment]
例子:
```
http://localhost:3000/dj/recommend/type?type=2001
```

**Comment by wzp14027** [comment]
我测试了一下这个它返回的是该分类下的优秀新电台，我想获得的数据是分类下 带台排行榜的数据如下图
![image](https://cloud.githubusercontent.com/assets/18573279/26142444/23e39950-3b13-11e7-829e-78f5548a7095.png)
最右边的那两个不同分类的数据！谢谢。

**Comment by Binaryify** [comment]
暂时没有呢
