### ISSUE TITLE
手机登录code：400

### ISSUE THREAD

**Issue by zluo01** [Binaryify/NeteaseCloudMusicApi#392]
### 环境
系统:
linux

nodejs 版本:
最新

### 出现问题
美国手机号注册后登录，显示code 400

### 重现步骤
试图用一下链接登录：
localhost:4000/login/cellphone?phone=xxxxxxxxxx&password=xx
没有登陆成功 显示code：400

### 期待效果
应成功登录，列出信息

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
先自助 fix 一下吧
https://github.com/trazyn/ieaseMusic/commit/8e61e2f3a3381006800cc43a2e067bb2ba906c38#diff-d7a9e7dd99b9cffe235d8757a90ff9d9R41

**Comment by zluo01** [comment]
> 先自助 fix 一下吧
> [trazyn/ieaseMusic@8e61e2f#diff-d7a9e7dd99b9cffe235d8757a90ff9d9R41](https://github.com/trazyn/ieaseMusic/commit/8e61e2f3a3381006800cc43a2e067bb2ba906c38#diff-d7a9e7dd99b9cffe235d8757a90ff9d9R41)

你好，我想问一下documentation里面关于error code 301 说数据被缓存了是什么意思？？
我用的是axios request
axios.get(url, {
        xhrFields: {
            withCredentials: true
        }
    }).then(function (response) {
        console.log(response);
    }).catch(function (error) {
        console.log(error);
    }).then(function () {
        //output = request.data;
    });

    axios.get('http://localhost:4000/login/status', {
        xhrFields: {
            withCredentials: true
        }
    }).then(function (response) {
        console.log(response);
    }).catch(function (error) {
        console.log(error);
    }).then(function () {
        //output = request.data;
    });

想问一下到底是什么地方出错了。。。。

谢谢！

**Comment by nondanee** [comment]
@zluo01 
你是说这个吗？
>301 错误基本都是没登录就调用了需要登录的接口,如果登陆了还是提示 301, 基本都是缓存把数据缓存起来了,解决方法是等待 2 分钟或者重启服务重新登录后再调用接口

- 301 是未登录错误
- 文档有些问题，其实只有 200 OK 的数据会被缓存(两分钟) [app.js#L51](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/app.js#L51)
- 如果感觉是缓存的锅，可以重启服务，缓存就没了

**Comment by zluo01** [comment]
> @zluo01
> 你是说这个吗？
> 
> > 301 错误基本都是没登录就调用了需要登录的接口,如果登陆了还是提示 301, 基本都是缓存把数据缓存起来了,解决方法是等待 2 分钟或者重启服务重新登录后再调用接口
> 
>     * 301 是未登录错误
> 
>     * 文档有些问题，其实只有 200 OK 的数据会被缓存(两分钟) [app.js#L51](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/app.js#L51)
> 
>     * 如果感觉是缓存的锅，可以重启服务，缓存就没了

对，就是这个，就是我的第一个request是return 200的，但是接着call 第二个Request就是301， 第一个是登录的request, 重启了服务尝试也依然是第二个返回code是301，我用的是next.js 写的，是在localhost:3000, 然后api的服务我转到了4000。想问一下，是不应该这个request么？

其实只有 200 OK 的数据会被缓存(两分钟) 的意思是只有request===200这一个information会保留两分钟么？？

十分感谢！

**Comment by nondanee** [comment]
@zluo01 
你发起的 API 请求只要 status 是 200 ，整个 response 都会被缓存
你可以在 network 里检查一下第二个 request 的 header 里有没有带 cookie

**Comment by zluo01** [comment]
> @zluo01
> 你发起的 API 请求只要 status 是 200 ，整个 response 都会被缓存
> 你可以在 network 里检查一下第二个 request 的 header 里有没有带 cookie

我在network里面看了一下，status的request并没有cookies, login的是有的，所以应该两个都有cookie才对么？？ 抱歉，第一次写这类型的。。不太懂 
谢谢

**Comment by nondanee** [comment]
@zluo01 
我去查了下应该是 withCredentials 写错了
试一下这样
```
axios.get('http://localhost:4000/login/status', {withCredentials: true})
.then(function(){
    ...
})
```

**Comment by nondanee** [comment]
@zluo01 
axios.get 只有两个参数 axios.get(url[, config])
所以登录那个错了，应该是
```
axios.get('http://localhost:4000/login', {
	params: {
		email: email,
		password: pass
	},
	withCredentials: true
})
.then(function (response) {
	console.log(response);
}).catch(function (error) {
	console.log(error);
}).then(function () {
	//output = request.data;
});
```

**Comment by zluo01** [comment]
> @zluo01
> axios.get 只有两个参数 axios.get(url[, config])
> 所以登录那个错了，应该是
> 
> ```
> axios.get('http://localhost:4000/login', {
> 	params: {
> 		email: email,
> 		password: pass
> 	},
> 	withCredentials: true
> }).then(function (response) {
> 	console.log(response);
> }).catch(function (error) {
> 	console.log(error);
> }).then(function () {
> 	//output = request.data;
> });
> ```

谢谢，可以了！！！！！ 十分感谢！！！！
