### ISSUE TITLE
歌曲详情里没有歌手图片了吗？

### ISSUE THREAD

**Issue by xingyue234** [Binaryify/NeteaseCloudMusicApi#393]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清
![image](https://user-images.githubusercontent.com/21305582/49276208-c7520080-f4b8-11e8-9826-c3603b33fd2b.png)
以前是有个picUrl参数，现在没有了

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
这个 API 服务只是网易云 API 的搬运工，不生产数据

至于你想要的 picUrl，是可以从 picId 算出来的，网上搜的到，参考里面的 `getTrackURL`
https://greasyfork.org/zh-CN/scripts/10582-网易云音乐高音质支持/code
https://greasyfork.org/zh-CN/scripts/23222-网易云下载/code
