### ISSUE TITLE
/search/suggest接口参数（limit、type、offset）无效

### ISSUE THREAD

**Issue by LunixTD** [Binaryify/NeteaseCloudMusicApi#394]
### 环境
系统:
win10
nodejs 版本: v8.14.0

### 出现问题
搜索建议接口limit、offset等参数都没效果

### 重现步骤
请求下列接口后，请求参数不论怎么修改请求数据都不会变化，limit和type参数都无效
/search/suggest?keywords=lo&type=1000
/search/suggest?keywords=lo&limit=40

### 期待效果
请求数据内容限制在某个类型（例如type=1000）里面
请求数据限制在指定数目

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
`/search/suggest` 不支持设置参数，请用 `/search`

**Comment by LunixTD** [comment]
好吧，谢谢。

**Comment by nondanee** [comment]
@Binaryify 
limit, offest 好像是支持的，type 不支持，你试一下

**Comment by Binaryify** [comment]
@nondanee 晚点再看看

**Comment by Binaryify** [comment]
@nondanee 不对,不支持

**Comment by nondanee** [comment]
@Binaryify 
👌哦哦好，我之前看官网用了 limit，刚才我也试了下是无效的
![image](https://user-images.githubusercontent.com/26399680/49860876-a03eeb80-fe35-11e8-8412-90be650e2909.png)
