### ISSUE TITLE
歌单详情接口只能获取一条数据

### ISSUE THREAD

**Issue by mjyplusone** [Binaryify/NeteaseCloudMusicApi#398]
### 环境
系统:

nodejs 版本:

### 出现问题
歌单详情接口只能获取一条数据

### 重现步骤
/playlist/detail?id=24381616
![image](https://user-images.githubusercontent.com/15232954/49707070-9023e200-fc64-11e8-954b-63f8413f141b.png)

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
请更新
