### ISSUE TITLE
【关注/follow】关注接口返回异常

### ISSUE THREAD

**Issue by fengzhengkeji** [Binaryify/NeteaseCloudMusicApi#399]
### 环境
系统:
windows

nodejs 版本:
8.12.0
### 出现问题
关注用户返回 {'code': 250, 'message': '关注异常'}
### 重现步骤
登录账号，获取一个用户ID，对用户进行关注

接口地址 : /follow

调用例子 : /follow?id=32953014&t=1

**Comment by fengzhengkeji** [comment]
目前测试任然无法正常关注

**Comment by nondanee** [comment]
@Binaryify 
测了下这个接口用到 checkToken
试过用 `cookie.os` 可以绕过，换 linuxapi 无效

**Comment by fengzhengkeji** [comment]
> @Binaryify
> 测了下这个接口用到 checkToken
> 试过用 `cookie.os` 可以绕过，换 linuxapi 无效

可以复现一下您的操作吗？cookie.os是在哪里获取

**Comment by Binaryify** [comment]
@nondanee 
加个 os=osx 吗

**Comment by nondanee** [comment]
@Binaryify 嗯，之前用的是 os=pc，其实都行

**Comment by nondanee** [comment]
@fengzhengkeji 
这是一个 trick ，具体想知道请在左上角搜 `query.cookie.os` "in this repository"
有几个查 token 的接口在用这个绕过，希望不要被滥用，等 @Binaryify 更新吧

**Comment by fengzhengkeji** [comment]
> @fengzhengkeji
> 这是一个 trick ，具体想知道请在左上角搜 `query.cookie.os` "in this repository"
> 有几个查 token 的接口在用这个绕过，希望不要被滥用，等 @Binaryify 更新吧

好的，谢谢！目前在改造python，遇到这些问题

**Comment by Binaryify** [comment]
已修复

**Comment by fengzhengkeji** [comment]
> @fengzhengkeji
> 这是一个 trick ，具体想知道请在左上角搜 `query.cookie.os` "in this repository"
> 有几个查 token 的接口在用这个绕过，希望不要被滥用，等 @Binaryify 更新吧

checktoken的生成机制有了解吗。刚才测试了，如果用python不知道该怎么复现绕过的机制

**Comment by nondanee** [comment]
@fengzhengkeji 
#46 #267 你了解一下
跟语言无关，往 cookie 里加点东西就好了

**Comment by fengzhengkeji** [comment]
> @fengzhengkeji
> #46 #267 你了解一下
> 跟语言无关，往 cookie 里加点东西就好了

没太看懂，python登录获取cookies只有'MUSIC_U'，'__csrf'，'__remember_me'三个值，我测试后续操作都不行，应该是cookies出问题了，cookie需要添加什么吗

**Comment by nondanee** [comment]
@fengzhengkeji `os=pc`

**Comment by Binaryify** [comment]
@fengzhengkeji 看我最后一次提交记录

**Comment by nondanee** [comment]
@fengzhengkeji 
checkToken的生成机制应该来自网易易盾，模拟不来，所以用别的方法绕过

**Comment by Binaryify** [comment]
网易云盾要是能绕过就不得了了  😂

**Comment by fengzhengkeji** [comment]
> 网易云盾要是能绕过就不得了了  😂

我用python改写，能登录，但是其他的死活不行，一直返回{"msg":null,"code":301}

可以增加发布动态接口吗
https://music.163.com/weapi/share/friends/resource

**Comment by Binaryify** [comment]
其他的301是因为你 cookie 没带上吧
