### ISSUE TITLE
搜索异常，返回code=-460,cheating

### ISSUE THREAD

**Issue by caiyonglong** [Binaryify/NeteaseCloudMusicApi#400]
### 环境
系统:

nodejs 版本:

### 出现问题
搜索接口异常，返回结果
{
    "code": -460,
    "msg": "Cheating"
}

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
没发现问题，海外的话加一下 `X-Real-IP`

**Comment by zhenhua397** [comment]
我也是同样的问题，机子在vultr的洛杉矶机房，加上X-Real-IP确实可以了。
多谢  @nondanee，顺便问下这是什么原理？

**Comment by nondanee** [comment]
@zhenhua397 #29

**Comment by caiyonglong** [comment]
X-Real-IP  ，嗯加上这个就OK了

**Comment by chaotianjiao** [comment]
问一下我在国内的服务器部署的，后来可能接口用多了，也出现了cheating,请问有办法修复吗？
