### ISSUE TITLE
关于 Android客户端调用 登录的问题

### ISSUE THREAD

**Issue by wnpllrzodiac** [Binaryify/NeteaseCloudMusicApi#401]
需要登录的接口
使用 Android httpconnection 先调用 login 再调用 /recommend/resource 返回301.
httpconnection必须使用一个吗？
使用两个 httpconnection 第二次添加了 cookie似乎总是不行，有sample code给给点提示么

**Comment by nondanee** [comment]
#395

**Comment by wnpllrzodiac** [comment]
多谢，我参考一下

**Comment by wnpllrzodiac** [comment]
搞好了！setcookie 要去掉expire等无用信息。
