### ISSUE TITLE
求游客登陆接口

### ISSUE THREAD

**Issue by easyboy1105** [Binaryify/NeteaseCloudMusicApi#402]
能抓到游客登陆接口嘛？

**Comment by nondanee** [comment]
网页版（weapi）没有游客登录接口，只有客户端有（eapi / linuxapi）
路径: `/api/register/anonimous`
参数 `{"username":"xxx"}` username 我这里看到是一个76位大小写字母加数字的字符串
不知道你有什么用，我感觉意义不大

**Comment by easyboy1105** [comment]
因为有写接口需要登陆嘛 所以想直接用游客cookie

**Comment by nondanee** [comment]
@easyboy1105 
哦那没有你要的那种游客登录，游客能做的操作没 cookie 都可以做
