### ISSUE TITLE
关于上传图片接口

### ISSUE THREAD

**Issue by fengzhengkeji** [Binaryify/NeteaseCloudMusicApi#403]
### 环境
系统:

nodejs 版本:

### 期待效果

上传图片接口不知道有没有测试，今天尝试了下，卡在最后post图片文件这里了

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
上传图片接口?

**Comment by fengzhengkeji** [comment]
> 上传图片接口?

对的，上传图片接口在更改头像背景图和发布动态等地方会用到，抓包发现是先向https://music.163.com/weapi/nos/token/alloc获取一个objectKey值，再由这个值和https://nosup-hz1.127.net/yyimgs构建一个URL，由一个option预请求，再通过post上传文件。模拟上传返回结果不成功卡在这最后一步。

**Comment by fengzhengkeji** [comment]
> 上传图片接口?

你好，最近有测试吗？

**Comment by Binaryify** [comment]
这个不好弄的

**Comment by fengzhengkeji** [comment]
> 这个不好弄的

能指点一下吗。我测试了，一直请求不通，不知道什么原因

**Comment by Binaryify** [comment]
传 cdn 的，没secret和 id 弄不了

**Comment by Binaryify** [comment]
这个有办法弄了，晚上更新

**Comment by Binaryify** [comment]
已更新
