### ISSUE TITLE
文档Docker章节错误

### ISSUE THREAD

**Issue by MyFaith** [Binaryify/NeteaseCloudMusicApi#406]
![](http://pjw2pdwkb.bkt.clouddn.com/18-12-20/31320078.jpg)

应该是`netease-cloud-music`吧

**Comment by Binaryify** [comment]
https://hub.docker.com/r/twesix/netease-cloud-music/
没错的

**Comment by MyFaith** [comment]
你仔细看图片...我圈出来了 `netease-music-api`

**Comment by Binaryify** [comment]
那里确实有误,一会更新下

**Comment by Binaryify** [comment]
@nondanee 晚点弄弄,今天加班😅

**Comment by nondanee** [comment]
@Binaryify 👌

**Comment by Binaryify** [comment]
@nondanee 
docker 不熟悉，要怎么 link github repository 的

**Comment by Binaryify** [comment]
嗯，昨天弄好了，一开始同步有延迟，我这里拉不了，还以为哪里不对

**Comment by Binaryify** [comment]
更新好了

**Comment by nondanee** [comment]
@Binaryify 👌
