### ISSUE TITLE
获取评论返回-460

### ISSUE THREAD

**Issue by xxf1996** [Binaryify/NeteaseCloudMusicApi#408]
### 环境
系统: Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-130-generic x86_64)

nodejs 版本: 10.8.0

### 出现问题

获取歌曲评论时返回：
`{"code":-460,"msg":"Cheating"}`

### 重现步骤
/comment/music?id=5189652

**Comment by magicknight** [comment]
这边也似乎是用不了了。换ip也不行。

**Comment by nondanee** [comment]
cookie 的问题
参考 `/song/url` 中 `query.cookie._ntes_nuid` 的写法

**Comment by Binaryify** [comment]
@xxf1996 
@magicknight 
海外吗,还是开了代理

**Comment by xxf1996** [comment]
@Binaryify 
国内的，也没有使用代理；
但我是部署在腾讯云的主机上，而且不是单独为这个项目开一个端口，而是直接接入到之前的一个express项目中，不知道有啥影响没。

**Comment by magicknight** [comment]
> @xxf1996
> @magicknight
> 海外吗,还是开了代理

部署在国内，不过按@nondanee
的做法可以解决了。

**Comment by Sender-cheng** [comment]
> 怎么处理的？
> 我在comment_music.js中加了和song_url中一样的cookie，但依旧显示`{"code":-460,"msg":"Cheating"}`
> 
> ![tim 20181224182135](https://user-images.githubusercontent.com/18100743/50397081-d6bb2580-07a8-11e9-9cc0-82698b166456.png)

好吧，解决了，是请求的地址的原因，解决后如下图：
![tim 20181224210451](https://user-images.githubusercontent.com/18100743/50400189-bd71a380-07bf-11e9-9b99-954d4871b05f.png)

**Comment by nondanee** [comment]
@Sender-cheng 
我试了下加 `/?csrf_token=` 没用，而且要加也应该是加 `?csrf_token=` 才对，你是不是因为别的改动解决的
之前的那张图里你甚至没有 `require('crypto')` ，应该会报错 500 才对啊

**Comment by Izayawww** [comment]
@nondanee 
说的是改源码
![image](https://user-images.githubusercontent.com/16361564/50535294-a77b2e80-0b83-11e9-8c91-5193d738154d.png)

**Comment by Sender-cheng** [comment]
> @Sender-cheng
> 我试了下加 `/?csrf_token=` 没用，而且要加也应该是加 `?csrf_token=` 才对，你是不是因为别的改动解决的
> 之前的那张图里你甚至没有 `require('crypto')` ，应该会报错 500 才对啊

哈哈，也是。没引进crypto。搞错了，细看，接口地址并不同。
`http://music.163.com/weapi/v1/resource/`comments`/R_SO_4_'${id}` 有问题
`http://music.163.com/weapi/v1/resource/`hotcomments`/R_SO_4_'${id}`

**Comment by nondanee** [comment]
@Sender-cheng 
确实在登录状态下也需要 nuid 的值，你是对的
不过 comments 和 hotcomments 是两个接口，而且 [hotcomments 接口](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/comment_hot.js)一直都存在

这个问题已经修复了，麻烦 @Binaryify 关一下
还有个建议，comment 的几个接口可以合并到一起

**Comment by Binaryify** [comment]
@nondanee 
合并了接口地址就变了，还是减少 breaking change 吧

**Comment by nondanee** [comment]
@Binaryify 👌
