### ISSUE TITLE
能否统一返回数据格式

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [Binaryify/NeteaseCloudMusicApi#411]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
目前 NeteaseCloudMusicApi 只是网易云接口的封装（隐藏部分细节），“几乎不”处理返回数据
如有需要，可以自己增加中间件实现 formatter。如果愿意共享这个组件，也欢迎 PR
