### ISSUE TITLE
关于用户登录接口的一些疑惑

### ISSUE THREAD

**Issue by chengxuzhang** [Binaryify/NeteaseCloudMusicApi#412]
我看登录接口可以用手机号和密码直接登录，如果我在中间把其他人的手机号和密码保存起来不是很危险么？嘿嘿嘿

**Comment by nondanee** [comment]
是的，很危险。文档中有写
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知

**Comment by Binaryify** [comment]
是的,这也是我这边不提供服务,只提供代码的原因
