### ISSUE TITLE
klyric

### ISSUE THREAD

**Issue by javascripth** [Binaryify/NeteaseCloudMusicApi#414]
### 环境
系统: win10

nodejs 版本:v10.13.0

### 期待效果 klyric有歌词每个字的时间/速度

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
不是所有都有 klyric 的
参考 /lyric?id=347230
