### ISSUE TITLE
不能正常启动服务

### ISSUE THREAD

**Issue by nicehiro** [Binaryify/NeteaseCloudMusicApi#415]
### 环境
系统: Linux 3.16.0-7-amd64

nodejs 版本: 
node -v v0.10.29
npm -v 1.4.21

### 出现问题
![screenshot_20190103_103337](https://user-images.githubusercontent.com/17773634/50621812-6b5d1a80-0f43-11e9-860d-dfd324a1a167.png)

### 重现步骤
npm install
npm start
### 期待效果
服务正常启动

不是很熟悉npm，在本地Arch环境搭建成功了，但是服务器上失败了，猜测是nodejs版本的问题？
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
你的 nodejs 版本太低了

**Comment by nicehiro** [comment]
> 你的 nodejs 版本太低了

多谢，解决了
