### ISSUE TITLE
想问一下，搜索的时候，能不能只精确匹配同名歌曲呢

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#419]
### 环境
系统:
windows10

nodejs 版本:
10.15.0

### 出现问题
搜索歌曲名字的时候搜出来一堆不是同名的歌曲

### 期待效果
搜索结果只是同名歌曲

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by ricycc** [comment]
我觉得你可以自己做一层筛选，只保留同名歌曲的结果

**Comment by Binaryify** [comment]
这个要你自己实现,这个项目只是转发网易官方接口,基本不对数据做处理的 ,filter 下就行
