### ISSUE TITLE
需要登录的接口在调用时出问题

### ISSUE THREAD

**Issue by lany9527** [Binaryify/NeteaseCloudMusicApi#42]
在PORT=8080 node app.js 后
1. 前端访问：http://localhost:8080/personalized/mv  成功

2. 访问需登录的接口时出现301错误，比如：
http://localhost:8080/recommend/resource?uid=479373404  【我理解的有些需登录的意思时通过登录获取uid,才能进一步访问接口。479373404,即为我登陆后获得的uid】

3.http://localhost:8080/recommend/resource?uid=479373404 直接粘贴到谷歌浏览器地址栏访问也报301错误。
实在是无解了，请各位指点迷津。
ps: 前端ajax请求用的是  axios 这个库。

@Binaryify  你好，搞了一上午，还是有问题。我想再请教一下，
我设置了  withCredentials:true。代码如下：
return axios.get(apiUrl + 'recommend/resource?uid=479373404',{withCredentials:true})
    .then(res => console.log('%c fetchSong==>','background:#666;color:#FFD100',res));

服务端的app.js 跨域设置部分改了：
res.header("Access-Control-Allow-Origin", "http://localhost:3000")   【因为我用react手脚架在前端跑了3000端口】

但是返回结果还是有点问题，data里面根本没有数据，只有{code：301}，详情如下：
`
Object {data: Object, status: 200, statusText: "OK", headers: Object, config: Object…}
config
:
Object
data
:
Object
code
:
301
__proto__
:
Object
headers
:
Object
request
:
XMLHttpRequest
status
:
200
statusText
:
"OK"
__proto__
:
Object

`

**Comment by Binaryify** [comment]
是否禁用了 cookie

**Comment by zhixuanziben** [comment]
你看一下你的http请求头是否带上了cookies

**Comment by lany9527** [comment]
多谢啦 @Binaryify @zhixuanziben
