### ISSUE TITLE
请求出错

### ISSUE THREAD

**Issue by C-C-Y** [Binaryify/NeteaseCloudMusicApi#420]
### 环境
系统: windows7

nodejs 版本:v8.11.1

### 期待效果 出现评论

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
#408

**Comment by nondanee** [comment]
@Binaryify 加上 `cookie.os` 应该就行了

**Comment by C-C-Y** [comment]
谢谢,已经解决了

**Comment by C-C-Y** [comment]
> #408

谢谢,已经解决了,我还有个问题,同一个用户播放相同的歌曲,为什么用这个api不能获取url,检查是否能播放显示无版权,但是登录官方的客户端后却可以播放?只是少部分部分歌曲,不是全部

**Comment by C-C-Y** [comment]
@nondanee  谢谢,已经解决了,我还有个问题,同一个用户播放相同的歌曲,为什么用这个api不能获取url,检查是否能播放显示无版权,但是登录官方的客户端后却可以播放?只是少部分部分歌曲,不是全部

**Comment by nondanee** [comment]
@C-C-Y 
应该不会出现的，请确认一下登录状态。麻烦提供下歌曲 ID，我查一下

**Comment by C-C-Y** [comment]
@nondanee  获取歌单详情返回数据中的privileges数组中每一首歌的的subp属性如果为0,均不能获取url,检查是否能播放也显示为无版权,例如"告白气球",id:440241144,但是客户端能播放,如果subp为1则都可以播放,其中不能播放的歌曲中有一些客户端也不行,但是很少,我一个歌单93首歌,客户端不能播放7首,api不能获取数据的有将近20首

**Comment by nondanee** [comment]
@C-C-Y 
可能是你的客户端有缓存吧，440241144 我就不能播放

![image](https://user-images.githubusercontent.com/26399680/50760844-d429f700-12a3-11e9-86cf-f599ab6a162b.png)

![image](https://user-images.githubusercontent.com/26399680/50760918-0c313a00-12a4-11e9-8d54-3e586a15a352.png)

**Comment by C-C-Y** [comment]
@nondanee 应该是这样吧,网易云的版权真的一言难尽...
