### ISSUE TITLE
用户登陆之后设置cookie的问题

### ISSUE THREAD

**Issue by QwerBoy** [Binaryify/NeteaseCloudMusicApi#424]
用户登陆之后是不是自动设置cookie？如果没有自动设置cookie可以手动设置吗？如果可以手动设置cookie，哪些内容需要设置为cookie

**Comment by nondanee** [comment]
浏览器（xhr/fetch/地址栏访问）会自动设置
不跨域的话用 js 可以修改（手动设置），已经把 httponly 去掉了，跨域的话只能用开发者工具修改

其它请求方式都需要手动设置

用户信息相关、个性推荐相关、订阅收藏相关、评论私信相关的接口都需要登录状态（要求 cookie）
