### ISSUE TITLE
关于用户登录接口的问题

### ISSUE THREAD

**Issue by IsKaros** [Binaryify/NeteaseCloudMusicApi#426]
### 环境
系统:
win10 时间:2019/1/10

nodejs 版本:
10.15.0

### 出现问题
vue项目通过axios向3000端口发送请求,并没有设置cookie.

### 重现步骤
vue项目通过axios使用get请求向3000端口发送请求,并没有设置cookie,但是直接在浏览器地址栏输入以及POSTMAN发送请求的话,有设置,用F12开发者工具清除cookie之后,刷新项目页面,我代码写的只要进入页面就会登录,可是没有设置cookie,虽然登录成功了,后面需要登录的API都用不了,报301需要登录.但在浏览器地址栏和POSTMAN使用需要登录的API的时候,不会报错,再在项目中调用该API也不会报301
axios的配置:只有官方的跨域配置,以及baseUrl

### 期待效果
项目通过axios发送请求会自带设置cookie

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
#392 
麻烦检查一下是不是 axios 写法的问题

**Comment by IsKaros** [comment]
除了配置之外就是使用下面的这个写法
axios.get(url, config)

**Comment by IsKaros** [comment]
不会意思,找到问题了,忘记写withCredentials: true,但这个好像和那个官方的跨域配置相似

**Comment by IsKaros** [comment]
不会意思,找到问题了,忘记写withCredentials: true,但这个好像和那个官方的跨域配置相似

**Comment by IsKaros** [comment]
不好意思,找到问题了,忘记写withCredentials: true,但这个好像和那个官方的跨域配置相似

**Comment by qipengwei** [comment]
> 不好意思,找到问题了,忘记写withCredentials: true,但这个好像和那个官方的跨域配置相似

请问在那里配置这个呢
