### ISSUE TITLE
付费精品电台里面的电台都不能播放吗

### ISSUE THREAD

**Issue by 082530** [Binaryify/NeteaseCloudMusicApi#428]
### 环境
系统:

nodejs 版本:

### 出现问题
获取到付费精品电台里面的URL之后的音频长度只有5s用id.mp3URL没法用
### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
买了才能播放的吧
