### ISSUE TITLE
第一次使用的是代理,然后就必须过代理了

### ISSUE THREAD

**Issue by d1y** [Binaryify/NeteaseCloudMusicApi#429]
### 环境
系统: macos

nodejs 版本: v11.6.0

### 出现问题
```bash
{
"code": 502,
"msg": "Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:19180\n at ClientRequest.onError (/Users/kozo4/cat/Project/MoeMusic/app/NeteaseCloudMusicApi/node_modules/_tunnel-agent@0.6.0@tunnel-agent/index.js:177:17)\n at Object.onceWrapper (events.js:276:13)\n at ClientRequest.emit (events.js:188:13)\n at Socket.socketErrorListener (_http_client.js:399:9)\n at Socket.emit (events.js:188:13)\n at emitErrorNT (internal/streams/destroy.js:82:8)\n at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n at process.internalTickCallback (internal/process/next_tick.js:72:19)"
}
```

求教大大们,另外,小弟最近在用`electron`写客户端,会用到这个,请教各位,我如何能够在`windows`上开启一个`server`呢(集成到`electron`上呢)🎂

**Comment by nondanee** [comment]
不会吧，我这边代理正常，请问你是怎么设置代理的呢？

electron 可以直接通过 require module 的方式使用，不用起 server，例子：
```JavaScript
let oneAPI = require('./module/xxxxxx.js')
let request = require('./util/request.js')
let query = {
	id: '',
	cookie: '',
	proxy: '',
}

oneAPI(request, query).then(response => {})
```
开启 server 的例子很多了，ieaseMusic 之类

**Comment by d1y** [comment]
> 不会吧，我这边代理正常，请问你是怎么设置代理的呢？
> 
> electron 可以直接通过 require module 的方式使用，不用起 server，例子：
> 
> ```js
> let oneAPI = require('./module/xxxxxx.js')
> let request = require('./util/request.js')
> let query = {
> 	id: '',
> 	cookie: '',
> 	proxy: '',
> }
> 
> oneAPI(request, query).then(response => {})
> ```
> 
> 开启 server 的例子很多了，ieaseMusic 之类

我使用`firefly`来代理的,我记得我关了软件啊,但它默认还是走的代理啊🥺

**Comment by nondanee** [comment]
@d1y 
检查一下是不是因为 firefly 影响了环境变量，文档里有说明，请看一下
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=docker-容器运行

每个请求都可以单独设置代理 `?proxy={url}`

**Comment by d1y** [comment]
> @d1y
> 检查一下是不是因为 firefly 影响了环境变量，文档里有说明，请看一下
> [https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=docker-容器运行](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=docker-%E5%AE%B9%E5%99%A8%E8%BF%90%E8%A1%8C)
> 
> 每个请求都可以单独设置代理 `?proxy={url}`

好的,谢谢❤️

`cookie`怎么拿到🙂
![image](https://user-images.githubusercontent.com/45585937/51372398-1a9b1380-1b38-11e9-85e5-145dfab36920.png)

**Comment by d1y** [comment]
![image](https://user-images.githubusercontent.com/45585937/51372586-ac0a8580-1b38-11e9-9b24-070150574a39.png)

**Comment by nondanee** [comment]
好吧我没说清楚
不同 API 的参数不同，search 用的参数是 keywords，不是 id，参照文档
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=搜索
每个 API 都支持设置这两个参数 proxy，cookie
看一下各个 module 的源码就明白了

cookie 登录 `require('./module/login.js')` 就能拿到
你要测试 search 接口其实不登录也可用

**Comment by nondanee** [comment]
可以的，不过 dependencies 要有 request
