### ISSUE TITLE
问下为什么我登录返回的头部中没有set-cookie信息呢

### ISSUE THREAD

**Issue by 082530** [Binaryify/NeteaseCloudMusicApi#430]
### 环境
系统:

nodejs 版本:

### 出现问题
问下为什么我登录返回的头部中没有set-cookie信息呢？我应该上哪儿去找着cookie呢？返回的数据里面也没有相关的数据，哪位大神能帮忙解答下，不管是用ajax还是axios都是一样的
![image](https://user-images.githubusercontent.com/38971082/51366974-79a25d80-1b23-11e9-8086-a8f81a7592f2.png)

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by 082530** [comment]
如果把登录的接口放到浏览器里面直接打开返回的头部又会携带set-cookie请问下这是怎么回事，该如何解决呢

**Comment by nondanee** [comment]
https://github.com/wengjq/Blog/issues/2#issuecomment-449810016
用相同**域名**试试看

**Comment by 082530** [comment]
> xhrFields: { withCredentials: true } 加了吗

加了，结果发现360浏览器里面带了cookie，而谷歌的却没带，不晓得怎么回事

**Comment by 082530** [comment]
> [wengjq/Blog#2 (comment)](https://github.com/wengjq/Blog/issues/2#issuecomment-449810016)
> 用相同试了同域名的，还是不行。用360浏览器登录后调用登录检测api怎么显示301提示未登录呢，cookie的信息也携带出去了，请问下这是怎么回事
![image](https://user-images.githubusercontent.com/38971082/51375793-c301a580-1b41-11e9-9e4a-88ab9620ee23.png)

**Comment by 082530** [comment]
这是测试用的代码，麻烦看下是不是哪里有问题
 $.ajax({
      url: "/login?email=user&password=pwd",
      xhrFields: {
        withCredentials: true
      },
      success: function (data) {
        console.log(data)
        $.ajax({
          url: "/user/subcount",
          xhrFields: {
            withCredentials: true
          },
          success: function (data) {
            console.log(data);
          },
          error: function (err) {
            console.log(err)
          }
        })
      },
      error: function (err) {
        console.log(err)
      }
    })

**Comment by IsKaros** [comment]
之前问过同样的问题,已解决.axios加一下withCredentials: true试试看,不是xhrFields: {withCredentials: true},

**Comment by 082530** [comment]
试了下，除了谷歌浏览器而外其他浏览器都正常

**Comment by nondanee** [comment]
这个是相同域名不同域的测试结果 (Chrome 72 隐身模式)
api :3000
page :8887

用的你的代码
```
let user = ""
let pwd = ""
let apiHost = "http://localhost:3000"
$.ajax({
	url: `${apiHost}/login?email=${user}&password=${pwd}`,
	xhrFields: {
		withCredentials: true
	},
	success: function (data) {
		console.log(data)
		$.ajax({
			url: `${apiHost}/user/subcount`,
			xhrFields: {
				withCredentials: true
			},
			success: function (data) {
				console.log(data)
			},
			error: function (err) {
				console.log(err)
			}
		})
	},
	error: function (err) {
		console.log(err)
	}
})
```

![image](https://user-images.githubusercontent.com/26399680/51542905-4d763c00-1e97-11e9-94aa-338d19a0e8da.png)
