### ISSUE TITLE
那个，希望作者可以添加一个banner轮播图的拉伸背景

### ISSUE THREAD

**Issue by summeryio** [Binaryify/NeteaseCloudMusicApi#435]
### 环境
系统:

nodejs 版本:

### 出现问题
是这样的，我目前在弄网易云pc版，然后那个轮播图背景接口里没有哎，就是每张轮播有条细细的背景图，网易云官网就是这样的，作者可以添加一下嘛，感谢前辈！！！

### 期待效果
就是这样的图片
http://p1.music.126.net/yTD-HbUfvp-e9S0IqE_b9Q==/109951163817357054.jpg

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
#351 把 banner.js 回滚到这个 PR 之前的版本就有了

**Comment by summeryio** [comment]
已获取，十分感谢前辈！

**Comment by nondanee** [comment]
不用谢，原来的数据是提取自网页版的数据，现在用的是客户端的 API。
网页版的 banner 尺寸要相对小一些
