### ISSUE TITLE
获取所有所有歌单信息

### ISSUE THREAD

**Issue by zluo01** [Binaryify/NeteaseCloudMusicApi#436]
### 环境
系统:
linux
nodejs 版本:
latest

### 期待效果
想问一下，api是否支持获取所有歌单信息？？ 
假如用一个loop暴力request过去会有高频ip的问题么？？

希望获得信息做推荐系统

谢谢
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
官方有的接口才有

**Comment by nondanee** [comment]
有这个 `/top/playlist?order=new`
不知道 limit 和 offset 有没有限制你自己试一下
感觉是自增 ID，所以从 1 开始 loop 可能也可以
高频可能会有吧
