### ISSUE TITLE
android端 Java调用API 

### ISSUE THREAD

**Issue by mikeliu60** [Binaryify/NeteaseCloudMusicApi#437]
### 环境
系统:
android
### 出现问题
js看着有点懵，能不能指点一下该从何处入手，获取完整的URL
### 重现步骤
Java 调用API 发送请求
### 期待效果
获取相关数据
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by StageGuard** [comment]
你要自己写post，get，encrypt算法
参考他的https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/crypto.js
或者我以前写的https://m.gitee.com/eskarton/NeteaseCloudMusic.js/blob/master/JSData/api.js

**Comment by mikeliu60** [comment]
> 你要自己写post，get，encrypt算法
> 参考他的https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/util/crypto.js
> 或者我以前写的https://gitee.com/eskarton/NeteaseCloudMusic.js/blob/master/JSData/api.js

代码中大部分都能看懂，对于URL https://music.163.com/weapi/的weapi字符串有些疑惑，这个是从哪里来的，是否等于crypto.js中的
`const weapi = (object) => {
    const text = JSON.stringify(object)
    const secretKey = crypto.randomBytes(16).map(n => (base62.charAt(n % 62).charCodeAt()))
    return {
        params: aesEncrypt(Buffer.from(aesEncrypt(Buffer.from(text), 'cbc', presetKey, iv).toString('base64')), 'cbc', secretKey, iv).toString('base64'),
        encSecKey: rsaEncrypt(secretKey.reverse(), publicKey).toString('hex')
    }
}`
