### ISSUE TITLE
请问一下，歌曲长度在哪

### ISSUE THREAD

**Issue by Drowned-fish** [Binaryify/NeteaseCloudMusicApi#438]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/204
