### ISSUE TITLE
歌曲URL还能正常获取到吗

### ISSUE THREAD

**Issue by JNUniversityYangHaotian** [Binaryify/NeteaseCloudMusicApi#44]
昨晚网易API更新了，你这个接口是不是也获取不到歌曲MP3的URL了。

**Comment by Binaryify** [comment]
发 issue 前可以先试下
例子:`/music/url?id=347230`
![image](https://cloud.githubusercontent.com/assets/12221718/26231609/09159c1a-3c83-11e7-9aaa-2e4d420d7743.png)
![image](https://cloud.githubusercontent.com/assets/12221718/26231614/11a3ac1e-3c83-11e7-87d7-8d0f3ec659df.png)

**Comment by JNUniversityYangHaotian** [comment]
好的，那我用你的接口吧，之前我用的网易的：http://music.163.com/api/song/detail/?id=28377211&ids=%5B28377211%5D。网易昨晚突然把mp3url字段给屏蔽了。

**Comment by JNUniversityYangHaotian** [comment]
能帮我看看这个错误吗
![default](https://cloud.githubusercontent.com/assets/19491871/26234951/ae8be6e2-3c9a-11e7-8fa1-9871af0a99c3.JPG)

**Comment by JNUniversityYangHaotian** [comment]
刚才是在UBUNTU上跑的结果
我又在WINDOWS上试了一下，还是有错误，结果如下，希望你能帮我看看，谢谢
![default](https://cloud.githubusercontent.com/assets/19491871/26235407/838c10cc-3c9d-11e7-8bee-a4698b2a4168.JPG)

**Comment by Binaryify** [comment]
node版本要求6.0以上
