### ISSUE TITLE
搜索的api(/search?keywords= 海阔天空) 返回的picUrl全部为空

### ISSUE THREAD

**Issue by chenpengdepot** [Binaryify/NeteaseCloudMusicApi#441]
搜索的api(/search?keywords= 海阔天空) 返回的picUrl全部为空
![axnqfb9jmrk 9g 5yey](https://user-images.githubusercontent.com/44863634/52833806-bb6df600-3119-11e9-9b79-4bc81ae212c7.png)

**Comment by Binaryify** [comment]
封面搜索接口没有，可以专辑接口获取
