### ISSUE TITLE
非登录状态下歌单信息获取只有一首歌

### ISSUE THREAD

**Issue by zluo01** [Binaryify/NeteaseCloudMusicApi#442]
### 环境
系统:
Ubuntu
nodejs 版本:
latest
### 出现问题
同样的歌单，非登陆状态下只有一首歌
### 重现步骤
/playlist/detail?id=1
### 期待效果
应该获取所有的歌，无论是localhost或者是deploy到server的，相同情况
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by zluo01** [comment]
突然又好了。。。。是本体的间歇抽风么？

**Comment by nondanee** [comment]
你加了 X-Real-IP 吗，代码里那个 IP 用太多被 ban 了，自己随便换一个国内 IP 即可

**Comment by zluo01** [comment]
> 你加了 X-Real-IP 吗，代码里那个 IP 用太多被 ban 了，自己随便换一个国内 IP 即可

对，加了。但是有什么办法可以test出来么，假如每次都要人工check的话太麻烦了。还有就是ip用的多少算是太多？？

**Comment by nondanee** [comment]
不知道，靠判断歌单只有一首歌？
不知道，看频率吧?
每次随机生成一个套路云网段里的 IP 不就好了嘛......

**Comment by zluo01** [comment]
现在是这样写了，但是问题是在于假如是Random的话，就无法validate IP 有没有被ban了吧，尽管数量够大的话，貌似是可以忽略不计？ 还有是不是request weapi的时候，假如没有加密话，返回200但是是会没有data的， 加密是不是要按照api的样子加密才行？？

**Comment by nondanee** [comment]
为啥无法 validate？歌单只有一首歌的结果打个 tag 加回任务队列
阿里有 2^18 个 IP 你觉得呢
加密错了 response body 是空的，status code 是 200
那肯定啊，要是随便加密的话网易怎么解密得知你的请求......
网易云有不加密的 api，参数写到 query string 里就行，你可以试试看

**Comment by zluo01** [comment]
但是无法知道ip 是不是被ban，我现在是直接在api util里头header[x real ip] = randomIP(), 每次create request 都是不同的ip, 而且爬了几百万data发现，大多数的歌单都只有一首歌。。。。
之前在写go的，看了git上头的其他repo写的加密，发现基本上不是没写完就是下载下来不work，也没法看那些implement 到底写对没，打算重头自己写了

**Comment by nondanee** [comment]
用这个 `https://music.163.com/api/v3/playlist/detail?id=`
不要加 X-Real-IP 你看看会有什么结果

**Comment by zluo01** [comment]
依然是会被ban的，现在这样随机random觉得也够用了，反正只是不停的爬而已，只要数量够多就好了

**Comment by zluo01** [comment]
问一下，套路云网段哪里可以get到准去的？ 用了这个里头的，https://blog.csdn.net/eagle_min/article/details/82260622， 但是有些IP会返回502.....

**Comment by nondanee** [comment]
你这个不是已经很详细吗？
https://ipinfo.io/AS37963

**Comment by zluo01** [comment]
double check
