### ISSUE TITLE
关注用户似乎有些问题，执行接口但无效

### ISSUE THREAD

**Issue by huiBuiling** [Binaryify/NeteaseCloudMusicApi#443]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by huiBuiling** [comment]
执行关注用户接口，返回成功信息但是状态还未改变

**Comment by Binaryify** [comment]
缓存问题吧，再看看文档吧
