### ISSUE TITLE
请问网易云音乐API文档是怎样生成的啊

### ISSUE THREAD

**Issue by dogfeeling** [Binaryify/NeteaseCloudMusicApi#444]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=关于此文档
