### ISSUE TITLE
Getting 403 error while accessing picUrl

### ISSUE THREAD

**Issue by upendra-web** [Binaryify/NeteaseCloudMusicApi#446]
When I am trying to access picture album using the 'latest album' interface, I am getting 403 error. Any idea to bypass this error?

**Chrome Dev tools error:**
![screenshot 105](https://user-images.githubusercontent.com/43108965/53687199-b2a33400-3d57-11e9-977a-5231f87d3ddc.png)

**Browser Error**
![screenshot 106](https://user-images.githubusercontent.com/43108965/53687200-b33bca80-3d57-11e9-8ebb-049fc4a38b48.png)

**Comment by nondanee** [comment]
#337 #371 #383 #425

**Comment by upendra-web** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/383#issuecomment-449647505

☝️ Solved issue by adding meta tags in client code (Vue), mentioned in the above comment, Thank you!

**Comment by upendra-web** [comment]
Some images are loading and some are showing the below error.

![screenshot 107](https://user-images.githubusercontent.com/43108965/53691685-1e61bd00-3da9-11e9-9539-1b2c4b7954c1.png)

**Comment by nondanee** [comment]
Try testing with mainland proxy, maybe due to CDN fault.
