### ISSUE TITLE
前几天api出现一个400问题，请求失败，麻烦修复下

### ISSUE THREAD

**Issue by 082530** [Binaryify/NeteaseCloudMusicApi#447]
### 环境
系统:

nodejs 版本:

### 出现问题
http://localhost:3000/mv/detail?mvid=55505FCE74DFA8223EDC294F847CF25E
api接口出现400的错误

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
你这个是 video id，用 `/video/detail ` 接口
另外，4xx 是客户端的问题，不是服务器的问题，400 意为 bad request
> https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
> The 4xx class of status code is intended for cases in which the client seems to have erred
