### ISSUE TITLE
你好，请问有注册接口吗

### ISSUE THREAD

**Issue by shengjiong** [Binaryify/NeteaseCloudMusicApi#448]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
(感觉像羊毛党的需求......

**Comment by Binaryify** [comment]
没有，以后应该也不会有

**Comment by Binaryify** [comment]
v3.8.0 已经加入注册相关接口
