### ISSUE TITLE
 "所有榜单内容摘要" 即/toplist/detail 接口返回值中 tracks内容不全

### ISSUE THREAD

**Issue by peoplewhoneedstruggle** [Binaryify/NeteaseCloudMusicApi#449]
### 环境
系统:
windows10

nodejs 版本: 
V8.10.0

### 出现问题 
 "所有榜单内容摘要"返回值内容不全

### 重现步骤  
调用/toplist/detail 接口时
![image](https://user-images.githubusercontent.com/27265060/54185648-8a989b00-44e4-11e9-8d4a-69c7b88697e7.png)

### 期待效果
返回值中
所有榜单都应该有tracks数据，即榜单中前3位歌手的姓名和歌曲名称
但是返回值中只有前4个榜单有相应数据，后面的榜单一律没有，如下图
![image](https://user-images.githubusercontent.com/27265060/54186409-4b6b4980-44e6-11e9-9f65-ae2cc83d49c7.png)

**我调用/top/list?idx=1是可以拿到数据的**，不知道这是不是属于异常现象，希望能在
**/toplist/detail 接口**上每个榜单都能添加上前三首歌的tracks信息，

在此感谢作者提供的Api以及代码的维护工作

**Comment by nondanee** [comment]
正常行为，官方就是如此（畅销榜是新增的）
tracks 信息自己请求就行了，没有捷径

![result-2019-03-13-15-27-39](https://user-images.githubusercontent.com/26399680/54260739-c72bcb80-45a4-11e9-882a-2662921142d0.jpg)

**Comment by peoplewhoneedstruggle** [comment]
收到，感谢回复。

**Comment by zion223** [comment]
推荐榜 全球榜 和更多榜单在请求的数据中有什么顺序规律吗  我看数据不是按照推荐榜 全球榜 更多榜单排列的
