### ISSUE TITLE
高频访问/user/detail导致-460,24小时仍未恢复

### ISSUE THREAD

**Issue by 1368129224** [Binaryify/NeteaseCloudMusicApi#450]
### 环境
系统:win10

nodejs 版本:v10.13.0

### 出现问题
高频访问/user/detail导致
```
    "code": -460,
    "msg": "Cheating"
```
24小时后仍未恢复

### 重现步骤
高频访问/user/detail
### 期待效果
寻求解决方法

**Comment by nondanee** [comment]
可以尝试
- 把 `X-Real-IP` 改成别的 #442 
- 同 IP 下在网页版上用自己账号登录一次（看看正常行为可不可以解封）

丢人==
