### ISSUE TITLE
歌单详情超过1000如何获取

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#452]
### 环境
系统:
Mac OS X 10.12.6

nodejs 版本:
v10.15.3

### 出现问题
歌单歌曲超过 1000 如何获取，登录状态和非登录状态都只能获取1000首
现在用的 API 版本：3月17日clone下来的
上两个issue已经看过了，这个问题还在
问题歌单：544215255
截图：https://imgchr.com/i/Amdvbq

### 期待效果
是有分页选项么

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
确实又出现这个问题了，晚点看看怎么解决

**Comment by kurodaakira-jp** [comment]
> 确实又出现这个问题了，晚点看看怎么解决

我看网易web版也是只有1000，也没有下一页什么的，不知道是不是网易的问题
还有个发现，就是有些歌没版权，但是App就可以播，比如【盾之勇者的ED】

**Comment by kurodaakira-jp** [comment]
> 确实又出现这个问题了，晚点看看怎么解决

歌单的收藏者只能获取20个，有没有专门获取这个的api

**Comment by nondanee** [comment]
之前抓包看过网易云 Windows 客户端的官方实现
它请求一次 500 首的 playlist/detail 再拿全部 trackIds 请求一次 `song/detail`

**Comment by nondanee** [comment]
@kurodaakira-jp 有的
```
/weapi/playlist/subscribers 
{
  id: <id>,
  limit: <limit>,
  offset: <offset>
}
```

**Comment by nondanee** [comment]
去看了下 UWP 客户端实现，也差不多
`/api/playlist/detail/dynamic` 这个是歌单收藏播放等等的计数

![show](https://user-images.githubusercontent.com/26399680/54587020-ce961d80-4a59-11e9-80e4-4a43a685be34.png)

**Comment by kurodaakira-jp** [comment]
> 之前抓包看过网易云 Windows 客户端的官方实现
> 它请求一次 500 首的 `playlist/detail` 再拿全部 trackIds 请求一次 `song/detail`

**Comment by kurodaakira-jp** [comment]
> 去看了下 UWP 客户端实现，也差不多
> `/api/playlist/detail/dynamic` 这个是歌单收藏播放等等的计数
> 
> ![show](https://user-images.githubusercontent.com/26399680/54587020-ce961d80-4a59-11e9-80e4-4a43a685be34.png)

拿id请求好几百，要是网不好怕不是得等上几分钟😂

**Comment by nondanee** [comment]
不会的，`playlist/detail` 的 response body 比这个 request body 大的多的多

**Comment by Binaryify** [comment]
@nondanee 
官方居然这么暴力的做法 o.o

**Comment by kurodaakira-jp** [comment]
> @nondanee
> 官方居然这么暴力的做法 o.o

/playlist/subscribers  这个 API 有空加一下呗！！🤔

**Comment by Binaryify** [comment]
@kurodaakira-jp 加上了，更新下

**Comment by 759036585** [comment]
![image](https://user-images.githubusercontent.com/55939674/74598306-55a8a700-50aa-11ea-87d4-11588c042519.png)
这里面数据都代表什么。。。

**Comment by nondanee** [comment]
@759036585 我也想知道==

**Comment by Mamong** [comment]
这个接口挺狗屎的。。另外我服务器上这个接口特别慢，不是数据大小的原因。好像查询很慢？？

**Comment by kurodaakira-jp** [comment]
> ![image](https://user-images.githubusercontent.com/55939674/74598306-55a8a700-50aa-11ea-87d4-11588c042519.png)
> 这里面数据都代表什么。。。

开局一个api，字段全靠猜

你可以参考我开源了的复刻网易云音乐，我觉得我猜的大多数应该都是对的，至少展示出来的样子是和官方的是一样的23333

**Comment by fivegg** [comment]
现在返回的歌单只有10条歌曲详情。拿全部 trackIds 请求一次 song/detail会timeout，也不行啊

**Comment by Binaryify** [comment]
@fivegg timeout 是你请求库设置的吧

**Comment by fivegg** [comment]
> @fivegg timeout 是你请求库设置的吧

我直接使用的netmusic-node代码，多id取歌曲详情用的你的代码。用浏览器测试，如果带2，3个id可以较快时间返回，如果带多个，例如10个，就60秒都返回不了。
//多曲详情
app.get(dir + '/allmusic/detail', function (request, response) {
	const ids = request.query.ids.split(/\s*,\s*/)
	const data = {
		c: '[' + ids.map(id => ('{"id":' + id + '}')).join(',') + ']',
		ids: '[' + ids.join(',') + ']'
	}
	var cookie = request.get('Cookie') ? request.get('Cookie') : (request.query.cookie ? request.query.cookie : '');
	createWebAPIRequest('/weapi/v3/song/detail', data, cookie, response)
});

**Comment by nondanee** [comment]
@fivegg 
60 秒都返回不了大概因为这个重试机制
https://github.com/sqaiyan/netmusic-node/blob/2ef7b383ef3f5b7dae74d448806dbc9e67061b6b/app.js#L48-L51

返回空数据应该是加密加得有问题

https://github.com/sqaiyan/netmusic-node/blob/2ef7b383ef3f5b7dae74d448806dbc9e67061b6b/app.js#L65
这个地方改成这样试一下

```diff
- http_client.write('params=' + cryptoreq.params + '&encSecKey=' + cryptoreq.encSecKey);
+ http_client.write('params=' + encodeURIComponent(cryptoreq.params) + '&encSecKey=' + encodeURIComponent(cryptoreq.encSecKey));
```

**Comment by repursue** [comment]
> 之前抓包看过网易云 Windows 客户端的官方实现
> 它请求一次 500 首的 `playlist/detail` 再拿全部 trackIds 请求一次 `song/detail`

UWP版本的好像就是直接获取的, 但是加密和eapi有点不太一样,大佬有了解过吗

**Comment by Terry-007** [comment]
> 之前抓包看过网易云 Windows 客户端的官方实现
> 它请求一次 500 首的 `playlist/detail` 再拿全部 trackIds 请求一次 `song/detail`

如何拿这个trackids一次性请求 `song/detail`呢

**Comment by Gaoyanpu111** [comment]
![图片](https://user-images.githubusercontent.com/70064688/96757281-cd805b80-1407-11eb-9ae0-4edf05f5d534.png)
全部新碟接口用不了

**Comment by zyf412** [comment]
![image](https://user-images.githubusercontent.com/87595743/145052698-5794c531-65c1-48d7-acbf-b6473ff4b686.png)

**Comment by JerseyW** [comment]
这个接口是不是报废了，怎么404呢
`getSongListDetail(id){
       const  detailData = utils.request('/playlist/detail',{id});
       console.log(detailData)
    },
    onLoad: function (options) {

        let info = wx.getStorageSync('storage_user_info');
        this.setData({
            userInfo:JSON.parse(info)
        } )

        this.getSongListDetail(this.data.userInfo.userId);
    }`

**Comment by Gaoyanpu111** [comment]
应该是的，我现在也是404





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌单详情超过1000如何获取 (#452)





 
这个接口是不是报废了，怎么404呢
 `getSongListDetail(id){
 const  detailData = utils.request('/playlist/detail',{id});
 console.log(detailData)
 },
 onLoad: function (options) {
     let info = wx.getStorageSync('storage_user_info');     this.setData({         userInfo:JSON.parse(info)     } )     this.getSongListDetail(this.data.userInfo.userId); }`  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gaoyanpu111** [comment]
说明 : 歌单能看到歌单名字, 但看不到具体歌单内容 , 调用此接口 , 传入歌单 id, 可 以获取对应歌单内的所有的音乐(未登录状态只能获取不完整的歌单,登录后是完整的)，但是返回的 trackIds 是完整的，tracks 则是不完整的，可拿全部 trackIds 请求一次&nbsp;song/detail&nbsp;接口获取所有歌曲的详情&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 晚上10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌单详情超过1000如何获取 (#452)





 

 现在是部分都获取不到了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SnowingFox** [comment]
https://neteasecloudmusicapi.vercel.app/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e5%8d%95%e6%89%80%e6%9c%89%e6%ad%8c%e6%9b%b2
可以看看我实现的

**Comment by SnowingFox** [comment]
https://neteasecloudmusicapi.vercel.app/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e5%8d%95%e6%89%80%e6%9c%89%e6%ad%8c%e6%9b%b2
可以看看我实现的功能

**Comment by FuchengQin** [comment]
> ![image](https://user-images.githubusercontent.com/78540954/147574725-a4b73f96-23e6-4eb4-83cb-e3e51b33c25c.png) 现在是部分都获取不到了吗

直接调登录接口就行啊

**Comment by FuchengQin** [comment]
> ![image](https://user-images.githubusercontent.com/87595743/145052698-5794c531-65c1-48d7-acbf-b6473ff4b686.png)

大佬，这里的完整代码能不能看一下，我老是不知道取数据

**Comment by sometimeQ** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/15411257/170984497-45001923-afaf-44db-bdba-d1ce3fce2c31.png">
报错了

**Comment by sometimeQ** [comment]
> 

是直接请求的，报错说要在app内打开验证，我这是pc端的

**Comment by FuchengQin** [comment]
你估计接口调错了，好好看下接口，这个我也是搞了一个多小时,接口有点乱看下你要的数据结构，字段




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 晚上7:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌单详情超过1000如何获取 (#452)





   
是直接请求的，报错说要在app内打开验证，我这是pc端的

**Comment by sometimeQ** [comment]
> 有点

谢谢亲，莫名其妙又好了。

**Comment by FuchengQin** [comment]
uniapp 请求携带cookie,怎么弄的，我报错，Refused to set unsafe header "cookie"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌单详情超过1000如何获取 (#452)





  
有点
  
谢谢亲，莫名其妙又好了。

**Comment by Binaryify** [comment]
@FuchengQin 直接当参数传

**Comment by FuchengQin** [comment]
> @FuchengQin 直接当参数传
咋传，我请求都是封装好的，当参数传过去，在请求头那里能看到传的cookie吗，我看大多数都是在封装的请求里面弄

**Comment by Binaryify** [comment]
@FuchengQin 不是请求头，直接普通参数里带上，每个请求都带

**Comment by schatz7** [comment]
> <img alt="image" width="1067" src="https://user-images.githubusercontent.com/15411257/170984497-45001923-afaf-44db-bdba-d1ce3fce2c31.png">
> 
> 报错了

老哥，咱俩做的项目一样，错误也一样，你是怎么解决的

**Comment by schatz7** [comment]
![image](https://user-images.githubusercontent.com/93331702/173975617-0bf5b46c-72d8-45b4-bfda-d520a1a528cf.png)
昨天还能请求到的，昨晚就不行了

**Comment by sometimeQ** [comment]
> > <img alt="image" width="1067" src="https://user-images.githubusercontent.com/15411257/170984497-45001923-afaf-44db-bdba-d1ce3fce2c31.png">
> > 报错了
> 
> 老哥，咱俩做的项目一样，错误也一样，你是怎么解决的

暂时没解决，我也是之前还行的，忽然之间就这样了

**Comment by schatz7** [comment]
> 

![image](https://user-images.githubusercontent.com/93331702/173976700-5d83ab7b-a161-4985-ae97-4c8aa0d964ff.png)
我看了别人的项目，这个排行榜也是请求不到数据了，可能是接口有问题了吧

**Comment by sometimeQ** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/93331702/173976700-5d83ab7b-a161-4985-ae97-4c8aa0d964ff.png) 我看了别人的项目，这个排行榜也是请求不到数据了，可能是接口有问题了吧

但是官方的也可以呀。哈哈，没搞懂，我跳过这个做其他的去了

**Comment by 0-gain** [comment]
> ![image](https://user-images.githubusercontent.com/93331702/173975617-0bf5b46c-72d8-45b4-bfda-d520a1a528cf.png) 昨天还能请求到的，昨晚就不行了

现在解决了嘛

**Comment by sometimeQ** [comment]
> > ![image](https://user-images.githubusercontent.com/93331702/173975617-0bf5b46c-72d8-45b4-bfda-d520a1a528cf.png) 昨天还能请求到的，昨晚就不行了
> 
> 现在解决了嘛

下载到本地，就好了

**Comment by 0-gain** [comment]
> 

怎么下载到本地啊

**Comment by 0-gain** [comment]
> > > ![image](https://user-images.githubusercontent.com/93331702/173975617-0bf5b46c-72d8-45b4-bfda-d520a1a528cf.png) 昨天还能请求到的，昨晚就不行了
> > 
> > 
> > 现在解决了嘛
> 
> 下载到本地，就好了

怎么下载到本地啊

**Comment by sometimeQ** [comment]
> 

git clone 地址, 然后node app.js运行

**Comment by 0-gain** [comment]
是下载api文件嘛，还是哪个地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌单详情超过1000如何获取 (#452)





   
git clone 地址, 然后node app.js运行

**Comment by 0-gain** [comment]
> > 
> 
> git clone 地址, 然后node app.js运行

下载api文件嘛

> > 
> 
> git clone 地址, 然后node app.js运行

clone api文件下来嘛

**Comment by 0-gain** [comment]
> > 
> 
> git clone 地址, 然后node app.js运行

clone 哪个地址啊

**Comment by 0-gain** [comment]
> > 
> 
> 是直接请求的，报错说要在app内打开验证，我这是pc端的

你这是怎么解决的

**Comment by leessmin** [comment]
我也是，请求收藏别人的页面只能找到20首歌，但是自己的歌单能找到全部

**Comment by charonycl** [comment]
![image](https://user-images.githubusercontent.com/84052152/231150103-b56ca3ba-b95e-4582-a9e8-baa61b0ba322.png)
为什么访问不了这个接口呀

**Comment by xin99zhang** [comment]
![image](https://user-images.githubusercontent.com/100652385/231467318-3dd84227-3929-4148-84f7-6682d911caf8.png)
这个接口频繁了

**Comment by xin99zhang** [comment]
![image](https://user-images.githubusercontent.com/100652385/231467815-f4499955-c63e-4c2f-a24e-a08a08bff318.png)
![image](https://user-images.githubusercontent.com/100652385/231467884-0591ed32-73ee-486d-ba42-cbbf0d57e197.png)
频繁了这个接口
