### ISSUE TITLE
喜欢音乐接口文档与实际行为不符

### ISSUE THREAD

**Issue by Y-qwq** [Binaryify/NeteaseCloudMusicApi#453]
### 环境
系统:win10

nodejs 版本:v10.14.1

NeteaseCloudMusicApi版本:v3.6.0

### 出现问题
喜欢音乐接口文档与实际行为不符。

> like: 布尔值 , 默认为 true 即喜欢 , 若传 false, 则取消喜欢

实际传参like=false才是喜欢，不传like是取消喜欢，like=true好像没啥效果
以上均是加了时间戳的情况下测试得出的结果。

**Comment by Binaryify** [comment]
这里确实存在问题，准备修复了

**Comment by Binaryify** [comment]
已修复
