### ISSUE TITLE
获取播放记录，接口返回的playCount全是0

### ISSUE THREAD

**Issue by Izayawww** [Binaryify/NeteaseCloudMusicApi#455]
### 环境
系统:mac

nodejs 版本:
v10.15.2
### 出现问题
获取播放记录，接口返回的playCount全是0
### 重现步骤
/user/record?uid=111736605&type=1
### 期待效果
playCount返回正确结果
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by nondanee** [comment]
只能看到自己的 playCount，别的用户是用 score 来表示的，没有具体数字，你可以在网页版上测试一下
自己的 playCount 需要登录带 cookie
大部分人设置了仅关注的人可见或仅自己可见，无法看到听歌记录

**Comment by Izayawww** [comment]
🏄‍♀️好了
