### ISSUE TITLE
如何获取用户收藏的歌单总量

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#456]
### 环境
系统:
Max OS 10.12.6

nodejs 版本:
v10.15.3

### 出现问题
没有找到用户收藏的歌单总量的字段，user/detail里只有自己创建的总量，网易web版也没找到哪里包含这个的字段

### 期待效果
有此字段

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
/user/playlist 不是有吗,数组长度,也可以根据创建者过滤

**Comment by kurodaakira-jp** [comment]
我指的是一次性获取总数量的数字

**Comment by Binaryify** [comment]
官方的就这样，长度也一样的
