### ISSUE TITLE
获取评论的分页请求有问题

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#457]
### 环境
系统:
Max OS X 10.12.6

nodejs 版本:
v10.15.3

### 出现问题
一共51条评论，limit设置的20，offset每次都有加1，但是请求N次以后，里面的more一直都是true，并且数据重复

### 期待效果
每次分页请求不重复

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
好好想想offset是干什么的吧

**Comment by boyan01** [comment]
offset不是page,细说不是胡说.

**Comment by kurodaakira-jp** [comment]
> offset不是page,细说不是胡说.

。。。好吧，当page用了
