### ISSUE TITLE
使用电台节目里面的歌曲 id 拿不到地址

### ISSUE THREAD

**Issue by Aifcce** [Binaryify/NeteaseCloudMusicApi#458]
### 环境
系统:
deepin
nodejs 版本:

### 出现问题
使用电台节目里面的歌曲 id 拿不到地址
### 重现步骤
歌曲地址
https://music.163.com/#/program?id=2059481077
请求结果
![image](https://user-images.githubusercontent.com/34526533/55535080-a872ad80-56e8-11e9-8760-53d7af1ad7a6.png)
使用以下外链也拿不到链接
https://music.163.com/song/media/outer/url?id=2059481077.mp3

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
你那个 id 怎么获取的

**Comment by Aifcce** [comment]
> 你那个 id 怎么获取的

我直接就是在浏览器里面拿到了

**Comment by Binaryify** [comment]
那个不是 id

**Comment by Aifcce** [comment]
> 那个不是电台的 id

这个不是电台的id， 这个是电台里面一期节目的 id， 如果这个 id 不正确，我应该怎么拿到正确的id
如果我想拿到如下电台所有节目的 歌曲链接 应该怎么做。
https://music.163.com/#/djradio?id=346002064
上面拿不到结果的 id 是通过点进一期节目，然后从上面url 链接拿到的。

**Comment by Binaryify** [comment]
应该说是你得拿里面的节目的 id 去获取，song/url 是获取单个的
![image](https://user-images.githubusercontent.com/12221718/55538032-0f479500-56f0-11e9-9e50-c64393ebdf64.png)
![image](https://user-images.githubusercontent.com/12221718/55538046-15d60c80-56f0-11e9-8795-95aeb4d42d3d.png)

**Comment by Aifcce** [comment]
> 应该说是你得拿里面的节目的 id 去获取，song/url 是获取单个的
> ![image](https://user-images.githubusercontent.com/12221718/55538032-0f479500-56f0-11e9-9e50-c64393ebdf64.png)
> ![image](https://user-images.githubusercontent.com/12221718/55538046-15d60c80-56f0-11e9-8795-95aeb4d42d3d.png)

非常感谢，我已经明白怎么拿到我想要的地址了。谢谢
