### ISSUE TITLE
登入時發生錯誤

### ISSUE THREAD

**Issue by gnehs** [Binaryify/NeteaseCloudMusicApi#459]
### 环境
系统: alpine(docker)

nodejs 版本: 10.15.3
NeteaseCloudMusicApi 版本: 3.7.0
### 出现问题
以 Email 登入時出現 `{"code":-460,"msg":"Cheating"}` 錯誤
### 重现步骤
以 Email 登入
### 期待效果
正常登入

**Comment by tianjianen** [comment]
同样登录时发生错误,所使用的 NeteaseCloudMusicApi 版本为3.1.0

**Comment by nondanee** [comment]
左上角搜索 "os=pc" in this repository，把 cookie 那行加上

**Comment by nondanee** [comment]
@Binaryify 有空修一下

**Comment by Binaryify** [comment]
@gnehs @tianjianen @nondanee 
 已修复
