### ISSUE TITLE
使用手机登录的时候报“登录异常”错误，code码为250

### ISSUE THREAD

**Issue by lsqy** [Binaryify/NeteaseCloudMusicApi#463]
### 环境
系统:
win10

nodejs 版本:
v10.14.1

### 出现问题
今天在调用手机登录接口的时候突然报了{message: "登录异常", code: 250}这个错误，以前没有遇到这个错误

![image](https://user-images.githubusercontent.com/18533232/56420645-6abd7980-62d1-11e9-97b4-48c67e550cd5.png)

### 期待效果
期待还可以正常登陆

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by fengzhengkeji** [comment]
是的，今天发现了，和token有关

**Comment by lsqy** [comment]
@fengzhengkeji 今天我在我的mac上调用登陆接口可以成功了，有可能昨天是网易云音乐后台校验登陆导致的
