### ISSUE TITLE
"code":502 Hostname/IP does not match certificate's

### ISSUE THREAD

**Issue by merry1997** [Binaryify/NeteaseCloudMusicApi#465]
系统: MacOS

nodejs 版本: v11.6.0

### 出现问题
报502错误
### 重现步骤
1、npm start || node app
2、调用测试接口或执行npm test
3、返回：{
                    "code":502,
                    "msg":"Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: music.163.com. is not in the cert's altnames: DNS:fjm.name, DNS:www.fjm.name\n    at Object.checkServerIdentity (tls.js:245:17)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1148:27)\n    at TLSSocket.emit (events.js:188:13)\n    at TLSSocket._finishInit (_tls_wrap.js:627:8)"
                    }

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/56480125-4c32ca80-64eb-11e9-805d-714fb0fa3a1e.png)
检查你的 DNS 或者代理
