### ISSUE TITLE
axios请求登陆状态报错301，在浏览器访问正常200

### ISSUE THREAD

**Issue by lvanboy** [Binaryify/NeteaseCloudMusicApi#466]
### 环境
系统:
window10
nodejs 版本:
v10.5
### 出现问题
axios添加了响应拦截器，对登陆状态请求时，进行了错误拦截，状态301，显示没有登陆，但已经使用axios调用了登陆接口，并且登陆正常。使用浏览器正常访问登陆状态接口时，可以正常返回数据，请问这是什么问题？我查看了请求头，在axios发送登陆状态请求时，没有携带cookie。浏览器访问登陆接口时，携带了cookie。
### 期待效果
获取登陆后的，登陆状态。
>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
文档有说明

**Comment by powerdong** [comment]
@lvanboy  之后怎么解决的呢  我现在也遇到了这个问题
