### ISSUE TITLE
歌词获取 code400

### ISSUE THREAD

**Issue by JasmineRain** [Binaryify/NeteaseCloudMusicApi#468]
### 环境
系统:
WINDOWS 10

nodejs 版本:
8.9.4

### 出现问题
歌词获取模块返回
code: 400
message: "Required long parameter 'id' is not present"

### 重现步骤
以为是我自己的错误，但是我直接把源码clone并跑起来以后，照着api访问http://localhost:3000/lyric?id=33894312
也出现了 code:400的上述结果，我确定我加了参数id，并且几天前获取结果都是正常的

### 期待效果
正确获取歌词

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by JasmineRain** [comment]
并且跑起来后访问api时的console输出是：
[ERR] /lyric?id=33894312
[ERR] /lyric?id=1313354324
[ERR] /lyric?id=1313354324

**Comment by Binaryify** [comment]
确实有问题，网易那边又改东西了，等下修复

**Comment by DaikonX** [comment]
就说我也400了

**Comment by Binaryify** [comment]
已修复

**Comment by wangzuo** [comment]
多谢!
