### ISSUE TITLE
获取歌词的接口崩了？？，希望赶紧修复，我很着急😣

### ISSUE THREAD

**Issue by xieyezi** [Binaryify/NeteaseCloudMusicApi#470]
### 环境
系统:Mac os Majave 10.14

nodejs 版本:
v9.3.0
### 出现问题
获取歌词接口崩了！！
### 重现步骤
http://localhost:3000/lyric?id=33894312
### 期待效果
![image](https://user-images.githubusercontent.com/16821989/56786227-d56b3980-682a-11e9-91d3-8e7aae503d75.png)

返回歌词数据失败，出现404错误，希望赶紧修复，比较着急，就要去答辩了，呜呜呜
>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
更新到 3.8.1 了吗

**Comment by xieyezi** [comment]
哦哦，还没，我马上更新一下，谢谢你这么快就回复我

**Comment by xieyezi** [comment]
解决了，衷心感谢你！！谢谢谢谢🙏
