### ISSUE TITLE
/song/detail 接口異常

### ISSUE THREAD

**Issue by gnehs** [Binaryify/NeteaseCloudMusicApi#471]
### 环境
系统: alpine(docker)
nodejs 版本: 10.15.3
NeteaseCloudMusicApi 版本: 3.8.1
### 出现问题
` {"code":-460,"msg":"Cheating"}`

<img width="353" alt="圖片" src="https://user-images.githubusercontent.com/16719720/56810482-fc486080-6868-11e9-946a-18ec3f2f305d.png">

### 重现步骤
/song/detail?ids=1309144430

**Comment by Binaryify** [comment]
song_detail.js 加上 query.cookie.os = 'pc' 看上会不会正常

**Comment by gnehs** [comment]
![圖片](https://user-images.githubusercontent.com/16719720/56844166-939bcb00-68de-11e9-971a-12f897666b05.png)
我沒改東西，他好像自己好了(?
