### ISSUE TITLE
vip 单曲 url 无法播放 账户信息为 vip用户

### ISSUE THREAD

**Issue by WeiYYin** [Binaryify/NeteaseCloudMusicApi#473]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
cookies 带上了吗

**Comment by WeiYYin** [comment]
带了 cookies  , 其他url 都可以播放。 这个 一开始请求的 url 403 然后换了 那个 id 的url 结果就404了

**Comment by WeiYYin** [comment]
今天又可以播放了。。。。。   0.0  可能网易的原因吧

**Comment by Binaryify** [comment]
嗯
