### ISSUE TITLE
没有能够获取被版权的歌曲吧

### ISSUE THREAD

**Issue by shanghai-Jerry** [Binaryify/NeteaseCloudMusicApi#474]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
没
