### ISSUE TITLE
发送验证码API参数错误

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#475]
### 环境
系统: 
Mac

nodejs 版本: 
v10.15.3

### 出现问题
请求发送验证码的api，后端返回{code: 400 msg: "参数错误"}，但是cellphone和stcode都有传值，get和post都一样，如何解决

### 期待效果
正常请求

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
我文档写错了，应该是 phone 不是 cellphone

**Comment by kurodaakira-jp** [comment]
OK了！
