### ISSUE TITLE
这个必须自己搭建一套么，有没有可以直接访问的地址

### ISSUE THREAD

**Issue by zwmmm** [Binaryify/NeteaseCloudMusicApi#476]
### 环境
系统:

nodejs 版本:

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by WeiYYin** [comment]
本地跑起来就可以用了  或者在服务器上跑起来

**Comment by kurodaakira-jp** [comment]
这也要白嫖。。。
