### ISSUE TITLE
登录状态api数据异常

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#477]
### 环境
系统:
Mac OS X 10.12.6

nodejs 版本:
10.15.3

### 出现问题
请求api正常200，但是profile里面什么数据都没有，之前的话会有uid等一些数据，现在变成了这个样子【{"code":200,"profile":{},"bindings":[]}】

### 期待效果
至少能拿到个uid

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by kurodaakira-jp** [comment]
昨天还可以，今天就出问题了

**Comment by nondanee** [comment]
emmm 这个接口自制的，要看页面结构，我回去看看
你可以先用 `/weapi/user/info` ，不需要 data (你自己先加一个 route)

**Comment by nondanee** [comment]
我试了几次 `/login/status` 这个接口也没出什么问题......
如果不放心的话你可以换用官方的 `/user/info` 取登录用户的 ID
```javascript
// 用户信息

module.exports = (query, request) => {
    return request(
        'POST', `https://music.163.com/weapi/user/info`, {},
        {crypto: 'weapi', cookie: query.cookie, proxy: query.proxy}
    )
}
```

**Comment by kurodaakira-jp** [comment]
试了一下，user/info这个302了

**Comment by nondanee** [comment]
我这里挺正常的==
302 重定向的 location 是啥？

**Comment by kurodaakira-jp** [comment]
![スクリーンショット 0031-05-05 18 21 08](https://user-images.githubusercontent.com/38561128/57192417-becb8d80-6f62-11e9-9db7-66d3a267b6ae.png)
请求是这样的

**Comment by nondanee** [comment]
不知道了==
我这边挺正常的
没登录是 301 不是 302

让 @Binaryify 试试吧
可以用的话就加上

**Comment by Binaryify** [comment]
@kurodaakira-jp 你那是文件都没加吧

**Comment by Binaryify** [comment]
@kurodaakira-jp 你的服务端环境是怎样的

**Comment by kurodaakira-jp** [comment]
文件没加也不会出现403啊，只会出现Cannot GET /xxx，我换了个环境可以了
