### ISSUE TITLE
post请求缓存有问题

### ISSUE THREAD

**Issue by zzy213326** [Binaryify/NeteaseCloudMusicApi#478]
### 环境
系统:CentOS Linux 7.3.1611 (Core)

nodejs 版本:1.15.9

### 出现问题
通过post获取/playlist/detail,在一段时间内始终是一样的,虽然request body里面的id已经修改了,但是数据依然是上次的id所请求的数据

### 重现步骤
1.post请求/playlist/detail ,data:{"id":"531321323"},返回歌单:playlist.name="将回忆酿成烈酒入喉 从此不再挽留不再回头"
2.post请求/playlist/detail ,data:{"id":"704472404"},返回歌单:playlist.name="将回忆酿成烈酒入喉 从此不再挽留不再回头"

### 期待效果
post请求/playlist/detail ,data:{"id":"704472404"},返回歌单:playlist.name="愿你最初的等待，也是最后的相爱"

**Comment by kurodaakira-jp** [comment]
app.use(cache('2 minutes', ((req, res) => res.statusCode === 200)))
把这个注释掉试试

**Comment by zzy213326** [comment]
> app.use(cache('2 minutes', ((req, res) => res.statusCode === 200)))
> 把这个注释掉试试

可以了!!!!多谢!!!

**Comment by zzy213326** [comment]
> app.use(cache('2 minutes', ((req, res) => res.statusCode === 200)))
> 把这个注释掉试试

虽然问题临时解决了,但是我觉得这样依然是有问题的,感觉缓存的命中依据是url,post请求url始终保持一致,导致取得的缓存是有问题的

**Comment by nondanee** [comment]
浏览器不会缓存任何 post 请求，url 一样没有问题

**Comment by Binaryify** [comment]
文档已经提到了,要加时间戳
