### ISSUE TITLE
貌似网易改了API 了都获取不到音乐地址了

### ISSUE THREAD

**Issue by markruan** [Binaryify/NeteaseCloudMusicApi#48]
貌似网易改了API 了都获取不到音乐地址了

**Comment by ZionLife** [comment]
歌曲的URL？可以吧。

**Comment by markruan** [comment]
url 为空

**Comment by Binaryify** [comment]
@markruan 
能否提供具体信息和复现

**Comment by markruan** [comment]
{
name: "海阔天空",
id: 347230,
pst: 0,
t: 0,
ar: [
{
id: 11127,
name: "Beyond",
tns: [ ],
alias: [ ]
}
],
alia: [ ],
pop: 100,
st: 0,
rt: "600902000004240302",
fee: 0,
v: 17,
crbt: null,
cf: "",
al: {
id: 34209,
name: "海阔天空",
picUrl: "http://p1.music.126.net/QHw-RuMwfQkmgtiyRpGs0Q==/102254581395219.jpg",
tns: [ ],
pic: 102254581395219
},
dt: 326348,
h: {
br: 320000,
fid: 0,
size: 13070578,
vd: 0.109906
},
m: {
br: 160000,
fid: 0,
size: 6549371,
vd: 0.272218
},
l: {
br: 96000,
fid: 0,
size: 3940469,
vd: 0.228837
},
a: null,
cd: "",
no: 1,
rtUrl: null,
ftype: 0,
rtUrls: [ ],
djId: 0,
copyright: 1,
s_id: 0,
mst: 9,
cp: 1003,
mv: 376199,
rtype: 0,
rurl: null
}
],

**Comment by markruan** [comment]
rturl 是mp3地址吧？

**Comment by Binaryify** [comment]
@markruan 
你得调 `/music/url` 这个接口
