### ISSUE TITLE
增加新的接口不成功

### ISSUE THREAD

**Issue by HIjack2015** [Binaryify/NeteaseCloudMusicApi#483]
### 环境
系统:  windows10

开发者您好，我在尝试增加一个'转发动态'的接口。
并进行了如下步骤。
1. 在网易云音乐的网站上转发时下js断点，找出转发的相应参数
![image](https://user-images.githubusercontent.com/10767193/57290852-dfc1e900-70f0-11e9-95aa-77d7b9e8aaf5.png)
里边的参数分别为 forwards 转发内容，  id：要转发的动态id，eventUserId:要转发的用户id
还有一个checkToken 根据之前您的issue 可以用os=pc绕过去。
2. 在代码module文件夹下新建forward.js 内容如下

```
// 转发动态

const crypto = require('crypto')

module.exports = (query, request) => {
    query.cookie.os = 'pc'
    const data = {
		forwards: query.forwards,
		id: query.id,
        eventUserId: query.eventUserId,
    }
    return request(
        'POST', `https://music.163.com/weapi/event/forward`, data,
        {crypto: 'weapi', ua: 'pc', cookie: query.cookie, proxy: query.proxy}
    )
}
```
然后在启动程序，登录，调用接口
结果如下：
![image](https://user-images.githubusercontent.com/10767193/57291256-ab9af800-70f1-11e9-8ddf-a7ef11587c6f.png)

我是一个新手，请问我哪里错了 ：》

**Comment by HIjack2015** [comment]
额，，重启应用没用。。关机过了两小时自己好了。。。如有打扰深表抱歉。

**Comment by boyan01** [comment]
把新增的接口PR到这个库里面来呗~

**Comment by HIjack2015** [comment]
> 把新增的接口PR到这个库里面来呗~
嗯嗯 我pr了，不过没改文档。是不是该把文档改了一起pr？

**Comment by HIjack2015** [comment]
> 把新增的接口PR到这个库里面来呗~

嗯嗯 我pr了，不过没改文档。是不是该把文档改了一起pr？

**Comment by boyan01** [comment]
不用改文档。 @Binaryify 会处理的

**Comment by Binaryify** [comment]
已更新

**Comment by Binaryify** [comment]
@HIjack2015 想请教下你的打断点的过程是怎样的

**Comment by Binaryify** [comment]
@HIjack2015 
![image](https://user-images.githubusercontent.com/12221718/57383459-71a91f00-71e1-11e9-9d67-abccac00695b.png)
你那个是怎么格式化的

**Comment by Binaryify** [comment]
@HIjack2015 
![image](https://user-images.githubusercontent.com/12221718/57383498-81c0fe80-71e1-11e9-9427-8c6906252792.png)
 你那个是怎么格式化的

**Comment by Binaryify** [comment]
@HIjack2015 
你那个是怎么格式化的,我这是这样的
![image](https://user-images.githubusercontent.com/12221718/57383587-a61cdb00-71e1-11e9-88a9-eb99bb9a1ba6.png)

**Comment by HIjack2015** [comment]
@Binaryify 
![image](https://user-images.githubusercontent.com/10767193/57383679-c9478a80-71e1-11e9-96fc-3321047ae02f.png)

**Comment by Binaryify** [comment]
@HIjack2015 好

**Comment by Binaryify** [comment]
@HIjack2015 这方法太赞了

**Comment by Binaryify** [comment]
发带歌曲动态是这个
```js
// 分享歌曲到动态

module.exports = (query, request) => {
  const data = {
    type:"song",
    msg:query.msg,
    id:query.id||''
  };
  return request(
    "POST",
    `http://music.163.com/weapi/share/friends/resource`,
    data,
    { crypto: "weapi", cookie: query.cookie, proxy: query.proxy }
  );
};

```
其他类型的明天看看

**Comment by HIjack2015** [comment]
@Binaryify 
但是有些接口网页端是没有的。现在我就没找到 发动态和转发评论的 接口。
可能得逆向客户端来搞。
ps.其实我就想要个转发评论的接口

**Comment by nondanee** [comment]
@HIjack2015
你想查客户端的请求可以用我这个 [nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)

你把这行注释取消了，所有参数都看得见
https://github.com/nondanee/UnblockNeteaseMusic/blob/48d5ff115f07727347df2ae42a61fc7069d7b816/hook.js#L79

weapi，linuxforward，eapi 用的参数应该是一样的

**Comment by Binaryify** [comment]
@nondanee 
decrypt 骚操作 😂
