### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Itanq** [Binaryify/NeteaseCloudMusicApi#488]
## 环境
- 系统/平台: Window10

- nodejs 版本: V10.13.0

- API版本: V3.12.0

## 出现问题
运行node app.js后，可以成功访问 https://localhost:3000 本地服务，但调用api的时候出现 ERR_SSL_PROTOCOL_ERROR.
git clone 下来，第一次运行的时候可以成功通过登陆api进行登陆，后面再运行的时候出现如下错误：

This site can’t provide a secure connection localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

## 重现步骤
node app.js
访问任意api接口，比如 /login/cellphone?phone=xxx&password=yyy

## 期待效果
能够成功调用API，

**Comment by Binaryify** [comment]
非项目自身问题,自行谷歌/百度解决吧

**Comment by Itanq** [comment]
已解: https -> http
