### ISSUE TITLE
act/hot 接口返回失败

### ISSUE THREAD

**Issue by JakePrim** [Binaryify/NeteaseCloudMusicApi#489]
## 环境
- 系统/平台: <你的系统和平台>
mac
- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
https://music.aityp.com/act/hot?limit=30&offset=30
访问返回:Cannot GET /act/hot
## 重现步骤
<重现步骤>
https://music.aityp.com/act/hot?limit=30&offset=30
访问返回:Cannot GET /act/hot
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
那里文档有问题，应该是 /hot/topic?limit=30&offset=30

**Comment by Binaryify** [comment]
已经更新文档

**Comment by JakePrim** [comment]
好的 谢谢
