### ISSUE TITLE
用户动态接口 是没有分页嘛 

### ISSUE THREAD

**Issue by lrain-lv** [Binaryify/NeteaseCloudMusicApi#492]

**Comment by nondanee** [comment]
用返回值里的 lasttime 时戳取一下页
![image](https://user-images.githubusercontent.com/26399680/57973188-8488d400-79d7-11e9-8dbb-2f4c6015c674.png)

**Comment by lrain-lv** [comment]
你好，我就是按照/event那个接口lasttime获取下一夜 但是数据没有变化，而且指定每页数据 pagesize好像也是没用啊

**Comment by nondanee** [comment]
你好，现在的版本不支持这两个参数，你需要自己改一下代码==
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/f5823477c0fd97a2caf0469d1c05b81306357f93/module/user_event.js#L1-L12
@Binaryify 有空更新一下 user event 参数吧

**Comment by lrain-lv** [comment]
我把user_event.js 是改成这样么

// 动态 
  
 module.exports = (query, request) => { 
     const data={ 
         "pagesize": query.pagesize || 20, 
         "lasttime": query.lasttime || -1 
     } 
     return request( 
         'POST', `https://music.163.com/weapi/event/get/${query.uid}`, data, 
         {crypto: 'weapi', cookie: query.cookie, proxy: query.proxy} 
     ) 
 }

**Comment by Binaryify** [comment]
"time": query.lasttime || -1
我晚点更新

**Comment by lrain-lv** [comment]
好了 多谢各位大佬 = =

**Comment by Binaryify** [comment]
好了
