### ISSUE TITLE
云盘只能获取前十个歌曲

### ISSUE THREAD

**Issue by dayfan0810** [Binaryify/NeteaseCloudMusicApi#494]
## 环境
- 系统/平台: all
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
	v3.12.0
## 出现问题
http://musicapi.leanapp.cn里的云盘API只能获取前十个云盘歌曲

**Comment by nondanee** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知
> 本项目不提供线上 demo，请不要轻易信任使用他人提供的公开服务，以免发生安全问题,泄露自己的账号和密码

1. 这个公共服务非本 repo 作者提供，已经提醒过了
2. 别人部署的服务没更新，版本肯定不是 v3.12.0，**你应该去要求别人更新**
