### ISSUE TITLE
搜索接口返回搜索结果数量

### ISSUE THREAD

**Issue by Muzm** [Binaryify/NeteaseCloudMusicApi#497]
## 环境
- 系统/平台: win 10

- nodejs 版本: 10.13.0

- API版本: 3.13.0

## 出现问题
搜索接口请求时只要`type=1`,  不管搜索什么`keyowrd`, 返回结果中的`songCount`都是600.

## 重现步骤
/search?keywords=jesusandmarychain&type=1

## 期待效果
返回歌曲数量正常

**Comment by Binaryify** [comment]
无法重现
![image](https://user-images.githubusercontent.com/12221718/58709598-1a1b5f00-83ed-11e9-8024-feb4d0b1b6ca.png)
![image](https://user-images.githubusercontent.com/12221718/58709617-243d5d80-83ed-11e9-863a-dc5b40e5c5ca.png)

**Comment by Muzm** [comment]
我刚刚发现如果`keywords`是英文的就会返回600. 
![英文](https://user-images.githubusercontent.com/18257790/58792323-8a60f500-8626-11e9-9522-d6097ce8eac2.png)
部分中文`keyword`返回正常.
![中文海阔天空](https://user-images.githubusercontent.com/18257790/58792995-d06a8880-8627-11e9-97f2-1549bcccf70a.png)
![中文Dear Eloise](https://user-images.githubusercontent.com/18257790/58793042-e415ef00-8627-11e9-8e17-3fa5c7587d71.png)
![中文名字](https://user-images.githubusercontent.com/18257790/58793110-0ad42580-8628-11e9-9f56-d2031aa33ee3.png)

**Comment by nondanee** [comment]
600 首大概是搜索结果上限吧，有什么问题吗？

**Comment by nondanee** [comment]
> ## 期待效果
> 返回歌曲数量正常

请问数量多少是正常？

**Comment by Muzm** [comment]
搜索实际结果有时候比 600 少但是返回的 Count 还是 600. 
![image](https://user-images.githubusercontent.com/18257790/58926782-ed659f80-877e-11e9-8223-b82073c959d9.png)
我刚刚又测试了一下同样的`keyword`(亲爱的艾洛伊斯)但是今天返回 Count 是正常的.

**Comment by Muzm** [comment]
不知道什么原因

**Comment by Binaryify** [comment]
反正是网易那边的问题

**Comment by nondanee** [comment]
@Muzm 
个人感觉，搜索结果会变很正常(对比两个 comment 的截图)，因为依赖推荐算法
如 @Binaryify 所说，这个 node server 不修改数据，只是网易云 API 数据的搬运工

另外，你的截图没有说服力
你想表达搜索结果显示为 600 条但实际不满 600 条
那应该截图 `search?keywords=亲爱的艾洛伊斯&type=1&offset=599&limit=1` 的返回数据来说明第 600 条搜索结果不存在

如果要做 offset 分页，也不一定要依赖 songCount 吧？有多少显示多少啊

**Comment by Muzm** [comment]
@nondanee 多谢指点, 我有个功能是根据Count来决定是否显示加载更多按钮, 所以这个Count不对就有点难受.

**Comment by Binaryify** [comment]
你根据数组长度也一样的吧

**Comment by xjbeta** [comment]
#### 这个栗子比较明显

搜索 “周杰伦”  歌曲  每页 100 首   第一页
`http://localhost:3000/search?keywords=周杰伦&type=1&limit=100`
songCount 是1266    
// 正确结果是1266

加上 offset 也就是搜索第二页
`http://localhost:3000/search?keywords=周杰伦&type=1&limit=100&offset=100`
songCount 就只有600 了

把offset 换成 600  也就是第七页
`http://localhost:3000/search?keywords=周杰伦&type=1&limit=100&offset=600`
就拿不到数据了
