### ISSUE TITLE
验证码获取次数限制

### ISSUE THREAD

**Issue by MakcRe** [Binaryify/NeteaseCloudMusicApi#498]
## 环境
- 系统/平台: window 10

- nodejs 版本: 10.15.3

- API版本: 3.13.0

## 出现问题
验证码获取次数限制, 每个手机号一天只能发5条验证码

## 重现步骤
![image](https://user-images.githubusercontent.com/39758225/58748886-439dbe80-84b1-11e9-9a48-b23e447accbb.png)

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
官方就是这样
