### ISSUE TITLE
simi_user.js 中请求 data 定义是不是有问题

### ISSUE THREAD

**Issue by boyan01** [Binaryify/NeteaseCloudMusicApi#502]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/c25da58100da18d7cfee5a09d3a4eee0736eab00/module/simi_user.js#L5

发送请求的 key 是用的 songid.

**Comment by boyan01** [comment]
好像没问题，是根据歌曲推荐相似用户是吧。

**Comment by Binaryify** [comment]
对
