### ISSUE TITLE
获取用户粉丝列表最多只能获取到1000个

### ISSUE THREAD

**Issue by sh3rry** [Binaryify/NeteaseCloudMusicApi#504]
最多只能获取到1000个粉丝，再往后面获取不到。我记得是web版的限制，app上一直往后拉的话可以看到1000以后的

**Comment by Binaryify** [comment]
重现信息呢

**Comment by sh3rry** [comment]
## 环境
- 系统/平台: <你的系统和平台>

win7 x64

- nodejs 版本: <你的 NodeJS 版本号>

10.16.0 LTS

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

3.13.0

## 出现问题

<获取用户粉丝列表>功能最多只能获取到1001个粉丝

## 重现步骤

1.登陆，登陆成功之后返回信息里面可以看到粉丝数量是5744

![image](https://user-images.githubusercontent.com/9400373/59157537-e7552300-8ade-11e9-9140-24e9a728e346.png)

2.获取用户粉丝列表，为方便演示我将limit设为1
 /user/followeds?uid=*****?limit=1&offset=999      第1000个
![image](https://user-images.githubusercontent.com/9400373/59157681-4ddb4080-8ae1-11e9-84f1-1a6c456b9f23.png)

 /user/followeds?uid=*****?limit=1&offset=1000   第1001个
![image](https://user-images.githubusercontent.com/9400373/59157689-95fa6300-8ae1-11e9-86eb-b8b8c3bd1db6.png)

 /user/followeds?uid=*****?limit=1&offset=1001    第1002个
![image](https://user-images.githubusercontent.com/9400373/59157689-95fa6300-8ae1-11e9-86eb-b8b8c3bd1db6.png)
 /user/followeds?uid=*****?limit=1&offset=1002    第1003个
![image](https://user-images.githubusercontent.com/9400373/59157689-95fa6300-8ae1-11e9-86eb-b8b8c3bd1db6.png)

可以看到只能显示1001个，1001之后的返回都是一样的重复的。

## 客户端限制测试
web端只能显示50页，每页20人，50x20=1000
![image](https://user-images.githubusercontent.com/9400373/59157590-d48f1e00-8adf-11e9-939b-ba0cc45e1751.png)
pc客户端只能显示页，每页60个，第17页会有报错提示，60x16=960
![image](https://user-images.githubusercontent.com/9400373/59157593-e7095780-8adf-11e9-96d8-7008a67d9978.png)
ios客户端可以看到1000以后的粉丝，应该是可以看到全部的
![image](https://user-images.githubusercontent.com/9400373/59157655-cf7e9e80-8ae0-11e9-8dbf-b316fc96e550.png)
安卓没设备，不过应该是和ios客户端一样没限制的

**Comment by sh3rry** [comment]
@Binaryify 重现信息在上面，可以看到应该是官方api的限制，所以这个能否改用移动端的api呢？

**Comment by Binaryify** [comment]
确实有这个问题,我换一下

**Comment by Binaryify** [comment]
@sh3rry 已修复

**Comment by sh3rry** [comment]
@Binaryify 参数需要修改，否则还是获取不到所有粉丝

**Comment by sh3rry** [comment]
@Binaryify  取消offset参数，增加两个参数  pagesize: query.pagesize || 20       time: query.lasttime || 0     lasttime : 返回数据的 lasttime ,默认0,传入上一次返回结果的 lasttime,将会返回下一页的数据    ，还有两个参数"verifyId":1,"e_r":true 实测加不加没区别

**Comment by sh3rry** [comment]
@Binaryify 测试成功
5745 最后一个粉丝
![image](https://user-images.githubusercontent.com/9400373/59159856-1b8e0b00-8b02-11e9-86c1-c9f87b21d864.png)

5746 返回空值
![image](https://user-images.githubusercontent.com/9400373/59159864-3496bc00-8b02-11e9-977f-0b08881fbf6d.png)

**Comment by Binaryify** [comment]
e_r 是控制是否返回加密内容的,这里已经解码了,所以看上去没区别,那两个参数明天再加吧

**Comment by Binaryify** [comment]
已更新，pagezise 我这边测无效，还是用 limit 代替了，网易那边不同接口参数有点乱

**Comment by sh3rry** [comment]
@Binaryify 好的

**Comment by sh3rry** [comment]
@Binaryify 我昨天测试的时候请求太多好像账号被限制了。。。现在看所有人的个人资料都变成空白的了。。不是ip的问题，退出登录就可以看了。。。

**Comment by Binaryify** [comment]
@sh3rry 客户端看也这样吗

**Comment by sh3rry** [comment]
@Binaryify 
![image](https://user-images.githubusercontent.com/9400373/59184707-467b6c00-8ba1-11e9-9b7c-9efb7a40a37b.png)
![C14C10505C8D326342EAC28EC91956C1](https://user-images.githubusercontent.com/9400373/59184887-b0941100-8ba1-11e9-94df-cd584a7383be.png)

**Comment by sh3rry** [comment]
@Binaryify 应该是获取用户详情 /user/detail 这个使用太多导致的

**Comment by Binaryify** [comment]
估计暂时被拉进小黑屋了

**Comment by sh3rry** [comment]
@Binaryify  获取用户详情和 获取用户粉丝列表这两个接口不登陆的情况应该也是可以用的吧

**Comment by sh3rry** [comment]
@Binaryify 如果不登陆可以用的的话那就不建议登录了

**Comment by Binaryify** [comment]
@sh3rry 奇怪了，按理说我这里做了接口缓存，应该不会频繁请求网易那边的，还得再观察下

**Comment by sh3rry** [comment]
@Binaryify 嗯嗯，我这边已经恢复了，封了一天，第二天就好了。
