### ISSUE TITLE
请求搜索歌曲接口出现 -460

### ISSUE THREAD

**Issue by nicehiro** [Binaryify/NeteaseCloudMusicApi#508]
## 环境
- 系统/平台: <你的系统和平台>
Ubuntu

- nodejs 版本: <你的 NodeJS 版本号>
v9.11.2

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.14.0

## 出现问题
<出现的问题>
搜索歌曲接口 返回 -460

![image](https://user-images.githubusercontent.com/17773634/59494895-c0bd3080-8ec0-11e9-9f7a-074fec59e2a6.png)

## 重现步骤
<重现步骤>
![image](https://user-images.githubusercontent.com/17773634/59494970-e5190d00-8ec0-11e9-81ac-5b7964e7eb02.png)

## 期待效果
<现在的效果，期待的效果>  
正常返回

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
服务器是国外的还是国内的

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/400

**Comment by nicehiro** [comment]
> #400

国内阿里云 服务器

**Comment by Binaryify** [comment]
search.js
const data 前一行 query.cookie.os = 'pc' 试试

**Comment by nicehiro** [comment]
> search.js
> const data 前一行 query.cookie.os = 'pc' 试试

![image](https://user-images.githubusercontent.com/17773634/59496311-b6e8fc80-8ec3-11e9-9956-ba01c1db1ed0.png)

没有用……

**Comment by Binaryify** [comment]
服务器区域是哪里的

**Comment by nicehiro** [comment]
> 服务器区域是哪里的

华北 1

**Comment by Binaryify** [comment]
奇怪了，你再试试修改 x-real-ip

**Comment by nicehiro** [comment]
> 奇怪了，你再试试修改 x-real-ip
抱歉，之前有点事情耽误了。刚刚测试了一下，把 X-Real-IP 改成我目前网络的 IP 之后可以了。但是仍然不清楚为什么之前的 IP 不可以。总之，非常感谢帮忙了！

**Comment by chaotianjiao** [comment]
你好，我的项目部署在了阿里云上，同样是搜索接口出现-460，我把X-real-IP改成了阿里云的IP，还是出现-460,请问有什么好的解决办法吗？

**Comment by Binaryify** [comment]
@chaotianjiao 
search.js 里面加 query.cookie.os = 'pc' 看看行不行

**Comment by Binaryify** [comment]
@chaotianjiao 还有网易云的 ip 可能是有问题的，你换成百度 ip 或者你自己的 ip 看看
