### ISSUE TITLE
专辑图片过大

### ISSUE THREAD

**Issue by chanzea** [Binaryify/NeteaseCloudMusicApi#509]
## 环境
- 系统/平台: win10，react做代理请求

- nodejs 版本: v8.12.0

- API版本:3.14.0

## 出现问题
<出现的问题>
![image](https://user-images.githubusercontent.com/21176539/59584338-47b41800-9110-11e9-81a5-6f8d92f05d6a.png)

## 重现步骤
将图片嵌入浏览器请求过大，picUrl字段对应的图片

## 期待效果
可以服务器优化吗

**Comment by chanzea** [comment]
/album/newest 这个接口

**Comment by nondanee** [comment]
加上后缀 `?param=200y200` 可以自由调整大小
