### ISSUE TITLE
为什么一次请求会多次调用utils.js中的createWebAPIRequest

### ISSUE THREAD

**Issue by VanishingDante** [Binaryify/NeteaseCloudMusicApi#51]
我请求了http://localhost:3000/user/playlist?uid=68688129地址
发现一次请求会调用多次utils.js中的createWebAPIRequest，这是什么原理

请问utils.js里面的
```
    if (res.statusCode != 200) {
      createWebAPIRequest(host, path, method, data, cookie, callback)
      return
    } else {
```
以及
```
        if (music_req == '') {
          createWebAPIRequest(host, path, method, data, cookie, callback)
          return
        }
```
是干什么的

**Comment by Binaryify** [comment]
`!=200 ` 说明请求过程有问题了,200才是正常状态码,再请求一次,然后 return 不执行下面的代码
`music_req == ''` 说明返回内容为空了,再请求一次,然后 return 不执行下面的代码
如果请求正常,当然只有一次请求

**Comment by VanishingDante** [comment]
这个是网易的问题吗
多次重复的相同的请求可能前几次都不正确返回结果

**Comment by Binaryify** [comment]
@VanishingDante 
只要是请求都可能不正常,要保证程序正常运行,就得做好临界处理

**Comment by VanishingDante** [comment]
是这个道理
主要是请求的时候 一次都没有直接成功过 我以为是网易有什么奇怪的限制
谢谢

**Comment by Binaryify** [comment]
@VanishingDante 
刚看了下 log, 确实走了很多次请求为空的情况,应该是网易那边也有特殊处理
