### ISSUE TITLE
评论只能抓取最前250和最后250页内容，可能是网页端的限制，浏览器打开也是这样，只有客户端上才能获取到全部评论，请问有什么解决方法的方向吗

### ISSUE THREAD

**Issue by randerous** [Binaryify/NeteaseCloudMusicApi#513]

**Comment by potato98** [comment]
环境
系统/平台: win10

nodejs 版本: nodejs8.0

API版本:3.2

出现问题
评论只能抓取最前250和最后250页内容，可能是网页端的限制，浏览器打开也是这样，只有客户端上才能获取到全部评论，请问有什么解决方法的方向吗

重现步骤
调用api设置页偏移，正常抓取一首歌的全部评论，抓到250页之后内容为重复内容

期待效果
评论只能抓取最前250和最后250页内容，可能是网页端的限制，浏览器打开也是这样，只有客户端上才能获取到全部评论，请问有什么解决方法的方向吗

**Comment by Binaryify** [comment]
网盘抽时间改成客户端的接口吧

**Comment by Binaryify** [comment]
更新试试

**Comment by randerous** [comment]
哦哦好的，谢谢啦，前几天没上来，没想到作者回复这么快，我现在试试

**Comment by randerous** [comment]
不好意思作者大大，我之前的说法有点问题，不只是网页端，电脑的客户端也只能抓取250页的内容，也就是达到5000条数据之后就爬取不到任何数据。但是这几天我测试了，android,ios,linux,windows10,macos上的客户端，发现android端和ios端的是能查看到250页之后的内容的，请问有移动端的接口吗？
