### ISSUE TITLE
访问任意接口都返回502

### ISSUE THREAD

**Issue by a416237796** [Binaryify/NeteaseCloudMusicApi#514]
## 环境
- 系统/平台: windows10

- nodejs 版本: v10.15.3

- API版本: v3.15.0

## 出现问题
访问任意接口都返回这个
{
"code": 502,
"msg": "Error: read ECONNRESET\n at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)"
}

## 重现步骤
任意接口

## 期待效果
正常的接口返回

>先看文档有没有相关说明：无

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

git clone
然后npm i，用的全局vpn
set PORT=4000 && node app.js
然后访问http://localhost:4000/，正常，点击搜索，就出现上述错误，尝试了登录等其他接口，去全部返回这个

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by SearchForPluto** [comment]
请问这问题解决了吗？

**Comment by Hjw52** [comment]
同问这个问题如何解决

**Comment by SongJasper** [comment]
mac端刚下载4.0.8 已经是描述的问题 切换好多次端口不起作用 请问如何解决
