### ISSUE TITLE
关于在手机上部署该项目的问题

### ISSUE THREAD

**Issue by LeoFate** [Binaryify/NeteaseCloudMusicApi#516]
想咨询一下是否可以在android手机上使用该项目，就是把这个项目作为我android程序的一部分来达到在手机上无须与电脑处于同一网络才可以调用接口的目的。
作为一个初学者咨询下这个是否可以实现。

**Comment by nondanee** [comment]
有 nodejs-mobile，可以运行 node，但建议别去折腾

可以找找应该会有 java 版的 weapi 加密实现
或者你自己移植到 java，逻辑其实不是很复杂

**Comment by boyan01** [comment]
在手机上部署？这儿有个dart版本 https://github.com/ziming1/NeteaseCloudMusicApi 

手机上运行dart代码还是比较简单的 https://flutter.dev/

**Comment by LeoFate** [comment]
感谢诸位帮助
