### ISSUE TITLE
想问一下可以单独指定使用某个api么，例如只使用eapi

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#517]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>
10.15.3

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
你可以自己改自己测试

**Comment by nondanee** [comment]
为什么？

**Comment by kurodaakira-jp** [comment]
> 为什么？

我正在复刻安卓版app啊，别的api有些字段缺失

**Comment by kurodaakira-jp** [comment]
> 你可以自己改自己测试

哭了，要从零开始的nodejs了

**Comment by nondanee** [comment]
麻烦举个例子


个人感觉 4 种 API 请求的数据应该是一样的
缺字段可能是不同 endpoint 的问题

比如 v3/playlist/detail 和 v6/playlist/detail
返回的格式就不太一样

**Comment by kurodaakira-jp** [comment]
> 麻烦举个例子
> 
> 个人感觉 4 种 API 请求的数据应该是一样的
> 缺字段可能是不同 endpoint 的问题
> 
> 比如 v3/playlist/detail 和 v6/playlist/detail
> 返回的格式就不太一样

专辑的收藏量字段，和是否收藏的字段没有找到

**Comment by nondanee** [comment]
哦这个啊
那改 crypto 没有用

确实是两个不同的 endpoint
现在这个 /album 用的 api 比较古老
客户端使用的请求专辑数据 api 需要 cache id，没有就会报错，也不知道怎么得到，你可以自己抓包试试看

收藏数现在这个 /album 里应该有吧
是否收藏可以请求 /album/detail/dynamic

你参考这个吧
https://github.com/nondanee/vsc-netease-music/blob/9336b126f1e29b93094b966888c52050d32427c1/request.js#L81

**Comment by kurodaakira-jp** [comment]
> 哦这个啊
> 那改 crypto 没有用
> 
> 确实是两个不同的 endpoint
> 现在这个 /album 用的 api 比较古老
> 客户端使用的请求专辑数据 api 需要 cache id，没有就会报错，也不知道怎么得到，你可以自己抓包试试看
> 
> 收藏数现在这个 /album 里应该有吧
> 是否收藏可以请求 /album/detail/dynamic
> 
> 你参考这个吧
> https://github.com/nondanee/vsc-netease-music/blob/9336b126f1e29b93094b966888c52050d32427c1/request.js#L81

其实我请求的就是/album，然后才发现没有这两个字段，/playlist是有的，还有其他的缺字段的，之前写的时候发现的，不过现在忘了是哪个了

**Comment by nondanee** [comment]
对的
playlist 有
artist 和 album 没有/或者有但是是错误的，必须再从别处请求

这个是 endpoint 的问题，不是 crypto 的问题，换 eapi 也没有用。

**Comment by kurodaakira-jp** [comment]
> 对的
> playlist 有
> artist 和 album 没有/或者有但是是错误的，必须再从别处请求
> 
> 这个是 endpoint 的问题，不是 crypto 的问题，换 eapi 也没有用。

强迫症哭了，没法全功能复刻了

**Comment by nondanee** [comment]
数据肯定是有的
就是不能一次请求全部拿到……
不要灰心啊！

**Comment by kurodaakira-jp** [comment]
> 数据肯定是有的
> 就是不能一次请求全部拿到……
> 不要灰心啊！

只能有啥写啥了，断断续续写了也有三四个月了，丢了可惜了

**Comment by Binaryify** [comment]
@kurodaakira-jp 明天我更新下吧,其实 '/album/detail/dynamic'就能拿到,不过还没加上去

**Comment by kurodaakira-jp** [comment]
> @kurodaakira-jp 明天我更新下吧,其实 '/album/detail/dynamic'就能拿到,不过还没加上去

![スクリーンショット 2019-06-28 23 35 50](https://user-images.githubusercontent.com/38561128/60353859-8645ae80-99fd-11e9-8fc4-b1dc89704a83.png)

**Comment by Binaryify** [comment]
@kurodaakira-jp 已更新

**Comment by Cool-Sky** [comment]
> 哦这个啊
> 那改 crypto 没有用
> 
> 确实是两个不同的 endpoint
> 现在这个 /album 用的 api 比较古老
> 客户端使用的请求专辑数据 api 需要 cache id，没有就会报错，也不知道怎么得到，你可以自己抓包试试看
> 
> 收藏数现在这个 /album 里应该有吧
> 是否收藏可以请求 /album/detail/dynamic
> 
> 你参考这个吧
> https://github.com/nondanee/vsc-netease-music/blob/9336b126f1e29b93094b966888c52050d32427c1/request.js#L81

老哥, 我发现似乎 /album/detail/dynamic 这个api不可用了,请求结果为 `{"msg":"参数错误","code":400}`

**Comment by Cool-Sky** [comment]
> @kurodaakira-jp 明天我更新下吧,其实 '/album/detail/dynamic'就能拿到,不过还没加上去

似乎现在不可用了, 返回 {"msg":"参数错误","code":400}

**Comment by Binaryify** [comment]
@Cool-Sky 你id传了吗

**Comment by Cool-Sky** [comment]
> @Cool-Sky 你id传了吗

我是直接用的你的node客户端配合浏览器获取json的, 不知道为什么,但是现在似乎浏览器又能获取到了,不明白怎么回事
