### ISSUE TITLE
微信小程序使用

### ISSUE THREAD

**Issue by bitqiang** [Binaryify/NeteaseCloudMusicApi#52]
小程序本身没有Cookie机制，那么这个要登录呢

**Comment by Binaryify** [comment]
要理解 Cookie 的本质是浏览器端的 token, 只要把 Cookie 存在一个变量里,然后把读取 Cookie 的地方修改成读取这个变量就行

**Comment by bitqiang** [comment]
噢噢。谢谢了噢。现在能用了。
我在请求接口的时候，保存下返回的cook。
wx.setStorageSync('cookie',res.header['Set-Cookie'])
然后在需要的地方请求的时候设置header
header: { cookie: wx.getStorageSync('cookie')},
这样就可以请求到数据了。

**Comment by estoi** [comment]
@bitqiang 你的小程序使用什么库做的请求啊 我这边wx.request发的请求 响应里没看到set-cookie
