### ISSUE TITLE
听歌打卡接口没有生效

### ISSUE THREAD

**Issue by jsososo** [Binaryify/NeteaseCloudMusicApi#522]
## 环境
- 系统/平台: mac os10.3

- nodejs 版本: 8.10

- API版本: 3.13.0

## 出现问题
按照文档示例，调用听歌打卡接口 `/scrobble?id=482369360&sourceid=35571977` 时返回结果为 code:200，没有在网易云的最近一周听歌排行里看到数据

## 重现步骤
如上调用接口 `/scrobble?id=482369360&sourceid=35571977`

**Comment by Binaryify** [comment]
把听歌时间也带上

**Comment by jsososo** [comment]
嗯，可以了，谢谢，我一开始还以为这个时间是歌曲播放的长度时间，没想到是当前的时间戳。。

**Comment by jsososo** [comment]
不对，我刚才应该是看错了，听歌时间我试了 时间戳、秒数和毫秒数在网易云那里都没有记录

**Comment by Binaryify** [comment]
单位应该是秒,统计有延迟,大概10分钟到30分钟,我明天抽空再测试下

**Comment by jsososo** [comment]
嗯，辛苦有空看下

**Comment by Binaryify** [comment]
我重新抓包发现网易那边换接口了,得更新下

**Comment by Binaryify** [comment]
@jsososo 我发现是之前人提交的时候参数和文档不对 ...

**Comment by Binaryify** [comment]
已更新,亲测可用

**Comment by jsososo** [comment]
非常感谢，我之前都没发现这两边的参数没有对上，还以为接口变了

**Comment by Clarkkkk** [comment]
发现time必须是整数，直接传带小数的duration不会生效
