### ISSUE TITLE
探索歌下载链接回复一直是 null.

### ISSUE THREAD

**Issue by seeya** [Binaryify/NeteaseCloudMusicApi#523]
## 环境
- 系统/平台: <你的系统和平台>
osx 10.14
- nodejs 版本: <你的 NodeJS 版本号>
12.2.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.18.2

## 出现问题
全部 `/song/url?id=64634` 的 API 回复，URL 里都是 `null`.

## 重现步骤
`/song/url?id=64634`

## 期待效果
现在的效果 
```
[
  {
    id: 64634,
    url: null,
    br: 0,
    size: 0,
    md5: null,
    code: 404,
    expi: 1200,
    type: null,
    gain: 0,
    fee: 0,
    uf: null,
    payed: 0,
    flag: 4,
    canExtend: false,
    freeTrialInfo: null,
    level: null,
    encodeType: null
  }
]

```
期待的效果
```
[
  {
    id: 64634,
    url: http://downloadurl....,
    br: 0,
    size: 0,
    md5: null,
    code: 404,
    expi: 1200,
    type: null,
    gain: 0,
    fee: 0,
    uf: null,
    payed: 0,
    flag: 4,
    canExtend: false,
    freeTrialInfo: null,
    level: null,
    encodeType: null
  }
]
```

**Comment by nondanee** [comment]
人在海外吗？

**Comment by seeya** [comment]
是的，之前在海外也行。只是下载的时候需要用proxy。

**Comment by nondanee** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知
> 由于网易限制,此项目在国外服务器上使用会受到限制,如需解决 , 可使用大陆服务器或者使用代理 , 感谢 @hiyangguo提出的解决方法: 在 '/util/request.js' 的 'headers' 处增加 X-Real-IP':'211.161.244.70' // 任意国内 IP 即可解决

**Comment by seeya** [comment]
多谢，改了就行了。
