### ISSUE TITLE
全部 mv 接口 分页出错offset无效

### ISSUE THREAD

**Issue by lxhcool** [Binaryify/NeteaseCloudMusicApi#524]
全部 mv

可选参数:
limit: 取出数量,默认为 30

offset: 偏移数量,用于分页,如:(页数-1)*30, 其中 30 为 limit 的值,默认为0

接口地址:
/mv/all

问题描述：
无论offset是多少，返回的都是同样的数据！

**Comment by lxhcool** [comment]
我把接口里的offset: query.limit || 0 改成了 offset: query.offset || 0然后数据返回正常
如果是这个问题，麻烦更新一下
![image](https://user-images.githubusercontent.com/20867671/60643521-ec02c200-9e65-11e9-8dcb-718b7e69896e.png)

**Comment by Binaryify** [comment]
一会更新下

**Comment by Binaryify** [comment]
已更新

**Comment by lxhcool** [comment]
@Binaryify 好的，麻烦了
