### ISSUE TITLE
cookie为空, 返回-460

### ISSUE THREAD

**Issue by kebichishaobing** [Binaryify/NeteaseCloudMusicApi#527]
## 环境
- 系统/平台: Linux

- nodejs 版本: 10.15.0
- API版本:3.13.0

## 出现问题
没有登录, cookie为空, 但是可以正常返回数据
但是使用代理, 频率大概1次/分钟, 例如1次/30秒,1次/10秒都被封号,返回-460
是否与没有登录状态有关系?

**Comment by Binaryify** [comment]
和你的代理有关吧,国内ip应该是没问题的

**Comment by oldpotter** [comment]
这两天都有这个问题，怎么解决?
