### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by memoryskull** [Binaryify/NeteaseCloudMusicApi#528]
Hello @Binaryify 
I want to create my portfolio and, therefore, I am contributing with open source repositories.
I can present you with a logo that represents your project without any commitment.

Thanks for your time.
Cheers!

**Comment by Binaryify** [comment]
this project don't need a logo, thank for your kindness

**Comment by memoryskull** [comment]
OK thanks for your time @Binaryify
