### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by plutosherry** [Binaryify/NeteaseCloudMusicApi#529]
standard_init_linux.go:190: exec user process caused "exec format error"

## 环境
树莓派 3B+

## 出现问题
build的时候出现错误信息如下：
<出现的问题>
Step 4/6 : RUN rm -f package-lock.json     ; rm -rf .idea     ; rm -rf node_modules     ; npm config set registry "https://registry.npm.taobao.org/"     && npm install
 ---> Running in af36b7bd02d8
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c rm -f package-lock.json     ; rm -rf .idea     ; rm -rf node_modules     ; npm config set registry "https://registry.npm.taobao.org/"     && npm install' returned a non-zero code: 1

**Comment by nondanee** [comment]
基础镜像架构不对 https://github.com/fatedier/frp/issues/1308

你自己改一下 Dockerfile 吧

https://hub.docker.com/r/arm32v7/node
https://hub.docker.com/r/arm64v8/node

**Comment by plutosherry** [comment]
非常感谢你的耐心回答！
我的使用如下： 
[https://hub.docker.com/r/arm32v7/node](url)
`FROM arm32v7/node:lts-stretch`
Docker下镜像加载运行成功！
