### ISSUE TITLE
歌曲连接过期

### ISSUE THREAD

**Issue by vidondc** [Binaryify/NeteaseCloudMusicApi#530]
## 环境
- 系统/平台: Mac 

- nodejs 版本: v8.11.1

- API版本:3.18.0

## 出现问题
每次连续播放到一定时间后，之后播放的音乐url都是403

## 重现步骤
https://m10c.music.126.net/20190712161557/44ce1a1d84d089b5daece3782ac99977/ymusic/af66/4326/bf62/223a9eae58c339ff17b38ef8ac9bdfca.mp3

## 期待效果
不会出现403

**Comment by boyan01** [comment]
网易云的机制就是这样的吧，返回的都是限时的链接。

每次播放之前都请求一下歌曲url不就可以了。

**Comment by vidondc** [comment]
> 网易云的机制就是这样的吧，返回的都是限时的链接。
> 
> 每次播放之前都请求一下歌曲url不就可以了。

已解决，感谢！
