### ISSUE TITLE
歌曲会提示无版权无法播放

### ISSUE THREAD

**Issue by fjjking** [Binaryify/NeteaseCloudMusicApi#531]
有些歌曲会提示“亲爱的，暂无版权”，但在网易云的客户端上是可以播放的，下载也不需要会员

几首出现这种问题的歌曲：
I hate me - Lily.μ
運命のルーレット廻して - ZARD
DYNAMITE - 倉木麻衣
金魚涙。 - 蓮花
（我是在隔壁的[网易云网页版听歌](https://github.com/egdw/SyncMusic/issues/5)项目中遇到的这个问题发送lssues后作者表示他可能没有能力修复）
我并不知道他的nodejs版本所以无法向你汇报更详细的 抱歉

**Comment by nondanee** [comment]
最好附上歌曲 id

把 `crypto` 换成 `linuxapi` 就行了
(实质上是 `cookie.os` 的问题)

**Comment by Binaryify** [comment]
已修复~

**Comment by nondanee** [comment]
@Binaryify 
这是 feature 不是 bug，网页版有限制的 😂
还是换成 `linuxapi` 或者 `eapi` 吧，这个问题之前被封过 https://github.com/JixunMoe/netease-cloud-music-api/issues/3

**Comment by Binaryify** [comment]
@nondanee 我说网页版的怎么是灰的
