### ISSUE TITLE
注册接口返回code码250，message显示注册异常是什么原因

### ISSUE THREAD

**Issue by JLsatisfied** [Binaryify/NeteaseCloudMusicApi#532]
## 环境
- 系统/平台: win7

- nodejs 版本: 10.15.1

- API版本:3.15.0

## 出现问题
使用注册接口，返回code250，注册异常

**Comment by Binaryify** [comment]
等下修复

**Comment by Binaryify** [comment]
已更新

**Comment by JLsatisfied** [comment]
@Binaryify 试了一下，还是显示250，注册异常，额

**Comment by JLsatisfied** [comment]
![image](https://user-images.githubusercontent.com/48816703/61194998-eaec5300-a6f7-11e9-965a-51c1c796747f.png)

**Comment by Binaryify** [comment]
更新到新版本了吗

**Comment by JLsatisfied** [comment]
![image](https://user-images.githubusercontent.com/48816703/61195146-e96f5a80-a6f8-11e9-9c87-58da0ebcfd95.png)   版本号3.15.0

**Comment by JLsatisfied** [comment]
@Binaryify 这个版本还要再更新吗

**Comment by Binaryify** [comment]
3.18.6解决了，你没更新

**Comment by JLsatisfied** [comment]
OK

**Comment by Binaryify** [comment]
我新版本修复的，你不更新肯定和之前一样啊 😅

**Comment by JLsatisfied** [comment]
没注意看
