### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 10

### ISSUE THREAD

**Issue by damonsu** [Binaryify/NeteaseCloudMusicApi#534]
## 环境
- 系统/平台: Debian

- nodejs 版本: 10.15.2~dfsg-2+rpi1

- API版本: 3.18.5

- 国外IP

## 出现问题
运行 sudo ./NeteaseCloudMusic 获取到musicid之后出现错误
MusicID: 28481189,1349292048,1313118277,561307164,1346104327,464863017,1341964346,1313354324,520482501,1340543218,410801523,1331819951,439121233,448317566,36270426,515453363,552145020,461519911,554241732,1372796676
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_28481189
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_1349292048
parse error: Invalid numeric literal at line 1, column 10
Player: Player low sound quality. ID_1313118277

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/61183005-2fcba780-a66e-11e9-9a8e-c13701d652c5.png)

**Comment by JLsatisfied** [comment]
@Binaryify 注册异常的那个问题怎么解决

**Comment by damonsu** [comment]
@Binaryify 回复没贴全？只看到个图
