### ISSUE TITLE
检测音乐是否可用接口有问题

### ISSUE THREAD

**Issue by lxhcool** [Binaryify/NeteaseCloudMusicApi#536]
音乐是否可用
说明: 调用此接口,传入歌曲 id, 可获取音乐是否可用,返回 { success: true, message: 'ok' } 或者 { success: false, message: '亲爱的,暂无版权' }

必选参数 : id : 歌曲 id

可选参数 : br: 码率,默认设置了 999000 即最大码率,如果要 320k 则可设置为 320000,其他类推

接口地址 : /check/music

调用例子 : /check/music?id=1335565331

无版权的音乐有时候返回是ok，有时候返回是无版权，第一次是可以的，刷新了一下就不行了
![image](https://user-images.githubusercontent.com/20867671/61282208-83183400-a7ed-11e9-9dcd-6898b0ee72a1.png)
![image](https://user-images.githubusercontent.com/20867671/61282209-83183400-a7ed-11e9-8722-6f11e762c502.png)

**Comment by nondanee** [comment]
查了下是随机 ua 的问题
用 pc 的 ua 是没有音源的，用 mobile 的 ua 请求有 128kbps 的音源
因为 ua 是随机取得，所以有时 success 有时 failed

建议不要用这个 API，直接判 `st` 字段或者直接请求 `/song/url`

**Comment by lxhcool** [comment]
@nondanee 麻烦问一下要根据什么值判断音乐是不是vip标志，音乐是否可以播放我根据url是不是为空判断了

**Comment by nondanee** [comment]
@lxhcool 
能不能播放可以从 `st` 判断，不为 `0` 好像就没法播
VIP 应该是 `fee`, `payed` 这两个
以 `privileges` 里的值为准

**Comment by lxhcool** [comment]
@nondanee 我去试试，谢啦
