### ISSUE TITLE
网易安卓app又换了登录逻辑了，希望加个api

### ISSUE THREAD

**Issue by kurodaakira-jp** [Binaryify/NeteaseCloudMusicApi#537]
## 环境
- 系统/平台: <你的系统和平台>
Mac OS 10.13.6

- nodejs 版本: <你的 NodeJS 版本号>
v10.15.3

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
网易安卓app换了登录逻辑，多了个检测的api，研究了一下午，也没猜出什么字段，也可能我写的就是错的，望大佬加一下！
![スクリーンショット 2019-07-16 17 37 21](https://user-images.githubusercontent.com/38561128/61284083-d5a71f80-a7f0-11e9-962d-1895572615b3.png)

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
这个检测不影响原来注册流程的吧

**Comment by kurodaakira-jp** [comment]
影响的，现在是输入一个手机号，然后判断是否注册，没注册就发送验证码，注册了的话就弹出输入密码的窗口

**Comment by Binaryify** [comment]
我有空再看看吧

**Comment by nondanee** [comment]
参数都是
```
{"cellphone": "手机号"}
```

**Comment by kurodaakira-jp** [comment]
不知道是不是我js写的有问题
![スクリーンショット 2019-07-17 16 21 59](https://user-images.githubusercontent.com/38561128/61359546-1a918b80-a8af-11e9-9b10-5091ee1c2439.png)
![スクリーンショット 2019-07-17 16 22 04](https://user-images.githubusercontent.com/38561128/61359550-1b2a2200-a8af-11e9-89b1-8bab4656c5bc.png)

**Comment by nondanee** [comment]
`crypto` 改成 weapi 或者 linuxapi 
用 eapi 的话缺 path 参数

**Comment by kurodaakira-jp** [comment]
> `crypto` 改成 weapi 或者 linuxapi
> 用 eapi 的话缺 path 参数

![スクリーンショット 2019-07-18 9 54 15](https://user-images.githubusercontent.com/38561128/61423355-0f3b7000-a942-11e9-812f-3d20ebf22931.png)

**Comment by kurodaakira-jp** [comment]
又有了一个新的问题
![Screenshot_20190718-142251](https://user-images.githubusercontent.com/38561128/61436051-8128af00-a96c-11e9-9f60-a2eb4e2406ea.png)
看样子还有一个验证用户名是否可用的 API，抓包结果如下
![スクリーンショット 2019-07-18 14 59 00](https://user-images.githubusercontent.com/38561128/61436106-a3223180-a96c-11e9-8f39-79dc93b156a1.png)
猜不出来那个是了。。。

**Comment by Binaryify** [comment]
你可以用 nondanee 的这个项目看参数
https://github.com/nondanee/UnblockNeteaseMusic

去掉这行注释就可以看到参数
https://github.com/nondanee/UnblockNeteaseMusic/blob/48d5ff115f07727347df2ae42a61fc7069d7b816/hook.js#L79

**Comment by kurodaakira-jp** [comment]
找到了，不过有个checkToken不知道怎么生成的
![スクリーンショット 2019-07-19 14 52 45](https://user-images.githubusercontent.com/38561128/61515354-feb7f200-aa34-11e9-8580-650785488a41.png)

**Comment by Binaryify** [comment]
token 我这边都处理好的，你就把参数传进去就行，不要把 header 和 cookies 混进去就行

**Comment by Binaryify** [comment]
我这几天比较忙，你先弄弄吧，弄好还可以提个 PR
