### ISSUE TITLE
git clone下来 运行例子接口502

### ISSUE THREAD

**Issue by noobzzzz** [Binaryify/NeteaseCloudMusicApi#538]
## 环境
- 系统/平台: <你的系统和平台>
macos
- nodejs 版本: <你的 NodeJS 版本号>
8.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.18.6
## 出现问题
<出现的问题>
clone代码运行 请求接口502
![image](https://user-images.githubusercontent.com/29473782/61505733-627cf380-aa12-11e9-8e6f-8a3f3a7399f1.png)

## 重现步骤
<重现步骤>
clone 运行 打开3000 点击首页的例子接口 
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
公司网络有审计？证书有问题？

**Comment by noobzzzz** [comment]
有可能是公司网络限制了，晚上我回家试试
