### ISSUE TITLE
您好，请教一个问题

### ISSUE THREAD

**Issue by jlala** [Binaryify/NeteaseCloudMusicApi#54]
通过搜索api可以搜索到音乐 但是里面有不能播放的音乐链接，请问如何区分呢？
比如我通过搜索api 搜索 贝加尔湖 这个关键字，可以返回m2 的mp3url 但是里面有不能播放的曲目，这个可以剔除吗？

**Comment by Binaryify** [comment]
能否提供更详细信息

**Comment by jlala** [comment]
例如：http://localhost:3000/search?keywords=贝加尔湖
我搜索这个会得到一些曲目
"mp3Url": "http://m2.music.126.net/vXnnAZFGZ30g5eCK_ccnUA==/1207263767307060.mp3",
"mp3Url": "http://m2.music.126.net/AMnPynmu8WEHbCrDfcPo9w==/2943392628763827.mp3",
这两首链接是搜索到的
但是 第一个链接放入 audio中是不能播放的，第二个可以。
如果通过网易云音乐搜索 第一首链接生成外链播放器 会提示版权问题不能使用。
我就是想知道怎么可以 把因为版权问题的链接剔除呢？

**Comment by Binaryify** [comment]
可以根据 copyright 字段排除

**Comment by jlala** [comment]
我通过观察 返回的数据 也是看到了 copyright 这个字段，但是 它有三个值  0  1  2 这三个值，通过具体点击播放，这个字段有点不准确。不知道还有别的方法吗？

**Comment by Binaryify** [comment]
@jlala 
所有信息都在返回 json 里面了,分析里面的字段应该可以知道哪些是有版权的
