### ISSUE TITLE
请问这个服务应该搭建在本地还是服务器？

### ISSUE THREAD

**Issue by Jortana** [Binaryify/NeteaseCloudMusicApi#541]
我想用这个api搭配electron-vue做一个windows的窗口程序，这个服务应该运行在客户端本地还是运行在服务器？
如果运行在本地是和窗口程序分开还是应该在一起？
因为不是很懂其中的原理，这个问题可能听起来不是很专业，见谅

**Comment by Binaryify** [comment]
electron 的话可以客户端跑

**Comment by Binaryify** [comment]
可以参考网上例子
