### ISSUE TITLE
部署到阿里云服务器的问题

### ISSUE THREAD

**Issue by WTAufPzIv** [Binaryify/NeteaseCloudMusicApi#543]
## 环境
- 系统/平台: <你的系统和平台>
阿里云服务器CentOS 7.6 64位
- nodejs 版本: <你的 NodeJS 版本号>
v0.10.24
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.19.0
## 出现问题
<出现的问题>
在进入项目目录执行npm install时候报错
然后查看日志文件：
24778 error TypeError: Cannot read property 'latest' of undefined
24778 error     at next (/usr/local/lib/node_modules/npm/lib/cache.js:688:35)
24778 error     at /usr/local/lib/node_modules/npm/lib/cache.js:676:5
24778 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
24778 error     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
24778 error     at Object.oncomplete (fs.js:107:15)
24779 error If you need help, you may report this *entire* log,
24779 error including the npm and node versions, at:
24779 error     <http://github.com/isaacs/npm/issues>
24780 error System Linux 3.10.0-957.21.3.el7.x86_64
24781 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
24782 error cwd /usr/local/src/net
24783 error node -v v0.10.24
24784 error npm -v 1.3.21
24785 error type non_object_property_load
24786 verbose exit [ 1, true ]
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
由于安装出错所以执行node app.js时候自然就报错
exec('npm info NeteaseCloudMusicApi version', (err, stdout, stderr) => {
                                                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi#环境要求
> 需要 NodeJS 8.12+ 环境

**Comment by Coo1Star** [comment]
{
  "message": "设置密码超时，请重新尝试",
  "code": 503
}

注册接口返回这个是什么意思?
