### ISSUE TITLE
如何支持多用户登录

### ISSUE THREAD

**Issue by imjustpassby** [Binaryify/NeteaseCloudMusicApi#549]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
先后登录两个账号，因为接口做了2分钟缓存，所以第二个账号的登录信息会返回第一个账号的登录信息，如何支持多用户登录？
## 重现步骤
<重现步骤>
2分钟内分别登录两个账号
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
把 apicache 注释掉

**Comment by imjustpassby** [comment]
> 把 apicache 注释掉

好的感谢！

**Comment by imjustpassby** [comment]
> > 把 apicache 注释掉
> 
> 好的感谢！


> > 把 apicache 注释掉
> 
> 好的感谢！

不好意思又来打扰了，我AB两账号先后登录，实际上后台保存的是B账号的cookie吧，两个账号的每日推荐是B账号的推荐，B登出后A也提示未登录。有办法做成多账号登录不干扰吗（纯粹建议而已）

**Comment by nondanee** [comment]
后台不保存 cookie

同一浏览器多用户登录的话 cookie 会被覆盖（因为 key 是一样的）以最后一次 set-cookie 为准

后台这边没办法做，因为你的请求只是带了最后一个用户的 cookie

login 后你可以取 cookie 然后存下来，JS 可以直接操作（我把 httponly 去掉了）

**Comment by imjustpassby** [comment]
> 后台不保存 cookie
> 
> 同一浏览器多用户登录的话 cookie 会被覆盖（因为 key 是一样的）以最后一次 set-cookie 为准
> 
> 后台这边没办法做，因为你的请求只是带了最后一个用户的 cookie
> 
> login 后你可以取 cookie 然后存下来，JS 可以直接操作（我把 httponly 去掉了）

谢谢你
