### ISSUE TITLE
你好，获取mv评论的接口失效了

### ISSUE THREAD

**Issue by xiaozhu188** [Binaryify/NeteaseCloudMusicApi#55]

**Comment by Binaryify** [comment]
我这里是正常的
![image](https://cloud.githubusercontent.com/assets/12221718/26823217/715f1232-4adf-11e7-8987-02e66e67ae26.png)

**Comment by xiaozhu188** [comment]
没有失效，可能是我网速问题。请问接口只能在本地实现吗，我现在在本地调用接口没有问题，我现在想以这种形式访问http://bxu2348550081.my3w.com/comment/mv?id=5541567，前面我的服务器地址。我该如何配置呢。

**Comment by Binaryify** [comment]
你 listen 80端口 或者用 nginx 转发到80端口就行
