### ISSUE TITLE
klyric歌词如何解析，如何实现逐字高亮，求好心人告知。

### ISSUE THREAD

**Issue by xiaofengwaner** [Binaryify/NeteaseCloudMusicApi#550]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
[20493,6360](0,672)（(0,376)齐(0,1064)）(0,188)我(0,188)想(0,250)消(0,562)失(0,248)在(0,376)茫(0,500)茫(0,314)的(0,248)人(0,1373)海

## 重现步骤
接口地址，/lyric?id=144560

## 期待效果
括号里横纵坐标的意思。实现歌词的逐字高亮

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by pengqiangsheng** [comment]
歌词获取到了后是这样的：
[00:00:00]作曲[00:00:02]周杰伦...
类似于这样，所以第一步你要先用正则表达式去捕获时间和对应的歌词。
然后再做一些小的处理，之后得数组用于存放时间和存放歌词。
这样就算是解析好了。比如lyricArray[0]它就等于‘作曲’，lyricArray[1]等于‘周杰伦’,
然后timeArray[0]===00:00:00，timeArray[1]===00:00:02，你的目标是得到这样的东西。
然后就是播放的问题了，一个思路是通过定时器去倒计时，然后回调相应的歌词。
-----------------------------分割线-------------------------------------------
把上述的组装成一个class类，然后在前端页面中import进来，然后歌播放的同时，播放歌词，然后得到相应的歌词回调，然后去显示出来，或者高亮。
-----------------------------分割线-------------------------------------------
最后，这个歌曲解析的类已经有人写了，我用着还不错，作者是batterScroll的作者，github上搜索：lyric-parse。[传送门](https://github.com/ustbhuangyi/lyric-parser)

**Comment by xiaofengwaner** [comment]
> 歌词获取到了后是这样的：
> [00:00:00]作曲[00:00:02]周杰伦...
> 类似于这样，所以第一步你要先用正则表达式去捕获时间和对应的歌词。
> 然后再做一些小的处理，之后得数组用于存放时间和存放歌词。
> 这样就算是解析好了。比如lyricArray[0]它就等于‘作曲’，lyricArray[1]等于‘周杰伦’,
> 然后timeArray[0]===00:00:00，timeArray[1]===00:00:02，你的目标是得到这样的东西。
> 然后就是播放的问题了，一个思路是通过定时器去倒计时，然后回调相应的歌词。
> -----------------------------分割线-------------------------------------------
> 把上述的组装成一个class类，然后在前端页面中import进来，然后歌播放的同时，播放歌词，然后得到相应的歌词回调，然后去显示出来，或者高亮。
> -----------------------------分割线-------------------------------------------
> 最后，这个歌曲解析的类已经有人写了，我用着还不错，作者是batterScroll的作者，github上搜索：lyric-parse。[传送门](https://github.com/ustbhuangyi/lyric-parser)

这是lrc的解析，不是krc。
