### ISSUE TITLE
eapi的专辑详情接口的catch_key值的问题

### ISSUE THREAD

**Issue by kurodaak1ra** [Binaryify/NeteaseCloudMusicApi#552]
## 环境
- 系统/平台: <你的系统和平台>
eapi的专辑详情接口的catch_key值的问题

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
安卓的eapi的专辑详情charles抓包发现连接上带有catch_key，导致无法直接单写js文件请求，提示参数错误，直接复制抓取的catch_key，提示"key validate failed!"，想请大佬有空看下这个catch怎么生成的
![スクリーンショット 2019-08-10 0 05 26](https://user-images.githubusercontent.com/38561128/62793043-329da900-bb03-11e9-91ad-6c85fa0be08c.png)

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/517#issuecomment-506750298

专辑这个 cache key(id) 的问题我不是告诉过你了吗 =.=

复制我记得是可以的，对应指定的那个 id

**Comment by kurodaakira-jp** [comment]
> [#517 (comment)](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/517#issuecomment-506750298)
> 
> 专辑这个 cache key(id) 的问题我不是告诉过你了吗 =.=
> 
> 复制我记得是可以的，对应指定的那个 id
这个实在没看明白。。。
