### ISSUE TITLE
为什么获取到的mp3地址，都无法播放的？

### ISSUE THREAD

**Issue by yiiouo** [Binaryify/NeteaseCloudMusicApi#56]
我赋值到audio中，最后都是报500的？是不是现在网易限制了？

**Comment by Binaryify** [comment]
能提供重现吗

**Comment by yiiouo** [comment]
重现是什么意思？？

**Comment by Binaryify** [comment]
就是能让我得到一样的结果的操作

**Comment by yiiouo** [comment]
我使用`/search`这个接口，进行搜索歌曲，从中得到了mp3Url，然后赋值到audio的src，然后就无法播放了。
我是使用webpack的proxy，来代理请求你的接口。

**Comment by Binaryify** [comment]
你直接开 express 的跨域然后赋值呢

**Comment by yiiouo** [comment]
现在这样就好了。。。不过我发这个问题前，试过不行的，不知道为什么现在有可以了。。。。
谢谢。

**Comment by cainiaozone** [comment]
还是不行啊，下面是查到的 mp3路径
![image](https://user-images.githubusercontent.com/9943151/29215221-bc9f2a58-7edc-11e7-8388-7a350dbe7704.png)

在浏览器打开直接报404错误，当然了放到小程序中不能播放
![image](https://user-images.githubusercontent.com/9943151/29215272-e84f1d98-7edc-11e7-9e00-03c0a967b35e.png)
