### ISSUE TITLE
请求接口http状态码503

### ISSUE THREAD

**Issue by pass13046132** [Binaryify/NeteaseCloudMusicApi#560]
![image](https://user-images.githubusercontent.com/27669212/63067261-a47d5480-bf40-11e9-8dc3-0cecded64cb3.png)

![image](https://user-images.githubusercontent.com/27669212/63067275-b7902480-bf40-11e9-8c07-94bb2c9723b7.png)

求问大神这是什么原因

**Comment by nondanee** [comment]
#357

https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知
> 本项目不提供线上 demo，请不要轻易信任使用他人提供的公开服务，以免发生安全问题,泄露自己的账号和密码

**Comment by pass13046132** [comment]
> #357
> 
> [https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E8%B0%83%E7%94%A8%E5%89%8D%E9%A1%BB%E7%9F%A5)
> 
> > 本项目不提供线上 demo，请不要轻易信任使用他人提供的公开服务，以免发生安全问题,泄露自己的账号和密码

我好想懂了点什么，我调用的是别人的服务器是吧

**Comment by nondanee** [comment]
是
