### ISSUE TITLE
搜索接口400错误

### ISSUE THREAD

**Issue by JLsatisfied** [Binaryify/NeteaseCloudMusicApi#561]
## 环境
- 系统/平台: win7

- nodejs 版本: 10.15.2

- API版本:3.20.0

## 出现问题
**搜索接口400错误**
![image](https://user-images.githubusercontent.com/48816703/63084097-fb088400-bf7c-11e9-9a45-44696ef472c2.png)

![image](https://user-images.githubusercontent.com/48816703/63085156-710dea80-bf7f-11e9-85c6-ae330e097ad3.png)

**出错接口：http://localhost:3000/search?keywords=海阔天空**
在笔记本电脑上搜索接口报错400，在另一台电脑上搜索接口又是可以用的

@Binaryify

**Comment by Binaryify** [comment]
都是同一个网络吗

**Comment by JLsatisfied** [comment]
没事了，之前是因为调用太频繁，IP被封了

**Comment by Binaryify** [comment]
好
