### ISSUE TITLE
post

### ISSUE THREAD

**Issue by jieboom** [Binaryify/NeteaseCloudMusicApi#564]

**Comment by nondanee** [comment]
无法解析怎么体现？
报什么错？
能不能详细描述一下

**Comment by jieboom** [comment]
> 无法解析怎么体现？
> 报什么错？
> 能不能详细描述一下

没有，报错。使用post请求时，express解析req参数时，method为options，body是{}。

**Comment by nondanee** [comment]
@jieboom 
好的，我查查

**Comment by jieboom** [comment]
> @jieboom
> 好的，我查查

好 辛苦啦
