### ISSUE TITLE
相关歌单推荐似乎是热门歌单

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#565]
## 环境
- 系统/平台: 
- nodejs 版本: 
- API版本:

## 出现问题

相关歌单的实现不是调用api，是从Html里面提取的内容。我手动打开了几个歌单看，发现相关歌单其实是热门歌单，不管id是多少，都是一样的。
https://music.163.com/#/playlist?id=1
https://music.163.com/#/playlist?id=2888212971
![Snipaste_2019-08-20_12-17-29](https://user-images.githubusercontent.com/27536652/63317237-98303780-c344-11e9-920c-da566e564f9b.png)
![Snipaste_2019-08-20_12-17-32](https://user-images.githubusercontent.com/27536652/63317241-99616480-c344-11e9-96fd-5e855d548691.png)

## 期待效果
接口描述和命名修改一下或者删掉这个接口？

**Comment by wwh1004** [comment]
好吧，有些歌单的相关歌单是一样的...

**Comment by nondanee** [comment]
官方没有这个接口，但是网页版有数据，有人需要所以加了 #284 #286 
好像对官方的歌单那个区域是 "热门歌单"，用户创建的是 "相关推荐"
