### ISSUE TITLE
user_audio.js的文档缺失

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#569]
感觉文档和代码好多地方都不同步

文档好多地方漏了可选参数

然后文档漏了个api /user/cloud

**Comment by Binaryify** [comment]
缺了的有例子吗，文档确实有疏漏的地方

**Comment by wwh1004** [comment]
我也不是特别清楚这个api干嘛的。看文档写的是 用户创建的电台，试了下返回结果

> {"djRadios":[],"hasMore":false,"code":200}

 我猜应该是

用户创建的电台
说明 : 调用此接口 , 传入用户 id, 获取用户创建的电台
必选参数 : uid: 用户 id
接口地址 : /user/audio
调用例子 : /user/audio?uid=32953014

**Comment by wwh1004** [comment]
收藏取消收藏-mv

https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e6%94%b6%e8%97%8f%e5%8f%96%e6%b6%88%e6%94%b6%e8%97%8f-mv
参数不是id，参数是mvid，代码：

>    mvId: query.mvid,
>    mvIds: '["' + query.mvid + '"]'

// MV链接

https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=mv-%e5%9c%b0%e5%9d%80
参数不是url，是id

>id: query.id,
>r: query.res || 1080

**Comment by wwh1004** [comment]
weblog.js 这个也没有文档

**Comment by Binaryify** [comment]
那两个确实有问题,感谢反馈
`/user/cloud` 文档有的,云盘里面的列表
/`weblog` 基本没啥用,官方记录埋点数据的,先暂时放那了

**Comment by wwh1004** [comment]
/user/cloud那个是手残打错了，应该就是标题的/user/audio
然后发现dj_banner.js dj_hot.js dj_program_detail.js 也没文档

**Comment by Binaryify** [comment]
好,洗完澡加一下

**Comment by Binaryify** [comment]
已更新~
