### ISSUE TITLE
获取精品歌单接口

### ISSUE THREAD

**Issue by xuyangqiao** [Binaryify/NeteaseCloudMusicApi#57]
可选参数:
limit: 取出评论数量,默认为20

offset: 偏移数量,用于分页,如:(页数-1)*20, 其中 20 为 limit 的值

接口地址:
/top/playlist/highquality

调用例子:
/top/playlist/highquality?limit=30

offset没有效果，一直都是重复相同的数据？请问正确的使用法，谢谢大神！
我是下拉到最底 然后 /top/playlist/highquality?limit=30&offset=30  offset 每次加30

**Comment by Binaryify** [comment]
貌似这个接口的这个参数失效了,你用 JS 的 slice 手动抽数据吧
