### ISSUE TITLE
请问一下，是没有删除“创建的歌单”么还是我没找到。

### ISSUE THREAD

**Issue by xiaofengwaner** [Binaryify/NeteaseCloudMusicApi#570]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
没有删除“创建的歌单”的接口。

## 重现步骤
调用取消收藏歌单接口尝试删除“创建的歌单”会返回400请使用删除歌单接口。

## 期待效果
添加删除“创建的歌单”的接口

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
确实没有,我加下吧

**Comment by Binaryify** [comment]
已更新~

**Comment by xiaozhu188** [comment]
> 
> 
> 已更新~

thanks,刚刚测试了没问题~
