### ISSUE TITLE
mv_exclusive_rcmd.js代码还是文档有误

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#571]
// 网易出品

module.exports = (query, request) => {
  const data = {
    offset: query.limit || 0,
    limit: query.limit || 30
  };

这里把limit给offset用，是文档有问题还是代码写错了？

**Comment by wwh1004** [comment]
personalized.js 也是这个问题

**Comment by Binaryify** [comment]
确实有问题,已更新~
