### ISSUE TITLE
考虑把日推歌曲限制改为30？

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#575]
我试了下，日推歌曲最多30，但是recommend_songs.js里面写死了20，是改成可选参数还是改成固定30？

>   const data = {
    limit: 20,
    offset: 0,
    total: true
  }

**Comment by wwh1004** [comment]
好吧，这个参数是废的，没用...

**Comment by Binaryify** [comment]
我把源码改改吧,这个之前别人提交的,没仔细校验
