### ISSUE TITLE
搜索接口有些问题

### ISSUE THREAD

**Issue by wwh1004** [Binaryify/NeteaseCloudMusicApi#576]
比如这样
[http://localhost:3000/search?keywords=test*](http://localhost:3000/search?keywords=test*)
返回的是{"msg":"test*_WEB","code":200}，不是正常的格式。因为我的一些歌曲的作者带了*，所以搜索的时候会带上*这个字符。原来的时候带上*返回结果是正确的，但是现在返回结果是很奇怪的玩意。我开了代理，也换了weapi，普通api，还有用网易云客户端搜索，结果都是这样。是网易最近改了什么吗？

**Comment by wwh1004** [comment]
一些关键词好像还是被屏蔽了...返回结果也是这样，比如
[http://localhost:3000/search?keywords=Masked%20bitcH](http://localhost:3000/search?keywords=Masked%20bitcH)
返回
{"msg":"Masked bitcH_WEB","code":200}
项目要不要对这些返回结果特殊处理一下？

**Comment by Binaryify** [comment]
官方就这样的话就跟着官方吧
