### ISSUE TITLE
获取推荐歌单接口

### ISSUE THREAD

**Issue by LonelyLiaR** [Binaryify/NeteaseCloudMusicApi#58]
PC端网易云音乐里, 除去每日推荐歌单还有九个是推荐歌单.
但是这个获取推荐歌单的接口只获取到了六条数据.
这是bug吗 还是说需要传什么参数?
谢谢解答 困惑我好久了.

**Comment by LonelyLiaR** [comment]
是的 就是这个接口 为什么只有六条数据呢?

**Comment by ZionLife** [comment]
跟手机端返回的数据一样，都是六条，应该没毛病。
