### ISSUE TITLE
/song/url返回顺序

### ISSUE THREAD

**Issue by Origami404** [Binaryify/NeteaseCloudMusicApi#580]
## 环境
- 系统/平台: Linux 4.19.66-1-MANJARO

- nodejs 版本: v11.15.0

- API版本: 3.21.1

## 出现问题
接口`/song/url`当传入多个以逗号分隔的id时, 返回的列表没有按传入id的顺序返回

## 重现步骤
以多个id访问`/song/url?id=id1,id2,id3...`即可

## 期待效果
现在效果: 返回顺序似乎是随机的, 观察不到规律
期待效果: 按输入的顺序返回, 如同`/song/detail?ids=`一样

#109 是旧版的相同问题, 但是似乎没有解决方案, 请问这种效果是否不会被实现?

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
官方确实就是无序的

这个自己实现一下应该不难的吧 😶
用 indexOf 重新再排一下就行了，供参考

```
data = data.reduce((result, song) => {
    result[query.ids.indexOf(song.id.toString())] = song
    return result
}, [])
```

返回数据有去重的

另外，不太建议一次取很多 song/url，因为链接时限就 20 分钟
