### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by xuminxue** [Binaryify/NeteaseCloudMusicApi#583]
## 环境
- 系统/平台: <你的系统和平台> Windows10 64

- nodejs 版本: <你的 NodeJS 版本号>  v10.15.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>  3.19.0

## 出现问题
<出现的问题>
前端使用vue生命 周期函数去请求一次登录，后面查询登录状态一直未需要登录，一定要在浏览器url栏目重新请求一次账号状态才能为登录

## 重现步骤
<重现步骤>
create函数里面请求一次登录，请求确认成功并且有返回值，在页面绑定一个事件查看登录状一直显示需要登录

## 期待效果
<现在的效果，期待的效果>  

现在效果：请求登录后状态一直为未登录
期待效果：一次请求后

使用login/status查看状态使用/login/cellphone登录

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
麻烦看下文档里的调用前须知
