### ISSUE TITLE
在node v7环境下，node app.js服务启动成功，浏览器却无法显示

### ISSUE THREAD

**Issue by lly0122** [Binaryify/NeteaseCloudMusicApi#59]
在node v7环境下，node app.js服务启动成功，浏览器却无法显示，这个需要怎么解决

**Comment by Binaryify** [comment]
能提供具体信息吗

**Comment by lly0122** [comment]
node版本是v7.10,全局安装了express，本地启动服务成功 ，浏览器端打开提示Cannot GET /，npm test是正常的

**Comment by Binaryify** [comment]
默认路径是这样的，需要根据文档，输入不同接口地址才能返回对应数据

**Comment by Binaryify** [comment]
下个版本将加入提示

**Comment by lly0122** [comment]
这样啊，我以为你有设置默认路径列出所有接口情况的，嗯，加个提示比较好，谢谢
