### ISSUE TITLE
由于使用两分钟缓存机制引起的问题

### ISSUE THREAD

**Issue by xuminxue** [Binaryify/NeteaseCloudMusicApi#591]
## 环境
- 系统/平台: <你的系统和平台>win10

- nodejs 版本: <你的 NodeJS 版本号>8.10.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>3.22.1

## 出现问题
<出现的问题>
使用两分钟缓存机制过后，两个不同的url去请求相同的服务会出现跨域问题，如何判断网页地址改变是不缓存

错误如下：Access to fetch at 'http://127.0.0.1:3000/banner?type=2' from origin 'http://192.168.7.35:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://127.0.0.1:8080' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
注释掉 apicache即可
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/254426fa0cbe0ad34680a3972f4920ec478d99c4/app.js#L51

因为缓存了 `Access-Control-Allow-Origin: req.headers.origin`
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/254426fa0cbe0ad34680a3972f4920ec478d99c4/app.js#L27
两次 req.headers.origin 不一致

Access-Control-Allow-Origin 不能为 * 是 `Access-Control-Allow-Credentials: true` 的要求
https://github.com/expressjs/cors/issues/119

**Comment by xuminxue** [comment]
今天在登录状态下加了withCredentials: true  调用/simi/artist?id=接口一直提示未登录，，搜索历史issue在登录请求加上withCredentials: true 也无效

**Comment by xuminxue** [comment]
![image](https://user-images.githubusercontent.com/37056570/64904071-ccee9f00-d6f6-11e9-9b90-794477760029.png)
![image](https://user-images.githubusercontent.com/37056570/64904074-e1329c00-d6f6-11e9-9a0c-ee23aa9eed1d.png)
换一个歌手可以请求成功

**Comment by nondanee** [comment]
那你看看 request headers 里有没有 cookie 吧

![image](https://user-images.githubusercontent.com/26399680/64904108-9ebd8f00-d6f7-11e9-857d-679574cc00b6.png)

**Comment by xuminxue** [comment]
![image](https://user-images.githubusercontent.com/37056570/64904150-40dd7700-d6f8-11e9-9b47-891209004af5.png)
都没有cookie但是一个有数据返回一个301未登录

**Comment by xuminxue** [comment]
然后将192.168.0.3改为127.0.0.1后出现错误
错误如下：Access to fetch at 'http://127.0.0.1:3000/banner?type=2' from origin 'http://192.168.0.3:8080' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://127.0.0.1:8080' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
注：已取消缓存

**Comment by nondanee** [comment]
都没 cookie 的话，应该是 {withCredentials: true} 写错位置了？
不知道你用 axios 还是 fetch 还是 XMLHttpRequest，查查文档吧

已经注释缓存了那我就不知道了......

**Comment by xuminxue** [comment]
我使用的是axios请求，刚才排查发现问题是在没加withCredentials: true的时候发起的请求，然后在加了withCredentials: true以后请求和未加withCredentials: true相同的歌手都会无法成功，会报未登录和跨域问题。
withCredentials: true位置应该没问题

**Comment by nondanee** [comment]
withCredentials: true 生效的话，request headers 里会有 cookie，你自查一下 (前提是登录过了，请求 `/login/status` 可查)

跨域错误我不知道，注释了 apicache 的话 cors headers 不会错的 (server 要重启总没忘吧)

**Comment by xuminxue** [comment]
请求头虽然没有cookie 但是还是有正确数据返回，，，我猜测是不是不带withCredentials: true发送请求请求，该请求被缓存了，所以下次带withCredentials: true请求也无效。

**Comment by xuminxue** [comment]
![$F%OL%}8B20DC%PZL0{H122](https://user-images.githubusercontent.com/37056570/64907258-975fab00-d722-11e9-87d9-2f8cb16b075d.png)
如图登陆接口被我改造了直接登陆，
但是上面获取相似歌手还是未登陆，复制请求链接用Google浏览器打开显示未登录，刷新后获取数据成功。但是在项目里面某些可以获取成功某些不成功

**Comment by xuminxue** [comment]
进一步测试发现  /login/status查询登陆状态的接口也存在同样问题，，，重现步骤如下
1.调用/login/cellphone接口登陆（浏览器获得cookie）
2.用浏览器打开/login/status接口查询状态为未登录，更换窗口同样为未登录
3.在显示未登录的窗口刷新后，状态变为登陆，有数据返回。

我想我的上述所有问题都是由此原因引起，猜测是否服务端有额外的缓存机制

**Comment by nondanee** [comment]
浏览器有缓存的
disable cache 钩一下

**Comment by xuminxue** [comment]
已解决问题，由于使用了get请求当url不发生改变时会一直请求请求缓存的状态，改为post请求即可解决，谢谢大佬帮助
