### ISSUE TITLE
排行榜的idx缺少

### ISSUE THREAD

**Issue by powerdong** [Binaryify/NeteaseCloudMusicApi#592]
## 环境
- 系统/平台: <你的系统和平台>
windows
- nodejs 版本: <你的 NodeJS 版本号>
10.15.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.20.0
## 出现问题
<出现的问题>
排行榜的idx缺少

## 期待效果
<现在的效果，期待的效果>  
有好多的排行榜无法请求到详细数据，希望增加相应的idx分类信息

还有文档中的 云音乐嘻哈榜 目前官方已经转换为 云音乐说唱榜

**Comment by Binaryify** [comment]
已更新

**Comment by powerdong** [comment]
@Binaryify  请求新增的 idx 报错！400 参数错误

**Comment by Binaryify** [comment]
@powerdong 你更新了吗

**Comment by powerdong** [comment]
@Binaryify   噢噢  忘记更新了   不好意思

**Comment by Binaryify** [comment]
@powerdong 嗯嗯
