### ISSUE TITLE
document.cookie取不到cookie的值，F12里面确实发现cookie有值

### ISSUE THREAD

**Issue by xuminxue** [Binaryify/NeteaseCloudMusicApi#595]
## 环境
- 系统/平台: <你的系统和平台> win10

- nodejs 版本: <你的 NodeJS 版本号>v8.10.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>3.20.0

## 出现问题
<出现的问题>
如题，拿不到客户端cookie
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
跨域了吧？
不是一个 origin，用 document.cookie 肯定取不到的

cookie 浏览器会自动处理的，不明白你为什么要取 cookie？

**Comment by xuminxue** [comment]
因为我要做判断是否有cookie，如果有就不请求登陆，否则请求登陆（账号密码我在服务端写死了）前端页面也无登陆按钮。 也可以换一个需要登陆的接口去判断把，只是感觉不够严谨

**Comment by nondanee** [comment]
有登录状态判断的接口 /login/status

跨域没法得到 cookie 的，要走后端中转，cors expose 'set-cookie' header 是无效的
https://stackoverflow.com/questions/39503622/access-control-expose-headers-does-not-work-to-allow-js-client-side-to-read-cook/39505535#39505535

你可以改一下 response，把 cookie 放到 body 里面
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/21344327503c59f94df3d1ff910d0a172309a7af/app.js#L74

或者加个反代不要跨域

**Comment by xuminxue** [comment]
嗯嗯好的，反代比较麻烦的一点是，开发环境和生产环境切来切去不太方便
