### ISSUE TITLE
喜欢音乐列表接口数据显示太慢

### ISSUE THREAD

**Issue by JLsatisfied** [Binaryify/NeteaseCloudMusicApi#597]
添加喜欢音乐后，喜欢音乐列表接口里的数组里要过一两分钟才把刚才的音乐添加进去

网络测试过没问题，版本也没问题

**Comment by nondanee** [comment]
有 2 分钟的 cache，请求带个时戳
看 👉 https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=调用前须知

**Comment by JLsatisfied** [comment]
@nondanee 但是我其他接口没有这个问题

**Comment by JLsatisfied** [comment]
谢谢了，解决了 @nondanee

**Comment by JLsatisfied** [comment]
我还想再问下，那为什么搜索这个接口可以进行多次请求呢？搜索接口没有加时间戳

**Comment by nondanee** [comment]
@JLsatisfied 

![image](https://user-images.githubusercontent.com/26399680/65334903-f5deca80-dbf5-11e9-91f0-b330f17a4844.png)

是按 url.path 缓存的，不是 url.pathname，所以加上 querystring 才会有效果啊

搜索接口用相同的关键词也是有缓存
