### ISSUE TITLE
私信的历史纪录无法通过offset来偏移获取

### ISSUE THREAD

**Issue by Gaubee** [Binaryify/NeteaseCloudMusicApi#599]
## 环境
- 系统/平台: Win10

- nodejs 版本: v10.15.3

- API版本: 3.22.3

## 出现问题
/msg/private/history
的 offset 参数无效

## 重现步骤
1. 执行登录
1. 访问 [/msg/private/history?uid={uid}&limit=30&offset=30]
1. 访问 [/msg/private/history?uid={uid}&limit=30&offset=60]

## 期待效果

返回的消息列表应该是不同的，
现在却是相同的内容

**Comment by Binaryify** [comment]
已修复,现在得用 `before` (取返回结果的 time)分页
