### ISSUE TITLE
请求慢...

### ISSUE THREAD

**Issue by harae** [Binaryify/NeteaseCloudMusicApi#600]
/NetEaseV2/playlist/detail?id=829437784&tsp=1570525350454 1833ms
[OK] /NetEaseV2/playlist/detail?id=829437784&tsp=1570525350454
/NetEaseV2/playlist/detail?id=829437784&tsp=1570525350455 1987ms
[OK] /NetEaseV2/playlist/detail?id=829437784&tsp=1570525350455
/NetEaseV2/playlist/detail?id=829437784&tsp=1570525350454&proxy=http://114.101.22.108:15980 15789ms
[OK] /NetEaseV2/playlist/detail?id=829437784&tsp=1570525350454&proxy=http://114.101.22.108:15980
/NetEaseV2/playlist/detail?id=829437784&tsp=1570525350459&proxy=http://114.101.22.108:15980 9558ms
[OK] /NetEaseV2/playlist/detail?id=829437784&tsp=1570525350459&proxy=http://114.101.22.108:15980

使用代理访问请求和本机请求相差很大，是代理问题吗？有遇到同类情况的人吗，从9/28开始出现这样的情况....

**Comment by Binaryify** [comment]
代理问题
