### ISSUE TITLE
排行榜该更新了其中的有的榜单不能调用

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#602]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v11.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.9.0
## 出现问题
文档接口更新
KTV唛榜 对应 KTV嗨榜，
法国 NRJ Vos Hits 周榜  对应  法国 NRJ EuroHot 30周榜，
新增榜单：
云音乐ACG动画榜，
云音乐ACG游戏榜，
云音乐ACG VOCALOID榜，
云音乐国电榜
不定调用的榜单
说唱TOP榜，
云音乐电音榜，
{
msg: "参数错误",
code: 400
}
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
可以正确获取参数

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
更新到最新版本

**Comment by shangsheng** [comment]
好的，谢谢

**Comment by shangsheng** [comment]
@Binaryify 排行榜里的，
云音乐ACG动画榜，
云音乐ACG游戏榜，
云音乐ACG VOCALOID榜，这三个榜单参数idx: 对象 key，文档中没有

**Comment by Binaryify** [comment]
已更新,v2.23.0
