### ISSUE TITLE
缺少部分API

### ISSUE THREAD

**Issue by powerdong** [Binaryify/NeteaseCloudMusicApi#606]
## 环境
- 系统/平台: <你的系统和平台>
windows
- nodejs 版本: <你的 NodeJS 版本号>
6.4.2
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
2.23.0
## 出现问题
<出现的问题>
缺少一些请求数据的API
24小时节目榜
付费精品榜
有声书|广播剧榜
最热主播榜
24小时主播榜
主播新人榜
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

麻烦大佬更新

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
这些是在哪的

**Comment by powerdong** [comment]
电台页面里面

**Comment by Binaryify** [comment]
24小时节目榜
24小时主播榜
最热主播榜
主播新人榜
这几个下次更新加上

有声书|广播剧榜
付费精品榜
这几个感觉没必要,而且涉及到的接口太多了

**Comment by Binaryify** [comment]
已更新~

**Comment by powerdong** [comment]
哇 感谢 感谢
