### ISSUE TITLE
新晋电台榜/热门电台榜，不能分类调取数据

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#607]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v11.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.23.0
## 出现问题
<出现的问题>
电台 - 新晋电台榜/热门电台榜,不能分类型调取数据，调取出来的数据都是‘创作|翻唱’类型的
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
传入电台类型 , 数字,调取相应的数据

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
官方就是这样的吧
![image](https://user-images.githubusercontent.com/12221718/67179404-c398d680-f408-11e9-8003-6d6b3a23647a.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/67179429-d14e5c00-f408-11e9-9661-757bf8e30bc9.png)

**Comment by Binaryify** [comment]
我看了也有其他的
![image](https://user-images.githubusercontent.com/12221718/67179489-09ee3580-f409-11e9-8afc-0b477fb07d4b.png)

**Comment by shangsheng** [comment]
@Binaryify 那pc端，的排行榜怎么调用
![image](https://user-images.githubusercontent.com/26435134/67179760-fa232100-f409-11e9-9aa5-cdc5f235dbb0.png)

**Comment by Binaryify** [comment]
http://localhost:3000/dj/recommend/type?type=2001

**Comment by Binaryify** [comment]
这个接口文档没写好,不好意思

**Comment by shangsheng** [comment]
好的，谢谢了，大神

**Comment by shangsheng** [comment]
@Binaryify 大神，这个请求过来的不是电台排行榜的，是优秀电台的，而且只有9个数据，也没有分页

**Comment by Binaryify** [comment]
我看看

**Comment by Binaryify** [comment]
最热电台能弄到,不过那个上升最快可能弄不了,在客户端没找到对应的

**Comment by shangsheng** [comment]
没事，辛苦了，大神。

**Comment by Binaryify** [comment]
已更新

**Comment by shangsheng** [comment]
@Binaryify 大神，又有问题了，这个接口 更改 limit 参数， 返回数量一直是34个

**Comment by Binaryify** [comment]
官方的就是有问题的

**Comment by Binaryify** [comment]
1 返回 6 个,2 返回 7 个,3 返回 8 个,10 返回 14,30 返回 34

**Comment by shangsheng** [comment]
好的，这知道了，谢谢了

**Comment by Binaryify** [comment]
嗯嗯
