### ISSUE TITLE
接口获取不到电台节目的url

### ISSUE THREAD

**Issue by fanzheng** [Binaryify/NeteaseCloudMusicApi#61]
网易：http://music.163.com/#/program?id=906296076

接口：http://localhost:3000/music/url?id=906296076
返回
{"data":[{"id":906296076,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false}],"code":200}

或者登录后访问 http://localhost:3000/dj/program?rid=336355127
其中的mp3Url也是null

**Comment by Binaryify** [comment]
确实,但是有个曲线救国的方法,使用 /music/url 接口能获取音频,比如 /music/url?id=478446370
等会更新文档

**Comment by fanzheng** [comment]
这个id可以获取到音频，但是其他的我试了几个都不行，例如906296076

**Comment by Binaryify** [comment]
906296076 这个 id 是怎么拿到的

**Comment by fanzheng** [comment]
明白了，我是取的URL上面的ID，要从json中取ID，谢谢。

**Comment by Binaryify** [comment]
对
