### ISSUE TITLE
搭建时显示权限被拒绝

### ISSUE THREAD

**Issue by NiuXiaoGuang** [Binaryify/NeteaseCloudMusicApi#610]
## 环境
- 系统/平台: <win7>

- nodejs 版本: <v12.13.0>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
![image](https://user-images.githubusercontent.com/30843465/67224400-aba27080-f463-11e9-9b84-d99a25d80114.png)

## 重现步骤
![image](https://user-images.githubusercontent.com/30843465/67224581-1bb0f680-f464-11e9-8204-44150b986bc1.png)

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
clone 用 https 地址
```
git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
```
不要用 ssh 地址
```
git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
```

**Comment by NiuXiaoGuang** [comment]
> clone用https地址
> 
> ```
> git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
> ```
> 
> 不要用ssh地址
> 
> ```
> git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
> ```

我搭建时遇到了问题，能qq指导下么，qq980334344

**Comment by Binaryify** [comment]
自行解决
