### ISSUE TITLE
ios 谷歌浏览器拿不到cookie 

### ISSUE THREAD

**Issue by xuminxue** [Binaryify/NeteaseCloudMusicApi#612]
## 环境
- 系统/平台: <你的系统和平台> linux 

- nodejs 版本: <你的 NodeJS 版本号>  v10.13.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version> "version": "3.22.0",

## 出现问题
<出现的问题>
ios12.0.1 iphone7 浏览器谷歌无法写入cookie到浏览器  导致一直提示未登录，PC端谷歌浏览器OK

## 重现步骤
<重现步骤>
如问题所示，请求登录接口后，浏览器查看不到cookie。比较好奇query.cookie.os = 'pc'这行代码标识仅仅适配PC端吗？

## 期待效果
<现在的效果，期待的效果>  
浏览器能有效果

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
1. 装个 vconsole 看下控制台
2. query.cookie.os = 'pc' 只是获取网易云音乐 PC 端的接口的返回的内容,跟适配无关
