### ISSUE TITLE
更新后获取歌单有缺少

### ISSUE THREAD

**Issue by zhouxiaofu** [Binaryify/NeteaseCloudMusicApi#614]
2019.10.25上午更新的

上个版本获取歌单有75个（正常），本次版本获取歌单只有31个（bug）

由于回滚到了上个版本，所以不知道package.json中的version是这个版本的还是上个版本的值。

**Comment by zhouxiaofu** [comment]
网易云的 uid=105821331，测试的时候可以看看，如果是70多个则是正常的

**Comment by zhouxiaofu** [comment]
有点时候获取所有的歌单正常，有的时候有缺少

**Comment by Binaryify** [comment]
网易云自身问题

**Comment by zhouxiaofu** [comment]
> 网易云自身问题

看了两个不同的返回json，然后发现，只要在参数设置more=false就行了，但是这个在文档中并没有写。
如：http://localhost:3000/user/playlist?uid=123456789&more=false

**Comment by Binaryify** [comment]
应该不是这个问题,那个 more 参数我也没接收
