### ISSUE TITLE
拿不到cookie

### ISSUE THREAD

**Issue by zpfnb** [Binaryify/NeteaseCloudMusicApi#616]
## 环境
- 系统/平台: <linux>

- nodejs 版本: <8.11.4>

- API版本:<3.22.4>

## 出现问题
<登陆了，却报301的错
响应里面有cookie，控制台没有cookie
![image](https://user-images.githubusercontent.com/41041503/67549974-0b389e80-f738-11e9-96ad-91f7316a09c1.png)
>
![image](https://user-images.githubusercontent.com/41041503/67550231-87cb7d00-f738-11e9-9d00-92487d02b719.png)

## 重现步骤
<登陆后新建歌单报错301>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
看文档

**Comment by zpfnb** [comment]
没有跨域，也试过重启了

**Comment by Binaryify** [comment]
public/test.html 跑下看看

**Comment by iamsongqian** [comment]
> public/test.html 跑下看看

![image](https://user-images.githubusercontent.com/26384811/68293206-75eac200-00c8-11ea-9954-98f226e4ddd6.png)

环境：chrome
test.html 运行如图  已登录成功却仍报301

**Comment by zsxSgithub** [comment]
127.0.0.0能拿到cookie，在linux服务器运行，用浏览器打开就拿不到cookie了

**Comment by zsxSgithub** [comment]
解决了
