### ISSUE TITLE
在阿里云起node服务，怎么在外面访问不了，是需要什么配置吗？

### ISSUE THREAD

**Issue by caim18340** [Binaryify/NeteaseCloudMusicApi#617]
## 环境
- 系统/平台: <阿里云windows服务器>

- nodejs 版本: <13.0.1>

- API版本:<3.24.0>

## 出现问题
在服务器上就需要node app运行不是吗？然后再外面就访问了

## 重现步骤
<重现步骤>

## 期待效果
在外部不能访问，怎么才能把这个放在服务器上，在外部调接口

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
更新到 3.24.1

**Comment by Binaryify** [comment]
或者  HOST=127.0.0.1 node app.js
