### ISSUE TITLE
获取到的视频播放地址打开为403

### ISSUE THREAD

**Issue by powerdong** [Binaryify/NeteaseCloudMusicApi#618]
## 环境
- 系统/平台: <你的系统和平台>
Windows
- nodejs 版本: <你的 NodeJS 版本号>
10.15.X
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.23.0
## 出现问题
<出现的问题>

403
Forbidden
出错时间: Sat, 26 Oct 2019 02:20:44 GMT
用户IP: 223.104.57.26节点信息：PSsxxyyd4vv38:2
URL: http://vodkgeyttp9c.vod.126.net/vodkgeyttp8/YB5wqHL5_2729776801_uhd.mp4?ts=1572056441&rid=47115DC667964F5C42BDE925D7219E80&rl=3&rs=CtdOQiQREmJzINCYteMhGjDiRbjdVjpb&sign=702171bf9a7cb133b584190132eed1c2&ext=NnR5gMvHcZNcbCz592mDGUGuDOFN18isir07K1EOfL3rlw3MPd25DgB/QuRZJMi75W34Yd7wp/BMIrIttTgWpS+qDgQvGCUd6IXxF2f7PJvXK//miLGn10UK9kPGHn81x2/L6bHsegklhyLsH7M1G2eRxMeTZ0vPQn12WeOS+MGLVlMP9mA4a2ABhlTESPfqNMgjxsNGMiVoigq8MC7Jxci9WuEjxChOFE6miMXc4WXZQszSGK91GfFLfvJbq9dq
查看报错详情: 详细信息

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
提供下重现

**Comment by HehongGit** [comment]
我也遇到了这个问题，只有很少的视频能够播放，大部分是403,视频地址直接在浏览器打开是能够播放的，但是使用在video标签里面就会报错 403

**Comment by nondanee** [comment]
head 里加上这个试试
```html
<meta name="referrer" content="never">
<meta name="referrer" content="no-referrer">
```

**Comment by HehongGit** [comment]
> head里加上这个试试
> 
> ```
> < meta  name = “ referrer ”  content = “从不” >
> < meta  name = “ Referrer ”  content = “ no-referrer ” >
> ```

这样解决了我的问题，its work
