### ISSUE TITLE
缺少获取排行榜评论API

### ISSUE THREAD

**Issue by powerdong** [Binaryify/NeteaseCloudMusicApi#619]
## 环境
- 系统/平台: <你的系统和平台>
Windows
- nodejs 版本: <你的 NodeJS 版本号>
10.15.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.23.0
## 出现问题
<出现的问题>
缺少获取排行榜评论API
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
增加API

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
排行榜就是歌曲，取歌单评论就行了

**Comment by powerdong** [comment]
好的  谢谢

**Comment by powerdong** [comment]
@nondanee 获取评论的id是排行榜的idx吗？

**Comment by Binaryify** [comment]
@powerdong 对应源码里的 id,比如:3779629 对应云音乐新歌榜

**Comment by powerdong** [comment]
好的 谢谢
