### ISSUE TITLE
更新到最新版本后局域网内手机无法访问windows的ipv4:3000,回退到22号的才能正常使用？

### ISSUE THREAD

**Issue by dayfan0810** [Binaryify/NeteaseCloudMusicApi#620]
## 环境
- 系统/平台: <你的系统和平台> win10

- nodejs 版本: <你的 NodeJS 版本号>v10.16.3

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>3.24.1

## 出现问题
<出现的问题>更新到最新版本后局域网内无法访问windows的192.168.199.130:3000,回退到22号的才能正常使用.

还发现一个现象，3.24.0版本服务起来后cmd是打印的“server running @ http://localhost:3000”，但是3.24.1打印的是“server running @ http://127.0.0.1:3000”.

看了最近的几个issue，发现是和某个提交customizable有关，请大神告知更新最新版本后如何解决访问不了的问题吧

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  现在PC段可以访问，局域网内手机浏览器无法访问，期待能访问

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
更新到3.24.1就行了

**Comment by Binaryify** [comment]
看错版本了，明天排查下，你可以运行的时候指定host为你的ip地址

**Comment by dayfan0810** [comment]
> 看错版本了，明天排查下，你可以运行的时候指定host为你的ip地址

”指定host为你的ip地址“这个命令是啥啊，我是搞用来搞Android客户端的，之前都是访问我电脑的IP后面加3000。

**Comment by dayfan0810** [comment]
> 看错版本了，明天排查下，你可以运行的时候指定host为你的ip地址

嗯，我在app.js中指定了“const host = process.env.HOST || '192.168.199.180'”后，局域网内手机浏览器就可以正常访问了，看来和这个localhost或者127.0.0.1有关系

**Comment by IAmWilling** [comment]
我刚刚还在想为什么 是不是我哪里出错了倒是网络无法访问 原来这里有解决方法

**Comment by ZengR** [comment]
遇到同样的问题

**Comment by Binaryify** [comment]
@dayfan0810 @IAmWilling @ZengR v3.24.2,已经修复

**Comment by zhouxiaofu** [comment]
我的也是

**Comment by zhouxiaofu** [comment]
我把app.js中的127.0.0.1替换为本机ip就行了

**Comment by Binaryify** [comment]
@zhouxiaofu 更新到 3.24.2看看

**Comment by dayfan0810** [comment]
> @dayfan0810 @IAmWilling @ZengR v3.24.2,已经修复

3.24.2已经修复OK。👍👍👍👍
