### ISSUE TITLE
请教一个问题，我把项目部署到腾讯云之后，一段时间就会断开连接，无法访问，终端没有错误提示，这可能是腾讯云服务器的问题还是项目的问题呢

### ISSUE THREAD

**Issue by powerzd** [Binaryify/NeteaseCloudMusicApi#622]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
你是怎么部署的

**Comment by SSSSSFFFFF** [comment]
node需要守护进程

**Comment by PeppaPig2000** [comment]
node进程不会在后台运行，需要手动设置
1、安装 forever
npm install forever -g
2、启动服务
service forever start
3、使用 forever 启动 js 文件
forever start app.js

**Comment by userNamexiong** [comment]
我把项目部署到阿里云服务器访问不了，请问你是怎么部署？用不用改项目代码？

**Comment by zoustin** [comment]
你好，可以部署到华为云，我按文档去做，无法实现，很尴尬，只能腾讯云吗？

**Comment by Binaryify** [comment]
@userNamexiong @zoustin 
端口开了吗

**Comment by zion223** [comment]
我的就是腾讯云部署的 直接npm start 在后台运行就行

**Comment by chr1995** [comment]
同问，怎么将api与ng-wyy项目一同部署到阿里云服务器上，求指导  搞了好久  也试了tomcat跟nginx，都没有成功
