### ISSUE TITLE
缺少pc端‘歌手’页面对应的API

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#624]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v11.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.24.0
## 出现问题
<出现的问题>
缺少pc端‘歌手’页面对应的API，
没有‘入驻歌手’、‘华语’、‘日韩’、‘欧美’、‘其他’，对应的API
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
类似与‘排行榜’的API，一样

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=歌手分类列表 这个不行吗？

**Comment by shangsheng** [comment]
可以，没有找到

**Comment by shangsheng** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=歌手分类列表,这个api没有‘其他的数据’，
![image](https://user-images.githubusercontent.com/26435134/67923675-80e5b400-fbe9-11e9-8735-408013e769bb.png)

**Comment by nondanee** [comment]
这个是 web 端不是 pc 端啊 (pc 端没有入驻歌手)

不是有吗？
```
其他男歌手 4001

其他女歌手 4002

其他组合/乐队 4003
```

**Comment by shangsheng** [comment]
我说的是选中的‘其他’，就是字母后面的那个‘其他’选项，
![image](https://user-images.githubusercontent.com/26435134/67930601-1178c000-fbfb-11e9-99b5-380bfd32c277.png)

**Comment by nondanee** [comment]
哦哦

看了下其实是 `initial=-1`
那 initial 的实现要改
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/1818a4ceb96ac91f6592c5d78bf3d96a667f8877/module/artist_list.js#L28

这样应该就行了
```js
initial: isNaN(query.initial) ? (query.initial || '').toUpperCase().charCodeAt() || undefined : query.initial
```

**Comment by Binaryify** [comment]
@nondanee 我抽空改下

**Comment by shangsheng** [comment]
好的,辛苦了，谢谢大神

**Comment by Binaryify** [comment]
已更新~
