### ISSUE TITLE
有没有办法改造成用token或者使用session的？

### ISSUE THREAD

**Issue by gjfei** [Binaryify/NeteaseCloudMusicApi#625]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
request.js 里面把 answer.cookie 放进 body 发送出来就行

**Comment by Binaryify** [comment]
或者登录的时候把 cookies 取出来存到本地

**Comment by gjfei** [comment]
> 或者登录的时候把cookie取出来存到本地
我是打算用uniapp写一个，如果取出来的话然后设置header会报错，那就只能放到body里面发送出来，发送出来的话请求别的接口也是要放到请求头里面再去请求，同样会报错。有没有解决方法

**Comment by nondanee** [comment]
改这里

https://github.com/Binaryify/NeteaseCloudMusicApi/blob/efa2d416b384b23f2fd295e85fa7ce627bac1807/app.js#L68-L82

两个地方，3 行

**Line 69**
```diff
- let query = Object.assign({}, req.query, req.body, {cookie: req.cookies})
+ let query = Object.assign({}, {cookie: req.cookies}, req.query, req.body)
```
改了以后支持从 querystring 和 body 里读取 cookie

**Line 74/Line 80**
~~之前写的冗余挺多==~~

```diff
- res.status(answer.status).send(answer.body)
+ res.status(answer.status).send(answer)
```

改了以后返回结构是
``` json
{
    "status": 200,
    "body": {},
    "cookie": []
}
```

**Comment by laurashen23** [comment]
> > 或者登录的时候把cookie取出来存到本地
> > 我是打算用uniapp写一个，如果取出来的话然后设置header会报错，那就只能放到body里面发送出来，发送出来的话请求别的接口也是要放到请求头里面再去请求，同样会报错。有没有解决方法

我也遇到了无法保存登录状态的问题，请问最后是怎么解决的？

**Comment by Binaryify** [comment]
下个版本我支持下吧

**Comment by Binaryify** [comment]
新版本登录接口返回内容增加cookie字段,支持手动传入cookie了
