### ISSUE TITLE
最新版本分别在win和Ubuntu下的控制台的打印不一样.Ubuntu无法设置端口?

### ISSUE THREAD

**Issue by dayfan0810** [Binaryify/NeteaseCloudMusicApi#628]
## 环境
- 系统/平台: <你的系统和平台>
win10
ubuntu: ubuntu18/04(阿里云)
- nodejs 版本: <你的 NodeJS 版本号>
win :v10.16.3
ubuntu: v9.10.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>3.24.2

## 出现问题
<出现的问题>
win10下:
输入命令:set PORT=80 && node app.js
cmd打印:server running @ http://localhost:80"

Ubuntu下打印:
server running @ http://localhost:3000

## 期待效果
<现在的效果，期待的效果>  
Ubuntu下打印:
server running @ http://localhost:80

**Comment by Binaryify** [comment]
好好看文档吧
