### ISSUE TITLE
静态资源HTTPS

### ISSUE THREAD

**Issue by huntdream** [Binaryify/NeteaseCloudMusicApi#629]
接口返回的数据中静态资源url都是http的
![image](https://user-images.githubusercontent.com/7903755/68013332-903b2f00-fcc7-11e9-9d10-c420ad73d1c0.png)
网易那边是支持https的，是否考虑在服务端将http替换为https？

**Comment by Binaryify** [comment]
客户端转吧,我这边只负责把原接口返回的内容转发出来,具体返回结果内容是什么并不关心的

**Comment by huntdream** [comment]
> 客户端转吧,我这边只负责把原接口返回的内容转发出来,具体返回结果内容是什么并不关心的

OK, 已经fork 了一份自己转了

**Comment by Binaryify** [comment]
嗯,注意字段名变更的临界情况就行,网易那边返回的字段是可能变化的
