### ISSUE TITLE
除了搜索结果以外的资源返回404

### ISSUE THREAD

**Issue by 17665347409** [Binaryify/NeteaseCloudMusicApi#631]
## 环境
- 系统/平台: CentOS7

- nodejs 版本: Node.js v12.10.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
请求/song/url?id=1378491298
{"data":[{"id":1378491298,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0,"fee":0,"uf":null,"payed":0,"flag":1092,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null}],"code":200}

**Comment by nondanee** [comment]
https://music.163.com/#/song?id=1378491298 

1. 没有登录请先登录
2. 没有开通会员请先开通会员
