### ISSUE TITLE
获取url的接口 谜之出现url为null的情况

### ISSUE THREAD

**Issue by Cloud370** [Binaryify/NeteaseCloudMusicApi#632]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>
v12.13.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
v3.24.2
## 出现问题
<出现的问题>
获取url的接口 谜之出现url为null的情况还是规律的
## 重现步骤
<重现步骤>
在服务器(HK的服务器)搭建好环境之后，直接浏览器访问测试过都没有问题，然后我自己用py写脚本调用接口的时候，发现一个很迷的现象，就是除非浏览器先访问过一次同样的timestamp参数的url
再用python来get接口，**只要是我用脚本get一次同样的timestamp参数**，然后浏览器访问就会出现虽然code是200但是数据 url等都是null的情况。换IP，同一局域网访问都是这样。
【请求接口】为：/song/url?id=

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明
看了 然后带了不同的timestamp参数来访问 但是浏览器怎么访问都OK，用py来调用的话，获取url的接口就会有问题，其他接口都能正常调用。
>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
cookies 没带上吧

**Comment by Cloud370** [comment]
> cookies 没带上吧

带了cookies也一样。。还有话说不是API自带cookies的吗，我获取VIP的url是可以的 但是null就很迷

**Comment by Binaryify** [comment]
浏览器没问题那肯定就是你的代码调用的问题了,大概率是 cookies 没带上的原因,或者是你的 ip 的问题了,你得把登录接口返回的 cookies 存起来

**Comment by SayaSS** [comment]
![image](https://user-images.githubusercontent.com/45657386/68476443-a74cc480-0265-11ea-9f54-e6eebe8b8d83.png)请求的时候带上cookies试试
