### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by chenxi24** [Binaryify/NeteaseCloudMusicApi#633]
登录时输入错误的邮箱。
报红502 (Bad Gateway)。
期待返回帐号/密码错误

**Comment by Binaryify** [comment]
那个就是网易那边返回的,你客户端判断下 code 吧

**Comment by chenxi24** [comment]
默认就返回这个嘛？
![image](https://user-images.githubusercontent.com/40349890/68291583-20f97c80-00c5-11ea-813b-a50d57cbaa6f.png)

**Comment by Binaryify** [comment]
哈哈，是的，原汁原味，我明天看看要不要给它改改吧

**Comment by Binaryify** [comment]
这块改了,你更新看看

**Comment by chenxi24** [comment]
收到，符合预期。谢谢。

**Comment by chenxi24** [comment]
登录后返回的数据是Cookies吗？
还是，是数据的某个字段。
另外文档登录返回数据的图挂了。

**Comment by Binaryify** [comment]
Cookies, 图片是 github 上的图片 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/static/%E7%99%BB%E5%BD%95.png

**Comment by chenxi24** [comment]
![image](https://user-images.githubusercontent.com/40349890/68374866-abeb7d00-0180-11ea-8fc0-f2072bab2775.png)
看不见

**Comment by Binaryify** [comment]
翻墙或者 download 下来

**Comment by Binaryify** [comment]
或者
https://cdn.statically.io/img/raw.githubusercontent.com/Binaryify/NeteaseCloudMusicApi/master/static/%E7%99%BB%E5%BD%95.png

**Comment by lingjianli** [comment]
最新登录返回的数据好像和文档返回的图不太一样了，好像存的是token？
