### ISSUE TITLE
拿不到cookie

### ISSUE THREAD

**Issue by iamsongqian** [Binaryify/NeteaseCloudMusicApi#634]
![image](https://user-images.githubusercontent.com/26384811/68367921-c8cc8400-0171-11ea-89e1-4d50202ab0f6.png)
test.html运行结果如图  登陆成功 但仍报301 拿不到cookie

**Comment by Binaryify** [comment]
你的过程怎样的

**Comment by iamsongqian** [comment]
修改监听端口为 8080  npm start跑起来项目 打开public/test.html 注释掉ajax请求只用axios  然后运行 控制台打印结果如图

**Comment by Binaryify** [comment]
是访问的 http://localhost:8080/test.html 还是什么

**Comment by iamsongqian** [comment]
刚才又登陆几次发现有cookie了  不好意思打扰了

**Comment by Hurricane233** [comment]
我也是这样的，但怎么登录都还是没有cookie
