### ISSUE TITLE
版本更新

### ISSUE THREAD

**Issue by xianyu21** [Binaryify/NeteaseCloudMusicApi#635]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>
10.16.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.23.0
## 出现问题
昨天更新从3.23.0-3.25.2
本地和服务器都有这个错误
![XEOLSH@)VCA91S}RDVQ$2$H](https://user-images.githubusercontent.com/35288214/68444822-ffa6a680-0212-11ea-9b86-28d5b0935956.png)

**Comment by Binaryify** [comment]
修复了

**Comment by xianyu21** [comment]
刚把依赖解决了
更新会不会影响呢

**Comment by Binaryify** [comment]
应该不会,引起问题的依赖是多余的,没用到
