### ISSUE TITLE
欢迎各位大佬访问高仿网易云音乐项目

### ISSUE THREAD

**Issue by powerdong** [Binaryify/NeteaseCloudMusicApi#636]
- 项目通过 Vue 编写实现，全面借用网易云音乐移动端的 UI 设计、功能实现，全面实现移动端网易云音乐的功能
- 目前大部分基本功能已经实现
- 访问地址 [https://github.com/powerdong/Music-player](https://github.com/powerdong/Music-player)

**Comment by xlwt123** [comment]
发现一点小瑕疵
![image](https://user-images.githubusercontent.com/43342829/68655111-60631580-056a-11ea-83d3-29d07070d477.png)
折行有点漏出来了，应该是padding造成的
首页swiper一拖就跳转新页面
登录页点不了返回

**Comment by kurodaakira-jp** [comment]
借楼挂一个我写了大半年的极致复刻版，准备年底左右开源
https://cloudmusic.xyz
