### ISSUE TITLE
[login] 这里为什么需要返回一个 Promise 呢？

### ISSUE THREAD

**Issue by JuoCode** [Binaryify/NeteaseCloudMusicApi#637]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/06e522b684b70eadc4cc22e0b8cc0e17e137339b/module/login.js#L17-L26

**Comment by Binaryify** [comment]
写习惯了，没留意就顺手写上去了，那里不需要写 Promise，下次更新去掉

**Comment by Binaryify** [comment]
去掉了~
