### ISSUE TITLE
登录状态问题

### ISSUE THREAD

**Issue by dream-saddle** [Binaryify/NeteaseCloudMusicApi#638]
## 环境
- 系统/平台: <你的系统和平台>
Linux  开发使用 Flutter  Android上
- nodejs 版本: <你的 NodeJS 版本号>
v12.13.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.24.2
## 出现问题
<出现的问题>
api 项目在我服务器上跑起的, 我在 app 中调用登录接口可以成功，但是获取日推这些需要登录的接口就不行了，提示需要登录。但是通过浏览器登录后，再到APP中访问可以访问，隔一定时间之后又不能访问了，又需要到浏览器重新登录，想问问有什么解决办法吗？
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by dream-saddle** [comment]
问题我已解决，打扰了！

**Comment by laurashen23** [comment]
你好，请问这个问题是怎么解决的？我现在在android app里用这个api，获取需要登录的接口都提示未登录，应该怎么保存token信息？

**Comment by DreamSaddle** [comment]
> 你好，请问这个问题是怎么解决的？我现在在android app里用这个api，获取需要登录的接口都提示未登录，应该怎么保存token信息？

没有token，只有cookie，之后的请求带上cookie就行了
