### ISSUE TITLE
按类别分页搜索歌手时最多只能搜索到的歌手数量为90

### ISSUE THREAD

**Issue by shieldFor** [Binaryify/NeteaseCloudMusicApi#640]
## 环境
- 系统/平台: <你的系统和平台>
  mac os 10.15.1

- nodejs 版本: <你的 NodeJS 版本号>
  10.15.2
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
  3.25.3
## 出现问题
<出现的问题>
  分页搜索歌手时，调用接口“/artist/list”，传入offset、limit参数，不管怎么调整offset与limit，最多都只能搜索到90位歌手
## 重现步骤
<重现步骤>
  分页搜索歌手时，调用接口“/artist/list”，传入offset、limit参数，设置limit=30，offset分别为0、30、60、90，当offset为90时，接口返回的artists字段为空数组
## 期待效果
<现在的效果，期待的效果>  
 与客户端相同，可以根据歌手实际数量，返回正确的分页结果

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
估计是接口限制吧，我看了下网易云网页版最多就是 100 条
`limit: 30 offset: 70` 可用，`limit: 100` 可用 (要求 limit + offset <= 100)

看了下现在客户端用 v1 版的接口，这边用的不是这个，可能返回数据字段不太一样 

/api/v1/artist/list 

```
{
  area: '7',
  type: '1',
  initial: '-1',
  offset: '0',
  total: 'false',
  limit: '30'
}
```

**Comment by DJAlejandro** [comment]
遇到相同情况，limit:100返回结果成功，limit:101时就报400错误。团队成员回复下，谢谢！

**Comment by Binaryify** [comment]
确实存在问题,已更新
