### ISSUE TITLE
获取音乐URL返回的数据顺序和传入的id顺序不一致

### ISSUE THREAD

**Issue by 364** [Binaryify/NeteaseCloudMusicApi#641]
## 环境
- 系统/平台: <你的系统和平台>
win10
- nodejs 版本: <你的 NodeJS 版本号>
v10.15.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3
## 出现问题
<出现的问题>
获取音乐URL返回的数据顺序和传入的id顺序不一致

## 重现步骤
<重现步骤>
根据歌单的 `trackIds` 同时调用 `/song/detail` 和 `/song/url` 接口

![MJETRs.png](https://s2.ax1x.com/2019/11/13/MJETRs.png)
![MJkpRI.png](https://s2.ax1x.com/2019/11/13/MJkpRI.png)

两个接口返回的数据长度是一致的
`/song/detail` 返回的数据顺序和传入的id顺序一致
`/song/url` 返回的数据顺序和传入的id顺序不一致

## 期待效果
<现在的效果，期待的效果>  
期待 `/song/url`  返回的数据顺序和传入的id顺序一致

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
duplicate #580 #109
