### ISSUE TITLE
登录API：接口未加密，不允许访问

### ISSUE THREAD

**Issue by sonichy** [Binaryify/NeteaseCloudMusicApi#642]
首先，文档 https://binaryify.github.io/NeteaseCloudMusicApi/ 做得非常好。
但是API用的相对路径，没有写域名：http://music.163.com/api
我的Qt版项目：https://github.com/sonichy/NeteaseMusic
看了你的文档，我想增加一些功能。
登录API：
http://music.163.com/api/login?email=xxx@163.com&password=xxx
http://music.163.com/api/login/cellphone?phone=xxx&password=yyy
返回：接口未加密，不允许访问。
文档并未说明如何加密。

**Comment by nondanee** [comment]
此项目是第三方项目，与官方无关，也没有线上 demo 服务，因此不存在域名一说，如有需要自行部署
文档只针对此 api server，请求 path 不能保证和官方一致
云音乐官方从未公开 api，使用请自律
