### ISSUE TITLE
登录失效

### ISSUE THREAD

**Issue by thinkerHope** [Binaryify/NeteaseCloudMusicApi#643]
## 环境
- 系统/平台: <你的系统和平台>
ubuntu
- nodejs 版本: <你的 NodeJS 版本号>
v8.10.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3
## 出现问题
我在项目里面用ajax访问请求接口
request( `${baseUrl}login/cellphone?phone=${ data.phone }&password=${ data.password }&timestamp=${timestamp}`);
然后用postman访问同域的/login/status，一直是301，但是在浏览器url里访问接口登录后，再访问login/status就能拿到数据了
我能问问是什么原因吗

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
api server 内不记录 session，通过响应头 `set-cookie` 让浏览器保存登录状态，请求头里带 `cookie` 才算有效登录

前端 ajax 访问登录接口，cookie 只记录在浏览器内；postman 是另一个应用，不共享 cookie

**Comment by thinkerHope** [comment]
我明白了，谢谢

**Comment by pandxiong** [comment]
请教一下，我出现了相同的现象，不同的是我用的是小程序的云服务器去请求我自己部署的服务器，调登录接口成功后再调/login/status一直是301，在浏览器去调我自己部署的服务器是正常的，请问是怎么回事呢？cookie应该是在登录是时候已经存服务器了？还是说其他原因呢？求教！！

**Comment by nondanee** [comment]
@pandxiong 
不清楚，小程序的云服务器相当于 proxy 吗？小程序会自动处理 cookie 吗？
请求 `/login/status` 要有 cookie 才行
如果小程序不会保存 cookie 的话应该需要手动从 response headers 里取 `set-cookie `并保存

**Comment by pandxiong** [comment]
是取到MUSIC_U、__remember_me、__csrf这几个吗？保存在哪里呢？或者说我发送请求的时候怎么携带过去呢？我现在能拿到headers的set-cookie，求教！

**Comment by pandxiong** [comment]
@nondanee是取到MUSIC_U、__remember_me、__csrf这几个吗？保存在哪里呢？或者说我发送请求的时候怎么携带过去呢？我现在能拿到headers的set-cookie，求教！

**Comment by nondanee** [comment]
@pandxiong 是的，小程序有 globalStorage 吗？不太清楚
发请求的时候加在 request headers 里
```js
{cookie: 'MUSIC_U=?; __remember_me=?; __csrf=?'}
```

**Comment by pandxiong** [comment]
@nondanee 已经解决了，谢谢！！

**Comment by PrintzZZ** [comment]
登录的时候浏览器的响应头里面能看到set-cookie,但是控制台的headers里面只有
{cache-control: "max-age=120"
content-length: "1361"
content-type: "application/json; charset=utf-8"}
这三个,有什么办法可以拿到set-cookie的值吗?

**Comment by nondanee** [comment]
@PrintzZZ 
前端取不到 `set-cookie` 这个请求头的，就算 cors expose headers 也不行
不跨域的话可以从 `document.cookie` 里取

**Comment by superowner** [comment]
现在是不是邮箱登入被和谐了，我用的一个.Net版本的，无法登入，有一个用这个部署的web版也无法登入，只能手机？

**Comment by Binaryify** [comment]
@superowner 没有和谐,尽量不要用第三方的
