### ISSUE TITLE
pc端，没有用户的听歌排行榜的接口

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#645]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v11.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.0
## 出现问题
<出现的问题>
pc端，没有用户的听歌排行榜的接口
![image](https://user-images.githubusercontent.com/26435134/69318748-cc373380-0c78-11ea-8458-2e6d2aee86c4.png)

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
传入用户id,可以返回相对应的听歌排行榜的数据

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
别人的听歌排行无法显示 playCount #455 
个人主页展示可以设置听歌排行 **"所有人、我关注的人、仅自己"** 可见，用户不让看就获取不到

**Comment by shangsheng** [comment]
好的，知道了，谢谢
