### ISSUE TITLE
登陆了还是无法获取到每日推荐

### ISSUE THREAD

**Issue by Jaygk** [Binaryify/NeteaseCloudMusicApi#648]
## 环境
- 系统/平台: Windows

- nodejs 版本: 10.13.0

- API版本: 3.25.3

## 出现问题
登陆了之后还是无法获取每日推荐歌曲
重启服务器和清缓存还是没用

## 重现步骤
![image](https://user-images.githubusercontent.com/49185245/69648311-0738cd00-10a6-11ea-94bc-6612ecff94ab.png)

![image](https://user-images.githubusercontent.com/49185245/69649120-81b61c80-10a7-11ea-9ac2-91834130d133.png)

status code 301

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Jaygk** [comment]
已解决

**Comment by Hurricane233** [comment]
怎么解决的
