### ISSUE TITLE
请问下音乐url端口是被和谐了嘛？搜出来url都是null

### ISSUE THREAD

**Issue by LeooonH** [Binaryify/NeteaseCloudMusicApi#65]
搜出来url都是null
<img width="315" alt="screen shot 2017-06-27 at 5 22 46 pm" src="https://user-images.githubusercontent.com/22501635/27575480-4d196042-5b5d-11e7-88a1-6520c3d3f9e1.png">

**Comment by Binaryify** [comment]
能提供重现吗

**Comment by LeooonH** [comment]
截图是我用教程的例子(/music/url?id=347230)搜出来的结果 
我还用搜索功能搜歌曲，然后根据歌曲id搜url，同样也是null。
几天前我搜url还有结果的，不过url打不开。今天搜出来都是null了。

还有播放mv功能，我调用播放mv的例子（/mv/url?url=http://v4.music.126.net/20170422034915/c98eab2f5e2c85fc8de2ab3f0f8ed1c6/web/cloudmusic/MjQ3NDQ3MjUw/89a6a279dc2acfcd068b45ce72b1f560/533e4183a709699d566180ed0cd9abe9.mp4)，结果显示拒绝访问。

**Comment by Binaryify** [comment]
是不是你访问太频繁了,我这里是正常的
![image](https://user-images.githubusercontent.com/12221718/27577121-1d0212e2-5b52-11e7-817f-f2014efb99ad.png)

**Comment by LeooonH** [comment]
是我的问题，我用了换了国内ip就能搜到了。可是url似乎打不开，还有请问下播放mv出403拒绝访问的错误和我ip有关吗？还是需要登陆才能播放吗？（我记得我之前登陆了之后也是这样）。
<img width="1920" alt="screen shot 2017-06-27 at 6 09 47 pm" src="https://user-images.githubusercontent.com/22501635/27577420-f5cc96d6-5b63-11e7-9481-43854134ef29.png">

**Comment by Binaryify** [comment]
@LeooonH 
必须国内 ip

**Comment by LeooonH** [comment]
我在util.js的header改了ip能搜出结果，但是打不开。我用代理试试。谢谢，麻烦你了！ @Binaryify

**Comment by Binaryify** [comment]
@LeooonH 
👌
