### ISSUE TITLE
apicache没有正确处理post

### ISSUE THREAD

**Issue by xaengceilbiths** [Binaryify/NeteaseCloudMusicApi#652]
API版本:3.25.3

## 重现步骤
使用POST方法调用/song/url，无论参数id如何变化2分钟内返回值都不会变。

## 期待效果
希望apicache能正确处理POST，POST方法对某些语言很方便。或者对POST停用apicache，这样比现在的情况好。

**Comment by Binaryify** [comment]
你加时间戳就行
