### ISSUE TITLE
全部mv接口，offset > 0 时，无法获取mv总条数

### ISSUE THREAD

**Issue by summeryio** [Binaryify/NeteaseCloudMusicApi#655]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
https://i.loli.net/2019/12/03/F2ZyqXpmnJ61NHP.png

https://i.loli.net/2019/12/03/4lqinK12k5t9VgR.png

这里我是想做个分页效果的，可是点击页码后，就没有mv总条数返回了

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
字段的问题无解，自己处理一下
