### ISSUE TITLE
获取的mv和视频播放地址，报403

### ISSUE THREAD

**Issue by RexHuang1** [Binaryify/NeteaseCloudMusicApi#656]
## 环境
- 系统/平台: <Linux CentOS 7.6 64位>

- nodejs 版本: <v10.17.0>

- API版本:<3.25.3>

## 出现问题
<出现的问题>
调用获取mv和视频播放地址接口，获得的地址报403 Forbidden。
## 重现步骤
<重现步骤>
/mv/url?id=10873772
/video/url?id=89ADDE33C0AAE8EC14B99F6750DB954D
## 期待效果
<现在的效果，期待的效果>

**Comment by nondanee** [comment]
创建 issue 的时候就有 related issues 啊

![image](https://user-images.githubusercontent.com/26399680/70206252-d4579e80-1761-11ea-92f8-4d22939a8bca.png)

**Comment by RexHuang1** [comment]
之前查过相应issue，问题没解决才创建的。
当时我用的是chrome的插件Postman做的接口测试。从Postman获取的mv和视频链接地址后在chrome上直接访问链接，报403。
今天试了不使用Postman直接测试接口获取的视频链接地址可以直接访问。

**Comment by InputMyHeart** [comment]
有老哥知道获取歌单详情接口报502，是什么情况呀，我是用的小程序
