### ISSUE TITLE
无法获取正确图片地址

### ISSUE THREAD

**Issue by Littleor** [Binaryify/NeteaseCloudMusicApi#657]
## 环境
- 系统/平台: Centos

- nodejs 版本: 10.16

- API版本:3.25.3

## 出现问题
search中获取到的所有图片链接都是:https://p1.music.126.net/6y-UleORITEDbvrOLV0Q8A==/5639395138885805.jpg

## 重现步骤
<重现步骤>

## 期待效果
获取到正常的图片链接撒

**Comment by PeppaPig2000** [comment]
可以在拿到id以后去 song/detail 拿图片
