### ISSUE TITLE
搜索传type:1(单曲)的时候没有返回picUrl   返回的为null

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#658]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
![QQ截图20191207111625](https://user-images.githubusercontent.com/38646454/70368232-0a705c00-18e3-11ea-940d-16798bf21b97.png)

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
期望返回picUrl 或者通过picid获取pic

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
搜索就是这样的,要图片去查song/detail

**Comment by refuse-c** [comment]
我现在就是这么实现的  拿到检索的id进行遍历,然后去detail拿info
发件人: binaryify<mailto:notifications@github.com>
发送时间: 2019年12月17日 11:22
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 搜索传type:1(单曲)的时候没有返回picUrl 返回的为null (#658)


搜索就是这样的,要图片去查song/detail

―
