### ISSUE TITLE
获取个人信息，能否把省份和城市的文字返回

### ISSUE THREAD

**Issue by lxhcool** [Binaryify/NeteaseCloudMusicApi#659]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by kurodaakira-jp** [comment]
这个自己就可以实现，安个mysql导入省市数据，然后nodejs写个查询api就行了，我自己有写好的，明天我开源出来（如果明天没忘。。。

**Comment by kurodaakira-jp** [comment]
https://github.com/kurodaakira-jp/NeteaseCloudMusicApi-eapi

**Comment by lxhcool** [comment]
嗯嗯，我自己实现了


| |
廖鑫豪
|
|
邮箱：18668161482@163.com
|

签名由 网易邮箱大师 定制

在2019年12月17日 19:37，kurodaakira-jp 写道：

这个自己就可以实现，安个mysql导入省市数据，然后nodejs写个查询api就行了，我自己有写好的，明天我开源出来（如果明天没忘。。。

**Comment by yanorl** [comment]
直接调用高德地图的api 就可以了 https://lbs.amap.com/api/webservice/guide/api/district
