### ISSUE TITLE
只能获取歌单前1000首歌的详细信息

### ISSUE THREAD

**Issue by simpleworldz** [Binaryify/NeteaseCloudMusicApi#660]
## 环境
- 系统/平台: win 10 

- nodejs 版本:  12.13.1

- API版本:3.25.3

## 出现问题
/playlist/detail 只能获取歌单前1000首歌的详细信息。

## 重现步骤
![01](https://user-images.githubusercontent.com/26664643/70961866-1e277980-20be-11ea-842a-fcddb3cba977.PNG)

## 期待效果
能获取歌单所有歌曲的详细信息。

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/452

**Comment by simpleworldz** [comment]
看过那个，是目前还没解决这个问题，只能用Id去请求详细信息吗？

**Comment by Binaryify** [comment]
拿id去请求
song/detail 支持多个id的

**Comment by simpleworldz** [comment]
忘了这一茬了，记得以前也试过，谢啦！
