### ISSUE TITLE
/check/music 的接口对于可用（!灰色）的歌曲，仍会报无版权

### ISSUE THREAD

**Issue by AlioLozy** [Binaryify/NeteaseCloudMusicApi#661]
版本：3.25.3

## 歌单中的部分歌曲为需要单独付费购买的专辑
https://music.163.com/playlist?id=2698977495

歌曲ID：[1396349011, 1391477429, 1386175488, 1386175484, 1369998604, 532777048, 1334849028]

请求返回结果：
```
1396349011: {'name': 'Wonderland', 'artist': '林俊杰', 'album': 'Wonderland', 'copyright': '亲爱的,暂无版权'}
```
PS：~~有可能专辑购买后就不会报错了，这个我暂时没法测试。~~
经测试，登录了购买过此歌曲或者此专辑的账号，请求结果不会报 “无版权”。

## 歌单中的部分歌曲需要下载后才能播放（常见下载后为 NCM 加密格式）
https://music.163.com/playlist?id=2228507437

歌曲 ID：[557407036, 5032212]

请求返回结果：
```
557407036: {'name': 'Ashes (from Deadpool 2)', 'artist': 'Celine Dion', 'album': 'Deadpool 2 (Original Motion Picture Soundtrack)', 'copyright': '亲爱的,暂无版权'}
```

**Comment by nondanee** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/9443bb25625a68d1e79ab25b24227393ddecd836/module/check_music.js#L19-L27

这个结果是写死的 == 提示语改成 "无法播放" 应该更合适一点 (无法播放的原因并不一定是没版权)

实际网易云没有 `/check/music` 这样的接口
`check/music` 这个接口其实就是 `/song/url` 的逻辑 + 判断 url 是否为空，和你直接请求 /song/url 消耗的资源是一样的，如果是要播放的话相当于还浪费了一次请求

建议不要用这个接口了

**Comment by AlioLozy** [comment]
> https://github.com/Binaryify/NeteaseCloudMusicApi/blob/9443bb25625a68d1e79ab25b24227393ddecd836/module/check_music.js#L19-L27
> 
> 这个结果是写死的 == 提示语改成 "无法播放" 应该更合适一点 (无法播放的原因并不一定是没版权)
> 
> 实际网易云没有 `/check/music` 这样的接口
> `check/music` 这个接口其实就是 `/song/url` 的逻辑 + 判断 url 是否为空，和你直接请求 /song/url 消耗的资源是一样的，如果是要播放的话相当于还浪费了一次请求
> 
> 建议不要用这个接口了

我觉得修改一下判断逻辑还是可以的……

如下图，红框是真没版权（灰色），绿框是有版权，但是存在其他版权限制（eg. 下载后播放）,真无版权的会有个 `class = js-dis` 

![image](https://user-images.githubusercontent.com/44765750/71322635-c8f7c780-2504-11ea-94e1-93f5d9caefdc.png)
