### ISSUE TITLE
登陆后调用此接口 , 可以获取用户信息  ，应该传递什么参数

### ISSUE THREAD

**Issue by yanorl** [Binaryify/NeteaseCloudMusicApi#663]
获取用户信息 , 歌单，收藏，mv, dj 数量
说明 : 登陆后调用此接口 , 可以获取用户信息

接口地址 : /user/subcount

调用例子 : /user/subcount

这里面应该传什么参数，才能获取到数据

**Comment by Binaryify** [comment]
你登录了就行

**Comment by lang1427** [comment]
邮箱登陆状态下 ， 请求 该接口  返回   {code：302 }
