### ISSUE TITLE
请求“mv 地址”接口，返回成功，但是MV播放次数没增加。

### ISSUE THREAD

**Issue by ohongyangf** [Binaryify/NeteaseCloudMusicApi#664]
## 出现问题

我尝试请求“mv 地址”接口，请求返回时200，是成功了的，但是网页上刷新看到的，MV播放次数没有增加，这是什么情况呢？

**Comment by nondanee** [comment]
那有可能是埋点统计的
(你是想刷榜吗 ==，这样不太好吧)

**Comment by ohongyangf** [comment]
提供这些接口了 也应该适当能实现功能呢，不刷榜 只提供少量点击量？能解决这个问题吗？
如果按照正常访问视频网站 正常播放 播放次数也没所上升 是不是网易不做播放次数了？

**Comment by Binaryify** [comment]
播放次数是埋点接口实现的,这里不打算加进来的.官方的为了防刷,会延迟增加次数
