### ISSUE TITLE
邀请前端开发人员重构桌面版的网易云音乐（非Electron ，基于vue3（等待发布稳定版））

### ISSUE THREAD

**Issue by Linkontoask** [Binaryify/NeteaseCloudMusicApi#665]
谢谢楼主的平台

仓库地址 [https://github.com/Linkontoask/radishes](https://github.com/Linkontoask/radishes)

**Comment by Linkontoask** [comment]
我发现作者未提供在线API，我这里提供一个临时的吧 [地址](https://music.linkorg.club/)

**Comment by mantou132** [comment]
我有个歌词扩展，可以使用你提供的这个 API 服务吗？什么时候会失效呢？

https://github.com/mantou132/Spotify-Lyrics

感谢。

**Comment by Linkontoask** [comment]
可以使用，年中可能失效。我不太确定
