### ISSUE TITLE
喜欢音乐api 频繁调用有时返回405

### ISSUE THREAD

**Issue by yanorl** [Binaryify/NeteaseCloudMusicApi#667]
我将 “获取用户播放记录api” 得到的歌曲 id,  传给 “喜欢音乐api ” ，因为 歌曲 id 有100个，所以有时候回返回405  的问题，求解决方法

**Comment by nondanee** [comment]
可以批量加到歌单，"我喜欢的歌曲" 也是一个歌单
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=对歌单添加或删除歌曲

**Comment by Chuan1997** [comment]
> 可以批量加到歌单，"我喜欢的歌曲" 也是一个歌单 [https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=对歌单添加或删除歌曲](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E5%AF%B9%E6%AD%8C%E5%8D%95%E6%B7%BB%E5%8A%A0%E6%88%96%E5%88%A0%E9%99%A4%E6%AD%8C%E6%9B%B2)

我也尝试爬取用户“喜欢的歌曲”，调用的是http://localhost:3000/playlist/detail?id=这个接口，不管间隔时间是多久，都是返回大量的405
