### ISSUE TITLE
搜索功能：当type===1018时，如何控制返回结果的数量？

### ISSUE THREAD

**Issue by DJAlejandro** [Binaryify/NeteaseCloudMusicApi#668]
搜索功能中

type: 搜索类型；默认为 1 即单曲 , 取值意义 : 1: 单曲, 10: 专辑, 100: 歌手, 1000: 歌单, 1002: 用户, 1004: MV, 1006: 歌词, 1009: 电台, 1014: 视频, 1018:综合

limit : 返回数量 , 默认为 30

测试发现type！==1018时，limit可以控制返回结果的数量，但是当type===1018时，返回的结果为综合结果，数据结构发生变化。修改limit参数对返回结果的数量无影响。

那么当type===1018时，如何控制返回结果的数量？

**Comment by Binaryify** [comment]
我的理解是综合是不需要分页的,所以官方也没提供这个功能,官方app(ios)下也没展示那么多结果,有个查看全部单曲,点进去就是搜索单个类目下的结果

**Comment by DJAlejandro** [comment]
> 我的理解是综合是不需要分页的,所以官方也没提供这个功能,官方app(ios)下也没展示那么多结果,有个查看全部单曲,点进去就是搜索单个类目下的结果

了解到了，感谢回复！

**Comment by Binaryify** [comment]
嗯嗯
