### ISSUE TITLE
搜索结果翻页请求的数据一致

### ISSUE THREAD

**Issue by lang1427** [Binaryify/NeteaseCloudMusicApi#669]
## 环境
- 系统/平台: <你的系统和平台>
Window7

- nodejs 版本: <你的 NodeJS 版本号>
10.15.3

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3

## 出现问题
<出现的问题>
搜索结果当offset+1时返回的数据和原数据一致

## 重现步骤
<重现步骤>
http://localhost:3000/search?keywords=%E4%B8%8B%E5%B1%B1&limit=30&offset=2&type=1
http://localhost:3000/search?keywords=%E4%B8%8B%E5%B1%B1&limit=30&offset=1&type=1

## 期待效果
<现在的效果，期待的效果>  
翻页 数据 期待返回不一致的效果，或者为没有这么多数据

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
offset 的含义你再看看文档

**Comment by lang1427** [comment]
从offset =1 设置到 2 ，是从请求30条数据到 请求60条数据，而不是在追加30条数据 ，是吗？
例子 ：  offset * limit 
请问 有 对应的翻页请求例子吗

**Comment by Binaryify** [comment]
文档写得很清楚了

**Comment by lang1427** [comment]
ok
