### ISSUE TITLE
没有收藏的视频列表的API

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#670]
## 环境
- 系统/平台: <你的系统和平台>
window
- nodejs 版本: <你的 NodeJS 版本号>
v11.12.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.0
## 出现问题
<出现的问题>
没有收藏的视频列表的接口
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
希望与‘收藏的MV列表’的接口的效果一致

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
没区别吧
![image](https://user-images.githubusercontent.com/12221718/71434599-36cc0b00-2720-11ea-98e0-52054f99e8e6.png)
![image](https://user-images.githubusercontent.com/12221718/71434603-3cc1ec00-2720-11ea-96b8-347a76d64b26.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/71434625-4b100800-2720-11ea-9df6-bfe2f2660bb8.png)

**Comment by shangsheng** [comment]
谢谢，大神，我知道我的原因所在了，那我在问一个问题
![image](https://user-images.githubusercontent.com/26435134/71436562-f8871980-2728-11ea-9d71-727fc82dccc8.png)这个接口 调的数据
![微信图片_20191225151535](https://user-images.githubusercontent.com/26435134/71436691-8531d780-2729-11ea-9659-2434126743a7.png)是不是没有视频的数量？能不能添加一个视频的数量

**Comment by Binaryify** [comment]
那个网易给的数据,我加不了

**Comment by shangsheng** [comment]
好的，谢了
