### ISSUE TITLE
您好,请问有更换头像的api接口么,我在基本信息里没有找到,谢谢

### ISSUE THREAD

**Issue by l-ning** [Binaryify/NeteaseCloudMusicApi#672]
## 环境
- 系统/平台: Mac OSX

- nodejs 版本: v13.1.0

- API版本:目前最新版:[2019年12月27日]

## 出现问题
请问是否有包含更改头像的api接口

## 重现步骤
无

## 期待效果
更改头像

**Comment by Binaryify** [comment]
没有
