### ISSUE TITLE
API的网址能否更改为类似于localhost:3000/somewhere的地址

### ISSUE THREAD

**Issue by LittleYe233** [Binaryify/NeteaseCloudMusicApi#674]
使用文档里所述的API根地址都是localhost:3000，加参数的时候也是localhost:3000/login/status之类的。现能否使根地址改成“localhost:3000/somewhere”的形式，即在调用接口的时候变成localhost:3000/somewhere/login/status？

**Comment by Binaryify** [comment]
1. 改app.js
2. nginx 转发
