### ISSUE TITLE
发私信功能失效

### ISSUE THREAD

**Issue by zhuyue11** [Binaryify/NeteaseCloudMusicApi#677]
## 环境
- 系统/平台: mac

- nodejs 版本: v11.2.0

- API版本: 3.25.3

## 出现问题
发私信接口无效

## 重现步骤
登录 -》 发私信

response: {"code":250,"msg":"发送私信异常","data":{"dialog":{"title":"风险提示","subtitle":"请您尝试切换网络或设备再尝试操作哦~","buttonMsg":"查看详情","buttonUrl":"http://163.lu/EmUzy2"}}}

## 期待效果
成功发送私信

**Comment by zhuyue11** [comment]
这个是解决了吗？

**Comment by Binaryify** [comment]
我这边没问题
你把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉试试
