### ISSUE TITLE
在阿里云centos上提示连接超时

### ISSUE THREAD

**Issue by tgxhx** [Binaryify/NeteaseCloudMusicApi#68]
### 环境
系统:  centos 6.8 x64

nodejs 版本:6.10.2

### 出现问题
在阿里云华南机房centos上，提示连接超时
![qq 20170703015925](https://user-images.githubusercontent.com/5463739/27772375-7ed7163a-5f93-11e7-8e18-e9b90bada945.png)

在本地电脑windows10上无此问题，怀疑是被封了ip？
如果是封了ip，有没有其他解决方案？

**Comment by FlyingAir** [comment]
跟楼上一样的情况

**Comment by Binaryify** [comment]
请问是怎么触发的

**Comment by FlyingAir** [comment]
可以正常进入这个页面
-------------
网易云音乐 API

当你看到这个页面时,这个服务已经成功跑起来了~ 查看文档
例子:

1. 搜索
2. 歌曲评论
3. 电台节目
----------------------
请求api时就会Error: connect ETIMEDOUT 59.111.160.195:80

**Comment by Binaryify** [comment]
加代理 IP 试试
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/29#issuecomment-298358438

**Comment by tgxhx** [comment]
@Binaryify 加代理ip试了无效

**Comment by Binaryify** [comment]
@tgxhx 
只有阿里云这样吗,检查下防火墙

**Comment by tgxhx** [comment]
@Binaryify 算了，还是不行，估计是封ip了，我换个服务器吧
