### ISSUE TITLE
歌词获取是不是又挂了。。。

### ISSUE THREAD

**Issue by chenweize** [Binaryify/NeteaseCloudMusicApi#682]
歌词获取code200, 但是内容啥子都没有。。。

**Comment by BILYHO** [comment]
貌似接口变了 我官网看了一下 变成了post请求 并且有加密了~~~~

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/72501836-dfc6db00-3872-11ea-8719-5151ce6c53af.png)
我这边可以,你们服务器环境怎样的,是国外的还是阿里云

**Comment by BILYHO** [comment]
> ![图片](https://user-images.githubusercontent.com/12221718/72501836-dfc6db00-3872-11ea-8719-5151ce6c53af.png)
> 我这边可以，你们服务器环境怎样的，是国外的还是阿里云

完整的地址是啥~~~

**Comment by Binaryify** [comment]
> > ![图片](https://user-images.githubusercontent.com/12221718/72501836-dfc6db00-3872-11ea-8719-5151ce6c53af.png)
> > 我这边可以，你们服务器环境怎样的，是国外的还是阿里云
> 
> 完整的地址是啥~~~

就文档例子

**Comment by chenweize** [comment]
我的问题，我这边自己解决了
