### ISSUE TITLE
获取歌曲详情

### ISSUE THREAD

**Issue by masterxing** [Binaryify/NeteaseCloudMusicApi#685]
## 环境
- 系统/平台: mac
- nodejs 版本: v11.13.0

- API版本:3.25.3

## 出现问题
歌单超过1000 用ids去获取歌曲详情 返回500 （Cannot read property 'split' of undefined）

## 重现步骤
怀疑是参数过长 截取ids的1/3再次请求/song/detail  200成功

## 期待效果
期待是传入多少ids 返回多少歌曲

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
我这里没法复现 500，client request 直接 error 了
本来想返回 431 的，但是没法复现就没法调试

你把参数放 body 里面用 POST 传
