### ISSUE TITLE
有人用uniapp开发过吗？

### ISSUE THREAD

**Issue by HehongGit** [Binaryify/NeteaseCloudMusicApi#686]
我想使用uniapp实现这个项目，但是uniapp不支持cookie，登录态记录不了，很多借口就没法调用，有大神指导下吗？

**Comment by nondanee** [comment]
Duplicate #625

**Comment by valone-1** [comment]
巧了 我也在写 快写完了都

**Comment by valone-1** [comment]
效果如何 我也在用uniapp做

**Comment by HehongGit** [comment]
不行，小程序没有cookie，登录态记录不了

**Comment by nondanee** [comment]
@valone-1 
大猪蹄子，你都说了 "快写完了都"，钓鱼嘛？
github comment 可没有撤回一说~
https://www.gitmemory.com/valone-1

**Comment by nondanee** [comment]
@HehongGit 参考 https://github.com/Binaryify/NeteaseCloudMusicApi/issues/625#issuecomment-582382474

**Comment by valone-1** [comment]
> @valone-1
> 大猪蹄子，你都说了 "快写完了都"，钓鱼嘛？
> github comment 可没有撤回一说~
> https://www.gitmemory.com/valone-1

刚学uniapp没多久 小菜🐔一枚 想看下前辈写的效果 我的歌曲详情始终获取不到😰

**Comment by liuxiaoyucc** [comment]
https://github.com/liuxiaoyucc/cloudmusic/tree/master/NVUE
多多指教
