### ISSUE TITLE
请教一下Proxy 代理问题    一个可用服务器ip  并不能代理成功  请求502

### ISSUE THREAD

**Issue by zzfc** [Binaryify/NeteaseCloudMusicApi#688]
## 环境
- 系统/平台: <windows 10>

- nodejs 版本: <v12.13.0>

- API版本:<3.25.3>

## 出现问题
<出现的问题>
proxy 代理无效
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
502 应该有 error message 的吧？

**Comment by zzfc** [comment]
> 502 应该有 error message 的吧？

木有  有的话应该还是能解决的额    很久没管了 忘记了
