### ISSUE TITLE
部署到服务器无法访问的问题

### ISSUE THREAD

**Issue by userNamexiong** [Binaryify/NeteaseCloudMusicApi#689]
我部署到阿里云服务器，linux系统，启动服务后无法访问3000端口的，服务器3000端口开发了，请问有没有知道怎么解决的大佬

**Comment by nondanee** [comment]
去查防火墙/安全组/IPset，不要用没有备案的域名访问

**Comment by bluryar** [comment]
是学生机？放nginx上吧
