### ISSUE TITLE
邮箱登录成功后，拿到的id不能获取用户,歌单信息，手机登录的却可以

### ISSUE THREAD

**Issue by TheKingOfTime** [Binaryify/NeteaseCloudMusicApi#690]
## 环境
- 系统/平台: <你的系统和平台>
Windows10
- nodejs 版本: <你的 NodeJS 版本号>
v12.14.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3
## 出现问题
<出现的问题>
通过axios请求接口，使用邮箱登录成功后返回的id不能获取用户的歌单信息，直接返回{"code":404}
使用手机号登录一切正常

**Comment by nondanee** [comment]
邮箱登录的账号和手机登录的账号是同一个吗？
拿到 id 不一样吗？

能稳定复现吗？(我试了没问题)
https://music.163.com/#/user/home?id=xxx 用户主页能打开吗？
最好能截图说明

**Comment by TheKingOfTime** [comment]
手机号登录

返回的id

使用邮箱登录

返回id







使用手机号的返回id访问网易云

使用邮箱的返回id访问网易云


得知邮箱返回的id存在问题

**Comment by nondanee** [comment]
邮件回复看不到图

**Comment by TheKingOfTime** [comment]
手机号返回的id进行拼接:https://music.163.com/#/user/home?id=1770521567
邮箱返回的id进行拼接:https://music.163.com/#/user/home?id=2135876027

**Comment by nondanee** [comment]
这三个全都不对吗？
account.id
profile.userId
bindings.userId

**Comment by TheKingOfTime** [comment]
使用邮箱登录返回的数据:
loginType:&nbsp;0

code:&nbsp;200

account:

id:&nbsp;2135876027

userName:&nbsp;"0_997253389@qq.com"

type:&nbsp;0

status:&nbsp;-10

whitelistAuthority:&nbsp;0

createTime:&nbsp;1580731248791

salt:&nbsp;""

tokenVersion:&nbsp;0

ban:&nbsp;0

baoyueVersion:&nbsp;0

donateVersion:&nbsp;0

vipType:&nbsp;0

viptypeVersion:&nbsp;0

anonimousUser:&nbsp;false

__proto__:&nbsp;Object

token:&nbsp;"77683768948d8ed9d5835394ef86f836dfb87cf702a12be81c9d7161580edbb85a32301f4b05feeea254c82d56a9b4d30f04db37a3e30627c3061cd18d77b7a0"

bindings:&nbsp;[]

__proto__:&nbsp;Object





使用手机号登录返回的数据:

loginType:&nbsp;1

code:&nbsp;200

account:

id:&nbsp;1770521567

userName:&nbsp;"1_17671620624"

type:&nbsp;1

status:&nbsp;0

whitelistAuthority:&nbsp;0

createTime:&nbsp;1550682713982

salt:&nbsp;"[B@3706fb60"

tokenVersion:&nbsp;0

ban:&nbsp;0

baoyueVersion:&nbsp;0

donateVersion:&nbsp;0

vipType:&nbsp;0

viptypeVersion:&nbsp;0

anonimousUser:&nbsp;false

__proto__:&nbsp;Object

token:&nbsp;"d33658da9213990d725acdd959a31c6b173217d452fe30431f3dbf1b07b0f467da23f3a0d153a757da1b7888bb1ce11e41049cea1c6bb9b6"

profile:

detailDescription:&nbsp;""

followed:&nbsp;false

backgroundUrl:&nbsp;"https://p4.music.126.net/POKG4NeIeElptyx6ld2F_g==/109951164138780520.jpg"

city:&nbsp;440300

userType:&nbsp;0

backgroundImgId:&nbsp;109951164138780510

experts:&nbsp;{}

userId:&nbsp;1770521567

djStatus:&nbsp;0

avatarImgIdStr:&nbsp;"109951164138119329"

backgroundImgIdStr:&nbsp;"109951164138780520"

province:&nbsp;440000

defaultAvatar:&nbsp;false

avatarUrl:&nbsp;"https://p4.music.126.net/oBFdYcRdR57iJk6Kqq7Hpg==/109951164138119329.jpg"

mutual:&nbsp;false

remarkName:&nbsp;null

expertTags:&nbsp;null

authStatus:&nbsp;0

nickname:&nbsp;"会笑的眼睛真美_R"

birthday:&nbsp;-2209017600000

accountStatus:&nbsp;0

vipType:&nbsp;0

gender:&nbsp;1

avatarImgId:&nbsp;109951164138119330

description:&nbsp;""

signature:&nbsp;""

authority:&nbsp;0

avatarImgId_str:&nbsp;"109951164138119329"

followeds:&nbsp;0

follows:&nbsp;5

eventCount:&nbsp;0

playlistCount:&nbsp;3

playlistBeSubscribedCount:&nbsp;0

__proto__:&nbsp;Object

bindings:&nbsp;Array(2)

0:&nbsp;{url:&nbsp;"",&nbsp;refreshTime:&nbsp;1559572941,&nbsp;tokenJsonStr:&nbsp;"{"countrycode":"","cellphone":"17671620624","hasPassword":true}",&nbsp;expiresIn:&nbsp;2147483647,&nbsp;userId:&nbsp;1770521567,&nbsp;…}

1:&nbsp;{url:&nbsp;"",&nbsp;refreshTime:&nbsp;1580748673,&nbsp;tokenJsonStr:&nbsp;"{"access_token":"788F4E3AEA9A1CA848F9CECD7CD0C791"…n":7776000,"login_cost":25,"authority_cost":2959}",&nbsp;expiresIn:&nbsp;7776000,&nbsp;userId:&nbsp;1770521567,&nbsp;…}

length:&nbsp;2

__proto__:&nbsp;Array(0)

__proto__:&nbsp;Object

**Comment by nondanee** [comment]
我也不知道

我是网易邮箱，为什么 qq 邮箱也可以登录？不是要求网易邮箱吗

![image](https://user-images.githubusercontent.com/26399680/73858208-fa3d1480-4872-11ea-936e-b502ddb1eced.png)


或许是这个问题==

邮箱登录以后你请求下 `/login/status` 看看 id 对不对吧

**Comment by TheKingOfTime** [comment]
![S00206-00261936](https://user-images.githubusercontent.com/46626448/73862670-ce03a280-4836-11ea-9a9b-4caffbdc3cb1.png)
刚刚在网易云音乐(手机客户端)试了试
用邮箱登录会出现这种情况(截图-附件)
然后正常登录

**Comment by TheKingOfTime** [comment]
好吧，我的问题，我之前没绑定网易云邮箱
绑定了后就成功了
![RW%@52Z_E2RPTBO53CYVRZH](https://user-images.githubusercontent.com/46626448/74005151-e1feef80-496f-11ea-80c9-c52633ca313c.png)

**Comment by lang1427** [comment]
同问：  邮箱登陆状态下  请求/user/subcount 接口    直接返回 {code：302}
