### ISSUE TITLE
在termux运行服务器后无法登陆

### ISSUE THREAD

**Issue by MansonLuo** [Binaryify/NeteaseCloudMusicApi#691]
## 环境
- 系统/平台: 安卓手机 红米7 termux软件 aarch64

- nodejs 版本: v13.0.0

- API版本: 3.25.3

## 出现问题
在termux里运行服务器后，尝试使用手机号码登陆。
以下操作均在在手机浏览器里进行:
输入网址可以获取验证码，验证验证码成功(返回200)。但是输入http://localhost:3000/login
后，返回{"code":301,"msg":"需要登录"}

/status## 重现步骤
1.  下载termux
2. 开启梯子，打开termux
3. 输入apt-get update;apt-get upgrade
4: 输入pkg install nodejs
5: pkg install git; git clone <你的项目地址>;cd xx
6: npm install;node app.js

## 期待效果
查看登陆状态，是301，期望200

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
测了下确实

因为 /captcha/verify 这个接口没有 set-cookie
接口行为应该是只会验证，不消费验证码
(可以多次调用返回 200，一般来说验证码只能用一次)

和 termux 环境没关系

验证码登录应该是别的接口，项目里还没有

这个接口是 #460 引进的，可以找那位 Contributor 帮你看看
