### ISSUE TITLE
请问一下音乐的时长是哪个接口下哪个数据啊

### ISSUE THREAD

**Issue by FYH7Yuan** [Binaryify/NeteaseCloudMusicApi#693]
## 环境
- 系统/平台: <你的系统和平台>
windows10
- nodejs 版本: <你的 NodeJS 版本号>
v12.12.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3
## 出现问题
<出现的问题>
歌曲详情里找不到歌曲时长duration 在song/detail的返回数据以及 歌单的返回数据里均没有找到歌曲时长 之前的issue写的st获取到的都是0 求解啊毕设进度卡住了

**Comment by nondanee** [comment]
/song/detail 里有的
`dt` 字段，单位毫秒

Duplicate #125 #140 #204 #559 

`st` 好像是判断能不能播放的

**Comment by FYH7Yuan** [comment]
感谢 之前注意到dt了但是大意了
