### ISSUE TITLE
歌手全部歌曲接口

### ISSUE THREAD

**Issue by 251205668** [Binaryify/NeteaseCloudMusicApi#694]
好像歌手歌曲只能搜到热门歌曲的接口 有没有全部歌曲的接口呀

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Binaryify** [comment]
客户端有展示歌手全部歌曲的地方吗,没有的话就不能

**Comment by Binaryify** [comment]
这个已经加了
