### ISSUE TITLE
电台 - 节目：节目音频都返回null

### ISSUE THREAD

**Issue by cnyb-kwange** [Binaryify/NeteaseCloudMusicApi#695]
文档里写到：

> ... 通过调用 /song/url 这 个接口 , 传入节目 id 仍然能获取到节目音频 ...

但返回的url都是null （data: { url: null }）

例子：/song/url?id=1367665101

这能解决吗？

谢谢

**Comment by nondanee** [comment]
文档有点问题，用的不是节目 id

应该先请求 `/dj/program/detail?id=1367665101`

取 `program.mainTrackId`

再请求 `/song/url?id=<mainTrackId>`
