### ISSUE TITLE
标签下视频接口，为什么id不同，但是返回的数据时相同的。

### ISSUE THREAD

**Issue by Zaylour** [Binaryify/NeteaseCloudMusicApi#696]
![1111](https://user-images.githubusercontent.com/31010597/75052416-89e8f100-550a-11ea-85a7-a47390dcc567.png)
![222](https://user-images.githubusercontent.com/31010597/75052426-8fded200-550a-11ea-9611-7852c643ae36.png)
这里请求了两次，但是结果都是一样的；
第一次：height":1080,"width":1920,"title":"熊猫宝宝偷偷从床上爬出来乱跑，但妈妈一出现让人笑翻","
第二次:height":1080,"width":1920,"title":"熊猫宝宝偷偷从床上爬出来乱跑，但妈妈一出现让人笑翻","

是我少配置了什么东西吗

**Comment by Binaryify** [comment]
有缓存机制,相同URL返回内容会被缓存起来,post请求url带上时间戳吧

**Comment by Zaylour** [comment]
好的，时间戳字段就是time吗

**Comment by Zaylour** [comment]
![image](https://user-images.githubusercontent.com/31010597/75087472-c9035a80-557b-11ea-8d20-a85388ad71cd.png)
加了还是相同的

**Comment by nondanee** [comment]
时间戳加在 url 里，不要写 body 里
url 相同就会命中缓存
