### ISSUE TITLE
你好。搜索歌词接口不能返回歌词了，以前是可以的

### ISSUE THREAD

**Issue by xiaozhu188** [Binaryify/NeteaseCloudMusicApi#697]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
搜索歌词接口不能返回歌词

## 重现步骤
搜索歌词

## 期待效果
能搜索歌词

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
版本号,参数发过来
