### ISSUE TITLE
建议新增PC端签到

### ISSUE THREAD

**Issue by 464978516** [Binaryify/NeteaseCloudMusicApi#698]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
无法实现PC端签到

## 重现步骤
直接调用daily_singin.js传值进入，只能实现安卓签到，web签到好像也是实现
## 期待效果
能够实现PC 手机 Web三端签到

**Comment by 464978516** [comment]
我抓出来的api是`https://interface.music.163.com/eapi/batch`
但是我不知道传值如何计算的

**Comment by nondanee** [comment]
pc web 是一样的，只有两端的区别，文档里有写
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=签到

**Comment by 464978516** [comment]
好的，明天我重新测试看看
