### ISSUE TITLE
有的歌是404

### ISSUE THREAD

**Issue by zephyrzoom** [Binaryify/NeteaseCloudMusicApi#7]
比如搜半兽人，第一个id是186045，歌曲链接是http://m2.music.126.net/FeY6o5eXGVZODjOVwNm1yw==/7825224255964543.mp3

**Comment by CeBkCn** [comment]
版权问题，分析copyright

**Comment by zephyrzoom** [comment]
原来是这个原因，有没有办法登录账号？

**Comment by CeBkCn** [comment]
个人认为这个版权问题不是帐号原因，比如你说的半兽人，在网易云音乐原始页面上生成外链播放器是会有版权提示的。但是抓包依然可以抓到地址，根据歌曲id用加密的方法生成资源链接是可行的，比如listen1就做到了，当然listen1也是借鉴更早的一个命令行播放器，有兴趣可以研究一下。
当前这个api为了避免麻烦，可以判断song.copyright，如果是0，表示没问题可以用，其他的一律表示版权问题。

**Comment by zephyrzoom** [comment]
就拿这个ID186045，在http://music.163.com/#/song?id=186045上可以播放，并没有提示版权。

**Comment by CeBkCn** [comment]
“生成外链播放器”，click

**Comment by zephyrzoom** [comment]
:sob:

**Comment by Binaryify** [comment]
@zephyrzoom
准备使用网易云音乐新版api了,看看这周有没有时间更新

**Comment by Binaryify** [comment]
@zephyrzoom
由于网易云音乐新版api加密了,暂无破解方法,所以暂时不更新了,等别人破解了,我就更下

**Comment by zephyrzoom** [comment]
@Binaryify 
能不能把 #6 先更新一下

**Comment by Binaryify** [comment]
@zephyrzoom 
今天抽时间更新下吧

**Comment by qq316107934** [comment]
@Binaryify  API 已经破解了：https://github.com/cosven/FeelUOwn/blob/master/feeluown/plugins/neteasemusic/api.py
WEAPI 是加密的那部分，期待更新。

**Comment by Binaryify** [comment]
@qq316107934 
不是新版的

**Comment by Binaryify** [comment]
@qq316107934
看错了,我研究下

**Comment by Binaryify** [comment]
@qq316107934
python不是很熟,可能得花点时间

**Comment by qq316107934** [comment]
@Binaryify
https://github.com/vfan140/node-music/tree/master/server/service/wy
js版，但是他还带了utils管理cookies，可能还要剥离下。

**Comment by Binaryify** [comment]
@qq316107934 
OK

**Comment by Binaryify** [comment]
@qq316107934 @zephyrzoom 项目升级完毕

**Comment by zephyrzoom** [comment]
很强势

**Comment by qq316107934** [comment]
一直维护不易，多谢了。
