### ISSUE TITLE
歌曲url

### ISSUE THREAD

**Issue by lipuisaboy** [Binaryify/NeteaseCloudMusicApi#701]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<请求歌曲url的时候,官方文档是/song/url,实际上是/music/url>

## 重现步骤
<希望官方温暖能够改正>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/75558247-7eeb0f00-5a7c-11ea-8c76-b43ee066bd40.png)

**Comment by nondanee** [comment]
3.0 以上是 `song/url`
以下是 `music/url`
见更新说明

https://github.com/Binaryify/NeteaseCloudMusicApi/tree/master/docs#更新到-v30-说明
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/CHANGELOG.MD#300--20181014

**Comment by lipuisaboy** [comment]
请问请求歌词的接口改成什么了呢?为什么请求不到歌词数据呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nzix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 凌晨2:28
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"罢了"<1213262105@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌曲url (#701)




3.0 以上是 song/url
 以下是 music/url
 见更新说明
 
https://github.com/Binaryify/NeteaseCloudMusicApi/tree/master/docs#更新到-v30-说明
 https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/CHANGELOG.MD#300--20181014

**Comment by nondanee** [comment]
没有改，是 api 本身的问题，可能官方歌词接口挂了，而且那个带参方式也不规范
等 @Binaryify 有空会更新的

**Comment by lipuisaboy** [comment]
好的 谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nzix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 凌晨2:34
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"罢了"<1213262105@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌曲url (#701)




没有改，是 api 本身的问题，可能官方歌词接口挂了，而且那个带参方式也不规范
 等 @Binaryify 有空会更新的

**Comment by lipuisaboy** [comment]
您好,请问现在的搜索接口是什么啊 ,为什么文档里的访问不到数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nzix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 凌晨2:34
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"罢了"<1213262105@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] 歌曲url (#701)




没有改，是 api 本身的问题，可能官方歌词接口挂了，而且那个带参方式也不规范
 等 @Binaryify 有空会更新的

**Comment by Binaryify** [comment]
你是调别人搭建的还是自己本地跑的

**Comment by lipuisaboy** [comment]
直接调用的

**Comment by Binaryify** [comment]
参数发出来

**Comment by lipuisaboy** [comment]
我想获取搜索建议等内容，我就请求官方文档上的/search/suggest?keywords= 海阔天空，结果和想象的数据不一样。------------------ 原始邮件 ------------------
发件人: "binaryify"<notifications@github.com>
发送时间: 2020年3月2日(星期一) 上午9:55
收件人: "Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com>;
抄送: "lipuisaboy"<1213262105@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Binaryify/NeteaseCloudMusicApi] 歌曲url (#701)



参数发出来
 
&mdash;

**Comment by Binaryify** [comment]
> 结果和想象的数据不一样
指的是什么

**Comment by lipuisaboy** [comment]
有些参数    官网输入的时候会有建议   但是访问这个接口的时候  确没有数据------------------ 原始邮件 ------------------
发件人: "binaryify"<notifications@github.com>
发送时间: 2020年3月2日(星期一) 上午10:21
收件人: "Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com>;
抄送: "lipuisaboy"<1213262105@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Binaryify/NeteaseCloudMusicApi] 歌曲url (#701)


 
结果和想象的数据不一样
 指的是什么
  
&mdash;

**Comment by Binaryify** [comment]
你是说 `/search/hot` ?

**Comment by lipuisaboy** [comment]
search/suggest

**Comment by nondanee** [comment]
![image](https://user-images.githubusercontent.com/26399680/75673458-f0fe6680-5cbd-11ea-98c2-a1861434d2ea.png)

![image](https://user-images.githubusercontent.com/26399680/75673518-19866080-5cbe-11ea-846b-039f30dc09fc.png)

"海阔天空" 数据一致

有些参数没有数据是指哪些参数？
官网有没有登录？API 有没有登录？测试条件是否一致？

**Comment by lipuisaboy** [comment]
当参数加上type＝mobile的时候 &nbsp;返回的数据和不加type参数一样 &nbsp;麻烦您看一下是不是 &nbsp;&nbsp;

**Comment by nondanee** [comment]
我试了不一样的
你是不是 post body 带的参数？
估计被缓存了，url 里加个时戳 #696

**Comment by lipuisaboy** [comment]
好的 我试一下 麻烦您了
