### ISSUE TITLE
小程序问签到出现301

### ISSUE THREAD

**Issue by mhxy13867806343** [Binaryify/NeteaseCloudMusicApi#703]
## 环境
- 系统/平台: <你的系统和平台>
 win10  
- nodejs 版本: <你的 NodeJS 版本号>
12.13.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
运行daily_signin接口之后就是报301，而浏览器里面是正常显示的
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by mhxy13867806343** [comment]
[
![1233444](https://user-images.githubusercontent.com/4418166/75854025-32ac2000-5e2a-11ea-8439-5321e8761a62.png)
](url)

**Comment by nondanee** [comment]
底下那个截图是小程序开发工具吧？https://github.com/Binaryify/NeteaseCloudMusicApi/issues/643#issuecomment-554610536

**Comment by mhxy13867806343** [comment]
@nondanee 解决了

**Comment by langyixuan** [comment]
请问一下你是怎么解决的呢，我也遇到了相同的问题。在写音乐小程序的时候用网易的api请求喜欢的音乐列表就会报这个错。浏览器里访问接口又是正常的。
