### ISSUE TITLE
私信功能失效

### ISSUE THREAD

**Issue by dengxiny** [Binaryify/NeteaseCloudMusicApi#704]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
发送私信失败

## 重现步骤
<重现步骤>

## 期待效果
给出正确加密串的格式或者告知加密方式有区别

**Comment by Binaryify** [comment]
参数发出来,我这边是可以的

**Comment by dengxiny** [comment]
请求 url : https://music.163.com/weapi/msg/private/send?csrf_token=4349b3868b58ef7eea4deadd5ff07644
------------------
加密前json串
"{"type":"text","msg":"1","userIds":"[\"5525532**\"]","checkToken":"9ca17ae2e6ffcda170e2e6eeaaf764f8b78caed16094bc8bb2d45e838e8aaaf45ba38fac88b54eaeecc0b1e42af0feaec3b92ab6bf9da8f974f2b084bae25a838e8ea6c14fa1af8bb1c845a1a89eacb33a8795ee9e","time":"-1","csrf_token":"b6a64f7b52d485a777e5590a9c87bb**"}"
------------------
结果是成功的
------------------
而你代码里
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/send_text.js
参数少了checkToken 所以都是返回参数异常，目前还不知道checkToken 生成规则

**Comment by Binaryify** [comment]
你是调官方接口?

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/77025003-f3a1d100-69ca-11ea-9d4a-cc07ac836187.png)
![image](https://user-images.githubusercontent.com/12221718/77025012-f997b200-69ca-11ea-94ce-a91d17aac132.png)

**Comment by dengxiny** [comment]
> 
> 
> 你是调官方接口?

恩 我直接改着你接口去测官方接口不通过。你能提供一下你传官网接口的参数吗

**Comment by Binaryify** [comment]
util 下面的文件有加密方式

**Comment by dengxiny** [comment]
> 
> 
> util 下面的文件有加密方式

不是这个问题，我看了我网页端分析的请求UA如果是较新的标识，不是你这种老的app的请求，参数校验不过的，你这个我改成老的UA就成功了
