### ISSUE TITLE
/user/subcount 接口报301

### ISSUE THREAD

**Issue by lovesL** [Binaryify/NeteaseCloudMusicApi#707]
## 环境
- 系统/平台: <你的系统和平台>
macOS/electron
- nodejs 版本: <你的 NodeJS 版本号>
11.10.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.3
## 出现问题
<出现的问题>
调用/user/subcount 接口报301 我尝试着重启服务器和加时间戳还是报301,我看登陆接口会返回一个token，这个token不知道有没有用
## 重现步骤
`get(`/user/subcount`).then((res)=>{
            console.log(res)
        })

respones:{
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With,Content-Type
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Access-Control-Allow-Origin: http://localhost:3000
cache-control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Length: 33
Content-Type: application/json; charset=utf-8
Date: Fri, 06 Mar 2020 13:47:31 GMT
ETag: W/"21-FccKlSeNOQr0LUGoio0DvtY+OHE"
X-Powered-By: Express
}

Request URL: http://localhost:8080/user/subcount
Request Method: GET
Status Code: 301 Moved Permanently
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
`
<重现步骤>
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
那个 token 用途未知

要带 cookie 请求
跨域带 cookie 需要 withCredentials
