### ISSUE TITLE
关于歌单列表中视频id不全的问题

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#708]
## 环境
- 系统/平台: <你的系统和平台>
win10 
- nodejs 版本: <你的 NodeJS 版本号>
v10.16.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
"version": "3.25.3",
## 出现问题
<出现的问题>
[歌单列表中视频id不全的问题](url)
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

[](url)

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发
![QQ图片20200307111450](https://user-images.githubusercontent.com/38646454/76135789-53ac8500-6065-11ea-809b-8ceea25953d8.jpg)

**Comment by nondanee** [comment]
看了

你用的是 `mv` 这个字段来显示标记的吧？
云音乐的视频 (video) 和 MV (mv) 是分开的 (接口也不同)

我试了下客户端点那个图标进去是精彩视频的页面 (集成了 video 和 mv)
和你展示的意义不一样 (你只展示了有 mv，有视频不代表就有 mv)

至于“有精彩视频”的字段是啥，现在这个接口里有没有这个字段 (`playlist/detail` 接口有 v1 v2 v3 v4 等等版本)，都不知道

**Comment by refuse-c** [comment]
好的 谢谢啦
