### ISSUE TITLE
搜索接口不能用了~

### ISSUE THREAD

**Issue by felixfujing** [Binaryify/NeteaseCloudMusicApi#709]
## 环境
- 系统/平台: Win10

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
/search接口失效

## 重现步骤
直接请求：https://musicapi.leanapp.cn/search?keywords=%E6%9D%8E%E5%81%A5
会报以下错误：
{
msg: "Cheating",
code: -460,
message: "Cheating"
}

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
不负责处理别人搭建的服务的问题
