### ISSUE TITLE
请问私人FM接口的逻辑

### ISSUE THREAD

**Issue by 97Yates05** [Binaryify/NeteaseCloudMusicApi#710]
不允许禁用缓存，每次请求基本（只有长时间重新刷新页面会变）都是相同的三首歌，做不到加新歌，（因为有时候是会快速跳过这三首歌的。。）这样这个接口基本就废了。。请问有什么解决办法吗

**Comment by Binaryify** [comment]
为啥都不好好看文档呢

**Comment by 97Yates05** [comment]
看到了。。在一开始，抱歉
