### ISSUE TITLE
与unblockneteasemusic 不能共存？

### ISSUE THREAD

**Issue by keivenliao** [Binaryify/NeteaseCloudMusicApi#711]
## 环境
- 系统/平台: <你的系统和平台>
debian

- nodejs 版本: <你的 NodeJS 版本号>
10.15.2

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
{
  "code": 502,
  "msg": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)\n    at TLSSocket.emit (events.js:189:13)\n    at TLSSocket._finishInit (_tls_wrap.js:633:8)"
}

## 重现步骤
<重现步骤>
因为我在路由上开启了unblockneteasemusic，关闭即可

## 期待效果
<现在的效果，期待的效果>  
期待在路由上开启 unblockneteasemusic也能请求
在其项目中有一句：在请求中加入： --ignore-certificate-errors 不知在API项目中如何添加此参数。 

最后附上该项目地址
https://github.com/project-openwrt/luci-app-unblockneteasemusic

--ignore-certificate-errors

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by nondanee** [comment]
```js
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0
```

**Comment by keivenliao** [comment]
> ```js
> process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0
> ```

z这个是改那个文件？

**Comment by nondanee** [comment]
别改 test/ 里的，改哪个都行
