### ISSUE TITLE
vip歌曲无法获取链接，用官方api也不行

### ISSUE THREAD

**Issue by lqszsd** [Binaryify/NeteaseCloudMusicApi#712]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
你的账号是会员吗

**Comment by refuse-c** [comment]
同问  我也是这个问题    ,账号是会员   并且已经登录了

**Comment by Binaryify** [comment]
@refuse-c 给请求地址和参数

**Comment by refuse-c** [comment]
大佬 你好:

我刚刚在issues也看了,你们说的,就是在请求的header中添加cookie 就可以获取到vip音乐的地址(是会员账号)  这个我还没去试,另外还有个问题就是检索的音乐怎么判断有木有版权  我看看了一下好像没有st字段

[cid:image003.png@01D62619.B19CA7C0]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年5月9日 15:07
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>;
主题: Re: [Binaryify/NeteaseCloudMusicApi] vip歌曲无法获取链接，用官方api也不行 (#712)


@refuse-c<https://github.com/refuse-c> 给请求地址和参数

―
