### ISSUE TITLE
收藏/取消收藏歌单 参数设置错误但是返回值不会报错

### ISSUE THREAD

**Issue by zion223** [Binaryify/NeteaseCloudMusicApi#715]
## 环境
- 系统/平台: win10 安卓

- nodejs 版本: 12.16.1

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
收藏/取消收藏歌单 参数设置错误但是返回值不会报错

## 重现步骤
<重现步骤>

## 期待效果
收藏/取消收藏歌单 参数设置错误时返回收藏或取消失败错误码

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
参数发出来

**Comment by zion223** [comment]
192.168.1.54:3000/playlist/subscribe?t=3&id=106697785 请求这个返回值还是code:200
但是t=3没有这个参数
t : 类型,1:收藏,2:取消收藏 id : 歌单 id

**Comment by Binaryify** [comment]
我的源码里1为收藏,其他为取消收藏
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/playlist_subscribe.js

**Comment by zion223** [comment]
明白了

**Comment by longhaolh** [comment]
> 

为啥我的请求参数是正确的但是返回401
