### ISSUE TITLE
能否实现上传音乐到音乐云盘的功能呢？

### ISSUE THREAD

**Issue by album-GitHub** [Binaryify/NeteaseCloudMusicApi#716]
## 环境
- 系统/平台: <Windows>

- nodejs 版本: <v12.16.1>

- API版本:<3.25.4>

## 出现问题
<无>

## 重现步骤
<无>

## 期待效果
<现在关于音乐云盘的功能只有获取信息删除歌曲，能否实现上传音乐呢？我看github上有关网易云的项目基本很少提及有关上传音乐到云盘这个功能的，找到的一个实现上传功能的项目发现调用的接口好像是失效了 [项目地址](https://github.com/picone/CloudMusicUploader.git)

>先看文档有没有相关说明

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数和操作过程描述

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by album-GitHub** [comment]
看到有人提过了，太麻烦就没办法了

**Comment by Binaryify** [comment]
已支持~
