### ISSUE TITLE
获取用户动态中 无法获取动态的类型

### ISSUE THREAD

**Issue by zion223** [Binaryify/NeteaseCloudMusicApi#717]
## 环境
- 系统/平台: win10 安卓

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
   获取用户动态中 如何根据type 获取动态的类型，比如是分享评论、分享歌单、分享单曲这些不同的分享类型，我看数据中有个type数值，但是没有对应的类型说明，不知道您有没有整理过这个，如果您那没有的话，我可以研究下这个type代表的类型给您分享下。

## 重现步骤
<重现步骤>

## 期待效果
期待的效果 （eg. type=18 分享歌单  type=19 分享视频）

**Comment by Binaryify** [comment]
这个没有整理,你要是有时间的话可以整理下,然后我更新到文档里

**Comment by zion223** [comment]
有时间我整理下，在这里回复你

**Comment by Binaryify** [comment]
嗯嗯~

**Comment by zion223** [comment]
18 分享单曲
19 分享专辑
17、28 分享电台节目
22 转发
39 发布视频
35、13 分享歌单
24 分享专栏文章
41、21 分享视频

暂时整理这么多 亲测好用

**Comment by Binaryify** [comment]
嗯嗯,明天我更新下文档

**Comment by Binaryify** [comment]
已更新~
