### ISSUE TITLE
这种没有版权就置灰的，是根据什么来判断没有版权的？

### ISSUE THREAD

**Issue by dayfan0810** [Binaryify/NeteaseCloudMusicApi#718]
## 环境
-系统/平台:

-nodejs 版本: <v12.16.1>
![有无版权](https://user-images.githubusercontent.com/8685291/77077380-1dd9aa00-6a30-11ea-9b9c-c18dd59a82a4.jpg)

-API版本:<3.25.4>

## 出现问题
<出现的问题>No

## 重现步骤
<重现步骤>No

## 期待效果
<现在的效果，期待的效果>  
这种没有版权就置灰的，是根据什么来判断没有版权的？

我通过把没有版权的歌曲上传到云盘前后对比，发现搜到的json结果没有差别啊，没搞懂是APP是通过哪个字段来判断是否有版权的

**Comment by Binaryify** [comment]
判断 st 字段，0就不可播放，或者直接请求 /song/url 接口
云盘不管有没有版权都能播放

**Comment by kevinzhao2233** [comment]
> 判断 st 字段，0就不可播放，或者直接请求 /song/url 接口
> 云盘不管有没有版权都能播放

尝试了，并不是这样的，搜索结果里没有 st 字段，歌单列表里有 st 字段，但是无论歌曲能不能播放，值都是 0，版本是最新版

**Comment by kevinzhao2233** [comment]
> ## 环境
> -系统/平台:
> 
> -nodejs 版本: <v12.16.1>
> ![有无版权](https://user-images.githubusercontent.com/8685291/77077380-1dd9aa00-6a30-11ea-9b9c-c18dd59a82a4.jpg)
> 
> -API版本:<3.25.4>
> 
> ## 出现问题
> <出现的问题>No
> 
> ## 重现步骤
> <重现步骤>No
> 
> ## 期待效果
> <现在的效果，期待的效果>
> 这种没有版权就置灰的，是根据什么来判断没有版权的？
> 
> 我通过把没有版权的歌曲上传到云盘前后对比，发现搜到的json结果没有差别啊，没搞懂是APP是通过哪个字段来判断是否有版权的

你现在知道了吗，我试了并不是 st 字段

**Comment by dayfan0810** [comment]
> > ## 环境
> > -系统/平台:
> > -nodejs 版本: <v12.16.1>
> > ![有无版权](https://user-images.githubusercontent.com/8685291/77077380-1dd9aa00-6a30-11ea-9b9c-c18dd59a82a4.jpg)
> > -API版本:<3.25.4>
> > ## 出现问题
> > <出现的问题>No
> > ## 重现步骤
> > <重现步骤>No
> > ## 期待效果
> > <现在的效果，期待的效果>
> > 这种没有版权就置灰的，是根据什么来判断没有版权的？
> > 我通过把没有版权的歌曲上传到云盘前后对比，发现搜到的json结果没有差别啊，没搞懂是APP是通过哪个字段来判断是否有版权的
> 
> 你现在知道了吗，我试了并不是 st 字段

等等,我还没时间弄,这两天看一下.

**Comment by kevinzhao2233** [comment]
> > > ## 环境
> > > -系统/平台:
> > > -nodejs 版本: <v12.16.1>
> > > -API版本:<3.25.4>
> > > ## 出现问题
> > > <出现的问题>No
> > > ## 重现步骤
> > > <重现步骤>No
> > > ## 期待效果
> > > <现在的效果，期待的效果>
> > > 这种没有版权就置灰的，是根据什么来判断没有版权的？
> > > 我通过把没有版权的歌曲上传到云盘前后对比，发现搜到的json结果没有差别啊，没搞懂是APP是通过哪个字段来判断是否有版权的
> > 
> > 
> > 你现在知道了吗，我试了并不是 st 字段
> 
> 等等,我还没时间弄,这两天看一下.

不用了，谢谢哈，确实是 st 字段，但是并不是歌曲的对象里面，而是在"privileges"对象里的 st 字段，我一直忽略了这个，目前看，如果 st < 0，就表示不能播，= 0，也是可以播的
