### ISSUE TITLE
请问有支持openwrt docker  64位的api么？

### ISSUE THREAD

**Issue by shadowby** [Binaryify/NeteaseCloudMusicApi#719]
## 环境
- 系统/平台: <你的系统和平台>
openwrt docker，斐讯N1
- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
docker报错
stderr: standard_init_linux.go:211: exec user process caused "exec format error"

## 期待效果
<现在的效果，期待的效果>  
初步理解应该是版本不支持本处理器。

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/529
参考这个

**Comment by shadowby** [comment]
谢谢，#529我看了，改dockerfile对初级用户难度太大，仍然谢谢大佬！！

**Comment by shadowby** [comment]
请问是否考虑出aarch64版的网易云api

**Comment by Binaryify** [comment]
@shadowby 我这个就js,跟系统无关的,运行时环境是 Node.js

**Comment by Binaryify** [comment]
你就把源码的dockerfile改改就行了1
