### ISSUE TITLE
动态点在不生效

### ISSUE THREAD

**Issue by YJKZHUZHU** [Binaryify/NeteaseCloudMusicApi#721]
## 环境
- 系统/平台: windows10

- nodejs 版本: v12.3.1

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
个人的动态点在不生效，接口返回200，cid 是是指哪个在这个接口user/event的返回数据里面

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
动态点在?
