### ISSUE TITLE
访问任意接口报错

### ISSUE THREAD

**Issue by SearchForPluto** [Binaryify/NeteaseCloudMusicApi#723]
## 环境
- 系统/平台: <你的系统和平台>
Windows10
- nodejs 版本: <你的 NodeJS 版本号>
v12.16.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.4
## 出现问题
安装好项目并启动 访问http://localhost:3000/提示成功 但访问其他端口都报错误
{"code":502,"msg":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)"}
## 重现步骤
安装 并启动 提示启动成功 页面提示“当你看到这个页面时,这个服务已经成功跑起来了”，点击下方的搜索、歌曲评论或电台节目都报错误：
{"code":502,"msg":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)"}
1.在家中测试可以获得返回数据
2.到公司环境测试则报错
## 期待效果
能正常访问

**Comment by nondanee** [comment]
```sh
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by danacm** [comment]
应该是公司的网络访问有限制，我用公司的网络也是会出现这个，但是用了公共网络没有问题

**Comment by SearchForPluto** [comment]
> 应该是公司的网络访问有限制，我用公司的网络也是会出现这个，但是用了公共网络没有问题

但是我在公司访问公共的接口可以访问

**Comment by nondanee** [comment]
@SearchForPluto 
没仔细看，你这个确实不是证书错误

那你让程序走访问公共的接口就好了
支持设置代理的，文档里有写
