### ISSUE TITLE
docker创建的时候端口不可以自定义吗？

### ISSUE THREAD

**Issue by cuijianzhe** [Binaryify/NeteaseCloudMusicApi#726]
## 环境
- 系统/平台: centos7.5 

- nodejs 版本: docker搭建

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
docker搭建可否自定义端口

## 重现步骤
<重现步骤>

## 期待效果
端口可以自定义

**Comment by nondanee** [comment]
自己映射端口不可以吗？`docker run -p <ANY PORT>:3000 ...`

**Comment by cuijianzhe** [comment]
感谢，可以了



598941324@qq.com
 
发件人： Nzix
发送时间： 2020-03-27 19:02
收件人： Binaryify/NeteaseCloudMusicApi
抄送： cuijianzhe; Author
主题： Re: [Binaryify/NeteaseCloudMusicApi] docker创建的时候端口不可以自定义吗？ (#726)
自己映射端口不可以吗？docker run -p <ANY PORT>:3000 ...
