### ISSUE TITLE
弱弱的问一句，它支持第三方登录吗？

### ISSUE THREAD

**Issue by little-buddy** [Binaryify/NeteaseCloudMusicApi#729]
这不是一个询问帖而是一个讨论帖，所以就没有走格式了。😂
登陆 我希望用微信、微博这类三方形式，但没有看到接口，是不是不支持呀？
感觉连验证码都能支持，这个三方登陆的卡点在哪里呀？

**Comment by Binaryify** [comment]
不支持的，也不打算支持，涉及到第三方的只能开webview，然后抓 cookies，这样就引入了 electron，会给项目安装依赖带来负担
