### ISSUE TITLE
获取到的歌曲有时候是12800的低质量版，如何获得高质量版的呢？

### ISSUE THREAD

**Issue by zhangruize** [Binaryify/NeteaseCloudMusicApi#73]
比如搜索see you again时，最终获取的是低质量版的mp3音乐。有没有可能去获取到高质量版呢？

无比感谢！

**Comment by Binaryify** [comment]
你看下客户端,这首歌192k 以上的都是会员才有的

**Comment by zhangruize** [comment]
谢谢回答！确实没有登录，之后登录了试试！可以关闭了
