### ISSUE TITLE
{"msg":"Cheating","code":-460,"message":"Cheating"}

### ISSUE THREAD

**Issue by Yemaoxin** [Binaryify/NeteaseCloudMusicApi#731]
## 环境
- 系统/平台: MAC系统，国内本地，官方Web页面 http://musicapi.leanapp.cn/ 

- API版本:项目文档的web页面首页  http://musicapi.leanapp.cn/

## 出现问题
点击搜索时，出现code：-460
API似乎已经被网易鉴别，无法返回歌曲ID
## 重现步骤
打开http://musicapi.leanapp.cn/
点击搜索

## 期待效果
恢复正常搜索使用

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Binaryify** [comment]
哪个接口,重现步骤,参数,服务器环境是什么,国内还是国外
不要无视issues模板,,啥都不发我只能跟你说我这里可以

**Comment by Yemaoxin** [comment]
> 哪个接口,重现步骤,参数,服务器环境是什么,国内还是国外
> 不要无视issues模板,,啥都不发我只能跟你说我这里可以

国内本机
重现步骤
方式1: 通过http://musicapi.leanapp.cn/处的搜索点击时，出现上述错误
方式2:通过url拼接调用时，同样产生上述错误

**Comment by Yemaoxin** [comment]
> 哪个接口,重现步骤,参数,服务器环境是什么,国内还是国外
> 不要无视issues模板,,啥都不发我只能跟你说我这里可以

已修改issue，抱歉

**Comment by Binaryify** [comment]
http://musicapi.leanapp.cn/ 是你自己搭的还是别人搭的

**Comment by Yemaoxin** [comment]
> http://musicapi.leanapp.cn/ 是你自己搭的还是别人搭的

别人搭的，事实上我自己通过api调用也出现这个问题，昨天一切正常
然后今天早上出现该问题。
使用该网站只是为了快速说明

**Comment by Binaryify** [comment]
ok,我看看

**Comment by Binaryify** [comment]
utils/request.js 里面的 headers['X-Real-IP'] 的注释取消掉就好

**Comment by Binaryify** [comment]
http://kbquzyjhejal.leanapp.cn/search?keywords=%E6%B5%B7%E9%98%94%E5%A4%A9%E7%A9%BA

**Comment by Yemaoxin** [comment]
ok，感谢
