### ISSUE TITLE
歌手分类接口请求结果出现异常

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [Binaryify/NeteaseCloudMusicApi#733]
## 环境
- 系统/平台: <windows、chrome>

- nodejs 版本: <v10.15.0>

- API版本:<3.25.4>

## 出现问题
访问***歌手分类列表***接口的时候，返回的结果与预期的结果不一致

## 重现步骤
将NeteaseCloudMusicApi下载到本地，然后安装项目依赖，输入node app.js运行
在谷歌浏览器中调用'http://192.168.0.107:3000/artist/list?cat=1003&initial=c'接口
{
文档中说明如下
1002：华语女歌手
initial=c 返回内容将以 name 字段开头为 c 或者拼音开头为 c 为顺序排列
}
接口返回的结果如下：
![image](https://user-images.githubusercontent.com/39010432/78683079-685c9100-7921-11ea-91e1-0ee01b02aca5.png)
可以很明显的看到，返回的结果中包含有男歌手。

### ***且经过多次测试，输入所有的歌手类型参数，接口返回的数据全部都是一样的值***
效果如下所示（展示了部分测试结果）:

***4002：其他女歌手***
![image](https://user-images.githubusercontent.com/39010432/78684063-a1493580-7922-11ea-8f26-4f83891cc9a9.png)

### ***请求地址中，如果不加上initial参数，返回的值全部都是热门歌手***
效果如下所示（不知道为什么其他截图上传不了。。。）:
***'/top/artists'热门歌手的接口***
![@NC2UEE 3%}M__})QXQ@47Y](https://user-images.githubusercontent.com/39010432/78687205-837dcf80-7926-11ea-9e95-4623f9211ea3.png)

## 期待效果
接口返回的数据是：与歌手分类类型参数对应

**Comment by Binaryify** [comment]
网易那边改参数了，地区和男女分离了，明天更新下

**Comment by Binaryify** [comment]
已更新~

**Comment by zhuxiaoluxiaonuan** [comment]
非常感谢团队大大们及时更新API，目前已更新至最新版本，请求数据无异常
