### ISSUE TITLE
歌曲url 在使用post时出错

### ISSUE THREAD

**Issue by waxly** [Binaryify/NeteaseCloudMusicApi#735]
## 环境
- 系统/平台: <你的系统和平台>
深度系统（linux）
- nodejs 版本: <你的 NodeJS 版本号>
12.16.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.4
## 出现问题
<出现的问题>
在获取歌曲url时，使用post方法，即使参数 “id”改了另一首歌的，但是有时候还是会返回之前那首歌的url，返回的信息都是上一首歌的信息，但是我post的数据是下一首歌的数据，当我改为get方法时，这个问题就不见了。
## 重现步骤
<重现步骤>
在获取歌曲url的时候，使用requests.post，（我用的是python语言），如果相隔时间较长就没问题，但是如果几秒钟调用一次就会出问题，返回的一直都是某一首歌的url，重新运行代码也没有用。。
## 期待效果
<现在的效果，期待的效果>  
现在只能用get，希望post也没问题。不过我也只是提出这个bug，免得别人不知道，像我这样调试了一晚上。

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
你把文档调用前须知第三条看一遍就不用这么折腾了

**Comment by waxly** [comment]
哦哦哦，突然懂了，谢谢
