### ISSUE TITLE
歌手分类接口，分类中的#号initial应该传什么啊，传了initial=#但是拿到的数据不一致

### ISSUE THREAD

**Issue by NoahJJ** [Binaryify/NeteaseCloudMusicApi#736]
## 环境
- 系统/平台: <macOS 10.14.6>

- nodejs 版本: <13.1.0>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
歌手分类接口，分类中的#号initial应该传什么啊，传了initial=#但是拿到的数据不一致

## 重现步骤
http://127.0.0.1:3000/artist/list?type=-1&area=7&initial=#&limit=100&offset=0

## 期待效果
和客户端搜索结果一样

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by NoahJJ** [comment]
抓到了 应该initial传0

**Comment by Binaryify** [comment]
我更新下文档
