### ISSUE TITLE
收藏/取消收藏更新慢

### ISSUE THREAD

**Issue by DJAlejandro** [Binaryify/NeteaseCloudMusicApi#737]
在使用类似（/artist/sublist）的收藏/取消收藏接口时，发现收藏/取消收藏代码执行后，从手机端看，执行生效了。但是在返回的数据中artist的followed字段没有更新，基本要等到1分钟以上，才会更新执行结果。而album的liked字段没有更新。这个是转发接口的普遍现象吗？收藏/取消收藏针对专辑、歌单、单曲、MV改变的字段是哪些呢？

![小Q截图-20200415135018](https://user-images.githubusercontent.com/14656317/79302957-431ee280-7f20-11ea-9a30-2835afe50cab.png)
![小Q截图-20200415135110](https://user-images.githubusercontent.com/14656317/79302961-45813c80-7f20-11ea-8044-52460c4b229c.png)

**Comment by Binaryify** [comment]
文档的调用前须知先看看

**Comment by DJAlejandro** [comment]
timestamp: new Date().getTime()

**Comment by Binaryify** [comment]
反正url不一样就行，随机数或者时间戳都可以

**Comment by DJAlejandro** [comment]
> 反正url不一样就行，随机数或者时间戳都可以

收藏/取消收藏专辑后更改的字段是哪个，没有变化啊。。。

**Comment by Binaryify** [comment]
专辑动态信息
说明 : 调用此接口 , 传入专辑 id, 可获得专辑动态信息,如是否收藏,收藏数,评论数,分享数

必选参数 : id: 专辑 id

接口地址 : /album/detail/dynamic

调用例子 : /album/detail/dynamic?id=32311
