### ISSUE TITLE
如何让网易云知道我听过什么歌

### ISSUE THREAD

**Issue by kevinzhao2233** [Binaryify/NeteaseCloudMusicApi#741]
**由于不是反馈错误等，我就不填环境模块了哈**
## 环境

- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
想要听过的歌在网易云有记录，这样可以促进推荐歌单和推荐歌曲的准确性，所以我怎么做才能让网易云知道我听了什么歌？

能给我一个思路就可以，我对这个实在不懂，看了网易云官方的，cookie 好像并没有携带

**Comment by nondanee** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=听歌打卡

**Comment by kevinzhao2233** [comment]
对不起，赶紧关了这个 issue 吧，太惭愧了
