### ISSUE TITLE
Java获取单个歌曲详情

### ISSUE THREAD

**Issue by LukeLiang** [Binaryify/NeteaseCloudMusicApi#742]
你好,我是一个后端的初学者，看了一下文档，我发现看不懂。所以我直接询问一下，望解答
问题：
         我想获取单个歌曲的 歌曲详情 ，我看到了接口是/song/detail?ids=xxxxx
请问：
         接口api的前缀是什么？

**Comment by nondanee** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi#运行

**Comment by LukeLiang** [comment]
> [https://github.com/Binaryify/NeteaseCloudMusicApi#运行](https://github.com/Binaryify/NeteaseCloudMusicApi#%E8%BF%90%E8%A1%8C)
谢谢！我还有一个问题
跨域设置的时候，是在请求的header中设置下面这段内容吗?
xhrFields: { withCredentials: true }

**Comment by nondanee** [comment]
java (后端)不存在跨域问题啊
前端的话查一下你用的请求库的文档吧

**Comment by LukeLiang** [comment]
> java (后端)不存在跨域问题啊
> 前端的话查一下你用的请求库的文档吧

就是说请求接口就可以返回数据了对吧？
谢谢你的回答☺☺
