### ISSUE TITLE
localhost:3000接口訪問錯誤問題

### ISSUE THREAD

**Issue by chr1995** [Binaryify/NeteaseCloudMusicApi#743]
系统/平台: <你的系统和平台>
Windows10
nodejs 版本: <你的 NodeJS 版本号>
v10.15.3
API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.25.4
出现问题
安装好项目并启动 访问http://localhost:3000/提示成功 但访问其他端口都报错误
{"code":502,"msg":"Error: connect ETIMEDOUT 103.126.92.133:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)"}

重现步骤
安装 并启动 提示启动成功 页面提示“当你看到这个页面时,这个服务已经成功跑起来了”，点击下方的搜索、歌曲评论或电台节目都报错误：
{"code":502,"msg":"Error: connect ETIMEDOUT 103.126.92.133:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)"}

在公司环境测试则报错

期待效果
能正常访问

我看有朋友跟我遇到相似問題，只不過他是read 而我是connect

**Comment by Binaryify** [comment]
```
set NODE_TLS_REJECT_UNAUTHORIZED=0 && node app.js
```
这个有试过吗

**Comment by chr1995** [comment]
> ```
> set NODE_TLS_REJECT_UNAUTHORIZED=0 && node app.js
> ```
> 
> 
> 这个有试过吗

大佬，这个是在哪里更改？  我不太确定是不是公司用了代理的问题，我准备回家试试家里的电脑

**Comment by chr1995** [comment]
> ```
> set NODE_TLS_REJECT_UNAUTHORIZED=0 && node app.js
> ```
> 
> 这个有试过吗
我試了這個set配置 環境變量,還是報502

haishi

**Comment by Binaryify** [comment]
你们公司是不是屏蔽了网易云音乐

**Comment by chr1995** [comment]
> 你们公司是不是屏蔽了网易云音乐
我直接开网易云的api，例如music.163/api/xx是可以拿到数据的，但是通过localhost:3000跳转musci.163的api,就不行了

**Comment by Binaryify** [comment]
那你全局把 https://music.163.com 替换成 http://music.163.com 试试

**Comment by chr1995** [comment]
> 那你全局把 https://music.163.com 替换成 http://music.163.com 试试

我把NeteaseCloudMusicApi-master/module/setting.js裏的，
'POST', `https://music.163.com/api/user/setting`改成http也還是不行，心態也點小崩

**Comment by Binaryify** [comment]
@nondanee 知道是什么原因吗

**Comment by chr1995** [comment]
> 那你全局把 https://music.163.com 替换成 http://music.163.com 试试

OK，我找到原因了，我代理配错了，公司是xxx：8080代理，但是让我们安装npm 代理时，config是http://username：password@xxx：8080，所以应该附加上自己账号的代理，而不是单独的xxx：8080，因为公司是海外服务器，所以比较烦一点，希望可以给各位小伙伴打个样

**Comment by chr1995** [comment]
> 那你全局把 https://music.163.com 替换成 http://music.163.com 试试
