### ISSUE TITLE
歌单（网友精选碟）offset 参数不能使用了吗

### ISSUE THREAD

**Issue by kevinzhao2233** [Binaryify/NeteaseCloudMusicApi#744]
## 环境
- 系统/平台: <你的系统和平台>
Windows，chrome83
- nodejs 版本: <你的 NodeJS 版本号>
10.X
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.27
## 出现问题
<出现的问题>
[歌单（网友精选碟）](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e6%ad%8c%e5%8d%95-%e7%bd%91%e5%8f%8b%e7%b2%be%e9%80%89%e7%a2%9f-)offset 参数无效，不管是多少，返回的数据都是为 0 的结果，
## 重现步骤
<重现步骤>
/top/playlist/?offset=1，这里offset设置失效，但是源码中有体现出来，希望可以测试一下，是否是我的问题
```javascript
// 分类歌单

module.exports = (query, request) => {
  const data = {
    cat: query.cat || '全部', // 全部,华语,……
    order: query.order || 'hot', // hot,new
    limit: query.limit || 50,
    offset: query.offset || 0,
    total: true
  }
  return request(
    'POST', `https://music.163.com/weapi/playlist/list`, data,
    {crypto: 'weapi', cookie: query.cookie, proxy: query.proxy}
  )
}
```
## 期待效果
<现在的效果，期待的效果>  
希望可以实现 offset，感觉还是蛮重要的

**Comment by Binaryify** [comment]
?offset=1

**Comment by kevinzhao2233** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/744#issuecomment-619470808
不好意思，那个 & 写错了，之前是还有别的参数，删的时候删错了，刚刚又试了，还是有问题。
比如
`/top/playlist/?offset=0&limit=2` 的结果与 `/top/playlist/?offset=1&limit=2` ,两个返回的是以 offset 为下标开始的 2 个歌单，也就是最后返回的数量是类似 `offset + limit`，也不是 `offset * limit` 的结果
不知道我说的清不清楚，比如歌单顺序是 `[A, B, C, D]`，返回的结果是 `[A, B]` 和 `[B, C]`

**Comment by Binaryify** [comment]
我看看

**Comment by Binaryify** [comment]
offset 就是这样的，不是页数

**Comment by kevinzhao2233** [comment]
好的，明白了，谢谢你~~

**Comment by Binaryify** [comment]
文档刚更新了，之前忘记写了

**Comment by kevinzhao2233** [comment]
哇，，，好快
