### ISSUE TITLE
排行榜数据缺失

### ISSUE THREAD

**Issue by lchkid** [Binaryify/NeteaseCloudMusicApi#746]
## 环境
- 系统/平台: window 10 / chrome 80

- nodejs 版本: v12.16.1

- API版本: v3.27.0

## 出现问题
`/toplist/detail` 接口返回的排行榜数据
其中 **云音乐说唱榜** 以及之后的榜单没有前三首歌曲数据

## 重现步骤
`/toplist/detail` 

![toplist.png](https://i.loli.net/2020/04/29/4sauHQhM1FxbNIf.png)

**Comment by Binaryify** [comment]
榜单也是歌单,调`/playlist/detail?id=xx` 就行
http://localhost:3000/playlist/detail?id=3112516681
![image](https://user-images.githubusercontent.com/12221718/80807799-ad0ddc00-8bf0-11ea-8fc9-7942c9cad1f2.png)
![image](https://user-images.githubusercontent.com/12221718/80807811-b303bd00-8bf0-11ea-9161-2fa2c745f9f5.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/80807829-c020ac00-8bf0-11ea-9a3b-a3c5cc0bd956.png)
