### ISSUE TITLE
正常登陆的情况下，调用喜欢音乐接口失败

### ISSUE THREAD

**Issue by zentanso** [Binaryify/NeteaseCloudMusicApi#75]
### 环境
系统:  

nodejs 版本:
v8.1.2
### 出现问题
在已经登陆并且私人FM和每日推荐等接口能正常调用的情况下，调用喜欢音乐接口失败
### 重现步骤
axios进行get请求'/like?id=3704901'

返回
```
{code: 400, message="Required long parameter 'trackId' is not present"}
```

### 期待效果
{code: 200}

**Comment by Binaryify** [comment]
正在修复

**Comment by Binaryify** [comment]
已修复

**Comment by zentanso** [comment]
感谢修复。

另外请问返回的歌曲数据里面是否带有表示“喜欢”的数据项？好像找不到……
![default](https://user-images.githubusercontent.com/26247160/28246523-790f1016-6a4e-11e7-8583-1ba49f864aca.PNG)

**Comment by Binaryify** [comment]
没有的

**Comment by zentanso** [comment]
好吧……

另外发现垃圾桶功能跟红心功能出现的问题类似，修复方法也一样，望更新

**Comment by Binaryify** [comment]
@zentanso 
好了,感谢反馈
