### ISSUE TITLE
以特殊字符创建歌单似乎会出现问题

### ISSUE THREAD

**Issue by sxyugao** [Binaryify/NeteaseCloudMusicApi#750]
RT，比如接口传入 `٩（ •̀㉨•́ ）و` 就会出锅

被解析成了 `&#1641;（&#160;&#8226;&#768;&#12904;&#8226;&#769;&#160;）&#1608; `

然后调用接口变成了 `[ERR] /playlist/create?name=&`

就创建失败了

**Comment by Binaryify** [comment]
转义是浏览器转的,你直接post请求吧,url带个时间戳或者随机数防止缓存就行

**Comment by sxyugao** [comment]
@Binaryify 我是本地用 nodejs 发送请求出现的问题，在浏览器中直接调用反而没这个问题

```
const createPlaylist = (name) => {
  return new Promise((resolve, reject) => {
    NeteaseAPI(`http://localhost:3000/playlist/create?name=${name}`).then((res) => {
      if (res.msg == "需要登录") reject("请将 Cookie 放入文件中！");
      resolve(res.id);
    })
  })
}
```

**Comment by Binaryify** [comment]
encodeURI 下呢

**Comment by sxyugao** [comment]
试过了，如果encodeURI，最后的链接为

`/playlist/create?name=&#1641;%EF%BC%88&#160;&#8226;&#768;&#12904;&#8226;&#769;&#160;%EF%BC%89&#1608;`

返回```{"code":400}```

**Comment by sxyugao** [comment]
其实最后本质上还是 `/playlist/create?name=&`

**Comment by Binaryify** [comment]
那你直接post就行了

**Comment by nondanee** [comment]
encodeURI 以后应该是
```
%D9%A9%EF%BC%88%20%E2%80%A2%CC%80%E3%89%A8%E2%80%A2%CC%81%20%EF%BC%89%D9%88
```
啊

**Comment by sxyugao** [comment]
@nondanee 但是你会发现 app,js 里又 decodeURIComponent 了一次，所以我说最后链接还是

```&#1641;%EF%BC%88&#160;&#8226;&#768;&#12904;&#8226;&#769;&#160;%EF%BC%89&#1608;```

**Comment by nondanee** [comment]
@sxyugao 
app.js 里的 decodeURIComponent 只是为了显示，和实际发出的请求没有关系
