### ISSUE TITLE
banners 輪播網頁沒有小圓點出現

### ISSUE THREAD

**Issue by chr1995** [Binaryify/NeteaseCloudMusicApi#751]
## 环境
- 系统/平台: <你的系统和平台>
win10
- nodejs 版本: <你的 NodeJS 版本号>
v10.15.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
我的banner網頁輪播沒有小圓點，我查看了代碼，跟最新版的項目，沒有什麽不同

## 重现步骤
<重现步骤>
<app-wy-carousel #wyCarousel [activeIndex]="carouselActiveIndex" 
   (changeSlie)="onChangeSlide($event)">       
                  <nz-carousel nzAutoPlay nzEffect="fade" [nzDotRender]="wyCarousel.dotRef" 
                       (nzBeforeChange)="onBeforeChange($event)">
                      <div class="carousel-item" nz-carousel-content *ngFor="let item of banners" >
                          <a [href]="item.url" target="_blank" class="banner-item">
                           <img [src]="item.imageUrl"/>
                          </a>
                      </div>
                  </nz-carousel>
          </app-wy-carousel>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
那不是前端的问题吗

**Comment by chr1995** [comment]
> 那不是前端的问题吗

按照正常情况，就是轮播图下面部分有小白点，然后做高光显示，问题是我光有轮播图，没有小白点

**Comment by Binaryify** [comment]
那个是前端实现的啊,和图片无关

**Comment by chr1995** [comment]
> 那个是前端实现的啊,和图片无关

![image](https://user-images.githubusercontent.com/25760245/81240384-d936bc00-9039-11ea-8049-0e2cc970180d.jpeg)上次表达的不太准确，我的问题是，我页面的banners不显示这个下划线_

**Comment by Binaryify** [comment]
那个是你用前端组件库实现的
