### ISSUE TITLE
歌曲评论限制无法使用

### ISSUE THREAD

**Issue by kiko-love** [Binaryify/NeteaseCloudMusicApi#752]
参数limit的更改对于结果不起作用

**Comment by Binaryify** [comment]
重现呢

**Comment by kiko-love** [comment]
问题出在最小值不起作用，如limit=1时出现多余一条评论，limit值较大时可以正常获取

**Comment by Binaryify** [comment]
例子呢?
![image](https://user-images.githubusercontent.com/12221718/81050234-37588780-8ef2-11ea-89a1-47b7aec2c1be.png)

**Comment by kiko-love** [comment]
我是通过网页访问获取内容并解析

![image](https://user-images.githubusercontent.com/57704238/81051543-6a037f80-8ef4-11ea-89e2-958063076522.png)

**Comment by kiko-love** [comment]
![image](https://user-images.githubusercontent.com/57704238/81051761-e6965e00-8ef4-11ea-9a07-c7163069c1ab.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/81051986-47259b00-8ef5-11ea-8190-dcdce323e421.png)
http://musicapi.leanapp.cn/comment/music?id=165593&limit=1

**Comment by Binaryify** [comment]
你是不是看hotComments了

**Comment by kiko-love** [comment]
我是用的首页例子更换id试的，单个歌曲的评论

**Comment by kiko-love** [comment]
hotcomments的参数和这个不一样
![image](https://user-images.githubusercontent.com/57704238/81052374-e2b70b80-8ef5-11ea-8491-a211be159d4f.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/81052446-02e6ca80-8ef6-11ea-88fe-0769d3475627.png)

**Comment by Binaryify** [comment]
![Uploading image.png…]()

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/81052490-198d2180-8ef6-11ea-9c2f-7c309e5c2a85.png)

**Comment by kiko-love** [comment]
那么网页get返回的数据是默认热评的

**Comment by Binaryify** [comment]
这个接口同时返回热评和普通评论的

**Comment by kiko-love** [comment]
好的，谢谢解答，这样可以单独做一个分类解析

**Comment by Binaryify** [comment]
网易那边就是这样的
