### ISSUE TITLE
需要登录的接口该如何使用？服务器是按什么验证登录的？

### ISSUE THREAD

**Issue by lvsong77** [Binaryify/NeteaseCloudMusicApi#755]
## 环境
- 系统/平台: web

- nodejs 版本: v12.16.3

- API版本:0.1.0

## 出现问题
需要登录的接口，比如‘每日推荐’。
早上刚打开项目请求数据报了301，返回登录页登陆了之后就拿到数据了。
但是我也并没有传给服务器什么呀？cockie和token都没有使用。
服务器是按照时间去验证是否登录失效的么？

## 期待效果
请大佬告知是否需要手动带cookie之类的来验证登录，小白没用过这个TAT

**Comment by Binaryify** [comment]
带cookies
`/public/test.html` 有例子

**Comment by lvsong77** [comment]
@Binaryify 之前看了test中的例子，有点不明白。
是说加上`withCredentials: true`就可以了么？还是说需要把需登录的请求写在登录的回调里面？

**Comment by Binaryify** [comment]
登陆了就有cookies了,之后的请求都会带上cookies的

**Comment by lvsong77** [comment]
@Binaryify 所以就是只要加上`withCredentials: true`就可以了是吧？也不需要自己去设置cookies？

**Comment by Binaryify** [comment]
withCredentials是为了跨域请求能带上cookies的,默认如果跨域请求是不会带cookies的

**Comment by lvsong77** [comment]
@Binaryify 那就是说，如果不跨域，其实什么都不用干，如果跨域，则加上`withCredentials: true`，我这样理解对吗？

**Comment by Binaryify** [comment]
@lvsong77 嗯
