### ISSUE TITLE
请问用哪个接口可以获取电台播放地址链接(不是直播), 用获取音乐接口获取不到

### ISSUE THREAD

**Issue by VitaminCtea** [Binaryify/NeteaseCloudMusicApi#756]
## 环境
- 系统/平台:  windows 10

- nodejs 版本:  v12.14.1

- API版本: 3.28

## 出现问题
请问如何获取非直播电台的播放地址，用获取音乐的接口获取不到!

## 重现步骤
用获取音乐的接口请求非直播电台的播放地址

## 期待效果
能够返回相应电台的播放地址

**Comment by Binaryify** [comment]
`/song/url?id=478446370`
这个不行吗

**Comment by VitaminCtea** [comment]
@Binaryify 获取电台节目的id不对，这回可以了，感谢！我以为不能用呢
