### ISSUE TITLE
部分接口突然无法拿到数据

### ISSUE THREAD

**Issue by SlowSoulWen** [Binaryify/NeteaseCloudMusicApi#76]
### 环境
系统:  Linux 

nodejs 版本: v6.11.1

### 出现问题

本地`Windows`测试时所用到的接口都没有任何问题一直能拿到数据。放在服务器`Linux`环境下运行，一开始所有接口均正常，之后获取歌单详细信息的`/playlist/detail`接口开始罢工一直无法获取数据，也未触发`err事件`，不知道是什么原因呢？ 

PS： 获取歌曲评论的接口也拿不到数据了

### 重现步骤

![pic](http://oo917ps5l.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20170719235552.png)

![pic2](http://oo917ps5l.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20170719235714.png)

### 期待效果

**Comment by SlowSoulWen** [comment]
我把vue项目重新build一遍可以拿到数据了，不是接口的问题。

**Comment by u3u** [comment]
估计是访问太频繁 IP 被封了
```
curl music.163.com
```
如果一直不返回的话就是封了 可以用代理试试 建议你看一下 #77

**Comment by SlowSoulWen** [comment]
还是可以访问到`music.163.com`，但是部分接口已经很久没有返回过数据了。昨天试了一下用代理IP就可以拿到，看来只能用代理了 ：（

**Comment by Jordonwang** [comment]
我上午还能拿到,中午的时候就一直pending了,不通了

**Comment by SlowSoulWen** [comment]
我现在只能通过代理IP来解决无法获取数据的问题，建议参照楼上的说法做好缓存机制，不然获取数据的速度是绝望级别的（虽然我做了以后也还是挺绝望的233），而且也可以很大程度上减少请求频率。

**Comment by Binaryify** [comment]
@SlowSoulWen 
新版本已加入缓存机制
