### ISSUE TITLE
批量删除歌单

### ISSUE THREAD

**Issue by lang1427** [Binaryify/NeteaseCloudMusicApi#760]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
  接口地址：  /playlist/delete
    我想要 批量删除歌单，可以全选我所有的歌单列表进行删除  而不应是一个一个的id进行删除
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

请提供 类似于  对歌单添加或删除歌曲接口中的 tracks: 歌曲 **id,可多个,用逗号隔开** 功能

**Comment by Binaryify** [comment]
已更新

**Comment by lang1427** [comment]
请打包新版本

**Comment by Binaryify** [comment]
release了

**Comment by lang1427** [comment]
Okey,thanks
