### ISSUE TITLE
nodejs版本过高问题

### ISSUE THREAD

**Issue by wlor0623** [Binaryify/NeteaseCloudMusicApi#763]
## 环境
- 系统/平台: macos 10.14.6

- nodejs 版本: 14.2.0

- API版本:3.29

## 出现问题
由于apicache依赖nodejs版本<13   13+版本运行不起来 能否兼容更高版本nodejs?

## 重现步骤
git clone
npm install

## 期待效果
成功运行

**Comment by Binaryify** [comment]
去apicache那边提issue
