### ISSUE TITLE
获取音乐的url地址有的获取不到

### ISSUE THREAD

**Issue by VitaminCtea** [Binaryify/NeteaseCloudMusicApi#764]
## 环境
- 系统/平台: windows10

- nodejs 版本: v12.14.1

- API版本 :3.29.0

## 出现问题
获取音乐的url地址不全，有的歌曲的url为null，使用文档的解决方案https://music.163.com/song/media/outer/url?id=id.mp3地址有的会正常获取，有的则无权访问，有的则404

## 重现步骤
获取音乐的url地址

## 期待效果
都能获取到音乐的url地址

**Comment by kiko-love** [comment]
获取不到是因为要获取的歌是vip歌曲或者付费歌曲，这个通用直链只能获取普通歌曲，付费通道是加密的，没办法直接获取

**Comment by kiko-love** [comment]
这个我没有试过，你得问问作者

**Comment by VitaminCtea** [comment]
@kiko-love 好的，谢谢您，麻烦了！

**Comment by Archieeeeee** [comment]
问下，已经登录的VIP用户用这个接口也是404是正常的吗，怎么获取VIP歌曲下载地址
