### ISSUE TITLE
查询登录状态接口301

### ISSUE THREAD

**Issue by lvsong77** [Binaryify/NeteaseCloudMusicApi#765]
##  #出现问题
调用`/login/status`接口，报错：
`Error: Request failed with status code 301`

**Comment by Binaryify** [comment]
看文档

**Comment by laurashen23** [comment]
> ## #出现问题
> 调用`/login/status`接口，报错：
> `Error: Request failed with status code 301`

请问解决了吗？我也遇到这个问题

**Comment by lvsong77** [comment]
> > ## #出现问题
> > 调用`/login/status`接口，报错：
> > `Error: Request failed with status code 301`
> 
> 请问解决了吗？我也遇到这个问题

参考`public/test.html`
发送请求时加上`withCredentials: true`

需要注意的是，如果不是直接使用axios，而是有封装的话，可能需要在封装的axios实例中这样写：
`instance.defaults.withCredentials = true`
