### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by wlor0623** [Binaryify/NeteaseCloudMusicApi#767]
## 出现问题
作为一个1.5w点赞的项目 感觉捕捉异常方面不是做的很好 请求错误的api路径 或者是缺少必要的参数 都没有很好的反馈 只是控制台一堆异常 能否完善下

**Comment by Binaryify** [comment]
主要工作量挺大的,以后抽时间完善下吧

**Comment by bubao** [comment]
现在是带服务的api，建议写成模块的方式。之前我写过zhihu的api，就是模块的方式。

[https://github.com/bubao/zhihu-api](https://github.com/bubao/zhihu-api)

**Comment by Binaryify** [comment]
@bubao 
v 3.31.0 后支持模块调用的
