### ISSUE TITLE
App端使用需登录的请求如何添加token

### ISSUE THREAD

**Issue by laurashen23** [Binaryify/NeteaseCloudMusicApi#769]
## 环境
- 系统/平台: <你的系统和平台>
win10+Android
- nodejs 版本: <你的 NodeJS 版本号>
v12.16.2
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.27.0
## 出现问题
我现在在Android App上使用这个api，用到需要登录的接口时，在请求头header里添加获取到的token还是没有用，依旧301未登录，请问这个我应该怎么添加token或者保存登录信息？app不能用cookie诶

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/625

**Comment by laurashen23** [comment]
> #625
我按照评论的操作了，返回的是[text={"status":301,"body":{"msg":"需要登录","code":301},"cookie":[]}]，还是不明白应该怎么保存设置cookie。登录的接口返回的只有token，但又不能放到请求头里去请求…那要怎么记录登录信息呢

**Comment by nondanee** [comment]
@laurashen23 
按 #625
改了以后调登录接口返回的 `cookie: []` 会有值
Android 上保存到 SharedPreference  里呗 

改了以后支持从 querystring 和 body 里读取 cookie
每次请求的时候拼上 `&cookie=xxx`

----

另外，你说的 "app不能用cookie" 我没有懂，为啥不能使用？
`.setHeaders("cookie", value)` 不行吗？
app 上肯定不限制设置请求头啊
如果请求库不提供 session 的话，cookie 需要手动设，自己管理

**Comment by Binaryify** [comment]
新版本登录接口返回内容增加cookie字段,支持手动传入cookie了

**Comment by laurashen23** [comment]
> 新版本登录接口返回内容增加cookie字段,支持手动传入cookie了

你好，我更新了也传入了cookie，每日推荐接口也需要cookie是可以正确返回的，但是获取歌曲url的接口data返回null，浏览器上有数据，同样的请求地址，请问这个会有什么原因吗？

**Comment by laurashen23** [comment]
> @laurashen23
> 按 #625
> 改了以后调登录接口返回的 `cookie: []` 会有值
> Android 上保存到 SharedPreference 里呗
> 
> 改了以后支持从 querystring 和 body 里读取 cookie
> 每次请求的时候拼上 `&cookie=xxx`
> 
> 另外，你说的 "app不能用cookie" 我没有懂，为啥不能使用？
> `.setHeaders("cookie", value)` 不行吗？
> app 上肯定不限制设置请求头啊
> 如果请求库不提供 session 的话，cookie 需要手动设，自己管理

谢谢！现在碰到的问题是，每日推荐这种需要cookie的接口可以请求到，但获取歌曲url的接口返回data为null，同时浏览器上是有数据的，一样的请求地址耶，也加了cookie，请问这个会有什么其他的原因吗？

**Comment by Binaryify** [comment]
你是怎么调的
![image](https://user-images.githubusercontent.com/12221718/82534963-b4356380-9b78-11ea-8794-0833ee527d71.png)
