### ISSUE TITLE
下架歌曲，

### ISSUE THREAD

**Issue by keivenliao** [Binaryify/NeteaseCloudMusicApi#770]
## 环境
- 系统/平台: <你的系统和平台>
debin

- nodejs 版本: <你的 NodeJS 版本号>
10.19

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
最新

## 出现问题
{"message":"下架歌曲无法收藏","coverImgUrl":"http://p1.music.126.net/tGHU62DTszbFQ37W9qPHcg==/2002210674180197.jpg","coverImgId":"2002210674180197","trackIds":"[482141126]","code":401,"count":0,"cloudCount":0}

## 重现步骤
路由器上开着UnblockNeteaseMusic
我已经将https 替换为 http  接口已能工作，在执行 

/playlist/tracks?op=add&pid=4947633142&tracks=482141126

时出现以上问题。

但相同网络环境下，使用网易云音乐windows客户端却可以。
请问能解决此问题吗？

**Comment by Binaryify** [comment]
官方就不支持吧
![Uploading image.png…]()

**Comment by keivenliao** [comment]
> 官方就不支持吧
> ![image](https://user-images.githubusercontent.com/12221718/81791649-91cc9600-9539-11ea-830a-85fbfc416f82.png)



我刚才对客户端进行了抓包分析，初步判断客户端走的不是http协议。

**Comment by keivenliao** [comment]
![image](https://user-images.githubusercontent.com/12838693/81793526-11f3fb00-953c-11ea-9b46-875613e22505.png)


这首歌是没有版权的。 经过 UnblockNeteaseMusic 后，在客户端里是可以的。

**Comment by Binaryify** [comment]
@nondanee 你那个是咋收藏的

**Comment by keivenliao** [comment]
我大胆猜测一下。。
收藏这个行为 应该是 客户端软件判断的， 只要歌曲版权状态可用，就可以收藏，由于版权状态经过了UnblockNeteaseMusic 处理，所以就绕过了客户端的限制。  

咱们的 NeteaseCloudMusicApi 请求的如添加无版权歌曲到歌单时，应该是网易的服务器做的判断。所以可能无解。

**Comment by keivenliao** [comment]
![image](https://user-images.githubusercontent.com/12838693/81795999-69e03100-953f-11ea-8235-15df66427ac1.png)

补充一个从路由器上抓的包以供分析@Binaryify

**Comment by nondanee** [comment]
> 我大胆猜测一下。。
> 收藏这个行为 应该是 客户端软件判断的， 只要歌曲版权状态可用，就可以收藏，由于版权状态经过了UnblockNeteaseMusic 处理，所以就绕过了客户端的限制。
> 
> 咱们的 NeteaseCloudMusicApi 请求的如添加无版权歌曲到歌单时，应该是网易的服务器做的判断。所以可能无解。

@keivenliao @Binaryify 
收藏状态服务器判的  (客户端也有判)，不过收藏接口应该有个去重的 bug，重复填 id 即可 (之前试过 v1 和没有 v1 的接口都可以)
https://github.com/nondanee/UnblockNeteaseMusic/issues/9#issuecomment-418770927

看了下这边 `/playlist/tracks` 用的网易云 api 不在我的 target path 里，而且我不处理 weapi 请求 (不对称加密拿不到请求参数)，直接放行了

**Comment by nondanee** [comment]
@Binaryify 你抓的这个包死 unblockneteasemusic 发出的，重复填了 id

**Comment by keivenliao** [comment]
http://192.168.1.202:3000/playlist/tracks?op=add&pid=4947633142&tracks=482141126,482141126
