### ISSUE TITLE
我用php curl 或者 file_get_contents 获取链接的时候 获取到的链接是错误的

### ISSUE THREAD

**Issue by yin50** [Binaryify/NeteaseCloudMusicApi#772]
## 环境
- 系统/平台: <linux 和 windwos都试过>

- nodejs 版本: <12.16.3>

- API版本:<3.27.0>

## 出现问题
php 想处理后 在发送数据出来
用php curl 或者 file_get_contents 获取链接的时候 获取到的链接是错误的
![image](https://user-images.githubusercontent.com/54521644/81998467-2394ea00-9685-11ea-8c6b-3ab1b89db16b.png)
br的值 是999000 获取到的一直是128k的链接 （有FLAC 资源的）然后用浏览器取访问这个链接 就能获取到正确的格式
curl 的头文件是
![image](https://user-images.githubusercontent.com/54521644/81998635-9dc56e80-9685-11ea-8142-6a7a161a2084.png)

## 期待效果
能直接获取正确链接，感谢

**Comment by nondanee** [comment]
绝大部分无损资源登录了才有，需要带 cookie 请求
