### ISSUE TITLE
请问是否考虑导出 API 为模块呢

### ISSUE THREAD

**Issue by poppinlp** [Binaryify/NeteaseCloudMusicApi#773]
看文档描述好像目前得 clone 下来使用，因为这是一个 service。请问是否考虑拆成两部分，core API 一部分，service 一部分呢？:)

**Comment by Binaryify** [comment]
已经模块化了的,每个模块都是个函数,你构造好query和request对象传入就行

**Comment by poppinlp** [comment]
不是，我的意思是目前这个看起来还是一个完整的 service，得 git clone 然后使用，而不是一个 npm 模块。
拆开之后核心 API 部分可以直接例如：

```js
const { apiName }  = require('xxx');
apiName(params)
```

而完整的 service 部分则可以还是类似当前这样集成好了 core API 然后拉下来启动。

不知道我对于 repo 当前状况理解是否正确。:)

**Comment by Binaryify** [comment]
之后的版本加这个功能吧

**Comment by Binaryify** [comment]
新版本支持了

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/82184162-bcdc2e80-9919-11ea-8972-5b3ac573ac04.png)
![image](https://user-images.githubusercontent.com/12221718/82184219-da10fd00-9919-11ea-96e6-7f0900d53e60.png)

**Comment by poppinlp** [comment]
Cool! 效率！

**Comment by Binaryify** [comment]
以后优化吧

**Comment by poppinlp** [comment]
嗯嗯，辛苦啦

**Comment by poppinlp** [comment]
如果你愿意的话，可以开一个 organization 然后拉我进去，我们可以一起处理这部分的事情。:)

**Comment by Binaryify** [comment]
可以的
