### ISSUE TITLE
cookie问题

### ISSUE THREAD

**Issue by 251205668** [Binaryify/NeteaseCloudMusicApi#774]
![](https://image.yangxiansheng.top/img/20200517110413.png?imagelist)
请问调用接口设置cookie要把所有的cookie信息全部存放进去吗, 或者可以在node里面写死cookie吗

**Comment by Binaryify** [comment]
新版本登录接口返回内容增加cookie字段,支持手动传入cookie了

**Comment by 251205668** [comment]
@Binaryify 好的 我更新下
