### ISSUE TITLE
建议新增接口 收藏的MLOG、收藏的专栏

### ISSUE THREAD

**Issue by zion223** [Binaryify/NeteaseCloudMusicApi#776]
## 环境
- 系统/平台: win10 Android

- nodejs 版本: v8.11.3

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
建议新增接口 收藏的MLOG、收藏的专栏，目前已有的接口中有收藏的歌手、专辑、视频。

## 重现步骤
<重现步骤>

## 期待效果
新增接口 收藏的MLOG、收藏的专栏 

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
暂时不加吧,涉及相关的其他接口多也杂,有时间再加吧

**Comment by zion223** [comment]
好的 ❤
