### ISSUE TITLE
在自己本地启动服务后，输入账号密码不会有泄露的风险吗？

### ISSUE THREAD

**Issue by tanjuntao** [Binaryify/NeteaseCloudMusicApi#780]
没有看项目源码，单纯只是担心和好奇：尽管这个项目是在本地启动的，但在地址栏中填入账号密码发请求，不会有泄露的风险吗？

**Comment by Binaryify** [comment]
本地使用没问题的,代码都给你了,泄露给谁呢,但是用别人搭好的会有风险,如果自己搭的给别人用,如果没用https,可能会被中间人获取到

**Comment by tanjuntao** [comment]
> 本地使用没问题的,代码都给你了,泄露给谁呢,但是用别人搭好的会有风险,如果自己搭的给别人用,如果没用https,可能会被中间人获取到,被抓包了,get和post就没区别了

感谢解答！
