### ISSUE TITLE
调用验证验证码接口，返回503状态码

### ISSUE THREAD

**Issue by VitaminCtea** [Binaryify/NeteaseCloudMusicApi#782]
## 环境
- 系统/平台: windows10

- nodejs 版本: v12.14.1

- API版本: 3.31.1

## 出现问题
调用验证验证码接口，返回503状态码
http://localhost:3000/api/captcha/verify?phone=183****4682&captcha=1111 503 (Service Unavailable)
正确的验证码和错误的验证码都是返回503状态码，请问该怎么修复？

## 重现步骤
调用验证验证码接口，返回503状态码

## 期待效果
预期是返回正确的验证码校验状态

**Comment by Binaryify** [comment]
发送验证码接口调了吗

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/82540419-9c161200-9b81-11ea-88cd-88f0dab0866d.png)

**Comment by VitaminCtea** [comment]
@Binaryify 抱歉，我这里调用的发送验证码接口方法给注释掉了，另外验证失败是503，而不是具体的状态码

**Comment by VitaminCtea** [comment]
@Binaryify 现在只能在请求失败里判断
```
axios.get(`/api/captcha/verify?phone=183****4682&captcha=${ captcha }`).then((res) => {
                    console.log(res)
                }).catch((e) => {
                    validationFails(validateItems)
                    index = 0
                    captcha = ''
                })
                return
```

**Comment by Binaryify** [comment]
你把captcha 打印出来看看对不对,还有503是网易那边返回的

**Comment by VitaminCtea** [comment]
@Binaryify 好的谢谢您
