### ISSUE TITLE
今天歌单详情怎么最多获取十首或者二十首了

### ISSUE THREAD

**Issue by nanwy** [Binaryify/NeteaseCloudMusicApi#784]
## 环境
- 系统/平台: win10 

- nodejs 版本: v13.10.1

- API版本:3.26.0

## 出现问题
歌单详情最多十首,pc最多二十首

## 重现步骤
调用playlist/detail?id=3214189237返回十首歌曲

## 期待效果
<现在的效果，期待的效果>  
playlist.tracks最多十首

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by nanwy** [comment]
我的项目..[http://www.nanwayan.cn/find](url)
你点进去看看..

**Comment by nanwy** [comment]
http://www.nanwayan.cn/find

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/82574706-16fb1f00-9bba-11ea-8304-4a6726c0c63a.png)

**Comment by XieWuHen** [comment]
今天我也发现这个问题，很奇怪，只返回10条数据，返回的 曲目统计数据 count 是正常的，但是可用数据就只有10条

**Comment by nanwy** [comment]
多调用一次song/detail  就好了

**Comment by nanwy** [comment]
> 今天我也发现这个问题，很奇怪，只返回10条数据，返回的 曲目统计数据 count 是正常的，但是可用数据就只有10条

多调用一次song/detail 就好了
