### ISSUE TITLE
请教搜索问题

### ISSUE THREAD

**Issue by zhangscofield** [Binaryify/NeteaseCloudMusicApi#788]
你好，我想请教一下，我有一个歌名和歌手的列表，想要通过网易云搜索框搜索并下载第一首歌，我应该怎么去做，可以给点建议吗，我看到您的代码里有搜索的功能。

**Comment by Binaryify** [comment]
调搜索接口然后用`/song/url`拿到歌曲链接,下载功能是你客户端实现的

**Comment by zhangscofield** [comment]
谢谢，我找到解决办法了
