### ISSUE TITLE
搜索接口获取的MP3地址还是无效？

### ISSUE THREAD

**Issue by cainiaozone** [Binaryify/NeteaseCloudMusicApi#79]
### 环境
系统:  微信小程序

nodejs 版本:

### 出现问题
搜索接口获取的MP3地址还是无效？
### 重现步骤
1、搜索接口调用
![image](https://user-images.githubusercontent.com/9943151/29215545-06d6a230-7ede-11e7-9831-03f288404274.png)

2、链接直接访问报404错误
![image](https://user-images.githubusercontent.com/9943151/29215533-f2f3f9c0-7edd-11e7-89b4-4ebf2ae787be.png)

### 期待效果
正常播放，如下：
![image](https://user-images.githubusercontent.com/9943151/29215603-40ecb3a6-7ede-11e7-93a2-9dd28fdf2df0.png)

**Comment by cainiaozone** [comment]
node js 版本：v7.10.0

**Comment by Binaryify** [comment]
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90-url
http://119.29.245.251:3000/search?keywords=%E6%B5%B7%E9%98%94%E5%A4%A9%E7%A9%BA
http://119.29.245.251:3000/music/url?id=347230
