### ISSUE TITLE
热门评论接口中电台评论无法正常获取

### ISSUE THREAD

**Issue by zion223** [Binaryify/NeteaseCloudMusicApi#790]
## 环境
- 系统/平台:Windows Android 

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
热门评论接口中电台评论无法正常获取
/comment/hot 接口 id 资源Id type：4 对应电台
http://62.234.57.125:3000/comment/hot?id=526289575&type=4

## 重现步骤
<重现步骤>

## 期待效果
能够正常获取电台的热门评论，

**Comment by zion223** [comment]
获取到的电台详情: 郭德纲于谦高清相声(持续更新) 此电台的首页是有热门评论的
{
    "dj": {
        "defaultAvatar": false,
        "province": 320000,
        "authStatus": 0,
        "followed": false,
        "avatarUrl": "http://p1.music.126.net/ibb8YiVuElUreqg5sur7Yg==/19218363742391659.jpg",
        "accountStatus": 0,
        "gender": 1,
        "city": 320100,
        "birthday": 794073600000,
        "userId": 75142276,
        "userType": 0,
        "nickname": "苏妙慈",
        "signature": "苏妙慈",
        "description": "",
        "detailDescription": "",
        "avatarImgId": 19218363742391660,
        "backgroundImgId": 109951163324415660,
        "backgroundUrl": "http://p1.music.126.net/2wuwwnfRcOMxcGF3HHKFqg==/109951163324415661.jpg",
        "authority": 0,
        "mutual": false,
        "expertTags": null,
        "experts": null,
        "djStatus": 10,
        "vipType": 0,
        "remarkName": null,
        "backgroundImgIdStr": "109951163324415661",
        "avatarImgIdStr": "19218363742391659",
        "avatarImgId_str": "19218363742391659"
    },
    "category": "相声曲艺",
    "buyed": false,
    "price": 0,
    "originalPrice": 0,
    "discountPrice": null,
    "purchaseCount": 0,
    "lastProgramName": "《我要走二环》郭德纲 于谦",
    "videos": null,
    "finished": false,
    "underShelf": false,
    "liveInfo": null,
    "picUrl": "https://p2.music.126.net/m00AiSZ0tmHSPNAAIZ6avw==/109951164263223904.jpg",
    "desc": "全网最全最高清",
    "picId": 109951164263223900,
    "createTime": 1511854635394,
    "lastProgramCreateTime": 1576058836896,
    "lastProgramId": 2064536957,
    "categoryId": 8,
    "feeScope": 0,
    "programCount": 268,
    "subCount": 377237,
    "radioFeeType": 0,
    "name": "郭德纲于谦高清相声(持续更新)",
    "id": 526289575,
    "rcmdtext": null,
    "newProgramCount": 0
}

**Comment by Binaryify** [comment]
你的id错了吧
http://62.234.57.125:3000/comment/hot?id=2064536957&type=4

**Comment by zion223** [comment]
这个是具体到每个节目的热门评论，我说的是整个电台的热门评论

**Comment by zion223** [comment]
![微信图片_20200525202245](https://user-images.githubusercontent.com/18309572/82812407-84ae9000-9ec5-11ea-97f8-678a4055a600.jpg)

**Comment by Binaryify** [comment]
这个在电台详情的commentDatas里

**Comment by Binaryify** [comment]
http://62.234.57.125:3000/dj/detail?rid=526289575

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/82817384-7cf3e900-9ecf-11ea-94e4-10b2f7f468bb.png)

**Comment by zion223** [comment]
ok 感谢 没注意到这个
