### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by SmileAndys** [Binaryify/NeteaseCloudMusicApi#792]
## 环境
- 系统/平台: <win10家庭版>

- nodejs 版本: <10.16.0>

- API版本:<3.31.1>

## 出现问题
在使用手机号密码登录的时候，如果密码带有特殊符号（比如 @#）这类，密码会在@后面开始截断，会导致登录时候出现登录密码错误的报错提示，也不会登录成功，但是密码是正确的

## 重现步骤
http://localhost:xxxx/login/cellphone?phone=157xxx&password=xxxx@#xxxx
控制台输出为 http://localhost:xxxx/login/cellphone?phone=157xxx&password=xxxx@
且返回密码错误的问题
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
post请求

**Comment by nondanee** [comment]
@ 没问题，# 有问题，因为 # 后面的算作 hash 
需要 encodeURIComponent

**Comment by Binaryify** [comment]
我更新下文档吧

**Comment by SmileAndys** [comment]
谢谢大家解答
