### ISSUE TITLE
playlist/detail 歌单信息不全 只返回10首歌曲

### ISSUE THREAD

**Issue by yueyericardo** [Binaryify/NeteaseCloudMusicApi#794]
## 环境
- 系统/平台: <你的系统和平台>
mac和linux都测试了
- nodejs 版本: <你的 NodeJS 版本号>
v13.13.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.31.1
## 出现问题
`playlist/detail` 歌单信息不全 只返回10首歌曲

## 重现步骤
`playlist/detail?id=981008207`

## 期待效果
应返回20首歌曲信息
只返回了10首

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/784
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/791

**Comment by yueyericardo** [comment]
> #784
> #791

啊 抱歉！没有检查closed 的 issue，重复了。
