### ISSUE TITLE
获取排行榜的数据

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#795]
## 环境
- 系统/平台: <你的系统和平台>
Microsoft Windows 10 专业版 10.0.18363 版本 18363

- nodejs 版本: <你的 NodeJS 版本号>
![image](https://user-images.githubusercontent.com/38646454/83014193-d8011980-a050-11ea-8ab7-f23cb67c85c2.png)

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.29.0

## 出现问题
<出现的问题>
获取排行榜的数据 总感觉是移动端的数据 
图片与桌面端不一致
## 重现步骤
<重现步骤>
![image](https://user-images.githubusercontent.com/38646454/83013991-7b9dfa00-a050-11ea-95fc-6b314701271f.png)

接口地址  :   /top/list?idx=3
唯一图片字段  :   coverImgUrl
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
可能是客户端写死的图片

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/83322638-f868e800-a28b-11ea-880b-1f55a7b88b2d.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/83322646-09195e00-a28c-11ea-9141-71bc27b679eb.png)

**Comment by refuse-c** [comment]
好的,我自己把那个图扣下来了   虽然有点模糊但是还能将就看,后期可能会重构,换个样式写

[cid:image001.png@01D637F2.F37A4C20]





发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年5月30日 15:13
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 获取排行榜的数据 (#795)
