### ISSUE TITLE
能否增加一个获取累计听歌量的接口

### ISSUE THREAD

**Issue by RedShameA** [Binaryify/NeteaseCloudMusicApi#796]
在网页端这个数据是直接嵌入在html里的，没有找到单独接口
在手机和PC客户端抓包返回的数据是加密的(interface*.music.163.com/****)

**Comment by Binaryify** [comment]
获取用户详情接口的listenSongs字段有

**Comment by RedShameA** [comment]
获取用户详情接口的listenSongs字段有
