### ISSUE TITLE
search 方法，参数无效

### ISSUE THREAD

**Issue by shalldie** [Binaryify/NeteaseCloudMusicApi#8]
【遇到的问题：】
limit 和 offset ，2个参数输入无效。

search接口总是返回4个结果。

【环境：】
OSX

【node 版本： 】
v7.2.0

【代码示例：】

```
const api = require('NeteaseCloudMusicApi').api;

api.search('第一次', data => {
    console.log(JSON.parse(data).length);
}, true, 10, 10);
````

**Comment by TangMonk** [comment]
[search.js](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/src/component/search.js#L7) 下的url是错误的：

不应该是 `const url = `${origin}/api/search/suggest/web`, 而是: `const url = `${origin}/api/search/get``

**Comment by Binaryify** [comment]
@TangMonk 已经修复
