### ISSUE TITLE
怎样支持https请求呢

### ISSUE THREAD

**Issue by 273851541** [Binaryify/NeteaseCloudMusicApi#804]
网上找了好多nodejs支持https请求的教程,都没有成功
比如这个:
[https://www.jianshu.com/p/638f364e0642?utm_source=oschina-app](url)

设置好后但是却报了下面的错误,搞了好久都搞不了https访问
![image](https://user-images.githubusercontent.com/22609984/83483909-44a76880-a4d6-11ea-8bea-1b9453654316.png)

**Comment by Binaryify** [comment]
配nginx

**Comment by 273851541** [comment]
> 配nginx

谢谢,已经可以了

**Comment by refuse-c** [comment]
我傻了   配置了nginx 的htpps   静态资源可以用https 访问 但是服务不能用https
