### ISSUE TITLE
服务端返回400报错

### ISSUE THREAD

**Issue by hmzkk** [Binaryify/NeteaseCloudMusicApi#807]
在使用api时出现{ status: 400,
  body: { msg: 'Cheating', code: -460, message: 'Cheating' } }，
有解决方法吗？

**Comment by Binaryify** [comment]
你提issues的时候不是能看到解决方案吗

**Comment by hmzkk** [comment]
> 你提issues的时候不是能看到解决方案吗,为什么不看就删掉呢,文档也有写啊

刚看到，抱歉哈
