### ISSUE TITLE
独家放送 只有3个item

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#808]
## 环境
- 系统/平台: <你的系统和平台>
![image](https://user-images.githubusercontent.com/38646454/83832611-abb65e80-a71c-11ea-8150-c73d4980fd0a.png)

- nodejs 版本: <你的 NodeJS 版本号>
![image](https://user-images.githubusercontent.com/38646454/83832277-d9e76e80-a71b-11ea-9faf-2e6c20124b8c.png)

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
![image](https://user-images.githubusercontent.com/38646454/83832402-292d9f00-a71c-11ea-8482-8dacec758a12.png)

## 出现问题
通过接口/personalized/privatecontent获取独家放送数据只有3个数据   但是网易云桌面端是可以下拉继续加载的 而且在接口文档上也没有看分页的 偏移数量和取出数量.我是吧接口地址调用错了还是其他的问题 
![image](https://user-images.githubusercontent.com/38646454/83832105-78bf9b00-a71b-11ea-803a-73bffe4be26e.png)

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
已更新支持(v@3.32.2)

**Comment by refuse-c** [comment]
好的


________________________________
发件人: binaryify <notifications@github.com>
发送时间: Friday, June 5, 2020 11:45:16 AM
收件人: Binaryify/NeteaseCloudMusicApi <NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh <xiangbh@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 独家放送 只有3个item (#808)


已更新支持(v@3.32.2)

―
