### ISSUE TITLE
获取用户歌单接口少了一个歌单

### ISSUE THREAD

**Issue by ljlhnick** [Binaryify/NeteaseCloudMusicApi#809]
## 环境
- 系统/平台: window10

- nodejs 版本: <10.14>

- API版本:<3.32.1>

## 出现问题
<获取用户歌单接口少了一个歌单的数据>

## 重现步骤
<直接根据用户userId请求接口>

![image](https://user-images.githubusercontent.com/29392527/83845853-38244980-a73c-11ea-9f09-c75a0c27a769.png)

**Comment by nondanee** [comment]
是隐私歌单吧？

**Comment by ljlhnick** [comment]
> 是隐私歌单吧？

是的，谢了
