### ISSUE TITLE
通知-通知接口返回的数据无法解析

### ISSUE THREAD

**Issue by zion223** [Binaryify/NeteaseCloudMusicApi#810]
## 环境
- 系统/平台: Linux Android

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
通知-通知返回的接口数据无法解析为JSON格式

## 重现步骤
请求 62.234.57.125:3000/msg/notices接口 返回数据

## 期待效果
接口返回的数据可返回为json格式数据

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
网易那边返回的就是这样的,你自己parse就好了

**Comment by zion223** [comment]
返回数据中的一个Notice如下 notice应该是可以被再次解析成json数据的，但是我放到json解析工具里面显示不是合法的json格式。
  "notices": [
        {
            "queued": false,
            "id": 49595824594,
            "userId": 123170560,
            "time": 1589466289377,
            "notice": "{\"playlist\":{\"name\":\"张张________喜欢的音乐\",\"id\":153503871,\"adType\":0,\"adjustedPlayCount\":427.0,\"validCloudTrackCount\":0,\"anonimous\":false,\"trackNumberUpdateTime\":1588243604470,\"validTrackCount\":20,\"description\":null,\"tags\":[],\"playCount\":159,\"trackUpdateTime\":1589370429380,\"specialType\":5,\"coverImgId\":109951164268555963,\"trackCount\":20,\"bookedCount\":0,\"privacy\":0,\"status\":0,\"userId\":123170560,\"createTime\":1452661838402,\"updateTime\":1588243604470,\"auditRejected\":false,\"approved\":false,\"recommended\":false,\"auditStatus\":0,\"auditTime\":1477055977051,\"copied\":false,\"highQuality\":0,\"coverStatus\":1,\"defaultCover\":false,\"createEventId\":0},\"type\":2,\"user\":{\"description\":\"\",\"avatarImgIdStr\":\"109951164899669891\",\"backgroundImgIdStr\":\"109951162868128395\",\"backgroundImgId\":109951162868128395,\"birthday\":633974400000,\"accountStatus\":0,\"city\":1002800,\"detailDescription\":\"\",\"defaultAvatar\":false,\"djStatus\":0,\"followed\":false,\"backgroundUrl\":\"https://p2.music.126.net/2zSNIqTcpHL2jIvU6hG0EA==/109951162868128395.jpg\",\"nickname\":\"s03z00joq\",\"userId\":3292887580,\"province\":1000000,\"avatarUrl\":\"https://p2.music.126.net/PwlpwKvVy5nKdP7cNDJ3CQ==/109951164899669891.jpg\",\"authStatus\":0,\"expertTags\":null,\"userType\":0,\"remarkName\":null,\"vipType\":0,\"experts\":null,\"gender\":2,\"mutual\":false,\"avatarImgId\":109951164899669891,\"signature\":\"       如果能好好在一起，大起大落，些许困难也没关系。可有些人和事再也回不去。\",\"authority\":0}}",
            "pushMsg": null,
            "type": 0
        }

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/83849216-a3bce580-a741-11ea-9805-02404b16e383.png)

**Comment by zion223** [comment]
是我找的解析JSON的工具的问题，换了一个就能解析了。
