### ISSUE TITLE
用户听歌记录的播放次数不对

### ISSUE THREAD

**Issue by ljlhnick** [Binaryify/NeteaseCloudMusicApi#811]
## 环境
- 系统/平台: window10

- nodejs 版本: <10.14>

- API版本:<3.32.1>

## 出现问题
<用户听歌记录次数不对，不论最近一周和所有都不对>

## 重现步骤
<直接根据用户userId请求接口/user/record?uid=>

![image](https://user-images.githubusercontent.com/29392527/83939993-bacc0800-a813-11ea-9e4b-3bfd20950cf6.png)

![image](https://user-images.githubusercontent.com/29392527/83940063-637a6780-a814-11ea-8439-e33477c5fa3d.png)

**Comment by nondanee** [comment]
#645
别人的 playCount 是看不到的，只能看自己的，要登录
