### ISSUE TITLE
批量发送请求点赞时，出现 502 报错

### ISSUE THREAD

**Issue by freedomwebcn** [Binaryify/NeteaseCloudMusicApi#813]
## 环境
- 系统/平台: <你的系统和平台>
Windows 10 
- nodejs 版本: <你的 NodeJS 版本号>
V10.15.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.31.1
## 出现问题
<出现的问题>
批量发送请求在歌曲评论区点赞时，出现 502 报错
## 重现步骤
<重现步骤>
 -- commentIdArr 数组中保存的是歌曲全部评论的 ID 号
![image](https://user-images.githubusercontent.com/43689316/83944305-0c38bf00-a835-11ea-8a08-c9f88c771478.png)

![image](https://user-images.githubusercontent.com/43689316/83944230-6f762180-a834-11ea-842d-50c0f015404c.png)

## 期待效果
<现在的效果，期待的效果>  
期待出现 200 状态

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by nondanee** [comment]
1. 不要刷赞，有风控的
2. cookie 使用方式有问题，返回头 set-cookie 和请求头 cookie 的格式不一样

**Comment by freedomwebcn** [comment]
> * 不要刷赞，有风控的
> * cookie 使用方式有问题，返回头 set-cookie 和请求头 cookie 的格式不一样

好的👌，谢谢
