### ISSUE TITLE
VIP音乐连接返回为null

### ISSUE THREAD

**Issue by Noire-Neptune** [Binaryify/NeteaseCloudMusicApi#814]
## 环境
- 系统/平台: <你的系统和平台>
win10 64
- nodejs 版本: <你的 NodeJS 版本号>
12
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
v12.16.1
## 出现问题
<出现的问题>
接口获取歌曲url, 这些歌曲是有效的, 但是返回url为null
![image](https://user-images.githubusercontent.com/50104727/83968206-1a044800-a8fa-11ea-9df9-dd5355e91a61.png)

## 重现步骤
<重现步骤>
进过我个人多次测试, 原因为大部分VIP音乐不能返回为null, 我个人为会员账号, 有没有办法可以返回出这些VIP音乐的url
## 期待效果
<现在的效果，期待的效果>  
能获取账号的VIP状态, 返回出VIP音乐的url

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
cookie确认带上了吗

**Comment by vibalavida** [comment]
搜索好像也不行，我是直接用浏览器请求的。这边只有歌曲名和歌手的数据，专辑封面url是空，歌手图片url是默认的：
![image](https://user-images.githubusercontent.com/35448638/85204244-bcceb480-b345-11ea-9e3b-3b4e09f63a18.png)

**Comment by Binaryify** [comment]
专辑和歌手图片都是其他接口获取的

**Comment by Binaryify** [comment]
vip 音乐的链接我这边是可以获取的
![image](https://user-images.githubusercontent.com/12221718/85217110-bc72ff80-b3bf-11ea-82ce-d5f1d1869c0a.png)
