### ISSUE TITLE
希望可以添加一个全部视频接口以及视频分类接口

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#816]
## 环境
- 系统/平台: <你的系统和平台>
 Microsoft Windows 10 专业版
- nodejs 版本: <你的 NodeJS 版本号>
v12.16.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.32.2

希望可以添加一个全部视频接口以及视频分类接口(我反复浏览了接口文档,没有看见这2个接口,不过mv是有的)
![image](https://user-images.githubusercontent.com/38646454/84116678-db3dd180-aa62-11ea-8719-20ca7cce4f36.png)

**Comment by refuse-c** [comment]
其实音乐排行榜那个我去看了你的源代码 我自己已经更新了  就是type取1  2   3  4   ,另外视频接口 我测试了 给你回复吧

发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月10日 23:23
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


已更新

―

**Comment by Binaryify** [comment]
嗯,就是1,2,3,4

**Comment by refuse-c** [comment]
但是我看那个排行榜一般都是top100  你给改成50了   另外视频接口可以自己传入一个limit?因为默认取出来就8个 感觉做桌面端好像有点少  在移动端还可以   接口地址: /video/group        /video/timeline/all



发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 11:01
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


嗯,就是1,2,3,4

―

**Comment by Binaryify** [comment]
limit 我试了无效,传1也是8个

**Comment by refuse-c** [comment]
尴尬ing  感觉应该是取错值了

发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 12:31
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


limit 我试了无效,传1也是8个

―

**Comment by Binaryify** [comment]
>但是我看那个排行榜一般都是top100  你给改成50了
这个指的是`/top/list`接口?

**Comment by refuse-c** [comment]
对的      从排行榜页面点击进入详情页是展示的top100   可以改成自定义条数    因为在桌面端排行榜页面显示的是前8条数据    详情是100    在我提建议之前我看你的默认是100 改了之后是50啦,可以考虑传值,不传时默认给100 一点小建议  我本地自己已经修改啦   看你怎么想嘛  我自己修改了一部分  然后每次都是git stash再同步你的最后部署到服务器
发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 13:15
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


但是我看那个排行榜一般都是top100 你给改成50了

这个指的是/top/list接口?

―

**Comment by Binaryify** [comment]
50指的是里面的tracks的长度吗,那个本身就不靠谱的,得靠trackIds的

**Comment by refuse-c** [comment]
Emmmm   我一直是取的tracks 的东西  那个里面我只是拿了id  名字  歌手 专辑名字 时长几个字段(用来初始化展示列表信息)  其他的都是播放时在线获取的 但是我看了很多 发现tracks和trackIds的长度好像是一样的


发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 13:54
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


50指的是里面的tracks的长度吗,那个本身就不靠谱的,得靠trackIds的

―

**Comment by Binaryify** [comment]
tracks 长度是会变的,不一定是100,一般是拿到全部 trackIds 请求一次 `song/detail`

**Comment by refuse-c** [comment]
哎呀,骚瑞 ,搞错了   不是这个接口  /top/list

是这个: 接口地址 : /toplist/artist

歌手榜

你现在改的limit是50啦
[cid:image002.png@01D63FFB.3DFCB0C0]

[cid:image001.png@01D63FF9.FCF3EFE0]
发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 14:02
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


tracks 长度是会变的,不一定是100,一般是拿到全部 trackIds 请求一次 song/detail

―

**Comment by Binaryify** [comment]
50?
![image](https://user-images.githubusercontent.com/12221718/84364022-22ae9400-ac02-11ea-88d1-45693a9a6ac8.png)

**Comment by refuse-c** [comment]
Emmmm  但是我把代码同步下来就是我截图的那样  QAQ     另外,大佬方便加个qq啥的? (qv同号:1633728652) 我准备耐心的把这个项目做完

发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年6月11日 16:39
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


50?
[image]<https://user-images.githubusercontent.com/12221718/84364022-22ae9400-ac02-11ea-88d1-45693a9a6ac8.png>

―

**Comment by Binaryify** [comment]
有问题直接提issues
我这边看是100条的
![image](https://user-images.githubusercontent.com/12221718/84380571-22ba8e00-ac1a-11ea-8ff6-25cdf7999b85.png)

**Comment by yl8023** [comment]
我想问一下全部视频接口和获取分类视频接口都是需要登录的吗，客户端不需要登录的啊

**Comment by refuse-c** [comment]
[cid:image001.png@01D650A8.9E45A320]
[cid:image002.png@01D650A8.B0DDC4E0]video 需要  nv 不需要

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: yl8023 <notifications@github.com>
发送时间: Thursday, July 2, 2020 5:03:08 PM
收件人: Binaryify/NeteaseCloudMusicApi <NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh <xiangbh@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 希望可以添加一个全部视频接口以及视频分类接口 (#816)


我想问一下全部视频接口和获取分类视频接口都是需要登录的吗，客户端不需要登录的啊

―
