### ISSUE TITLE
抖音排行榜发布评论失败

### ISSUE THREAD

**Issue by lang1427** [Binaryify/NeteaseCloudMusicApi#819]
## 环境
- 系统/平台: <你的系统和平台>
win10
- nodejs 版本: <你的 NodeJS 版本号>
12.16.1
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.29.0
## 出现问题
<出现的问题>
在抖音排行榜中发布评论，请求状态成功，但是没有看到发布后的评论，
看了issues，当然云音乐新歌榜是可以的
## 重现步骤
<重现步骤>
/comment?t=1&type=2&id=2250011882&content=233
## 期待效果
<现在的效果，期待的效果>  
请告知是否为bug还是操作有误

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/84367880-6c4dad80-ac07-11ea-88dd-f9fc601a0b88.png)
你是不是遇到缓存了

**Comment by Binaryify** [comment]
我看到评论被删了,不知道是不是限评了

**Comment by Binaryify** [comment]
手动在客户端评论也会被删评论

**Comment by lang1427** [comment]
Oh，好像是的，我在客户端也是。还以为是被接口被限评了
