### ISSUE TITLE
axios withCredentials为true的疑问

### ISSUE THREAD

**Issue by sandmanman** [Binaryify/NeteaseCloudMusicApi#82]
### 环境
系统:  mac 10.11.6

nodejs 版本:7.4.0

### 出现问题
因为一开始发现调用登录接口，登录成功后浏览器并没有保存Cookies，然后设置axios withCredentials=true后，浏览器能够自动保存到Cookie '__csrf'，但是请求的接口就会报错：

`XMLHttpRequest cannot load http://localhost:1128/banner. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://192.168.1.4:8080' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

但是我通过NetWork查看请求的数据都是能够请求到数据的，比如http://localhost:1128/banner
（app.js也开启了跨域）
如果withCredentials=false，数据请求就没有上面的报错，可登录后浏览器却无法自动保存Cookie '__csrf'，

我想知道这是什么原因，还有就是'__csrf'的值应该怎么获取并保存时正确的...
感谢。

**Comment by u3u** [comment]
`Access-Control-Allow-Credentials` 为 `true` 的时候
`Access-Control-Allow-Origin` 响应头不能为 `*` 必须指定域名

你可以把 `app.js` 改成这样

``` javascript
// 跨域设置
app.all('*', function (req, res, next) {
  if (req.path !== '/' && !req.path.includes('.')) {
    res.header('Access-Control-Allow-Credentials', true)
    // 这里获取 origin 请求头 而不是用 *
    res.header('Access-Control-Allow-Origin', req.headers['origin'] || '*')
    res.header('Access-Control-Allow-Headers', 'X-Requested-With')
    res.header('Access-Control-Allow-Methods', 'PUT,POST,GET,DELETE,OPTIONS')
    res.header('Content-Type', 'application/json;charset=utf-8')
  }
  next()
})
```

**Comment by u3u** [comment]
@Binaryify 
这里有个小 bug 也可以顺手改了 qwq

**Comment by Huohuohuo** [comment]
> `Access-Control-Allow-Credentials` 为 `true` 的时候
> `Access-Control-Allow-Origin` 响应头不能为 `*` 必须指定域名
> 
> 你可以把 `app.js` 改成这样
> 
> ```js
> // 跨域设置
> app.all('*', function (req, res, next) {
>   if (req.path !== '/' && !req.path.includes('.')) {
>     res.header('Access-Control-Allow-Credentials', true)
>     // 这里获取 origin 请求头 而不是用 *
>     res.header('Access-Control-Allow-Origin', req.headers['origin'] || '*')
>     res.header('Access-Control-Allow-Headers', 'X-Requested-With')
>     res.header('Access-Control-Allow-Methods', 'PUT,POST,GET,DELETE,OPTIONS')
>     res.header('Content-Type', 'application/json;charset=utf-8')
>   }
>   next()
> })
> ```

按你的注释说的，需要改成：
`res.header('Access-Control-Allow-Origin', req.headers['origin'])`
