### ISSUE TITLE
在获取专辑内容时好像没有返回专辑的发行时间?

### ISSUE THREAD

**Issue by album-GitHub** [Binaryify/NeteaseCloudMusicApi#820]
在获取专辑内容时好像没有见返回专辑的发行时间,整理专辑时挺不方便的,希望大大能考虑下添加进去.

**Comment by Binaryify** [comment]
publishTime 不是吗

**Comment by album-GitHub** [comment]
> publishTime不是吗

这个得出来的时间要怎样才能换算成标准时间呢,长长的一串数字看着没啥头绪呀.............

**Comment by Binaryify** [comment]
new Date(时间戳)
