### ISSUE TITLE
新建歌单接口请求状态码为250

### ISSUE THREAD

**Issue by 1240892737** [Binaryify/NeteaseCloudMusicApi#822]
## 环境
- 系统/平台:  linux H5

- nodejs 版本: v10.20.1

- API版本:3.33.0

## 出现问题
<出现的问题>
![image](https://user-images.githubusercontent.com/39523871/84613068-f1c9aa00-aef4-11ea-92d5-57705282a9c4.png)
此接口请求返回250

## 重现步骤
<重现步骤>
地址
/playlist/create?name=我的111&cookie=... 
加上正确的cookie，接口还是状态码还是250
问题： http状态码返回250
![image](https://user-images.githubusercontent.com/39523871/84613134-2b9ab080-aef5-11ea-8a83-c930c80d609e.png)

## 期待效果
<现在的效果，期待的效果>  
请求200就行

**Comment by Binaryify** [comment]
已修复~
