### ISSUE TITLE
获取每日推荐歌曲只能获取非会员的，是否能获取会员的歌曲名称

### ISSUE THREAD

**Issue by 346180990** [Binaryify/NeteaseCloudMusicApi#826]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>
3.0.0

![image](https://user-images.githubusercontent.com/39411372/85197979-65b1eb00-b317-11ea-8b4b-ecc3b0656055.png)

**Comment by Binaryify** [comment]
更新了

**Comment by 346180990** [comment]
OK，谢谢
