### ISSUE TITLE
网易云音乐用户等级

### ISSUE THREAD

**Issue by ZainCheung** [Binaryify/NeteaseCloudMusicApi#829]
## 环境
- 系统/平台: centos

- nodejs 版本: 12.16.3

- API版本:3.33.2

## 期待效果
目前文档里没有看到用户等级相关的接口, 希望可以添加接口, 能够查询自己一共听过多少歌曲还有多少歌曲可以升级等
网易的查询入口是https://music.163.com/#/user/level

**Comment by Binaryify** [comment]
用户详情接口有
