### ISSUE TITLE
榜单排行有些参数错误 

### ISSUE THREAD

**Issue by IAmWilling** [Binaryify/NeteaseCloudMusicApi#830]
## 环境
- 系统/平台: <windows>

- nodejs 版本: <8.1>

- API版本:<3.33.2>

## 出现问题
<榜单排行有些参数错误 >

## 重现步骤
<榜单排行有些参数错误 >

## 期待效果
<有榜单歌曲的排行>  

![QQ截图20200625162701](https://user-images.githubusercontent.com/39398882/85684752-fa925b00-b700-11ea-8eee-5c220524db54.png)

**Comment by Binaryify** [comment]
你的id错了

**Comment by Binaryify** [comment]
/top/list?id=2809577409

**Comment by IAmWilling** [comment]
> / top / list？id = 2809577409
对着呢呀，我是先获取的所有榜单列表 从列表里面拿出来的id 然后用这个id去获取榜单排行的歌曲

**Comment by IAmWilling** [comment]
![RRM A%0`EZ% TMN~W{YU$YJ](https://user-images.githubusercontent.com/39398882/85686093-3da0fe00-b702-11ea-9348-d34001512680.png)

**Comment by Binaryify** [comment]
我看看

**Comment by IAmWilling** [comment]
> 我看看

好的！

**Comment by Binaryify** [comment]
修复了

**Comment by IAmWilling** [comment]
> 修复了
好的 谢谢！节日快乐

**Comment by Binaryify** [comment]
同乐同乐~

**Comment by ooiv7oo** [comment]
啥也没说，就修复了？
