### ISSUE TITLE
歌单歌曲1973首 无法获取了

### ISSUE THREAD

**Issue by IAmWilling** [Binaryify/NeteaseCloudMusicApi#833]
RT！
歌单id 2431972562
步骤1.先调用playlist/detail?id=2431972562
步骤2.拿到taracksids拼接id字符串
步骤3.请求song/details?ids=xxxxx,xxxxx,xxxxx,xxxxx,....
当歌曲有一千多首的时候，无法获取了！

**Comment by mynamezhaoyu** [comment]
切开，不要一次性拉数据。

**Comment by OldSixLi** [comment]
目前网易云改版，web端无法查看全部歌单内容，只能在客户端查看，应该和这个有关系。

**Comment by Binaryify** [comment]
晚点更新接口

**Comment by Binaryify** [comment]
应该是官方限制了 song/detail 接口的id数量了，客户端的接口也不能超过1000，你分割下吧

**Comment by vayci** [comment]
> 目前网易云改版，web端无法查看全部歌单内容，只能在客户端查看，应该和这个有关系。

这个有解吗~

**Comment by Binaryify** [comment]
@vayci 每次只发1000个id

**Comment by vayci** [comment]
> @vayci 每次只发1000个id

噢噢噢， 我的问题是playlist/detail获取tracksids获取不完整，看了文档应该是API调整后我没登录的原因，感谢~
