### ISSUE TITLE
下载完成后,执行npm i 出现报错 Unexpected end of JSON input while parsing near '...-nodecli":"~0.1.0","s' 

### ISSUE THREAD

**Issue by left-handed** [Binaryify/NeteaseCloudMusicApi#835]
## 环境
- 系统/平台:mac

- nodejs 版本: 12.16.1

- API版本:3.34.0

## 出现问题
![image](https://user-images.githubusercontent.com/22977943/86034314-ec2fa080-ba6c-11ea-8c0f-1aef5e411910.png)

## 重现步骤
$ npm i

## 期待效果
成功

**Comment by Binaryify** [comment]
npm cache clean --force
之后再重新装依赖试试
