### ISSUE TITLE
排行榜接口获取的数据不是最新的(应该是这个问题吧)

### ISSUE THREAD

**Issue by Mint-green** [Binaryify/NeteaseCloudMusicApi#838]
## 环境
- 系统/平台: Linux Centos 8.0

- nodejs 版本: v14.4.0

- API版本: 3.34.0

## 出现问题
排行榜接口获取的数据不是最新的（和toplist接口和toplist_detail的更新时间不一样）

## 重现步骤
1. 首先调用toplist接口获取榜单id
![image](https://user-images.githubusercontent.com/45754271/86503363-fd1b4180-bddf-11ea-8e86-fa530adf007d.png)
"trackNumberUpdateTime": 1593820924043,
"trackUpdateTime": 1593824525238,
"id": 19723756,
"name": "云音乐飙升榜",

2. 然后到top_list接口获取榜单详情
![image](https://user-images.githubusercontent.com/45754271/86503431-b0843600-bde0-11ea-9a5c-536e48d3431f.png)

3. 发现和网易云的榜单不一样
![image](https://user-images.githubusercontent.com/45754271/86503491-2a1c2400-bde1-11ea-8fbe-45c8640289a6.png)
这里只截了一部分，实际上100首里面没有刚刚调用接口时获取的一首

4. 调用榜单内容摘要发现时间也和详情不一致，但和toplist接口的一样，前三首也和网易云的一样，故猜测是时间的问题
![image](https://user-images.githubusercontent.com/45754271/86503595-3fde1900-bde2-11ea-9172-228677d1e288.png)

## 期待效果
top_list接口修改一下，时间更正，能和网易云的同步，
或者榜单相关接口同时延迟？(雾

##最后
感谢作者！！！
救了我老命一条！

**Comment by Binaryify** [comment]
接口做了缓存处理,你自己url加个时间戳或者随机数

**Comment by Mint-green** [comment]
请问怎么加时间戳啊233
是直接&(timestamp)嘛

**Comment by Binaryify** [comment]
?xxx=timestamp

**Comment by Mint-green** [comment]
可是他不是本身就已经有个id参数了嘛
所以就是 ?id=...&xxx=timestamp 嘛

**Comment by Mint-green** [comment]
噢噢，看到文档的说明了，我去试试，谢谢作者大大！

**Comment by Mint-green** [comment]
![image](https://user-images.githubusercontent.com/45754271/86503906-30140400-bde5-11ea-9127-e5a550fbff00.png)
这还是没有变也

**Comment by Mint-green** [comment]
![image](https://user-images.githubusercontent.com/45754271/86504050-e0ced300-bde6-11ea-8b3f-d95086557704.png)
emm，我算了一下，那个时间是6.16，会不会是那个接口的请求链接坏了？

**Comment by Binaryify** [comment]
晚点我看看

**Comment by Mint-green** [comment]
好滴，谢谢！

**Comment by Binaryify** [comment]
暂时用歌单详情接口吧,排行榜也是歌单的一种,榜单详情接口考虑废弃了

**Comment by Mint-green** [comment]
哇，真的可以耶！
之前居然没发现orz
谢谢大佬！
