### ISSUE TITLE
建议，将这个api做成依赖包的形式，方便嵌入到其他项目中去

### ISSUE THREAD

**Issue by jarden-liu** [Binaryify/NeteaseCloudMusicApi#84]
### 期待效果
建议，将这个api做成依赖包的形式，方便嵌入到其他项目中去

**Comment by Binaryify** [comment]
现在项目耦合度已经很松了,很容易嵌入到其他项目的

**Comment by jarden-liu** [comment]
感觉路由那里可以再拆一下，会更方便用

**Comment by Binaryify** [comment]
有什么建议吗

**Comment by jarden-liu** [comment]
以NeteaseCloudMusicApi/router/artists.js这个为例子吧

router.get("/", (req, res) => {
  const cookie = req.get('Cookie') ? req.get('Cookie') : ''
  const data = {
		"csrf_token": ""
  }
  const id = req.query.id
  const offset = req.query.offset || 0
  const limit = req.query.limit || 50
  createWebAPIRequest(
    'music.163.com',
    `/weapi/v1/artist/${id}?offset=${offset}&limit=${limit}`,
    'POST',
    data,
    cookie,
    music_req => res.send(music_req),
    err => res.status(502).send('fetch error')
  )
})



就是希望这个APIRequest  和  router 拆分一下  。
这样就可以使用APIRequest  也可以引用router

**Comment by Binaryify** [comment]
可以,不过需要点时间

**Comment by jarden-liu** [comment]
好，辛苦啦

**Comment by vc1** [comment]
@Binaryify 网易云音乐 PC 客户端加密 API 逆向解析 http://www.freebuf.com/articles/web/164636.html

**Comment by XGHeaven** [comment]
如果你有兴趣，可以看一下这个 [netease-music-sdk](https://www.npmjs.com/package/netease-music-sdk)
