### ISSUE TITLE
歌手分类列表(/artist/list)，变更cat参数数值，始终为相同数据

### ISSUE THREAD

**Issue by TothingWay** [Binaryify/NeteaseCloudMusicApi#843]
## 环境
- 系统/平台: macOS

- nodejs 版本: 12.16.2

- API版本: 3.34.1

## 出现问题
歌手分类列表，变更cat参数数值，始终为相同数据

## 重现步骤
分别调用 /artist/list?cat=1002 接口，/artist/list?cat=1003 接口，返回数据不变

## 期待效果
返回cat参数对应数据

**Comment by Binaryify** [comment]
文档忘记改了, cat 参数已经废弃了
