### ISSUE TITLE
喜欢歌曲评论接口能调用成功，但数据不更新呀。

### ISSUE THREAD

**Issue by Xzw111222** [Binaryify/NeteaseCloudMusicApi#846]
## 环境
- 系统/平台: <Win10>

- API版本:<3.4.0>

## 出现问题
喜欢歌曲评论接口 ``/comment/like?id=28256115&cid=146996974&t=1&type=0`` 能成功调用，返回的res.code也是200，但第二次获取刷新获取liked状态还是false 没有进行更改。
谢谢

**Comment by Binaryify** [comment]
调用前须知再看一遍吧
