### ISSUE TITLE
登录成功过后我是把什么信息存起来，后面根据这个存的信息来获取用户登录上的接口，比如说每日推荐。还有我喜欢的音乐，就是需要登录的请求的接口

### ISSUE THREAD

**Issue by ZhongHongLi** [Binaryify/NeteaseCloudMusicApi#847]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>

## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
文档里没有吗?

**Comment by ZhongHongLi** [comment]
> 文档里没有吗?



> 文档里没有吗?

文档里貌似没那么详细，就说了需要登录

**Comment by Binaryify** [comment]
我又看了下文档
![image](https://user-images.githubusercontent.com/12221718/87221349-f8392d80-c39d-11ea-9698-d55e89288c53.png)

**Comment by ZhongHongLi** [comment]
> 我又看了下文档
> ![image](https://user-images.githubusercontent.com/12221718/87221349-f8392d80-c39d-11ea-9698-d55e89288c53.png)

意思登录后会自动存一个cookie，我只需要取这个cookie到时候请求带过去，后端就可以知道我是登录过后是吧

**Comment by ZhongHongLi** [comment]
> > 我又看了下文档
> > ![image](https://user-images.githubusercontent.com/12221718/87221349-f8392d80-c39d-11ea-9698-d55e89288c53.png)
> 
> 意思登录后会自动存一个cookie，我只需要取这个cookie到时候请求带过去，后端就可以知道我是登录过后是吧

我发了一个邮件到你的github邮箱里，是我登录成功后，set-cookie 没有设置进去，由于图片只有链接才能回复，我发了个邮箱

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/public/test.html
这里有例子

**Comment by ZhongHongLi** [comment]
> https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/public/test.html
> 这里有例子

好了。就是那个关键的参数  withCredentials: true //关键 带过去cookie就存进去了 。以前是301.感谢了

**Comment by Binaryify** [comment]
嗯嗯

**Comment by ZhongHongLi** [comment]
> 嗯嗯

再次感谢，不用回我了
