### ISSUE TITLE
能否加一个获取全部数字专辑的接口

### ISSUE THREAD

**Issue by owen-debug** [Binaryify/NeteaseCloudMusicApi#852]
谢谢了~

**Comment by Binaryify** [comment]
这个客户端里有吗

**Comment by owen-debug** [comment]
有的，手机客户端，banner图下面有个导航条，向左拉，有个数字专辑，之后点语种风格馆，里面有华语，欧美，韩国，日本的数字专辑，麻烦帮忙看一下呗，谢谢了~

**Comment by Binaryify** [comment]
好，看到了，有时间就弄下

**Comment by owen-debug** [comment]
好的，谢谢开发者~

**Comment by Binaryify** [comment]
已更新数字专辑相关接口~

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/commit/0ad746dad41277b6d9cfb44f941c1b265e34f3d2

**Comment by owen-debug** [comment]
谢谢，谢谢~
