### ISSUE TITLE
评论接口我加了时间戳后还是存在无法实时更新的问题

### ISSUE THREAD

**Issue by lxhcool** [Binaryify/NeteaseCloudMusicApi#855]
点赞评论接口我加了时间戳后还是存在无法实时更新的问题，只有第一次是会实时更新的

**Comment by Binaryify** [comment]
你时间戳每次请求有更新吗

**Comment by lxhcool** [comment]
有的，每次的时间都不一样

**Comment by Binaryify** [comment]
重新步骤提供下

**Comment by lxhcool** [comment]
let timestamp = new Date().getTime()时间戳加的这个

**Comment by Binaryify** [comment]
重现步骤要详细点，不然我只能跟你说我这里没问题

**Comment by lxhcool** [comment]
我刚试了一下好像是ok了，这后面有跟新过嘛

**Comment by Binaryify** [comment]
我更新会有提交记录的，而且你那里也需要重新pull代码
可能是网易那边在弄什么东西
