### ISSUE TITLE
获取视频点赞转发评论数数据接口

### ISSUE THREAD

**Issue by lxhcool** [Binaryify/NeteaseCloudMusicApi#856]
http://localhost:3000/video/detail/info?vid=2DE7E9798C3B02A906A0910A6B62E592
能否加入收藏的数据，和是否已收藏的字段

**Comment by Binaryify** [comment]
有专门的接口,在文档里

**Comment by ilovecanglaoshi** [comment]
有个疑惑，既然`/video/detail/info`这个接口已经返回了是否点赞的数据，为什么不在这个接口里面直接返回是否收藏的信息，为什么不把视频点赞转发收藏的数据放到`/video/detail`这个接口一并返回呢
