### ISSUE TITLE
邮箱登陆成功后。根据ID获取用户信息，返回302，和404

### ISSUE THREAD

**Issue by 498997144** [Binaryify/NeteaseCloudMusicApi#859]
## 出现问题
163邮箱登陆成功后，根据ID发获取用户祥情返回302和404，手机号登陆成功正常的
！createError.js?2d83:16 Uncaught (in promise) Error: Request failed with status code 302
！Uncaught (in promise) Error: Request failed with status code 404

**Comment by Binaryify** [comment]
无法重现
