### ISSUE TITLE
http://m2.music.126.net/SiP1WmKhmLgtKSgXLMlZ-Q==/6652045348116920.mp3无法访问

### ISSUE THREAD

**Issue by rockyhu** [Binaryify/NeteaseCloudMusicApi#86]
### 环境
系统:  
Mac Pro
nodejs 版本:
最新
### 出现问题
搜索下来的歌曲的链接都无法访问了
### 重现步骤
mp3Url: "http://m2.music.126.net/SiP1WmKhmLgtKSgXLMlZ-Q==/6652045348116920.mp3",
在浏览器上访问以上链接出现404错误!
### 期待效果
有什么好的其他替换方案不！

**Comment by u3u** [comment]
> 搜索获取的 `mp3Url` 不能直接用，可通过 `/music/url` 接口传入歌曲 `id` 获取具体的播放链接

用这个接口获取音乐 URL
https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e9%9f%b3%e4%b9%90-url
