### ISSUE TITLE
大佬们可以增加获取歌手的全部歌曲嘛

### ISSUE THREAD

**Issue by xiaou66** [Binaryify/NeteaseCloudMusicApi#864]
目前API 获取歌手单曲 `/artists?id=6452` 功能获取热门50首歌曲

**Comment by denven** [comment]
> 目前API 获取歌手单曲 `/artists?id=6452` 功能获取热门50首歌曲

默认最多获取50首。你可以先获取歌手的所有专辑，然后再获取各专辑下的歌曲。

**Comment by xiaou66** [comment]
这样也是可以，但是在 App 中应该是有所有歌曲的接口

**Comment by xiaou66** [comment]
> > 目前API 获取歌手单曲 `/artists?id=6452` 功能获取热门50首歌曲
> 
> 默认最多获取50首。你可以先获取歌手的所有专辑，然后再获取各专辑下的歌曲。



> > 目前API 获取歌手单曲 `/artists?id=6452` 功能获取热门50首歌曲
> 
> 默认最多获取50首。你可以先获取歌手的所有专辑，然后再获取各专辑下的歌曲。

这样也是可以，但是在 App 中应该是有所有歌曲的接口

**Comment by Binaryify** [comment]
这个接口加上了

**Comment by xiaou66** [comment]
> 这个接口加上了

Thanks♪(･ω･)ﾉ

**Comment by DJAlejandro** [comment]
/artist/songs这个接口是只有移动端有是吗？网页端404
![小Q截图-20200820144543](https://user-images.githubusercontent.com/14656317/90726394-38bc8d00-e2f4-11ea-8277-ae2814742806.png)

**Comment by Binaryify** [comment]
你更新了吗

**Comment by DJAlejandro** [comment]
> 你更新了吗

更新了3.37.2

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/90777150-9ae5b400-e32d-11ea-9d01-a78c88480aeb.png)
