### ISSUE TITLE
歌手分类列表接口返回值是否能添加总条数,用来做分页抓取

### ISSUE THREAD

**Issue by songangweb** [Binaryify/NeteaseCloudMusicApi#866]
以这个请求参数为例:
http://localhost:3000/artist/list?type=1&area=7&initial=a&offset=400&limit=100
实际结果为454条
没有分页的话,这个列表就无法估计抓取的请求次数,
只能每次抓取完,判断是否为空.再停止抓取

**Comment by Binaryify** [comment]
有个more参数,官方也是滚动加载更多的

**Comment by songangweb** [comment]
麻烦能详细说明下吗?   我再咱们文档里没有找到more参数

**Comment by Binaryify** [comment]
more是接口返回的，有这个字段就说明有下一页

**Comment by songangweb** [comment]
好的,谢谢
