### ISSUE TITLE
请求歌手不能返回总个数

### ISSUE THREAD

**Issue by denven** [Binaryify/NeteaseCloudMusicApi#868]
调用  /artist/list 接口 每次返回了limit参数内的数量的数据，但同时希望能返回一个剩余数量或者所有的总个数。
虽然 data 中有一项 more: true/false，但这不利于计算分页总数，如去请求到最后一页才返回一个false将很低效。

因为已有offset了，希望将more改成total或count即可，其他情况均可以计算。

**Comment by Binaryify** [comment]
官方返回的就是这样的

**Comment by denven** [comment]
> 官方返回的就是这样的

我看了一下代码，确实是你说的这样。

还有一些其他接口，也不是太完好。例如：有些可以按category或者type, area请求数据，返回的数据里面有个字段记录总数，但这个数字一直不变，是不分类的总数。按理说，分类变了，类型变了，返回的总数应该是当前类别的总数才更合理。

**Comment by Binaryify** [comment]
没办法,网易那边有些接口就是这样的,还有些字段啥的也不是很统一
