### ISSUE TITLE
歌单／歌曲详情JSON property minified

### ISSUE THREAD

**Issue by zhuhan0** [Binaryify/NeteaseCloudMusicApi#87]
### 环境
系统:  
ubuntu 16.04 LTS
nodejs 版本:
7.10.0
### 出现问题
获取歌单／歌曲详情，返回JSON property被minified。如下：
![screenshot from 2017-08-18 21-48-02](https://user-images.githubusercontent.com/17732499/29482427-f8cbf6e6-845e-11e7-98de-a03db1409141.png)
### 重现步骤
搜索任何歌单或歌曲详情。
### 期待效果
Property不缩写。

**Comment by Binaryify** [comment]
能再具体描述问题吗

**Comment by zhuhan0** [comment]
看不出JSON包含了什么信息。例如这张图里，t, tns, st, rt这些属性。我不知道为什么会这样，文档上的例子明明不是缩写的。。

**Comment by Binaryify** [comment]
官方返回的结果就是这样的,我只做转发处理,字段可能会有变化的

**Comment by zhuhan0** [comment]
你那边返回的也是这样吗？另外请问官方的API在哪能找到？

**Comment by Binaryify** [comment]
是,官方的没有公布,现有的都是被网友摸索出来的

**Comment by zhuhan0** [comment]
ok... thanks!
