### ISSUE TITLE
/simi/artist 请求相似歌手时出现 301 错误

### ISSUE THREAD

**Issue by denven** [Binaryify/NeteaseCloudMusicApi#877]
[ERR] /simi/artist?id=7063 { status: 301, body: { msg: 'system error!', code: 301 } }
[ERR] /simi/artist?id=768208 { status: 301, body: { msg: 'system error!', code: 301 } }

貌似是官方API没响应？

**Comment by Binaryify** [comment]
登录了吗

**Comment by chenchunyang123** [comment]
我也遇到了这个问题，但是网易云官方的程序没有登录也能获取相似歌手，这个实现的接口需要强制登录吗

**Comment by DJAlejandro** [comment]
![小Q截图-20200815144836](https://user-images.githubusercontent.com/14656317/90307192-a89ed200-df06-11ea-9e5e-99d68b20c5ff.png)



需要登录

**Comment by Binaryify** [comment]
这个接口本来就需要登录的,客户端写死了MUSIC_A

**Comment by Binaryify** [comment]
加了匿名登录了
