### ISSUE TITLE
潜在的apicache缓存问题，虽然目前几乎不会触发

### ISSUE THREAD

**Issue by huhuime** [Binaryify/NeteaseCloudMusicApi#88]
### 环境
系统:  win7 x64

nodejs 版本:v6.3.0

### 出现问题
apicache本身bug 判断200来决定是否缓存是无效的（执行判断代码位置错了），有人已经提交了问题 https://github.com/kwhitley/apicache/issues/96
这个情况再NeteaseCloudMusicApi 状态码非200直接死循环了，请求超时直接服务崩溃（网易云服务器太好了很难遇到超时，遇到只有本地测试网络太差了）
当时修改这两个情况的时候就会遇到
也就是加上了重试次数和在`http.request(...)`后面补上`.on('error' err=>{....})`
这两操作后再次测试非200和超时就会遇到apicache死活都缓存bug
### 重现步骤
将music.163.com 指向不存在的ip，并修改util.js接受超时异常
### 期待效果
修改死循环和超时处理后非200和超时均不缓存

### 解决方法
修改apicache（我没想到更好的不修改apicache且不等apicache更新的解决方法）
在apicache.js里的shouldCacheResponse 追加middlewareToggle并执行middlewareToggle的内容（为了传递参数还需要修改makeResponseCacheable）

### 结尾
所以这种约等于0%概率触发的bug还修么？还是不修，等apicache 更新下一版本么？

**Comment by Binaryify** [comment]
目前看 apicache 维护还算积极,还是等他们上游修复bug吧

**Comment by kwhitley** [comment]
Fixed in [apicache v0.11.1](https://www.npmjs.com/package/apicache) (releasing to NPM  tonight)

**Comment by Binaryify** [comment]
@kwhitley 
wow, thanks for the fixed
