### ISSUE TITLE
文档网站找不到服务器IP地址？

### ISSUE THREAD

**Issue by Benleie** [Binaryify/NeteaseCloudMusicApi#882]
没法访问文档了

**Comment by Binaryify** [comment]
你这啥信息都不给,我只能跟你说我这里没问题
![image](https://user-images.githubusercontent.com/12221718/90315085-1c62ce00-df4b-11ea-87ca-c6c6dcf2330a.png)

**Comment by Benleie** [comment]
好的，谢谢回复。
我这边两个浏览器都突然访问不到了，那可能是我电脑DNS暂时出问题了。
