### ISSUE TITLE
你们是怎么得到或者计算歌曲时长的啊，就是歌曲列表显示的那个时长

### ISSUE THREAD

**Issue by crawler-ww** [Binaryify/NeteaseCloudMusicApi#886]
![捕获](https://user-images.githubusercontent.com/53415213/90373583-b427ff80-e0a4-11ea-9ab4-bb4a67613d6b.jpg)

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/issues?q=%E6%97%B6%E9%95%BF
