### ISSUE TITLE
接口地址 : /user/playlist 无法完整获取用户创建(公开)的歌单和收藏的歌单

### ISSUE THREAD

**Issue by Beattheend** [Binaryify/NeteaseCloudMusicApi#887]
## 环境
- 系统/平台: <你的系统和平台>
Linux/CentOS
- nodejs 版本: <你的 NodeJS 版本号>
12.18.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.38.0
## 出现问题
接口地址 : /user/playlist 无法获取全部用户歌单和收藏

## 重现步骤
直接访问 接口

## 期待效果
获取全部用户公开创建的歌词和收藏的歌单 

测试用户 UID  325436573
接口 /user/playlist 获取的用户歌单 创建的歌单是公开的且歌单内有歌曲存在 但无法完全获取全部歌单
且 测试用户 UID  325436573  的收藏歌单也不能获取。

**Comment by Binaryify** [comment]
那个接口支持limit和offset分页，文档漏写了
