### ISSUE TITLE
请教刷新登录的疑问

### ISSUE THREAD

**Issue by sandmanman** [Binaryify/NeteaseCloudMusicApi#89]
>刷新登录
>说明:调用此接口,可刷新登录状态
>调用例子:
>/login/refresh

请教，刷新登录接口是做什么用的，文档说是刷新登录状态，是刷新浏览器是否存在Cookie '__csrf' 吗，还是？

**Comment by RanBasara** [comment]
同一个问题~  
登陆这一块还是没有太懂。

**Comment by Binaryify** [comment]
@sandmanman 
@RanBasara 
刷新这一块是收集网上的,现在发现是有问题的,感谢提醒,刚更新了代码
现在代码逻辑是发送现有 cookie 到接口,接口再返回新 cookie,然后覆盖原有 cookie,从而达到刷新登录状态的效果
