### ISSUE TITLE
讨论：支持 TypeScript 的类型注解

### ISSUE THREAD

**Issue by greenhat616** [Binaryify/NeteaseCloudMusicApi#891]
## 起因

现在的 Module 还没有一套能使用的类型注解，这对于使用 TypeScript 的同学带来诸多不便。

## 目的

1.  得出对应接口的响应结构
2.  得出参数，响应结构非常见的坑

如果讨论顺利的话，我可以提交 PR 以支持 @types

**Comment by Binaryify** [comment]
不怕麻烦的话可以加

**Comment by greenhat616** [comment]
好，等我回来我就启动这项工作。

**Comment by greenhat616** [comment]
草案: #908 ，当工作完成时，将标记为可合并

**Comment by Binaryify** [comment]
好

**Comment by greenhat616** [comment]
@Binaryify https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/avatar_upload.js 这个接口有办法在node端使用嘛，有的话例子能不能给一个呢

**Comment by greenhat616** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/module/playlist_cover_update.js 同样的，还有这个接口涉及上传

**Comment by Binaryify** [comment]
```
const { avatar_upload, login_cellphone } = require('./main')
const fs = require('fs')
const path = require('path')

async function main() {
  const result = await login_cellphone({
    phone: '手机号',
    password: '密码'
  })
  const filePath = './test.jpg'
  avatar_upload({
    imgFile: {
      name: path.basename(filePath),
      data: fs.readFileSync(filePath)
    },
    cookie: result.body.cookie
  })
}
main()
```

**Comment by Binaryify** [comment]
https://github.com/Binaryify/NeteaseCloudMusicApi/tree/master/module_example
更新了案例

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/92302297-b263a480-ef9d-11ea-98ab-45f5f8c7e14e.png)

**Comment by Binaryify** [comment]
俩上传接口上传参数和返回结果内容大同小异

**Comment by greenhat616** [comment]
好，稍晚我更新下这两个接口的注解

**Comment by Binaryify** [comment]
好~
