### ISSUE TITLE
希望添加获取VIP音乐试用接口

### ISSUE THREAD

**Issue by Beattheend** [Binaryify/NeteaseCloudMusicApi#897]
将VIP歌曲分享到QQ后无法直接播放且需要进入网页后才能试用歌曲片段，那么可以获取到这个试听的片段吗？
同时获取VIP音乐分享的封面 例如：[https://external-30160.picsz.qpic.cn/a4d49193dc7247823eaf3f72a8f64072/jpg1](https://external-30160.picsz.qpic.cn/a4d49193dc7247823eaf3f72a8f64072/jpg1)
## 期待效果
获取到VIP歌曲的试听片段，获取VIP歌曲分享的封面。

**Comment by Binaryify** [comment]
接口已更新
