### ISSUE TITLE
访问后端接口报证书错误，request.js加入：strictSSL=false，接口通了，但是单元测试过不了，返回非JSON数据

### ISSUE THREAD

**Issue by mebest100** [Binaryify/NeteaseCloudMusicApi#898]
![image](https://user-images.githubusercontent.com/11530991/90996968-c5b45e80-e5f2-11ea-9c68-0fd81d3d804a.png)

**Comment by Binaryify** [comment]
这证书是你电脑上的

**Comment by mebest100** [comment]
不是吧，我根本就没有引用证书，而且本地也没有证书

**Comment by mebest100** [comment]
之前访问测试接口直接报502错误，然后google查到在util/request.js文件中加入restrictSSL= false
![image](https://user-images.githubusercontent.com/11530991/91010852-d7f3c400-e615-11ea-9e1a-835defbaa398.png)

于是修改request.js文件，重新测试，接口通了，但是单元测试过不了，返回非JSON数据：
![image](https://user-images.githubusercontent.com/11530991/91011069-3751d400-e616-11ea-8201-534fdc71ca62.png)

然后直连https://music.163.com/接口，发现：
1. 原厂证书确实有问题
2. 直连接口无法调用，报404

是不是网易云音乐的API现在已经不能用了?
![image](https://user-images.githubusercontent.com/11530991/91011242-88fa5e80-e616-11ea-836b-78c84a6ab51f.png)

**Comment by mebest100** [comment]
卧槽，找到原因了，原来是路由器openwrt的解锁网易云音乐导入了自签证书的原因，开启了解锁网易云音乐就会这样。

害得我迎着头皮死啃你的nodejs源码，把request.js都给研究透了，也算有点收获

**Comment by Binaryify** [comment]
解决了就好
