### ISSUE TITLE
想请问一下如何区分vip, 已经下架, 或者还有其他无法获取的类型.

### ISSUE THREAD

**Issue by lenohard** [Binaryify/NeteaseCloudMusicApi#899]
歌曲详情里有个 fee
比如:
[{'name': '明明就',
  'id': 25641369,
  'pst': 0,
  't': 0,
  'ar': [{'id': 6452, 'name': '周杰伦', 'tns': [], 'alias': []}],
  'alia': [],
  'pop': 100,
  'st': 0,
  'rt': '600902000009525160',
  **_'fee': 0,_**
  'v': 137,
  'crbt': None,
  'cf': '',
  'al': {'id': 2263029,
   'name': '十二新作',
   'picUrl': 'https://p2.music.126.net/oL_TYdmT9mm_erNZb187_g==/109951163533013578.jpg',
   'tns': [],
   'pic_str': '109951163533013578',
   'pic': 109951163533013580},
  'dt': 260386,
  'h': {'br': 320000, 'fid': 0, 'size': 10417676, 'vd': 0},
  'm': {'br': 192000, 'fid': 0, 'size': 6250623, 'vd': 0},
  'l': {'br': 128000, 'fid': 0, 'size': 4167097, 'vd': 0},
  'a': None,
  'cd': '1',
  'no': 4,
  'rtUrl': None,
  'ftype': 0,
  'rtUrls': [],
  'djId': 0,
  'copyright': 1,
  's_id': 0,
  'mark': 0,
  'originCoverType': 0,
  'single': 0,
  'noCopyrightRcmd': None,
  'mv': 0,
  'mst': 9,
  'cp': 1007,
  'rtype': 0,
  'rurl': None,
  'publishTime': 1356624000007}]

我发现fee有四种情况, 0, 1, 4, 8. 
为8时是可以正常访问的, 为1的是肯定不能获取的, 为1的是有的可以有的不可以.
如何从歌曲详情的信息里判断音乐为vip或者已下架或者其他不可获取的类型呢?

**Comment by DJAlejandro** [comment]
privilege.fee
8、0：免费
4：所在专辑需单独付费
1：VIP可听
privilege.cs:云盘
privilege.st：-200无版权

**Comment by lenohard** [comment]
🆗，完美， 多谢

**Comment by refuse-c** [comment]
> privilege.fee
> 8、0：免费
> 4：其中专辑需要单独投标
> 1：VIP可听
> privilege.cs：云盘
> privilege.st：-200无版权


请问一下  这个sq是通过那个字段进行判断的
![QQ截图20200917142211](https://user-images.githubusercontent.com/38646454/93427936-36e4ea00-f8f1-11ea-82bc-9d4625c69e3a.png)

**Comment by refuse-c** [comment]
> privilege.fee
> 8、0：免费
> 4：所在专辑需单独付费
> 1：VIP可听
> privilege.cs:云盘
> privilege.st：-200无版权

找到了  QAQ    取item.dl===999000     就代表是sq的
