### ISSUE TITLE
php处理返回的信息

### ISSUE THREAD

**Issue by 2659494057** [Binaryify/NeteaseCloudMusicApi#900]
## 出现问题
phpcurl，访问http://127.0.0.1:3000/search?keywords=海阔天空，返回信息如下：
Array
(
    [result] => Array
        (
            [songCount] => 0
        )

    [code] => 200
)
phpcurl，访问http://127.0.0.1:3000/search?keywords=lifeline，返回的信息与搜索内容匹配

phpcurl访问，搜索内容为英文字符，返回的结果正常；搜索内容为中文字符，返回的结果与搜索内容不匹配。
不通过php，直接访问http://127.0.0.1:3000/search?keywords=lifeline均是正常的

## 重现步骤
header("Content-Type:application/json;charset=utf-8");
$wb=$_GET["wb"];
$url="http://127.0.0.1:3000/search?limit=10&keywords=$wb";
$curl=curl_init();
curl_setopt($curl,CURLOPT_URL,$url);
curl_setopt($curl,CURLOPT_SSL_VERIFYPEER,FALSE);
curl_setopt($curl,CURLOPT_SSL_VERIFYHOST,FALSE);
curl_setopt($curl,CURLOPT_RETURNTRANSFER,1);
$sc=curl_exec($curl);
curl_close($curl);
$json=json_decode($sc,ture);
print_r($json);

## 期待效果
php可以处理返回的信息

**Comment by greenhat616** [comment]
- - 这个不是你的php基础该做的么..... 你把传入字符 urlEncode 一下不就好了
