### ISSUE TITLE
获取音乐url接口问题

### ISSUE THREAD

**Issue by huihuilovekuikui** [Binaryify/NeteaseCloudMusicApi#902]
/song/url
这个接口文档里写着传入id获取url,可是无论我传入什么id,确定已经不是vip歌曲,得到的url都是为空
![image](https://user-images.githubusercontent.com/66559869/91196371-a15c9d00-e72c-11ea-9442-39afc57773d4.png)
导致我无法获取播放地址

**Comment by Binaryify** [comment]
你的id错了吧
例子：http://localhost:3000/song/url?id=33894312

**Comment by huihuilovekuikui** [comment]
> 你的id错了吧
> 例子：http://localhost:3000/song/url?id=33894312
今天早上发现了,全部用成了专辑的id,确实是id错了
