### ISSUE TITLE
新歌速递不能使用分页???

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#909]
## 环境
环境都是最新的  

看了你的代码

top_song.js 下的代码这2行是注释了的  我自己在我本地放开了(服务已经重启过了) 但是还是不得行  emm  是不是不支持哇  

    limit: query.limit || 100,
    offset: query.offset || 0,
    

直接上个图吧  
![image](https://user-images.githubusercontent.com/38646454/92061578-3a448580-edc9-11ea-8acf-36eb7b46c044.png)

**Comment by Binaryify** [comment]
返回内容没有more的都是不支持分页的

**Comment by refuse-c** [comment]
好的 , 了解了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: binaryify <notifications@github.com>
发送时间: Thursday, September 3, 2020 9:42:33 AM
收件人: Binaryify/NeteaseCloudMusicApi <NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh <xiangbh@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 新歌速递不能使用分页??? (#909)


返回内容没有more的都是不支持分页的

―
