### ISSUE TITLE
如何设置可以返回https的图片链接

### ISSUE THREAD

**Issue by zhongjun96** [Binaryify/NeteaseCloudMusicApi#910]
## 环境

- nodejs 版本: 14.9

- API版本:3.39.0

## 出现问题
获取的图片为http格式，导致网站使用了https也标示为不安全
![image.png](https://i.loli.net/2020/09/03/gwmZABoUvOHqSbF.png)

## 期待效果
如何可以获取到https格式的图片？检查直接添加s是可以正常访问的

![image.png](https://i.loli.net/2020/09/03/xtI3jhNL6zvX59q.png)

**Comment by Binaryify** [comment]
这个接口返回的就是这样,可以正则替换下http
