### ISSUE TITLE
music/url无法正常获取到url

### ISSUE THREAD

**Issue by rockyhu** [Binaryify/NeteaseCloudMusicApi#92]
### 环境
系统:  
Mac pro

nodejs 版本:
最新版

### 出现问题
直接访问http://music.163.com/api/music/url?id= 299981无法获取到数据

### 重现步骤
![image](https://user-images.githubusercontent.com/15012307/29503270-c3053430-8668-11e7-84de-f0df10f564cf.png)
### 期待效果
希望能够提供一下原生的访问链接，正常获取到url的

**Comment by u3u** [comment]
请求自己的 Node 服务而不是直接请求网易云
