### ISSUE TITLE
Windows平台下运行的问题

### ISSUE THREAD

**Issue by DoveBoy** [Binaryify/NeteaseCloudMusicApi#920]
## 环境
- 系统/平台: Windows

- nodejs 版本: 14.10.0

- API版本:3.39.0

## 出现问题
完全不知道怎么用，浏览器登录后的页面点击例子都是代码

## 重现步骤
已经用nodejs搭建好了平台，Powershell下运行app.js也出现了地址http://localhost:3000，浏览器登录后显示正常，但是之后不知道怎么用，请开发者解答一下Windows下怎么用

## 期待效果
感觉没有出现想象中的web界面，完全不知道怎么用，例子里面的链接点进去都是一串代码，没有出现ui界面

![image](https://user-images.githubusercontent.com/19201447/92602843-4062c680-f2e1-11ea-856f-5b99f9b51a85.png)
![image](https://user-images.githubusercontent.com/19201447/92602884-48bb0180-f2e1-11ea-9f97-ca36a4e41fa5.png)
![image](https://user-images.githubusercontent.com/19201447/92602959-5c666800-f2e1-11ea-96fb-74f7a944fc4a.png)

**Comment by greenhat616** [comment]
这本来就是 API 不是 APP。。。。怎么可能有 UI

**Comment by DoveBoy** [comment]
> 这本来就是 API 不是 APP。。。。怎么可能有 UI

那如果搭建出来api后，可以做什么用？小白不是太懂这个

**Comment by greenhat616** [comment]
https://www.zhihu.com/answer/487039892



---原始邮件---
发件人: "DoveBoy"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 上午8:20
收件人: "Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送: "Jonson Petard"<i@a632079.me&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [Binaryify/NeteaseCloudMusicApi] Windows平台下运行的问题 (#920)




  
这本来就是 API 不是 APP。。。。怎么可能有 UI
  
那如果搭建出来api后，可以做什么用？小白不是太懂这个
