### ISSUE TITLE
如何区分当前cat下有无精品歌单

### ISSUE THREAD

**Issue by refuse-c** [Binaryify/NeteaseCloudMusicApi#921]
遇见一个问题不晓得怎么解决 
就是通过什么字段判断当前`cat`下有无精品歌单

就比如说我通过获取精品歌单`/top/playlist/highquality`的接口获取**华语**的歌单是有精品歌单的  但是获取**雷鬼**的就没有数据 
我查看了获取`cat`的接口(`/playlist/catlist`) 也没看出有什么区别    附几张截图吧 
![QQ截图20200910013343](https://user-images.githubusercontent.com/38646454/92634140-69e21900-f306-11ea-8926-0d83bcd1d9ea.png)
![QQ截图20200910013428](https://user-images.githubusercontent.com/38646454/92634146-6babdc80-f306-11ea-96d4-46db156ccfc5.png)
![QQ截图20200910013533](https://user-images.githubusercontent.com/38646454/92634174-78303500-f306-11ea-9982-f123f3ce8e59.png)
![QQ截图20200910013546](https://user-images.githubusercontent.com/38646454/92634178-79f9f880-f306-11ea-8248-8bb8607fb848.png)

![QQ截图20200910013307](https://user-images.githubusercontent.com/38646454/92634130-6484ce80-f306-11ea-865c-492c3e928369.png)
![QQ截图20200910013321](https://user-images.githubusercontent.com/38646454/92634134-677fbf00-f306-11ea-82fa-4773ae32e7fd.png)

**Comment by Binaryify** [comment]
我升级下接口吧

**Comment by Binaryify** [comment]
已更新

**Comment by refuse-c** [comment]
谢谢大佬   每次都是有求必应 !!


发件人: binaryify<mailto:notifications@github.com>
发送时间: 2020年9月19日 18:50
收件人: Binaryify/NeteaseCloudMusicApi<mailto:NeteaseCloudMusicApi@noreply.github.com>
抄送: xiangbh<mailto:xiangbh@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Binaryify/NeteaseCloudMusicApi] 如何区分当前cat下有无精品歌单 (#921)


已更新

―
