### ISSUE TITLE
用户的等级页面里的到达下一个等级还剩多少的数据在用户详情数据里没有

### ISSUE THREAD

**Issue by shangsheng** [Binaryify/NeteaseCloudMusicApi#929]
## 环境
- 系统/平台: <你的系统和平台>
pc
- nodejs 版本: <你的 NodeJS 版本号>
v12.13.0

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.39.0
## 出现问题
<出现的问题>
用户的等级页面里的到达下一个等级还剩多少的数据在用户详情数据里没有
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  
在用户详情数据里添加需要听歌多少首以及需要登陆多少天，以及听歌多少首的数据

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
我加个接口吧

**Comment by Binaryify** [comment]
已更新

**Comment by shangsheng** [comment]
@Binaryify 大神，pc端首页榜单下的收藏调用
![image](https://user-images.githubusercontent.com/26435134/94217503-c2273680-ff14-11ea-94b1-466c3f411456.png)这个接口报501错误
![image](https://user-images.githubusercontent.com/26435134/94217548-dbc87e00-ff14-11ea-9453-d4ccaa254d8f.png)在排行榜页面调用时没有问题的，是因为什么原因呢

**Comment by shangsheng** [comment]
知道原因了是收藏之后之后没有进行其他操作，再次收藏了。能不能已经收藏的内容再次点击收藏时返回个参数啊

**Comment by Binaryify** [comment]
收藏完你得刷新下列表

**Comment by shangsheng** [comment]
好吧，谢谢了
