### ISSUE TITLE
登录接口网易云好像不记录登录天数

### ISSUE THREAD

**Issue by Cloud370** [Binaryify/NeteaseCloudMusicApi#936]
## 环境
- 系统/平台: <你的系统和平台>
win10
- nodejs 版本: <你的 NodeJS 版本号>
最新版
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
最新版
## 出现问题
<出现的问题>
自己写了个用来挂机升级的，听歌网易云可以正常统计，但是用手机号登录的接口网易云似乎不记录。
## 重现步骤
<重现步骤>
直接require的login_cellphone.js
 cookie可以正常返回也可以正常使用 但是网易云记录的登录天数没有动。
## 期待效果
<现在的效果，期待的效果>  

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
登录天数应该是埋点接口处理的,但是我也不知道是哪一个

**Comment by Cloud370** [comment]
> 登录天数应该是埋点接口处理的,但是我也不知道是哪一个

是不是那个feedback/weblog呀 我写了个模块明天看看效果

**Comment by Binaryify** [comment]
应该是那个,但是参数不好找

**Comment by Cloud370** [comment]
> 应该是那个,但是参数不好找

![image](https://user-images.githubusercontent.com/46866207/93905234-5040c880-fd2d-11ea-96de-28a8890866d5.png)
折腾了一下 不太会 参数是不是这个呀？

**Comment by Binaryify** [comment]
不是那个，那个是专辑的埋点

**Comment by Cloud370** [comment]
> 思路是对的，但是参数不是那个，那个是专辑的埋点

按道理来说，不应该是有了log就算登录吗 还是说要准确的 好像登录的时候就全是banner的

**Comment by Cloud370** [comment]
> 思路是对的，但是参数不是那个，那个是专辑的埋点

按道理来说不应该是记录有就算了吗 我靠 太变态了吧 大佬真的没办法了吗

**Comment by Binaryify** [comment]
应该不是，官方很多操作都会触发weblog

**Comment by Cloud370** [comment]
> 应该不是，官方很多操作都会触发weblog

那咋办呀~大佬秋秋了 整一个吧 太难了 自从用了你的接口之后就飘了 我小号都快十级了😙

**Comment by Binaryify** [comment]
周末看看能不能找到吧

**Comment by Binaryify** [comment]
登录天数是不是按签到算的

**Comment by Cloud370** [comment]
> 登录天数是不是按签到算的，我的10级忘了之前是不是点签到升上去的

我大号我记得两年前就签到满了，听歌一直不够，一年了才升一级哈哈哈

> 周末看看能不能找到吧

谢谢大佬！

**Comment by Binaryify** [comment]
https://www.bilibili.com/read/cv6926598/
试试这个

**Comment by Cloud370** [comment]
> https://www.bilibili.com/read/cv6926598/
> 试试这个

他这几条请求好像都加不了天数吧？

**Comment by Cloud370** [comment]
> 周末看看能不能找到吧

咋样大佬~我实在找不到 好像你给我推那个也不管用

**Comment by Binaryify** [comment]
这个我还得再看看

**Comment by Binaryify** [comment]
应该是网易把策略改了，之前的方法都失效了，还得重新抓包看看

**Comment by Binaryify** [comment]
试试这个
https://github.com/Secriy/CloudMusic-LevelUp
应该就是调签到接口的

**Comment by Cloud370** [comment]
> 试试这个
> https://github.com/Secriy/CloudMusic-LevelUp
> 应该就是调签到接口的

https://github.com/Secriy/CloudMusic-LevelUp/blob/9c8fecef2279071b13a17d77ab1deaef389b894f/action.py#L187
这条weblog吗

**Comment by yushuohuanxiu** [comment]
> > 试试这个
> > https://github.com/Secriy/CloudMusic-LevelUp
> > 应该就是调签到接口的
> 
> https://github.com/Secriy/CloudMusic-LevelUp/blob/9c8fecef2279071b13a17d77ab1deaef389b894f/action.py#L187 这条weblog吗

你好，请问此问题有解决方案了吗？

**Comment by Binaryify** [comment]
@yushuohuanxiu 
用这个库吧
https://github.com/chen310/NeteaseCloudMusicTasks
