### ISSUE TITLE
启动进不了主页

### ISSUE THREAD

**Issue by zhangmingzhong619** [Binaryify/NeteaseCloudMusicApi#937]
请问怎么进到主页呢 项目跑起来进的是一个

![9L6C67LM_1$Y8CESX)CU{Q7](https://user-images.githubusercontent.com/58554048/93544458-b8d82000-f990-11ea-90ba-e751e0110352.png)
这个页面

**Comment by Binaryify** [comment]
你先搞清楚这个项目是做什么的吧
