### ISSUE TITLE
获取精品歌单标签列表返回’Cannot GET /playlist/highquality/tags‘

### ISSUE THREAD

**Issue by CitronsBlog** [Binaryify/NeteaseCloudMusicApi#943]
## 环境
- 系统/平台: windows

- nodejs 版本: 12.18.4

- API版本:3.40.1

## 出现问题
获取精品歌单标签列表返回’Cannot GET /playlist/highquality/tags‘

## 重现步骤
无

## 期待效果
希望能够成功获取到歌单标签列表

**Comment by Binaryify** [comment]
![Uploading image.png…]()

**Comment by CitronsBlog** [comment]
![error3](https://user-images.githubusercontent.com/41941990/94096899-d9541e80-fe57-11ea-8503-a092e97dcad9.png)
![error2](https://user-images.githubusercontent.com/41941990/94096910-dfe29600-fe57-11ea-94d3-3e2a09e98974.png)
![error1](https://user-images.githubusercontent.com/41941990/94096915-e3761d00-fe57-11ea-9154-c3e6ab0a70ae.png)

**Comment by Binaryify** [comment]
我也想知道怎么不更新项目就能调新加的接口
