### ISSUE TITLE
登录成功之后获取登录状态依旧是需要登录,但是可以获取数据

### ISSUE THREAD

**Issue by Bk24MamBa** [Binaryify/NeteaseCloudMusicApi#944]
## 环境
- 系统/平台: <你的系统和平台>
windows
- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
<出现的问题>
登录成功之后获取登录状态依旧是需要登录,但是可以获取数据
## 重现步骤
<重现步骤>

## 期待效果
<现在的效果，期待的效果>  

我是用axios的，withCredentials: true也加上去了。小白一枚，谢谢哥哥姐姐们。

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Bk24MamBa** [comment]
问题应该是跨域请求默认不能携带cookie,怎么解决呢?

**Comment by Binaryify** [comment]
代码里有例子
