### ISSUE TITLE
阿里云香港 ECS 服务器，启用 X-Real-IP，ip 访问可用，域名访问不可用。

### ISSUE THREAD

**Issue by zyw5791557** [Binaryify/NeteaseCloudMusicApi#95]
### 环境
系统:  
Cent OS 7.2 64位
nodejs 版本:
v6.11.2
### 出现问题
服务器在香港，已经设置 X-Real-IP ，但是如果ip访问没问题，如果使用域名访问还是听不了，求解求解~~~

### 重现步骤
[ip访问可用](http://47.91.235.103/xly?id=418603077&musicName=%u544A%u767D%u6C14%u7403-%u5468%u6770%u4F26)
[域名访问不可用](http://emlice.top/xly?id=418603077&musicName=%u544A%u767D%u6C14%u7403-%u5468%u6770%u4F26)
### 期待效果
效果一致。

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/29609000-662db248-8828-11e7-9088-5a86c84b1c8f.png)
我这里访问你带域名的那个 url 很正常

**Comment by zyw5791557** [comment]
@Binaryify 又行了，奇怪，刚非得ip访问，或者把链接复制出来新标签打开才能使用，谢啦，感谢提供API。

**Comment by Binaryify** [comment]
@zyw5791557 
不客气
