### ISSUE TITLE
API结果时好时坏

### ISSUE THREAD

**Issue by liumin1128** [Binaryify/NeteaseCloudMusicApi#96]
### 环境
系统:   mac 

nodejs 版本:  6.11.2

### 出现问题
API结果时好时坏，有时候正常，有时候404，基本上几分钟有一次访问正常，过一会就404，再过一会又好了。

### 重现步骤
正常操作即可发现

### 期待效果
一直显示正常

**Comment by Binaryify** [comment]
请正确提供详细的环境和重现步骤并配上截图,因为目前只有你反馈偶现 404

**Comment by stoneWeb** [comment]
@liumin1128 有可能是代理的问题吧，你有安装什么浏览器插件吗，unblock youku之类的东西
