### ISSUE TITLE
需要登录的接口都返回301，在issues搜过了。还是解决不了

### ISSUE THREAD

**Issue by yqwertb** [Binaryify/NeteaseCloudMusicApi#961]
## 环境
- 系统/平台: win10  vue axios

- nodejs 版本:  v12.16.1

- API版本: 3.42.3

## 出现问题
在浏览器直接访问需要登录的接口可以正常访问（如 签到），但是在项目中就返回301 
axios 设置了withCredentials: true 也尝试过添加时间戳 重启服务也不行

>
![Snipaste_2020-10-06_23-42-35](https://user-images.githubusercontent.com/50364829/95224913-cf55f680-082d-11eb-8c19-f0be693c465d.png)

![Snipaste_2020-10-06_23-42-44](https://user-images.githubusercontent.com/50364829/95224882-c8c77f00-082d-11eb-9794-086d1c2adcd0.png)

**Comment by Binaryify** [comment]
你手动传cookie吧

**Comment by rayshaan** [comment]
一样，请问解决了吗

**Comment by yqwertb** [comment]
> 一样，请问解决了吗

只要接口和网页同源就没啥问题 我把接口部署到域名的3000端口上了

**Comment by hwy2** [comment]
@yqwertb 请问是vue做的前端项目吗，我部署之后也是这个问题，不太理解你说的网页同源怎么操作

**Comment by yqwertb** [comment]
> @yqwertb 请问是vue做的前端项目吗，我部署之后也是这个问题，不太理解你说的网页同源怎么操作

我说的不太准确，因为端口不一样不是同源。就比如我的项目的链接是 baidu.com  接口就baidu.com:3000 这样我就没再出现报错了

**Comment by hwy2** [comment]
> 
> 
> > @yqwertb 请问是vue做的前端项目吗，我部署之后也是这个问题，不太理解你说的网页同源怎么操作
> 
> 我说的不太准确，因为端口不一样不是同源。就比如我的项目的链接是 baidu.com 接口就baidu.com:3000 这样我就没再出现报错了

我也搞定了，也是像你这样，不过我是主域名：5005端口做接口，二级域名做的项目，但指向的都是同一IP地址就没报错，本地项目运行还是会，这个就不知道怎么解决

**Comment by acanzaima** [comment]
这个问题的话，axios首先是要设置允许发送cookie的
```
axios.defaults.withCredentials = true;
```
然后，如果vue项目运行在本地localhost时，网易云接口也要运行在localhost，如果vue项目使用192.168.0.xxx运行，那么网易云接口也要运行在192.168.0.xxx的地址下，端口都是默认的没有问题，同理，在服务器上也是。
***
简单来说，vue项目和网易云接口api如果一者使用本地localhost加端口运行，另外一者使用局域网ip192.168.0.xxx加端口运行时，当我们登录时，后端虽然正确返回了cookie值，但到达浏览器以后，浏览器认为这是第三方cookie，会对其加以限制，最终cookie值并未存储在浏览器的Application—cookies—对应的主机地址/域名下，因此我们在使用需要登录的接口时，哪怕你设置了携带cookie发送，当然也是最终并没有带上任何cookie，最终当然是301需要登录啦。
***
之所以会限制是因为浏览器的samesite属性，chrome从51开始引入，用来防止csrf攻击，可以查看阮一峰老师的这篇文章“[Cookie 的 SameSite 属性](http://www.ruanyifeng.com/blog/2019/09/cookie-samesite.html)”
***
按理来说即使vue项目运行在本地localhost:8080并且网易云接口运行在本地localhost:3000也是属于跨域的，但最终运行却没有问题，而一者localhost一者局域网192.168.0.xxx就会遭到浏览器的限制，莫非跨域是有等级之分的？在浏览器看来，前者不严重？后者太严重？

**Comment by qiuniang6943** [comment]
我和你的问题一模一样，你解决了吗

**Comment by qiuniang6943** [comment]
我通过手动发送cookie解决了，直接get方式在url发送就可以
我是将登录成功返回的cookie手动保存到了localstorage里
希望对你有帮助
`url: `/login/status?cookie=${localStorage.getItem('Cookie')}&timestamp=${Date.now()}`,`

**Comment by yqwertb** [comment]
@qiuniang6943  感谢 我暂时没问题了 api和项目地址在同一ip下就没啥事了 后面我可以试试手动传cookie

**Comment by lzzqwe** [comment]
大佬牛逼 @acanzaima

**Comment by EightDoor** [comment]
顺利解决了  
```javascript
url: `/login/status?cookie=${localStorage.getItem('Cookie')}&timestamp=${Date.now()}`,
```
