### ISSUE TITLE
关于对歌单评论点赞的延迟时间问题

### ISSUE THREAD

**Issue by 1144790758** [Binaryify/NeteaseCloudMusicApi#969]
## 环境
- 系统/平台: <你的系统和平台>
windows  
- nodejs 版本: <你的 NodeJS 版本号>
v12.18.3
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
"version": "3.42.4"
## 出现问题
<出现的问题>
收藏的别人的歌单,对其下面的评论点赞
点赞后再次访问评论数据,点赞数量的变化需要一定时间后才能发现
相比官网的延迟有点大啊,官网点赞基本没有延迟
## 重现步骤
<重现步骤>
http://localhost:3000/like?id=2395304063&cid=1353178915&t=1&type=2&timestamp=1602509473282
## 期待效果
<现在的效果，期待的效果>  
现在的效果延迟太大了,想稍微点赞延迟稍微往官网上靠一下

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
调用前须知看了吗

**Comment by 1144790758** [comment]
看了须知了,调用相同接口,访问相同的url会被缓存只会发一次向网易请求,所以我所以点赞请求都是加了时间戳的

破案了:既然确实发送了向网易的点赞请求,那么再次获取最新评论也必须是最新的,也要加时间戳.
我的,我的问题不够细
