### ISSUE TITLE
手动传cookie报301

### ISSUE THREAD

**Issue by 2659494057** [Binaryify/NeteaseCloudMusicApi#970]
第一次获取cookie，将这个cookie带入请求需要登录的接口，可正常使用，再次获取cookie，将最新的cookie带入请求需要登录的接口，返回301

**Comment by Binaryify** [comment]
post方式还是get方式

**Comment by Binaryify** [comment]
post的话注意url带上时间戳或者随机数，防止被缓存

**Comment by 2659494057** [comment]
> post方式还是get方式

Get方式

**Comment by Binaryify** [comment]
你咋调的

**Comment by 2659494057** [comment]
> 你咋调的,过程描述清楚,别人都没问题的

没用什么语言，直接浏览器访问。

访问登录接口，返回200和相应信息，复制cookie，带入签到接口，返回200，签到成功。

再次访问登录接口，返回200和相应信息，再次复制cookie，带入签到接口，返回301。

再换回前一个获取的cookie，返回重复签到

就这样。

**Comment by Binaryify** [comment]
时间戳带了吗

**Comment by 2659494057** [comment]
> 时间戳带了吗

时间戳是我登录的时间戳还是我签到的时间戳?

**Comment by Binaryify** [comment]
都带上，时间戳每次都得变化，防止被缓存
