### ISSUE TITLE
电台订阅者的详情接口好像没有

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#971]
**功能描述**
歌单的收藏者详情有，电台的订阅者好像没有

**Comment by Binaryify** [comment]
是对应客户端的哪个位置的，有截图吗

**Comment by gyjcode** [comment]
![Uploading 12121.png…]()

**Comment by Binaryify** [comment]
你这个图片没上传完，看不了

**Comment by gyjcode** [comment]
![12121](https://user-images.githubusercontent.com/45870098/96224288-e7620e80-0fc1-11eb-9b62-e106bdc3d525.png)

**Comment by Binaryify** [comment]
好，晚点看看

**Comment by Binaryify** [comment]
好了，加上了

**Comment by gyjcode** [comment]
> 好了，加上了

感谢

**Comment by gyjcode** [comment]
> 好了，加上了
我重新下载的好像不行

**Comment by Binaryify** [comment]
不行?
![image](https://user-images.githubusercontent.com/12221718/96267592-90c4f680-0ffa-11eb-8f1a-f8861843c324.png)

**Comment by gyjcode** [comment]
> 不行?
> ![image](https://user-images.githubusercontent.com/12221718/96267592-90c4f680-0ffa-11eb-8f1a-f8861843c324.png)

额，我再重新下载试下
