### ISSUE TITLE
电台 - 节目 接口 文字电台内容简介有，图片简介好像没有获取到

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#977]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
问题截图
![10-17-04](https://user-images.githubusercontent.com/45870098/96326487-a4f10e00-1063-11eb-8215-3173c3b5229e.png)
![10-17-01](https://user-images.githubusercontent.com/45870098/96326488-a6bad180-1063-11eb-90f0-1958d8452948.png)
![10-17-02](https://user-images.githubusercontent.com/45870098/96326489-a7536800-1063-11eb-9bdf-06aa4bd2554d.png)
![10-17-03](https://user-images.githubusercontent.com/45870098/96326490-a8849500-1063-11eb-9f14-375b2b329c97.png)

## 重现步骤
/dj/paygift

## 期待效果
<请清晰描述现在的效果和期待的效果>  

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
接口更新了,但是数据结构有变化

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/96329693-1f308b00-1082-11eb-919c-1334f77e4a7f.png)

**Comment by gyjcode** [comment]
> 接口更新了,但是数据结构有变化
> ![image](https://user-images.githubusercontent.com/12221718/96329701-26f02f80-1082-11eb-87ff-f678f56594aa.png)

好的，感谢

**Comment by gyjcode** [comment]
那个，想问一下，modules里面其他数据项目的type 对应的title 有对照的title数据吗？
![1211](https://user-images.githubusercontent.com/45870098/96331970-ff09c780-1093-11eb-9fe8-54e9cf21388f.png)

**Comment by Binaryify** [comment]
这个我也不知道,你得自己找对照

**Comment by gyjcode** [comment]
> 这个我也不知道,你得自己找对照

查到了，好像只有免费试听与最近更新没有，其他都有。谢谢

**Comment by Binaryify** [comment]
好
