### ISSUE TITLE
接口一直 pending 或 301

### ISSUE THREAD

**Issue by MichealXie** [Binaryify/NeteaseCloudMusicApi#978]
## 环境
- 系统/平台: mac

- nodejs 版本: 10.16.2

- API版本: 3.44.0

## 出现问题
接口一直 pending 或 301

## 重现步骤
拉取 git 仓库
npm install
demo.html 中填入手机号及密码
npm run start
打开 http://localhost:3000/test.html
打开网络tab
看到 pending

## 期待效果
接口正确返回

**Comment by wangzhen-CHN** [comment]
我的填入用户名密码可以登录成功
但是拿到token后 手动传入cookie获取用户信息返回301

**Comment by Binaryify** [comment]
有截图吗

**Comment by wangzhen-CHN** [comment]
> 有控制台和命令行截图吗
[图片](https://ftp.bmp.ovh/imgs/2020/10/088ded6d341f069c.png)
https://ftp.bmp.ovh/imgs/2020/10/088ded6d341f069c.png

**Comment by Binaryify** [comment]
这个是你自己搭的服务还是别人的

**Comment by wangzhen-CHN** [comment]
> 这个是你自己搭的服务还是别人的

自己搭的，找到问题所在了,正确用法是{url}?cookie=MUSIC_U=xxx

**Comment by wangzhen-CHN** [comment]
> 这个是你自己搭的服务还是别人的

感谢您的构件的这个项目，很好用

**Comment by MichealXie** [comment]
> 有控制台和命令行截图吗

[here](https://s1.ax1x.com/2020/10/19/0vqOEQ.png)

**Comment by MichealXie** [comment]
17年还是学生的时候就靠这个api搞了个前端项目, 借此找到一份还不错的工作, 感谢楼主, 一定程度改变了我人生的轨迹

**Comment by Binaryify** [comment]
@MichealXie 哈哈，互相成就互相成就

**Comment by Binaryify** [comment]
@MichealXie 命令行那边有报什么错吗

**Comment by MichealXie** [comment]
> @MichealXie 命令行那边有报什么错吗

[![0zVlYn.png](https://s1.ax1x.com/2020/10/19/0zVlYn.png)](https://imgchr.com/i/0zVlYn)

**Comment by Binaryify** [comment]
@MichealXie 你这就是装了乱七八糟的证书引起的

**Comment by Binaryify** [comment]
试试
```
export NODE_TLS_REJECT_UNAUTHORIZED=0
```
再重新运行

**Comment by MichealXie** [comment]
> @MichealXie 你这就是装了乱七八糟的证书引起的

感谢提示, 没想到是这个原因, 搜了一下直接  `NODE_TLS_REJECT_UNAUTHORIZED=0 npm run start` 就好了
