### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by Amren112** [Binaryify/NeteaseCloudMusicApi#980]
## 环境
- 系统/平台: windows、idea

- nodejs 版本: v12.14.1

- API版本: 3.44.0

## 出现问题
注册的时候填写了正确的手机号和验证码以及密码，直接返回验证码失败，用同样的验证码网页手动注册成功。

## 重现步骤
发送短信，然后获得验证码后直接调用注册接口即可

## 期待效果
程序手机号+验证码注册成功

**Comment by Binaryify** [comment]
周末看看

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/97079997-dbfa8d00-162a-11eb-85cc-035215a5cca5.png)
我这边没问题,你是POST还是GET方式调的,post的话每次请求url都得带个随机数或者时间戳,防止接口被缓存

**Comment by Amren112** [comment]
谢谢，我在看看，您那边没问题的话。API应该没问题
