### ISSUE TITLE
首页>最新音乐>新碟上架 返回的本周新碟数据好像不对

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#981]
## 环境
- 系统/平台: <你的系统和平台>

- nodejs 版本: <你的 NodeJS 版本号>

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题
之前 /top/album 有本周新碟数据来着，现在好像没有了

![新碟上架3](https://user-images.githubusercontent.com/45870098/96445213-1ab2d080-1242-11eb-883a-3f6f26e511e4.png)
![新碟上架1](https://user-images.githubusercontent.com/45870098/96445228-20101b00-1242-11eb-8bea-2fc608d53edf.png)
![新碟上架2](https://user-images.githubusercontent.com/45870098/96445230-21414800-1242-11eb-9476-481ee8c4add9.png)

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by gyjcode** [comment]
首页最新音乐（推荐新音乐接口）目前为12首歌曲了。

**Comment by Binaryify** [comment]
周末看看

**Comment by Binaryify** [comment]
top_album.js
可以把 rcmd 设为true，这样就有周的数据了，其他的我周末再更新

**Comment by Binaryify** [comment]
已修复

**Comment by gyjcode** [comment]
> 已修复

感谢
