### ISSUE TITLE
在服务器上运行，好多接口出错

### ISSUE THREAD

**Issue by Yousaisai** [Binaryify/NeteaseCloudMusicApi#984]
服务器打开这个api接口出错

**Comment by Binaryify** [comment]
大佬，你把我模板都删了，也不提供任何错误信息，我又不是神仙，光凭“在服务器上运行，好多接口出错” 这句话就能直接读取你服务器上出什么错

**Comment by Yousaisai** [comment]
首先感谢您写了这个文档，我是渣渣，我的意思是说，在本地运行我暂时所有接口都是对的，但是在在服务器上直接启动3000，就会有部分接口出错。显示404，或者有的提是参数错误，其实这个接口压根没有参数
