### ISSUE TITLE
首页-发现-圆形图标入口列表

### ISSUE THREAD

**Issue by chenxi24** [Binaryify/NeteaseCloudMusicApi#988]
## 环境
- 系统/平台: <win10>

- nodejs 版本: <10.15.3>

- API版本: <3.44.0>

## 出现问题
<首页-发现-圆形图标入口列表接口返回值是空数组>

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/96839440-c98e2100-147b-11eb-8bbe-89a1d88a77c9.png)

**Comment by chenxi24** [comment]
![image](https://user-images.githubusercontent.com/40349890/97011673-92059e80-1579-11eb-9de1-e993d1e11fd4.png)

**Comment by chenxi24** [comment]
我为什么没有值呢？

**Comment by chenxi24** [comment]
这个接口怎么用啊，我http://localhost:3000/homepage/dragon/ball确实没有值

**Comment by Binaryify** [comment]
登录了吗

**Comment by Binaryify** [comment]
好了,加了匿名登录了
