### ISSUE TITLE
<不理解 首页-发现 /homepage/block/page 该接口返回的数据中action的含义和用途>

### ISSUE THREAD

**Issue by ZhangFan-1999** [Binaryify/NeteaseCloudMusicApi#989]
## 环境
- 系统/平台: <win10>

- nodejs 版本: <v13.12.0>

- API版本: <3.44.0>

## 出现的问题： 
不理解 `首页-发现 /homepage/block/page` 该接口返回的数据中`action`的含义和用途
例如：`action: "orpheus://playlistCollection?referLog=HOMEPAGE_BLOCK_PLAYLIST_RCMD"`
action后面的字符串有什么用途呢？
## 期待效果
想要理解这个action字段的用途，并继续完成我的项目。期望您能回答我这个小白的问题，谢谢！！！

**Comment by Binaryify** [comment]
那个是原生APP的页面url

**Comment by ZhangFan-1999** [comment]
那要在什么场景下使用这个url？
这个和普通的url例如：avatarUrl": "http://p1.music.126.net/Z_em8hU略两者的区别是什么呢？

**Comment by Binaryify** [comment]
那个只有在客户端才能调的

**Comment by ZhangFan-1999** [comment]
哦哦，知道了，麻烦您了！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Binaryify/NeteaseCloudMusicApi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 晚上10:12
收件人:&nbsp;"Binaryify/NeteaseCloudMusicApi"<NeteaseCloudMusicApi@noreply.github.com&gt;;
抄送:&nbsp;"好家伙三子"<2071616646@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Binaryify/NeteaseCloudMusicApi] <不理解 首页-发现 /homepage/block/page 该接口返回的数据中action的含义和用途&gt; (#989)





 
那个只有在客户端才能调的

**Comment by Binaryify** [comment]
https://sharecuts.cn/app/590338362
