### ISSUE TITLE
无法收藏/取消收藏歌手

### ISSUE THREAD

**Issue by qier222** [Binaryify/NeteaseCloudMusicApi#994]
## 环境
- 系统/平台: macOS Catalina

- nodejs 版本: v14.8.0

- API版本: v3.45.1

## 出现问题
发送收藏/取消收藏歌手请求时返回错误信息，并且网易云那边收藏的歌手数据没有变化。

## 重现步骤
收藏歌手，发送请求 `curl -X "POST" "http://127.0.0.1:3000/artist/sub?artistId=12024301&t=1"` ，返回
```json
{
  "msg": "参数错误",
  "code": 400{
    "msg": "参数错误",
    "code": 400
  }
}
```

取消收藏歌手，发送请求 `curl -X "POST" "http://127.0.0.1:3000/artist/sub?artistId=12024301&t=0"`，返回
```json
{
  "msg": "readObject出错：class:java.util.List<java.lang.Long> json:[undefined]",
  "code": -1
}
```
## 期待效果
希望能正常收藏/取消收藏歌手

**Comment by Binaryify** [comment]
文档写的有问题，应该是id不是artistId
